### ISSUE TITLE
Application form not showing

### ISSUE THREAD

**Issue by MyPhysioJob** [Automattic/WP-Job-Manager#1001]
I had been able to click on the "Apply for Job" button and it would cause the Application form to pop up.

Today there is nothing happening when I click on the button/

This is this error in the console which might help but is another language to me!

![image](https://cloud.githubusercontent.com/assets/29032416/26537354/d5d46602-4492-11e7-92bc-6a51f1a0c99d.png)

Thank you for your help!

**Comment by jom** [comment]
This looks like an issue with your theme (Jobify). The JavaScript error that pops up is coming from your theme.
Astoundify support: https://astoundify.com/support/?envato_item_id=5247604
