### ISSUE TITLE
Placeholder doesn't work for job_description field

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#1003]
If you set a placeholder for 'job_description' here:
https://github.com/Automattic/WP-Job-Manager/blob/master/includes/forms/class-wp-job-manager-form-submit-job.php#L200

... it doesn't display in the form:
![image](https://cloud.githubusercontent.com/assets/1990037/26591327/36de89c4-4555-11e7-859d-6f145e35159a.png)

3236421-t

**Comment by jom** [comment]
I don't think we can add placeholders inside the WP editor.

**Comment by danjjohnson** [comment]
Cool. Should we build it into core? If not, maybe we should remove the placeholder field from https://github.com/Automattic/WP-Job-Manager/blob/master/includes/forms/class-wp-job-manager-form-submit-job.php#L200 to avoid confusion.

**Comment by tripflex** [comment]
@jom yup that would be correct, i can submit a PR with it included if you guys want 👍

**Comment by tripflex** [comment]
@jom did you want me to submit a PR with this integrated into core?

**Comment by jom** [comment]
@tripflex For now, let's leave additional WP editor hacks out of WPJM core, especially with the [rapid development](https://make.wordpress.org/core/tag/gutenberg/) of the next gen of the WP editor. I'm in favor of taking out the reference to the placeholder on WP editor fields.

**Comment by tripflex** [comment]
@jom yeah no worries, I agree though, probably best to just remove placeholder and be done with it ... don't know anybody that has used it, or honestly even asked about it before (what I put together was for another personal project)
