### ISSUE TITLE
Can't filter submit_job_form_required_label without throwing a warning

### ISSUE THREAD

**Issue by piersb** [Automattic/WP-Job-Manager#1010]
When debug is turned to true and a user is not logged in, trying to submit a job and filter on submit_job_form_required_label will result in a warning.

#### What I Expected To Happen

No warnings

#### What Happened Instead

![screen shot 2017-06-02 at 14 02 11](https://cloud.githubusercontent.com/assets/1419092/26728456/3520b8ce-47a2-11e7-81f9-756c2a13245b.png)

#### Steps to Reproduce the Bug

- Create fresh install
- Install plugin
- Add the following filter to functions.php

```
add_filter( 'submit_job_form_required_label', 'test_label_function', 10, 2 );

function test_label_function( $tag, $field ) {

    // do some things

	return $tag;
}
```

Pull request with fix to follow.

**Comment by piersb** [comment]
Hmp, opening a pull request creates a new issue apparently. This is now a dupe of #1011. Closing.

**Comment by tripflex** [comment]
Technically this isn't necessary as all you need to do to prevent that from being output is to define the second argument in your function, like so:

```php
add_filter( 'submit_job_form_required_label', 'test_label_function', 10, 2 );

function test_label_function( $tag, $field = false ) {

    // do some things

	return $tag;
}
```

But this does fix the core codebase from calling a filter without the same arguments each time
