### ISSUE TITLE
Listing My Services in 3 columns instead of 1

### ISSUE THREAD

**Issue by guito26** [Automattic/WP-Job-Manager#1012]
#### Steps to Reproduce the Bug

I would like to list my services in 3 columns on resume. How can I do that?
Thanks

**Comment by volodymyrpekh** [comment]
@guito26 You have to edit template file to achieve 3 columns layout. Simply copy template file to your child theme and edit it. Any wordpress developer/designer can do that if you don't know how. 

P.S. This is not a support forum.
