### ISSUE TITLE
I can't view added jobs in my page

### ISSUE THREAD

**Issue by pbharathiraja** [Automattic/WP-Job-Manager#1016]
I have installed latest version and added jobs in my admin dashboard. I pasted the shortcode [jobs] in my page. While viewing my page, but there is no jobs listed in that page. I attached the screenshot what I am seeing.

Please help me.
![screenshot-website 2017-06-08 14-33-40](https://user-images.githubusercontent.com/29274193/26920956-320c30b8-4c58-11e7-9c7c-7a1b12eb4b87.png)

**Comment by jom** [comment]
Hi there! For support requests, please visit:
https://wpjobmanager.com/support/
https://wordpress.org/support/plugin/wp-job-manager
