### ISSUE TITLE
404 error, documentation not helping

### ISSUE THREAD

**Issue by swdtrista** [Automattic/WP-Job-Manager#1019]
We installed wp-job-manager about two weeks ago and purchased the woo commerce add on (haven't activated it yet). 
We are having the 404 this page is not found error when clicking on job links. I was able have the plugin "reset" itself by deactivating and activating it a few times when this has happened, but when I did that today the error persisted after about 20 minutes.

From the documentation I have done:
- Ensure it is not a permalink issue by going to Settings > Permalinks from your WordPress dashboard and pressing the ‘save’ button
-Try disabling other installed plugins and then repeating (1). If it is a plugin conflict you can then either leave the problem plugin disabled or contact the author.

But cannot switch to the Twenty Twelve theme as our theme is custom and we can't afford the downtime. 
"Switch to the default Twenty Twelve theme to rule out a conflict, again repeating (1) after doing so."

Is there anything else that we can do, otherwise we are unable to use this plugin.

Thank you, this is very urgent if our partners cannot see their jobs posted it would be a huge deal.
https://www.sidewalkdog.com/jobs-and-volunteer-opportunities/

**Comment by tripflex** [comment]
Hi there! For support, please visit:
https://wpjobmanager.com/support/
https://wordpress.org/support/plugin/wp-job-manager

If it works when you deactivate and then reactivate the plugin, that leads me to believe that when plugin is activated it flushes the rewrite rules, which is the same as when you click save in the permalinks settings.

When you go to permalink settings and click save, does it work after doing that?

Check your `.htaccess` file and see what is inside of it (and post in the support thread you create on the support forum)

**Comment by swdtrista** [comment]
Hi, thanks for the quick response.

I've tried the permalink settings, saving it does nothing. I also can't find the .htaccess file, withing the ftp and wp install can you direct me at all where to look?

Thanks!

**Comment by swdtrista** [comment]
Just kidding, had invisible files hid apparently.  
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress
