### ISSUE TITLE
Automatic Listing Duration isn't working anymore

### ISSUE THREAD

**Issue by Liptonicer** [Automattic/WP-Job-Manager#1028]
Dear team, 

since the last update the automatic job-duration no longer works. New jobs no longer receive the automatically specified job-duration. The Job Manager has a certain duration. However, this period is no longer set automatically for new job offers.

Best wishes from germany
Sebastian

**Comment by jom** [comment]
I am unable to reproduce. Are you using any WPJM plugins? If so, which ones?

**Comment by Liptonicer** [comment]
I'm using following Plugins:

1.) WPJM - Extended Locations
2.) WPJM - WooCommerce Paid Listings
3.) WPJM - Field Editor
4.) WPJM - Client-Side Geocoder
5.) WPJM - Registration Use Email

**Comment by jom** [comment]
I can only speak to the second one in terms of conflicts made in the last release. Are these listings being added using a job package subscription? If so, what is the subscription type? If it is linked to the listing, job expiration is always cleared (it uses the subscription itself).

**Comment by Liptonicer** [comment]
I think that was the problem! Thanks a lot! I think I could solve the problem...
