### ISSUE TITLE
Using custom template for RSS feed

### ISSUE THREAD

**Issue by Irpe1337master** [Automattic/WP-Job-Manager#1029]
#### What I Expected To Happen
Tried to use custom RSS feed template for Job Manager RSS feed. Followed instructions given here https://codex.wordpress.org/Customizing_Feeds . 

#### What Happened Instead
Nothing happened so I dived into the code and noticed that  in “**class-wp-job-manager-post-types.php**” file on line 370, a function “**do_feed_rss2()**” is called directly. 

Maybe this function could be called using ‘**do_action(“do_feed_rss2”, false);**’? Then it would be possible to change RSS template as instructed in the codex.

**Comment by Irpe1337master** [comment]
Any update on this issue? :)

**Comment by jom** [comment]
For now, I'd recommend replacing the `job_feed` feed altogether.
```
remove_all_actions( 'do_feed_job_feed' );
add_feed( 'job_feed', 'your_custom_job_feed_func' );
```
