### ISSUE TITLE
.htaccess file 

### ISSUE THREAD

**Issue by swdtrista** [Automattic/WP-Job-Manager#1030]
BEGIN WordPress

RewriteEngine On RewriteBase / RewriteRule ^index\.php$ - [L] RewriteCond %{REQUEST_FILENAME} !-f RewriteCond %{REQUEST_FILENAME} !-d RewriteRule . /index.php [L]
END WordPress

> > From : tripflex 
> > If it works when you deactivate and then reactivate the plugin, that leads me to believe that when plugin is activated it flushes the rewrite rules, which is the same as when you click save in the permalinks settings.
> 
> When you go to permalink settings and click save, does it work after doing that? **It does nothing to reset, only deactivating then reactivating works**
> 
> Check your .htaccess file and see what is inside of it (and post in the support thread you create on the support forum) **pasted above**
> 

We installed wp-job-manager about two weeks ago and purchased the woo commerce add on (haven't activated it yet).
We are having the 404 this page is not found error when clicking on job links. I was able have the plugin "reset" itself by deactivating and activating it a few times when this has happened, but when I did that today the error persisted after about 20 minutes.

From the documentation I have done:

Ensure it is not a permalink issue by going to Settings > Permalinks from your WordPress dashboard and pressing the ‘save’ button
-Try disabling other installed plugins and then repeating (1). If it is a plugin conflict you can then either leave the problem plugin disabled or contact the author.
But cannot switch to the Twenty Twelve theme as our theme is custom and we can't afford the downtime.
"Switch to the default Twenty Twelve theme to rule out a conflict, again repeating (1) after doing so."

Is there anything else that we can do, otherwise we are unable to use this plugin.

Thank you, this is very urgent if our partners cannot see their jobs posted it would be a huge deal.
https://www.sidewalkdog.com/jobs-and-volunteer-opportunities/f you're requesting a new feature, explain why you'd like it to be added.
-->

**Comment by jom** [comment]
Please visit https://wpjobmanager.com/support/ for support. Include the name of your theme in your support ticket (from that site).
