### ISSUE TITLE
WooCommerce Paid Listings - Job Package Subscriptions reverts to Simple Subscriptions

### ISSUE THREAD

**Issue by razwan** [Automattic/WP-Job-Manager#1031]
The issue is fairly simple. There is no way to set a **Product Type** to **Job Package Subscription**. 
After you click Publish or **Update**, the value for the Product Type dropdown will always default to **Simple Subscription**.

**Comment by jom** [comment]
That should be fixed in 2.7.2. Please make sure you've updated to the latest version.
