### ISSUE TITLE
Introduce Deprecation File

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#1035]
As discussed in https://github.com/Automattic/WP-Job-Manager/pull/1033 we should slowly start  deprecating non-prefixed or incorrectly prefixed functions. The first step is to have a place to put these.

**Comment by jom** [comment]
Introduced in #1014; Closing for now, but should be used while implementing #1034 and future deprecations from `wp-job-manager-functions.php` and `wp-job-manager-template.php`
