### ISSUE TITLE
Job not expired after the closing date pass

### ISSUE THREAD

**Issue by angelirc** [Automattic/WP-Job-Manager#1037]
In the joblist, i always see closed jobs

I check the option - Enable automatic expiration for Automatic deadline expiry.
I check the cron Schedule
I see the expire date is ok in the jobs board but the statut not write expired

The jobs write closed buy always stay in the jobslist.

I have another problem - The jobs closed with the UTC universal default time and not the time zone then i set in the Wordpress

Thanks  to help me!

**Comment by spencerfinnell** [comment]
Duplicate https://github.com/Automattic/WP-Job-Manager/issues/983 https://github.com/Automattic/WP-Job-Manager/issues/919

**Comment by angelirc** [comment]
Finally is because i use wp all import. I make a function to convert the date and now they Work

<?php
function date_convert($x){
	$timestamp = strtotime ($x);
	$new_date= date ("Y-m-d", $timestamp);
return $new_date ;
}
