### ISSUE TITLE
Resume add-on -> Application notification is send with FROM email address of candidate

### ISSUE THREAD

**Issue by Lens40** [Automattic/WP-Job-Manager#1038]
As the title says in line 187 of wp-content/plugins/wp-job-manager-resumes/includes/class-wp-resume-manager-apply.ph it is coded that the emails should be send with the candidate email address in the email header. The issue s that in most cases it will not be accepted by most servers as usually your server is not allowed to send emails in the name of the candidates domain (Gmail, Yahoo, Hotmail are quite strict on that which is good!). Most or all mailing services also refuse to send from an not authenticated FROM-address. So I guess it would make sense to use the noreply@ for the FROM address and use the Reply-to to set the candidate email as done in the application plugin.

My suggestion ist to update this piece of code.

Change: 
`$headers[] = 'From: ' . $candidate_name . ' <' . $candidate_email . '>';`

To: 
`$headers[] = 'From: ' . get_bloginfo( 'name' ) . ' <noreply@' . str_replace( array( 'http://', 'https://', 'www.' ), '', site_url( '' ) ) . '>';`

**Comment by jom** [comment]
We could shift it to `Reply-to` and remove the `From` header entirely (that will cause WordPress to use its default).

**Comment by Lens40** [comment]
Its also an option.

**Comment by Lens40** [comment]
The reply-to part already exists, so you would just need to remove the code for the header address. I just noticed because many of my customers did not receive any of the notifications when the candidates applied with their resume.

**Comment by tripflex** [comment]
Yeah looks like that's the way the applications addon handles it, by setting the Reply-to in the headers to the candidate email

**Comment by jom** [comment]
Closing this as it is a plugin issue. I'd recommend using the `apply_with_resume_email_headers` filter.
