### ISSUE TITLE
Closed Jobs use UTC universal hour and not the local hour

### ISSUE THREAD

**Issue by angelirc** [Automattic/WP-Job-Manager#1039]
I setting the local hour in the WordPress but the hour to closed a job is use the universal hour.
I stay in Canada and the job closed at 20 h and not a midnight.

**Comment by spencerfinnell** [comment]
Duplicate https://github.com/Automattic/WP-Job-Manager/issues/983 https://github.com/Automattic/WP-Job-Manager/issues/919 https://github.com/Automattic/WP-Job-Manager/issues/1037

**Comment by angelirc** [comment]
You close the Issue because of duplicate, but is not the same.  
The other is not because of UTC universal hour????????

**Comment by spencerfinnell** [comment]
Fixing https://github.com/Automattic/WP-Job-Manager/issues/919 will solve the issue if your website's timezone is set to UTC.

**Comment by jom** [comment]
@angelirc Can you verify the timezone is set correctly in WP Admin > Settings > General?

**Comment by angelirc** [comment]
The Deadline application don't use the default time in WP Admin > Setttings > General.
Finally i change the «UTC default time zone» in wp-settings.php
date_default_timezone_set( 'America/New_York' );

**Comment by jom** [comment]
This is for the applications deadline plugin? If so, I think I can see what is going on. I'll track the issue in our repo for that plugin.
