### ISSUE TITLE
Job submit

### ISSUE THREAD

**Issue by Vigoempleo** [Automattic/WP-Job-Manager#1040]

**Comment by spencerfinnell** [comment]
You have a javascript error in your theme or in one of your plugins. Switch themes and try. If it works it's your theme. If it doesn't disable your plugins one at a time and try.

**Comment by Vigoempleo** [comment]
I will try but I don't understand because I didn't change anything...

**Comment by Vigoempleo** [comment]
You were right it was a plugin... Thank you very much for your help

**Comment by Vigoempleo** [comment]
How can I close this issue?
