### ISSUE TITLE
Guest ajax file upload issues after 1.26.2 update

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1043]
With the patch added in #1020, any themes, plugins, or users that have their own `file-field.php` template override files (which is a lot of them, if not the majority of users), **_will have problems with ajax uploads for any guest users (not-logged in users)_**.

The problem stems from relying on the function call to check in the template file, if it should be loaded as an ajax file upload field.

Almost every theme and plugin defaults to ajax upload as it has the best user experience, and because of that, if they have not updated their template overrides (which I don't think any have yet), it will still load as ajax for any guest user.

When the guest user attempts to upload a file it will fail silently in the background, as the jQuery handling only handles ajax errors, not an error sent by WP.

_IMO this is a major issue as chances are it will be very widespread_, i'll submit my PR to fix this in just a minute

**Comment by spencerfinnell** [comment]
What about instead of adding the function check to the template file a filter is added that loops through registered fields and adjusts the `ajax` parameter of the registered `file` fields accordingly?

**Comment by tripflex** [comment]
@spencerfinnell yup did you see my comment in the Slack chan?  That's what I think would probably be the best way to handle it, just need to test and figure out to make sure.

The PR I just submitted fixes the error failing silently in the background, but I do agree, I think we need to come up with a solution for this, outside of the template override file.

**Comment by jom** [comment]
@tripflex did #1044 fix this issue? If not, mind providing more info on what issues remain in WPJM core?

I know there could be issues with custom `file-field.php` templates, but hopefully those get updated.

**Comment by jom** [comment]
Closing for now. Feel free to comment if it is still an issue.
