### ISSUE TITLE
Show all jobs when checkboxes are all checked and unchecked

### ISSUE THREAD

**Issue by annezazu** [Automattic/WP-Job-Manager#1050]
Brought up in 3271080-t.

If you uncheck all options for the job search, no jobs show: https://cloudup.com/ceSKAfz_6gP
Tested this on sandbox and can confirm say thing happens: https://cloudup.com/c36dKuwpnat

This flow is confusing - you'd expect to be able to uncheck everything and have items still show. Is this logic we can implement so that if all items are checked or unchecked, results still appear?

**Comment by jom** [comment]
Going to close this and have it inform our new jobs block (#1287). There should be a way we can implement this and have it be more intuitive.
