### ISSUE TITLE
Listable / Wp Job Manager products not displaying correctly

### ISSUE THREAD

**Issue by AllARTSoftworks** [Automattic/WP-Job-Manager#1055]
Hi, I’ve got a problem with my WordPress website. We installed Listable and Wp Job Manager and got no problems until now.

My issue is the following: in our page containing [submit_job_forms] shortcode SOME users can view all the products (job packages) and others can’t view them.

In addition to this, nobody, neither admins or other roles, can add a new job package.

WordPress core and every plugin / theme are updated to the last version.

We already disabled every plugin to test any conflict.

I’ve searched into any possibile configuration for a setting concerning this problem, with no luck.

I’ve also dig into code and wp_postmeta to search for a solution…. nothing found.

Now we do want to buy a new license to obtain support but we don’t know if it’s a theme or a plugin issue.

Can anyone help me?

**Comment by tripflex** [comment]
This wouldn't have anything to do with core WP Job Manager.

You should request support for this from Astoundify, the developers of WP Job Manager Products.

**Comment by spencerfinnell** [comment]
The Products plugin does not control anything for the job packages during submission. 

Try disabling Listable. Do your packages show?

**Comment by tripflex** [comment]
@spencerfinnell ahhh so he may be talking about WooCommerce Paid Listings then?  His title has the Products plugin in it so I assumed that's what he was talking about ... 

@AllARTSoftworks can you please clarify what specifically you're talking about.  

Are you referring to the package selection BEFORE going to the page to fill in job details OR are you talking about the dropdown that shows ON the submit form to select products from?

**Comment by AllARTSoftworks** [comment]
@tripflex sorry, my question was unclear. I am referring to the package selection BEFORE going to the page to fill in job details. 

Our website uses Listable theme and WP Job Manager to create packages that users can buy in order to open an account on our pages. From this point they can be able to have a simple shop window or an ecommerce side (sort of). 

This isn't the canonical use of the theme and the plugin I assume, but I succeeded the first webmaster so I am not fully aware of choices made before my arrival and must take the previous work "as is". 

Now I'll try to disable Listable theme as suggested, let's see if the problem is over there. I'll report here the results of my attempts.

Thank you for your attention.

**Comment by AllARTSoftworks** [comment]
As you suggested, the problem is into Listable theme. I tried with another theme and every package becomes suddenly visibile to every user. I'll try to debug accordingly, thank you for your support and sorry for my OT and lack of clearness.
