### ISSUE TITLE
Loading spinner or some other status indicator on submit/preview

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1056]
https://wordpress.org/support/topic/suggestion-add-spinner-or-status-indicator-to-form-submission/

Now that AJAX uploads are disabled for guest users, it may be a good idea to add some type of spinner or some type of user feedback (maybe like WC does on checkout?) to let the user know that the upload is processing?

Thoughts? Ideas?

**Comment by joewa1980** [comment]
Any news on this? It's pretty essential as the form submission can sometimes take some time depending on current site load etc., and it occasionally results in site abandonment or confusion.

**Comment by tripflex** [comment]
@joewa1980 looks like @jom has already put in a PR for this, looks like it's planned to be released with version 1.30.0
