### ISSUE TITLE
Add recaptcha to job submission

### ISSUE THREAD

**Issue by bikedorkjon** [Automattic/WP-Job-Manager#1057]
re: https://wordpress.org/support/topic/he-form-to-place-a-job-is-not-secure-enough/

I think it's a bit silly this has not been added as an option for a users. Can we add this in the next release especially since most of the code has already been generated here: https://wpjobmanager.com/document/tutorial-adding-recaptcha-job-submission-form/

**Comment by tripflex** [comment]
Please keep me in the loop if you guys do decide to integrate this, as my field editor has full integration with reCAPTCHA including advanced customizations ... just want to make sure there aren't any conflicts 😛
