### ISSUE TITLE
Job duration isn't working correctly

### ISSUE THREAD

**Issue by Liptonicer** [Automattic/WP-Job-Manager#1059]
Hey guys,

I've wrote for few days and thought I could solve the problem. But it isn't so :-(

The possibility to set a fix duration for listings isn't working. When I open in the backend a listing, the date of the duration is using the actually time. When I set the time manually to another date and open the listing in the backend again, the counter is jumping to the actually date.

Also when I'm setting the date for 62 days, new listing didn't get the date automatically.

I'm using the Listify-Theme with the following plugins:

- WP Job Manager
- WP Job Manager - Extended Location
- WP Job Manager - WooCommerce Paid Listings
- WP Job Manager - Client-Side Geocoder
- WP Job Manager - Field Editor

Can you help me?

Best wishes from germany
Sebastian

**Comment by Keesdew** [comment]
I have the same problem for a few weeks. 
Using:
WP Job Manager
WP Job Manager - WooCommerce Paid Listings
on
[https://salonvacatures.nl]

Best wishes form Holland, Gelderland

Kees

**Comment by Keesdew** [comment]
See this post: https://github.com/Automattic/WP-Job-Manager/issues/1054

**Comment by jom** [comment]
Fixed with #1078 for issue #1054
