### ISSUE TITLE
WP Job Manager Version 1.26.2  displays Listify theme (Plans) as Jobs

### ISSUE THREAD

**Issue by TreasureValley** [Automattic/WP-Job-Manager#1061]
#### I expect my subscription plans to display like in this image.
![plan displayed correctly](https://user-images.githubusercontent.com/29758507/27649319-44540d20-5be6-11e7-8d45-033d8fc299b5.png)

#### What Happened Instead is they display like this with job references.
![plans display jobs](https://user-images.githubusercontent.com/29758507/27649472-b8eaec30-5be6-11e7-8efc-86c55fcdb011.png)

**Comment by spencerfinnell** [comment]
As mentioned in the support ticket the string will be updated to "listing" in the next release of the theme. 

Are you only concerned about the nouns in the string or the notice appearing at all?

**Comment by TreasureValley** [comment]
I would like the "You are editing an existing job. Create A New Job" text to be removed or hidden.

**Comment by spencerfinnell** [comment]
You will need to modify this template file https://github.com/Automattic/WP-Job-Manager/blob/master/templates/job-submit.php and remove lines 11-15

https://wpjobmanager.com/document/template-overrides/

**Comment by TreasureValley** [comment]
Thank you Spencer, that allowed me the ability to modify it as desired.
