### ISSUE TITLE
Candidate Notification Email Error / How to Attach "File" to Employer Notification Email

### ISSUE THREAD

**Issue by ryankhong** [Automattic/WP-Job-Manager#1062]
Hi there,

My account hello@wordofmouthagency.com.au can’t seem to access the Support Forum.

I have a issue with the “Candidate Notification”. I would like to attach a message and image into this but everytime I add anything into the field the Form cannot submit properly. See screenshots:

 
![1](https://user-images.githubusercontent.com/29768231/27672029-c2f36e02-5cca-11e7-977d-3896f9b17f48.jpg)

Only when I add any text into the Candidate Notification then this error “Invalid address: (setFrom)” pops up on the Job when I try to submit. 

![2](https://user-images.githubusercontent.com/29768231/27672053-e0b67d4e-5cca-11e7-9d67-bf3e3c0c1a32.jpg)

::

My next question is how do you attach a “File” field to the Employer Notification Email? So when the employer receives the email all attachments are already attached within the email.

Thanks 
Ryan

**Comment by tripflex** [comment]
This means the outgoing email address is invalid, that error is from the PHPMailer used by WordPress to send the email.

Either you did not fill in the email address in the form field with the `from_email` rule, the email was invalid, or idn not supported on your site and you used an idn email address.

You can't attach a file using the core email handling, but you can use the meta key and output the link to the file.

The other option would be to use my Emails addon which will allow you to attach the file to the email
https://plugins.smyl.es/wp-job-manager-emails/
