### ISSUE TITLE
Bug with wp-geo and indeed integration plugin + fix

### ISSUE THREAD

**Issue by RichardLindhout** [Automattic/WP-Job-Manager#1070]
#### What I Expected To Happen
When entering geocode: Beatrixlaan 2, 4694 EG Scherpenisse, Nederland
#### What Happened Instead
500 error or no results
#### Steps to Reproduce the Bug
Entering unsupported location

Possible solutions
Hande possible Exception from WP_Job_Manager_Geocode::get_location_data( $search_location ); on line
155 of `class-wp-job-manager-indeed-import.php`

Solution for no results:
Adding after line 188 following lines
```
if ( ! empty( $address_data['city'] ) ) {
 $search_location = $address_data['city'];
 }
```

Final code:

```
if ( $search_location && apply_filters( 'job_manager_indeed_geolocate_country', true ) ) {
    $address_data = WP_Job_Manager_Geocode::get_location_data( $search_location );
    if (!$address_data instanceof Exception) {
        if (!empty($address_data['country_short'])) {
            $search_country = $address_data['country_short'];
        }
        if (!empty($address_data['city'])) {
            $search_location = $address_data['city'];
        }
    }
}

```

**Comment by davoraltman** [comment]
3300961-t

**Comment by RichardLindhout** [comment]
@davoraltman ?

**Comment by davoraltman** [comment]
@RichardLindhout Just referenced a ticket you sent in for better tracking :)

**Comment by jom** [comment]
What version of the indeed plugin are you using? I don't see `city` ever being used in (`class-wp-job-manager-indeed-import.php`) and just has 133 lines. `WP_Job_Manager_Geocode::get_location_data` does return `false`|`WP_Error`. I'll add a request in the Indeed integration repo to better handle that.

Closing for now, but feel free to reply and I'll reopen.
