### ISSUE TITLE
Add Quick Edit option

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#1081]
Would be super cool to add the quick edit option to the backend so that the jobs can quickly be edited, just like the regular posts.

Came up in 599911-zd

**Comment by davoraltman** [comment]
It seems this exists already. closing.

**Comment by jvdhelder** [comment]
It is not available.
Edit. Show. Delete. are the options. No Quick Edit.

![image](https://github.com/Automattic/WP-Job-Manager/assets/25108948/00c8511f-6af1-4dbd-ada7-3c7bed5d0079)
