### ISSUE TITLE
NPM-based build/test/update process

### ISSUE THREAD

**Issue by pgk** [Automattic/WP-Job-Manager#1085]
echoing from @dbtlr 's comment at https://github.com/Automattic/WP-Job-Manager/pull/1083

> One comment I have is completely unrelated, but in looking at the testing instructions, it seems like we have some manual build instructions. It might be useful to match some of the standards the Jetpack team are using and use NPM commands to make updating, building, and testing require as little knowledge as possible.
> 
> I know we're not really using npm right now for anything else, but it is a tool that comes preloaded on most systems, so it is pretty easy to use as a loader.

**Comment by jom** [comment]
I've started this process by adding already-in-core's deploy tasks to Grunt.

**Comment by jom** [comment]
Fixed by #2052
