### ISSUE TITLE
Featured listing not being updated!

### ISSUE THREAD

**Issue by Gnodesign** [Automattic/WP-Job-Manager#1088]
Hello,

Thank you for this great plugin.
I have been developing a job board theme with your plugin + all premium addons.

It was working great and i was ready to publish it but after WordPress updated to 4.8 the featuring listing feature doesn't work anymore.
I check the "Featured Listing" Option and when i click on update it refreshes and the "Featured Listing" option is still unchecked.

Tried it on Tweenty Fifteen to see if it was my themes fault but still doesnt work.

Hopefully this gets fixed soon.

Regards,
Gino

**Comment by masteradhoc** [comment]
@Gnodesign please tell me when the theme is ready :)

**Comment by Gnodesign** [comment]
@masteradhoc Will let you know for sure. :)

**Comment by Gnodesign** [comment]
@masteradhoc Hi, incase you are still interested in having a look in my theme you can check it out here:
https://themeforest.net/item/cariera-job-board-wordpress-theme/20167356

Have a nice day! :)

**Comment by masteradhoc** [comment]
@Gnodesign thanks looks very good. have you fixed the problem you're facing in this thread?

**Comment by Gnodesign** [comment]
Thank you, happy you liked it!

The theme works great and all of WP Job Managers features. The only issue is when i try to make a existing job into a featured one and update the page the job doesn't become featured. I'm still trying to figure it out.

Tried in on Twenty Fifteen too and the issue is still the same.

I will keep this thread updated in case I find a solution.

**Comment by Gnodesign** [comment]
@masteradhoc Everything is working fine now.
For some kind of reason the importer was interacting with the WP-Job Manager thats why the featured job didn't work on any theme.

The theme is working great now. :D
