### ISSUE TITLE
Carrier builder confirmed Word press API will not work

### ISSUE THREAD

**Issue by VNeni** [Automattic/WP-Job-Manager#1090]
#### What I Expected To Happen
when i give the API Key it should pull jobs 
#### What Happened Instead

I had contacted the Carrier builder and they confirm wordpress API will not work and they are suggested an different process.Please let me know how to fix it?  

#### Steps to Reproduce the Bug
go to API for CB and check even after giving the right API its not working

**Comment by kraftbj** [comment]
We no longer sell the CareerBuilder add-on since they locked down their API.
