### ISSUE TITLE
Collision between WP Jobs and Classifieds WP (Ajax method names)

### ISSUE THREAD

**Issue by Malaiac** [Automattic/WP-Job-Manager#1091]
#### Steps to Reproduce the Bug

Found this one https://github.com/Automattic/WP-Job-Manager/issues/680
which was closed.
The true problem is not these plugins share the same post type (they do not)
but they do use the same Ajax method name, the very specific "get_listings" method. 
That prevents WP Job Manager to display results on the main jobs page. 

To reproduce the bug : 
install WP Job Manger
install Classifieds WP
Enter some jobs offers and some classified ads.
Go to the front end jobs page. Inspect the XHR response.

Suggestion of resolution : 
Both plugins should use more specific names for their methods.

**Comment by tripflex** [comment]
I'm confused by this though ... why would you be using both of these plugins together on the same site, at the same time?

It's clear that the Classifieds WP plugin is just a fork of **_this_** plugin ... so there's not really any reason for us to change this ... if anything they should change it in their plugin as the code base they're using is WP Job Manager ....

https://plugins.trac.wordpress.org/browser/classifieds-wp/trunk?order=name

**Comment by Malaiac** [comment]
Why ? Because WP jobs manager does not manage classifieds ? :)
Didn't see that classifieds was a fork of wp jobs manager.
