### ISSUE TITLE
no auto update when you change "Posted by:" in Admin - job listing

### ISSUE THREAD

**Issue by CVgeek** [Automattic/WP-Job-Manager#1095]
#### What I Expected To Happen
If admin changes the "posted by:" to another employer profileID it should automatically update /change all details, including the company logo.
As sometimes webmasters need to create the job for those non technical hiring managers from small business. (you'd be surprised at how often this is requested...or they say to admin/ webmaster - please create the account for us )

#### What Happened Instead
nothing

#### Steps to Reproduce the Bug
no idea.

**Comment by jom** [comment]
Related to #1381. The fix for that will fix the new author not being able to see the listing. Unfortunately, the company info is stored with the job listing so that will need to be updated manually.
