### ISSUE TITLE
Multiple Job Type values don't get saved when editing

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#1097]
I have the option `Multi-select Listing Types` enabled in the settings. I go to the job submission page and I add a couple of job types to the listing and fill in the other details. I click on Preview and afterward on edit. All the other details I entered are saved properly, except for the job type which only has the first value I selected.

Came up in 602672-zen

**Comment by jom** [comment]
@davoraltman I'm not able to reproduce in 1.27.0. We added better support for _viewing_ multiple job types in the last version (before you could save them but they would only sometimes show up). If they're in most recent version and saving isn't working (go back to edit and first one is selected), then we can keep this open if we're able to reproduce.

PR #1014;
Issues: #854 & #928

**Comment by davoraltman** [comment]
@jom I was able to reproduce this on my test site - http://cld.wthms.co/OMYVv

1.27.0 version. I'm not sure why it's working for you [:D](http://bit.ly/2vtME36)

**Comment by spencerfinnell** [comment]
Can't reproduce either.

**Comment by jom** [comment]
Able to reproduced. When submitting a new job listing, click Edit Listing on the Preview step. I found the code and am putting together a quick fix.
