### ISSUE TITLE
Add Preview option on Edit job page

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#1098]
When editing a job via [job_dashboard], there's only the _Save Settings_ button. We could add the _Preview_ button there, just as it exists in the job submission flow.

Came up in 602778-zen

**Comment by jom** [comment]
Closing for now. If interest kicks up for something like this, it will be tricky. The reason this works for new listings is we save it in the DB with a post status of `preview`. However, we'd have to probably figure out how to use revisions for this.
