### ISSUE TITLE
New version makes functions no longer pluggable by themes

### ISSUE THREAD

**Issue by joelworsham** [Automattic/WP-Job-Manager#1103]
In the most recent versions of the plugin, 1.26.x, you included the `wp-job-manager-functions.php` file from within `WP_Job_Manager->include_template_functions()`. This meant themes could override any of those functions.

In 1.27.0, you don't do this anymore. Now you include `wp-job-manager-functions.php` in `WP_Job_Manager->__construct()`, so those functions are no longer pluggable by themes. This crashed my website because I override one of those functions in my child theme.

Why did you move the load order of this file? This is a huge change.

**Comment by jom** [comment]
Hi Joel! For permalinks we needed access to some of those functions earlier in the chain (`init`). 

I'll look into moving it back, but it'd be best to see if we can move out of function overriding. What function(s) are you overriding and are there any actions/filters we could add to WPJM core to prevent the need for that?

**Comment by joelworsham** [comment]
Understandable. I was overriding `wp_job_manager_notify_new_user()` and filling it simply with:

```
WC_Emails::instance()->emails['WC_Email_Customer_New_Account']->trigger(
    $user_id,
    $password,
    true
);
```

This way, the WooCommerce email would be used when a new user registers via WP Job Manager job submission.

**Comment by jom** [comment]
I can see how that could be a useful action. I'll add an enhancement request for it. In the meantime, 1.27.1 should allow you to override that function again.
