### ISSUE TITLE
Company logo not displayed on mobile

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#1106]
The company logo is not being displayed when `[jobs]` page is viewed on mobile.

Thanks for taking a look!

604526-zen

**Comment by spencerfinnell** [comment]
Which theme?

**Comment by davoraltman** [comment]
I was able to reproduce on Twenty Sixteen.

**Comment by davoraltman** [comment]
@jom Can you take a look at this one when you are back? Thanks!

**Comment by donnapep** [comment]
Looks like it was a conscious decision to hide the logo at smaller resolutions, probably to avoid breaking the layout - https://github.com/Automattic/WP-Job-Manager/blob/master/assets/css/frontend.less#L888. Do we want to show the logo at all resolutions now?

**Comment by davoraltman** [comment]
@donnapep I'd say we do. Let's see what others think.

cc @dbtlr @annezazu @bikedorkjon

**Comment by annezazu** [comment]
I have no real authoritative opinion :/ I wonder if a mobile dev or a dev who really understands mobile dev could offer an opinion. Mine would be offered on shaky ground.

**Comment by dbtlr** [comment]
I would need to evaluate some test cases to understand the pros and cons of showing vs hiding. @donnapep Do you think you could do some screenshots of this at various resolutions, with it shown and hidden, so we can see what it would look like?

**Comment by donnapep** [comment]
@dbtlr Sure thing.

Here's iPhone 6 with no images:

![iphone6-no-image](https://user-images.githubusercontent.com/1190420/29975457-656ef2bc-8f04-11e7-8264-5bcb8ee1c231.jpg)

iPhone 6 with images:

![iphone6-image](https://user-images.githubusercontent.com/1190420/29975462-6b71694c-8f04-11e7-9507-4dce4d1f9102.jpg)

iPad with images (which is what is shows currently):

![ipad-image](https://user-images.githubusercontent.com/1190420/29975476-81b06780-8f04-11e7-90ce-4181f45d6903.jpg)

So the smaller resolutions would need some work. It's not just a matter of turning the visibility of the image back on.

**Comment by dbtlr** [comment]
@donnapep Yeah, it seems like if we rearranged it to put the title on the top and the meta on the bottom, there would be plenty of room for the default style of have images in it on the left.

**Comment by jom** [comment]
Closing but should inform our work on the new jobs block (#1287)
