### ISSUE TITLE
Bulk Edit option doesn't show Job Title

### ISSUE THREAD

**Issue by annezazu** [Automattic/WP-Job-Manager#1109]
Brought up in [599911-zen](https://woothemes.zendesk.com/agent/tickets/599911)

If you try to bulk edit job listings, the job title shows as "no title":

<img width="604" alt="screen shot 2017-07-24 at 12 49 01 pm" src="https://user-images.githubusercontent.com/26996883/28541623-87f8383e-706e-11e7-82e4-5b27aebf7030.png">

We should show job title there from what I understand :)

**Comment by jom** [comment]
Interesting. The job title is really just a different label for the post title, which isn't included in WP's standard Bulk Edit for posts. I'm going to switch this over to an enhancement request for now. Looks like there are hooks that allow us to override this behavior:
https://codex.wordpress.org/Plugin_API/Action_Reference/bulk_edit_custom_box

**Comment by jom** [comment]
Closing for now, but if we get more requests we can re-open. I'm not sure how common this would be used.
