### ISSUE TITLE
Submission Form Not showing up

### ISSUE THREAD

**Issue by tstidotcom** [Automattic/WP-Job-Manager#1111]
On the site I am currently building, the "submit listing" option would send you to the store, and upon signing up for a subscription, would then kick you over to the submit job form.  Now when you sign up for a subscription, it simply takes you to an account dashboard, and no longer gives you the ability to post a job. If you go to the post a job page, the submission form will not show up. 
I have tried changing the page the form is set to in the "listings" settings and put the shortcode on the made up page to try to force it to show, and it still does not show up. Has anyone had this issue?

**Comment by tripflex** [comment]
Make sure you have all your pages configured in the Settings page ... but this is support for an addon plugin, which you should contact the developer of that plugin for support with this.

Please also make sure you follow the issue template when creating new issues, which has the following:

**PLEASE NOTE:**
- Try to add as much detail as possible. Be specific!
   _You did not provide any specific details as to what versions you're using, what addon you're using, etc._
- GitHub issues aren't for support! If you have questions, use this form: https://wpjobmanager.com/support/
