### ISSUE TITLE
Admin writepanel esc_html on label output

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1114]
Looks like the majority of outputs in the admin area are calling `esc_html` on any of the label values ... which is fine, except for when the user wants to define custom HTML inside the label, which is then output in the admin area.

![](https://smyl.es/img/SS_2017-07-25_07-40-40_PM2.png)

What are you guys thoughts on maybe switching this to something like `wp_strip_all_tags` to completely remove any HTML and only output string value?

The other option I was thinking of, would be to just add a method in the writepanels class that could be something like `self::esc_html()` which would call the core `esc_html` but pass it through a WPJM filter before doing so (that way I wouldn't have to do a `debug_backtrace()` just to see if WPJM is the one calling `esc_html`)

Thoughts?

https://github.com/Automattic/WP-Job-Manager/blob/master/includes/admin/class-wp-job-manager-writepanels.php#L295

**Comment by jom** [comment]
Using `wp_strip_all_tags()` seems to be an alright solution.
