### ISSUE TITLE
List Jobs Within Locations

### ISSUE THREAD

**Issue by thedecanus** [Automattic/WP-Job-Manager#1122]
New to GitHub - Not sure on the correct way to create a suggestion for a new feature but anyway here goes:

**List Jobs Within Locations**

I'd like to suggest creating a way for locations that are entered to have their own page that lists any jobs within them.

If a job listings location was entered into the post, then that location would then generate its own page. If the location did not exist beforehand then a new page would be created.

Alongside this feature, their could be a widget that displays the "Top Locations". A user could then select "x" amount of locations to show in a grid/list item format. Each location displayed would have the number of jobs posted within that location and would link through to the relevant locations pages.

**It could look something like this:**

London (120) - Southampton (240) - Portsmouth (30)

Manchester (25) - Liverpool (200) - Birmingham (55)

**Comment by jom** [comment]
Closing as stale. This should probably happen outside of core WPJM and in a third-party plugin with taxonomies.
