### ISSUE TITLE
No input allowed in description section

### ISSUE THREAD

**Issue by mbsc1993** [Automattic/WP-Job-Manager#1141]
#### What I Expected To Happen
I should be able to type in a job description when submitting a job, especially when it is a mandatory field. Job Posting link is: http://hubzoners.com/index.php/post-a-job/

#### What Happened Instead
I am not able to type anything in the required field, therefore, not allowing any job submissions. It was working a couple days ago flawlessly, but now people are having issues. I've tried updating every plug-in and removing ones I don't need.

#### Steps to Reproduce the Bug
N/A

**Comment by tripflex** [comment]
I am unable to reproduce this issue, which points to it being a site specific problem.

This is 99.9999% of the time an issue related to other plugins, themes, or custom code on your site, as WP Job Manager just calls the native WordPress `wp_editor` function to output this editor.

What did you change, install, or update on your site recently before this issue started happening?  This is more than likely the cause of your problems, especially if it was working fine previously.

Please also make sure you follow the issue template when creating new issues, which has the following (_**specifically, GitHub issues are not for support, please use the correct medium for support requests**_):

**PLEASE NOTE:**
- Try to add as much detail as possible. Be specific!
   _You did not provide any specific details as to what versions you're using, what addon you're using, etc._
- GitHub issues aren't for support! If you have questions, use this form: https://wpjobmanager.com/support/
