### ISSUE TITLE
job listing not shown when page gets loaded with ajax

### ISSUE THREAD

**Issue by andreschmid98** [Automattic/WP-Job-Manager#1145]
I am loading my page with ajax so the page does not refresh when I get to the job page. Then the job listing is not visible but when I refresh the page the job listing is visible

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.

It may be a compatibility issue with your theme and the `[jobs]` shortcode.
