### ISSUE TITLE
Error with Filled/Expired Jobs

### ISSUE THREAD

**Issue by michdia** [Automattic/WP-Job-Manager#1149]
#### What I Expected To Happen

Expired jobs should remain visible to the employer in their dashboard and to site administrators in wp-admin, but should be nonexistent to the public (either on the public job board, in the rss feed or sitemap or via google or similar). Going to the url for the expired job posting should yield a 404 error.

Filled jobs should have the same behavior. The only difference should be that the employer initiated this action before the job expired.

#### What Happened Instead

Expired jobs behave largely the way I expected, but a visit to the url tries to load content rather than displaying a 404 error.

Filled jobs are still displaying to the public via rss, sitemap, search, etc. I have no idea why a filled job should be available in any way for public consumption. This does no service for the employer or for a job seeker. If a job has been marked as filled, it should disappear from public view just like if it expired.

#### Steps to Reproduce the Bug

Set a job to expired and then go to the url for that job. 

Set a job to filled and then go to the url for the job, the rss or sitemap for the job board or search for it on the job board or in Google.

**Comment by dmoise2** [comment]
**Feature request:
What is happening:**

When a job is active, a page is created like so:

http://myURLcom/job/JobTitle-17-00124/

This Job also appears in the job_listing-sitemap.xml.

This is all good so far. When I close the job, I have configuration options to keep the URL active, but it no longer shows in the  job_listing-sitemap.xml. 

**What I want to see:**
Can we have an option in settings to called “keep sitemap for expired jobs”. If true, we would additionally create a sitemap called “expired_job_listing-sitemap.xml” that would hold the URLs of expired jobs.

**Why I want this:**
Having those pages being found in a sitemap will help us from an SEO perspective.

**Comment by jom** [comment]
@dmoise2 The implementation will depend on the 3rd-party plugin you're using to generate your sitemaps. You can look at our implementation in `includes/3rd-party` and remove the hooks for the associated plugin. We put those filters _for_ SEO, though, so be careful. Google said (for its Job Search) functionality that it may flag filled/expired jobs in sitemaps as spam.

@michdia We have settings for keeping them out of search results and hiding their content. Sitemaps depend on the generator. WPJM (as of 1.28.0) filters out expired/filled jobs from Yoast , All in One SEO, and Jetpack. 

I'll set the enhancement request for returning 404, but I don't know how high of a priority it will be. It is definitely possible with a filter:
```php
add_action( 'wp', function () {
	global $post, $wp_query;

	if ( ! $post || 'job_listing' !== $post->post_type ) {
		return;
	}
	if ( is_position_filled( $post ) ) {
		status_header(404);
		$wp_query->set_404();
		include( get_query_template( '404' ) );	
		exit;
	}
} );
```

**Comment by jom** [comment]
Closing in lieu of the filter solution.
