### ISSUE TITLE
Undefined Index "placeholder" in submit form

### ISSUE THREAD

**Issue by turtlepod** [Automattic/WP-Job-Manager#1150]
On submit Form when Registration Enabled:

> `Notice:  Undefined index: placeholder in <b>..wp-content\plugins\wp-job-manager\templates\form-fields\text-field.php</b> on line <b>18</b><br />`

> `Notice:  Undefined index: placeholder in <b>...wp-content\plugins\wp-job-manager\templates\form-fields\password-field.php</b> on line 18`

> `Notice:  Undefined index: placeholder in <b>...wp-content\plugins\wp-job-manager\templates\form-fields\password-field.php</b> on line 18`

**Comment by turtlepod** [comment]
Placeholder is a required field data.

Currently in `wpjm_get_registration_fields()`

- $registration_fields['create_account_username']
- $registration_fields['create_account_password_verify']
- $registration_fields['create_account_password']

do not have placeholder data.

**Comment by jom** [comment]
Fixed in #1180
