### ISSUE TITLE
Feature Request: Do Not Log User In Automatically in wp_job_manager_create_account()

### ISSUE THREAD

**Issue by turtlepod** [Automattic/WP-Job-Manager#1151]
It's not a bug (well, maybe in some country)

I got a report that in Germany there's a rule (maybe someone can confirm?):

> according to german law an email address have to be proved by the provider before delivering service

And because it's automatically log user in, it violate the law.

**Comment by turtlepod** [comment]
Here's more info from the user:

![20916680_10212584304257103_507082845_n](https://user-images.githubusercontent.com/1705549/29465728-7a6f41b2-8464-11e7-9301-1900cc390c05.png)

**Comment by CVgeek** [comment]
Mobile number authentication process!!!I'd pay if made to be compatible plugin.This is a very good point and something that would make you guys stand out from the competitors.

-------- Original message --------

**Comment by jom** [comment]
I'm not a legal expert, but double opt-in seems to more be around emailing users not providing a service. I think for this, it would be better for users to disable account creation in WPJM and instead guide users to use WordPress' normal registration process first.
