### ISSUE TITLE
Unable to activate comments on individual job listings

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1152]
This came up in 639702-zen ; @danjjohnson helped to test it.

We are unable to activate comments on individual job listings; Dan was able to have comments on an old listing, but not on a newly-created listing. The Discussion meta-box was not available, and was not listed in the Screen Options either.

**Comment by donnapep** [comment]
How old is the listing that had comments enabled? From what I can tell, the Job Listings post type has [never supported comments](https://github.com/Automattic/WP-Job-Manager/blame/master/includes/class-wp-job-manager-post-types.php#L246). At least not as far back as 2 years ago. It's easy enough to add support for it, but if this previously worked and only stopped working recently, then there's something else going on.

**Comment by richardmtl** [comment]
I'll have to defer to @danjjohnson here, Donna; he actually tested it, not me.

**Comment by jom** [comment]
Job Manager does not (and I don't think should) add support for job listing comments when registering the post type. Closing for now.

Users can get around this by adding support (de-anonymize the function for compatibility):
```php
add_action( 'init', function() {
	add_post_type_support( 'job_listing', 'comments' );
} );
```
