### ISSUE TITLE
Sign-in link pointed to incorrect url

### ISSUE THREAD

**Issue by myjkkskl** [Automattic/WP-Job-Manager#1153]
The 'sign-in' link for submit-job-form (slug) is pointed to incorrect url. It's currently pointed to 'http://mydomain.com/submit-a-job' page instead of '/login or /register'.

Sample → http://myjkkskl.com/submit-a-job/

**Comment by myjkkskl** [comment]
P/S: New slug is now known as "post-a-job".

Correct sample link → http://myjkkskl.com/post-a-job

**Comment by jom** [comment]
Please see https://wpjobmanager.com/support for support. 

Make sure the correct page is selected in WP Admin > Job Listings > Settings > Pages.
