### ISSUE TITLE
[Question] Disable Expire Date

### ISSUE THREAD

**Issue by dertuerke** [Automattic/WP-Job-Manager#1154]
Hi, can i disable the Expire function? I dont need it. I want manuell close the Job.

Thx

**Comment by dertuerke** [comment]
push

**Comment by jom** [comment]
For support, please visit: https://wpjobmanager.com/support/

Clearing the default expiration duration in WPJM settings will dodo this.

**Comment by dertuerke** [comment]
@jom I mean when importing job offers. The jobs should not expire.
