### ISSUE TITLE
Apply for job with resume where user has multiple resumes - Second Online Resume dropdown just shows user name

### ISSUE THREAD

**Issue by patwalshlondon** [Automattic/WP-Job-Manager#1155]
#### What I Expected To Happen
My test user has two resumes - both with the same name, as that's his name - and with different titles. Resume title 1 is Automation expert. Resume title 2 is Agile QA/Tester.

When applying for a job, the Apply form shows the Online Resume (Optional) selector correctly shows the two resumes, showing the name and the title, so you can distinguish between them. 

However, the section lower down 'Apply using your online resume...' also has an Online Resume selector. I expected this to also show the same info as the Online Resume (Optional) selector further up the Apply form, showing name and title for each resume.

#### What Happened Instead
The lower Online Resume selector shows just the name and not the title, so I can't distinguish one from the other. 

#### Steps to Reproduce the Bug
Setup two resumes for the same registered user.
Leave the names on the resumes the same, but have different professional titles in each resume. 
Apply for a job and look at the two Online Resume selectors to see the difference between them - the second one should be the same as the first one, as that's more useful.

![bottom online resume selector - not so good](https://user-images.githubusercontent.com/31097385/29533469-f35d9686-86a9-11e7-953d-a8b3f2670fe2.png)
![top online resume selector good](https://user-images.githubusercontent.com/31097385/29533468-f3412186-86a9-11e7-910d-80cc07e14b2c.png)

**Comment by jom** [comment]
A fix is in ready for the Resume plugin that will add this. Should be shipped soon.
