### ISSUE TITLE
Bug: Optional Register Field Do Not Make Sense

### ISSUE THREAD

**Issue by turtlepod** [Automattic/WP-Job-Manager#1157]
If I disable "Account Required" Settings, this is what I see in register field:

![optional-weird](https://user-images.githubusercontent.com/1705549/29657140-e6f4e1ea-88e0-11e7-88a9-fb118e1b641c.png)

What a weird fields.
So I can set my password but my user name is optional?
Or I can create account using only password?

If account is not required, it should not display any fields at all.

function info `wpjm_get_registration_fields()`:

**Comment by jom** [comment]
This is expected behavior for now (although clunky). If users don't put in a username, it generates one for them based on their email address. If users don't put in a password, it sends email to activate.

Disabling 'Enable account creation during submission' will hide the fields.
