### ISSUE TITLE
WP Job Manager - Adding Salary Field

### ISSUE THREAD

**Issue by paulb22** [Automattic/WP-Job-Manager#116]
Give me the shove if this is wrong forum to ask in...
Read your posts about 'Step by Step adding a Salary Field' into jobs form...
Can add the field okay, using edits to 'function.php', it is in the wordpress jobsadmin area just fine. But it does not result in any display of the salary info on page - When you finish the post with "Thats all there is to it.", assumed it would work. Am I missing something more to edit to display the new field?

I am an innocent - not a brainer, so please help if not too time consuming. Thanks in advance. Have read a couple of other forumites asking similar, but they don't appear to have been answered as yet. Thanks

**Comment by imiMike** [comment]
I have followed this tutorial to add the salary field: https://wpjobmanager.com/document/tutorial-adding-a-salary-field-for-jobs/

The salary field is displayed when adding new job and in the single job page.

There is a dropdown in the job search page now, however it doesn't work. Each time you change the dropdown value, the search results reload but all the result's are shown, so the filter doesn't work.

Any clues on what's wrong?

Thanks is advance.

![image](https://cloud.githubusercontent.com/assets/13148477/10727763/3e86a086-7bd4-11e5-8ff0-0efebf734972.png)
