### ISSUE TITLE
Job Listings doesn't appear on page [jobs] - Template: Map & Results

### ISSUE THREAD

**Issue by gabrymusix** [Automattic/WP-Job-Manager#1160]
Dears,
plugin updated last version

in page [jobs] shortcode no jobs are displaied.
Only the .gif of loading is running. also refreshing the page nothing happens.
The maps works correctly also the Resumes are displaied correctly.

does anybody have a solution 
thanks

**Comment by jom** [comment]
What theme are you using? "Map & Results" is not a template included in WPJM core. You may need to contact your theme developer.

**Comment by gabrymusix** [comment]
Dear Sir,thanks for your email,we contacted the theme dev
regardsGabriele




----Messaggio originale----

Da: "Jake Oehler Morrison" <notifications@github.com>

Data: 20/09/2017 1.13

A: "Automattic/WP-Job-Manager"<WP-Job-Manager@noreply.github.com>

Cc: "gabrymusix"<gabry.musix@libero.it>, "Author"<author@noreply.github.com>

Ogg: Re: [Automattic/WP-Job-Manager] Job Listings doesn't appear on page [jobs] - Template: Map &amp; Results (#1160)




What theme are you using? "Map &amp; Results" is not a template included in WPJM core. You may need to contact your theme developer.
