### ISSUE TITLE
WC Paid Listings - packages not appearing

### ISSUE THREAD

**Issue by craigwillis85** [Automattic/WP-Job-Manager#1161]
#### What I Expected To Happen
I should see 2 jobs when submitting a new job

#### What Happened Instead
I don't see any job packages on the job submission form

I'm using a theme (WorkScout), which implements WP Job Manager. I have installed the WC Paid Listings plugin and changed my 2 products to be a `Job Package`.

When I create a new job post, I'd expect them to be shown in the form, but they are not.

Is this expected behaviour? Or do potential job posters need to purchase a package before going to the job submission page?

Thanks

**Comment by craigwillis85** [comment]
It seems that the packages are displayed on a different step.

**Comment by ldoherty74** [comment]
I have exactly the same issue with WorkScout, I have set the job package flow to show the packages before posting a job but this is not appearing and a job can be posted without selecting a package. How was this resolved?

**Comment by jeleanor** [comment]
Hi, I have a similar problem, Job Packages aren't showing on the Pricing Table page. Anybody experienced/fixed these things?
