### ISSUE TITLE
Default option in category select disappear on mobile

### ISSUE THREAD

**Issue by limestreet** [Automattic/WP-Job-Manager#1162]
#### What I Expected To Happen
After choosing something in category filter and resetting the filter I expected default field value ("Any category" text)
#### What Happened Instead
I got empty field - please see: https://snag.gy/16bX0G.jpg
#### Steps to Reproduce the Bug
Open jobs/listing page on mobile (or dev tools in chrome with mobile preview i.e. Nexus 5) select category in filter (single category set up on back-end) and then tap/click reset.

**Comment by jom** [comment]
Able to reproduce on Safari (iOS).
