### ISSUE TITLE
Blank RSS feed

### ISSUE THREAD

**Issue by Alex-clubferoviar** [Automattic/WP-Job-Manager#1165]
Hello everyone,

Encountered an issue with WP Job Manager RSS feed that i couldn't fix even after reading the other threads about RSS problems.

My RSS feed URL is [http://clubferoviar.ro/?feed=job_feed](http://clubferoviar.ro/?feed=job_feed) and it shows a blank page with no posts (jobs), even though there are several listed here [http://clubferoviar.ro/jobs/](http://clubferoviar.ro/jobs/).
Using W3C rss validator gives the following error: 

> This feed does not validate.
> line 12, column 20: XML parsing error: <unknown>:12:20: undefined entity 

Any help would be appreciated.

Thanks

**Comment by jom** [comment]
It looks like something is overriding your title separator (`document_title_separator` filter) to be `& raquo;`/», which must not be appreciated by RSS.
