### ISSUE TITLE
No translated job list when https enabled and site is in diffrent language (PL)

### ISSUE THREAD

**Issue by KrzysztofCieslak** [Automattic/WP-Job-Manager#1167]
#### What I Expected To Happen
Load translated job positions via https in diffrent language

#### What Happened Instead
stuck, no https protocol and no domain in ajax request when looking at console

#### Steps to Reproduce the Bug
visit https://b-mind.pl/pl/praca/ and look at the console

**Comment by jom** [comment]
Looks like you are overriding `home_url`. What is your permalink structure? `WP_Job_Manager::get_endpoint()` is returning `http://jm-ajax/%endpoint%`.

**Comment by KrzysztofCieslak** [comment]
Looks like this (attached image)
![screen shot 2017-09-22 at 10 56 00](https://user-images.githubusercontent.com/1867098/30736846-acd3fd92-9f84-11e7-832e-a0ef183a34cb.png)

**Comment by jom** [comment]
This is a known issue with the most recent version of WPML. See #1176
