### ISSUE TITLE
WP Job Listing Still showing on Front-end after being deleted

### ISSUE THREAD

**Issue by Social-Grant** [Automattic/WP-Job-Manager#1170]
I deleted the Job listing from the WP Job Manager listing "All Jobs" tab.
This should have deleted it on both the front and back-end.

However, it did removed it from the back-end but not the front end.
It has left a "Job listing" on the front-end, which if clicked on, gives you a 404 error.

![back-end all jobs page](https://user-images.githubusercontent.com/31867129/30298101-741f4dd6-974a-11e7-93a8-812665163b3e.jpg)

![front-end job listing](https://user-images.githubusercontent.com/31867129/30298103-742eac04-974a-11e7-95a1-97fe613c9b12.jpg)

![error when clicked on](https://user-images.githubusercontent.com/31867129/30298102-74274374-974a-11e7-8b91-8ff6eaa4e342.jpg)

I have also tried deactivating and reactivating the plug-in.

How can I go about removing this from the front-end?

**Comment by jom** [comment]
Please visit https://wpjobmanager.com/support for support related questions.

It may have been a caching issue.
