### ISSUE TITLE
Source code of wp-job-manager.php

### ISSUE THREAD

**Issue by DevRami1** [Automattic/WP-Job-Manager#1171]
I am little bit changed some code inside wp-job-manager.php which caused my wp site to stop! So i want to reset my wp-job-manager.php file to its original code. 

Can any body give me the source code of this file?

By the way, my wp theme is workscout

**Comment by spencerfinnell** [comment]
https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager.php

Raw: https://raw.githubusercontent.com/Automattic/WP-Job-Manager/master/wp-job-manager.php

You should not edit plugin files directly due to this reason.
