### ISSUE TITLE
if you have problem pulling the_candidate_photo() with custom sizing

### ISSUE THREAD

**Issue by zenics** [Automattic/WP-Job-Manager#1172]
I had the same problem with images.

I was using the function the_candidate_photo( 'custom-size' ); to pull the image from upload field. The problem was I couldn't pull the right sized image because function the_candidate_photo was nt able to create the custom size. Going back and forth I ve looked at how the latest job manager pulls the company logo and edited the the_candidate_photo function accordingly and walla...!

Here is what I did. (on /wp-job-manager-resumes/includes/wp-resume-manager-template.php) So It would be nice if the resume manager addon gets this in the core so I dont need to overwrite the core file.
```

function the_candidate_photo( $size = 'thumbnail', $default = null, $post = null ) {
	$logo = get_the_candidate_photo( $post , $size);

	if ( $logo ) {

		if ( $size !== 'full' ) {
			$logo = job_manager_get_resized_image( $logo, $size );
		}

		echo '<img class="candidate_photo" src="' . $logo . '" alt="Photo" />';

	} elseif ( $default )
		echo '<img class="candidate_photo" src="' . $default . '" alt="Photo" />';
	else
		echo '<img class="candidate_photo" src="' . apply_filters( 'resume_manager_default_candidate_photo', RESUME_MANAGER_PLUGIN_URL . '/assets/images/candidate.png' ) . '" alt="Logo" />'; }
function get_the_candidate_photo( $post = null, $size = 'thumbnail' ) {
	$post = get_post( $post );

	if ( has_post_thumbnail( $post->ID ) ) {
		$src = wp_get_attachment_image_src( get_post_thumbnail_id( $post->ID ), $size );
		return $src ? $src[0] : '';
	} elseif ( ! empty( $post->_candidate_photo ) ) {
		// Before 1.24.0, logo URLs were stored in post meta.
		return apply_filters( 'the_candidate_photo', $post->_candidate_photo, $post );
	}

	return '';
}

```

**Comment by jom** [comment]
Hi there! This issues board for WP Job Manager core only. I've created the enhancement request for the resume plugin. Thanks for your feedback!
