### ISSUE TITLE
Erreur HTTP 500 dans le back-office et lecture des CV impossible

### ISSUE THREAD

**Issue by benjamin-altena** [Automattic/WP-Job-Manager#1173]
#### What Happened Instead
La mise en ligne des CV via le formulaire accessible par le shortcode [submit_resume_form] fonctionne parfaitement.
Lors de la consultation des CV via le shortcode [resumes] la page s'affiche mais impossible de voir les contenu.

Dans le back-office, le dépôt de CV fonctionne ainsi que les catégories de CV, mais impossible de visionner les CV qui se situe en page 2 & 3 même en changent la vu par page (ex : 50). a ce moment la j'obtient l'erreur 500 HTTP, qui correspond a rien pour moi.

Çà fonctionner hier et ce matin plus rien, le serveur et héberger en mutualisé sur le domaine des noms avec un DDN standart.

#### Steps to Reproduce the Bug

se connecter sur notre site internet www.jobando.fr/cv/   est constaté que le chargement se fait mais rien ne s'affiche.

**Comment by jom** [comment]
For support questions, please visit https://wpjobmanager.com/support.
