### ISSUE TITLE
500 - Internal Server Error with WP Resume Manager

### ISSUE THREAD

**Issue by Yunis777** [Automattic/WP-Job-Manager#1175]
#### What I Expected To Happen
I expected a user to be able to return to my website after having filled in the page https://beanjobs.com/register-your-skills/, confirming their email address, setting their password **AND** logging into their account using their email address and password.

#### What Happened Instead
The user sees the following error message: https://s26.postimg.org/kteo3b789/500_internal_server_error.png

#### Steps to Reproduce the Bug
1. Fill in the page https://beanjobs.com/register-your-skills/
2. Use an email address which you can login into yourself in the field 'Your email'.
3. Click 'Send my resume free' button at bottom of page
4. Follow pages through
5. At some point you will receive a message from the website at the email address you gave in step 2.
6. The email message will ask you to set your password by clicking on a link
7. After you have clicked the link, you will be required to set a password as part of the website registration and account creation.
https://s26.postimg.org/cdkyrfvx5/500_internal_server_error_-_setting_user_passwor.png
8. When you have set your password and click on 'Beanjobs.com' logo, you will see page a with the "500 - Internal Server Error". Not very nice to see if you're a user.
See screenshot: https://s26.postimg.org/kteo3b789/500_internal_server_error.png

The only way to get rid of the error message is by clearing the browser's cache which I definitely do not want to the user having to do.

My webhost said it is because the plugin is generating very large cookies and generating shorter ones would resolve the issue.

This is what he said:
"The original request that results in error 500 is, it can be taken from a browser >> developer tools >> Network >> right click on the 500 error request >> Copy as curl:

Code:
curl 'https://beanjobs.com/login/' -H 'pragma: no-cache' -H 'accept-encoding: gzip, deflate, sdch' -H 'accept-language: bg-BG,bg;q=0.8' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'cache-control: no-cache' -H 'authority: beanjobs.com' -H 'cookie: wordpress_logged_in_e5daacf8d0b15a0298e71e5299b42894=paveldosev%7C1506775622%7CLj2MOLagUNpRcrWcgpeXmVo9dbv5sRHU22NKDUoZGDB%7Cfb9425fa3cb96586dc0345d24522f1f64cff6ded999ba3450fd0c53a665a73f1; _ga=GA1.2.1880442822.1505565964; _gid=GA1.2.529783117.1505565964; wfwaf-authcookie-fdc6735b21a24db3ee5e119ffaf73d95=70%7C%7C7bbbe84e61d02794b6dd759fdc5964cab4ce42fe37216efc3530af29866ec50d; wordpress_test_cookie=WP+Cookie+check' -H 'referer: https://beanjobs.com/login/?action=resetpass' --compressed

If I get the same request but reducing the lenght of the cookie string the error is no longer showing:

Code:
curl 'https://beanjobs.com/login/' -H 'pragma: no-cache' -H 'accept-encoding: gzip, deflate, sdch' -H 'accept-language: bg-BG,bg;q=0.8' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'cache-control: no-cache' -H 'authority: beanjobs.com' -H 'cookie: wordpress_logged_in_e5daacf8d0b15a0298e71e5299b42894=paveldosev%7C150cb96586dc0345d245220fd0c53a665a73f1; _ga=GA1.2.1880442822.1505565964; _gid=GA1.2.529783117.1505565964; wfwaf-authcookie-fdc6735b21a24db3ee5e119ffaf73d95=70%7C%7C7bbbe84e61d0af29866ec50d; wordpress_test_cookie=WP+Cookie+check' -H 'referer: https://beanjobs.com/login/?action=resetpass' --compressed

As this seems to be from a custom made plugin I suggest contacting its developer and asking him if it is possible to generate shorter cookies as this should resolve the issue. "

Kind regards,

Yunis

**Comment by jom** [comment]
The cookies WPJM sets are quite small. It looks like you have too many plugins attempting to set cookies. If your web host isn't able to increase that limit, you'll need to disable some plugins. Looks like Wordfence is adding a larger cookie.

**Comment by Yunis777** [comment]
Jom,

Thanks for the reply. The issue was caused by the plugin 'Limit Login Attempts' which was last updated an unbelievable 5 years ago.  See: https://en-gb.wordpress.org/plugins/limit-login-attempts/

Kind regards,

Yunis
