### ISSUE TITLE
Add searching by username for changing author in job post

### ISSUE THREAD

**Issue by annezazu** [Automattic/WP-Job-Manager#1177]
In order for a user to change the author of a job listing, they have to know the user ID. Most folks won't know what that is. Can we update this to search for the username?

<img width="391" alt="screen shot 2017-09-18 at 6 19 17 pm" src="https://user-images.githubusercontent.com/26996883/30571631-f0932c5e-9c9d-11e7-983c-49296e9773e4.png">

**Comment by spencerfinnell** [comment]
Related/duplicate: #846 

Gets a 👍 from me though. No one knows what an ID is.

**Comment by jom** [comment]
Definitely 👍  from me too. Closing in favor of #846, although a drop-down might not be the way to go.... but some kind of user selector that shows "Fname Lname (Username)" would be nice.
