### ISSUE TITLE
can you please explain how to use rest-api?

### ISSUE THREAD

**Issue by sunilnimble2015** [Automattic/WP-Job-Manager#1183]
Hi,
Can you please give me the example URL to call a rest api for listing, add, Edit, delete WS. Means i need a demo url format by using which i can perform any action. I have put rest-api folder within includes folder as mentioned in plugin structure. can you please help me.

I just want to a WS which will be called from mobile side to perform action.

**Comment by gaurav1984** [comment]
696762-zen

**Comment by jom** [comment]
Hi there! We don't yet have any documentation to provide as the REST API has not been fully released. I don't have an ETA at this time. For now, the best resource would be the PRs that have been merged or are in-progress:
https://github.com/Automattic/WP-Job-Manager/pulls?utf8=%E2%9C%93&q=is%3Apr%20%22REST%20API%22%20author%3Apgk%20

In the future, this is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
