### ISSUE TITLE
feature request - approval option

### ISSUE THREAD

**Issue by belindawaldock** [Automattic/WP-Job-Manager#1185]
Hi,
ive just started using the plug in for our site www.softwarecornwall.org to show jobs in the software community here in Cornwall, its great thank you! 

There are a couple of would like to haves which i cant find available as add ons so i thought i would share here, much more from user/product owner perspective than dev 

Approvals - it would be great if users that already have a login could post jobs and me not have to approve them.  The approval works great as we limit jobs posts to our members only, but then once a member is live it would be nice if they could post jobs without having to wait for approval

ive just thought i should probably separate my two ideas so i will start a new post!

thanks again for a brilliant plugin 

Belinda
belinda@beingagile.co.uk
www.softwarecornwall.org

**Comment by jom** [comment]
Duplicate #933 

Feel free to let us know if you feel what you're suggesting is significantly different than or not covered by what is proposed in #933.
