### ISSUE TITLE
feature request - twitter sharing of job post

### ISSUE THREAD

**Issue by belindawaldock** [Automattic/WP-Job-Manager#1186]
Hi me again!

so my second wish..

Social Sharing - it would be awesome if when a job was approved if it could send out a tweet automatically, at the moment when i approve a job i then manually tweet it out.. what would be ace would be the ability to tweet it and include the job title, location, and some hashtage keywords from fields.. but thats probably asking a bit too much.

sending to linked in and facebook would also be cool too

thanks again for a great plug in, hope you find these ideas of interest, if you are looking for a product owner type contributor do please let me know ! 

best wishes

Belinda 
www.SoftwareCornwall.org

**Comment by cestrian77** [comment]
I highly recommend the WP to Twitter plugin to achieve what you're asking https://en-gb.wordpress.org/plugins/wp-to-twitter/

It can be configured to send Tweets every time a new job is published, and you can configure it to automatically add hashtags specific to your sector: e.g. A new tweet could look like this:

New job: #title# #[[_job_location]] #url# #SECTOR #jobs

Whereby the title is automatically populated from your job post, the location is pulled in automatically and hashtagged, and the URL back to your job post is included. The #SECTOR can be changed manually at any point to match the sector you work in. And #jobs is an optional hashtag to add to all Tweets.

**Comment by belindawaldock** [comment]
Thank you cestrian77 this is ideal :) much appreciated!
B

**Comment by belindawaldock** [comment]
hi @cestrian77 .. the plugin worked great, thanks so much for sharing.  do you know of a similar plugin that will post to facebook or linked in in a similar way please ?! thanks again B :)
