### ISSUE TITLE
Can someone explain how to print out a field label?

### ISSUE THREAD

**Issue by zenics** [Automattic/WP-Job-Manager#1187]
Hey, I am working on a site that requires outputting the label of a field and I would like to know if there is a way of doing this.

I have tried both
$custom_field = get_post_meta( $post->ID, '_custom_field', true ); 
or 
get_resume_field( 'custom_field', $post->ID );

to get
$custom_label = $custom_field['label'];

with no luck,

the whole field group is under $field_data array(21) and the specific field is in an array with:
$field_data array(21)
array(71)
ID' => integer4967
'post_id' => integer4967
'status' => string(7) "enabled"
'hasp_expire_enable' => string(1) "0"
'hasp_expire_date' => string(0) ""
'hasp_overwrite_enable' => string(0) ""
'hasp_overwrite_post_id' => string(0) ""
'meta_key' => string(11) "custom_field"
'_meta_key' => string(11) "custom_field"
'admin_only' => string(1) "0"
'multiple' => string(1) "0"
'ajax' => string(1) "0"
'required' => boolFALSE
'output_show_label' => string(1) "0"
'populate_enable' => string(1) "0"
'populate_save' => string(1) "0"
'option_default' => string(1) "0"
'option_disabled' => string(1) "0"
'packages_require' => string(1) "0"
'image_link' => string(1) "0"
'output_enable_fw' => string(1) "0"
'output_enable_vw' => string(1) "0"
'output_video_allowdl' => string(1) "0"
'hide_in_admin' => string(1) "0"
'label_over_value' => string(1) "0"
'type' => string(8) "checkbox"
'label' => string(7) "LABEL of the custom field"
'description' => string(54) "Description of the custom field"

Any way I can get that label? I need to output that on the results.

Thanks in advance.

**Comment by jom** [comment]
Hi there! This is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
