### ISSUE TITLE
WP Job Manager Shows Previous Data for New Job Submissions

### ISSUE THREAD

**Issue by scottallanaz** [Automattic/WP-Job-Manager#1195]
#### What I Expected To Happen

Form fields to be clear when a user submits a new listing

#### What Happened Instead

WP Job Manager Shows Previous Data for New Job Submissions

#### Steps to Reproduce the Bug

Create a new listing AFTER having created a listing previously

corporatelanding.com

**Comment by spencerfinnell** [comment]
It should only pre-fill "Company" fields with the previously entered information. This is intentional as each WordPress user is considered to be a unique company.

**Comment by scottallanaz** [comment]
Great thank you.  How can I remove the payment information fields from
listings that are free?  We can't seem to figure it out

Scott A. Weber

(480) 622-3527
scott@scottweber.me

Skype: scottweberaz
LinkedIn: Scott Weber <https://www.linkedin.com/in/morebass>

E-MAIL CONFIDENTIALITY NOTICE:    This e-mail message is intended solely
for the addressee(s) and may contain confidential and/or legally privileged
information. If you are not the intended recipient, or this e-mail was
addressed to you in error, you should delete this e-mail message and any
attachments, and you are notified that disclosing,copying, distributing or
taking action in reliance on the contents of this information is strictly
prohibited.

**Comment by jom** [comment]
Hi there! For support, please visit https://wpjobmanager.com/support.
