### ISSUE TITLE
Settings Pages selected pages lost when saving changes in second language

### ISSUE THREAD

**Issue by Irpe1337master** [Automattic/WP-Job-Manager#1199]
#### What I Expected To Happen & Steps to Reproduce the Bug

Define WPJM pages in english and press save changes.  

![define pages in english](https://user-images.githubusercontent.com/25027233/31336316-f7f731b8-acfe-11e7-9c61-11a3e53c32f3.png)

Change to second language and do nothing else but press save changes

![save settings in second language](https://user-images.githubusercontent.com/25027233/31336320-fb9d25de-acfe-11e7-9009-3d84549d721a.png)

I expect nothing to happen because I just pressed save settings and changed nothing.

#### What Happened Instead

After saving settings in second language, all the previosly defined WPJM pages were lost.

![aftermath](https://user-images.githubusercontent.com/25027233/31336321-0077df22-acff-11e7-833a-f1b78d417e45.png)

I also tried defining pages in both languages and only in second lannguage but it didn't help either. 

Tested with fresh install:
 - WP Job Manager Version 1.29.0 
 - WPML Version 3.8.3

Theme
 - Jobify

 Found this old issue which could be somewhat related https://github.com/Automattic/WP-Job-Manager/issues/786

**Comment by richardmtl** [comment]
Another in 1065670-zen

**Comment by jom** [comment]
It used to work if the pages were set to the _primary_ langauge's page. Once you do that, do not set them again for other languages. The WPML integration should convert them automatically when the setting values are retrieved: 
https://github.com/Automattic/WP-Job-Manager/blob/d3243bf5efe74c77074cde1a67edf98f0ea55ca8/includes/3rd-party/wpml.php

If we can confirm that it is not mapping these values to the current language (when the setting is set to the primary language's version of each page), then we'll need to dig back in.

cc: @vukvukovich

**Comment by richardmtl** [comment]
I'm asking the user in 1065670-zen to confirm.

**Comment by vukvukovich** [comment]
@jom I've just tested issue and it works as it supposed to do. I can't tell for sure, but as far as I could remember there was some dropdown disable on secondary languages and now it is gone. Am I right or that was related to some other plugin I've been testing? :)

**Comment by jom** [comment]
@vukvukovich Must be another plugin, but definitely worthy of an enhancement request 😄

**Comment by vukvukovich** [comment]
@jom I'll will write that mini fix feature. Do you want me to disable whole pages tab or just dropdowns?

**Comment by codestor4** [comment]
1065670-zen

They confirm this with the following reply:

> Nope, that does not work. I currently have the pages set to my primary language’s page and none of the other languages work.

**Comment by vukvukovich** [comment]
@codestor4 Are they checking pages from the frontend?

**Comment by richardmtl** [comment]
@vukvukovich This is what they said:

<blockquote>Both. I add the correct pages to the Admin Panel under Job Listings - Settings - Pages and GEO SEARCH (an extension) for each English. Then, I check the front end JOBS LIST page and everything comes up correctly. However, when I go to the FRENCH front end site, Jobs Listing Page - nothing appears. Then when I go under the Admin Panel for FRENCH - Job Listing- Settings- Pages – no pages are connected to Submit Job Form Page, Job Dashboard Page, and Job Listings Page – then when I try to add them – and view the French Front End Jobs Listings page – it works. However, when I return to the English website, front end Job Listing Page, no jobs appear. So then I go to the English Admin Panel under Job Listings - Settings - Pages and see that nothing is now connected to Submit Job Form Page, Job Dashboard Page, and Job Listings Page – the French site overwrote it I assume when I assigned French pages to it when under the French Admin Panel. </blockquote>

Any ideas?

**Comment by jom** [comment]
They should never go to `Job Listings - Settings - Pages` for the secondary language (French, it seems). Instead, they need to make sure that there are French language variants for all those pages attached to the primary language's page. They should all have essentially the same content (the shortcode). The settings in `Job Listings - Settings - Pages`, however, should just be set when on the primary language.

**Comment by vukvukovich** [comment]
@richardmtl Exactly as @jom wrote. 

Once again steps to make it work:

1. Create pages in default language (usually generated by WPJM wizard)
2. Translate those pages with same content copied from default one
3. Set pages for default languages in `Job Listings - Settings - Pages` (As I remember already set by default, but resave just in case)

Thant's it! 💃

**Comment by jom** [comment]
With the PR I just merged from @vukvukovich (#1442), these settings will only be editable when using the default language. They'll be directed to switch their language if on a secondary language.
