### ISSUE TITLE
search options categories all selected

### ISSUE THREAD

**Issue by artiman** [Automattic/WP-Job-Manager#1201]
#### What I Expected To Happen
when people looking for a job and trying to search on the job board all categories needs to display.
so that people can select itself which categorie he wants to see.
 
#### What Happened Instead
when people try to search the job board, All categorie are visible but all are selected. 
and that means all ads on the board are seen at the search.
so people needs to manuel deselect all the categories to just see 1 categorie 👎 

#### Steps to Reproduce the Bug
if it posible that on the start all ads are visible when all categories are unselected but when the members select any categorie then only the jobs in this categorie will be displayed !
that would be much better and usefriendly for all people !

**Comment by jom** [comment]
I think this would be better as a customization for individual sites.
