### ISSUE TITLE
Replace chosen.js?

### ISSUE THREAD

**Issue by dsaric-dev** [Automattic/WP-Job-Manager#1202]
Hello,

The included select element enhancement library (chosen.js) doesn't support mobile browsers. Are there any plans on replacing it with one that does provide mobile support such as select2 or selectize?

Thanks,
Damir

**Comment by jom** [comment]
What issue are you having on your mobile browser? Please also include your browser/OS information. I'm able to select [multiple] job categories from both Chrome and Safari on iOS.

**Comment by dsaric-dev** [comment]
The issue is that chosen.js library is disabled for mobile browsers, so the dropdown list defaults to html select. This also means that placeholder isn't being used, but defaults to mobile browser default of "0/n items selected."

**Comment by spencerfinnell** [comment]
https://github.com/harvesthq/chosen/pull/1388

**Comment by tripflex** [comment]
iOS seems to be a common issue with mobile stuff ... had similar issue with Flatpickr and iOS when using native HTML5 elements, geezzz ... @dsaric-dev can you tell us what browser you're using, the version, and what version of iOS you're using?

**Comment by dsaric-dev** [comment]
@tripflex, I'm not personally using iOS, and it's not important, as this is relevant for all mobile browsers. Chosen.js doesn't support them, and it doesn't seem as it will support them any time soon.

From https://harvesthq.github.io/chosen/#faqs:
_What browsers are supported?
All modern desktop browsers are supported (Firefox, Chrome, Safari and IE9). Legacy support for IE8 is also enabled. **Chosen is disabled on iPhone, iPod Touch, and Android mobile devices** [(more information)](https://github.com/harvesthq/chosen/pull/1388)._

**Comment by dsaric-dev** [comment]
Is there any progress on or interest in this issue/enhancement? @jom? Anyone else?

**Comment by tripflex** [comment]
I think switching to Select2 or even just using the select lib from Semantic UI would be a nice improvement 😁

**Comment by spencerfinnell** [comment]
https://github.com/jshjohnson/Choices is nice as well.

**Comment by richardmtl** [comment]
Reported in 1533329-zen

**Comment by codestor4** [comment]
![img_1747](https://user-images.githubusercontent.com/20779676/49800202-eda35600-fd6c-11e8-837d-3a08704ee79d.PNG)


1637325-zen
