### ISSUE TITLE
How to have Miles and Location Field for Job Alerts

### ISSUE THREAD

**Issue by subhash0709** [Automattic/WP-Job-Manager#1204]
Hi Please help on this isssue.
I have the Job Alerts module installed so that users can setup Job Alerts when a specific criteria matches.
One of the fields in the Job Alerts form is the “Location” field. Is there a way to have Miles field with location.
Also, is there a way for the user to specify that he wants to receive alerts 50 Miles radius from the specified address.

Thanks,
Subhash

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
