### ISSUE TITLE
Non-Latin URLs not encoded/decoded correctly?

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#1205]
To repro:

1. Get a URL with no-Latin chars in it, like this one:

https://www.colsadna.co.il/%D7%94%D7%95%D7%A1%D7%A4%D7%AA-%D7%A1%D7%93%D7%A0%D7%94/

2. Post a new job.
3. Use that URL as application method.
4. On the job page after you submit, it doesn't work:

<img width="650" alt="screen shot 2017-10-16 at 10 38 25 am" src="https://user-images.githubusercontent.com/5512652/31617788-28df1296-b25e-11e7-8623-7558f1ba5563.png">

722598-zen

**Comment by weiching123** [comment]
Hello,

Thank you for fixing this at 1.29.1

The same problem is also in social fields, such as: Facebook

In addition, this issue is fixed only front-end published in the admin Dashboard changes are not properly encoded.

**Comment by jom** [comment]
@weiching123 WPJM out-of-the-box doesn't have a Facebook field, but I'll create a new issue for the Twitter company field and check on the admin write panels issue.
