### ISSUE TITLE
To be able to change the time of the automatic Cron tasks

### ISSUE THREAD

**Issue by colomet** [Automattic/WP-Job-Manager#1206]
I would like to request a new feature: to be able to choose the time for the Cron automatic tasks. Example: The cron check if there is a job out of date. I think now is too often, and I would like to be able to change to 1 day or so.

**Comment by jom** [comment]
I'd recommend using a plugin such as Crontrol (https://en-gb.wordpress.org/plugins/wp-crontrol/). As long as there is an event scheduled sometime, WPJM will not try to modify the timing.
