### ISSUE TITLE
Facet are not going black upon saving in WP Job Manager Listings Setting

### ISSUE THREAD

**Issue by techtonix** [Automattic/WP-Job-Manager#1207]
#### What I Expected To Happen

Ideally when we setup the Facets under WP Dashboard > SETTINGS > FACETWP

![image](https://user-images.githubusercontent.com/19252869/31683521-49555db0-b38e-11e7-8094-5823c7395d64.png)

All we had to do was set them in various segments within WP Dashboard > Listings > FacetWP 

![image](https://user-images.githubusercontent.com/19252869/31683709-b732efa0-b38e-11e7-8706-b9f8fd98299a.png)

Ideally that should show up in front-end without at issue. However, after saving the Keyword Search Facet goes south.

#### What Happened Instead

The Facet go blank and don't show up on front-end

![image](https://user-images.githubusercontent.com/19252869/31683783-ea1387c2-b38e-11e7-8c32-ffca7c20d0dc.png)

#### Steps to Reproduce the Bug

Creating a new search facet using facetwp and adding it on to the FacetWP tab in Listings Settings.

**Comment by spencerfinnell** [comment]
That page only exists via the Listable theme. You should contact the theme author to ensure the theme is up to date with the latest version of FacetWP.

**Comment by techtonix** [comment]
Will do, Thanks for the swift response.
