### ISSUE TITLE
Job alert is NOT WORKING

### ISSUE THREAD

**Issue by jimacambo** [Automattic/WP-Job-Manager#1209]
Hi, guys !
[job_alerts] 

 is not working in any combination.

For 1 year.

only "no matches" mail coming.

You can check it at http://alljob.cc/find-job/

Please fix it and report.

Brgds 

Dmitrii

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests of the core WP Job Manager plugin. For support, please visit https://wpjobmanager.com/support.

**Comment by jimacambo** [comment]
You have acquired the rights for all WP Job Manager from Mike Jolley = core + add-ons, right ?
Who is responsible now for
[job_alerts] add-on is not working ?
May be it is worth to fix the bug and reply
to avoid negative comments throughout the net
about  Automattic is selling plugins that is not working
and requires additional money
 (because you don't want to support
users who bought your products more than 1 year before)
to fix your own bugs ???

Is it worth to receive many negative comments
instead of  just bugs fix ?

Brgds
Dmitrii

**Comment by jom** [comment]
If you have an active license, you'll be able to submit a support request for the job alerts plugin from https://wpjobmanager.com/support. If our support engineers are able to reproduce it, they'll report the bug appropriately. Again, this repository/issues board is just for the core WP Job Manager plugin.

**Comment by jimacambo** [comment]
In other words, you are telling me:
" Although it is our bug,
and we sold you the add-on that is not working,
we want additional 29$ 
to solve the problem."

Am I right ?

My license key has expired.
I bought your product 
2 years before.
