### ISSUE TITLE
Feature request: locations to link to job search by location

### ISSUE THREAD

**Issue by cestrian77** [Automattic/WP-Job-Manager#1211]
When a new job is published, the location is included in the job page - but this hyperlinks to a Google Maps listing for that location.

It would be much better in my opinion, if this linked back to a WP Job Manager search with that location as a location/keyword query, so returning all jobs that match that location.

*new to GitHub so please excuse if this isn't the right place to write this!

**Comment by linoman-zz** [comment]
good evening dear cestrian77, this is a important issue - and i think it is worth to work on this.

You are very very right: When a new job is published, the location is included in the job page - but this hyperlinks to a Google Maps listing for that location. It is  be much better - also in  my opinion, if this linked back to a WP Job Manager search with that location as a location/keyword query, so returning all jobs that match that location.

we should work on this!!

**Comment by jom** [comment]
I think this would be better as an individual customization. Closing as stale, but we can reopen if it gets traction.
