### ISSUE TITLE
Feature request - Apply with LinkedIn

### ISSUE THREAD

**Issue by cestrian77** [Automattic/WP-Job-Manager#1213]
Without a doubt, the number one feature I need is the ability to add "Apply with LinkedIn" to the WP Job Manager plugin. 

Apply with Facebook - as one of the available add ons is fine - but LinkedIn is the main professional network. 

They've recently changed their API and made it very difficult to set up, so having this functionality out of the box, or even available as one of the core/bundled add ons would be very beneficial.

**Comment by jom** [comment]
It is a feature of our Applications plugin to auto-fill from LinkedIn. Right now applying for jobs (besides contact/link) isn't supported in WPJM. Was this meant for a change to the applications add-on? 

Closing for now.

**Comment by cestrian77** [comment]
Thanks for the quick reply. 

Apologies, but the [Applications plugin](https://wpjobmanager.com/add-ons/applications/) page makes no mention of auto-fill from LinkedIn? 

I just haven't bought the add on bundle yet... it's on my to-do list! If this feature is available via the Applications Plugin then that's all I need.

**Comment by jom** [comment]
We should add the feature on the page, but it is quite limited due to what LinkedIn passed back.

**Comment by cestrian77** [comment]
Thanks again.  

Any ability to auto-populate the application fields and save time for people applying for jobs will be beneficial. 

Not knowing that it's part of the Applications plugin has led me to look elsewhere... something I'm guessing others might have done too.
