### ISSUE TITLE
Sitemap - Google 404 not found

### ISSUE THREAD

**Issue by Bertsi** [Automattic/WP-Job-Manager#1214]
Every day I get around 30 to 50 new 404 Crawling Faliure from google reported.
These Failures are always related to job-posts. For instance:

1 | job/wissenschaftlicher...| 404 | 18.10.17
2 | job/wissenschaftlichen... | 404 | 15.10.17
3 | job/professor-w3... | 404 | 16.10.17
4 | job/verwaltungsmitarbeiterin... | 404 | 16.10.17

So it seems like, that these job-posts are still listed in the "/job_listing-sitemap.xml", although they are actually already deleted.

Alltogehter there are around 2500 Jobs listed and via the WP-All-Import Plugin all jobs get updated or deleted on a daily base.

Im using the Yoast Plugin for my Sitemap. So far I know, does Yoast update the sitemap immediatley after a job get delited. 

Does anyone has an idea what the problem could be or has the same issue?

Thanks a lot!

**Comment by jom** [comment]
This seems like a problem with Yoast's caching of the `sitemap.xml` and not a bug with WPJM. Please check in with Yoast support.
