### ISSUE TITLE
Bcc email notifications of new resumes 

### ISSUE THREAD

**Issue by belindawaldock** [Automattic/WP-Job-Manager#1216]
#### What I Expected To Happen
I set up email notifications within resume submission settings to a number of emails, this sends an email to everyone which is great, but all emails are visible to all recipients 
#### What Happened Instead
i expected either individual emails to send or for the recipient to not be able to see other recipients - eg would be sent as Bcc recipients 
#### Steps to Reproduce the Bug
not a bug

i believe i can add a filter to the functions.php file somehow which im talking to your ace support about, but in terms of a feature request it would be great if there was the option to tick 'send by bcc' or a way to hide the list of recipients from the recipients 

all suggestions gratefully received! 

great plug in, its working really well for us, thank you

best wishes

Belinda (not a coder but has enthusiam and a basic understanding of coding from a 20 year old computer science degree where i coded assembly.. im sure this should be easier to learn!!)

**Comment by belindawaldock** [comment]
here's some code shared by the brilliant support at jobmanager .. i havent tested it as im a bit nervous about giving our admin access to code when we need to add / remove people until weve settled into the feature a bit more, hence my request for a wp tick for bcc which would be the idea, but the code looks good so i wanted to share for anyone else who may like this option via the code!

add_filter( 'resume_manager_new_resume_notification_recipient', 'resume_cc_email' );
function resume_cc_email( $headers ) {
    $headers[] = 'Bcc:emai1@email.com, email2@email.com';
    return $headers;
}

**Comment by tripflex** [comment]
@belindawaldock this looks good to me, you can use the code Snippets plugin to add this if you don't want to edit functions.php file

**Comment by belindawaldock** [comment]
thank you @tripflex i didnt know about the plugin.. will save me breaking the site by missing a tag .. again! :)

**Comment by jom** [comment]
Closing for now. I think this is best resolved using the snippet mentioned.
