### ISSUE TITLE
Feature: Multiple locations in search

### ISSUE THREAD

**Issue by cestrian77** [Automattic/WP-Job-Manager#1217]
Can we either have the ability to add multiple locations to search queries, or apply some sort of fuzzy logic or search radius?

What I mean by this is that it would be great to be able to say to return all results within a certain radius of the primary job location... or to be able to list "city 1, city 2, city 3" in job search queries so that we can build better landing pages with pre-defined search results.

This could then also be used on the job search front end to search by radius or multiple locations.

**Comment by wpfan2099** [comment]
good evening dear cestrian77 

well this is a great idea. Truely - to me it seems some kind of fuzzy-logic topic. 

I would love to see this feature - the ability to add multiple locations to search queries.
Thats it - this could then also be used on the job search front end to search by radius or multiple locations. I like this idea very much!!!

**Comment by jom** [comment]
Requested in 2982672-zd

**Comment by jinnypark** [comment]
Requested in the [forums](https://wordpress.org/support/topic/searching-uk-and-united-kingdom-yields-different-results/)
