### ISSUE TITLE
Bug With Resume preview using jobify theme

### ISSUE THREAD

**Issue by tabrez96** [Automattic/WP-Job-Manager#1219]
![capture](https://user-images.githubusercontent.com/29143166/32092352-b635fc80-bb15-11e7-9804-e01240ffd12c.PNG)

Priority: urgent
this is happening while submitting resumes

**Comment by jom** [comment]
This issues board is just for core WP Job Manager issues. Please contact Astoundify for Jobify support.

**Comment by spencerfinnell** [comment]
(Looks like you just need to remove the duplicate widgets in Appearance > Widgets).
