### ISSUE TITLE
Add Google's Cloud Job Discovery for Job Searching and Results Display

### ISSUE THREAD

**Issue by brenthealy** [Automattic/WP-Job-Manager#1223]
Feature Request

https://cloud.google.com/job-discovery/

Cloud Job Discovery is part of Google for Jobs - a Google-wide commitment to help people find jobs more easily. Job Discovery provides plug and play access to Google’s search and machine learning capabilities, enabling the entire recruiting ecosystem - company career sites, job boards, applicant tracking systems, and staffing agencies to improve job site engagement and candidate conversion.

Developers must request access to this private beta.

**Comment by tsanren89** [comment]
+1 Wish to have this also.

**Comment by jom** [comment]
I don't think this will make it into the core WPJM, but I've added it to a list for consideration of a separate extension.
