### ISSUE TITLE
Logo submission and form issues with WP Job board

### ISSUE THREAD

**Issue by sirjamalot** [Automattic/WP-Job-Manager#1224]
#### Steps to Reproduce
1. Visit http://www.ndma.org.uk/careers-skills-education/ndma-job-board/post-a-job/
2. Attempt to post job, filling in description field
3.

#### What I Expected
Job to post, pending approval

#### What Happened Instead
Error: Description is a required field

#### WordPress / WP Job Manager Version
WP 4.8.3
WP JM 1.29.0

#### Browser / OS Version
Chrome / Windows 10

**Comment by sirjamalot** [comment]
Sorry, meant to add that previously had issues with people posting logos. Logos are posted, but do not come through in the job listing. I can't test this currently because of above problem.

**Comment by jom** [comment]
These should be split into two issues. What plugins do you have installed/activated? It looks like something is clearing your `Description` field.
