### ISSUE TITLE
Featured jobs doesn't work

### ISSUE THREAD

**Issue by bravesloot** [Automattic/WP-Job-Manager#1225]
#### Steps to Reproduce
1. Check "featured post" in a job post
2. Update
3. Nothing happens

#### What I Expected
I expected to see a checkmark in the box and a featured job post at my page

#### What Happened Instead
The box unchecked as soon as I updated my post and nothing happend at the job-page

#### WordPress / WP Job Manager Version
WP version 4.8.3
WP Job Manager version 1.29.0

#### Browser / OS Version
Safari/Mac OS Sierra 10.12.6
Windows 10/ Chrome

**Comment by jom** [comment]
Unable to replicate in WP Admin. Are you saving the post after checking the featured listing box in WP Admin? What other plugins do you have activated? If possible, please provide a screencast.

**Comment by jom** [comment]
Closing for now. Please comment with additional information if you're able to replicate in another environment.
