### ISSUE TITLE
Can 'account required' be set to certain user types rather than all user types 

### ISSUE THREAD

**Issue by belindawaldock** [Automattic/WP-Job-Manager#1227]
#### Steps to Reproduce

Hi i am using the plugin on a tech community website in Cornwall UK www.softwarecornwall.org where we run as a not for profit helping our members to grow their tech organisations in cornwall.  a key part of this is helping them to recruit and your plugin works brilliantly to allow our members to now add jobs themselves rather than us have to manually add them, thank you! 

i would like to limit access to the 'post job' feature to our basic 'subscriber' users who do not have this feature included in their membership. 

I'd really appreciate any advice on how i might be able to implement the above please! is there an add on or other plugin/feature/code i could use please?

thank you  

thoughts... 
1.  
Account Required | Require an account to submit listings Limits job listing submissions to registered, logged-in users.
-- | --

2.  ticking box limited post jobs function to post if logged in user - this allows all/any logged in users of the site to add a jobs post.  this is great as limits this features to our users/members of the community. 

3.  i would like to limit what type of users can add job posts - user types represent different levels of members on our site and what features they can access, eg post news, post jobs, view candidates, post events which we use a variety of plugins to admin. 

www.softwarecornwall.org

#### What I Expected

on the resume manager i can select which user types can view candidates eg employer, which is great, id like to do the same for what user types can submit job posts

#### What Happened Instead
all users can post jobs, unable to limit/select what user types can add jobs

**Comment by jom** [comment]
I don't see his getting integrated into WPJM at this time. You may be able to implement this using third-party plugins that restrict access to pages (such as the job submission page) based on user role.
