### ISSUE TITLE
How to delete log in field on submit form?

### ISSUE THREAD

**Issue by turntable1** [Automattic/WP-Job-Manager#1228]
Hi
How to delete log in field on submit form? 

i look up the "class-wp-job-manager-form-submit-job.php" but i could not figure out.

https://www.screencast.com/t/9bLrtUdZdF3Y

Thanks

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.

There are settings for requiring accounts, etc. in Job Listings > Settings > Job Submission. For further help, please use link above.
