### ISSUE TITLE
Plan To Add More Schema?

### ISSUE THREAD

**Issue by bickelt** [Automattic/WP-Job-Manager#1229]
Curious if there is a plan to add support for the warnings the Google Structured Data Testing Tool throws up in the JobPosting schema (Industry, etc) ? 

![image](https://user-images.githubusercontent.com/6226199/32748059-9a4a41de-c880-11e7-9180-91147bf71261.png)

**Comment by bickelt** [comment]
aybe I am missing something basic, but it seems like Google For Jobs is sort of hot topic right now and that schema is at the heart of it.   Does the WP Job Manager team have any thoughts on this?  Just trying to get a feel for if there is a plan to include support for this at some point.

**Comment by jom** [comment]
Right now we've included the fields WPJM currently ships with. We'd need enhancement requests to add these each new field. When adding the fields we'd make sure they were added to the structured data. If you add these fields using a third-party plugin or hooking into WPJM's filters, you can add them to the structured data using the `wpjm_get_job_listing_structured_data` filter.
