### ISSUE TITLE
Remove dollar sign at zip code number

### ISSUE THREAD

**Issue by penxelstudio** [Automattic/WP-Job-Manager#1231]
![image](https://user-images.githubusercontent.com/32474358/33053644-acbdffce-ceaf-11e7-9a8e-147517c1ec61.png)
As per attached, the zip code number has a dollar sign in front of it. Please help me to remove it.

**Comment by jom** [comment]
That is an issue with your theme.

**Comment by spencerfinnell** [comment]
Not the theme. The automatic output of your custom data. Check your output if you are using the Field Editor plugin.

**Comment by spencerfinnell** [comment]
Looks like you may have duplicated your Salary field code/settings and did not remove the $

**Comment by penxelstudio** [comment]
Th problem is fixed. As advice by @jom I checked the theme and found the problem. Thank you for the help.
