### ISSUE TITLE
Scroll to application area when Apply To Job is clicked

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#1232]
If I click the Apply For Job button, the browser viewport should scroll to have the application details or form at the top (using an anchor or some such). Otherwise I may not be able to tell that anything is happening, e.g. if I'm clicking the Apply For Job button when it's near the bottom of the viewport.

https://wordpress.org/support/topic/scroll-down-when-selecting-apply-for-job-button/

**Comment by deeperlook** [comment]
Second this.
