### ISSUE TITLE
WPJM add-ons lose license keys when updated

### ISSUE THREAD

**Issue by donnapep** [Automattic/WP-Job-Manager#1242]
Originally logged as JPOP issues [#1371](https://github.com/Automattic/jpop-issues/issues/1371).

#### Steps to Reproduce
1. On Day 1, I purchased the WPJM core bundle, then installed and activated both the Applications and Resume Manager plugins. I entered a license key for both.
2. On Day 2, I logged into my site and there were updates available for both the Applications and Resume Manager plugins (I didn't pay attention to what the versions were prior to updating).
3. I clicked on both to update and was taken to another screen where Applications updated without issue.
4. Back on the Plugins page, I clicked to update the Resume Manager plugin again and saw this:
![screen shot 2017-11-28 at 6 36 18 am](https://user-images.githubusercontent.com/1190420/33317855-84dd5a0c-d406-11e7-8d05-e63b15f4f0b0.jpg)
5. When I returned to the Plugins page, both the Applications and Resume Manager plugins had lost their license keys:
![screen shot 2017-11-28 at 6 11 31 am](https://user-images.githubusercontent.com/1190420/33316754-18ddc77c-d403-11e7-9623-97a56257e283.jpg)

#### What I Expected
Both the Applications and Resume Manager plugins to update without issue, and for the license keys to persist.

#### What Happened Instead
Both plugins lost their license keys.

#### WordPress / WP Job Manager Version
WordPress 5.0-alpha-42247
WPJM 1.29.0
WPJM - Applications 2.3.0 (post-update)
WPJM - Resume Manager 1.16.0 (post-update)

#### Browser / OS Version
Chrome 62.0.3202.94
MacOS 10.12.6

**Comment by jom** [comment]
This might be unrelated to the original issue. I'd like to try to reproduce this again and capture what the version was being reported as before doing the update. No update should have been reported.
