### ISSUE TITLE
After update 1.29.1 I getting HTTP error 500

### ISSUE THREAD

**Issue by tsanren89** [Automattic/WP-Job-Manager#1246]
Hi,

After updated to 1.29.1 I getting HTTP error 500.

Any solution?

Thanks

**Comment by jom** [comment]
Do you have access to your PHP error log? You can also try enabling the `wp-content/debug.log` by putting this in your `wp-config.php`:

```
define( 'WP_DEBUG', true );
if ( WP_DEBUG ) {
	@error_reporting( E_ALL );
	@ini_set( 'log_errors', true );
	@ini_set( 'log_errors_max_len', '0' );
	define( 'WP_DEBUG_LOG', true );
	define( 'WP_DEBUG_DISPLAY', false );
}
```

**Comment by jom** [comment]
Closing for now. Feel free comment again if you're able to post steps to reproduce.
