### ISSUE TITLE
Help request: override company logo via child theme

### ISSUE THREAD

**Issue by cestrian77** [Automattic/WP-Job-Manager#1247]
If using WP Job Manager for a single company, it would be helpful to avoid the need to upload the logo each time a new vacancy is added. 

Whilst we can easily upload a new company.png file to the plugin folder's assets/images/ location, this file will be overwritten each time the plugin is updated.

I know I can do template overrides with child themes that work even with plugin updates, but is it possible to do the same with these fixed assets?

Thanks

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.

For the enhancement request embedded, these are similar: #1135; #1086
