### ISSUE TITLE
Feature Request: Display Job Application

### ISSUE THREAD

**Issue by piersb** [Automattic/WP-Job-Manager#1248]
Our client would like the ability for candidates to view their previous job applications.

Is there any chance that this could be added to the roadmap?

**Comment by jom** [comment]
This is just for the core WP Job Manager plugin, but I've added it to the repo for the applications plugin. No ETA, there is some backlog of other enhancements. Thanks for letting us know!

**Comment by jom** [comment]
@piersb Looks like there already is a shortcode for this. @aheckler reminded me about `[past_applications]`.

**Comment by piersb** [comment]
Thanks - sadly it just shows that you've applied. What we're really after is the application data itself, so you can see what you sent to them.
