### ISSUE TITLE
How To show 20 Jobs in RSS

### ISSUE THREAD

**Issue by Madi99** [Automattic/WP-Job-Manager#1250]
in rss jobs,  http://mysite.com/?feed=job_feed  only show 10 jobs. How To show 20 Jobs in RSS? or all jobs?

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.

You can use the `posts_per_page` query var. http://example.com/?feed=job_feed&posts_per_page=50

**Comment by Madi99** [comment]
thanks bro, u save me
