### ISSUE TITLE
Duplicate listings show up on Listings page

### ISSUE THREAD

**Issue by seymourdesign** [Automattic/WP-Job-Manager#1254]
I am getting duplicates of the same listings. I double checked to make sure there were not duplicates in the files and there are not. 
I switched from Apus Prolist to another theme to double check it and it occurred in the other theme as well. I am very frustrated as I need to get this site up ASAP.

Wordpress ersion 4.9.1/WP Job Manager 1.29.2
Firefox Quantam
![screen shot 2017-12-05 at 10 57 45 am](https://user-images.githubusercontent.com/34239763/33616542-2ab4c04c-d9ab-11e7-99e5-bf596169215b.png)

![screen shot 2017-12-05 at 10 56 28 am](https://user-images.githubusercontent.com/34239763/33616485-0006554a-d9ab-11e7-979f-c892521cc9d5.png)

**Comment by jom** [comment]
Please provide URL for reproducing as well as list of plugins.

**Comment by seymourdesign** [comment]
I have it as being under construction, here is the login:

http://seymourdesignnewwebsite.com/ <http://seymourdesignnewwebsite.com/>
user: cseymour
password: Adoption$6804105


Apus Framework
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=apus-framework%2Fapus-framework.php&plugin_status=all&paged=1&s&_wpnonce=50f2aac87c>	
Apus framework for wordpress theme

Version 1.0 | By Team ApusTheme <http://apusthemes.com/> | Visit plugin site <http://apusthemes.com/>
Select Apus Prolist	Apus Prolist
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=apus-prolist%2Fapus-prolist.php&plugin_status=all&paged=1&s&_wpnonce=2470675f60>	
Apus Prolist is a plugin for Prolist directory listing theme

Version 1.0.0 | By ApusTheme <http://apusthemes.com/> | Visit plugin site <http://apusthemes.com/booking/>
Select BackWPup	BackWPup
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=backwpup%2Fbackwpup.php&plugin_status=all&paged=1&s&_wpnonce=48dcfdb5fc>	
WordPress Backup Plugin

Version 3.4.4 | By Inpsyde GmbH <http://inpsyde.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=backwpup&TB_iframe=true&width=600&height=550> | Documentation <http://docs.backwpup.com/>
Select Blog Designer	Blog Designer
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=blog-designer%2Fblog-designer.php&plugin_status=all&paged=1&s&_wpnonce=f8d95e4bdc> | Documentation <https://www.solwininfotech.com/documents/wordpress/blogdesigner-lite/> | Upgrade <https://codecanyon.net/item/blog-designer-pro-for-wordpress/17069678?ref=solwin>	
To make your blog design more pretty, attractive and colorful.

Version 1.8.4.1 | By Solwin Infotech <https://www.solwininfotech.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=blog-designer&TB_iframe=true&width=600&height=550>
Select CMB2	CMB2
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=cmb2%2Finit.php&plugin_status=all&paged=1&s&_wpnonce=a132ca5eca>	
CMB2 will create metaboxes and forms with custom fields that will blow your mind.

Version 2.2.6.2 | By CMB2 team <https://cmb2.io/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=cmb2&TB_iframe=true&width=600&height=550>

Disable Google Fonts
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=disable-google-fonts%2Fdisable-google-fonts.php&plugin_status=all&paged=1&s&_wpnonce=ade8d33b5f>	
Disable enqueuing of Open Sans and other fonts used by WordPress from Google.

Version 1.3 | By Milan Dinić <http://blog.milandinic.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=disable-google-fonts&TB_iframe=true&width=600&height=550>
Select Formidable Forms	Formidable Forms
Settings <http://seymourdesignnewwebsite.com/wp-admin/admin.php?page=formidable-settings> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=formidable%2Fformidable.php&plugin_status=all&paged=1&s&_wpnonce=3d64e45421>	
Quickly and easily create drag-and-drop forms

Version 2.05.07 | By Strategy11 <https://formidableforms.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=formidable&TB_iframe=true&width=600&height=550>
Select Give - Donation Plugin	Give - Donation Plugin
Settings <http://seymourdesignnewwebsite.com/wp-admin/edit.php?post_type=give_forms&page=give-settings> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=give%2Fgive.php&plugin_status=all&paged=1&s&_wpnonce=87469454b0>	
The most robust, flexible, and intuitive way to accept donations on WordPress.

Version 1.8.16 | By WordImpress <https://wordimpress.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=give&TB_iframe=true&width=600&height=550> | Documentation <https://givewp.com/documentation/?utm_source=plugins-page&utm_medium=plugin-row&utm_campaign=admin> | Add-ons <https://givewp.com/addons/?utm_source=plugins-page&utm_medium=plugin-row&utm_campaign=admin>
MailChimp for WordPress
Settings <http://seymourdesignnewwebsite.com/wp-admin/admin.php?page=mailchimp-for-wp> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=mailchimp-for-wp%2Fmailchimp-for-wp.php&plugin_status=all&paged=1&s&_wpnonce=c0aa8456f5>	
MailChimp for WordPress by ibericode. Adds various highly effective sign-up methods to your site.

Version 4.1.11 | By ibericode <https://ibericode.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=mailchimp-for-wp&TB_iframe=true&width=600&height=550> | Documentation <https://kb.mc4wp.com/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=plugins-page> | Upgrade to Premium <https://mc4wp.com/premium-features/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=plugins-upgrade-link>

MailChimp WD
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php#>	
MailChimp WD is a functional plugin developed to create MailChimp subscribe/unsubscribe forms and manage lists from your WordPress site.

Version 1.0.15 | By WebDorado <https://web-dorado.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=wd-mailchimp&TB_iframe=true&width=600&height=550>
Select Ninja Forms	Ninja Forms
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=ninja-forms%2Fninja-forms.php&plugin_status=all&paged=1&s&_wpnonce=cbd898841a>	
Ninja Forms is a webform builder with unparalleled ease of use and features.

Version 3.2.4 | By The WP Ninjas <http://ninjaforms.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=ninja-forms&TB_iframe=true&width=600&height=550>
Select P3 (Plugin Performance Profiler)	P3 (Plugin Performance Profiler)
Scan Now <http://seymourdesignnewwebsite.com/wp-admin/tools.php?page=p3-profiler> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=p3-profiler%2Fp3-profiler.php&plugin_status=all&paged=1&s&_wpnonce=e0027950b6>	
See which plugins are slowing down your site. Create a profile of your WordPress site's plugins' performance by measuring their impact on your site's load time.

Version 1.5.3.9 | By GoDaddy.com <http://www.godaddy.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=p3-profiler&TB_iframe=true&width=600&height=550>
Select Slider Revolution	Slider Revolution
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=revslider%2Frevslider.php&plugin_status=all&paged=1&s&_wpnonce=f469f9520c>	
Slider Revolution - Premium responsive slider

Version 5.4.6.4 | By ThemePunch <http://themepunch.com/> | Visit plugin site <http://revolution.themepunch.com/>
Select Social Media Feather	Social Media Feather
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=social-media-feather%2Fsocial-media-feather.php&plugin_status=all&paged=1&s&_wpnonce=106def9fb6> | Settings <http://seymourdesignnewwebsite.com/wp-admin/options-general.php?page=synved_social_settings>	
Super lightweight social media plugin to add nice and effective social media sharing and following buttons and icons anywhere on your site quickly and easily

Version 1.8.4 | By socialmediafeather <http://socialmediafeather.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=social-media-feather&TB_iframe=true&width=600&height=550>
Select SVG Support	SVG Support
Settings <http://seymourdesignnewwebsite.com/wp-admin/options-general.php?page=svg-support> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=svg-support%2Fsvg-support.php&plugin_status=all&paged=1&s&_wpnonce=436e3e537c>	
Allow SVG file uploads using the WordPress Media Library uploader plus the ability to inline SVG files for direct styling/animation of SVG elements using CSS/JS.

Version 2.3.11 | By Benbodhi <http://benbodhi.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=svg-support&TB_iframe=true&width=600&height=550> | Get Support <https://wordpress.org/support/plugin/svg-support> | Donate to author <https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=Z9R7JERS82EQQ> | $25 Free Credit from GoWebben <https://secure.gowebben.com/cart.php?promocode=SVGSUPPORT>
Ultimate Social Media PLUS
Opt In <http://seymourdesignnewwebsite.com/wp-admin/admin.php?nonce=66d4459b71&fs_action=ultimate-social-media-plus_reconnect&page=sfsi-plus-options> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=ultimate-social-media-plus%2Fultimate_social_media_icons.php&plugin_status=all&paged=1&s&_wpnonce=e763e958c1> | Check out pro version <https://www.ultimatelysocial.com/usm-premium/?utm_source=usmplus_manage_plugin_page&utm_campaign=check_out_pro_version&utm_medium=banner> | | Settings <http://seymourdesignnewwebsite.com/wp-admin/admin.php?page=sfsi-plus-options>	
The best social media plugin on the market. And 100% FREE. Allows you to add social media & share icons to your blog (esp. Facebook, Twitter, Email, RSS, Pinterest, Instagram, Google+, LinkedIn, Share-button). It offers a wide range of design options and other features.

Version 2.7.5 | By UltimatelySocial <http://ultimatelysocial.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=ultimate-social-media-plus&TB_iframe=true&width=600&height=550>

Under Construction
Settings <http://seymourdesignnewwebsite.com/wp-admin/options-general.php?page=ucp> | Go PRO <https://underconstructionpage.com/?utm_source=ucp-free&utm_medium=plugin&utm_content=plugins-table-left&utm_campaign=ucp-free-v2.80> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=under-construction-page%2Funder-construction.php&plugin_status=all&paged=1&s&_wpnonce=a5135f1cee>	
Put your site behind a great looking under construction, coming soon, maintenance mode or landing page.

Version 2.80 | By Web factory Ltd <http://www.webfactoryltd.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=under-construction-page&TB_iframe=true&width=600&height=550> | Support <https://wordpress.org/support/plugin/under-construction-page> | Get the PRO version <https://underconstructionpage.com/?utm_source=ucp-free&utm_medium=plugin&utm_content=plugins-table-right&utm_campaign=ucp-free-v2.80>
Select UpdraftPlus - Backup/Restore	UpdraftPlus - Backup/Restore
Manage Addons <http://seymourdesignnewwebsite.com/wp-admin/options-general.php?page=updraftplus&tab=addons> | Add-Ons / Pro Support <https://updraftplus.com/> | Settings <http://seymourdesignnewwebsite.com/wp-admin/options-general.php?page=updraftplus> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=updraftplus%2Fupdraftplus.php&plugin_status=all&paged=1&s&_wpnonce=078be053f5>	
Backup and restore: take backups locally, or backup to Amazon S3, Dropbox, Google Drive, Rackspace, (S)FTP, WebDAV & email, on automatic schedules.

Version 2.13.7.1 | By UpdraftPlus.Com, DavidAnderson <https://updraftplus.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=updraftplus&TB_iframe=true&width=600&height=550>
Select WooCommerce	WooCommerce
Settings <http://seymourdesignnewwebsite.com/wp-admin/admin.php?page=wc-settings> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=woocommerce%2Fwoocommerce.php&plugin_status=all&paged=1&s&_wpnonce=3b7571b129>	
An e-commerce toolkit that helps you sell anything. Beautifully.

Version 3.2.5 | By Automattic <https://woocommerce.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=woocommerce&TB_iframe=true&width=600&height=550> | Docs <https://docs.woocommerce.com/documentation/plugins/woocommerce/> | API docs <https://docs.woocommerce.com/wc-apidocs/> | Premium support <https://woocommerce.com/my-account/tickets/>
Select WooCommerce Quantity Increment	WooCommerce Quantity Increment
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=woocommerce-quantity-increment%2Fwoocommerce-quantity-increment.php&plugin_status=all&paged=1&s&_wpnonce=5c8b5081d0>	
WooCommerce Quantity Increment adds JavaScript powered quantity buttons to your cart page.

Version 1.1.0 | By Automattic, WooThemes <https://woocommerce.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=woocommerce-quantity-increment&TB_iframe=true&width=600&height=550>

WordPress Social Login
Settings <http://seymourdesignnewwebsite.com/wp-admin/options-general.php?page=wordpress-social-login> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=wordpress-social-login%2Fwp-social-login.php&plugin_status=all&paged=1&s&_wpnonce=5b0c3cd9b7>	
Allow your visitors to comment and login with social networks such as Twitter, Facebook, Google, Yahoo and more.

Version 2.3.3 | By Miled <https://github.com/miled> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=wordpress-social-login&TB_iframe=true&width=600&height=550> | Docs <http://miled.github.io/wordpress-social-login/> | Support <http://miled.github.io/wordpress-social-login/support.html> | Fork me on Github <https://github.com/miled/wordpress-social-login>
Select WP Fastest Cache	


WP Job Manager
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=wp-job-manager%2Fwp-job-manager.php&plugin_status=all&paged=1&s&_wpnonce=a03bc6a556>	
Manage job listings from the WordPress admin panel, and allow users to post jobs directly to your site.

Version 1.29.2 | By Automattic <https://wpjobmanager.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=wp-job-manager&TB_iframe=true&width=600&height=550>
Select WPBakery Visual Composer	WPBakery Visual Composer
Settings <http://seymourdesignnewwebsite.com/wp-admin/admin.php?page=vc-general> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=js_composer%2Fjs_composer.php&plugin_status=all&paged=1&s&_wpnonce=ce88dfad9b>	
Drag and drop page builder for WordPress. Take full control over your WordPress site, build any layout you can imagine – no programming knowledge required.

Version 5.2.1 | By Michael M - WPBakery.com <http://wpbakery.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=js_composer&TB_iframe=true&width=600&height=550>
There is a new version of WPBakery Visual Composer available. View version 5.4.5 details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=js_composer&section=changelog&TB_iframe=true&width=600&height=800>. Automatic update is unavailable for this plugin. To receive automatic updates license activation is required. Please visit settings <http://seymourdesignnewwebsite.com/wp-admin/admin.php?page=vc-updater> to activate your Visual Composer. Got Visual Composer in theme? <http://go.wpbakery.com/faq-update-in-theme>
Select Yellow Pencil Lite	Yellow Pencil Lite
Customize <http://seymourdesignnewwebsite.com/wp-admin/themes.php?page=yellow-pencil> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=yellow-pencil-visual-theme-customizer%2Fyellow-pencil.php&plugin_status=all&paged=1&s&_wpnonce=4175b03708>	
The most advanced visual CSS editor. Customize any theme and any page in real-time without coding.

Version 6.1.4 | By WaspThemes <http://www.waspthemes.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=yellow-pencil-visual-theme-customizer&TB_iframe=true&width=600&height=550> | Documentation <http://waspthemes.com/yellow-pencil/documentation/>
Select YITH WooCommerce Subscription	YITH WooCommerce Subscription
Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=yith-woocommerce-subscription%2Finit.php&plugin_status=all&paged=1&s&_wpnonce=a0557eb132> | Settings <http://seymourdesignnewwebsite.com/wp-admin/admin.php?page=yith_woocommerce_subscription> | Premium Version <http://yithemes.com/themes/plugins/yith-woocommerce-subscription/?refer_id=1030585>	
YITH WooCommerce Subscription

Version 1.2.0 | By YITHEMES <http://yithemes.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=yith-woocommerce-subscription&TB_iframe=true&width=600&height=550> | Plugin Documentation <https://yithemes.com/docs-plugins/yith-woocommerce-subscription/>
Select Yoast SEO	Yoast SEO
FAQ <https://kb.yoast.com/kb/category/yoast-seo/#utm_source=wordpress-seo-faq-link&utm_medium=textlink&utm_campaign=faq-link> | Premium Support <https://yoast.com/wordpress/plugins/seo-premium/support/#utm_source=wordpress-seo-settings-link&utm_medium=textlink&utm_campaign=support-link> | Settings <http://seymourdesignnewwebsite.com/wp-admin/admin.php?page=wpseo_dashboard> | Deactivate <http://seymourdesignnewwebsite.com/wp-admin/plugins.php?action=deactivate&plugin=wordpress-seo%2Fwp-seo.php&plugin_status=all&paged=1&s&_wpnonce=fce6b70577>	
The first true all-in-one SEO solution for WordPress, including on-page content analysis, XML sitemaps and much more.

Version 5.9.1 | By Team Yoast <https://yoast.com/> | View details <http://seymourdesignnewwebsite.com/wp-admin/plugin-install.php?tab=plugin-information&plugin=wordpress-seo&TB_iframe=true&width=600&height=550>






COLLEEN SEYMOUR • SEYMOURDESIGNMAINE.COM • 207.232.3812

**Comment by jom** [comment]
Please change your password as you just posted it publicly on GitHub. I've removed it from the comment.

You need to make the site publicly accessible for us to reproduce it here. Note: GitHub issues isn't for support. For support, please visit https://wpjobmanager.com/support. This is only for posting _reproduceable_ (through a list of steps) issues.

**Comment by seymourdesign** [comment]
I thought this was support. I have removed the under construction so you can look at it now. http://seymourdesignnewwebsite.com



COLLEEN SEYMOUR • SEYMOURDESIGNMAINE.COM • 207.232.3812

**Comment by jom** [comment]
Notice is still there.

**Comment by seymourdesign** [comment]
try now


COLLEEN SEYMOUR • SEYMOURDESIGNMAINE.COM • 207.232.3812

**Comment by jom** [comment]
I can see the issue. To come up with reproducible steps, you may need to set up a staging site and deactivate all other plugins and set the theme to twenty seventeen to isolate the issue. It looks like your theme is making modifications to the standard `[jobs]` shortcode.

**Comment by seymourdesign** [comment]
This is a staging site. I am using one of my urls to create the new site while the exisitng one is on the original site. I have deactivated all the plugins and switched it to seventeen. 




COLLEEN SEYMOUR • SEYMOURDESIGNMAINE.COM • 207.232.3812

**Comment by jom** [comment]
You need to have at least WP Job Manager enabled. If the issue persists with all other plugins disabled, we'll need to come up with steps to reproduce outside of this site. 

Otherwise, I'd recommend slowly reactivating plugins / change theme (one by one) to see where the issue is. If it is with your theme, you may need to contact them.

**Comment by seymourdesign** [comment]
it is enabled, and still getting duplicates.



COLLEEN SEYMOUR • SEYMOURDESIGNMAINE.COM • 207.232.3812

**Comment by jom** [comment]
I was able to reproduce locally. We'll investigate and push out a fix soon. Thanks for the report!

**Comment by seymourdesign** [comment]
thank you for your help!


COLLEEN SEYMOUR • SEYMOURDESIGNMAINE.COM • 207.232.3812

**Comment by jom** [comment]
I think I found the problem. It showed up for me because I had posts created at the same time. A fix will be out in the next release, but one workaround is setting your shortcode's `orderby` option to:
`[jobs orderby=ID]`

You can also add a `order=ASC` to reverse that order.

**Comment by seymourdesign** [comment]
Great! that worked!


COLLEEN SEYMOUR • SEYMOURDESIGNMAINE.COM • 207.232.3812
