### ISSUE TITLE
Can't access posts using WORDPRESS REST API

### ISSUE THREAD

**Issue by phoenixvk** [Automattic/WP-Job-Manager#1258]
I used curl on http://example.com/wp-json/wp/v2/posts. But not able to access the jobs that I have created from admin panel. I tried editing constant **WPJM_REST_API_ENABLED** to true from **wp-config.php** but then also I am getting same response. Can't I access wordpress rest api?

**Comment by jom** [comment]
We haven't launched this feature yet and it may change, but with the constant you mentioned set to `true` you can access job listings from this endpoint:
`http://example.com/wp-json/wp/v2/job-listings`

See #1060 for more info.

**Comment by phoenixvk** [comment]
Man this is awesome. I am very grateful to you. <3
