### ISSUE TITLE
Feature Request: Pending Payment on Job Dashboard

### ISSUE THREAD

**Issue by GuilhermeMReis** [Automattic/WP-Job-Manager#1259]
We can see an ad once its been 'reviewed' at the Job Dashboard. Is it possible to show on their account as pending payment? Because it's good for the client understand that everything its in the process.

**Comment by linoman-zz** [comment]
good evening dear GuilhermeMReis; Many thanks for bringing this issue to the public awareness. I am very very glad. Sure thing: it is very important  to look at the clients view on all that: it is very good for the client understand that everything its in the process.

**Comment by jom** [comment]
Payment isn't something that is part of WPJM core. Closing as this is just for core, but if you let me know if you're using one of our core extensions (such as WC Paid Listings or Simple Paid Listings) I'll make sure this is recorded as an enhancement request for those plugins.
