### ISSUE TITLE
AMP not showing "APPLY FOR JOB" button

### ISSUE THREAD

**Issue by tsanren89** [Automattic/WP-Job-Manager#1261]
Hi there,

I install AMP for WP plugin, and also purchase Custom Post Type extension to display job listing in AMP.

But for AMP site, not showing "APPLY FOR JOB" button after Job Overview.

Normal site: [https://betteraviationjobs.com/job/aerologic-first-officer-december-2017/](https://betteraviationjobs.com/job/aerologic-first-officer-december-2017/)
AMP site: [https://betteraviationjobs.com/job/aerologic-first-officer-december-2017/amp](https://betteraviationjobs.com/job/aerologic-first-officer-december-2017/ampl)

Any solution on this?

Thanks and appreciated.

**Comment by gitblair** [comment]
+ this

**Comment by djanym** [comment]
Any news on this? The issue still exists.

**Comment by cena** [comment]
reported in 1879276-zen

**Comment by mikeyarce** [comment]
Just adding a note that it looks like with the latest version of the official AMP plugin, jobs are not supported and don't have an AMP version.
