### ISSUE TITLE
For mobile display: using DIV-based layout rather than a straight-up HTML table: 

### ISSUE THREAD

**Issue by htdat** [Automattic/WP-Job-Manager#1265]
### Enhancement: 

I have noticed that the jobs dashboard has been created as a straight-up HTML table, which makes it hard to scale it back for mobile fruition. Would it be possible to see a DIV-based layout in the future? 

### Notices: 

* I do realize this would need to be coordinated with theme authors as well, though, so it's alright if it weren't feasible.

* Basically this requires a huge refactor in the templates of the core plugin, extensions, and themes. 

### Other info

Tix: 864584-zen

**Comment by linoman-zz** [comment]
Hello dear htfat, many many thanks for this heads-up: thanks for raising this topic with this major-important issue. This is one of the most important things we have to work on.
Admit it: Having a beautiful and fully functioning mobile version of your WordPress website is a must, considering that the significant volume of the internet surfing originates from mobile devices.

We need to work on this.  This is so important!!!

**Comment by AiratHalitov** [comment]
You can see good example on page: `/wp-admin/edit.php `

**Comment by aheckler** [comment]
@AiratHalitov As I mentioned here:

https://wordpress.org/support/topic/optimization-for-mobile-devices-2/#post-9874012

This issue is about the Job Dashboard page specifically, not the WordPress backend pages.

**Comment by richardmtl** [comment]
2695639-zen

**Comment by navinp** [comment]
So what I am asking is: how can I use/where should I look for / existing classes or ID's to it (the table) can inherit its already-nice-looking-build-in layout.

**Comment by navinp** [comment]
Okay, I did some "rewriting" tonight, using existing code.

The shortcode [job_dashboard] is backed by this page: 
https://github.com/Automattic/WP-Job-Manager/blob/master/templates/job-dashboard.php

I took this table, which is showcased in the TwentyTwenty-demo

`<table cellspacing="0" cellpadding="0">
<tbody><tr>
<th>Table Header 1</th>
<th>Table Header 2</th>
<th>Table Header 3</th>
</tr>
<tr>
<td>Division 1</td>
<td>Division 2</td>
<td>Division 3</td>
</tr>
<tr class="even">
<td>Division 1</td>
<td>Division 2</td>
<td>Division 3</td>
</tr>
<tr>
<td>Division 1</td>
<td>Division 2</td>
<td>Division 3</td>
</tr>
</tbody></table>`



`<table cellspacing="0" cellpadding="0">
	<tbody>
		<tr>
            <?php foreach ( $job_dashboard_columns as $key => $column ) : ?>
                <th class="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $column ); ?></th>
            <?php endforeach; ?>
		</tr>
		<tr>
            <?php if ( ! $jobs ) : ?>
			     <td colspan="<?php echo intval( count( $job_dashboard_columns ) ); ?>"><?php esc_html_e( 'You do not have any active listings.', 'wp-job-manager' ); ?></td>
        </tr>
        <?php else : ?>
				<?php foreach ( $jobs as $job ) : ?>
        <tr>
            <?php foreach ( $job_dashboard_columns as $key => $column ) : ?>
			     <td>
                     <?php if ('job_title' === $key ) : ?>
									<?php if ( $job->post_status == 'publish' ) : ?>
										<a href="<?php echo esc_url( get_permalink( $job->ID ) ); ?>"><?php wpjm_the_job_title( $job ); ?></a>
									<?php else : ?>
										<?php wpjm_the_job_title( $job ); ?> <small>(<?php the_job_status( $job ); ?>)</small>
									<?php endif; ?>
									<?php echo is_position_featured( $job ) ? '<span class="featured-job-icon" title="' . esc_attr__( 'Featured Job', 'wp-job-manager' ) . '"></span>' : ''; ?>
									<ul class="job-dashboard-actions">
										<?php
											$actions = [];

											switch ( $job->post_status ) {
												case 'publish' :
													if ( WP_Job_Manager_Post_Types::job_is_editable( $job->ID ) ) {
														$actions[ 'edit' ] = [ 'label' => __( 'Edit', 'wp-job-manager' ), 'nonce' => false ];
													}
													if ( is_position_filled( $job ) ) {
														$actions['mark_not_filled'] = [ 'label' => __( 'Mark not filled', 'wp-job-manager' ), 'nonce' => true ];
													} else {
														$actions['mark_filled'] = [ 'label' => __( 'Mark filled', 'wp-job-manager' ), 'nonce' => true ];
													}

													$actions['duplicate'] = [ 'label' => __( 'Duplicate', 'wp-job-manager' ), 'nonce' => true ];
													break;
												case 'expired' :
													if ( job_manager_get_permalink( 'submit_job_form' ) ) {
														$actions['relist'] = [ 'label' => __( 'Relist', 'wp-job-manager' ), 'nonce' => true ];
													}
													break;
												case 'pending_payment' :
												case 'pending' :
													if ( WP_Job_Manager_Post_Types::job_is_editable( $job->ID ) ) {
														$actions['edit'] = [ 'label' => __( 'Edit', 'wp-job-manager' ), 'nonce' => false ];
													}
												break;
												case 'draft' :
												case 'preview' :
													$actions['continue'] = [ 'label' => __( 'Continue Submission', 'wp-job-manager' ), 'nonce' => true ];
													break;
											}

											$actions['delete'] = [ 'label' => __( 'Delete', 'wp-job-manager' ), 'nonce' => true ];
											$actions           = apply_filters( 'job_manager_my_job_actions', $actions, $job );

											foreach ( $actions as $action => $value ) {
												$action_url = add_query_arg( [ 'action' => $action, 'job_id' => $job->ID ] );
												if ( $value['nonce'] ) {
													$action_url = wp_nonce_url( $action_url, 'job_manager_my_job_actions' );
												}
												echo '<li><a href="' . esc_url( $action_url ) . '" class="job-dashboard-action-' . esc_attr( $action ) . '">' . esc_html( $value['label'] ) . '</a></li>';
											}
										?>
									</ul>
								<?php elseif ('date' === $key ) : ?>
									<?php echo esc_html( date_i18n( get_option( 'date_format' ), strtotime( $job->post_date ) ) ); ?>
								<?php elseif ('expires' === $key ) : ?>
									<?php echo esc_html( $job->_job_expires ? date_i18n( get_option( 'date_format' ), strtotime( $job->_job_expires ) ) : '&ndash;' ); ?>
								<?php elseif ('filled' === $key ) : ?>
									<?php echo is_position_filled( $job ) ? '&#10004;' : '&ndash;'; ?>
								<?php else : ?>
									<?php do_action( 'job_manager_job_dashboard_column_' . $key, $job ); ?>
								<?php endif; ?>
             </td>
            <?php endforeach; ?>
		
		</tr>
        <?php endforeach; ?>
			<?php endif; ?>

	</tbody>
</table>`

**Comment by gflower1** [comment]
How is mobile-responsive tables still a low priority after 2.5 years?

**Comment by gikaragia** [comment]
Relates to #1500

**Comment by yscik** [comment]
Done in https://github.com/Automattic/WP-Job-Manager/releases/tag/2.3.0
