### ISSUE TITLE
Text apearing for "Sending Email" is incorrect when clicking in "Apply for a Job" in Spanish

### ISSUE THREAD

**Issue by titotullidito** [Automattic/WP-Job-Manager#1266]
Text appearing when Apply for a Job is clicked is incorrect in Spanish, the text appearing below is:
"Para postural a ésta oferta laboral envier un email a ejemplo@ejemplo.com".

The text mentioned above contain 2 spelling mistakes;
1. The word "postural", must be set to "postular"
2. The word "envier", must be set to "enviar"

I'm using WP Job Manager plugin for WordPress version 4.7.8

Can anyone knows how to solve this issues?, i'm using a Test Environment an i'm not programmer, just a front-end user.

Suggestions:
Could be helpful adding a link markup reference in the email address showed in the text, because isn´t intuitive.

Thanks in advance.

**Comment by jom** [comment]
Hi there! Thanks for reporting this translation issue. Translations are done by community members. I'm not sure where your translation came from. WP Job Manager doesn't ship with any, but some plugins download them for you. You can contribute to the translations for the plugin and check for any updates here:
https://translate.wordpress.org/projects/wp-plugins/wp-job-manager
