### ISSUE TITLE
WP-Job-Manager REST API job categories

### ISSUE THREAD

**Issue by phoenixvk** [Automattic/WP-Job-Manager#1267]
**This is question not the bug in WP-Job-Manager.**

I can view job-listing and job-types using REST API. But how to access job-categories using REST API?

**Comment by phoenixvk** [comment]
Anyone do have any idea about it?

**Comment by phoenixvk** [comment]
@jom Can you tell me anything?

**Comment by jom** [comment]
This hasn't been implemented yet.

**Comment by jom** [comment]
Actually, I'm going to reopen to track this. I couldn't find another issue.

**Comment by phoenixvk** [comment]
Hey @jom thankew for your reply will you tell me keypoints and files to change to make this happen?

**Comment by Nisha9219** [comment]
I can view job-listing and job-types using REST API. But how to access job-categories using REST API?

**Comment by Nisha9219** [comment]
plz help me

**Comment by richardmtl** [comment]
@Nisha9219 the REST API for WPJM is not documented nor ready yet.

**Comment by Nisha9219** [comment]
Is it Possible to get Json Out put Using Any API plugin I.e rest api,jet pack or json api. by this plugin we are getting out put for default post and categories but we want for all jobs or job categories.Also is their any way to generate rss feed of all jobs and job categories. by when we can expect document ready.
