### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by CareerSearch** [Automattic/WP-Job-Manager#1270]
I have recently moved the Jobify site from Crazy domains to a new server and with this plugin on the ad packages page i get this message where the Ad packs are?
when I deactivate the plugin it disappears 

Fatal error: Class 'WP_Job_Manager_WCPL_Submit_Resume_Form' not found in /home/carevger/public_html/wp-content/themes/jobify/inc/integrations/wp-job-manager-wc-paid-listings/widgets/class-widget-price-table.php on line 73

**Comment by jom** [comment]
Please contact your theme author for support with errors within the theme. It looks like it is expecting the WooCommerce Paid Listings plugin to be active.

**Comment by CareerSearch** [comment]
Ok thank you

 

Waal

**Comment by spencerfinnell** [comment]
Looks like the plugin might have become inactive while the widget remained in place. Ensure the plugins previously activated remain active.

**Comment by CareerSearch** [comment]
I have activated, deactivated and reactivated and it comes up with the same message?

 

I will just work around the problem 

 

Have you seen this before?

 

 

Waal
