### ISSUE TITLE
How I can remove the schema code from the plugin.

### ISSUE THREAD

**Issue by veronika6987** [Automattic/WP-Job-Manager#1276]
Hi,

I've implemented this plugin for the job posting, but it is causing me lots of errors in Google schema. Could you please let me know how I can remove the Job posting schema?

Thanks,

Veronika

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. In the future, for support, please visit https://wpjobmanager.com/support.

If you're on the most recent version: 
```php
add_filter( 'wpjm_output_job_listing_structured_data', '__return_false' );
```
