### ISSUE TITLE
Limit number of job alerts per user

### ISSUE THREAD

**Issue by bcristian2** [Automattic/WP-Job-Manager#1284]
Hi everyone.

I'm sure has faced this issue before, I just can't seem to find the magic solution for it.

How would one go about to limit the number of job alerts a user can create to 3, for example? I'm looking at a solution to avoid daily mass-mailings that would load up the server / lead to marking as spam by e-mail hosts.

Thank you ever so much.

**Comment by jom** [comment]
This is for WP Job Manager core, not the plugins. I'll track this issue for the alerts plugin.
