### ISSUE TITLE
Resume Manager + Visibility

### ISSUE THREAD

**Issue by rafaelsartoribr** [Automattic/WP-Job-Manager#1285]
Hello Mike, how are you?

I'm using resume manager with visibility plugin. I have a issue when i hide some fields for a user role.

The employer field and the resume_file field didn't show the message setup on visibilities. The plugin hide the field, what is great, but didnt show the message.

Cheers!

#### Steps to Reproduce
1.
2.
3.

#### WordPress / WP Job Manager Version

Latest

#### Browser / OS Version

Latest

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core WP Job Manager plugin. For support, please visit https://wpjobmanager.com/support.

**Comment by rafaelsartoribr** [comment]
Thanks Jom!
