### ISSUE TITLE
Update add-ons page to use REST API

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1288]
Right now the add-ons page is currently being pulled from https://wpjobmanager.com/add-ons and is dependent on consistent structuring of the products on that page. We should change that over to a REST API call to wpjobmanager.com to decouple that from the design/structure of that page.

**Comment by wpfan2099** [comment]
Thanks for your idea. I like this idea!! We should work on this!! Many many thanks for the engagement and all you do!! Keep up the great work - it rocks!!
