### ISSUE TITLE
Admin approval for editing existing listings

### ISSUE THREAD

**Issue by raduconst** [Automattic/WP-Job-Manager#1290]
For now, an option called _Moderate New Listings_ can be used when users add listings to a website and need admin approval. 
However, a lot of users are looking for an option to make editing of existing listings wait for approval too. It's hard to say what a listing owner will change to his listing once approved and this kind of option might be helpful.

**Comment by jom** [comment]
Duplicate: #509 

Fixed in #1264 (unreleased; scheduled for 1.30.0)
