### ISSUE TITLE
uploaded-file-html.php attempts to show docx files as images

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1293]
https://github.com/Automattic/WP-Job-Manager/blob/43aa806e98e466f1c50b05123f9da383cda7a18a/templates/form-fields/uploaded-file-html.php#L28

Because of the initial OR check `||` it's considering a `.docx` file as an image and attempting to show a preview of the file, which results in a broken image:

**Comment by wpfan2099** [comment]
two thumbs up - well this is really very important. LEt us iron out a solution. 

We need to work on this issues.  We can improve the wp-jobmanager - More than 100 000 user are out there. WP Jobmanager is one of the most used plugins in its class. 

Let us make it better and better day by day.
