### ISSUE TITLE
An invalid form control with name='XXXX' is not focusable.

### ISSUE THREAD

**Issue by DWS-paris** [Automattic/WP-Job-Manager#1295]
Hello, 

I have a issue with hidden form control: it's not possible to add urls, experienc or education in the submit resume form.

Is it possible to have some help to fix it?
thx, Julien

**Comment by jom** [comment]
Hi there! This is just for the core WP Job Manager plugin, not the other plugins.

For support, please visit https://wpjobmanager.com/support.
