### ISSUE TITLE
Search does not work as expected / errors

### ISSUE THREAD

**Issue by purplepineapple2** [Automattic/WP-Job-Manager#1296]
Hi guys,
first of all. I am a complete programming beginner. I have read through many issues regarding similar problems with WP Job Manager and still was not sure wether my problem was discussed or not. Therefore I am posting it and hope not to step on ones toes, and maybe even get some help. :)

#### Steps to Reproduce
1. Type something into the "keyword" field and hit enter – the search results will look really strange and not show any listing, but articles and portfolios of my wordpress.
2. Type something into solely the "location/Ort" field – the search results will look as expected
3. Type something into both fields – the search will not show any of the results it should find

#### What I Expected
I expected the search to work overall as dissused in step 2.

#### What Happened Instead
The results are displayed very strangely and not show job listing, but portfolios and articles.

#### WordPress / WP Job Manager Version
WordPress 4.9.2–de_DE
WP Job Manager 1.29.2 

#### Browser / OS Version
Various Macbooks, iMacs, Win PCs with various browsers

#### Screenshot / Video
![bildschirmfoto 2018-01-23 um 11 29 32](https://user-images.githubusercontent.com/35698297/35271486-93bbd992-0032-11e8-9716-a745e48be569.png)

#### Context / Source
www.ausbildung-hier.de/ausbildungsboard

If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by bartje1994** [comment]
I have the same issue.

**Comment by jom** [comment]
What theme are you using? It may be an issue with your theme. Please try to replicate on Twenty-Seventeen. If you are able to, please post a screenshot on that theme.

**Comment by bartje1994** [comment]
I'm currently using Jobera. If i switch the theme to 'Twenty-Seventeen' it's working. I already thought it was a theme issue but i'm still no step further to the solution..

**Comment by jom** [comment]
I'd recommend contacting the theme author. Unfortunately this is just for issues with the core plug-in.
