### ISSUE TITLE
Search Results Page URL Rewrite

### ISSUE THREAD

**Issue by asadpk** [Automattic/WP-Job-Manager#1297]
Hi,

I want to rewrite search results pages URL. I am using homepage search box for filter results

http://goasquare.com/jobs/?search_keywords=Hotel&search_location=&search_categories%5B%5D=44&search_region=&submit=&filter_job_type%5B%5D=

To something like this.

http://goasquare.com/jobs/%keyword%/%category%/%location%

Thanks

Asad

**Comment by wpfan2099** [comment]
Asad - well to be frank - this is pretty important - let us focus on doing this.  We need to evlove WP-JobManager.  Let us collaboratetively work togehter to make it better and better. 

More than 100 000 user are out there - togethter were strong - to make the jobmanager better and better .

**Comment by codestor4** [comment]
1155892-zen
