### ISSUE TITLE
Allow preselecting categories on job's page by slug

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#1300]
I used to be able to append a query string to the jobs page URL to automatically narrow down the jobs list to a category, like so:

`http://wpjm.local/?search_categories=test`

... which would only show jobs in the `test` category. This no longer appears to be working.

**Comment by aheckler** [comment]
922497-zen

**Comment by jenhooks** [comment]
1115792-zen

**Comment by jom** [comment]
Do we know where this is documented as having had worked at one time?

**Comment by aheckler** [comment]
/me magically appears from paternity leave!

I don't know if this was ever "officially" documented, but some amount of our users know about it, probably because Mike or I posted about in the forums at some point. It looks like it should work per this:

https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-ajax.php#L120

/me disappears back into his leave!

**Comment by jom** [comment]
That would be for the `http://wpjm.localhost/jm-ajax/get_listings/` endpoint, which is used by the `[jobs]` short code. Is this for the `job_listings` archive page, WP home/root page (as shown in first example), or `[jobs]` page?

(Hi Adam! Don't feel the need to pop back from leave 😉)

**Comment by aheckler** [comment]
I know it used to work for the `[jobs]` page at least.

**Comment by spencerfinnell** [comment]
https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-shortcodes.php#L304

Try `search_category` -- though I see some code in Jobify dealing with a `search_categories` query arg but forget exactly why it was needed...

**Comment by richardmtl** [comment]
Also reported in https://wordpress.org/support/topic/how-to-make-a-link-towards-the-listing-job-page-but-with-tag-filtered-search/ ; I'm not sure if there's a way to change this / fix this?

**Comment by richardmtl** [comment]
2121408-zen
