### ISSUE TITLE
Make the Company Details an optional field.

### ISSUE THREAD

**Issue by gaurav1984** [Automattic/WP-Job-Manager#1301]
From the user's feedback on 922391-zen

> Feedback if interested: the company details shouldn’t be a required field, or: displaying this field or not should be editable in the plugin. Otherwise, this plugin is only restricted to agencies listing jobs for other companies, rather than being open for use by individual businesses.

**Comment by jom** [comment]
I'd recommend they use a filter to make this possible. They can remove the company fields easily:
```add_filter( 'submit_job_form_fields', function( $fields ) {
	unset( $fields['company'] );
	return $fields;
} );
```

They may need to override their templates as well.
