### ISSUE TITLE
REST API: Check and document endpoint authorization assumptions

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1303]
I'll be working on a swagger doc for our REST API endpoints. I'd like to double check our 
authorization assumptions for our endpoints.

I'm using this issue to collect some notes/thoughts.

## Settings ##
* **_General Questions/Thoughts_**
   * Should any setting be `GET`-able by guests? For example: `Multi-select Listing Types` might be useful for the client to sniff. Same with the page definitions.
   * If we do expose some, the ability to sniff may create easier attack surfaces.
   * Not sure about these endpoints. `POST` and `DELETE` (I'm guessing) aren't used?
* **OPTIONS /wp-json/wpjm/v1/settings**: admin only with `manage_options` cap 
* **GET /wp-json/wpjm/v1/settings**: admin only with `manage_options` cap ✅
* **PATCH /wp-json/wpjm/v1/settings**: admin only with `manage_options` cap✅

## Job Listings ##
* **_General Questions/Thoughts_**
   * Permissions may be WordPress defined.
   * As we think about field-based access, how will custom fields define their access requirements?
* **OPTIONS /wp-json/wp/v2/job-listings**: open to public with returned schema based on access.
* **GET /wp-json/wp/v2/job-listings**: open to public with filtered _fields_ based on access.
* **POST /wp-json/wp/v2/job-listings**: logged in users only with access to create jobs 
* **GET /wp-json/wp/v2/job-listings/{id}**: open to public with filtered fields based on access. 
* **PATCH /wp-json/wp/v2/job-listings/{id}**: logged in users only with access to update a specific job. Admins: everything; job listing author: based on settings, fields being updated (filled, for example, doesn't depend on whether or not the site owner allows edits to listings).
* **DELETE /wp-json/wp/v2/job-listings/{id}**: logged in users only with access to delete a specific job. Admins: allowed; job listing author: allowed; everyone else: not allowed.

## Taxonomy: Job Types ##
* **OPTIONS /wp/v2/job-types**: public
* **GET /wp/v2/job-types**: public
* **POST /wp/v2/job-types**: admin only
* **GET /wp/v2/job-types/{id}**: public
* **PATCH /wp/v2/job-types/{id}**: admin only
* **DELETE /wp/v2/job-types/{id}**: admin only

## Taxonomy: Job Categories (TBI) ##
* **OPTIONS /wp/v2/job-categories** : public
* **GET /wp/v2/job-categories**: public
* **POST /wp/v2/job-categories**: admin only
* **GET /wp/v2/job-categories/{id}**: public
* **PATCH /wp/v2/job-categories/{id}**: admin only
* **DELETE /wp/v2/job-categories/{id}**: admin only

cc: @pgk

**Comment by multiversonews** [comment]
when will the release be released with the api included?

**Comment by jom** [comment]
Closed in favor of #1625
