### ISSUE TITLE
No Apply with Resume Button, or option on my Listings.

### ISSUE THREAD

**Issue by tstidotcom** [Automattic/WP-Job-Manager#1307]
I have the resume manager and am currently building a listing based site. Everything works except that i do not have the option on the front end, when making the listing, (or on the back end) to use the resume submission option. I can create a resume, but when trying to test submitting it for a listing, there is no submission button on the listing. When I initially researched the problem I see that there is an option in the job detail section of the listing creation to show your apply with option (Email or Website). My version of Wp Job Manager does not have this. I currently have WP job manager and Resume Manager plugins installed. 

I use chrome but also tested this in Internet Explorer.
Updated to latest wordpress today and Job Manager
My website is using the Prolist theme. 
I have the apply with resume options checked in both setting for both both Wp job manager plugins.
My job submission form doesn't have an option to set an "apply with", just an email contact and a website.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for WP Job Manager's core plugin only. For support, especially for the resume plugin, please visit https://wpjobmanager.com/support.

**Comment by tstidotcom** [comment]
Thank you. I've moved the request over.
