### ISSUE TITLE
Google Search Console - New Job Postings issues detected for site

### ISSUE THREAD

**Issue by praitosola** [Automattic/WP-Job-Manager#1313]
Hi, I am getting this same issue today (we updated the Job Manager plugin yesterday - is this something to do with that? - we use Listable theme - so we do not have any Hiring Organizations or Base Salaries, etc... ):

Search Console has identified that your site is affected by 11 new Job Postings related issues. This means that Job Postings may be negatively affected in Google Search results. We encourage you to fix these issues.

Top 5 new issues found, ordered by number of affected pages:
Missing or invalid field: employmentType
Missing or invalid field: hiringOrganization.name
Missing or invalid field: baseSalary
Missing or invalid field: validThrough
Missing or invalid field: jobLocation.address.addressRegion

**Comment by jom** [comment]
Please confirm that if your theme overrode `content-single-job_listing.php` (and related templates) it has all the `itemprop`, `itemscope`, and `itemtype` properties removed.

`employmentType` is set from the job type. Make sure your job type terms have their employment type set. Hiring organization should be coming from new implementation we added in 1.28.0 (#1115). `addressRegion` will only show up if you have had Google Maps API key added to your profile (adding the key will not change your already added listings). `baseSalary` and `validThrough` are currently not part of our implementation, but shouldn't be required fields (just recommended).

**Comment by praitosola** [comment]
Hi Jake,

We have listable theme, so those Hiring Organisations etc are not relevant to the page.

I will take a look at the issues you advised now.

Best regards,
Pauliina

**Comment by praitosola** [comment]
We do not want to use any employment types (it is Listable theme - job manager is used for travel site for listings). Also there are no "Job Types" or "Employment profiles" or JobType Terms" (at least not with this theme).  And there is no place to add Google Maps Api for "profile" (there is no Employment profile). Please advise.

**Comment by jom** [comment]
To disable, add this snippet to your theme/snippet manager:
`add_filter( 'wpjm_output_job_listing_structured_data', '__return_false' );`

**Comment by lucascino** [comment]
we have the same problem as praitosola, instead of disabling all the structured data, we would like to disable only the fields "hiringOrganization.name" - "baseSalary" - "employmentType", is there a filter to do that? thanks!

**Comment by amarsai1** [comment]
Anybody, please help me how I can fix the **Missing field 'validThrough'** on https://www.techsingh123.com/

actually, I'm facing too much issue please help me

**Comment by amarsai1** [comment]
I am facing an issue on https://www.techsingh123.com/ 
``add_filter( 'wpjm_output_job_listing_structured_data', '__return_false' ); is not working please help me.
