### ISSUE TITLE
Job Manager short codes (type and category) are not working in translated pages

### ISSUE THREAD

**Issue by praitosola** [Automattic/WP-Job-Manager#1314]
Job Manager short codes (type and category) are not working in translated pages (using Listable theme). They worked fine for a long time, and then suddenly yesterday stopped working. We did update the WPML plugins to try to fix the isseu, but this did not work. Now we get on the other pages (except English): There are no listings matching your search. (if there are any shortcodes for listing types & categories - this is called job types in Job Manager, which is the plugin used)

If you look at this page:
FINNISH: http://www.discoveringfinland.com/fi/jarvisuomi/kuopio/
And compare with ENG: http://www.discoveringfinland.com/lakeland/kuopio/
(You see that in English all the listings are appearing fine)
Short code is: [jobs per_page="24" show_map="false" show_filters="false" location="Kuopio" job_types="premium"]
If I remove the job_types="premium" - then the listings show just fine.

We are using WPbakery Page Builder as well.

**Comment by praitosola** [comment]
I also tried this same short code without WPbakery Page Builder, and same error occurs.

**Comment by leanna-norwood** [comment]
I am having the a similar issue with the Workscout theme. The jobs listing shortcodes only filter on the first page of pagination. After the first page, all category and/or location filters are reset. This only occurs when I have the "show filters" above list set to false. If I choose to show filters, everything works correctly, but I wish to hide the filters.

**Comment by diegox80** [comment]
I am having the a similar issue with Listable theme.
But in my installation, deactivating Listable and FacetWP, [jobs job_types="my_type"] still not work; [jobs categories="my_category"] is ok.

**Comment by praitosola** [comment]
I think we fixed this by checking in the WPML settings ->Languages, the setting "Adjust IDs for multilingual functionality ". We had unchecked this, and that caused the problem. After rechecking it, we saved a few pages and all was fine again. Maybe this is not cause for diegox80, but for us it worked.

**Comment by jom** [comment]
Closing this for now as there seems to be a fix in WPML. Feel free to re-open if still happening.

**Comment by todoenlaces** [comment]
Hi, we use wp job manager and want show the related category jobs in our web https://www.todoenlaces.com/ but only get the actual job category, this is our code [jobs categories="my_category" jobs per_page="20" orderby="title"] thanks in advanced.
