### ISSUE TITLE
Add salary field to satisfy Google's Job Search schema

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#1320]
Assuming a user fills out all the job form fields correctly, Google will still throw a warning (_not_ an error) because listings do not have a salary by default. We should consider adding this:

https://wpjobmanager.com/document/tutorial-adding-a-salary-field-for-jobs/

... to the core plugin, IMHO.

We should also consider renaming the `Location` field to `Address`, since if you don't enter an exact street address, Google will throw other warnings (or actual errors, depending on how the user enters the location). `Address` is less ambiguous in this regard.

Related to #1313

**Comment by jom** [comment]
I agree that we should add a salary field. Is it safe enough to just add the field and provide a filter snippet for folks who want to remove it as a field? 

For the Location/Address, I take it these are errors in the schema check and not background address fetching from Google Maps?

**Comment by aheckler** [comment]
> Is it safe enough to just add the field and provide a filter snippet for folks who want to remove it as a field?

I don't even think we need to provide a filter really. We don't provide a specific filter for any of the other default fields. People can already use `submit_job_form_fields` to `unset` whatever they don't want.

> For the Location/Address, I take it these are errors in the schema check and not background address fetching from Google Maps?

Correct, yeah. It's nothing we're doing ourselves, but we can help the user avoid errors in the schema check if we make the label more accurately reflect what they need to enter to pass the check.

**Comment by jom** [comment]
> People can already use `submit_job_form_fields` to `unset` whatever they don't want.

Yup, I meant documenting a snippet on wpjobmanager.com that uses `submit_job_form_fields`.

> Correct, yeah. It's nothing we're doing ourselves, but we can help the user avoid errors in the schema check if we make the label more accurately reflect what they need to enter to pass the check.

Alrighty. I might break this ticket up. I feel like I've seen *Location* more than *Address* on job listing sites, but we could try it out. I think we'll be needing to rethink that field anyway to support remote jobs (#918).

**Comment by aheckler** [comment]
> I meant documenting a snippet on wpjobmanager.com that uses `submit_job_form_fields`.

I can do this when we merge, yeah.

> I feel like I've seen Location more than Address on job listing sites, but we could try it out.

Yeah, it's a tough call. 

People probably aren't used to putting in exact addresses on job listing sites. But Google says: "The more properties you provide, the higher quality the job posting is to our users." ([Source](https://developers.google.com/search/docs/data-types/job-posting#JobPosting-definition).) And people always want to obey Google. ¯\\_(ツ)_/¯ 

CTRL+F here for `TELECOMMUTE` to see how they want us to designate remote jobs:

https://developers.google.com/search/docs/data-types/job-posting

That will probably need to be a new checkbox in the default form fields.

**Comment by aheckler** [comment]
Also, when/if we do add salary to the built-in fields, we should add it to the Indeed job feed XML.

947425-zen

**Comment by jenhooks** [comment]
1512665-zen

**Comment by gravitymaster97** [comment]
<a href='https://wordpress.org/plugins/custom-field-for-wp-job-manager/'><u>Custom Field For WP Job Manager</u></a> is also one good plugin for adding text as well select field in wp job manager

**Comment by richardmtl** [comment]
This continues to come up (see https://wordpress.org/support/topic/job-posting-schema-2/ for example).

**Comment by jom** [comment]
This seems like a higher priority issue. Doing it correctly isn't super easy. We should support the following in v1:
- Adding this field should be a setting that is turned off by default. If we enable it, we'll probably break a lot of sites that have added this using Field Editor or our documentation. We could warn people if we see a 'salary' field already being added. 
  - We'll need to store the currency value as a number and not allow strings, such as currency symbols, intervals, or ranges-as-strings. For example, these values for `_salary` would probably break:
`$30,000`, `30,000`, `$30,000 / yr`, `$30,000 - $40,000`
- _Setting_ for per job currencies with a global default. Base our function(s) off of `get_woocommerce_currencies` and `get_woocommerce_currency_symbol`. 
- Interval will also need to be supported / tracked (`HOUR`, `DAY`, `WEEK`, `MONTH`, `YEAR`). For the default, we could probably use `YEAR` with a _filter_ to adjust.
- Ideally, ranges should also be supported from the start. We could do some magic parsing of a string (`20000-40000`) -> `'minValue' => 20000, 'maxValue' => 40000` or two fields. Two fields would probably be best. 

For the UI on the front-end form, we'll probably need some design help. cc: @digitalwaveride 
It would be a set of fields to allow user input of: 
- Currency (unless disabled/forced to a single currency)
- Salary value/range (it'd be nice to have a seamless way to go between a single salary and range)
- Interval unit (hour, day, week, month, year)

**Comment by iweeleaks** [comment]
So I followed every step in the tutorial - [https://wpjobmanager.com/document/tutorial-adding-a-salary-field-for-jobs/] and salary field shows up in admin, frontend job form as well as single job posting. 
However, when I test it in Structured Data Tool, it still shows "The baseSalary field is recommended."
Am I missing something? Why is it not reading it correctly? TIA!

**Comment by richardmtl** [comment]
@iweeleaks please start a thread in the forum if you haven't already:

https://wordpress.org/support/plugin/wp-job-manager/

Or, if you have a license for one of our paid add-ons, contact us here:

https://wpjobmanager.com/support/

**Comment by muhammadmadni21** [comment]
Field "jobLocation.address.addressLocality" is missing
Field "jobLocation.address.streetAddress" is missing
Field "jobLocation.address.addressRegion" is missing
Field "jobLocation.address.postalCode" is missing
address warnings how can we fix these issues my [website ](https://jobletpk.com/) show this issue many times ple help to fix

**Comment by onubrooks** [comment]
FYI a PR and some discussion [here](https://github.com/Automattic/WP-Job-Manager/pull/1510)
