### ISSUE TITLE
Function to retrieve Job Listings page url

### ISSUE THREAD

**Issue by paulkirspuu** [Automattic/WP-Job-Manager#1323]
This function would come in handy when setting up a "back to listings" link to single job listing page.

**Comment by jom** [comment]
Job listings are normal custom post types. You should be able to just use `get_permalink( $job->ID )`. Is this what you're referring to? I may not understand the issue.

**Comment by paulkirspuu** [comment]
@rloconne-ncsu-edu this is what I was looking for. thank you!
