### ISSUE TITLE
WP Job Manager Applications

### ISSUE THREAD

**Issue by ET-Mod** [Automattic/WP-Job-Manager#1328]
I'm using Job  Manager Application to apply for a Job
I would like the email to go to Admin not the employer. 
How do I apply that? 
Your help is highly appreciated I'm a beginner with php and WP.  

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, especially for our paid add-ons, please visit https://wpjobmanager.com/support.
