### ISSUE TITLE
Redirect Roles after Registration

### ISSUE THREAD

**Issue by ET-Mod** [Automattic/WP-Job-Manager#1329]
#### Steps to Reproduce
1.
2.
3.

#### What I Expected
My code supposed to redirect roles to their designated pages after registration.
Candidate to candidate-dashboard
Employer to employer-dashboard

#### What Happened Instead
Instead both roles are redirected to employer-dashboard,which is right for employer but wrng for candidate

#### WordPress / WP Job Manager Version
Version 1.29.3

#### Screenshot / Video
See the screenshot of my code
http://prntscr.com/ieibmc

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core add-on. For support, especially for our paid add-ons, please visit https://wpjobmanager.com/support. If they can reproduce the issue with the application/resume plugin, they'll file the appropriate bug report.
