### ISSUE TITLE
Hide/dim jobs in job listing [jobs] that have already been applied to

### ISSUE THREAD

**Issue by joewa1980** [Automattic/WP-Job-Manager#1346]
Hide/dim/add a 'APPLIED' flag to jobs in the job listing [jobs] that have already been applied to, similar to how the apply button is hidden on the job page when a user has already applied.

**Comment by richardmtl** [comment]
Originally requested in 962330-zen

**Comment by joewa1980** [comment]
Is there a link for that original request?

**Comment by richardmtl** [comment]
@joewa1980 962330-zen is an internal reference on our end, which points to the ticket that you sent in. Sorry for the confusion! :)

**Comment by richardmtl** [comment]
Also requested in 967093-zen

**Comment by jom** [comment]
Hi there! This is just for tracking issues with the core WP Job Manager plugin. I've created an enhancement request for the applications plugin to add this feature.

**Comment by joewa1980** [comment]
Thanks @jom, I was unable to initially post it as an enhancement. I look forward to this developing.

**Comment by richardmtl** [comment]
@joewa1980 Just FYI, the development repository for the Applications addon is private, so you won't be able to follow along directly. However, we'll notify you when and if your suggestion gets implemented!
