### ISSUE TITLE
Remove legacy asset enqueueing  compatibility code

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1358]
See: #1354 

Remove constant check and compatibility filters that maintain the old enqueueing strategy:

https://github.com/Automattic/WP-Job-Manager/blob/b0a781a80441b8e735cc62aff0919d211a96787a/wp-job-manager.php#L230-L261

**Comment by tripflex** [comment]
Any specific reason for not keeping the asset registered and just dealing with the enqueueing of the asset?

**Comment by jom** [comment]
@tripflex Are you referring to `chosen` and the original PR that this references? 

We could, but it has a bit of a cascading effect unless we update `templates/form-fields/term-multiselect-field.php` and `templates/form-fields/multiselect-field.php`. Those blindly enqueue `wp-job-manager-multiselect` which has no effect if that is never registered (which is good if we have disabled the library). We could, technically, _register_ chosen JS and CSS and leave them out there, but if we are replacing that library soon I'd rather not make it easier for people to add dependencies other than `wp-job-manager-multiselect`.
