### ISSUE TITLE
Delete plugin data on uninstall

### ISSUE THREAD

**Issue by donnapep** [Automattic/WP-Job-Manager#1362]
As part of the GDPR, we need to delete all data (especially user data) when a user uninstalls WPJM.

WordPress core shows a prompt when deleting a plugin to indicate that both the plugin and its data will be deleted. The user must accept this confirmation before anything gets removed:

![screen shot 2018-03-01 at 1 32 08 pm](https://user-images.githubusercontent.com/1190420/36862502-f977351c-1d54-11e8-9036-65aa4950af83.jpg)

We'll need to be sure to communicate that WPJM will now delete ALL of its data, as there may be site admins who have grown accustomed to deleting the plugin and then immediately re-installing it (perhaps installing a different version), and take for granted that most of their data will remain intact.

# What to Delete?

The following data should be deleted when WP Job Manager is deleted if that is not the case already. _Note that for a multi-site install, this means that the data deletion needs to happen across all sites._

## Custom Post Types

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1418_

All posts for the following custom post type should be moved to the Trash:
- `job_listing`

## Terms & Taxonomies

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1419_

Term and taxonomy data for the following taxonomies should be deleted:
- `job_listing_category`
- `job_listing_type`

## Pages

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1421_

The following pages should be moved to the Trash:
- The page referenced in the _Submit Job Form Page_ field of the settings
- The page referenced in the _Job Dashboard Page_ field of the settings
- The page referenced in the _Job Listings Page_ field of the settings

## Options

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1427_

The following options should be deleted:
- `wp_job_manager_version`
- `job_manager_installed_terms`
- `wpjm_permalinks`
- `job_manager_helper`
- `job_manager_date_format`
- `job_manager_google_maps_api_key`
- `job_manager_usage_tracking_enabled`
- `job_manager_usage_tracking_opt_in_hide`
- `job_manager_per_page`
- `job_manager_hide_filled_positions`
- `job_manager_hide_expired`
- `job_manager_hide_expired_content`
- `job_manager_enable_categories`
- `job_manager_enable_default_category_multiselect`
- `job_manager_category_filter_type`
- `job_manager_enable_types`
- `job_manager_multi_job_type`
- `job_manager_user_requires_account`
- `job_manager_enable_registration`
- `job_manager_generate_username_from_email`
- `job_manager_use_standard_password_setup_email`
- `job_manager_registration_role`
- `job_manager_submission_requires_approval`
- `job_manager_user_can_edit_pending_submissions`
- `job_manager_user_edit_published_submissions`
- `job_manager_submission_duration`
- `job_manager_allowed_application_method`
- `job_manager_recaptcha_label`
- `job_manager_recaptcha_site_key`
- `job_manager_recaptcha_secret_key`
- `job_manager_enable_recaptcha_job_submission`
- `job_manager_submit_job_form_page_id`
- `job_manager_job_dashboard_page_id`
- `job_manager_jobs_page_id`
- `job_manager_submit_page_slug`
- `job_manager_job_dashboard_page_slug`

The following site option should be deleted for multi-site installs:
- `job_manager_helper`

## Transients

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1428_

The following transients should be deleted:
- `_transient_timeout__job_manager_activation_redirect`
- `_transient_get_job_listings-transient-version`

Transients that _start with_ the following identifiers should be deleted:
- `_transient_timeout_jm_`
- `_transient_jm_`

## Capabilities

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1429_

The following capabilities should be removed from any role that has them:
- `manage_job_listings`
- `edit_job_listing`
- `read_job_listing`
- `delete_job_listing`
- `edit_job_listings`
- `edit_others_job_listings`
- `publish_job_listings`
- `read_private_job_listings`
- `delete_job_listings`
- `delete_private_job_listings`
- `delete_published_job_listings`
- `delete_others_job_listings`
- `edit_private_job_listings`
- `edit_published_job_listings`
- `manage_job_listing_terms`
- `edit_job_listing_terms`
- `delete_job_listing_terms`
- `assign_job_listing_terms`

## Roles

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1429_

The following role should be deleted:
- `employer`

## Post Meta

_Done. Since these are all stored on Job Listings, they are deleted when the posts are deleted (see #1418)_

Post meta with the following meta keys should be deleted:
- `_application`
- `_company_name`
- `_company_website`
- `_company_tagline`
- `_company_twitter`
- `_company_video`
- `_filled`
- `_featured`
- `_job_author`
- `_job_description`
- `_job_expires`
- `_job_edited`
- `_job_location`
- `_job_title`
- `_submitting_key`
- `geolocated`
- `geolocation_city`
- `geolocation_country_long`
- `geolocation_country_short`
- `geolocation_formatted_address`
- `geolocation_lat`
- `geolocation_long`
- `geolocation_state_long`
- `geolocation_state_short`
- `geolocation_street`
- `geolocation_street_number`
- `geolocation_zipcode`
- `geolocation_postcode`

## User Meta

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1430_

User meta with the following meta keys should be deleted:
- `_company_logo`
- `_company_name`
- `_company_website`
- `_company_tagline`
- `_company_twitter`
- `_company_video`

## Cron Jobs

_Done: https://github.com/Automattic/WP-Job-Manager/pull/1431_

The following cron jobs should be cleared:
- `job_manager_check_for_expired_jobs`
- `job_manager_delete_old_previews`
- `job_manager_clear_expired_transients`
- `job_manager_usage_tracking_send_usage_data`

A good example of an `uninstall.php` file can be seen [here](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/uninstall.php).

**Comment by alexsanford** [comment]
Done!

The PR's that completed each section are linked in the description.

Also see #1435 for the addition of the setting.
