### ISSUE TITLE
Static function WP_Job_Manager_Usage_Tracking_Base::get_instance() should not be abstract

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1363]
Reported in 989416-zen

`
Strict Standards: Static function WP_Job_Manager_Usage_Tracking_Base::get_instance() should not be abstract in /home1/XXXX/public_html/wp-content/plugins/wp-job-manager/lib/usage-tracking/class-usage-tracking-base.php on line 70
`

**Comment by jom** [comment]
@alexsanford For now, we should probably just overload the function but have the base class just trigger a fatal. Eventually, when we drop PHP 5.2 support, we can move to late static bindings (`static::` instead of `self::`) and simplify our `get_instance` methods.

**Comment by codestor4** [comment]
990722-zen
