### ISSUE TITLE
Support job feed pagination

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1369]
For job feeds, we should support the standard `paged` query param for paginating RSS feeds. For now, folks can add support using this snippet:
```php
add_filter( 'job_feed_args', function( $args ) {
	$args['paged'] = absint( get_query_var( 'paged', 1 ) );
	return $args;
} );
```

Folks can then use queries such as:
`http://example.com/?feed=job_feed&posts_per_page=10&paged=1`
`http://example.com/?feed=job_feed&posts_per_page=10&paged=2`
...

**Comment by linoman-zz** [comment]
dear Jom - great idea - superb Job. I like it very much!!
