### ISSUE TITLE
Allow `parent` to be passed to get_terms() in job_manager_dropdown_categories()

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#1370]
#### Steps to Reproduce
1. Call `job_manager_dropdown_categories( array( 'parent' => 0 ) );`

#### What I Expected

Only parent terms to show.

#### What Happened Instead

All terms show.

#### WordPress / WP Job Manager Version

Master

#### Context / Source

Extra args added to function call do not get passed to `get_terms()` https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L1044-L1049

**Comment by tripflex** [comment]
I can confirm this as well, `child_of` is passed but there will be instances where may need to pass `parent` as well
