### ISSUE TITLE
Capital letters in email creates a problem while activating the license

### ISSUE THREAD

**Issue by wigglemuff** [Automattic/WP-Job-Manager#1376]
If I try to activate a license using capital letters and my email is registered in all lower-case with WPJM, it'll say my email is invalid.

For example:

1) my account with WPJM is registered with: `omkar.bhagat@automattic.com`
2) if I try to activate using `Omkar.bhagat@automattic.com`, it'll say invalid email.

To fix this, we can convert entered text (email) and the account email to lowercase before we compare them. 

Ticket: 1000457-zen

I was able to reproduce this on a staging site!

**Comment by jom** [comment]
This has been fixed through an update to wpjobmanager.com's license API.
