### ISSUE TITLE
Warnings in Google Search Console

### ISSUE THREAD

**Issue by bairdynl** [Automattic/WP-Job-Manager#1378]
Hi,

Just started to use WP-Job manager and getting 4 warnings and an error on the first online job listening. 

Error: 
hiringOrganization.name
Warnings:
 jobLocation.address.postalCode (optioneel)
jobLocation.address.streetAddress (optioneel)
 baseSalary (optioneel)
 employmentType (optioneel)

Where can you fix this?

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
