### ISSUE TITLE
Delete job not working after migrating website to another webhost

### ISSUE THREAD

**Issue by zirria** [Automattic/WP-Job-Manager#1382]
#### Steps to Reproduce
1.go to My Jobs
2.Delete a job

#### What I Expected
Job will be deleted

#### What Happened Instead
Job won't be deleted. The page just refreshes and nothing happens

**Comment by jom** [comment]
I'm not able to reproduce on a vanilla install of WPJM. Please try digging more into the other possible conflicts that could be producing this and let us know what in your environment is causing the behavior. Once you have reproducible steps, post here. 

Also, make sure your new host doesn't do page caching on this page.

**Comment by zirria** [comment]
I recently migrated my site from 000webhost to another web host and that's when the issue happened

**Comment by zirria** [comment]
The plugin and wordpress version is up to date. Talked to a support from my new webhost and he said that they do not do page caching with my page.

**Comment by zirria** [comment]
Do I have to create another ticket for Mark Filled and duplicate option? Because they are not working as well

**Comment by jom** [comment]
We'll need reproducible steps to keep this issue, unfortunately. Please try reproducing on TwentySeventeen theme with other plugins disabled. If it works, slowly change back to your current environment (switch them, then one-by-one reactivate plugins). 

Also, try just resaving the Permalink settings in WP Admin (no need to change anything).

**Comment by zirria** [comment]
A moment please. Trying them now.

**Comment by zirria** [comment]
I resaved my Permalink settings still no good. switching to twenty-seventeen

**Comment by zirria** [comment]
Can I private chat you or something?

**Comment by zirria** [comment]
I tried the former option but did not work as well. Only thing I can do is delete and do mark filled from the dashboard and it works fine

**Comment by iamgabrielma** [comment]
Hi @zirria 

Are you still experiencing issues with this? Please be sure to share reproducible steps to so we can take a look into it. 

I'd recommend to test this out by deactivating all plugins except WP Job Manager, switching themes to a default WordPress theme like Twenty Sixteen, and testing again.

If that's not possible to do in your live site without affecting your business, you can try this on a staging environment, you can use a plugin like wp-staging: https://wordpress.org/plugins/wp-staging/ for this.

A staging site is a clone of your live site, once you have the staging site running you can add/remove/edit data as you wish, as any modification won't affect your live site.
