### ISSUE TITLE
Multiple recipients

### ISSUE THREAD

**Issue by clairemugnier** [Automattic/WP-Job-Manager#1384]
Hi,

I would like to include multiple e-mails in the job listing to receive notifications. Right now, it's only allowing a single address.

The post has already been discussed here but does not give the code : https://github.com/Automattic/WP-Job-Manager/issues/316

My recipients are the same across all jobs.

In the other post, you say that it is possible. Can you give me the code?

Thanks

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
