### ISSUE TITLE
Add setting to allow disabling of preview step?

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#1385]
The user in 987444-zen thinks there are too many steps to apply to a job, and too many candidates are abandoning the process before actually applying to the job. The user recommends changing the process to remove the "preview" step, so applying is simply uploading a resume and confirming the application. 

I understand that the preview step is probably appreciated by a lot of users, so would it be possible to add a setting for admins to be able to toggle previews on and off for the site?

**Comment by spencerfinnell** [comment]
https://wpjobmanager.com/document/remove-the-preview-step/

**Comment by jenhooks** [comment]
@jom -- Any preference which one of those repos I move this to?

**Comment by jom** [comment]
@jenhooks I think this would be for the resume plugin.

**Comment by jenhooks** [comment]
Added [here](https://github.com/Automattic/wp-job-manager-resumes/issues/203), closing. Thanks!
