### ISSUE TITLE
Add SearchAction to JSON-LD

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#1391]
https://developers.google.com/search/docs/data-types/sitelinks-searchbox

Adding a `potentialAction` to the JSON-LD structured data would potentially allow a search form to be shown inline in Google.

```js
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "url": "https://www.example.com/",
  "potentialAction": {
    "@type": "SearchAction",
    "target": "https://query.example.com/search?q={search_term_string}",
    "query-input": "required name=search_term_string"
  }
}
```

**Comment by UVLabs** [comment]
Props ;) ;)

**Comment by UVLabs** [comment]
The target would look something like this:

https://example.com/{name set for plural job post type}/?search_keywords={search_term_string}

**Comment by jom** [comment]
This seems like a good customization for some sites, but other sites might want to search the whole site vs just jobs. I think it would have to be a setting that was disabled by default, which makes me thing this is a better customization. Closing for now, but can re-open if more people want to discuss.
