### ISSUE TITLE
Search form: Include actual "Search" or "Submit" button for accessibility

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1409]
Raised in https://wordpress.org/support/topic/accessibility-issues-with-plugin/ 

<blockquote>This form does not contain a submit button, which creates issues for those who cannot submit the form using the keyboard. Submit buttons are INPUT elements with type attribute “submit” or “image”, or BUTTON elements with type “submit” or omitted/invalid.”</blockquote>

**Comment by wpfan2099** [comment]
Many many thanks dear  Richard,  this is a valid point you raise here. I am happy to see your posting. It describes a pretty important thing.  on a sidenote: You and your hard work on Job-board-manager make me happy happy. ' I am so glad to see you here and there.!!! Keep up the great work - it rocks!!! many many greetings ! Wordpresser

**Comment by jenhooks** [comment]
https://wordpress.org/support/topic/search-button-on-jobs-page/

**Comment by jenhooks** [comment]
1730242-zen

**Comment by richardmtl** [comment]
1882362-zen

**Comment by jenhooks** [comment]
18904520-zen

**Comment by jenhooks** [comment]
1893399-zen

**Comment by richardmtl** [comment]
1890508-zen ; they assumed it was a bug
