### ISSUE TITLE
wysiwyg editor not loading on post jobs

### ISSUE THREAD

**Issue by belindawaldock** [Automattic/WP-Job-Manager#1423]
Hello
i have a user (logged in) who is trying to add a job via https://www.softwarecornwall.org/post-a-job/ but the wysiwyg editor isnt loading/displaying.. its working for me and other users, any ideas why this might be happening on their device please? 

their screenshot...

![image](https://user-images.githubusercontent.com/9388372/38393917-5b7521ee-3924-11e8-96cb-da65e2832762.png)

im assuming it might be a browser issue, or a browser security thing, im sure i have had a similar problem before with a wysiwyg not showing before but i cant recall what the issue was.  we have ithemes security plugin, and have just updated to the new version of wordpress. 

any help or advice, or guesses much appreciated ! 

thank you!

Belinda

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs that you can reproduce (and describe how to reproduce) and feature requests. For support, please visit https://wpjobmanager.com/support.

I'd recommend having them try clearing their cache and try to reproduce without any browser add-ons enabled (ad-blockers, etc). It shouldn't be blocked by ad blockers, but I've heard of stranger things getting blocked.
