### ISSUE TITLE
Call [submit_job_form] errors within the templates.

### ISSUE THREAD

**Issue by asalkey** [Automattic/WP-Job-Manager#1425]
I have two different layouts for preview and submit job form. Trying to get my layouts to work was tricky because both preview and the submit job form are wrapped in a single shortcode **[submit_job_form]**

To remedy this issue I attempted to put my different layouts in job-submit.php and job-preview.php. This worked fine except the errors are not being called within the two template files. This caused the errors to display above my layout rather than above the form:

![screen shot 2018-04-06 at 11 41 45 am](https://user-images.githubusercontent.com/1271601/38430573-9f7fa862-398f-11e8-8e05-3fc67b46bd75.png)

In abstract-wp-job-manager-form.php line 114 this is what is outputting the errors. Should be an action or function within the templates.

**Comment by mikeyarce** [comment]
Closing this as it seems like it's an issue with customization and not with the plugin.
