### ISSUE TITLE
Adding two seperate Attachment fields to the Application form

### ISSUE THREAD

**Issue by JMaartenW** [Automattic/WP-Job-Manager#1426]
#### Steps to Reproduce
1. add a 2nd file attchment field in the form 
2.make both file attachment non-multiple files but required
3. do test application and upload one file  in each field

#### What I Expected
to receive an employer email notification with both files attached

#### What Happened Instead
only the first default file arrived with the email

#### WordPress / WP Job Manager Version
latest version

#### Browser / OS Version
Chrome latest version

#### Context / Source

because i need to ensure each application has 2 attachements at all times

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core WP Job Manager plugin only. For support, including the Applications plugin, please visit https://wpjobmanager.com/support.
