### ISSUE TITLE
Fixing multiple submissions when using applications and resume manager

### ISSUE THREAD

**Issue by bengoodson** [Automattic/WP-Job-Manager#1451]
Wordpress version - WordPress 4.9.5
Jobs manager version - 1.30.2 + core addons bundle.

**Steps to reproduce:**
- Create a job
- Enable the setting so that the candidate can only apply with a resume
- Enable 'Prevent users from applying multiple times' 
- Find a job
- Click 'apply for job'
- Click 'send application' button multiple times
- Check the jobs dashboard and view the applications number

**What I expect:**
- A single application for the position

**What happens:**
- Multiple applications are received from the same user

**Fix:**
- I assume that somewhere some error checking JS has been missed.  I've written some in jQuery that has the benefit of working on any submit button.

/*start*/

if (jQuery('input[type="submit"]').length) {
checkFormSubmit();
}

function checkFormSubmit(){
var button = jQuery('input[type="submit"]');
var init = 0;
button.each(function(){
	jQuery(this).on('click',function(e){
		init++;
		if (init > 1) {
			e.preventDefault();
			jQuery(this).val('Please wait ...',function(){
				jQuery(this).attr('disabled','disabled');
    		});
		}
	});
});
}
*/end*/

**Comment by jom** [comment]
This is just for the WPJM core plugin.  I'll mark this enhancement request in the respective repositories.
