### ISSUE TITLE
Override content-job_listing.php

### ISSUE THREAD

**Issue by mattiasghodsian** [Automattic/WP-Job-Manager#1458]
#### Steps to Reproduce
add content-job_listing.php to your custom made theme in job_manager folder

#### What I Expected
Loading content-job_listing.php template from theme folder

#### What Happened Instead
Nothing happens no hooks can be seen

#### WordPress / WP Job Manager Version
WP 4.9.5 / WP JOB MANAGER 1.30.2

#### Browser / OS Version
Chrome

#### Context / Source
I am currently trying to override  content-job_listing.php template but with no success when dumping out what files are used in the front end i can not find content-job_listing.php

```
string(97) "/srv/users/site/apps/dev/public/ng/wp-content/themes/ng/job_manager/job-filters.php"
string(114) "/srv/users/site/apps/dev/public/ng/wp-content/plugins/wp-job-manager/templates/job-filter-job-types.php"
string(104) "/srv/users/site/apps/dev/public/ng/wp-content/themes/ng/job_manager/job-listings-start.php" 
string(102) "/srv/users/site/apps/dev/public/ng/wp-content/themes/ng/job_manager/job-listings-end.php"
```

with this in functions.php
```
add_filter( 'job_manager_locate_template', 
    function( $template, $template_name, $template_path )
    {


    	var_dump($template);

    	
        return $template;
    }
, 10, 3 );
```
My Settings
![Extras](https://imgur.com/ONIxZlD.png)

Template files inside my theme
[ng.zip](https://github.com/Automattic/WP-Job-Manager/files/1920894/ng.zip)

**Comment by jom** [comment]
Template overrides work for me, but you need to set your `<tbody class="job_listings">`. That class name is important. GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.

Full content of your `job-listings-start.php`:
```
<?php
/**
 * Content shown before job listings in `[jobs]` shortcode.
 *
 * This template can be overridden by copying it to yourtheme/job_manager/job-listings-start.php.
 *
 * @see         https://wpjobmanager.com/document/template-overrides/
 * @author      Automattic
 * @package     WP Job Manager
 * @category    Template
 * @version     1.15.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}
?>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Job posting title</th>
      <th scope="col">Location</th>
      <th scope="col">Department</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody class="job_listings">
```
