### ISSUE TITLE
the title

### ISSUE THREAD

**Issue by Zwillingscraft** [Automattic/WP-Job-Manager#1460]
Hi 

I search for a solution to replace the the_title in WP resume Manager with a custom value,
it would be great if there is a solution to use the candidate_title   or job_title field for generating the post title   - is there a solution for wp resume manager ? 

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting core WPJM bugs and feature requests. For support and feature requests for our extensions, please visit https://wpjobmanager.com/support.
