### ISSUE TITLE
Deleting Users Should Delete All Of Their Associated Data

### ISSUE THREAD

**Issue by bengoodson** [Automattic/WP-Job-Manager#1463]
I've noticed when deleting users that it doesn't delete their resumes or applications.  I think that there should be an option to delete all of their data upon deletion of the user object.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for WPJM core only. For support, please visit https://wpjobmanager.com/support.

For this issue, when you're deleting the user, are you selecting "Delete all content"? That should delete all CPTs that they are associated with.
