### ISSUE TITLE
Open links in current tab

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1473]
Reported in 1121083-zen

This one in particular:

https://github.com/Automattic/WP-Job-Manager/blob/master/templates/content-single-job_listing-company.php#L30

Though we have a few more: https://github.com/Automattic/WP-Job-Manager/search?utf8=%E2%9C%93&q=target%3D%22_blank%22&type=

Should we consider removing them, since they sometimes don't work (I was able to reproduce this on the site):

https://answers.microsoft.com/en-us/ie/forum/ie10-windows_7/ie-10-does-not-open-links-with-target-blank/74c9a624-538e-48fb-83f1-36a86aca1249

**Comment by jom** [comment]
Probably should remove them for accessibility, too. Seems like that is the best practice.

**Comment by donnapep** [comment]
Changed the title since the original ticket mentioned in the issue description was not caused by IE10's security settings.
