### ISSUE TITLE
Job Location Not working in WPBakery Page

### ISSUE THREAD

**Issue by pantsman28** [Automattic/WP-Job-Manager#1475]
WP Job Manager current Version 1.31.0 and WP WordPress (Version 4.9.5)

shortcode [jobs  location=”Worcester”]  i.e. narrow down to area location is not working. Its placed in latest build of WPBakery Page Builder version 5.4.7 - Text block which seems to be causing the problem.

I have tested this with other standard themes and all other plugins turned off. It only seems to work outside of the WPBakery Page Builder.

Anyone fix this?

The page I need help with: https://www.redwoodsearch.co.uk/worcester-recruitment-agency-worcester-job-agency/

The short code above is whats being used.

Happy to give more info if needed thanks

**Comment by mikeyarce** [comment]
Closing as it looks like this has been resolved.
