### ISSUE TITLE
WP Job Manager jobs not loading

### ISSUE THREAD

**Issue by BuildingSiteDesign** [Automattic/WP-Job-Manager#1477]
WP Job Manager jobs not loading jobs on search from location field. Keywords are functioning as they should.

Currently backfill form indeed using WP Job Manager Indeed Integration

Java script console in Safari shows error on:

line 88: window.console && "abort" !== a && window.console.log(a + ": " + t)

error: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Any Ideas?

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs with reproducible steps and feature requests. For support, please visit https://wpjobmanager.com/support. If you have an active license of Indeed integration plugin you'll be able to submit a support ticket.
