### ISSUE TITLE
unable to remove region column Google Maps link from admin backend (only).

### ISSUE THREAD

**Issue by hughc** [Automattic/WP-Job-Manager#1478]
I'd like to stop linking to a Google Map from the admin column for region terms, but there is nothing admin-specific to hook into here. 

Line 529 of `includes/admin/class-wp-job-manager-cpt.php` calls `the_job_location()` incorrectly:

`''
case "job_location" :
				the_job_location( $post );
			break;
'''

The first parameter should be a boolean, the second the `$post`. It works as is, but appears to be via luck more than design (as it's called in the admin cpt list loop).

Yes, I can use the `the_job_location_map_link` filter, along with a test of `is_admin()` to craft a filter link. 
Rather than just doing this, could we wrap this in an admin-specific filter so that users can write admin specific versions of the column contents. 

something like:

`echo apply_filters("the_job_location_admin_column",  get_the_job_location($post), $post);`

A default hook for the column could do the map linking, but could be unhooked if i wanted to hook something else (like a link to filter posts by region).

**Comment by hughc** [comment]
to clarify this is a bit; as it stands, the way `the_job_location()` is called, with the missing boolean, makes rewriting the link hard, as the $post var is empty when the `the_job_location_map_link` filter is called.

**Comment by jom** [comment]
Filing as bug report to fix the `the_job_location()` call:
https://github.com/Automattic/wp-job-manager/blob/33a98587b91bff750a2de4d6af34511087204abe/includes/admin/class-wp-job-manager-cpt.php#L529-L530

I'm not quite sure what you want to do with the filters. I think you're best bet is adding another custom column using `manage_edit-job_listing_columns` and `manage_job_listing_posts_custom_column` filters.

**Comment by hughc** [comment]
I couldn't see why anyone would want to link to Google maps from the admin list page. Surely a content filter link would be more useful? Ended up writing this filter, but it is a pretty blunt tool to get the job done. An admin hook for the column would be cleaner,

```

    add_filter( 'the_job_location_map_link', 'edit_admin_location_link', 10, 3 );

    function edit_admin_location_link($text, $location, $post) {
      if (!is_admin()) return $text;

      // fix for the way the params are passed in admin
      if (!$post) $post = get_post();
      $locations = wp_get_object_terms( $post->ID, 'job_listing_region');
      $r_array = Array();
      foreach ($locations as $loc) {
        $url =  admin_url(sprintf("edit.php?job_listing_region=%s&post_type=job_listing", $loc->slug));
        $r_array[] = sprintf("<a href='%s'>%s</a>", $url, $loc->name);
      }

      return implode(", ", $r_array);
    }
```
