### ISSUE TITLE
Cosmetic change to "Uploaded files need to be..." string.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#1479]
A user in 1103206-zen reports that the [mention of JPG files](https://github.com/Automattic/WP-Job-Manager/blob/fa9347765e51a9b7cb95554dad841ac7b1256504/wp-job-manager-functions.php#L1291) in the "Uploaded files need to be..." string looks messy:

![uploaded_files_need_to_be](https://user-images.githubusercontent.com/7585054/39479111-47ab892e-4d32-11e8-9aa4-4ad4c4560c9c.png)

 Can we make this look a bit prettier?

**Comment by richardmtl** [comment]
I think adding a space before and after each | symbol will do the job!

**Comment by jenhooks** [comment]
Yep, that would probably be enough.

**Comment by richardmtl** [comment]
Hi @oscarssanchez ! Thanks for the PR! Looks good to me, we'll let a developer take a look at it and confirm, and merge it when they're ready. :)

**Comment by oscarssanchez** [comment]
That sounds great @richardmtl , thanks!

**Comment by jenhooks** [comment]
@jom -- could you have a look at the above from @tripflex ?
