### ISSUE TITLE
job description wysiwyg not loading in browser when adding job

### ISSUE THREAD

**Issue by belindawaldock** [Automattic/WP-Job-Manager#1485]
Hi
im having issues reported that the wysiwyg editor is not loading when trying to add an new job post in firefox and i think chrome, working ok in IE .. 
any ideas what might be causing this and if a bug with plugin browser compatibility or likely another reason? 
thanks
B

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support. If you're able to come up with reproducible steps to produce in a fresh environment (with Twenty Seventeen and non-WPJM plugins deactivated), feel free to comment again and we can re-open the ticket.
