### ISSUE TITLE
When themes support archive page, allow for custom archive page slug

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1486]
Right now, when a theme has support for `job-manager-templates` the archive page slug defaults to `jobs`, which often conflicts with the automatically created `[jobs]` page. 

We should allow people to customize this slug in Permalink settings (when theme support is enabled) and have it default to something that won't conflict (like `job-listings`).

This will require an upgrade rule. All old instances that have set something for the post type's `has_archive` when declaring the post type (either by theme support or filter), we'll want to have it default to whatever they've set. Otherwise, when people enable theme support, we should default it to the non-conflicting slug.

**Comment by RajeebTheGreat** [comment]
Hi @jom,

I would like to take on this issue and start working.

Can you please mention what do you mean by the `upgrade rule` here? 

Thank you :)

**Comment by jom** [comment]
Hi @RajeebTheGreat! In `WP_Job_Manager_Install::install()`, we'll need to do a version check before the version this is released  (slated for 1.32.0). One thing to check is if the `job_listing` post type has been registered when this is called during an upgrade before we check for `has_archive` value (as described in issue). This will be a bit tricky to test.

For implementing this, we can add `jobs_base` to the setting referenced in `WP_Job_Manager_Post_Types::get_permalink_structure()`.
