### ISSUE TITLE
Previewing job when submitting leads to 404 when BuddyPress and bbPress are active

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1489]
Originally reported in 1146751-zen (as well as on a few random threads in different forums).

To reproduce:

1) Install WPJM, bbPress and BuddyPress on a site
2) For WPJM, have "Enable account creation during submission" and "Email new users a link to set a password" checked (I did not try with other permutations)
3) For the other two plugins, install them and go through their activation wizards, but leave the default settings.
4) While not logged in, submit a job and click Preview

Expected result: See the preview of the job posting

Actual result: WordPress-generated 404 page.

In this thread: https://buddypress.org/support/topic/buddypress-conflict-when-previewing-new-job-listsings-or-resume-listings/

A moderator said the following:

<blockquote>Definetly not a BP or bbP issue IMHO.
– Once you click on preview, you get a page not found. OK
Because the entered user IS NOT registered as member.
After the first click he’s registered.

– If he goes back in browser history to the edit form, and click again on preview he can see it.

I suppose it’s because of his status change – not member/member.

And this is defined by the plugin for the job submit form.</blockquote>

**Comment by mikeyarce** [comment]
Tested this out today and it no longer seems to be a problem!  I was able to preview the job without seeing a 404.
