### ISSUE TITLE
Cannot duplicate job entry from dashboard - ERROR: Missing Submission Page

### ISSUE THREAD

**Issue by di1lon** [Automattic/WP-Job-Manager#1496]
#### Steps to Reproduce
1. Purchase and install WP Job Manager - Applications
2. Create a new job listing
3. From the /career-dashboard/ hover over the job listing name and select duplicate

#### What I Expected
I expected to get a new job edit listing form with prepopulated with all of the job listing data.

#### What Happened Instead
I received an error message: Missing Submission Page.

#### WordPress / WP Job Manager Version
WP Job Manager Version 1.31.0
WP Job Manager - Applications Version 2.3.0

#### Browser / OS Version
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/12600340/40201272-35e086f4-59e4-11e8-95c6-5b6968e3b7b0.png)

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for WPJM core only. For support and reporting issues of the paid extensions, please visit https://wpjobmanager.com/support.
