### ISSUE TITLE
Resume management

### ISSUE THREAD

**Issue by C-Nog** [Automattic/WP-Job-Manager#1498]
#### Steps to Reproduce
1.
2.
3.

#### Context / Source

I'm using My Listing theme to display a job board, which is a really good theme. But I'm finding difficult to store resumes inside my WordPress panel. I need to allow only registered users to apply for a job. User has to fill a form, upload his Resume and store this data on WP  panel, showing which vacancie the candidate applied. I'm using WP job manager (native from the theme) and Resume manager plugin, but It doesn't shows which vacancie the candidate is interested after filling the form. Someone can help with a smart solution?

**Comment by richardmtl** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for WPJM core only. For support and reporting issues of the paid extensions, please visit https://wpjobmanager.com/support.
