### ISSUE TITLE
WP Job Manager 1.31.0 does not work "Location" and set "Anywhere" instead.

### ISSUE THREAD

**Issue by johnwainer** [Automattic/WP-Job-Manager#1499]
I am using WP Job Manager 1.31.0, I inserted the Google Maps API correctly, I removed the restrictions, and "Anywhere" is still coming out when I create a new "Location", for example "Miami, Fl"

**Comment by richardmtl** [comment]
As I said in the other thread, can you start a new thread in the WPJM support forum, please? If we determine that your issue is a new bug, we'll open up a new issue here. Thanks!

https://wordpress.org/support/plugin/wp-job-manager/
