### ISSUE TITLE
WPJM: Make Jobs dashboard responsive

### ISSUE THREAD

**Issue by rakmob42** [Automattic/WP-Job-Manager#1500]
Currently Jobs dashboard is non-responsive as follows:

![image1](https://user-images.githubusercontent.com/20779676/40294601-efbf7186-5cf3-11e8-8379-c129521c5016.png)

Next step: We need to make it responsive! 

Ticket: https://woothemes.zendesk.com/agent/tickets/1167250

**Comment by jenhooks** [comment]
Would changing the HTML div `<div id="job-manager-job-dashboard">` to `<div id="job-manager-job-dashboard" style="overflow-x:auto">` fix this?

**Comment by jenhooks** [comment]
Reported in 2047624-zen

**Comment by Braehler** [comment]
This CSS here adds a scrollbar to the bottom. This is a workaround for now
`div#job-manager-job-dashboard {
    overflow-x: scroll !important;
}`

**Comment by danjjohnson** [comment]
I put together a temporary CSS workaround for both this and the Candidate Dashboard (Resume Manager). They can be tweaked as necessary.

**Job Dashboard**
```
@media(max-width: 768px) {
    /* Hide the table headings */
    table.job-manager-jobs thead {
        left: -9999px;
        position: absolute;
        visibility: hidden;
    }
    table.job-manager-jobs tr {
        border-bottom: 0;
        display: block;
        margin-bottom: 40px;
    }
    table.job-manager-jobs td {
        border: 1px solid;
        display: block;
        margin: 0 -1px -1px 0; /* Removes double-borders */
        width: 100%;
        position: relative;
        text-align: right !important;
    }
    table.job-manager-jobs td:before { 
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 0;
		left: 0;
		font-size: 0.6em;
		font-weight: bold;
		text-align: right;
		background: #eee;
		padding: 6px; 
		white-space: nowrap;
	}
    /*
	Label the data
	*/
	table.job-manager-jobs td:nth-of-type(1):before { content: "Title"; }
	table.job-manager-jobs td:nth-of-type(2):before { content: "Filled?"; }
	table.job-manager-jobs td:nth-of-type(3):before { content: "Date Posted"; }
	table.job-manager-jobs td:nth-of-type(4):before { content: "Listing Expires"; }
	table.job-manager-jobs td:nth-of-type(5):before { content: "Applications"; }

}
```

**Candidate Dashboard**
```
@media(max-width: 768px) {
    /* Hide the table headings */
    table.resume-manager-resumes thead {
        left: -9999px;
        position: absolute;
        visibility: hidden;
    }
    table.resume-manager-resumes tr {
        border-bottom: 0;
        display: block;
        margin-bottom: 40px;
    }
    table.resume-manager-resumes td {
        border: 1px solid;
        display: block;
        margin: 0 -1px -1px 0; /* Removes double-borders */
        width: 100%;
        position: relative;
        text-align: right !important;
    }
    table.resume-manager-resumes td:before { 
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 0;
		left: 0;
		font-size: 0.6em;
		font-weight: bold;
		text-align: right;
		background: #eee;
		padding: 6px; 
		white-space: nowrap;
	}
    /*
	Label the data
	*/
	table.resume-manager-resumes td:nth-of-type(1):before { content: "Name"; }
	table.resume-manager-resumes td:nth-of-type(2):before { content: "Age"; }
	table.resume-manager-resumes td:nth-of-type(3):before { content: "Location"; }
	table.resume-manager-resumes td:nth-of-type(4):before { content: "Category"; }
	table.resume-manager-resumes td:nth-of-type(5):before { content: "Date Posted"; }

}
```

**Comment by dericleeyy** [comment]
3829644-zen

**Comment by gaurav1984** [comment]
4210653-zen

**Comment by aqademik** [comment]
hi, i have the same issue. When i copy paste a job from excel sheet the table doesnt fit on mobile device and it breaks the look of the page [here is an example page](https://aqademik.com/ilan/istanbul-medeniyet-universitesi-ogretim-uyesi-ve-ogretim-elemani-alim-ilani/) i am using buddyboss theme. If you have answer for this please make it simple i am not so familiar with codes thank you!

**Comment by renrax** [comment]
> I put together a temporary CSS workaround for both this and the Candidate Dashboard (Resume Manager). They can be tweaked as necessary.
> 
> **Job Dashboard**
> 
> ```
> @media(max-width: 768px) {
>     /* Hide the table headings */
>     table.job-manager-jobs thead {
>         left: -9999px;
>         position: absolute;
>         visibility: hidden;
>     }
>     table.job-manager-jobs tr {
>         border-bottom: 0;
>         display: block;
>         margin-bottom: 40px;
>     }
>     table.job-manager-jobs td {
>         border: 1px solid;
>         display: block;
>         margin: 0 -1px -1px 0; /* Removes double-borders */
>         width: 100%;
>         position: relative;
>         text-align: right !important;
>     }
>     table.job-manager-jobs td:before { 
> 		/* Now like a table header */
> 		position: absolute;
> 		/* Top/left values mimic padding */
> 		top: 0;
> 		left: 0;
> 		font-size: 0.6em;
> 		font-weight: bold;
> 		text-align: right;
> 		background: #eee;
> 		padding: 6px; 
> 		white-space: nowrap;
> 	}
>     /*
> 	Label the data
> 	*/
> 	table.job-manager-jobs td:nth-of-type(1):before { content: "Title"; }
> 	table.job-manager-jobs td:nth-of-type(2):before { content: "Filled?"; }
> 	table.job-manager-jobs td:nth-of-type(3):before { content: "Date Posted"; }
> 	table.job-manager-jobs td:nth-of-type(4):before { content: "Listing Expires"; }
> 	table.job-manager-jobs td:nth-of-type(5):before { content: "Applications"; }
> 
> }
> ```
> 
> **Candidate Dashboard**
> 
> ```
> @media(max-width: 768px) {
>     /* Hide the table headings */
>     table.resume-manager-resumes thead {
>         left: -9999px;
>         position: absolute;
>         visibility: hidden;
>     }
>     table.resume-manager-resumes tr {
>         border-bottom: 0;
>         display: block;
>         margin-bottom: 40px;
>     }
>     table.resume-manager-resumes td {
>         border: 1px solid;
>         display: block;
>         margin: 0 -1px -1px 0; /* Removes double-borders */
>         width: 100%;
>         position: relative;
>         text-align: right !important;
>     }
>     table.resume-manager-resumes td:before { 
> 		/* Now like a table header */
> 		position: absolute;
> 		/* Top/left values mimic padding */
> 		top: 0;
> 		left: 0;
> 		font-size: 0.6em;
> 		font-weight: bold;
> 		text-align: right;
> 		background: #eee;
> 		padding: 6px; 
> 		white-space: nowrap;
> 	}
>     /*
> 	Label the data
> 	*/
> 	table.resume-manager-resumes td:nth-of-type(1):before { content: "Name"; }
> 	table.resume-manager-resumes td:nth-of-type(2):before { content: "Age"; }
> 	table.resume-manager-resumes td:nth-of-type(3):before { content: "Location"; }
> 	table.resume-manager-resumes td:nth-of-type(4):before { content: "Category"; }
> 	table.resume-manager-resumes td:nth-of-type(5):before { content: "Date Posted"; }
> 
> }
> ```

Exemple for Jobs:

 ```
jQuery(document).ready(function($){
    var titles = [];
    $('table.job-manager-jobs thead tr th').each(function(i, elem) {
        titles[i] = $(elem).text();
    });

    var style = document.createElement('style'),
    head = document.head || document.getElementsByTagName('head')[0];

    var css = '@media(max-width: 1028px) {';
    css += 'table.job-manager-jobs thead';
    css += 'table.job-manager-jobs tr';
    css += 'table.job-manager-jobs td';
    css += 'table.job-manager-jobs td:before';

    $.each(titles, function(i, title) {
        css += 'table.job-manager-jobs td:nth-of-type(' + (i + 1) + '):before { content: "' + title + '"; }';
    });

    css += '}';

    style.type = 'text/css';
    if (style.styleSheet){
        style.styleSheet.cssText = css;
    } else {
        style.appendChild(document.createTextNode(css));
    }

    head.appendChild(style);
});
 ```
 CSS
 ```
@media(max-width: 1028px) {
    /* Hide the table headings */
    table.job-manager-jobs thead {
        left: -9999px;
        position: absolute;
        visibility: hidden;
    }
    table.job-manager-jobs tr {
        border-bottom: 0;
        display: block;
        margin-bottom: 40px;
    }
    table.job-manager-jobs td {
        border: 1px solid;
        display: block;
        margin: 0 -1px -1px 0;
        width: 100%;
        position: relative;
        text-align: right !important;
    }
    table.job-manager-jobs td:before { 
        position: absolute;
        top: 0;
        left: 0;
        text-align: right;
        padding: 6px; 
        white-space: nowrap;
    }
}
 ```

**Comment by yscik** [comment]
Done in https://github.com/Automattic/WP-Job-Manager/releases/tag/2.3.0
