### ISSUE TITLE
Search returning zero results, blog results or case sensitive results.

### ISSUE THREAD

**Issue by cestrian77** [Automattic/WP-Job-Manager#1501]
#### Steps to Reproduce
1. Carry out keyword search in WP Job Manager
2.
3.

#### What I Expected
Job results matching the keyword search

#### What Happened Instead
I'm getting mixed results, depending on the site/installation I try this with. On some sites I'm getting zero results. On others, I'm getting blog results returned. On some I'm seeing the search only working with case sensitive queries. 

#### WordPress / WP Job Manager Version
4.9.6

#### Browser / OS Version
Windows 10 Pro / Google Chrome 66.0.3359.181

#### Screenshot / Video

This is what I see if I search for "science" - all lowercase.
![no-results](https://user-images.githubusercontent.com/11726700/40313077-8d57f888-5d0c-11e8-94b3-df71c3a9e2e6.png)

Then if I search for "Science" with a capital 'S'... I get results returned.
![results](https://user-images.githubusercontent.com/11726700/40313089-9506b4c0-5d0c-11e8-828d-0c39eec0b5ac.png)

**Comment by cestrian77** [comment]
If I leave the page open, I subsequently get a POST error message in the Console that looks like:

jquery.js?ver=1.12.4:4 POST https://www.DOMAIN.co.uk/wp-admin/admin-ajax.php 0 ()
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
call_ajax @ job_count_ajax.js?ver=4.9.6:21

Not sure if this helps?

**Comment by cestrian77** [comment]
And an admin-ajax.php (failed) error message too:

![admin-ajax](https://user-images.githubusercontent.com/11726700/40313823-981d2c28-5d0e-11e8-8bda-85de17aa5802.png)

**Comment by richardmtl** [comment]
Hi! GitHub Issues is for reporting core WPJM bugs and feature requests. For support and feature requests for our extensions, please visit https://wpjobmanager.com/support. For support for the core plugin, post in the forum: https://wordpress.org/support/plugin/wp-job-manager/

As a first step to troubleshooting this, though, I'd suggest switching to a default theme like Twenty Seventeen, to see if your theme is getting in the way.

**Comment by richardmtl** [comment]
@cestrian77 We consider a bug to usually be something wrong with the code; until we've determined that this is the case, let's take this to the forum or our support form (if you have a paid add-on), shall we? Thanks!

**Comment by cestrian77** [comment]
Panic over! I've identified that we had some custom script in our child theme's functions.php aimed at narrowing search to posts only (ie excluding pages). This used to work, but I guess a recent update has now led to it conflicting. Removing the code instantly fixes the issue.

**Comment by richardmtl** [comment]
Thanks for letting me know! For future cross-referencing, you opened this thread: https://wordpress.org/support/topic/wp-job-manager-search-not-working-properly/

**Comment by webdesignvision** [comment]
Dear Team,

I am facing with the same issue unfortunately.

Could you please advise?

Thank you in advance
