### ISSUE TITLE
"TypeError: a(...).size is not a function" - Add support for jQuery 3.x

### ISSUE THREAD

**Issue by mborn319** [Automattic/WP-Job-Manager#1502]
#### Steps to Reproduce
1. Install any version of jQuery 3 on the website, such as jQuery 3.2.1.
2. Customize the application form (I'm not sure if this step is necessary or not.)
3. Fill out and submit the application form.

#### What I Expected
A clear console with no JS errors, and a working application which I could fill out and submit.

#### What Happened Instead
Could not submit the application. My JS console shows:

```
TypeError: a(...).size is not a function[Learn More] application.min.js:1:36
	<anonymous> http://[redacted].com/wp-content/plugins/wp-job-manager-applications/assets/js/application.min.js:1:36
	j https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29997
	g/</k< https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313
```

#### WordPress / WP Job Manager Version
Wordpress 4.9.6

#### Browser / OS Version
Firefox 61

**Comment by mborn319** [comment]
My apologies, this is an issue with the [WP Job Manager Applications](https://wpjobmanager.com/add-ons/applications/) plugin - not WP Job Manager itself.

**Comment by richardmtl** [comment]
For what it's worth, best practice with WordPress is NOT to load your own jQuery, but to use the version that comes packaged with WordPress itself. As such, most plugins (if they follow the best practice) are coded to work with that version, and not others; therefore, we won't fix this issue unless and until that version of jQuery comes packaged with WordPress.
