### ISSUE TITLE
Data Privacy: Add user meta to user extract

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1506]
The meta keys that we add to user profiles can be included in WP Core's new data export feature.

**Comment by shantanu2704** [comment]
Hi @jom 
I'd like to pick this up, but before I do, could you please confirm that the following are the meta keys that you'd like to be included in the data export and erasure tool -

- _company_logo
- _company_name
- _company_website
- _company_tagline
- _company_twitter
- _company_video
