### ISSUE TITLE
Job Alerts not deleted when deleting corresponding user

### ISSUE THREAD

**Issue by mamirago** [Automattic/WP-Job-Manager#1511]
I think there is a little bug in the job alerts plugin. When a new subscriber creates a new job alert and is deleted by an admin afterwards, then the user entry in the database is deleted, however her or his job alerts in the wp_posts database are not, although the box for deleting all her or his contents is checked. Now when a user is created with the same id, those old job alerts are assigned to the new user with the same id.
It's nothing severe, of course, but I still thought it might be an issue worth reporting. One of the reasons could be, that job_alerts return false on post_type_supports('job_alert', 'author') and when the post type is registered, 'delete_with_user' is unset, which prevents wordpress from deleting the contents by default when calling.

step by step reproduction:
- create new user (i.e. register as a new one while creating a new job) (assume the new user is called john)
- create a job_alert
- check database entry in wp_users for john 
- check database entry in wp_posts for the job_alert
- logout as john
- login as an admin
- delete the new user making sure the users contents are scheduled for deletion as well
- check database entry in wp_users for john (gone, as expected)
- check database entry in wp_posts for the job_alert (still there)
- create new user
- check the users job alerts
- repeat last two steps until you are lucky enough to get johns job_alerts (might not be successful even after multiple times) 

I hope I made myself clear, English is not my native language. Of course, I do not want to exclude the possibility, that the issue might be my fault because of a mistake on my side. If so, I would like to apologise in advance.

Best regards,

mamirago

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the WPJM core plugin. For support or reporting bugs for the core plugins, please visit https://wpjobmanager.com/support.
