### ISSUE TITLE
Add the install-wp-tests.sh file to the plugin

### ISSUE THREAD

**Issue by shantanu2704** [Automattic/WP-Job-Manager#1516]
Currently, the plugin doesn't contain a `install-wp-tests.sh` file that generates all the files needed for running tests.

When the `phpunit` command is run from inside the plugin directory, it throws a bunch of errors similar to -
`Warning: require_once(/tmp/wordpress-tests-lib/includes/functions.php): failed to open stream: No such file or directory`
and
`Fatal error: require_once(): Failed opening required '/tmp/wordpress-tests-lib/includes/functions.php'`

These directories are created by `bash bin/install-wp-tests.sh <db-name> <db-user> <db-pass> <db-host> <wp-version>` and then `phpunit` can be run successfully.

So I'd like to either add the `bin/install-wp-tests.sh` file to the plugin or perhaps add these steps in the README file for developers trying to run the existing unit tests and/or trying to add their own.

Thanks!

**Comment by mdbitz** [comment]
Shantanu, this is a great idea. Lets move forward with creation of the bin/install-wp-tests.sh script as well as adding a note to the readme file on how to run the unit tests locally.

**Comment by shantanu2704** [comment]
Thanks, Matthew!
I will proceed by creating the necessary file using `wp scaffold plugin-tests` and write a first draft for the README file.

**Comment by mdbitz** [comment]
@shantanu2704 I would keep it in the readme file. Documentation should be on how to use the plugin and examples from my perspective.
