### ISSUE TITLE
User can submit a listing with multiple categories when "Multi-select Categories" is unchecked in Settings

### ISSUE THREAD

**Issue by alexsanford** [Automattic/WP-Job-Manager#1517]
#### Steps to Reproduce
1. Go to Job Listings > Settings, uncheck "Multi-select Categories" and save
2. Submit a job using the frontend. Notice that you can supply multiple categories.

#### What I Expected

I expected to only be able to supply a single category when posting a job.

#### What Happened Instead

I was able to supply multiple categories.

#### Other Notes

The helper text for the setting is inconsistent. It says the following:

_The category selection box will default to allowing multiple selections on the [jobs] shortcode. Without this, users will only be able to select a single category when submitting jobs._

This seems to be saying that the change to the [jobs] shortcode implies that the user will not be able to submit multiple categories. However, the [jobs] shortcode is not related to the user's ability to submit multiple categories; the two UI's are separate.

Incidentally, the [jobs] shortcode works properly; it has a single-select or multi-select for the category filter based on the value of this setting.

**Comment by cena** [comment]
Also reported in 1214442-zen.

**Comment by jom** [comment]
I think this is more an issue with the description of the setting. I believe that setting is just for the `[jobs]` shortcode.

**Comment by tripflex** [comment]
@jom I agree, this is only used in the `show_category_multiselect` param for `job_manager_output_jobs_defaults` in `output_jobs` ... so really it would just be updating the lang to state something like:

> The category selection box will default to allowing multiple selections on the [jobs] shortcode (for filtering)

**Comment by jom** [comment]
@cena just to clarify, this setting was never meant to limit the number of categories during submission, just on the filter form in the `[jobs]` shortcode. The "fix" was to clarify the language on that setting.

**Comment by jom** [comment]
Closing for now, as I think this is a different issue (possibly an enhancement request if people want it).
