### ISSUE TITLE
Add export to XLSX Resumes and/or Applications option

### ISSUE THREAD

**Issue by 1DayWebs** [Automattic/WP-Job-Manager#1520]
We are using the plugin to force Resumes to be added and then apply with them.  Client needs an Excel export of the applications (showing Resume fields) per Job Listing. 

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin only. For support, especially questions/comments regarding our paid plugins, please visit https://wpjobmanager.com/support.
