### ISSUE TITLE
Escaped code shown on job listing pages

### ISSUE THREAD

**Issue by Rick-Pro** [Automattic/WP-Job-Manager#1547]
God Evening, 

I wanted to report a major issue that we experience when upgrading the WP Job manager plugin from 1.30 to 1.31. 

On each job post, we manually add a script that is provided by Google directly to display ads. We have been using this procedure for months now.  When we updated the plugin today it broke the Google script, ads were no longer showing and instead a portion of the script was displaying on every job post. The moment we reverse to the plugin to the previous version, the ads started to display again with no problem. 

Can you please provide a fix or update to the current latest release?
 

#### Steps to Reproduce
1. Upgrade plugin from version 1.30 to latest release

#### What I Expected
Improved functionality

#### What Happened Instead
Broke all the Google ads script that we had on each job posting. We reverse immediately and the issue got resolved. 

#### WordPress / WP Job Manager Version
1.30  Latest Release 1.31,1

#### Browser / OS Version
Chrome

#### Screenshot / Video
N/A

#### Context / Source
On every job post we add the google ads code to display adds. we add it in the body of the job post since we display it at the begining and the end of each job post.

**Comment by Rick-Pro** [comment]
The issue was also reported on your (WP JOb Manager) twitter and on your support forum https://wordpress.org/support/topic/latest-release-1-31-1-major-issue-broke-google-ad-script-i-had-to-revert/  

Thanks so much for your help.

**Comment by jom** [comment]
@Rick-Pro We added quite a bit of string escaping. In order to accept this as a bug report, you need to provide reproducible steps from a vanilla fresh install of WordPress, including the code/plugin you're using to add the Google Ads.

**Comment by Rick-Pro** [comment]
Thanks so much for following up. We only have the live version of the site,
so I am not attempting to duplicate the problem until I get a Dev
environment set up.  However, there was no custom code, just the same code
that Google gives everyone for ad-sense. I have been using that exact same
code for over a year and it always worked fine. The moment I updated the
plugin it broke the display of the ads for all the present and previous
posts. Once I rolled back the plugin everything went back to normal. Hense,
I am sure it is the current update that created the issue. Nothing else was
touched.

If your team want to replicate the issue, all they have to do is create a
post on a WP page with a google ad-sense code and upgrade the plugin to the
most current version.

I hope this helps. Let me know if there is any other info I can share.

Cheers,

Rick.

On Sat, Jul 21, 2018 at 4:22 AM, Gabriel Maldonado <notifications@github.com

**Comment by jom** [comment]
Were you pasting that code into the job description? If so, does it vary job listing to job listing? There are better ways of placing that code on job listings that won't be escaped. Right now, generally, most people shouldn't be allowed to paste scripts/special code into job listings.

**Comment by iamgabrielma** [comment]
Hei @Rick-Pro , I'm closing this issue in GitHub for the moment until we can get reproducible steps for this problem and/or rule out any possible conflict.

I'll followup with you via email to debug this and if ultimately is a problem with WP Job Manager we can always open it again so our developers can take a look into it.

**Comment by Rick-Pro** [comment]
@jom @iamgabrielma  

Hey Guys, 
Sorry for the late reply, I have been super busy running my company, but I had to rollback to the previous version of the plugin that is working with no problem. I was now able to partner with Wordpress Professional that is taking over the maintenance on the site and he is experiencing the same issue, and I have asked him to participate on this thread to provide additional information to help. 

But we are still experiencing this issue every time we update to a newer version of the plugin, even with the newest release as of this week. 

Thanks so much for your help. 
Sincerely.  
Rick.

**Comment by Rick-Pro** [comment]
@jom & @iamgabrielma 

Thanks so much for your help. While the problem was not technically solved, I found a workaround, by adding the scrip to one of the plugin files in the child theme. After that was able to update with no problems. 

Thanks so much for your help.  I appreciate it.
