### ISSUE TITLE
Job Type can't be selected since 1.31.1

### ISSUE THREAD

**Issue by FernandoSalinas33** [Automattic/WP-Job-Manager#1552]
Since updating to WPJM 1.31.1 Admins are unable to select or edit a Job Type from the Admin Dashboard.

When creating a Job from the backend, the Radio button will not allow selecting a Job Type. When Editing a job with a Job Type is how it is generated without being able to change the Job Type: https://cloudup.com/cWD3tzLgLKh

**Comment by spencerfinnell** [comment]
Fixed in https://github.com/Automattic/WP-Job-Manager/pull/1550 👍

**Comment by jom** [comment]
Will be released today.
