### ISSUE TITLE
Location Problem

### ISSUE THREAD

**Issue by ealparslan48** [Automattic/WP-Job-Manager#1554]
I am using findgo theme which works with job manager plugin. While I am posting new listing I am choosing location and google map updating it self and showing map marker at correct position. Once I update or publish the page, map marker is being disappear and showing world map as below screen shop.  At the end listing location is not being shown with location at fronted.   
http://i.hizliresim.com/2a9vR0.png
Can some one help how to fix this ?

Warm Regards,

#### Steps to Reproduce
1.
2.
3.

#### WordPress / WP Job Manager Version
4.9.7  / 1.31.2

#### Browser / OS Version
Chrome

#### Screenshot / Video
http://i.hizliresim.com/2a9vR0.png

**Comment by jom** [comment]
Hi there! The screenshot is not available, but as the core plugin doesn't provide any mapping functionality this sounds like a theme issue. Please contact the theme author for support.
