### ISSUE TITLE
Is WPJM REST API available yet???

### ISSUE THREAD

**Issue by adedayomatt** [Automattic/WP-Job-Manager#1557]
I just want to confirm if the REST API is available and stable yet. Please share me the link to the documentation if available. Thanks.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.

It is not stable. Hopefully next major release (no ETA). Follow this for updates:
https://github.com/Automattic/WP-Job-Manager/issues/1303
