### ISSUE TITLE
1.31.1 breaks priority sorting with decimals

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1562]
The update in commit https://github.com/Automattic/WP-Job-Manager/commit/51ecd6a792a80df832653b9c39e23a153303d533 to use `intval` on priorities, has broken priority sorting when using decimal places (which is really popular, especially sites with large number of fields).

Was this done just to match PHPCS reports, or was there a specific reason behind this change?  I suggest reverting back to original handling for priorities, or switch to using `floatval` instead 

https://github.com/Automattic/WP-Job-Manager/blob/4a50eb21e9c9641a071e4e79de48a7cd75f2999e/includes/abstracts/abstract-wp-job-manager-form.php#L239-L243

**Comment by jom** [comment]
It was a PHPCS fix, but `floatval()` works for me.

**Comment by tripflex** [comment]
@jom I submitted a PR to fix this, LGTM 👍
