### ISSUE TITLE
Registration of new user doesn't give any notification but creates the new user.

### ISSUE THREAD

**Issue by malkiatsingh** [Automattic/WP-Job-Manager#1563]
Hi there,

I am facing issues on the website, there is no notification to the user when they register or post a vacancy/CV. In the background it is done but the page is not updated and it looks as if the website is inactive and nothing happened.

Please help

Kind regards
Malkiat Singh

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin only. For support, especially for our paid plugins such as Resume Manager and Applications, please visit https://wpjobmanager.com/support.
