### ISSUE TITLE
add custom field and not see nothing in the view page

### ISSUE THREAD

**Issue by ofirk12** [Automattic/WP-Job-Manager#1571]
Hello I add code to function to add custom filed and take out fields that i dont want, when i submit the job i dont see any details beside the description , what i need to do to change the page to be with all the details ?

![download 14](https://user-images.githubusercontent.com/8176351/43755822-3dafa8ea-9a55-11e8-94ab-97de658ac66a.png)
![download 15](https://user-images.githubusercontent.com/8176351/43755824-3de19c06-9a55-11e8-98ed-7c39b5319d75.png)

**Comment by tripflex** [comment]
You need to manually add the fields to output on the listing ... there isn't any "magic" or "automatic" output of custom fields on the listing page, that is up to the user (or any addon plugins you use) to output them.

See documentation at the bottom of this page:
https://wpjobmanager.com/document/tutorial-adding-a-salary-field-for-jobs/
