### ISSUE TITLE
UI in wp-admin for editing placeholder text in job listing form fields.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#1575]
A user has requested the ability to easily edit and/or add placeholder text for the job listing form fields -- i.e. _"Choose a category..."_ or _"Briefly describe your company..."_

I recommended a string replacement plugin to modify existing placeholders, but this wouldn't allow wp-admin addition of placeholder text where there isn't any yet.

**Comment by tripflex** [comment]
This can all be done easily through filters (or using field editor plugin), super simple:
https://wpjobmanager.com/document/editing-job-submission-fields/

This could be done using the Code Snippets plugin as well, to avoid having to deal with child theme's functions.php

What specific fields are they referring to that don't have placeholders yet?  We could look at adding placeholders where there may not be any ... but that also depends on the type of field

**Comment by jenhooks** [comment]
Hi @tripflex -- thanks! 

> What specific fields are they referring to that don't have placeholders yet? We could look at adding placeholders where there may not be any ... but that also depends on the type of field

I can't find the ticket again offhand, but if I remember correctly, there was something the user was trying to do that wasn't covered by that documentation. When I come across it again (or have time to dig it up), I'll share specifics.
