### ISSUE TITLE
Job Dashboard not fully responsive on mobile. 

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#1576]
Ticket: 1350251-zen

This user reports that the Job Dashboard is not fully responsive on mobile using the Hestia theme:

![mobile_job_dashboard](https://user-images.githubusercontent.com/7585054/44213555-fa57ca80-a13b-11e8-9eb4-9cfbe07dae5b.png)

They say it would be an easy fix, by changing the HTML div  `<div id="job-manager-job-dashboard">` to:

`<div id="job-manager-job-dashboard" style="overflow-x:auto">`

Screenshot from the user, after adding the style:

![mobile_job_dashboard_fixed](https://user-images.githubusercontent.com/7585054/44213590-09d71380-a13c-11e8-92ce-d8389a3404a1.jpg)

I checked this out on my test site with a few frequently used themes, and the Job Dashboard doesn't behave well with other themes, either:

**With Jobify:**

![job_dashboard_jobify_mobile](https://user-images.githubusercontent.com/7585054/44214411-13617b00-a13e-11e8-9929-6d6ba8c6455c.PNG)

**With RoboJob Lite:**

![job_dashboard_robojoblite_mobile](https://user-images.githubusercontent.com/7585054/44214423-1b211f80-a13e-11e8-8457-9bfde5674060.PNG)

**With Twenty Seventeen**

![job_dashboard_2017_mobile](https://user-images.githubusercontent.com/7585054/44214437-2411f100-a13e-11e8-95c1-76a7f1581824.PNG)

**With Twenty Sixteen**

![job_dashboard_2016_mobile](https://user-images.githubusercontent.com/7585054/44214444-2aa06880-a13e-11e8-86c1-8f6817f42869.PNG)

**With Listify**

![job_dashboard_listify_mobilepng](https://user-images.githubusercontent.com/7585054/44214453-312ee000-a13e-11e8-9303-99ab57958947.PNG)

**Comment by tripflex** [comment]
Related to #1500

**Comment by jenhooks** [comment]
Missed that one. Closing this in favor of it -- thanks!
