### ISSUE TITLE
single page job listing company logo does not sit in correct position

### ISSUE THREAD

**Issue by JMaartenW** [Automattic/WP-Job-Manager#1582]
#### Steps to Reproduce
1. create a job listing and add a company logo
2. preview the page - without custom CSS the logo sits too low
3. add a company tagline to the post listing and the logo now sits correctly in the centre ( although the tagline needs to be line up with the company name on the line above
4. remove the tag line and add Custom CSS 
.single_job_listing .company img {
  margin-top: -16px;
}
the logo now sits correctly without a tagline
5. now add a tagline and the Company logo sits too high on the line

#### Browser ALL / OS Version win10 ent

the code needs to be adjusted so that the company logo sits centred on the line with and without a company tag 

-->

**Comment by 0xDELS** [comment]
Hello,

@iamgabrielma, @donnapep  can we bypass the verification of the strlen on the company tagline? Doing this we can "force" the <p class="tagline"></p> to appear every time. Would this be a acceptable fix?

It would give us something like this.
![without](https://user-images.githubusercontent.com/36240423/48590462-76c69900-e937-11e8-81cb-3dcd2a86f56d.PNG)


And with the tagline. (NOTE: i've aligned the company tagline with the company name)
![with](https://user-images.githubusercontent.com/36240423/48590499-9493fe00-e937-11e8-9faa-1868ed7ec7d5.PNG)

**Comment by JMaartenW** [comment]
yes that would work ok ! 
when will this fix appear in the plugin on my website?

**Comment by JMaartenW** [comment]
please note the company logo also sits too low without CSS amendment if there is no tagline.

**Comment by 0xDELS** [comment]
> please note the company logo also sits too low without CSS amendment if there is no tagline.

Hi @JMaartenW , i've also made the CSS amendements. Even if you don't fill the Company Tagline field it should work. I'm just holding on the PR to see if this was an acceptable fix by the developers.

**Comment by JMaartenW** [comment]
hi, when will this fix appear in the Live version? what version will the bug fix appear in? This really is a big issue for us and urgently need this fix?!

**Comment by iamgabrielma** [comment]
> when will this fix appear in the Live version? what version will the bug fix appear in?

Hi @JMaartenW , if the pull request is accepted by the plugin developers and works as expected, it will possibly go in the next release of WP Job Manager.

For the moment you'll have to rely on the CSS that was already added to your site to not see this issue.

**Comment by jom** [comment]
Closed by #1622
