### ISSUE TITLE
Job posting: without tagline, company logo position is wrong.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#1583]
During job posting previews and in the job listing itself, a company logo is positioned incorrectly when no company tagline is added in the job listing. A user reported this in 1379778-zen (theme: Avada), and I was able to reproduce it on my test site (theme: Storefront).

**Screenshot of listing preview with tagline:**

<img width="948" alt="tagline_present" src="https://user-images.githubusercontent.com/7585054/44815723-4da33180-abae-11e8-8dd4-c48476987b38.png">

Note, however -- the tagline is justified too close to the logo -- there needs to be a space there.

**Screenshot of listing preview without tagline:**

<img width="955" alt="tagline_absent" src="https://user-images.githubusercontent.com/7585054/44815729-572c9980-abae-11e8-944c-7dbd9580b007.png">

**To reproduce:**

1. Create a job listing with a company logo.
2. Preview the listing -- logo is positioned too low.
3. Edit the listing to add a company tagline -- preview. Logo now positioned correctly. 

**Partial CSS solution:**

```
.single_job_listing .company img { 
margin-top: -16px; 
 } 
```

Using this CSS, the logo is positioned correctly without a tagline, however, adding a tagline (while using this CSS) will position the logo too high.

**Comment by donnapep** [comment]
@jenhooks Looks like the user already created #1582 for this.
