### ISSUE TITLE
Allow additional HTML entities in job listing post content

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1584]
In our recent HTML escaping PRs we started doing a pass on `the_content()` through `wp_kses_post()`. This is filtering out safe transformations (such as YouTube embeds) in `the_content` hook.

https://github.com/Automattic/WP-Job-Manager/blob/7ea7454fd98b9bf655b452f1193118ae5525e0fb/wp-job-manager-template.php#L532

To fix this, I think we should add a new context to `wp_kses_allowed_html` (allowing for everything in `posts` + ifames), pass it through `wp_kses` in `wpjm_get_the_job_description()`, and `echo` it with a `// WPCS: XSS ok.` exception in `wpjm_the_job_description()`. 

Alternatively, we could run `wp_kses_post` on the raw `post_content` value in `wpjm_get_the_job_description()` and then apply `the_content` filter on the final value.

#### Steps to Reproduce
1.  Create a job post with a YouTube link on one line.
2. View the job.

#### What I Expected
YouTube video to be displayed.

#### What Happened Instead
No YouTube embed in job description.

#### WordPress / WP Job Manager Version
4.9.x / 1.31.3

#### Browser / OS Version
Chrome

#### Context / Source
https://wordpress.org/support/topic/why-embedded-youtube-wont-show-up-in-single-job-page/

**Comment by 0xDELS** [comment]
Hi @jom ,

I might have a fix for this issue based on your approach. Can discuss this for 5 minutes, like on slack or something just to see if my approach is valid?

**Comment by jom** [comment]
Quasi-related #1672; this approach might fix both issues:
> Alternatively, we could run wp_kses_post on the raw post_content value in wpjm_get_the_job_description() and then apply the_content filter on the final value.
