### ISSUE TITLE
Job listing fields data not show in rest api

### ISSUE THREAD

**Issue by marianagarciaferreira** [Automattic/WP-Job-Manager#1585]
I'm trying to list via WP rest API however I noticed that the listing data fields do not come out in the rest API

**Comment by jom** [comment]
Have you turned them on with the custom constant `WPJM_REST_API_ENABLED` in `wp-config.php`? WPJM's REST API features are currently in beta and could change. Follow #1303 for updates. No ETA.

**Comment by iamgabrielma** [comment]
Closing this due no reply from the OP. Please open a new issue if you still experience problems, with as many details as possible.
