### ISSUE TITLE
Remove reference to `spinner.gif` in CSS

### ISSUE THREAD

**Issue by benharold** [Automattic/WP-Job-Manager#1586]
WP Job Manager uses a relative URL to reference the `spinner.gif` file that is included with WordPress as of this commit: https://github.com/Automattic/WP-Job-Manager/commit/bed45230a45fe1f9db13d45dfcd18f2083dc4622

This causes a 404 error on WordPress installations where a user chooses to [give WordPress it's own directory](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory).

Rather than referencing a file which may or may not be there, it would be best to simply include the `spinner.gif` with WP Job Manager such that the location of the file is well known.

**Comment by jom** [comment]
There is the quick reference in the CSS but it should be corrected here:
https://github.com/Automattic/WP-Job-Manager/commit/bed45230a45fe1f9db13d45dfcd18f2083dc4622#diff-db434871f9320e69f6ad7e91ba4e2de3R77

What is the configuration of your WordPress install that is preventing this from working?

**Comment by jom** [comment]
What is currently being generated for the element `style` CSS for:
`background-image: url(<?php echo includes_url( 'images/spinner.gif' );`

That should be fixing any abnormal path.

**Comment by benharold** [comment]
If that's the case then I would submit that the `background: url(../../../../../wp-includes/images/spinner.gif) no-repeat;` declaration should be removed so as to not cause unnecessary pollution of web logs with 404 errors.
