### ISSUE TITLE
rest api query

### ISSUE THREAD

**Issue by vnh1991** [Automattic/WP-Job-Manager#1588]
https://github.com/Automattic/WP-Job-Manager/issues/1303

for my job module on my site http://itzshowtime.singlestaging.com/jobs/
when i export the rest api json http://itzshowtime.singlestaging.com/wp-json/wp/v2/job-listings

The inner content is returned as html and not in json format.
`"content":{"rendered":"<p>This event is for Males.<\/p>\n<h3>Work Profile<\/h3>\n<ul>\n<li>Promote the brand ...`

I'm talking about the content in the content.rendered node of the json
https://pastebin.com/VWM6yYY5 or http://itzshowtime.singlestaging.com/wp-json/wp/v2/job-listings

Need pointers on how i can get the inner rendered content in json key value node format

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
