### ISSUE TITLE
Application field auto populating new listings with user email (even if app method set to URL only)

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1591]
https://github.com/Automattic/WP-Job-Manager/blob/68d32d068d1e095036c5ed2c1f8562c1bb00dbdf/includes/admin/class-wp-job-manager-writepanels.php#L66

Looks like by default as you can see in the code above, if meta doesn't exist on a listing when it's created from admin area, it auto populates that field value with the current user's email address.

My main concern with this is that even if the application method is configured in the settings for "Website URLs only" ... this field is still populated with a user's email address ...

My opinion on this is that we should either remove this entirely (only populating from existing value), check the application method and only populate if email is enabled, or add something in settings to enable/disable this feature

I think there are a few options we have to resolve this:

1. Completely remove the auto populate from user's email
2. Only populate if application method has email allowed (URL & Email, or Email only)
3. Add a setting to enable/disable this feature, or even just a text box to save as option for "application populate value" or something

Thoughts? @jom

**Comment by tripflex** [comment]
@jom this is still an issue, any thoughts on this (had a client contact me regarding it)?  I can submit a PR for a fix just want to make sure we're all in agreement of the best way to approach this.

**Comment by jom** [comment]
@tripflex This is all getting refactored by #1731. I'll fix in that issue.
