### ISSUE TITLE
Expired jobs or jobs without expiration are not counted under job categories

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/WP-Job-Manager#1593]
#### Steps to Reproduce
1. Create a job without expiration date or set a past expiration date
2. Add it to a Job Category
3. Go to Job Listings > Job Categories
4. See how the job is not counted under `count` on its category
5. Go back to Job Listings > All Jobs and edit the same job
6. Add an expiration date in the future and save changes.
7. Go back to Job Listings > Job Categories
8. See how now the job is counted.

#### What I Expected

The job to be counted no matter if is expired, or no expiration date has been set.

#### What Happened Instead

Expired jobs, or these without expiration date, are not shown or counted under Job Listings > Job Categories

#### Screenshot / Video

See how there's 8 jobs categorized as `test-job`, but only 4 of them are not expired (October 5 and 11). The rest either are expired or have no expiration date set:

<img width="1280" alt="screen shot 2018-09-25 at 13 29 42" src="https://user-images.githubusercontent.com/3812076/45996996-61b45300-c0c8-11e8-975e-0b5f453f4172.png">

Job Listings > Job Categories shows only these 4 jobs:

<img width="1280" alt="screen shot 2018-09-25 at 13 30 04" src="https://user-images.githubusercontent.com/3812076/45996997-61b45300-c0c8-11e8-93f0-5a2d646bb4ef.png">

After editing the expiration dates of one of the expired jobs, 5 jobs show up now:

<img width="1174" alt="screen shot 2018-09-25 at 13 41 16" src="https://user-images.githubusercontent.com/3812076/45997103-bce64580-c0c8-11e8-97cf-193e6777f7c1.png">

**Comment by tarifa10** [comment]
hello dear iamgabrleilmam 

great to see you  - my dear iamgabrleilmam - coming up with this ideea. I really like this idea. 
'Well dear  - many many thanks for your work - it is a great pleasure to see this project so vialbe. Again - many thanks for your engaged work!

  Keep up the great project!

greetings Martin --

**Comment by interlineae** [comment]
@iamgabrielma I've been extensively testing the behaviour reported:

- I'm able to replicate the behaviour where job listings with an `expired` post status aren't contributing to the **Jobs --> Jobs Categories** count.
- I'm unable to replicate the behaviour where this is occurring for posts without an expiration date. Those posts _are_ contributing towards the **Jobs --> categories** count, though that might not have been the case when this was first reported.

After reviewing this with @aaronfc, we've determined that the `expired` post status behaviour is intended. This is behaviour that's seen with other post statuses' as well, such as `pending`. As `expired` job listings are treated as no longer active, we don't expect them to populate counts.

With that in mind, I'm going to go ahead and close this with two caveats:

- If you continue to experience behaviour where posts with no expiration date aren't contributing to post counts, I'll take another look.
- If there are additional requests for `expired` posts to populate the counts, we can change this to an `enhancement` request and reopen.

Thanks!
