### ISSUE TITLE
Remove “Filled” column from Job Dashboard snippet 

### ISSUE THREAD

**Issue by freudknows** [Automattic/WP-Job-Manager#1594]
Hello @iamgabrielma,

Thanks for providing me the code on this issue. 
https://github.com/Automattic/WP-Job-Manager/issues/1592

Would you be able to provide me the same code to remove the 'filled' column from the frontend as well? 
I have tried:

add_filter( 'job_manager_job_dashboard_columns', 'remove_expires_column' );

function remove_expires_column( $columns ) {
unset( $columns['filled'] );
return $columns;
}

But this code is not working. 
Thanks in advance. :)

**Comment by donnapep** [comment]
If you need help with WP Job Manager, we ask that you please [open a ticket](https://wpjobmanager.com/support) with our Support team. GitHub issues is reserved for reporting bugs and feature requests. Thx!
