### ISSUE TITLE
Styling the word "Applied" in the job title differently

### ISSUE THREAD

**Issue by imfaisalkh** [Automattic/WP-Job-Manager#1595]
I'm using default `[jobs]` shortcode to list the jobs on the front-end. If I apply to any job the word "Applied" is appended to the job title. The issue is, this word does not seem to have any markup around it so I cannot style it differently from the regular title. How can I add some markup around this word (i.e. `<span>Applied</span>`)?

**Comment by donnapep** [comment]
If you need help with WP Job Manager, we ask that you please [open a ticket](https://wpjobmanager.com/support) with our Support team. GitHub issues is reserved for reporting bugs and feature requests. Thx!
