### ISSUE TITLE
Changing the text of "Posted xx weeks/months ago"

### ISSUE THREAD

**Issue by imfaisalkh** [Automattic/WP-Job-Manager#1596]
I'm using default `[jobs]` shortcode to list the jobs on the front-end. In this listing each job has a posting date with a string something like "Posted xx weeks/months ago". Now, I want to strip the word "Posted" from this string and only want the other part. I've checked the source code of the plugin and it seems no filter hook is available for the function named `the_job_publish_date()`. How can I achieve my requirement?

**Comment by donnapep** [comment]
If you need help with WP Job Manager, we ask that you please [open a ticket](https://wpjobmanager.com/support) with our Support team. GitHub issues is reserved for reporting bugs and feature requests. Thx!
