### ISSUE TITLE
"Select Category" filter does not work

### ISSUE THREAD

**Issue by sublines** [Automattic/WP-Job-Manager#1598]
I have several job categories and all job listings are assigned to one or more category. However, in the admin dashboard, the drop down "Select category" does not work. 
The other filters "Select filled", "Select featured" etc. work fine but "Select category" doesn't show the categories.

#### Steps to Reproduce
1. Create job categories
2. Assign jobs to categories
3. Try to use the "Select category" filter on the job listings page

#### What I Expected
To show the list of categories. At least the ones that actually have a job listing assigned to them.

#### What Happened Instead
It shows nothing.

#### WordPress / WP Job Manager Version
WordPress 4.9.8
WP Job Manager 1.31.3 with all add-ons from the bundle installed

#### Browser / OS Version
Chrome 69 or any other Browser

#### Context / Source
[Ref](https://github.com/Automattic/WP-Job-Manager/blob/98e78e8b11d977bac7705d4bb815d7838c39887b/includes/admin/class-wp-job-manager-cpt.php#L285-L322)

**Comment by jom** [comment]
This issue was reopened here:
https://github.com/Automattic/WP-Job-Manager/issues/1564
