### ISSUE TITLE
Customize the default email application subject line

### ISSUE THREAD

**Issue by sarvbbg** [Automattic/WP-Job-Manager#1600]
The default subject line is set to [Job Application via “Job Title” listing on Your Site name] is it possible change it to [Job Application via “Job Title”-"Location" listing on Your Site name]?

In the subject, I want also to show the Location of the job.

How this can be achieved?

Thanks,
Sarvanshu

**Comment by jom** [comment]
Hi there! This can be achieved using the `job_manager_application_email_subject` filter. For support on using this, please visit the product forums:
https://wordpress.org/support/plugin/wp-job-manager

**Comment by ockang** [comment]
I am using wp job manager.

My question is the following.

When the candidate applies for a job, the correct email arrives, but I need to know within the email the position that I apply, in the content and title of the email

**Comment by tripflex** [comment]
@ockang as jom mentioned, this is really meant for the support forums not for GitHub which is meant for issues.

Sounds like you're going through Resume manager, this would be the filter for the content of resume manager:
`apply_with_resume_email_message`

Or use my emails addon:
https://plugins.smyl.es/wp-job-manager-emails/

**Comment by ockang** [comment]
I just need a little function.

I would like to add the related job to the title of the email, thank you

**Comment by ockang** [comment]
what is the filter?
