### ISSUE TITLE
Improve client side Jobs Table Header for each column

### ISSUE THREAD

**Issue by DanielNetzer** [Automattic/WP-Job-Manager#1601]
#### Context / Source

I'm asking for a new feature that adds the ability to create/add a table header with custom column names.

**Comment by jom** [comment]
These are all part of templates/filters that can be overridden.  Is this for the Jobs Dashboard? For that, you can use this filter:
https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-shortcodes.php#L243-L251
