### ISSUE TITLE
Registered user can't delete or hide resumes

### ISSUE THREAD

**Issue by Revy94** [Automattic/WP-Job-Manager#1603]
**Steps to Reproduce**
Hide or Delete a Resume from Resume Dashboard

**What I Expected**
The online resume is deleted or hide

**What Happened Instead**
The browser shows the confirmation popup but when i click on "ok" nothing happens.
After clicking on "ok" the url of the page changes from /index.php/account/curriculum to /index.php/account/curriculum/?action=delete&resume_id=871&_wpnonce=ed86dad267 but nothing happens. 

If i click on modify everithing works.

**WordPress / WP Job Manager Version**
WP 4.9.8
WP Job Manager 1.31.3

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core WP Job Manager plugin. For support on the add-ons, please visit https://wpjobmanager.com/support.

**Comment by GraphicBytes** [comment]
For god sake, this issue has been reported on a few forums and you just close it or link to your support.

Answer the bloody questions on the platforms they are asked on
