### ISSUE TITLE
WPJM: unescaped quotes in apply with email

### ISSUE THREAD

**Issue by wigglemuff** [Automattic/WP-Job-Manager#1605]
## Summary

user reports in 1513933-zen on vanilla (no addons) WPJM that email subjects are unescaped, when apply for job is set to 'email addresses only'

## Steps to Reproduce

1.  Set Job Listings->Job Submisstions->Application Method to "email addresses only'.
2. View and apply for job.
3.  See email subject line

### Expected Result

That email subject line would be escaped properly.

### Actual Result

<img width="649" alt="application via quot testing backend job submission quot listing on http wpjmdefault local 2018-10-25 11-27-59" src="https://user-images.githubusercontent.com/19334/47515798-64ca6c80-d849-11e8-85e3-cfc44956d9f1.png">

cc: @cena (issue moved here as it is reproducible).

**Comment by codestor4** [comment]
1518512-zen

**Comment by jom** [comment]
Fixed by #1606
