### ISSUE TITLE
WordPress 5.0 - Meta boxes not compatible with the block editor 

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/WP-Job-Manager#1608]
Discovered this when testing [my add-on](https://github.com/iamgabrielma/WPJM-Company-Profile-Page/issues/9) for 5.0 . This happens with the core plugin as well, with no further add-ons or plugins activated.

#### Steps to Reproduce
1. Install WordPress 5.0 from [here](https://wordpress.org/wordpress-5.0-beta1.zip)
2. Activate WP Job Manager
3. Create a new listing via wp-admin, or edit an existing one.
4. See error messages under `job data` and `job types`:

<img width="1151" alt="screen shot 2018-10-27 at 18 51 07" src="https://user-images.githubusercontent.com/3812076/47603795-0ce35f80-da1b-11e8-9144-771d252d07ba.png">

#### WordPress / WP Job Manager Version

- WordPress 5.0

I have added the `Question` label because while with the current WordPress version this should be an enhancement, from mid-November this will be a bug.

**Comment by spencerfinnell** [comment]
Related: 
https://core.trac.wordpress.org/ticket/45207

**Comment by jom** [comment]
I don't think this applies.
