### ISSUE TITLE
Use email as username

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#162]
Mike just wanted to let you know about this plugin.  Pretty simple and my main focus was for Jobify but it works just the same for WP Job Manager.  Right now you have it use the email address (without @domain.com) as username, this plugin will simply use the entire email address as the username:

https://github.com/tripflex/wp-job-manager-reg-use-email

**Comment by contractorcloud** [comment]
Great plugin! The username field remains though, any suggestions on how to remove that field? Thank you!
