### ISSUE TITLE
Resolve incompatibility with block editor and job description rich text

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1626]
When we implement #1625 the block editor will be enabled (by default) for `job_listing` CPT. Generally, the meta boxes seem compatible with WordPress 5.0 and the new block editor. There is a  problem with job listings that are edited with a mix of the frontend (job dashboard shortcode) and WP admin. For job listings created or edited in WP Admin from the block editor, blocks could get messed up when edited from the standard `wp_editor()` from the job dashboard. In A Dream World, we'd have a mini frontenberg block editor for the job dashboard editor. What complicates this is already complicated functionality/hack is the guest posting functionality of WPJM.

For now, we need something that helps us immediately mitigates this issue. Possible solutions:
- Prevent block editor from being used for job listings CPT.
- Prevent jobs with non-classic blocks from being edited on the job dashboard.
- See if it is possible to just allow the classic block in the block editor.

**Comment by alexsanford** [comment]
It would be interesting to know how much "mixed editing" actually happens. I have some assumptions, and some ideas of a solution based on those assumptions, but it would be nice to know objectively.

Could we add some usage tracking data for this? For example, maybe we add a piece of meta on every listing that is created/edited on the frontend, and another for listings that are created/edited on the backend, and we add the number of listings with one or the other or both to usage tracking.

Specifically, my assumption is that the number of listings edited in both places on any given site is low (i.e. people will use the frontend, or they will use WP Admin, but generally not both for a single listing). If we find that is correct, we could design our solution accordingly (e.g. disable Gutenberg entirely for frontend-edited listings).

That said, given the timeline for 5.0 compatibility, we may need to just make an assumption and ship a solution. In that case, I would still argue that we should add the usage tracking data to test the validity of our assumption.

**Comment by spencerfinnell** [comment]
My vote would be for

> See if it is possible to just allow the classic block in the block editor.

Definitely possible to create a locked template including only a single Classic block for the Job Listing post type: https://github.com/WordPress/gutenberg/blob/master/docs/designers-developers/developers/block-api/block-templates.md
