### ISSUE TITLE
Creating short code combining 2 tags like SEO Jobs in Delhi & for a Job Tag specific page all search fields aren't coming

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1629]
#### Steps to Reproduce

1. I am using Job Tag shortcode to pull all the jobs for a specific job tag.
like [jobs_by_tag per_page="15" tag="content-optimization"] and showing me all jobs without search bar like
http://prntscr.com/lf238c
I want to show search bar with a list of jobs list for specific job tag Like http://prntscr.com/lf25si

2. Can arguments of [jobs] and [jobs_by_tag] are combine?
example: I want to show all jobs which are matching Job tag "Content" and for the job location in London? https://snag.gy/ybimzL.jpg 
Thanks in Advance

**Comment by thedigitalcircle** [comment]
Please any one can light up the issue?

**Comment by richardmtl** [comment]
Hi!

This repo is for bug reports, not for support requests. Please contact us here if you have an add-on subscription:

https://wpjobmanager.com/support/

Otherwise, please start a new thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!
