### ISSUE TITLE
Enableb Gutenberg with filter but can't see taxonomy boxes

### ISSUE THREAD

**Issue by wpublish** [Automattic/WP-Job-Manager#1639]
As instructed by maddisondesigns here: https://github.com/WordPress/gutenberg/issues/6757#issue-323131944

I activated Gutenberg for WP Job Manager posts to see how far your valuable work has achieved on this. All working greatly, but I found that taxonomy boxes (in my case: Regions, Categories and Amenities) aren't visible/available. So I'd like to ask:

1) Am I missing something? Should I activate them with additional code to 'register_post_type_args' filter? Or this implementation is on progress and should I wait?

2) Do you plan to add a setting to activate/deactivate Gutenberg for WP Job Manager posts? Consider this a suggestion :)

Cheers!

#### Steps to Reproduce
1. Add to functions.php of the theme:

```
add_filter( 'register_post_type_args', 'wpse247328_register_post_type_args', 10, 2 );
function wpse247328_register_post_type_args( $args, $post_type ) {

    if ( 'job_listing' === $post_type ) {
        $args['show_in_rest'] = true;
    }

    return $args;
}
```

2. Go to admin dashboard, Jobs / Settings / Job Listings. activate 'Categories' checkbox and 'Save changes'.

3. Optionally, install/activate 'Regions for WP Job Manager': [https://br.wordpress.org/plugins/wp-job-manager-locations/](url)

4. Start editing a WP Job Manager post.

#### What I Expected
To see custom taxonomy boxes (in my case: Regions, Categories and Amenities) visible as a drop down menu on the right side of the screen, the same way that "Categories" are available to WordPress default "Posts" editor.

#### What Happened Instead
Custom taxonomy boxes aren't visible/available, so I can't select, deselect, add or exclude taxonomy terms for current post.

#### WordPress / WP Job Manager Version
WordPress 5.0.
WP Job manager 1.31.3

#### Browser / OS Version
Any browser.

#### Screenshot / Video
Before: https://prnt.sc/lspzmj
After: https://prnt.sc/lsq0qu

**Comment by jom** [comment]
Hi there! Some additional support will be in the next release (due out January). There are some PRs getting merged soon you could use to test. `master` has added the necessary flags for the CPT _and_ taxonomies.
