### ISSUE TITLE
how to add salary to resume post_name/permalink WPJM - Resume manager

### ISSUE THREAD

**Issue by gregory-n7** [Automattic/WP-Job-Manager#1650]
#### Steps to Reproduce
1. How to add salary to the resume page / permalink
2.
3.

#### What I Expected
I have found the code on the resume manager tutorial (Changing the resume post_name/permalink) to replace permalinks, but I would like to keep location but also add salary on to the [resume] page

#### WordPress / WP Job Manager Version
Versions = Wordpress 5.02 / Job manager 1.31.3 & resume 1.17.0

#### Browser / OS Version
Chrome

#### Screenshot / Video
![resume](https://user-images.githubusercontent.com/46421223/50737661-b6419100-11d4-11e9-992f-5643db5cc1b1.PNG)

**Comment by alexsanford** [comment]
Hi there! It would be best to ask this in a [support ticket](https://wpjobmanager.com/support/) or on the [community forum](https://wordpress.org/support/plugin/wp-job-manager). We prefer to keep Github issues for verified bugs.
