### ISSUE TITLE
Jobs page on Divi - JS error prevents load in some cases

### ISSUE THREAD

**Issue by alexsanford** [Automattic/WP-Job-Manager#1656]
#### Steps to Reproduce
1. Install Divi.
2. Go to the Jobs page on the frontend. It should work fine.
3. Use the Keyword input to perform a search. Notice when the search is performed, the string `#s=1` is appended to the page URL.
4. Reload the page. The reload will not be successful, and a JS error will appear: `Syntax error, unrecognized expression: #s=1`

This issue appears to be specific to the theme (I do not see the same problem on Twenty Nineteen, for example). However, there may be themes other than Divi that have this problem.

Setting the initial priority to "Low" since we don't have evidence that this issue is widespread.

- WP 5.0.2
- WPJM 1.31.3

**Comment by alexsanford** [comment]
Worth noting: the JS error occurs on the Resumes page as well, but the render still works fine. So maybe the two are unrelated?

**Comment by mikeyarce** [comment]
Tested with WPJM 1.41.0 and Divi 4.22.1 and the issue is not there any more.
