### ISSUE TITLE
PHP 7.3 Compat: Continue Targeting Switch issues Warning

### ISSUE THREAD

**Issue by rebeccahum** [Automattic/WP-Job-Manager#1663]
Hi there!

Looks like the below line generates a PHP 7.3 compat warning:

https://github.com/Automattic/WP-Job-Manager/blob/3ca296767387ae76a17c58eb9d3a188b52c4a8e8/includes/admin/class-wp-job-manager-writepanels.php#L704

> continue statements targeting switch control flow structures will now generate a warning. In PHP such continue statements are equivalent to break, while they behave as continue 2 in other languages.

http://php.net/manual/en/migration73.incompatible.php#migration73.incompatible.core.continue-targeting-switch

**Comment by richardmtl** [comment]
Another report in 1738799-zen

**Comment by jom** [comment]
In addition to these, we'll need to update (see: WooCommerce) Emogrify for the new regex.
