### ISSUE TITLE
How to get user password to link to WooCommerce / WP job manager account

### ISSUE THREAD

**Issue by gregory-n7** [Automattic/WP-Job-Manager#1665]
I have added a password field onto my WPJM register as a developer page. The problem is that it’s not linked to anything, please help!!

What I need help with is to get this password to actually be added to my WooCommerce account / my sites background.

This has been added via a code snippet.

add_filter( 'resume_manager_resume_fields', 
  'wpjms_admin_resume_form_fields' );
function wpjms_admin_resume_form_fields( $fields ) {

 $fields['user_password'] = array(
 'label'   => __( 'Your Password', 'job_manager' ),
 'type'    => 'password',
 'placeholder' => 'password',
    'description' => '',
  'priority' => 11
 );

 return $fields;

}

// Add field to frontend
add_filter( 'submit_resume_form_fields',
'wpjms_frontend_resume_form_fields' );
function wpjms_frontend_resume_form_fields( $fields ) {

 $fields['resume_fields']['user_password'] = array(
 'label'   => __( 'Your Password', 'job_manager' ),
 'type'    => 'password',
 'placeholder' => 'password',
  'required' => true,
    'description' => '',
  'priority' => 11
  );

 return $fields;

}

**Comment by jom** [comment]
This looks like Resume manager instead of WPJM core. Also, Resume Manager now has a password option. Please contact support for more assistance with our official extensions: https://wpjobmanager.com/support.
