### ISSUE TITLE
Can't create reset button when no jobs found

### ISSUE THREAD

**Issue by jgthms** [Automattic/WP-Job-Manager#1670]
This one is driving me crazy. I'm trying to add my own reset button. It works everywhere on the page, except when putting it in the `content-no-jobs-found.php` (where it would make sense).

![wp-bug](https://user-images.githubusercontent.com/1254808/51804065-ea4c2700-2253-11e9-831f-545be3bf3f1c.png)

#### Steps to Reproduce
1. Add a custom reset button (see below) in the `content-no-jobs-found.php` template
2. Add the same button _anywhere else_ on the page (like in `job-filters.php`)
3. Add the appropriate JS (see below)

#### What I Expected

The reset button works in any context.

#### What Happened Instead

The reset button only works when outside the `div.job_listings`.

#### WordPress / WP Job Manager Version

1.31.3

#### Context / Source

```html
<a class="button my-reset">
  Reset filters
</a>
```

```js
function resetSearch() {
  const $list = $('div.job_listings');
  const $form = $('#filters');
  $form.find(':input[name="search_keywords"], :input[name="search_location"], .job-manager-filter').not(':input[type="hidden"]').val("").trigger("chosen:updated");
  $form.find(':input[name^="search_categories"]').not(':input[type="hidden"]').val("").trigger("chosen:updated");
  $(':input[name="filter_job_type[]"]', $form).not(':input[type="hidden"]').attr("checked", "checked");
  $list.triggerHandler("reset");
  $list.triggerHandler("update_results", [1, false]);
}

// Filters
$('.my-reset').click(function() {
  console.log('RESET');
  resetSearch();
});
```

I can't see what is preventing that button to work. I feel like something is disabling all the buttons within the `div.job_listings` but that's just a guess.

Thanks for your help!

**Comment by richardmtl** [comment]
Hi! 

Note that we generally aren't able to help with custom code requests such as this one. If you feel that this is a bug in the plugin, and you have a paid add-on subscription, please contact us here:

https://wpjobmanager.com/support/
