### ISSUE TITLE
Jobs CPT doesn't show password field when job is password protected.

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#1672]
If adding a job in wp-admin, you can choose to password protect it, as with standard post types:

![password_job](https://user-images.githubusercontent.com/7585054/51709661-ff774a80-1ff4-11e9-81c7-691b9924f266.png)

However, when viewing the job, the field to enter the password is not there. I tried with Twenty Sixteen and Storefront. Storefront is being used in the screenshot below:

![no_pw_field](https://user-images.githubusercontent.com/7585054/51709705-1fa70980-1ff5-11e9-9586-4741e05eafae.png)

Internal ticket reference: 1746039-zen

**Comment by tripflex** [comment]
I can confirm this as well.

I also noticed it's being added to the schema markup as well under `description`, with the input field and submit button, so maybe that's the culprit?  

Could also be during autop or something, as I noticed that the form html element is also stripped
