### ISSUE TITLE
Restrict access to my WP job manager applications function

### ISSUE THREAD

**Issue by gregory-n7** [Automattic/WP-Job-Manager#1673]
I would like to restrict access to my WP job manager applications add-on, using the function to only allow the developer 'role' to apply for jobs. I added the code found on your Applications: Limiting applications to a certain role, link below;(https://wpjobmanager.com/document/applications-limiting-applications-certain-role/).

As stated in the above link, I added the below code to my site’s application form.php.

At the top of the file add:

   <?php if ( current_user_can( 'developer' ) ) : ?>
I Replace ROLE with my desired role ‘developer’.

At the end of the file add:

    <?php else : ?>
     Custom content here shown to users without access.
    <?php endif; ?>
The problem is that this has not blocked the employer from applying for jobs, where it is supposed to bring up the restricted content message; "Custom content here shown to users without access."

Could you please assist me correct this code or point me in the right direction to fix this problem with my add-on.

Looking forward to your response.

Regards;

Greg

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin only. For support, especially for the paid addons, please visit https://wpjobmanager.com/support.
