### ISSUE TITLE
Hide Apply for Job button for employer

### ISSUE THREAD

**Issue by mediahausuk** [Automattic/WP-Job-Manager#1674]
#### Steps to Reproduce
1. I created a USER new account in the ROLE of EMPLOYER
2. I added a new job listing with the new account
3. I approved the job listing in my ADMIN account
4. I clicked on MANAGE JOBS in my site which points to this URL

http://www.vedarecruitment.co.uk/job/luton-school-london-16-teacher/

5. I don't know why the APPLY FOR JOB button shows on this page - I am the EMPLOYER - the person who created the job listing - why would I want to apply for the job.

#### What I Expected

I expected the APPLY FOR JOB BUTTON not to be on this page
http://www.vedarecruitment.co.uk/job/luton-school-london-16-teacher/

#### What Happened Instead

the APPLY FOR JOB BUTTON is on this page
http://www.vedarecruitment.co.uk/job/luton-school-london-16-teacher/

#### WordPress / WP Job Manager Version

1.32.0

#### Browser / OS Version

MAC OSX Mojave

#### Screenshot / Video
<img width="1256" alt="screenshot 2019-01-28 at 22 35 39" src="https://user-images.githubusercontent.com/47125551/51871202-a2a9c600-234d-11e9-9279-772c7771fa61.png">

**Comment by 0xDELS** [comment]
I got this.

**Comment by eppul** [comment]
Hi,

What if the employer wants to see what hes/hers listing looks like? Should I be forced to sign out to see what the listing actually looks like? I for one would like all the buttons to be where they should be. 

Thank you for your time.

**Comment by CarlitoDevDreamer** [comment]
Is there a way to only allow logged users to have access to the content of the "Apply for job" button?
