### ISSUE TITLE
Display Name Error On User Account Creation

### ISSUE THREAD

**Issue by mediahausuk** [Automattic/WP-Job-Manager#1675]
en.support.wordpress.com/make-a-screenshot/
-->

#### Steps to Reproduce
1. I went to this page - http://www.vedarecruitment.co.uk/register/
2. I registered a new account (See first screenshot1.jpg)
<img width="1365" alt="screenshot1" src="https://user-images.githubusercontent.com/47125551/51871501-67f45d80-234e-11e9-8104-5946e9e20301.png">

3. I clicked REGISTER to create the new user (submit the new user details)
4. On the /MYACCOUNT/ page the salution is derived from the first part of the email before the @ symbol (See screenshot2.jpg)

<img width="1296" alt="screenshot2" src="https://user-images.githubusercontent.com/47125551/51871908-9c1c4e00-234f-11e9-9286-38a5cea9b5ac.png">

5. Also when I look at this new user in ADMIN you can see that its showing the username as 'earn' - which is incorrect.

![screenshot3](https://user-images.githubusercontent.com/47125551/51871705-04b6fb00-234f-11e9-9277-cfadcb7076b6.png)

#### What I Expected

I expected that a new user should be able to choose thier own username - something they can remember. They should also be able to choose a password on registration too.

#### What Happened Instead

The form only asks for First Name, Last Name & Email then makes up a username based in the first part of the email (before the @) - I mainly deal with schools where many emails are admin@ so this means I will end up with hundreds of users with the same name of admin@ in my user list.

Not good, not good at all.

#### WordPress / WP Job Manager Version
1.32.0

#### Browser / OS Version

CHROME LATEST

**Comment by jom** [comment]
WPJM does not handle the registration page. Please check with your theme.
