### ISSUE TITLE
Google Map API 

### ISSUE THREAD

**Issue by Gnodesign** [Automattic/WP-Job-Manager#1677]
Hi Everybody,

I've been having this issue ever since Google started charging for their map services. I need to get the geolocation of my jobs so that I can show them all in a map but every time I update a job the "job data" doesn't get updated. 

I have enabled the necessary libraries, tried a 2-3 new APIs, still nothing. Is there something that I am missing?

Is there any plan to add support for mapbox? This could be a very nice option and benefit all users of WPJM.

Best Regards,
Gnodesign

**Comment by richardmtl** [comment]
Hi!

This repo is for bug reports, not for support requests. Please contact us here if you have an add-on subscription:

https://wpjobmanager.com/support/

Otherwise, please start a new thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!
