### ISSUE TITLE
Latest Update changes external links opening in new Tabs

### ISSUE THREAD

**Issue by vetpetjobs** [Automattic/WP-Job-Manager#1678]
#### Steps to Reproduce
1. Create new job campaign
2. Add Location data
3. Add application method as a URL, not an email
4. Click on link
5. Click goes straight to Google Maps or client application URL in same Tab
6. Pretty sure (but not 100% certain) that opening these links in prior version opened in new Tab, same as Social Media and client Website links do now

#### What I Expected
Clicks on Location link or application button link to open in new Tab, same as external links to Social Media and client website

#### What Happened Instead
Clicks on Location link or application button link open in same Tab

#### WordPress / WP Job Manager Version
1.32.0

#### Browser / OS Version
Firefox/Chrome/Opera/Edge
Windows 10 current build

#### Screenshot / Video
![190201 veterinary jobs animal technician large animal facility vet pet jobs](https://user-images.githubusercontent.com/45862220/52097852-5b0a8f00-2618-11e9-83a9-1b7b43c9f75a.png)

#### Context / Source
Maximising time on site/multiple page (job) views is a key stat for Job Sites - not opening in new Tab anymore distorts those benchmarks for a site

If requesting a new feature, explain why you'd like to see it added.
-->

**Comment by jom** [comment]
This was intentional. See #1631 and related issue #1473. Although the issue doesn't mention this, it is now thought of as best practice for accessibility so that people can choose when they want a link opened in a new tab.

**Comment by vetpetjobs** [comment]
OK - but the jury is kinda mixed/50:50 in opinion - see this article which also references multiple other sources...

https://www.caktusgroup.com/blog/2017/03/01/opening-external-links-same-tab-or-new/

...with the perennial contrast between marketer needs and accessibility preferences.

Perhaps a back end admin option "Open all external links in a new tab" yes/no checkbox?

Either way, consistency is the key...so if it is the decision for links to open in the same tab/window (and no option to switch this off or on in the admin) then the other links to Social Media and the job ad website (highlighted in green on the screenshot) should also open in the same window - currently they open in new tab.

**Comment by jom** [comment]
@vetpetjobs Those links might come from your theme or another plugin. WPJM core only handles Twitter, which by default now opens in the same tab:
https://github.com/Automattic/wp-job-manager/blob/3e10f3eff8192200d4c6e105838420c36c708c93/wp-job-manager-template.php#L1096-L1110

For now, users can override the templates if the need `target="_blank"`.

**Comment by vetpetjobs** [comment]
Ok
Thanks for your guidance - and thanks so much to you and all the WPJM team for the latest enhancements as well as you ongoing refinements - greatly appreciated.
