### ISSUE TITLE
Search: Show all jobs in selected categories

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1679]
Suggested in 1783293-zen

On the user's site, if you select two categories from the search filter, it will show only jobs that match both categories (usually none). The user would like it to instead show **all** jobs from either category.

Similar (yet opposite) request for tags: https://github.com/Automattic/WP-Job-Manager/issues/1664

**Comment by tripflex** [comment]
So maybe good idea to figure out a way to set comparison to either `AND` or `OR`?  Maybe a checkbox in filters for this?

**Comment by jom** [comment]
How is this different from this setting?
<img width="728" alt="Screen Shot 2019-12-05 at 3 16 12 PM" src="https://user-images.githubusercontent.com/68693/70248012-37e9c800-1772-11ea-8686-ac301b186f98.png">

**Comment by richardmtl** [comment]
Closing. @jom is right, there's already the setting for it. 🤦‍♂ Sorry!
