### ISSUE TITLE
New features on Resume add-on

### ISSUE THREAD

**Issue by rfzamith** [Automattic/WP-Job-Manager#1681]
I am looking to have some features added to the Resume add-on:

1) Video CV upload field, ideally with some backend settings, such as size limit, time limit and compression.
2) Ability to include (or not) the Video CV on a job application
3) Ability to make the Resume public or not, and in case of public, user would be able to pick a slug / username
4) User can choose if they want to make the Resume visible for the employer resume search

Thanks in advance!

**Comment by richardmtl** [comment]
Hi!

Thanks for the suggestions! We won't be adding a video upload field; you can always use the embed option instead. 

As for making a resume public or private, I am not clear on what the purpose of that would be; can you elaborate? I would presume that a job seeker would always want to have their resume publicly viewable and searchable, no?

Finally, in the future, please open a new enhancement request for every new feature you'd like to see; it makes it easier to evaluate and handle them that way! :)

**Comment by rfzamith** [comment]
Hi Richard, many thanks for your reply.

The public/private feature would tick several boxes in my view. Firstly, the ability to easily include or exclude your profile from the open resume search. A candidate may no longer be looking for a job for example. Second, the whole privacy topic is very much alive nowadays. The ability to "deactivate" the profile/account would be very relevant, as by law businesses have to make it very simple for a user to erase their data, or at least deactivate their public profiles.

Also, by having a public profile I'm not just talking about the resume search, but also the ability to share your URL in your CV or in other sites. It's just like having a public linkedin profile. So, one of the toggle buttons would be to have a public profile or not; and another toggle button would be to include (or not) the profile on the resume search.

Hopefully I was able to explain myself clearly!

**Comment by richardmtl** [comment]
Hi!

Thanks for those clarifications. I will open up an enhancement request for the Resume add-on. Note that in the future if you have further suggestions for one of our paid add-ons, don't use this Github repo for it (as this repo is for the core WPJM plugin); instead, contact us here:

https://wpjobmanager.com/support/

Thanks!

**Comment by rfzamith** [comment]
OK, will do!

With regards to the enhancement request, when exactly can I expect to see
an update or a confirmation?

Best regards.

Rui

**Comment by richardmtl** [comment]
@rfzamith when and if the developers decide to implement it, we'll get in contact with you. I can't give you a a timeline, nor even a confirmation that they'll work on it, however.
