### ISSUE TITLE
Can select more than the max number of selections in Checklist

### ISSUE THREAD

**Issue by pjpulumbarit** [Automattic/WP-Job-Manager#1683]
#### What I Expected

When I click Edit Listing, it will prevent selection more than the maxinum number of selections.

#### What Happened Instead

I was able to select more than the maximum number of selections, also I can't deselect an option, whenever I uncheck one, the other options are the one unchecked.

#### WordPress / WP Job Manager Version

1.32.1

#### Browser / OS Version

Chrome / Windows 8.1

#### Screenshot / Video

![image](https://user-images.githubusercontent.com/42906595/52987866-f03ebd80-3437-11e9-9d72-8db6f2ee1418.png)

**Comment by jom** [comment]
@pjpulumbarit Where are you seeing a "maximum number of selections"? I don't believe WPJM core has this setting. This looks like functionality coming from a third-party extension/theme. 

Feel free to comment if I'm misunderstanding.
