### ISSUE TITLE
Search button on Jobs page

### ISSUE THREAD

**Issue by gerryking** [Automattic/WP-Job-Manager#1686]
I would completely agree with the previous view expressed on this matter. The fact that there is not a search button similar to your demo on the premium version of jobs search is a major shortcoming and disappointing to say the least. To advise customers to undertake bespoke customisation is poor response. Likewise, making the statement that you are using a premium theme on your demo is unhelpful. I am building my website using a highly rated premium theme, seemingly just not the same premium theme as you use.

Bearing in mind I've invested time and money in the premium plugin plus addons I'm a disappointed customer.

**Comment by richardmtl** [comment]
Closing; the issue already exists here: https://github.com/Automattic/WP-Job-Manager/issues/1409
