### ISSUE TITLE
WP 5.1+ - Job type does not save from admin area -- removes value when saved from admin

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1687]
#### Steps to Reproduce
1. Employer Submit a Job Front end.
2.On Back End Admin DashBoard, admin hit Approve/Save AS Pending
3.Immediately Job Type(Full Time, Part Time...) got disappeared.

#### What I Expected
Job Will publish with selected Job Type after Approve/Save as Pending 

#### What Happened Instead
Never Job Type got deselected after Approve/Save as Pending

#### WordPress / WP Job Manager Version
1.32

#### Browser / OS Version
Crome, Mozilla, Opera

#### Screenshot / Video
https://prnt.sc/mp012t
https://prnt.sc/mp02rr
https://prnt.sc/mp02iw

**Comment by tripflex** [comment]
Related support thread:
https://wordpress.org/support/topic/job-type-does-not-get-saved-displayed-anymore/#post-11242537

**Comment by tripflex** [comment]
i can confirm this is an issue, tested with both WordPress 5.1 and 5.2-alpha-44767

**Comment by tripflex** [comment]
Appears to be related to this update:
https://make.wordpress.org/core/2019/01/23/improved-taxonomy-metabox-sanitization-in-5-1/

Which after processing, results in the taxonomy value being `null` which is the cause of these problems -- looking to see what the solution needs to be

**Comment by jom** [comment]
I'll take a look. As a very short-term workaround, you can enable the setting "Allow multiple types for listings" (and just select one). That enables the default metabox.

**Comment by thedigitalcircle** [comment]
Hi Jom,
Yah!! It's Works well, and I think this is a temporary solution for now.

Shuvashish
