### ISSUE TITLE
Unable to import resume details from LinkedIn

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1688]
Candidate not able to import their field from LinkedIn. We have tested this features few months back and then it working fine.
But now its not redirecting to LinkedIn and Import.
http://prntscr.com/moh9f2
When clicked on LinkedIn it will open only a browser showing "invalid://" blank screen only.
Shuvashish.

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
We're aware of this issue in tracking in the appropriate plugin repo. This repo is just for the core WPJM plugin.
