### ISSUE TITLE
MySQL query low performance

### ISSUE THREAD

**Issue by manu-garrido** [Automattic/WP-Job-Manager#1693]
#### Steps to Reproduce
1. Have a database with 150,000 posts, of which 5,000 are job listings.
2. Go do Job Listing and use the search box.
3. The query written in includes/admin/class-wp-job-manager-cpt.php:search_meta() is not optimised and takes almost 50 seconds.
4. I have rewritten the INNER JOIN in a subquery version that increases performance. It the scenario described here, saves around 45 seconds. See screenshots below.

#### Screenshot / Video

Query snapshot without modifications
![screenshot 2019-03-01 at 15 05 26](https://user-images.githubusercontent.com/21025947/53647725-0e759c00-3c36-11e9-8643-5d2d5aff7844.png)

Query snapshot with modifications
![screenshot 2019-03-01 at 15 01 52](https://user-images.githubusercontent.com/21025947/53647780-2cdb9780-3c36-11e9-8b5e-e5f7baa82f48.png)

#### Code

Complete `search_meta()` function, after improvement:

    /**
      * Searches custom fields as well as content.
      *
      * @param WP_Query $wp
     */
      public function search_meta( $wp ) {
        global $pagenow, $wpdb;

        if ( 'edit.php' !== $pagenow || empty( $wp->query_vars['s'] ) || 'job_listing' !== $wp->query_vars['post_type'] ) {
          return;
        }

        $post_ids = array_unique(
          array_merge(
            $wpdb->get_col(
              $wpdb->prepare( "
                SELECT posts.ID
                FROM {$wpdb->posts} posts
                WHERE (
                  posts.ID IN (
                    SELECT post_id
                    FROM {$wpdb->postmeta}
                    WHERE meta_value LIKE %s
                  )
                  OR posts.post_title LIKE %s
                  OR posts.post_content LIKE %s
                )
                AND posts.post_type = 'job_listing'
              ",
              "%".$wpdb->esc_like( $wp->query_vars['s'] )."%",
              "%".$wpdb->esc_like( $wp->query_vars['s'] )."%",
              "%".$wpdb->esc_like( $wp->query_vars['s'] )."%"
            )
          ),
          array( 0 )
        )
      );

    // Adjust the query vars.
    unset( $wp->query_vars['s'] );
    $wp->query_vars['job_listing_search'] = true;
    $wp->query_vars['post__in']           = $post_ids;
    }

**Comment by manu-garrido** [comment]
Same happens in `plugins/wp-job-manager-applications/wp-job-manager-applications.php`. I cannot find the repo anywhere so I will leave that modified `search_meta()` here:

    /**
      * Searches custom fields as well as content.
      *
      * @param WP_Query $wp
     */
      public function search_meta( $wp ) {
        global $pagenow, $wpdb;

        if ( 'edit.php' !== $pagenow || empty( $wp->query_vars['s'] ) || 'job_listing' !== $wp->query_vars['post_type'] ) {
          return;
        }

        $post_ids = array_unique(
          array_merge(
            $wpdb->get_col(
              $wpdb->prepare( "
                SELECT posts.ID
                FROM {$wpdb->posts} posts
                WHERE (
                  posts.ID IN (
                    SELECT post_id
                    FROM {$wpdb->postmeta}
                    WHERE meta_value LIKE %s
                  )
                  OR posts.post_title LIKE %s
                  OR posts.post_content LIKE %s
                )
                AND posts.post_type = 'job_application'
              ",
              "%".$wpdb->esc_like( $wp->query_vars['s'] )."%",
              "%".$wpdb->esc_like( $wp->query_vars['s'] )."%",
              "%".$wpdb->esc_like( $wp->query_vars['s'] )."%"
            )
          ),
          array( 0 )
        )
      );

    // Adjust the query vars.
    unset( $wp->query_vars['s'] );
    $wp->query_vars['job_listing_search'] = true;
    $wp->query_vars['post__in']           = $post_ids;
    }

**Comment by jenhooks** [comment]
Hey @manu-garrido -- thanks so much for this.

**Comment by richardmtl** [comment]
18824550-zen

user has 500k jobs in the db and it takes 30 seconds to pull up results. I suggested they try the changes here (in staging!).

**Comment by manu-garrido** [comment]
@richardmtl let us know any useful feedback :)
