### ISSUE TITLE
After saving the Edited Resume, when moving to another page,it's showing a pop up  "Leave Site? Changes You made may not Saved" 

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1695]
#### Steps to Reproduce
1. Submit a Resume.
2. Edit anything on the saved resume.
3. HIt Save Button.
4. After that click on "View Resume" or Any other Link.
5. Pop up is triggering "Leave Site? Changes you have made may not Saved."

#### What I Expected

It will smoothly redirect to any page after saving the edited resume without no such Alert message, Because it already shows what ever changes done is saved successfully.

#### What Happened Instead
Its showing a Pop up " Leave Site? Changes that you made may Not Saved" and without clicking on "Leave"  its not redirecting to any page. 
We have tested by disabling all the plug in and activated the Default Twenty Nineteen Theme, but the issues still persists. Screen shots 
http://recordit.co/6HGXMFpy0w

If the problem occurred due to any  theme or  plug in conflict it would not have occurred when I had activated default Twenty Nineteen.

#### WordPress / WP Job Manager Version
1.32.2

#### Browser / OS Version
Crome, Mozilla, Opera

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin. For support and reporting bugs for the add-ons, please visit https://wpjobmanager.com/support.
