### ISSUE TITLE
Single company job listing issue

### ISSUE THREAD

**Issue by osmionogi** [Automattic/WP-Job-Manager#1696]
Hello,

I hope I can explain everything clear enough.

I've got an issue with displaying a list of jobs for a single company. When you go to 'Companies' page (where [job_manager_companies] shortcode is placed) you can see how many listings each of current companies have e.g.:

Company123 (4) ABCompany (10) and so on...

But after I select one of the companies and redirect to single company page, not all jobs counted under a specified company are present. If there is 10 or more job entries, page only loads 9 (latest) for some reason, despite there is more of them to show. Also "load more" button is not present on the bottom of results.

In backend settings i set up "listings per page" to 10. It works for 'Category' page (plus "load more" button is present if category has more than 10 entries) but not for single 'Company' page.

I'm puzzled here. The only differance i can find is in code after "inspect" in browser that /div class=job_listings/ has some parameters on category page and works fine, while company page doesn't:

![category_listing](https://user-images.githubusercontent.com/48238029/53789796-9fde5a00-3f25-11e9-8a0d-9eace3953447.jpg)
![company_listing](https://user-images.githubusercontent.com/48238029/53789801-a40a7780-3f25-11e9-934f-737e070f53b3.jpg)

Is this a setup error by my side or plugin for some reason generates results differently for both shortcodes?

Regards, Piotr

**Comment by jom** [comment]
That shortcode is not provided by WP Job Manager. You might be using https://wordpress.org/plugins/wp-job-manager-companies
