### ISSUE TITLE
Counter Having the Number of User Vied Jobs and Number of Applicant Applied a Job

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1698]
#### Steps to Reproduce
1.
2.
3.

#### Context / Source

Hi
Is it possible to show a counter on Single Job Listing Page for showing no of users have already applied for that job & how may users have views that job?  
Shuvashish

**Comment by jom** [comment]
Hi there! For support, please visit https://wpjobmanager.com/support.
