### ISSUE TITLE
Custom validation for job description

### ISSUE THREAD

**Issue by iparker** [Automattic/WP-Job-Manager#1699]
Hello,

it would be gread to have the possibility to add a custom validation rule for the job description.

In my case I need a custom validation for the input, for example to check the text-length or to check that there is no email address inside the text.

I looked at documentation and snippets and did not find anything about this.

For me it would be fine if this validation is done server side.

Best regards,

Timo

**Comment by tripflex** [comment]
This can be done already using `submit_job_form_validate_fields` filter, which passes 3 arguments, `true, $fields, $values` ... if you return a new `WP_Error` it will fail validation and show the error message.

**Comment by iparker** [comment]
Hello,

great - thanks for your reply.

I just added a simple filter for do this:

```
add_filter('submit_job_form_validate_fields', 'ipm_custom_job_validation', 100, 3);
function ipm_custom_job_validation( $isValid, $fields, $values ) {

    foreach ( $fields['job'] as $key => $field ) {
        // Example regex validation
        if ( $key == 'job_description' && isset( $values['job']['job_description'] ) && strlen( $values['job']['job_description'] ) < 500 ) {
            return new \WP_Error( 'validation-error', 'Die Job-Beschreibung muss mindestens 500 Zeichen lang sein.' );
        }

        if ( $key == 'job_description' && isset( $values['job']['job_description'] ) && preg_match('/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/si', $values['job']['job_description']) ) {
            return new \WP_Error( 'validation-error', 'Die Job-Beschreibung darf keine E-Mail Adresse beinhalten.' );
        }
    }
    return $isValid;
}
```

But I have a problem with this: When my validation raises the WP_Error the content in the job description is not the last submitted value but the value before.

Hope you can understand what I mean.

Best regards,

Timo
