### ISSUE TITLE
Featured Jobs widget: Company logo is not displayed

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1700]
Originally reported in 1862198-zen ; I was able to reproduce on a site with Twenty Seventeen.

The Featured Jobs widget does not display the company logo:

![Screen Shot 2019-03-12 at 16 18 53](https://user-images.githubusercontent.com/3676359/54233095-97b48a80-44e2-11e9-9b25-2df5062e37ee.png)

Even though it should, as far as I can tell:

https://github.com/Automattic/WP-Job-Manager/blob/master/includes/widgets/class-wp-job-manager-widget-featured-jobs.php#L113
https://github.com/Automattic/WP-Job-Manager/blob/master/templates/content-job_listing.php#L23

So I don't know what's blocking it from showing. Note: it's not just hidden because of CSS; the HTML output isn't there for it either.

**Comment by cena** [comment]
1939317-zen

Anecdata: lthough the user is able to view logos in the regular 'Recent Jobs' widget, I'm not able to, on stock WPJM (no addons), using Storefront or TwentySeventeen.

<img width="430" alt="JobsWidgetNoLogoStorefront" src="https://user-images.githubusercontent.com/19334/55631709-4b293b80-577e-11e9-9a36-773b5ea89fc3.png">

@jom can you take a look?

**Comment by jom** [comment]
This is an enhancement request. Actual template is here:
https://github.com/Automattic/WP-Job-Manager/blob/6a1e5f044e32dae3602bedab5b06ada386441919/templates/content-widget-job_listing.php#L22

The featured job widget doesn't have the `Show Logo` setting. They both share that template, but the variable/setting is only there on Recent Jobs right now. It is an easy thing to add, though. I'll whip up a quick PR.
