### ISSUE TITLE
Job preview gives error The link you followed has expired

### ISSUE THREAD

**Issue by AndyS7A** [Automattic/WP-Job-Manager#1703]
I'm using WP Job Manger and recently I've been unable to get past Preview step when trying to post a new job. I keep getting "The link you followed has expired".

I've checked https://github.com/Automattic/WP-Job-Manager/issues/1694
But unfortunately it did not help. I also tried a solution to skip preview based on this guide https://wpjobmanager.com/document/remove-the-preview-step/, but reached the same issue.

I'm using WorkScout theme and the job-preview.php file looks as it should. I'm out of ideas.

**Comment by jom** [comment]
Hi there! Until you have reproducible steps, for support, please try https://wpjobmanager.com/support or https://wordpress.org/support/plugin/wp-job-manager. 

With that support request, please copy in the contents of your `job-preview.php` template. If you're using a child theme, check there first for the overridden `job-preview.php` template and then your parent theme.
