### ISSUE TITLE
Post a listing(403 Forbidden error)

### ISSUE THREAD

**Issue by gasinikesh** [Automattic/WP-Job-Manager#1704]
I’m using wordpress.com as a host and listable theme which include WP Job Manager plugin. It allows me to post listing from back end “Dashboard”. But from front end form it gives 403 forbidden error.

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support. Looks like you have an [issue open on the forum](https://wordpress.org/support/topic/403-forbidden-error-67/). If this happens on the preview step, check this thread for a solution: https://wordpress.org/support/topic/the-link-you-followed-has-expired-19/
