### ISSUE TITLE
Filter by Featured in Jobs shortcode not working properly

### ISSUE THREAD

**Issue by yousufansa** [Automattic/WP-Job-Manager#1705]
The Featured filter on shortcode not working correctly. I put the shortcode as [jobs featured="true" per_page="10" show_filters="false"]. but i got the output with not featured jobs and also orderby featured also not working in shortcode. I had tested against the themes "Twenty Nineteen" and "Store Front" ( Latest version ).  I attached screenshot ( Theme: "Twenty Nineteen" ) for reference.

Shortcode:
![image](https://user-images.githubusercontent.com/19503695/54977923-c5123580-4fc4-11e9-9a3a-043d3fde8cb2.png)

Output:
![image](https://user-images.githubusercontent.com/19503695/54977843-867c7b00-4fc4-11e9-8f7a-8e46b01254ba.png)

**Comment by richardmtl** [comment]
Hi! I'm not able to reproduce this. Please contact us [here](https://wpjobmanager.com/support/) if you have purchased one of our addons, or post to the [WordPress.org support forums](https://wordpress.org/support/plugin/wp-job-manager/ ) if you have not.
