### ISSUE TITLE
Past Application Delete Button

### ISSUE THREAD

**Issue by raps1984** [Automattic/WP-Job-Manager#1714]
Hey There!

I bought the core add-on bundle last month wp-job-manager. I have an issue with the past application. Need to add a functionality for candidates to able to delete past application with a delete button..

Plugin Name: WP Job Manager - Applications

file name = 
![ShowGit](https://user-images.githubusercontent.com/22958578/55961012-437e0100-5c6e-11e9-93b3-bfa363e1a270.jpg)
past-applications.php

Thanks!

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin. For support and requests with the paid add-ons, please visit https://wpjobmanager.com/support.

**Comment by raps1984** [comment]
thank you !
