### ISSUE TITLE
REST API: Access all fields

### ISSUE THREAD

**Issue by tuzmusic** [Automattic/WP-Job-Manager#1715]
I'm writing a mobile app based on a website using WPJM. I need to display all the information for a listing, but currently, only these fields are coming in from an API request to `http://example.com/wp-json/wp/v2/job-listings/850`:

```
fields: {
    _job_location: "1600 Pennsylvania Ave NW, Washington, DC",
    _application: "",
    _company_name: "",
    _company_website: "http://www.whatever.com",
    _company_tagline: "Awesome tagline",
    _company_twitter: "twitter.com/123456",
    _company_video: "",
    _filled: false
  },
```

I need other fields, including prices, the phone number and the email of a listing, and anything that displays on the listing's show page.

![Screen Shot 2019-04-11 at 8 12 18 AM](https://user-images.githubusercontent.com/22814728/56145740-d8d10c00-5f72-11e9-9e70-4d5e9fea2e00.png)

**Comment by jom** [comment]
Closing in favor for duplicate #1697.
