### ISSUE TITLE
Youtube video embeds not working

### ISSUE THREAD

**Issue by alexsanford** [Automattic/WP-Job-Manager#1718]
#### Steps to Reproduce
- Add a Youtube video to a job description from WP Admin.
- Video preview shows in the Editor.
- Save or Preview the post.
- Video embed is missing when viewing the Job Details page on the Frontend.
- Video embed is working with JobifyVersion: 3.8.6 & ListifyVersion: 2.5.0.
- Video embed not working with `Twenty Seventeen`, `Twenty Nineteen`.
- Video embed not working with `Avada 5.7.2` (reported by a user in support).

**Comment by richardmtl** [comment]
Another report in 1958011-zen

**Comment by jom** [comment]
Quasi-duplicate: https://github.com/Automattic/WP-Job-Manager/issues/1584

**Comment by JohnGiddi** [comment]
Hello! Is there now a solution? In my case youtube shows up only 23pixels high.
