### ISSUE TITLE
Browse "back" button breaks the submission form, if new account creation involves

### ISSUE THREAD

**Issue by imfaisalkh** [Automattic/WP-Job-Manager#1720]
When a new un-registered user submits a new job (and the process includes account creation). Now if the browser "back" button is used on the "Preview Job" page it displays "Document Expired" error instead of showing the actual submission form.

This issue does not happen, when the submission process does not involves an account creation, or, the user clicks the "Edit Listing" button instead of clicking the browser "back" button.

![image](https://user-images.githubusercontent.com/10553273/56457758-b9821680-6398-11e9-96a3-38a7e305b544.png)

**Comment by richardmtl** [comment]
Hi,

This is the browser protecting against re-submitting a form, and as such, isn't something we can change.
