### ISSUE TITLE
Jobs dashboard: allow pagination and/or include shortcode parameter to change the number of jobs displayed

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1724]
Requested here: https://wordpress.org/support/topic/job-dashboard-pagination/

**Comment by linoman-zz** [comment]
hello dear Richard - this is a superb ideea. 'I really love this idea. Well - we would have made a big big step forward in the job-dashboard. 

Let us work on this thing!!! 

I really love the sustainable development!!! it is great!! 
Let us keep up the great project - it rocks.

**Comment by Braehler** [comment]
Is this working in the current version? cause there is a pagination.php. but I have no output

**Comment by richardmtl** [comment]
@Braehler There actually *is* pagination in the dashboard, I was mistaken. See here:

https://wordpress.org/support/topic/job-dashboard-pagination/#post-11580390

If yours isn't working, please start a new thread in the support forum. Thanks!

**Comment by Braehler** [comment]
@richardmtl Thanks, works out
