### ISSUE TITLE
Set Password at Job Submission Request

### ISSUE THREAD

**Issue by shemakeswebthings** [Automattic/WP-Job-Manager#1725]
#### Steps to Reproduce
1. At job submission force email address to be set as username
2. At job submission allow users to set their own password

#### What I Expected
Currently, the options only allow you to generate the username from an email address but does not allow users to set their own password. I would like to force users email addresses to be used as their username, but also allow the option to set their own password.

#### What Happened Instead
When I check the option to generate the username from an email address, the set password field is also checked, but greyed out – so i can’t uncheck it forcing users with the need to reset their password in order to actually set it instead of being able to set it upon job submission/account creation.

#### WordPress / WP Job Manager Version
Most recent - core and plugins are updated.

<!-- Optional: share your unique context to help us understand your perspective.

If requesting a new feature, explain why you'd like to see it added.
Emails are much easier to remember as usernames so I want to keep that function in place, but I also want to allow users to set their password upon submission of a job. I’ve also read that this isn’t possible using your resumes add-on, once I get all the kinks in the core plugin I do plan on looking into the add-ons for additional features. (https://github.com/Automattic/WP-Job-Manager/pull/1063)

Is this something that will be fixed for better user experience in the near future? Also, sending users to the backend form to set their password is a bit disjointed.

**Comment by thedigitalcircle** [comment]
Hi
This is a Good Call.
Shuvashish

**Comment by shemakeswebthings** [comment]
Hello, what happens after an issue is submitted? Does it need to be "Accepted" to be worked upon?

**Comment by thedigitalcircle** [comment]
I think this issue has already been closed on 1.33.0 version. Now user able to set password on the time of job submission.

Shuvashish

**Comment by shemakeswebthings** [comment]
Thank you for your reply.

The problem was that we are unable to force the email as the username if we
allow users to choose their own password. Do you know about that?

**Comment by jom** [comment]
Setting as an enhancement request to remove restriction of `Generate usernames from email addresses` to be enabled and `Email new users a link to set a password` to be disabled.

**Comment by shemakeswebthings** [comment]
Thank you for accepting this request!
