### ISSUE TITLE
Save as Pending not working and Published the Job or Resume

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1735]
#### Steps to Reproduce
1. Job / Resume Submitted from Front End and Waiting For Admin Approval
2. On Back End it shows Pending Approval
3. If Admin click "Save As Pending" that as http://prntscr.com/nlgjjt
4. It directly Published. http://prntscr.com/nlgkp4

#### What I Expected
If Admin want to modify and Click on "Save as Pending", it will not directly published and as of now it is working with this flow.

#### What Happened Instead
It will Directly Published instead of Save as Pending.

#### WordPress / WP Job Manager Version
5.1.1

#### Browser / OS Version

Crome 73
#### Screenshot / Video
http://prntscr.com/nlgjjt
http://prntscr.com/nlgkp4

**Comment by jom** [comment]
I am not able to reproduce. Please try reproducing on install without any plugins (except Classic Editor, as it looks like this is an issue specifically with the classic editor) and Twenty Nineteen theme. 

For me, `Save as Pending` never shows if the custom post status has been set to anything other than a pending status. In your screenshot, the post status shows as Published before clicking the button. 

Feel free to comment on this issue with additional steps to reproduce (settings changes, etc) and I can re-open.
