### ISSUE TITLE
Company Sign In 

### ISSUE THREAD

**Issue by wr0917** [Automattic/WP-Job-Manager#1744]
The Company sign-in for job posting is not working.  When a new company signs-up to post a job on our site, they're not receiving their account details which allows them to sign-in with a password.  How can I get this fixed?

Thanks! 

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
