### ISSUE TITLE
change default upload folder

### ISSUE THREAD

**Issue by zagrox** [Automattic/WP-Job-Manager#1747]
for more security its necessary to hide the original and predictable default folders names,
I tried to change the default path for upload media from job manager!
any advise for custom related codes in function to change the default folder name?

there's a code which will only change the folder location and not rename it, means still the "job-manager-uploads folder name is still on each url of images inside the media.
`add_filter( 'job_manager_upload_dir', 'my_custom_job_manager_upload_dir' );

function my_custom_job_manager_upload_dir( $job_manager_uploading_file ) {

	// This is the default below
	// $dir = 'job-manager-uploads/' . $job_manager_uploading_file;
	
	// This is using a custom directory, make sure to add $job_manager_uploading_file to the end of the string
	$dir = 'custom_jm_uploads/' . $job_manager_uploading_file;
	
	return $dir;
}`

It would be great for protection to hide and change it with new name.

**Comment by richardmtl** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
