### ISSUE TITLE
The "RSS", "Reset" and "Add Alert" links when no search result

### ISSUE THREAD

**Issue by imfaisalkh** [Automattic/WP-Job-Manager#1749]
The "Reset" and "Add Alert" button appears when the search query has some results (see top right corner).

![image](https://user-images.githubusercontent.com/10553273/57946353-89755700-78f5-11e9-8776-d0e74fe3ab58.png)

But it does not appear when it has no result.

![image](https://user-images.githubusercontent.com/10553273/57946397-a27e0800-78f5-11e9-9cad-e6cea73dcc82.png)

Ideally, for consistent and better user experience these buttons should appear in both cases.

**Comment by richardmtl** [comment]
This came up again in 2559216-zen
