### ISSUE TITLE
improve job alert

### ISSUE THREAD

**Issue by fablin** [Automattic/WP-Job-Manager#1754]
Hi
I would like to suggest a new feature for the job alert add-on:
- when a user choose to receive a weekly alert, he can precise which day and what time
- when a user choose to receive a daily alert, he can precise what time

Thanks
Fabrice

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin only. For support or to make an enhancement request for an official extension, please visit https://wpjobmanager.com/support.
