### ISSUE TITLE
WP Job Manager - jobs not displayed

### ISSUE THREAD

**Issue by InternetBPhD** [Automattic/WP-Job-Manager#1756]
Hello,

I use the plugin WP Job Manager on the website www.bphd.de. The problem is that the plugin is displayed but the job ads are not loaded. The widget in the sidebar works though.

I've tried to install older versions so far and have uninstalled other plugins that allegedly also resulted in erros (were displayed in the console on the website)

I hope someone can help me  here.

![2019-05-25](https://user-images.githubusercontent.com/41341688/58366758-617a8a80-7ed7-11e9-877d-8ecb2212d38a.png)

**Comment by richardmtl** [comment]
Hi!

This repo is for bug reports, not for support requests. Please contact us here if you have an add-on subscription:

https://wpjobmanager.com/support/

Otherwise, please start a new thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!
