### ISSUE TITLE
Maintenance: Add `wp_unslash` to request input

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1767]
Building off of #1760 

Remove the following from `phpcs.xml.dist` and then fix the new issues when running `phpcs -s phpcs.xml.dist .`.
```xml
	<rule ref="WordPress.Security.ValidatedSanitizedInput.MissingUnslash">
		<severity>4</severity>
	</rule>
```

**Comment by GaryJones** [comment]
@jom and I discussed this, so here's my summary:

---

Jake proposed that `MissingUnslash` has too many false positives, especially for non-storage cases, and for when the data isn't expected to contain any characters that might need slashing, such as in nonces, actions, non-text filters.

His example was a violation being given on `'delete' === $_GET['action']`, i.e. a simple comparison.

I’m running `phpcs phpcs-test.php --sniffs=WordPress.Security.ValidatedSanitizedInput --standard=WordPress -s` against

```
<?php

wp_verify_nonce( 'my_nonce', 'my_action' );

if ( isset( $_GET['action'] ) && 'delete' === $_GET['action'] ) {
	echo 'foo';
}

```

and I’m not getting any warning about missing an unslash. If I change it to:

```
<?php

wp_verify_nonce( 'my_nonce', 'my_action' );

if ( isset( $_GET['action'] ) && 'delete' === sanitize_text_field( $_GET['action'] ) ) {
	echo 'foo';
}
```

i.e. add `sanitize_text_field()` which indicates I want to do more than a comparison with it, _then_ I do indeed get a warning:

```
5 | ERROR | Missing wp_unslash() before sanitization.
   |       | (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
```

So - a simple comparison against a superglobal doesn’t warn about missing unslash. Wrapping the superglobal in a sanitizing function, then does warn about missing unslashing.

----

Regarding the non-storage, WP adds slashes to all superglobals values: https://github.com/WordPress/WordPress/blob/27720e15a79548313a5f647f373494d13263379c/wp-includes/load.php#L915-L940 so anytime you read from them, you should unslash, regardless of whether you use or store the resulting value.

----

For cases where you’re not expecting an apostrophe, then the call would technically be redundant, but equally, it doesn’t hurt to have it, if it forms a good practice. It's the same with escaping - it's better to add it and not technically need it in case some previous code changes, than not have it and then be caught out later.

----

For these reasons, I think this ticket should be re-opened and the root causes addressed as needed. There may still be individual instances that are false positives (in which case, please [report them upstream at WPCS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/new?template=bug_report.md)) that need excluding, but that would be a better situation than blanket excluding all current and future instances where superglobal data does need to be unslashed.

**Comment by jom** [comment]
I'll remove the exclusion in #1769 instead of reopening this one. Most/all will be fixed together.
