### ISSUE TITLE
Job Tag, Category and Company All are not showing the Complete list of Jobs after full Tag & Category page load 

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1778]
#### Steps to Reproduce
1. Twenty Nineteen Theme
2. WPJM 1.33.0
3. WPJM -Job Tags
After Updating WPJM 1.33.0, When I will go to a Specific Job Tag or Category or Company Page, 

#### What I Expected

This will need to show all the Jobs relevant to that Job Tag or Job Category or Company.
#### What Happened Instead
This will only show the latest one job after page loading complete. One the loading time page will trying to show the reverent all available jobs, but remain with only one after page loading complete. This also true for Category and Company.

#### WordPress / WP Job Manager Version

Latest
#### Browser / OS Version

Crome, Mozilla
#### Screenshot / Video
https://careerfynder-gmail.tinytake.com/tt/MzU2OTk1NF8xMDc2Nzg1Nw

**Comment by jom** [comment]
WPJM or WPJM Job Tags does not support the `[jobs]` generated archive pages. That looks like it is your theme (which isn't Twenty Nineteen). Job Tags just supports standard archive pages (which do seem to work properly  on Twenty Nineteen). Might be worth asking your theme developer.
