### ISSUE TITLE
Resume Manager Malfunctioning After WPJM 1.33.0 Update

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1780]
#### Steps to Reproduce
1. WPJM 1.33.0
2. Resume Manager 1.17.2
3. Smyles WPJM Field Editor

I have created some extra Fields, Like Preferred Job Location, CTC, D.O.B etc.
User have able to fill and submit resume, no issues there

#### What I Expected
No need to manual intervene on the any fields from the back end, all fields are saved as user filled from front end. 
#### What Happened Instead

When admin access the resume from the Back end and open the resume Pending for Approval all filled fields are gone vanish, even if  Admin wants to fill those fields once again, then also those fields haven't got saved from the Back end. Every time Admin hit Save as Pending/Publish, all fields have cleared from the back end.

#### WordPress / WP Job Manager Version
All Updated.

#### Browser / OS Version
Crome, Mozilla

#### Screenshot / Video
https://prnt.sc/ny96kb
https://prnt.sc/ny96uz
https://careerfynder-gmail.tinytake.com/tt/MzU3MDQzNF8xMDc2OTM0NQ

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin only. For support, please visit https://wpjobmanager.com/support. It might also be worth reaching out to the author of Field Editor (cc: @tripflex). When you submit your support request, please include the type of fields you're adding.

**Comment by jom** [comment]
No need to send in support request. This will be fixed in an imminent update to resume manager.
