### ISSUE TITLE
Add link to Jobs Dashboard after submitting job

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1782]
If you have the following settings active:

* "Require an account to submit listings"
* "Enable account creation during submission"
* "Require admin approval of all new listing submissions"

and someone submits a job, all you get is a message saying ""Job submitted successfully. Your listing will be visible once approved." 

How about adding a link to the Jobs Dashboard as well?

Requested in 2087930-zen

Related: https://github.com/Automattic/WP-Job-Manager/issues/1179

**Comment by jom** [comment]
Seems sensible. I'll add it to 1.34.0.

**Comment by JuanchoPestana** [comment]
Hey @richardmtl @jom ,
I submitted a PR for this enhancement.
Here's a screenshot of how it looks. 
Please let me know your thoughts and if there's anything else I could do to help regarding this issue!
![issue1782](https://user-images.githubusercontent.com/17458017/62511289-885b1400-b7d8-11e9-88f7-fa96bde25942.png)

**Comment by technerdlove** [comment]
### Hi, @richardmtl and @jom - 

- I also submitted a PR for this issue, but with a different approach. 

- Happy that this enhancement is getting a lot of love. :wink:

- **Please don't hesitate to contact me with questions.**

### **Screenshots:**

_With page title_

![job-submitted-title](https://user-images.githubusercontent.com/15333603/62732231-b444e800-b9d8-11e9-8052-a6fd5a0bdcbe.png)

 _Without page title_

![job-submitted-no-title](https://user-images.githubusercontent.com/15333603/62732245-bdce5000-b9d8-11e9-8025-15a48a7aa130.png)

**Comment by onubrooks** [comment]
Adding this to 1.36.0, PRs open [here](https://github.com/Automattic/WP-Job-Manager/pull/1845) and [here](https://github.com/Automattic/WP-Job-Manager/pull/1854)
