### ISSUE TITLE
Related to #1772/1773

### ISSUE THREAD

**Issue by ESADoggy** [Automattic/WP-Job-Manager#1789]
Good morning.

I too experienced the error being thrown... I've installed the snippet...

Now, an error is not thrown, however:

1. the first job listing is created
2. the import hangs

  - Attempted to create parent Job job_listing_type `Contract, PRN`, duplicate detected. Importing Job to existing `Contract, PRN` job_listing_type, ID 2940, slug `contract-prn` ...

I've been successfully running imports for the last year using the same process.

Hope this helps.

Chaz
 

#### Steps to Reproduce
1.
2.
3.

**Comment by jom** [comment]
Hi there! Is this with WP All Import? If so, please try again with [1.33.1 Beta 1](https://github.com/Automattic/WP-Job-Manager/releases/tag/1.33.1-beta.1) (on a staging site). I'm closing for now, but if you have specific steps reproducing a specific error from a vanilla install, please update your issue with a more descriptive title.
