### ISSUE TITLE
Issue when "applying for job" where new account creation involves

### ISSUE THREAD

**Issue by imfaisalkh** [Automattic/WP-Job-Manager#1790]
There seems a bug with job application flow when resume add-on is enabled and new-account creation is involved.

1. Click on Apply as logged out user.
2. Complete profile / submit resume, click “Preview Listing".
3. Go to Preview listing page and click “Submit Resume”.
4. Submit your application page -> clicking “Send Application”.

Now here after clicking "Send Application" button, it takes user back to "Submit Resume" page saying again "Submit your resume below to apply for the job...".

On another server, instead of taking back to "Submit Resume" page it simply throws "Link Expired" error message.

**Comment by richardmtl** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin only. For support or to report issues with the other official extensions (such as Resume Manager), please visit https://wpjobmanager.com/support.
