### ISSUE TITLE
Search Bar Broken after 1.33.0 Update

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1792]
After Update Search Bar on Find a Job Page has broken. I am using Jobify Theme.
#### Steps to Reproduce
1.
2.
3.

#### Screenshot / Video

http://prntscr.com/nzxwii

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for core WP Job Manager. I'm unable to reproduce Twenty Nineteen. Might be worth reaching out to Astoundify if you're still experiencing issues with 1.33.1.
