### ISSUE TITLE
Google Recaptcha Still Can Bypass When Save as Draft

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1800]
#### Steps to Reproduce
1. Fill All The details on Post-A-Job page
2. Bypass Google Recaptcha
3. Form will save as Draft

#### What I Expected
Showing error when someone bypasses the Google Recaptcha

#### What Happened Instead
Will save as Draft

#### WordPress / WP Job Manager Version
WPJM 1.33.2 and Latest WP

#### Browser / OS Version
Crome, Safari, Mozilla

#### Screenshot / Video

https://careerfynder-gmail.tinytake.com/tt/MzU5Mzc0OF8xMDg1OTMwMw

**Comment by jom** [comment]
Are you using the Field Editor plugin or a theme that provides their own recaptcha support? I'm unable to produce on base install.

**Comment by thedigitalcircle** [comment]
Hi @jom 
Yes I am using WP Field Editor.
Shuvashish

**Comment by jom** [comment]
Do you have reCAPTCHA enabled through Job Manager (WP Admin > Job Manager > Settings > reCAPTCHA) or Field Editor (WP Admin > Job Manager > Field Editor Settings > reCAPTCHA)?

Closing this for now, but I've pinged @tripflex.

**Comment by thedigitalcircle** [comment]
Hi @jom 

Through Field Editor (WP Admin > Job Manager > Field Editor Settings > reCAPTCHA)
Shuvashish

**Comment by tripflex** [comment]
@thedigitalcircle thanks for reporting this, I will work on getting an update out shortly to resolve this issue @jom thanks for the heads up

**Comment by thedigitalcircle** [comment]
Hi @tripflex 
Thanks for taking up the issues.
Shuvashish
