### ISSUE TITLE
job-submission.js throws js error expects job_description to be WP Editor

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1808]
https://github.com/Automattic/WP-Job-Manager/blob/7b9df224e2bfc6107e8a0f3069eaaec4ef94a01b/assets/js/job-submission.js#L154-L165

If a user modifies (via plugin or PHP) the job description field to change it to say, a textarea, this will result in JS error on the page, as TinyMCE might not even be set.

Probably should add a conditional if statement around it to check if tinymce even exists on window object before assuming it does

**Comment by tripflex** [comment]
Disregard this .. not sure how I didn't see the check right above it ..durp!

**Comment by jom** [comment]
Actually, I’m wondering if this should be `&&` instead of `||`.
https://github.com/Automattic/WP-Job-Manager/blob/7b9df224e2bfc6107e8a0f3069eaaec4ef94a01b/assets/js/job-submission.js#L142

The check in the `setTimeout()` looks good, though.

**Comment by tripflex** [comment]
@jom yeah i agree it should be `&&` because tinymce should exist AND job_description not equal to null

**Comment by tripflex** [comment]
So i'm going to re-open this issue, as this is still a problem, but it's due to checking against `undefined` without quotes, when it should be in quotes

**Comment by tripflex** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined#Typeof_operator_and_undefined

Example:
https://glot.io/snippets/fdt65d486p

`undefined` will only be true when the var has been set, but not defined, ie:

```javascript
var x;
```

But in the case where `job_description` is not using WP Editor (or any other field on the page), `tinymce` is never actually loaded on the page, so it must be checked against `"undefined"`
