### ISSUE TITLE
Deleting job resets job package

### ISSUE THREAD

**Issue by pguilha** [Automattic/WP-Job-Manager#1817]
#### Steps to Reproduce
1.Purchase job package (with WC Paid Listings add on)
2.Create a job on the front-end as a user/employer
3.Delete job from job dashboard

#### What I Expected
job is deleted and job package is no longer available (ie has been used up)

#### What Happened Instead
job was deleted BUT the job package was reset as if the user had not in fact used up a job from the package.

#### WordPress / WP Job Manager Version
wp job manager Version 1.33.2
wc paid listings: Version 2.8.3

**Comment by richardmtl** [comment]
Hi!

Since this is for one of our paid add-ons, please contact us here instead:

https://wpjobmanager.com/support/

This repo is for the free core WPJM plugin only.

**Comment by Hastibe** [comment]
I also encountered this issue, and received this response via support, which I think would be helpful to provide here, as it may help other people and reduce future support queries about this:

> The WC Paid listings plugin has a grace period of 2 days i.e. if the user purchased a Job Package and Published a job here is what happens.
> 
> If the user deletes the Job within 2 days of publishing the purchase package count is restored as 0 and they can post another Job Listing using this package.
> 
> f the user deletes the Job after 2 days of publishing the purchase package count is not restored and the user is not able to publish any new listings using this package.

I strongly urge this information about the 2 day grace period that WC Paid Listings has to be added to the documentation of the plugin--knowing about this feature would have prevented a lot of confusion and concern on our side.
