### ISSUE TITLE
No User Name sanitize 

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1818]
#### Steps to Reproduce
1. Go to Job or resume submission form
2. Enter user name with space
3. User will creating with the spaces like "ABC XYZ"

#### What I Expected
At least have an error message to user enter a proper user name 

#### What Happened Instead
User will created ABC XYZ

#### WordPress / WP Job Manager Version
All Latest

#### Browser / OS Version
All browser

#### Screenshot / Video
http://prntscr.com/oc0sa9

**Comment by richardmtl** [comment]
WordPress allows spaces in usernames (unless it's a multisite). If you don't want to allow spaces, see here for a sample code snippet that you can use:

https://trickspanda.com/prevent-spaces-wordpress-usernames/

**Comment by thedigitalcircle** [comment]
Hi 
I am already using the code you are given. But it's not working on Job & Resume submission page except woocommerce registration page.
Shuvashish

**Comment by thedigitalcircle** [comment]
Hi @richardmtl 
Please help on this issues. This code is not working only on Job & Resume submission pages.
Shuvashish
