### ISSUE TITLE
Making WPJM PWA compatible

### ISSUE THREAD

**Issue by thedigitalcircle** [Automattic/WP-Job-Manager#1824]
Is there any plan to make WPJM as Progressive web app(PWA) compatible?
This is a great features to have a website to look like a app. This is also make website faster and lot of other benefits. So is there any plan?

**Comment by tripflex** [comment]
@thedigitalcircle have you tried using it as a PWA at all?  If so, what issues are you having?  There's numerous plugins out there to turn a standard WordPress site into a PWA

**Comment by thedigitalcircle** [comment]
Hi @tripflex
Thanks for commenting. Can you suggest one which is best fit for our site.
Shuvashish

**Comment by thedigitalcircle** [comment]
HI @tripflex 
Can you suggest us any PWA plugin which will be the best fit with WPJM.

Shuvashish

**Comment by richardmtl** [comment]
@thedigitalcircle There are several listed here: https://wordpress.org/plugins/tags/pwa/

There are also several paid options out there, too. I suggest you experiment with these yourself, to see what works best for your site.
