### ISSUE TITLE
Can't see other sub menus than Settings and Add-ons under Job Listings menu

### ISSUE THREAD

**Issue by 83bba01** [Automattic/WP-Job-Manager#1826]
Made a clean install of wordpress two times using the jobify theme once and the twenty nineteen theme once. Didn't work out even though I only installed the Wp Job Manager plugin and disabled the rest of the (few) plugins. 

#### What I Expected
To see sub menus under Job Listings.

#### What Happened Instead
I only see the Settings and Add-ons sub menus.

#### WordPress / WP Job Manager Version
Wordpress 5.2.2.  / WP Jobmanager 1.33.3

Another user has the same issue:
https://wordpress.org/support/topic/something-critically-wrong-with-the-latest-update/

With best regards,

bb

**Comment by danjjohnson** [comment]
Thank you! We're currently working on a fix for this issue. Will comment here with updates.

**Comment by cena** [comment]
reported in 2201186-zen

**Comment by pgk** [comment]
link to the beta release in case someone want to help with testing this https://github.com/Automattic/WP-Job-Manager/releases/tag/1.33.4-beta-2

**Comment by Meyxel** [comment]
i have the same issue, but the beta release doesn´t help.

i have to deaktive all the plugins and change the theme but nothing works.

anyone can help m here?

![Listing data](https://user-images.githubusercontent.com/53534585/62231087-987f8780-b3c3-11e9-9ebf-675b4c6cffcf.PNG)

**Comment by richardmtl** [comment]
@Meyxel Your screenshot is a different issue, and in fact, that doesn't appear to be WP Job Manager at all. If you have a license with us for one of our add-ons, please contact us here:

https://wpjobmanager.com/support/

Otherwise, please start a new thread here:

https://wordpress.org/support/plugin/wp-job-manager/

Thanks!

**Comment by 83bba01** [comment]
I do have a license. Can I just refer to our conversation?

Med vänliga hälsningar,

Babak Badri 

Skicka från min iPhone

**Comment by 83bba01** [comment]
Sorry. Wrong e-mail. Just ignore my message. I’m drunk!

Med vänliga hälsningar,

Babak Badri 

Skicka från min iPhone
