### ISSUE TITLE
Apply options

### ISSUE THREAD

**Issue by TheJobWork** [Automattic/WP-Job-Manager#1833]
I am on the demo right now and i am seeing only optiosn to Apply are the " email " and a link ... no direct apply nor  with resume upload or resume saved or not even not appply with profile, 

I am sure guys you can do better than that.

**Comment by Hastibe** [comment]
Check the documentation for their Resume add-on; that adds those features. Also check this demo of a custom theme using WP Job Manager and its add-ons for a demonstration site that displays its features much more effectively, in my opinion: [https://demo.wpscouts.net/capstone/](https://demo.wpscouts.net/capstone/)

**Comment by TheJobWork** [comment]
ok so the demo is outdated then...thanks for the info.

Where did he get the company profile from on the link you shared ?

**Comment by Hastibe** [comment]
I believe the theme modifies the WP Job Manager templates to do this. If you look at the [job post](https://demo.wpscouts.net/capstone/post-a-job/) submission page, and scroll down to the "Company Information" section, the theme modifies that part to include selecting an existing company or creating a new company, which includes a description field as meta data, which (is then subsequently auto-filled) and updates the description on the company profile page each time a job for the company is submitted, if there are any changes to the description.

...At least, I think that's how it works?

For a better explanation, check out the [theme documentation](https://wpscouts.gitbook.io/capstone/4-setting-up-company-profile-page-s) about company profile pages, too.

Hope this is helpful!

**Comment by TheJobWork** [comment]
the thing is that i already have the theme i want, i am more looking for a better version of WP manager that entails company listing, reviews, endorsement to form some kind of linkedin website ...WP job manager is so basic.

But thanks anyway.

**Comment by TheJobWork** [comment]
By the way i realized that Buddy press + buddy press job manager + WP job manager can also do the trick ...have you checked ?
