### ISSUE TITLE
job-submission.min.js throws js error expects job_description to be WP Editor

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1856]
Resolved in #1808 -- but it seems that never made it's way into the minified version.

When i submitted the PR should I have included the updated `.min.js` version as well, or should minification be ran before release (for all files)?

I can submit a PR for the updated `job-submission.min.js` but want to make sure we get the process of handling minified files moving forward to some kind of standard so we don't come  across this issue again 👍

**Comment by roundhill** [comment]
I think we should minify it as part of the PR. Any thoughts @pgk or @jom?

I created a PR for the minified file: #1859

**Comment by tripflex** [comment]
Closing this as resolved in #1859
