### ISSUE TITLE
Allow short circuit application field forced validation

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#1872]
Based on this support thread:
https://wordpress.org/support/topic/way-to-change-field-hidden-by-apply-for-job-button/

Basically the `application` field is hard coded for validation of either URL or Email ... which is fine as that should be the standard, but in the instance that a user wants to allow something other than just URL or Email, would be good to have a filter added around here:
https://github.com/Automattic/WP-Job-Manager/blob/6c35acabbbc7eacb03bf72ea21461f293f0a0ec0/includes/forms/class-wp-job-manager-form-submit-job.php#L437-L446

To allow short circuiting the required validation as email or URL (without having to hack apart validation through core WordPress `is_email` field)

Maybe changing `if ( ! is_email( $values['job']['application'] ) ) {` to something like:

```php
if ( ! is_email( $values['job']['application'] ) && apply_filters( 'job_manager_validate_fields_application_force_validate_url', true ) ) {
```

**Comment by Hastibe** [comment]
Thanks for opening this--in addition to "email," "URL," or "email or URL," having the option to bypass those sanitizers, and just use the default sanitizer that the general "Description" field uses would be very appreciated.
