### ISSUE TITLE
Polylang - Featured Jobs (fields) not translating

### ISSUE THREAD

**Issue by AshleyBale** [Automattic/WP-Job-Manager#1877]
There appears to be an issue using Polylang with the latest update of WP Job Manager.

This specifically affects custom fields e.g. – hours, salary, closing date

Whatever is entered into the field on the English translation e.g. 27 hours per week
Will then appear on both English and the Alternative language job advert, rather than the correct language. 

It appears that it will only allow you to save one version of the language for the field type. This is only affecting feature jobs.

If you change the Alternative language to e.g. 27 awr yr wythnos
This will then reflect on both Alternative and English language job advert.

Any ideas on a fix?

**Comment by jom** [comment]
This seems like it involves custom code or plugins. I'm going to close for now. However, if you can provide reproduction steps from a fresh install of WordPress + WP Job Manager, we can see what might be happening. For support, please visit https://wpjobmanager.com/support or http://wordpress.org/support/plugin/wp-job-manager.

**Comment by jom** [comment]
I was able to reproduce with the standard WPJM fields and I have a fix pending in #1876.

### Steps to Reproduce
1) Install WP Job Manager and Polylang.
1) Add two languages.
1) Create a job listing.
1) Create a translation for the job listing in the non-default language.
1) Mark either language version of the job listing as a _Featured Listing_ in WP admin job listing editor.
1) That languages fields (such as Company Tagline) will replace the field values for the other language.
