### ISSUE TITLE
Page titles aren't being set during setup wizard

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1880]
Page titles are not being set properly when going through the initial setup wizard.

<img width="1126" alt="Screen Shot 2019-09-06 at 12 43 33 PM" src="https://user-images.githubusercontent.com/68693/64425575-fe86bb00-d0a3-11e9-8c5c-3fe49f623509.png">

**Comment by JuanchoPestana** [comment]
Hey @jom !
I think this PR I just submitted fixes this. Please let me know your thoughts and if there's anything else I could do to help!
