### ISSUE TITLE
WordPress search returns expired job

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1884]
Reported in 2331742-zen

If we look at https://github.com/Automattic/WP-Job-Manager/pull/1570 , we should not be seeing Filled and Expired jobs in the WordPress search any longer. However, they do appear now (with WPJM 1.33.5).

Aside: how can we exclude jobs entirely from WordPress search, without breaking the plugin's search capability? Is that possible?

**Comment by crazelab** [comment]
@richardmtl Is there any update on this? 

What I want to achieve more exactly is this;

1. The expired jobs should not show up in wp search

2. Expired jobs should be accessible by accessing the original URL where will show as info tab (e.g. above the job description) that the job is expired. Like [this](https://www.totaljobs.com/job/flt-driver/ideal-recruit-job89379347).

**Comment by richardmtl** [comment]
Hi! I no longer work for Automattic or WP Job Manager. cc @jom

**Comment by bindlegirl** [comment]
Solution requested in forum: https://wordpress.org/support/topic/expired-listings-returned-in-site-search

**Comment by michaelnutt2** [comment]
Solution also requested here: https://wordpress.org/support/topic/hide-job-listings-from-wp-search/

**Comment by michaelnutt2** [comment]
Solution also requested here: https://wordpress.org/support/topic/hide-expired-jobs-from-wp-search/
