### ISSUE TITLE
extend active listing 

### ISSUE THREAD

**Issue by Braehler** [Automattic/WP-Job-Manager#1888]
#### Steps to Reproduce
1.Go to you account and look for an active listing
2. right now, there is now option to extend an active listing.
3.

#### What I Expected
Go to you account, look for a listing you want to extend
Click on "extend" and choose the duration like 4 weeks

#### What Happened Instead
Currentyl customers are not able to extend their listings, and have to wait until the listing is expired and renew it

#### WordPress / WP Job Manager Version
WP: 5.2.3
WPJM: 1.33.5

#### Browser / OS Version
FF, Chrome etc

#### Context / Source

We should give the customers the option to exend their active listings. This could go hand in hand with raising up their listings as an paid option, like "get your listing back to the top for price X"
This would be a big benefit for hanling the listings, so it mekes it easier, because you don´t have to wait for a listing to expire.
Has to work with the WC PaidListings add on and I guess with simple paid listings as well

**Comment by jom** [comment]
Closing in favor of #848
