### ISSUE TITLE
Allow employers to schedule listing to post in the future

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#1901]
Allow an employer to set a date in the future for the post to publish. You can do this in wp-admin, but not on the front end currently.

Moved here from https://github.com/Automattic/wp-job-manager-applications/issues/92

**Comment by pgk** [comment]
If someone with access to wp-admin wanted to replicate Application Deadline, they could do so using e.g. https://wordpress.com/plugins/expiring-posts or similar. Application Deadline is an addon aimed at employers/frontend-only users.

Similarly, jobs can be scheduled from wp-admin.

I would argue that Scheduled job listings *for the frontend*, would make more sense to me as a new addon, pretty much like Application Deadline is an addon aimed at employers/frontend-only users.

WDYT?

**Comment by fjorgemota** [comment]
I agree with @pgk's comment here.

This indeed looks like a feature that should be present in a new addon, especially considering its focus on the front end of the site and its similarity with the Application Deadline plugin (despite different goals).

Should we maybe move this to our addons repository maybe?

**Comment by pgk** [comment]
We are discussing this a bit more. TBD
