### ISSUE TITLE
Allow employers to duplicate Expired listings.

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1918]
Requested in 2442522-zen

**Comment by richardmtl** [comment]
Also requested here: https://wordpress.org/support/topic/question-enhancement-request-make-duplicate-option-always-available/

**Comment by zatakk** [comment]
Very Useful and required !!

**Comment by cena** [comment]
3633067-zen

**Comment by gaurav1984** [comment]
4438605-zen

**Comment by samikip** [comment]
Are there any plans for this?

**Comment by richardmtl** [comment]
@samikip I no longer work for Automattic / WPJM, sorry!

**Comment by gikaragia** [comment]
6417579-zd-woothemes

**Comment by thedebian** [comment]
Superseeded by #2470
