### ISSUE TITLE
Issuse on google search console about location.

### ISSUE THREAD

**Issue by logixtreeCode** [Automattic/WP-Job-Manager#1920]
Hey there,
There is an issue on wp job manager plugin about the scheme that generating about the job.
We are seeing 4 warnings related to location on the schema testing tool.

addressLocality - The addressLocality field is recommended. Please provide a value if available.
warningaddressRegion - The addressRegion field is recommended. Please provide a value if available.
warningpostalCode - The postalCode field is recommended. Please provide a value if available.
warningstreetAddress - The streetAddress field is recommended. Please provide a value if available.

i am testing this job url 
https://gomednet.com/jobboard/9195221/
i did check the source and location in schema is coming this way 
"jobLocation":{"@type":"Place","address":"555 Clancy St, Detroit, MI, 48201, US"}
but searching more about google check, the need schema in this way 
"jobLocation":{"@type":"Place","address":{"@type":"PostalAddress","streetAddress":"555 Clancy St,","addressLocality":"Wijchen","addressRegion":"Detroit","postalCode":"48201 MI","addressCountry":"US"}

i have also searched about existing thread here, and as per your comments i have entered full address but i think scheme output is wrong
Do we need particular fields for street, city, region, and country?
in that way schema can be correctly generated or wp job manage can alter that full address and automatically pick region, city, postal code.

let me know what can be done here.

**Comment by jom** [comment]
It looks like your geocoding isn't working. Do you have the Google Maps API key set? If so, you may need to either enable billing on your Google account or enable the Geocoding API on the API key you've set.

The simple string is used when the address isn't geocoded correctly. Closing for now, but feel free to comment again if Geocoding is working and not being parsed. Otherwise, for support, please visit https://wpjobmanager.com/support or post in the forums: https://wordpress.org/support/plugin/wp-job-manager

**Comment by logixtreeCode** [comment]
Hey, Jom 
sorry I wasn't working on it 
so recently I talked with the client and did a few tests.
So the thing is it's still not working after confirming that we have enabled geocoding API.
see screenshots
![image](https://user-images.githubusercontent.com/18518982/70421910-c58a2800-1a90-11ea-8c4f-364a61a3322c.png)
and further, I did check similar thing on your demo website 
https://demo.wpjobmanager.com/job/logixtree-networks-1100-central-ave-se-albuquerque-nm-87106-usa-6-test-job/
and you can see this job is also not properly generating schema for location even I have entered the full address.
Do we need an addon for this?
Let me know that we need this sorted as soon as possible.

**Comment by richardmtl** [comment]
@logixtreeCode Please start a thread in our support forum:

https://wordpress.org/support/plugin/wp-job-manager

Or if you have a license for one of our paid add-ons, contact us here:

https://wpjobmanager.com/support

We do not provide support via Github. Thanks!
