### ISSUE TITLE
Jobs Dashboard and Post a Job only available for certain user roles

### ISSUE THREAD

**Issue by just-us** [Automattic/WP-Job-Manager#1932]
**Is your feature request related to a problem? Please describe.**
We use the jobs manager to advertise jobs to the temporary workers we have on our books and have started using the Job Alerts and Ultimate Membership plugin to create a membership site for workers at the company to get alerts when a particular job becomes available. 

The issue is that when they are logged in, they can see Post a Job and the Dashboard links in their accounts. We don't want them to have access to this feature as they are only looking for jobs, not posting them.

**Describe the solution you'd like**
A way to restrict these items so that people with a certain user role can't access them. Maybe attaching a user role that is allowed to submit jobs in the Job Submission tab, so that we can create users independently and asign the correct role to allow them to create jobs.

**Describe alternatives you've considered**

**Additional context**
![Harpers Jobs submission](https://user-images.githubusercontent.com/26407839/68394548-f14e8100-0165-11ea-96f6-cbffdce59371.png)

**Comment by richardmtl** [comment]
Hi! WPJM comes with the Employer and Candidate roles. You can use a Role Editor or Content Restriction-type plugin to achieve what you're trying to do.
