### ISSUE TITLE
Lack of consistency in regards to selection.

### ISSUE THREAD

**Issue by paaljoachim** [Automattic/WP-Job-Manager#1935]
**Is your feature request related to a problem? Please describe.**
This has to do with consistency in the submit listing page.
Example here: https://surfadesk.com/submit-listing/

Listing Region, Listing Type and Listing Category all have a drop down. Either single or multiselect. Like so.

<img width="881" alt="Screen Shot 2019-11-08 at 08 49 13" src="https://user-images.githubusercontent.com/5323259/68481245-ab94c580-0204-11ea-9cfc-974ee4a2886b.png">

Listing Labels does not have a drop down showing pre existing labels or mentioning that one can make ones own. The user has to guess which labels are available or make their own. In general WordPress tags should be listed where one can do a multi select. I just asked in the slack core channel about this, and might have to see if there is an issue for this on trac. I would do suggest to use the multi select feature for on tags/labels. In regards to the submit listing page it would then be consistent with the other selection methods present.

**Describe the solution you'd like**
A drop down multiselect for Listing Labels. Consistent with Listing Type and Listing Category.

**Describe alternatives you've considered**
I have been told of this plugin: https://plugins.smyl.es/wp-job-manager-field-editor/

**Additional context**
Hidden tags the user needs to first write the first letter of to see show up is not good user practice. Tags/labels should be visible right away for the user to choose from or create new labels if needed.

Hopefully a dev will be able to pick up this issue.

**Comment by jom** [comment]
Is listing Labels a renamed listing tags? That field doesn't exist in WPJM core, but it looks like it behaves like tags.

**Comment by jom** [comment]
Looks like that is being added by this third-party plugin https://astoundify.com/products/wp-job-manager-listing-labels/

**Comment by paaljoachim** [comment]
Thanks for the quick feedback Jake!
It seems I made a mistake in adding the issue here on the repo for WP Job Manager. 
I added a trac ticket in regards to having tags use a multi select drop down.
https://core.trac.wordpress.org/ticket/48538

**Comment by jom** [comment]
@paaljoachim I think it is an issue to raise with Astoundify. They just need to change the field to use the correct field type. I don't think this is a WP core issue.

**Comment by paaljoachim** [comment]
@jom 
The issue tok on a life of its own and jumped from labels in WP Job Manager to how WordPress in general handles tags. 
For instance categories have a visible list to choose from. The user can easily see the list and select which categories to use. Tags on the other hand is hidden until one begins to write and suggestions might show up depending on what one writes. So the trac issue is in general for how Wordpress handles tags. (I just started out with WP Job Manager and jumped over to a general Wordpress issue.)
