### ISSUE TITLE
Job Type can´t be selected on IE

### ISSUE THREAD

**Issue by Braehler** [Automattic/WP-Job-Manager#1937]
**Describe the bug**
When submitting a listing on IE the customer is not able to select a job type. If he selects on, everything is fine, but when trying to continue to submit the listing, it throws an error

**To Reproduce**
1. Go to 'submit a job.'
2. Click on 'the listing duration and click continue, edit the whole job submit mask, and choose a job type. You can choose a type and it´s accepted. But when you try to continue it throws an error, that you have to select a job type'

**Expected behavior**
User can submit a job-listing without this error, like on all other browsers. This only happens on IE

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version:5.2.4 
- WP Job Manager Version: 134.0
- PHP Version: 7.1.16 
- Other important details:

**Comment by richardmtl** [comment]
Hi!

What is the error that the user gets? Can you share a screenshot please?

What version of Windows and IE does this happen on?

**Comment by Braehler** [comment]
Hey,
it´s the standard error that says please select a type, if the field is required.
Windwos Version of the customer was Win7 with IE Version 9 or 10

**Comment by richardmtl** [comment]
@Braehler is this a bug that's reproducible on any site, or just their site? If just their site, please start a thread in the forum. If it's on any site, let me know. Thanks!
