### ISSUE TITLE
Improve compatibility with TwentyTwenty

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#1938]
- Buttons on frontend TinyMCE editor shouldn't use theme's colors for background color.
<img width="617" alt="Screen Shot 2019-11-14 at 4 58 17 PM" src="https://user-images.githubusercontent.com/68693/68878637-fa0ffb80-06ff-11ea-8b64-85a35b1ad0e9.png">

- We might need to add a wrapper on WPJM pages. We should also consider making this wide. That should fix these issues:
<img width="1045" alt="Screen Shot 2019-11-14 at 4 58 54 PM" src="https://user-images.githubusercontent.com/68693/68878699-0eec8f00-0700-11ea-89b9-a170877e0fbb.png">
<img width="633" alt="Screen Shot 2019-11-14 at 4 59 28 PM" src="https://user-images.githubusercontent.com/68693/68878763-26c41300-0700-11ea-87d8-055500fa66d8.png">

**Comment by JuanchoPestana** [comment]
Hey @jom! This PR should take care of the background color in the TinyMCE buttons. Please let me know your thoughts and if there's anything else I could do to help! 
Thanks!
