### ISSUE TITLE
Bug with Newspaper Theme 

### ISSUE THREAD

**Issue by dbart10** [Automattic/WP-Job-Manager#1942]
**Describe the bug**

Warning: require(/home/agenciabocca/public_html/achougastronomia.com.br/wp-content/plugins/td-standard-pack/Newspaper): failed to open stream: No such file or directory in /home/agenciabocca/public_html/achougastronomia.com.br/wp-includes/comment-template.php on line 1508

Fatal error: require(): Failed opening required '/home/agenciabocca/public_html/achougastronomia.com.br/wp-content/plugins/td-standard-pack/Newspaper/' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/agenciabocca/public_html/achougastronomia.com.br/wp-includes/comment-template.php on line 1508
Há um erro crítico no seu site.

**To Reproduce**
1. Newspaper 10.2 installed
2. Click on see the Job
3. See error

**Screenshots**
![Captura de Tela 2019-12-04 às 16 07 08](https://user-images.githubusercontent.com/58528576/70172792-348e0800-16b0-11ea-94ab-d8a235b30fa8.png)

**Comment by jom** [comment]
This seems like a theme issue or potentially something with the `td-standard-pack` plugin. Closing for now.

**Comment by dbart10** [comment]
Hey @jom i don't understand, i deactivate the plugin, but the error keeps...

anyways this plugins is needed, can you help me? I need this so much!!!

**Comment by jom** [comment]
I would first ask the theme developer: https://themeforest.net/item/newspaper/5489609/support

It doesn't look like it is due to anything directly in WPJM, but if you ever see `wp-job-manager` in the trace for the error you can ask in the WPJM forum: https://wordpress.org/support/plugin/wp-job-manager/
