### ISSUE TITLE
Not able to change the author of a vacancy

### ISSUE THREAD

**Issue by wdejager** [Automattic/WP-Job-Manager#1945]
Hi, I'm using WP Job Manager v. 1.34.1. I was just adding a new vacancy and tried to assign the vacancy to another author (not me, the site admin). However after changing the author and updating the vacancy, the vacancy is still listing me as the author.

**Comment by richardmtl** [comment]
Hi! Please start a thread in our support forum:

https://wordpress.org/support/plugin/wp-job-manager

Or if you have a license for one of our paid add-ons, contact us here:

https://wpjobmanager.com/support

We do not provide support via Github. Thanks!
