### ISSUE TITLE
Add option to allow for additional email notification recipients

### ISSUE THREAD

**Issue by IronWarjack** [Automattic/WP-Job-Manager#1951]
Just found the WP Job Manager plugin, works wonderfully, but the email options do not (for us).

You only provide one option, the site admin.  Our site has a few folks who handle the info of traffic, questions and email. Most plugins give us the option to make a selection of who.

It would really help to add a radio button when enabled [x] default to admin... but also offer a [x] other text box for a custom address.

[x] Notice of New Listing

Send a notice when a new job is submitted on the front end.
(*) Site Admin Email (Settings > General)
( ) Other ____________________________________________

Thank you!

**Comment by Hastibe** [comment]
@grungyape - the [WP Job Manager Emails](https://plugins.smyl.es/wp-job-manager-emails/) add-on can do this (and a whole lot more). Hope this is helpful!

**Comment by jom** [comment]
Similar #1530

**Comment by cena** [comment]
3564952-zen

**Comment by bindlegirl** [comment]
4047444-zen

**Comment by yscik** [comment]
Closing as it's possible with a third-party plugin.
