### ISSUE TITLE
Security fixes

### ISSUE THREAD

**Issue by alexsanford** [Automattic/WP-Job-Manager#1955]
Placeholder for security fixes - https://github.com/Automattic/WP-Job-Manager-Private/pulls

**Comment by truongwp** [comment]
I found a security vulnerability here: https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L1068

We should wrap the $_GET like this `sanitize_text_field( wp_unslash( $_GET['search_category'] ) )`

Does this issue cover the above thing? Is anyone working to fix? I can provide PR.

**Comment by jom** [comment]
Hi @truongwp! Nice catch. This is unreleased code, but please in the future report security vulnerabilities to https://hackerone.com/automattic. 

I'll throw up a quick PR.

**Comment by truongwp** [comment]
Ok. I will notice that thing. Thanks @jom
