### ISSUE TITLE
Changing the "Company" slug to something else

### ISSUE THREAD

**Issue by uniglobaledu** [Automattic/WP-Job-Manager#1956]
There are other uses for this plug-in such as jobs in the education industry. Will it be possible to change the "company" slug to "school"?

E.g. yoursite.com/**company**/xyz%20University/ to yoursite.com/**school**/xyz%20University/

**Comment by jom** [comment]
WP Job Manager does not provide the company profile/listing pages. You may be using another plugin to add this functionality (such as https://wordpress.org/plugins/wp-job-manager-companies/), if so I'd reach out to them.
