### ISSUE TITLE
Allow users to select between pagination links or load more button in [jobs] page

### ISSUE THREAD

**Issue by JuanchoPestana** [Automattic/WP-Job-Manager#1960]
If I'm not mistaken, there's no way for the user to choose pagination links in the [jobs] page. The only option currently supported is the "Load More Listings" button.

We could add a setting that allows the users to select the type of pagination they desire. 
I'll submit a PR that addresses this. Maybe it could be useful for someone...

**Comment by richardmtl** [comment]
Noting that there is a way to do in the shortcode:

https://wpjobmanager.com/document/shortcode-reference/

`[jobs show_pagination="true"]`
