### ISSUE TITLE
The option "job_manager_display_only_city_state" is not deleted when uninstalling the plugin

### ISSUE THREAD

**Issue by JuanchoPestana** [Automattic/WP-Job-Manager#1962]
**Describe the bug**
When uninstalling the plugin, with the Delete data setting enabled, the option "job_manager_display_only_city_state" is not deleted.

**To Reproduce**
1. Enable the Delete data on uninstall setting
2. Uninstall the plugin
3. Go to the wp_options table -> this option is still there

**Expected behavior**
The option should be deleted on uninstall.

**Comment by jom** [comment]
Mentioned this in the PR, but I don't think this is a WPJM core option. Have you attempted to replicate on an instance with just WPJM core?

**Comment by JuanchoPestana** [comment]
Hey Jake, sorry about this! I polluted my db while working on issue #1878 ... My bad!
