### ISSUE TITLE
Resizing and compressing images client side with file upload

### ISSUE THREAD

**Issue by sebapao** [Automattic/WP-Job-Manager#1965]
I'm building an advertisement site where users can upload their product photos using the file field in the job submission form. However when users upload too many images the total amount is too large and will timeout the server. 

Therefore I would like a solution to do client-side image resizing with javascript, as I know there is already jquery file upload loaded and they have options to do so. I can't get this too work unfortunately. Would be good to choose maxwidth/maxheight and imagequality for example so they are processed and compressed before uploading to server.

**Comment by richardmtl** [comment]
Hi,

Noting that you opened this thread about the issue as well: 

https://wordpress.org/support/topic/client-side-image-resizing-with-file-upload-on-wp-job-manager/

This isn't something that we'd add to our plugin, as it's quite out of scope for what WPJM does, and to do it properly wouldn't be simple. As such, I'm closing this issue.
