### ISSUE TITLE
Featured Jobs widget: sort by random behaves unexpectedly

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#1967]
**Describe the bug**

In the settings for the Featured Jobs widget, if you choose sort by: random, it doesn't seem to display a random selection of featured jobs. The same jobs are displayed on refresh, and it doesn't make sense to have a 'sort direction' field for random.

**To Reproduce**
1. Create several jobs and make them all featured.
2. Add the Featured Jobs widget to any widget area and set sort by: random.
3. View a page containing the widget.
4. Results are inconsistent, but refreshing the page does not change the jobs shown.
5. Changing the sort direction displays a different selection of jobs.

**Expected behavior**
When sort by is set to random, a random selection from all featured jobs should be displayed, and that should change on refresh. Not sure if the 'sort direction' field makes sense when sort by is random, maybe it should be disabled.

**WordPress Environment**
- WordPress Version: 5.3.2
- WP Job Manager Version: 1.34.1
- PHP Version: 7.2.26

Reported in 2655100-zen

**Comment by mrdiger** [comment]
Please do not disable random option. Instead try fix it so it works like it is suposed to work.
Random among ALL featured jobs

Thanks alot. This is an important feature

**Comment by danjjohnson** [comment]
@mrdiger I didn't mean to disable the random option. I meant if the 'sort by' is random, then maybe we should disable the 'sort order' since items sorted randomly have no sort order by definition.

**Comment by mrdiger** [comment]
Ok! Sorry i missunderstood. Hope this random feature is fixed. It is quite important. Good luck!

**Comment by mrdiger** [comment]
Hello guys!

Nothing new to this bug?

**Comment by danjjohnson** [comment]
@mrdiger not yet. We'll provide an update here when there is any news.

**Comment by mrdiger** [comment]
I bump this issue cause it need a fix. Hope it is possible. Thank you

**Comment by mrdiger** [comment]
> To clarify: the job listings are displayed in a random order, but the same job listings are shown on refresh every time.

Exactly! Thank you for accepting (not sure what it means since i'am new but i guess it means you will try fix it. In that case i wish you good luck and thank you in advance!)

**Comment by danjjohnson** [comment]
@mrdiger yes, it means we will be fixing it. You can subscribe to this issue for updates on the fix as they happen :)

**Comment by truongwp** [comment]
It's the cache problem. The previous jobs are cached and used for the next load.

https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L171
https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L184
https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L191
https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L212

IMO we should not use the cache for random order.

**Comment by roundhill** [comment]
Do I need to enable something to get caching working? On my test site it re-randomizes on every page load for me.

**Comment by truongwp** [comment]
I tested on a fresh installation and didn't enable anything. Make sure that the number of jobs in widget must be less than the total of featured jobs, and you will see the same set of jobs on every page loads, just change the order.

**Comment by roundhill** [comment]
> I meant if the 'sort by' is random, then maybe we should disable the 'sort order' since items sorted randomly have no sort order by definition.

Unfortunately it appears to be quite difficult to use js in the widget editor... I think possible but might be more trouble than it's worth.

**Comment by mrdiger** [comment]
> It's the cache problem. The previous jobs are cached and used for the next load.
> 
> https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L171
> https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L184
> https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L191
> https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L212
> 
> IMO we should not use the cache for random order.

Hello! How can we remove cache from this widget?
Thanks

**Comment by truongwp** [comment]
@mrdiger Via your theme, you can set this hook to `false` to disable cache for all widgets: https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L166

Or remove this transient in `before_get_job_listings` hook: https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L171

Or wait for this issue is solved
