### ISSUE TITLE
post-a-job - 404 When selecting a package 

### ISSUE THREAD

**Issue by kierandesmond** [Automattic/WP-Job-Manager#1970]
Hi All,

Appreciate any help, can't seem to figure out whats going on. Thought it would all work out of the box... Maybe I am missing something.

#### Steps to Reproduce
1. Install Jobify, follow all steps - e.g. plugins and content imports 
2. Create a profile
3. Create a job and select the Select Package Button

#### What I Expected

To go to a page and select 1 of 3 packages

#### What Happened Instead
404 page not found error

#### WordPress / WP Job Manager Version

Version 1.34.1 
#### Browser / OS Version
Chrome on Windows 10

#### Screenshot / Video
https://drive.google.com/file/d/1o4YlxczZlT_og2h-_s2JILzvri45W8XO/view

**Comment by richardmtl** [comment]
Hi! Please start a thread in our support forum:

https://wordpress.org/support/plugin/wp-job-manager

Or if you have a license for one of our paid add-ons, contact us here:

https://wpjobmanager.com/support

We do not provide support via Github. Thanks!
