### ISSUE TITLE
Changing http to https placeholders for company web site

### ISSUE THREAD

**Issue by paaljoachim** [Automattic/WP-Job-Manager#1971]
**Is your feature request related to a problem? Please describe.**

We have a dev site here:
https://dev.surfadesk.com/submit-listing/

It uses the Listify theme and WP Job Manager.

![Screen Shot 2020-02-05 at 17 55 45](https://user-images.githubusercontent.com/5323259/73863714-c648fb80-4840-11ea-8929-7e3aad39fda8.png)

**Describe the solution you'd like**

All Social Media Placeholders should use https://

**Describe alternatives you've considered**

I have searched for a placeholder code snippet to change the http to https but have not found the code to do so (it looks like the specific code has not yet been added to the docs). As a temporary solution it would be helpful to have the code snippet to change the placeholders.

**Comment by jom** [comment]
Changing this to use `https://` placeholder on company web site. The social media fields do not come from WPJM core. They might be provided by your theme.

**Comment by paaljoachim** [comment]
Well I have a solution for anyone else who happens upon this issue.
Here is the CSS I used to hide the http placeholder located inside the social media fields.

```
/* https://stackoverflow.com/questions/7896402/how-can-i-replace-text-with-css and 
https://blog.escapecreative.com/how-to-replace-text-with-css/*/

/* Hides http:// placeholder. */
input#company_website::placeholder,
input#company_youtube::placeholder,
input#company_twitter::placeholder,
input#company_facebook::placeholder,
input#company_linkedin::placeholder,
input#company_instagram::placeholder{
	position: relative;
	visibility: hidden;
}
```

I will just close this for now.
