### ISSUE TITLE
Not able to through WPML find string translations for Submit listing field labels.

### ISSUE THREAD

**Issue by paaljoachim** [Automattic/WP-Job-Manager#1972]
**Describe the bug**

I have a case going with WPML which I also want to inform about here as well.

https://dev.surfadesk.com/submit-listing/
A dev site that contains Listify theme and WP Job Manager.
It also uses WPML.

Through string translation I have not been able to find words such as the labels for various fields. "Listing Name" , "Location (optional)" and other label names for the various fields are not to be found in the WPML string translation. WPML are puzzled, support at Listify are puzzled and I have yet to figure out what is going on.

I am thinking that you might have some advice on this matter. 
I have searched but not found any helpful information.

Submit listing page in Norwegian:
![Screen Shot 2020-02-05 at 18 16 06](https://user-images.githubusercontent.com/5323259/73865502-a535da00-4843-11ea-9e1f-86e1350e96cb.png)

String translation page:
![Screen Shot 2020-02-05 at 18 20 19](https://user-images.githubusercontent.com/5323259/73865873-3a38d300-4844-11ea-9eeb-f1d2f122d717.png)

I did a search for "Listing Name" but it did not show up through the String Translation screen.

**Expected behavior**

I expected to find the Submit listing field labels in the WMPL String Translation.

**WordPress Environment**
- WordPress Version: 5.3.2
- WP Job Manager Version: 1.34.1

**Comment by jom** [comment]
That string isn't in WPJM core. I imagine that is coming through your theme or a 3rd party plugin.

**Comment by paaljoachim** [comment]
Hey Jake

Following **Editing fields on the frontend**
https://wpjobmanager.com/document/editing-job-submission-fields/?aff=6990

```
// Add your own function to filter the fields
add_filter( 'submit_job_form_fields', 'custom_submit_job_form_fields' );

// This is your function which takes the fields, modifies them, and returns them
// You can see the fields which can be changed here: https://github.com/mikejolley/WP-Job-Manager/blob/master/includes/forms/class-wp-job-manager-form-submit-job.php
function custom_submit_job_form_fields( $fields ) {

    // Here we target one of the job fields (job_title) and change it's label
     $fields['job']['job_title']['label'] = "Look ma no hands";
	//$fields['job']['job_title']['placeholder'] = "Custom Label - Code not working";

    // And return the modified fields
    return $fields;
}
```

Listing name field is now renamed to "Look ma no hands".
<img width="943" alt="Screen Shot 2020-02-06 at 13 34 29" src="https://user-images.githubusercontent.com/5323259/73937484-6d7f6e80-48e5-11ea-83c7-4c6125394dbd.png">



Checking the source: view-source:https://dev.surfadesk.com/no/send-inn-oppforing/
I notice that the fields I am looking at is in a section called Job Information Fields.

Btw when I check further down in the social media fields. The section there is called Company Information Fields.
