### ISSUE TITLE
Searching by category slug returns all jobs if category has no jobs

### ISSUE THREAD

**Issue by richardmtl** [Automattic/WP-Job-Manager#1977]
First reported here: https://wordpress.org/support/topic/job-category-page/

I think I was able to reproduce, but not 100% certain.

Try running a /?search_category=slug where slug = a category on the site that has no jobs associated with it. It returns all jobs instead of nothing.

**Comment by richardmtl** [comment]
Another report in 2785125-zen!

**Comment by cena** [comment]
@alexsanford any chance you  could  take a look at this?
