### ISSUE TITLE
Extended Location WP Job Manager not working with Mapbox

### ISSUE THREAD

**Issue by jasonhyperledger** [Automattic/WP-Job-Manager#1985]
Bug:
We are using the latest Listify Theme (2.12.1), latest WP Version and your plugin 
Extended Location for WP Job Manager and Mapbox.

When we want to add a new listing, the listing-form is not displaying the Maps. It's only working with Google Maps. We don't want to use Google Maps anymore and now using Mapbox. We filled out the api keys for Mapbox. We don't see the map on the listing form. Can you make it work for Mapbox?

We need instructions, a script to make it work.

Thank you!

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support on our plugins, please visit https://wpjobmanager.com/support. For theme support, please contact the theme author. WP Job Manager does not contain any support for Mapbox at this time.
