### ISSUE TITLE
Job Title, Location, Apply Now Button/Link not showing 

### ISSUE THREAD

**Issue by montegue85** [Automattic/WP-Job-Manager#1986]
**Describe the bug**
We noticed the job post title was missing on the job listing webpage. I got to looking and seen that the location wasn't following through. Clicked into one of the job posted and seen the Apply Now Button/Link was gone.

**To Reproduce**
1. Go to 'https://personnelplusinc.com/job-openings/'
2. Click on 'any of the jobs' (no Job Title)
3. Scroll down to 'bottom of job post, no Apply Now'

**Screenshots**
https://i.imgur.com/xqVFIp1.png <-- webpage no, Job Title, or location
https://i.imgur.com/ADjeD5T.png <-- admin side showing Job Title and location is set
https://i.imgur.com/NlFDWGl.png <-- webpage now Apply Now Button/Link
https://i.imgur.com/UR6qldW.png <-- admin side showing Apply Now populated 
screenshot of Chrome console https://i.imgur.com/JKZbFAO.png

**Expected behavior**
Job Title should be showing on the Job listing page.
The location should follow through from the admin side to the webpage
Apply Now button/link should show when the admin field is populated

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WP Job Manager plugin is active.
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WP Job Manager Geolocation and other relate plugin is active/disabled.
- [ ] This bug happens with a default WordPress theme active.(did not try this)
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.3.2
- WP Job Manager Version:1.34.1
- PHP Version: 7.2
- Other important details: We use these plugins as well https://i.imgur.com/Sjc9jB0.png

**Comment by jom** [comment]
> This bug happens with a default WordPress theme active.(did not try this)

Please try this as this sounds like a theme issue. It doesn't seem to happen on fresh install with standard theme.

**Comment by tripflex** [comment]
Yeah make sure to check any template overrides you may have in your theme to make sure they are using the default templates (or at least similar to default templates)

**Comment by montegue85** [comment]
Theme? We use child themefy. Only recent updates was the WP JM Geolocation. We did swap the theme around and it still did not display the job title or location or Apply Now .
