### ISSUE TITLE
Filter to edit job fields after submission

### ISSUE THREAD

**Issue by AlexxxH** [Automattic/WP-Job-Manager#1990]
**Is your feature request related to a problem? Please describe.**
There are many fields on the job submission form which is time-consuming and off putting for users. In order to solve this problem, I have hidden some fields in the page template and would like to auto fill them after job submission (e.g the job deadline, image, application deadline, etc). Users also commonly make errors in job submission, e.g. grammar mistakes and spelling mistakes, which can also be corrected using this filter.

**Describe the solution you'd like**
I would like the following filter added on Line 852 of /includes/forms/class-wp-job-manager-form-submit-job.php:

$values = apply_filters('edit_job_submission_values',$values);

**Describe alternatives you've considered**
I have added this filter by hand into my plugin files, but this is over written after every update.

**Additional context**
This is a simple and quick fix to make.

**Comment by tripflex** [comment]
as mentioned https://github.com/Automattic/WP-Job-Manager/issues/1996 there already is a filter you can use to do this

**Comment by alexsanford** [comment]
Thanks @tripflex! Closing this issue, as the current filters should be adequate.
