### ISSUE TITLE
Edit job expiry email with filter

### ISSUE THREAD

**Issue by AlexxxH** [Automattic/WP-Job-Manager#1992]
**Is your feature request related to a problem? Please describe.**
I would like to edit the expiry email to add information, edit the body, and change the template to my company's standard email template.

**Describe the solution you'd like**
Please add the following filter to Line 816 of /includes/class-wp-job-manager-email-notifications.php

$content = apply_filters('edit_expiry_email_body',$content,$args,$email);

It might also be a good idea to add filters for the other arguments ($to_email, $subject, $headers, etc).

**Describe alternatives you've considered**
I have considered added a hook to the wp_mail function but as I only want to apply this to particular emails (WP job manager expiry emails), it is not ideal. I have also added the above filter to my code in the plugin folder, but this is overwritten after every update.

**Additional context**
This is a quick and easy change :)

**Comment by jom** [comment]
Email content is in templates. You can override the template in your theme. There is also a filter for the body, but I'd recommend using the template option. See `templates/emails/admin-expiring-job.php`/`templates/emails/plain/admin-expiring-job.php` for template.

If for some reason you'd rather use the filter... https://github.com/Automattic/wp-job-manager/blob/006ce36cfd6c4696b51fbdc1499f925887852f03/includes/class-wp-job-manager-email-notifications.php#L761-L769

For additional support, please visit https://wpjobmanager.com/support.
