### ISSUE TITLE
Request to add an action to class-wp-job-manager-form-submit-job.php

### ISSUE THREAD

**Issue by AlexxxH** [Automattic/WP-Job-Manager#1993]
**Is your feature request related to a problem? Please describe.**
I would like an action added to Ln 691 in the class-wp-job-manager-form-submit-job.php file. This enables developers to hook into the code before the preview/ package page is loaded, after a job is submitted. 

**Describe the solution you'd like**
I would like the following action added to Line 691 of /includes/forms/class-wp-job-manager-form-submit-job.php

do_action('submit_job_before_preview_custom');

**Describe alternatives you've considered**
I have added this to my plugin files but this is overwritten by every update.

**Additional context**
This is a very quick and easy addition to the code.

**Comment by jom** [comment]
As I mentioned [here](https://github.com/Automattic/WP-Job-Manager/issues/1991#issuecomment-611082438), you might be able to accomplish this by filtering on `submit_job_steps` and adding the `before` (callback) attribute to the `preview` step.

I don't know if a new filter makes sense there as depending on the filtered status, the preview step might not be next.

**Comment by AlexxxH** [comment]
Ok, thanks for your feedback Jom. Sorry I have just realised that I mentioned the wrong file in the other thread- sorry for the confusion there. I will look into the submit_job_steps option.
Thanks

**Comment by tripflex** [comment]
Closing this to clean things up a bit, if you have more questions please feel free to reopen it
