### ISSUE TITLE
Filled job appears in feed

### ISSUE THREAD

**Issue by alexsanford** [Automattic/WP-Job-Manager#1994]
When a job listing is Filled, it still shows up in the Feed at `?feed=job_feed`, despite the "Hide filled listings" setting being enabled.

This was mentioned in https://github.com/Automattic/WP-Job-Manager/issues/1149 (which has since been closed) and the solution alluded to was that setting. It appears that this was never fixed for the feed (or has been broken again since then).

**To Reproduce**
1. Create a job listing and set it to "Filled" (you may use the "Position Filled" checkbox on the Edit Job page for this).
2. In Job Listings > Settings > Job Listings, check the "Hide filled positions" checkbox and click "Save Changes".
3. Visit `?feed=job_feed`
4. Notice that the filled job listing appears in the feed.

**Expected behavior**

I do not expect to see the filled position in the feed.

**Comment by dericleeyy** [comment]
2883810-zen

**Comment by collegelifenl** [comment]
Just to double check: the issue has been fixed?
Kristian Voldrich
*Founder & Managing Director*
College Life
m: +31 (0)6 1933 1671
w: collegelife.co  e: kristian@collegelife.co
<https://facebook.com/collegelifenl>   <https://twitter.com/collegelifenl>
<https://www.linkedin.com/company/13031568/>
<https://www.linkedin.com/posts/kristianvoldrich_collegelife-raawards2019-employerbranding-activity-6607204772741292032-INa4>

**Comment by jom** [comment]
@collegelifenl It has been merged into master, but the fix hasn't been released. No ETA at this time.
