### ISSUE TITLE
Add filter to edit $values in job submit_handler

### ISSUE THREAD

**Issue by AlexxxH** [Automattic/WP-Job-Manager#1996]
**Is your feature request related to a problem? Please describe.**
Please could you add a filter to the function submit_handler to allow job field values to be changed after a user has submitted a job. This allows for example correction of errors, auto-filling of blank fields, etc.

**Describe the solution you'd like**
Please add the following filter to Line 595 of includes/forms/class-wp-job-manager-form-submit-job.php

$values = apply_filters('edit_job_submission_values', $values);

**Describe alternatives you've considered**
There doesn't seem to be another way to do this, there aren't many filters in the job submission process

**Additional context**

**Comment by tripflex** [comment]
This isn't needed, there's already a filter when the values are pulled you can use `job_manager_get_posted_fields`  located at `wp-content/plugins/wp-job-manager/includes/abstracts/abstract-wp-job-manager-form.php` line #447

**Comment by alexsanford** [comment]
@tripflex Thank you for the pointer! Closing this, as the current filters should be adequate.
