### ISSUE TITLE
Add npm or composer script to run phpcs

### ISSUE THREAD

**Issue by truongwp** [Automattic/WP-Job-Manager#2006]
Should add npm or composer script to run phpcs. Instead of `./vendor/squizlabs/php_codesniffer/bin/phpcs`, developers can run `npm run phpcs` or `composer run phpcs`. 

Documentation for this should also be added or created to prevent using OS's phpcs, which is wrong, and leading to sniff does not exist error.

**Comment by jom** [comment]
Fixed by #2052
