### ISSUE TITLE
PHP notice related to WP_Job_Manager_Geocode class

### ISSUE THREAD

**Issue by truongwp** [Automattic/WP-Job-Manager#2010]
I just see this PHP notice in the `debug.log` file and don't know exactly how to reproduce.

`PHP Notice:  Trying to get property 'status' of non-object in /srv/www/wp-job-manager.test/public_html/wp-content/plugins/WP-Job-Manager/includes/class-wp-job-manager-geocode.php on line 232`

We should use `isset()` check here: https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-geocode.php#L232

**Comment by alexsanford** [comment]
@truongwp Could you look into tracking this down and coming up with reproducible steps? Otherwise it will be hard for us to dig into it 🙂

**Comment by truongwp** [comment]
Yes. I will check it tomorrow when I have time.

**Comment by truongwp** [comment]
I tried to reproduce this issue but can't figure out the steps.

I reset my WordPress and install only WP Job Manager, create some jobs via both frontend and backend. I approve frontend submitted jobs and edit the location and other fields. Nothing is logged. But suddenly, the error shows in my debug.log file. I haven't checked cronjobs yet. Since that, I can't reproduce the notice message anymore :smiley:

Before I test, I added `error_log( $result );` [here](https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-geocode.php#L231) and it logs an empty value. I checked the code and found that you don't handle the case `wp_remote_get()` return `WP_Error`, causes `wp_remote_retrieve_body()` returns empty string.

Currently, I can't find a way to make that `wp_remote_get()` call returns a `WP_Error`. Do you have any idea?

**Comment by alexsanford** [comment]
Ah ok, that's fine. I actually missed that you already have a PR for this. Looks good. I'll plan to do some testing and get it merged soon 👍
