### ISSUE TITLE
Rest API problem

### ISSUE THREAD

**Issue by shorya95** [Automattic/WP-Job-Manager#2014]
Hi there, 

We're recently purchased Listify theme which basically relies on your plugin in order to function properly. We are happy that we chose listify for developing our mobile app because we get endpoints for everything through REST API, we have completed our mobile application which is halfway done. Unfortunately, we came across a problem which we did not expect while starting our mobile development.

Problem,
Check this screenshot
shorturl.at/wHMN2

We are trying to fetch response using the parameters which are predefined for getting the results but in return, it show us all the listings, 

Our Objective
We are going to ask the mobile user their geolocation using Maps API and make custom query in a way so it will work with job listing Rest API

For eg -
https://farmsnation.com/job-listings/?search_keywords=&search_categories%5B%5D=&search_location=Hockey+Academy+Rd%2C+Sector+62%2C+Badh+Khalsa%2C+Haryana%2C+India&search_radius=5&search_lat=28.9140859&search_lng=77.1079659&search_region=
(Imagine building this module on mobile)

Can you please help us how can we fetch job listings through GET request or we're doing it all wrong, Let me know what is the alternative to do that

We're looking to launch our app (Being built on Flutter) as soon as possible once we figure this.
Regards,
Pulkit

**Comment by jom** [comment]
I'm not quite sure what the bug is in this. I'm closing for now. GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
