### ISSUE TITLE
Changing the view of WPJM Job Listing list view

### ISSUE THREAD

**Issue by nunmul** [Automattic/WP-Job-Manager#2015]
Hi all,

I would like to change the list view of [jobs] listing page of WPJM into user option to switching from list view to grid view. I know somehow would be possible through the Theme(I have BuddyBoss), but couldn't figure it out.
Created a new template page from the Parent Theme templates, in the child theme with no success,  unfortunately.
Examples:
![List view02](https://user-images.githubusercontent.com/65557900/82237913-b0b29a00-9936-11ea-9587-063f5f2050d5.png)
![Grid view02](https://user-images.githubusercontent.com/65557900/82237992-d8a1fd80-9936-11ea-8c6f-e0eef10b2faa.png)

Appreciate any advice

**Comment by alexsanford** [comment]
Hi there!

This repository is reserved for bugs and enhancement requests for the plugin. For support issues, please post in the [support forum](https://wordpress.org/support/plugin/wp-job-manager/).
