### ISSUE TITLE
Allow jobs to be deleted from job dashboard in My Account tab.

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#2016]
In 2970163-zen the user reported that she was using https://yithemes.com/themes/plugins/yith-woocommerce-customize-myaccount-page/ to add the Job Dashboard to a new tab in the Woo My Account section, but from there, the 'Delete' function doesn't work. 

There are several similar premium plugins for adding a tab like this:
- https://welaunch.io/plugins/woocommerce-my-account/
- https://iconicwp.com/products/woocommerce-account-pages/

I don't have any of these, but I added the Job Dashboard to a new tab with some custom code, as described here:

https://businessbloomer.com/woocommerce-add-new-tab-account-page/

When I visited that tab and tried to delete a listing, the page refreshed but the listing was not deleted.

Since we have another feature request open to add the Job Dashboard to the My Account page - https://github.com/Automattic/WP-Job-Manager/issues/1311 - we should probably make sure that jobs can be deleted from there.

**Comment by Braehler** [comment]
Any updates on this? definitely a needed feature for customer experience

**Comment by Braehler** [comment]
@danjjohnson 
Any updates on this one? Still an annoying issue that needs to be fixed

**Comment by D-Akademie** [comment]
@danjjohnson 
Hey, we are facing this issue as well for a long time. We need a solution for this. Because this is provides customer experience and a lot of our customers would be happy

**Comment by Braehler** [comment]
Updates on this?

**Comment by Braehler** [comment]
Any news an that here? @danjjohnson

**Comment by danjjohnson** [comment]
No updates on this yet. When there are, the developers will update this issue.

**Comment by Braehler** [comment]
Updates on this? Waiting for a solution for so long

**Comment by HlebP** [comment]
There is now a plugin that can do that - Dashboard and User Account for WP Job Manager, Addons and WooCommerce.

**Comment by nvrn** [comment]
Hi there. It is possible that someone will need it.

In file \includes\class-wp-job-manager-shortcodes.php on line 61 has hook:
`add_action( 'wp', [ $this, 'shortcode_action_handler' ] );`

Function in this hook on line 84:

```
private function is_job_dashboard_page() {
  global $post;
  
  if ( is_page() && has_shortcode( $post->post_content, 'job_dashboard' ) ) {
	  return true;
  }
  
  return false;
}
```
In other words - before start actions check shortcode in post_content.

**For best quick solution you have four options:**

1. Disable this hook with the help Remove Class Action Without Access to Class Object Function (Search in Google).

2. Comment function in \includes\class-wp-job-manager-shortcodes.php (it's bad option).

3. If you use custom template for account page (example my-account.php) – not use `the_content()`; in this php code, but insert shortcode `[job_dashboard]` in account page (in the admin panel). Further: set Account Page for option Job Management Page in plugin settings (Jobs Settings – Pages).

4. Add Shortcode `[job_dashboard]` in template/page and hide this without CSS.

I chose the third option for myself.

**Comment by renrax** [comment]
> In 2970163-zen the user reported that she was using https://yithemes.com/themes/plugins/yith-woocommerce-customize-myaccount-page/ to add the Job Dashboard to a new tab in the Woo My Account section, but from there, the 'Delete' function doesn't work.
> 
> There are several similar premium plugins for adding a tab like this:
> 
> * https://welaunch.io/plugins/woocommerce-my-account/
> * https://iconicwp.com/products/woocommerce-account-pages/
> 
> I don't have any of these, but I added the Job Dashboard to a new tab with some custom code, as described here:
> 
> https://businessbloomer.com/woocommerce-add-new-tab-account-page/
> 
> When I visited that tab and tried to delete a listing, the page refreshed but the listing was not deleted.
> 
> Since we have another feature request open to add the Job Dashboard to the My Account page - #1311 - we should probably make sure that jobs can be deleted from there.

Woocommerce my account does the same thing as if you added a menu item with its own endpoint and shortcode content manually via php code. The content on the pages is displayed statically.

**Comment by renrax** [comment]
> There is now a plugin that can do that - [Dashboard and User Account for WP Job Manager, Addons and WooCommerce](https://codecanyon.net/item/dashboard-and-user-account-for-wp-job-manager-addons-and-woocommerce/34747803).

This plugin offers to place only wp job manager pages with lists on the account page. Pages to add jobs or resumes are outside the woocommerce account. So this plugin does not do anything special, unlike the code written manually by the method described here:
https://businessbloomer.com/woocommerce-add-new-tab-account-page/

**Comment by hPaltanovich** [comment]
> So this plugin does not do anything special, unlike the code written manually by the method described here: https://businessbloomer.com/woocommerce-add-new-tab-account-page/

It will not work with the WPJM shortcodes. There is a specific test in the code results in shortcodes are not working in an endpoint. And this [plugin](https://codecanyon.net/item/dashboard-and-user-account-for-wp-job-manager-addons-and-woocommerce/34747803) solve this problem.

**Comment by Braehler** [comment]
Any news on this on? Still anoying that after all this time it´s still not solved/ no good workaround.   needed feature for customer experience

**Comment by yscik** [comment]
There is a filter to control if the job dashboard action handler should run. This snippet should enable it for the WooCommerce My account page:

```php
add_filter( 'job_manager_should_run_shortcode_action_handler', function( $handle_actions ) {
	return $handle_actions || is_account_page();
} );
```
