### ISSUE TITLE
Making Resume Manager Fields Required

### ISSUE THREAD

**Issue by russellsangoyo** [Automattic/WP-Job-Manager#2020]
Can we have a toggle for making fields required?
Eg.
1. Require uploading a profile picture.
2. Require a video link introduction of applicants

**Comment by alexsanford** [comment]
Customizing the fields can be done in code using the `submit_resume_form_fields` filter. There are also third-party extensions that may be helpful, such as [this one](https://plugins.smyl.es/wp-job-manager-field-editor/).

There is already an open enhancement request within the Resume Manager repo, and so l am closing this issue in favour of the existing request.
