### ISSUE TITLE
Limit Resume Category

### ISSUE THREAD

**Issue by russellsangoyo** [Automattic/WP-Job-Manager#2021]
Can we limit resume categories?
![IMG_20200601_061603](https://user-images.githubusercontent.com/56496248/83363877-800b3f80-a3cf-11ea-874a-b06a61e632ef.jpg)

**Comment by tripflex** [comment]
No you currently can not, but when/if this PR gets merged you can use the filter to define `maximumSelectionLength` in the filter to do that

**Comment by tripflex** [comment]
You can also use the new Search and Filtering addon to set this up, closing this issue due to no response from author
