### ISSUE TITLE
Allow Listings in Pending Payment to be edited and completed

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/WP-Job-Manager#2022]
When using WC Paid Listings, listings that are filled up are saved in _Pending Payment_ status before the package is checkout is completed.

If users do not complete the checkout process and go back to the post-job form, the fields are auto-populated with the previous data. However, this data is lost if the user chooses to post a new job or if the user log in using a different device.

### Suggestion

Provide an option for users to edit their existing pending payment posts like drafts. Giving them the ability to continue with the checkout process.

### Additional context

3024039-zen

**Comment by Hastibe** [comment]
This would be a terrific fix. I reported this as (in my opinion) a bug on May 17, 2020, and would love to see this resolved. As I wrote in my support ticket, this would be the desired behavior, in my opinion:

_On at least the front-end, job posts are listed as a "Draft" in the jobs dashboard with the "Continue Submission" option until they are actually submitted (so, a job post would appear as a "Draft" to the user even if a listing package had been selected, until the actual "Place Order" button is hit, which would then take the job post to the "Pending approval" status, etc.)._

**Comment by alexsanford** [comment]
This request is duplicated [here](https://github.com/Automattic/WP-Job-Manager/issues/2127). Closing this one, since the other issue has more discussion, workarounds, etc. as well as an [open PR](https://github.com/Automattic/WP-Job-Manager/pull/2141).
