### ISSUE TITLE
Abandoned 3rd Party Forms Plugin

### ISSUE THREAD

**Issue by simonpointer** [Automattic/WP-Job-Manager#2024]
I am using custom CF7 forms to manage the job process. Your support page - https://wpjobmanager.com/document/customising-job-application-process/ says to use the plugin https://wordpress.org/plugins/wp-job-manager-contact-listing/ to integrate CF7, Ninja Froms and Gravity Forms.

This plugin is now abandoned not compatible with the last 3 versions of Wordpress making it vulberable and unsecure.

Could you please change the support page and remove this information anbd suggest an alternative as managing the job applicztion form and process with custom forms is a pretty big deal for most users. Frankly I am surprised you don't have your own addon for this?

Thanks

**Comment by alexsanford** [comment]
Thank you for bringing this up. I see that you've also opened a [forum thread](https://wordpress.org/support/topic/adandoned-plugin-for-contact-from-7/), which is a more appropriate place for this type of discussion, so I'll close out this issue and the conversation can continue in the thread.

Please note, however, that we did remove that section of the documentation.
