### ISSUE TITLE
Upgrade reCAPTCHA to use v3

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#2025]
Our reCAPTCHA options require v2 of reCAPTCHA: https://wpjobmanager.com/document/setting-up-wp-job-manager/#section-3

Other plugins such as Contact Form 7 use v3, which can cause conflicts, and v3 is more user friendly.

### Additional context
Requested in 3033999-zen

**Comment by tripflex** [comment]
I don't know if v3 is more "user friendly" but more so meant for not showing validation to the user, but for leaving that on the backend to handle. 

IF anything the best option would be to move to v2 invisible instead

https://developers.google.com/recaptcha/docs/faq
https://developers.google.com/recaptcha/docs/invisible

**Comment by tripflex** [comment]
Either way the problem here is the way that invisible and v3 work, which have to be tied to a button or programmatically called , but the issue i found when trying to do it programmatically is that if you use standard `click` `submit` or even `mousedown` action, by the time that is done the form is already being sent, so you end up with an empty value in the input for the recaptcha value

**Comment by tripflex** [comment]
I was able to come up with a "hack/workaround" if you guys need details just let me know

**Comment by bindlegirl** [comment]
Requested in zd-3297712

**Comment by tripflex** [comment]
Yeah because this is done client side it has to have some kind of "trigger" which is supposed to be on submit button, this is basically what I had to do to get it to work with current version of WPJM:

```
<script type="text/javascript">
	var jmfeSubmitButtonEl;

	function jmfeRecaptchaResponse( response ) {
		jmfeSubmitButtonEl.click();
	}

	jQuery( function( $ ){
		$( document.body ).on( 'click', '.job-manager-form input[type="submit"]', function ( e ) {
			var $form = $( this ).closest( '.job-manager-form' );

			if( $form.hasClass( 'disable-validation' ) || $form[ 0 ].checkValidity() ){

				// reCAPTCHA value will be empty if not set or has expired
				var recaptcha_value = $( '.g-recaptcha-response' ).val();

				if ( !recaptcha_value ) {
					grecaptcha.execute();
					// Prevent actual submission until reCAPTCHA is validated
					e.preventDefault();
					// Store the button clicked, so we can trigger it after reCAPTCHA validation
					jmfeSubmitButtonEl = $( this );
				}

			}


		});
	});
</script>
<div class="g-recaptcha"
         ....
	 data-callback="jmfeRecaptchaResponse"
	 >
</div>
```

**Comment by gaurav1984** [comment]
Also requested in 4777720-zen

**Comment by yscik** [comment]
We should include some research in this and see if there are any reCAPTCHA alternatives that could be a better fit.
