### ISSUE TITLE
sort by closing date not working with application deadline add-on

### ISSUE THREAD

**Issue by pguilha** [Automattic/WP-Job-Manager#2027]
Hi!
On the admin job list, when you have the Application Deadline add-on activated, you can display the Closing Date column, which has the little arrow on it suggesting the ability to sort by Closing Date which would be incredibly useful in my case.

However, when you click on that, it actually sorts by posted date rather than closing date.

WPJM v1.34.2
Application Deadline v1.2.2

thanks!

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests for the core plugin only. For support, especially for our official plugins, please visit https://wpjobmanager.com/support.
