### ISSUE TITLE
Expose taxonomies to third party plugins

### ISSUE THREAD

**Issue by vaccinemedia** [Automattic/WP-Job-Manager#2038]
I'm not sure if this is an issue with WP Job Manager but when trying to use Jet Engine for example, to create a "related jobs" based on the category of the currently viewed job I'm not seeing the job category or the job type taxonomies in order to filter by them. Normal post categories, tags and the woocommerce taxonomies all show up but none of the job manager ones.

I'm attaching a screen grab of what I'm seeing. I would have expected the job manager taxonomies to also be in this list
![Screenshot 2020-07-14 at 12 09 37](https://user-images.githubusercontent.com/10465885/87419312-28b1df00-c5cb-11ea-9de3-2a23acb63f4f.png)

**Comment by alexsanford** [comment]
See the taxonomy registration here - https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-post-types.php#L169

I'm guessing Jet Engine needs the `public` attribute to be `true`, in which case you should be able to use the `register_taxonomy_job_listing_category_args` filter to make it work.

Closing this as it does not seem like a bug.
