### ISSUE TITLE
Enhancement Request - Add a setting to control hiding the posting date

### ISSUE THREAD

**Issue by chancerollins** [Automattic/WP-Job-Manager#2040]
It would be really nice to have an additional checkbox under the Job Listings Settings or in the specific listing's settings that would allow you to hide the posted on date.  Sometimes we have listings that we want to be indefinite and it actually causes confusion about the listing.

**Comment by tripflex** [comment]
I think it would be a little bit overkill to add a setting just for preventing that to show on a site, but with that said ... If you want to hide this on your site you can easily do this using CSS:

```
.job-listing-meta .date-posted {
    display: none;
}
```
