### ISSUE TITLE
Allow Iframes please

### ISSUE THREAD

**Issue by Zaserr** [Automattic/WP-Job-Manager#2041]
How do  I get this to work within a job posting? 
<iframe src="https://ptb.discordapp.com/widget?id=&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>

**Comment by alexsanford** [comment]
This repo is reserved for bug reports and enhancement requests. Please post support requests such as these to the [plugin forum](https://wordpress.org/support/plugin/wp-job-manager/). Alternatively, if you have purchased one or more WPJM extensions, feel free to contact our support engineers through your wpjobmanager.com account.
