### ISSUE TITLE
Add jobLocationType: TELECOMMUTE , per Google

### ISSUE THREAD

**Issue by cena** [Automattic/WP-Job-Manager#2043]
User in 3182442-zen passed along email from Google recommending users incorporate

`jobLocationType: TELECOMMUTE` for 100% remote jobs.

From the email the user passed along:
```

"Implementing this markup can expose a "work from home" tag next to that job posting, to improve visibility for interested job seekers.
Please note that this feature is available only in the USA and UK at the moment"
```

See also: https://developers.google.com/search/docs/data-types/job-posting#remote-jobs

**Comment by thedigitalcircle** [comment]
I had also received mail from Google webmaster.

**Comment by alexsanford** [comment]
Related: https://github.com/Automattic/WP-Job-Manager/issues/918#issuecomment-665091374

**Comment by tripflex** [comment]
This would also require some kind of setting to set that value as well though, if was to be included in the default schema

**Comment by bindlegirl** [comment]
Requested in 3841596-zen

**Comment by gaurav1984** [comment]
4446490-zen

**Comment by aicee** [comment]
4875955-zen

**Comment by MikeSEONuts** [comment]
Has there been an update on this as we need this feature for our job board site as the majority of the roles are now remote?

**Comment by onubrooks** [comment]
> Has there been an update on this as we need this feature for our job board site as the majority of the roles are now remote?

Hey @MikeSEONuts! hopefully this issue will be fixed to our next release in a few weeks.
