### ISSUE TITLE
Broken paragraphs at description field when editing from frontend

### ISSUE THREAD

**Issue by portnovyury** [Automattic/WP-Job-Manager#2054]
**Describe the bug**
When editing job from frontend, all the paragraphs that were initially at job description dissapear. 
Here is an example of the backend view - https://prnt.sc/uexq4v. 
This is the same job posting, opened for editing from job dashboard - https://prnt.sc/uexo8y 

**To Reproduce**
1. Create new job posting - from frontend or admin panel. Insert a long text with lots of paragraphs. 
2. Approve this job posting from admin panel
3. Go to Job Dashboard (frontend), choose created job posting and click edit.
4. Witness that all of your paragraphs are gone, and all you see is a uniform text.

**Screenshots**
 https://prnt.sc/uexq4v
https://prnt.sc/uexo8y 

**Expected behavior**
I expected to see the job posting description that has the same formatting with the one at admin panel, where all the paragraphs are in place.

**Isolating the problem (mark completed items with an [x]):**
- [* ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [* ] This bug happens with a default WordPress theme active.
- [* ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.5.1
- WP Job Manager Version: 1.34.2
- PHP Version: 7.2.31
- Other important details:

**Comment by Hastibe** [comment]
I'm still having issues related to this, too ([see my comments here](https://wordpress.org/support/topic/broken-paragraphs-at-description-field-when-editing-from-frontend/)), and appreciate this bug report being opened.

**Comment by tripflex** [comment]
I can confirm this is an issue as well, tested on a blank install and should probably be considered a major bug as this means any edit from a user will lose all formatting @jom thoughts?

**Comment by tripflex** [comment]
To add to this:

When listing is saved from frontend edit, the `<p>` tags are saved correctly, when that value is loaded in the admin area, these are stripped out and replaced with newlines.  Saving from admin saves with the newlines/linebreaks. 

 When "Edit Listing" page is loaded on frontend, the new lines are present, but when loaded by WP Editor for some reason are being stripped out.

**Comment by tripflex** [comment]
I think the solution here is to just change this:

https://github.com/Automattic/WP-Job-Manager/blob/00df198c7325ef974eb1a208c60044b97221a7f2/templates/form-fields/wp-editor-field.php#L41

To this:

```php
wp_editor( isset( $field['value'] ) ? wpautop( wp_kses_post( $field['value'] ) ) : '', $key, $editor );
```

This will basically convert any double linebreaks to actual <p> tags, which the editor recognizes just fine and shows correctly.  This way if the listing is edited from the admin area, we don't have to worry about it losing the formatting.

I will be updating the field editor template override to use this, @jom do you want me to submit a PR for core?

**Comment by mikeyarce** [comment]
I tested this out today and cannot reproduce the issue. 

Editing Job: 

![](https://user-images.githubusercontent.com/3220162/222556632-98129ccf-6b62-4268-a320-26cbbc671070.png)

Viewing the job:

![qhy4jS.png](https://user-images.githubusercontent.com/3220162/222556782-805fe598-a90f-47d2-9428-e23c6807d713.png)

If this is still happening please let us know and feel free to open this issue back up!
