### ISSUE TITLE
Page name vs job base conflict

### ISSUE THREAD

**Issue by toomanyairmiles** [Automattic/WP-Job-Manager#2061]
I'm replicating an existing site with a URL structure that can't be altered without fear of damaging its traffic. 

The issue is several pages are nested under `site.com/job-seekers/page-name ` including the jobs list page which is `site.com/job-seekers/current-vacancies` and listings which live at `site.com/job-seekers/current-vacancies/category/job-title`. Settings the jobs base to job-seekers causes every page under `site.com/job-seekers/page` to 404.

Even if I attempt to circumvent the slug conflict using

```
add_action('init', function () {
     add_rewrite_rule('job-seekers/?$','index.php?pagename=job-seekers', 'top');
}, 1000);
```

It does not work. Is there a way to configure the jobs base and the page slugs to be the same without breaking the plugin?

**Comment by Hastibe** [comment]
I recommend also posting on [the WordPress support forum for WP Job Manager](https://wordpress.org/support/plugin/wp-job-manager/) for assistance.
