### ISSUE TITLE
Search Bar is not working

### ISSUE THREAD

**Issue by Aichan1** [Automattic/WP-Job-Manager#2062]
**Describe the bug**
The search bar is not working in my site. I have jobs but it cannot be searched. Before, you can see the job listing but now I cannot see it now.

**Screenshots**
![search bar not working](https://user-images.githubusercontent.com/71756416/94000501-d3176100-fdc9-11ea-88e4-6ae0c522a297.PNG)

**WordPress Environment**
- WordPress Version:  5.5.1
- WP Job Manager Version: 1.34.3
- PHP Version: PHP Version 7.4.10

**Comment by Hastibe** [comment]
I recommend also posting on [the WordPress support forum for WP Job Manager](https://wordpress.org/support/plugin/wp-job-manager/) for assistance.

**Comment by tripflex** [comment]
I just tested with a blank install and everything works fine, so this issue has to be something specific to your site, not WP Job Manager specific.

Please request support/help on the support forum for your issue, and possibly provide the URL to the site so others can try and help you.
