### ISSUE TITLE
Create an Addon for WPGeoDirectory Plugin

### ISSUE THREAD

**Issue by bapjo4** [Automattic/WP-Job-Manager#2063]
WP Job Manager is an excellent plugin for their functionality, dashboard and etc.  But I would like to see an addon for WPGeoDirectory plugin.    WPGeoDirectory is the world's most advanced and scalable WordPress Directory Plugin.

When an user types the name of place on the WPGeoDirectory website and go to the detailed page of that place, there should be a job posting for this particular place be seen on the web page where people can apply.

If the business owner owns five locations and posts five positions but one for each location/place.  That one particular place will show one job opening.  And other places might have at least one job opening and some none.  You get the idea.

For business owner, they should have the dashboard and manage jobs postings and also pay to post jobs if they don't list with the directory...  if they are listed with directory, they can either post it for free or still have to pay to post jobs.

And also gives users the option to look at the listing of job openings at all locations/places.

For more information, please check wpgeodirectory.com  

Thanks,

Brad

**Comment by tripflex** [comment]
I suggest contacting the developer of WPGeoDirectory as they know their plugin the best and would probably be the ones to create an addon for handling integration with WP Job Manager.

As an addon developer for WP Job Manager for the past 5+ years this is probably one of the first requests i've heard for this plugin, so chances are the only person who will create one is going to be the developer of WPGeoDirectory as that is a value add for their current software.
