### ISSUE TITLE
Double list of Job on Listing Page (Polylang & WP Job Manager)

### ISSUE THREAD

**Issue by letas89** [Automattic/WP-Job-Manager#2064]
Hello to all. 

I am writing this post because i want to help me with an issue which i have with Polylang and WP Job Manager plugin. 
I am creating my website in English and Greek Language. 
When I create a Job in English, I create and the translation in Greek Language and connect each other. 
When I go to the listing page I see two jobs. One in English and one Greek. The correct is to see one job and until change the laguage to see the other Job. 

Look at the pictures to understand. 

![Screenshot_2](https://user-images.githubusercontent.com/72230128/94862137-37c56200-0441-11eb-8d7b-3faff1804565.png)
g…]()
![Screenshot_1](https://user-images.githubusercontent.com/72230128/94862273-67746a00-0441-11eb-9f50-b3254105565b.png)
![Screenshot_3](https://user-images.githubusercontent.com/72230128/94862766-19ac3180-0442-11eb-9e51-c9dd179672fa.png)

You will see in admin panel that the jobs are connect successfull but in my search page you can see two Jobs one in Greek and one in English title. 

Thank you
John

**Comment by gkaragia** [comment]
Hey @letas89 Job Manager is not aware that the extra job is from another language, it simply returns all jobs. I imagine that if you want jobs from single language to be displayed, this is something that you will need to implement. 

Is this the jobs shortcode page? If yes you can possibly use the `job_manager_output_jobs_args` filter to achieve that. In any case I don't think that this is a bug with WP Job Manager. There is a [guide for WPML and WP Job Manager](https://wpml.org/documentation/plugins-compatibility/translating-wp-job-manager-using-wpml) if you want to take a look.
