### ISSUE TITLE
Html code support

### ISSUE THREAD

**Issue by dewebkiller** [Automattic/WP-Job-Manager#2093]
### Is your feature request related to a problem? Please describe
While creating the field for the google map. It doesn't support the iframe (html code). Thats frustrating.

### Describe the solution you'd like
Html code support for the textarea.

**Comment by tripflex** [comment]
Are you saying you want textarea fields to support HTML input by the user submitting a listing?  This is not possible specifically for security reasons, as this would allow any user to enter in arbitrary HTML and iframes, which is a security risk for sites.

If you want to allow HTML you will need to do this with your own PHP code, we will not open up security vulnerabilities in this plugin for site specific customizations/requirements.

You can use this filter to define your own function to call for getting the value:
https://github.com/Automattic/WP-Job-Manager/blob/master/includes/abstracts/abstract-wp-job-manager-form.php#L422

Here's the default function:
https://github.com/Automattic/WP-Job-Manager/blob/master/includes/abstracts/abstract-wp-job-manager-form.php#L550-L553

You could also define to allow iframes through `wp_kses` which is what the default function uses to sanitize with:
https://gist.github.com/bjorn2404/8afe35383a29d2dd1135ae0a39dc018c
