### ISSUE TITLE
Custom Submit Job Form Fields filter to make phone number required?

### ISSUE THREAD

**Issue by Michaelh818** [Automattic/WP-Job-Manager#2094]
### Is your feature request related to a problem? Please describe
There is nowhere I can adjust the phone number to make it required.  
 // You can see the fields which can be changed here: https://github.com/mikejolley/WP-Job-Manager/blob/master/includes/forms/class-wp-job-manager-form-submit-job.php

### Describe the solution you'd like
 why is there no filter like     $fields['job']['job_phone']['required'] = true;
or     $fields['job']['phone']['required'] = true;
Can we add that so I can make this field required? 

### Describe alternatives you've considered
Can add JavaScript to make it required on page load but I want a backend solution that also makes sure this field is required.

### Additional context
...

**Comment by tripflex** [comment]
There is no default "job_phone" field, this must be something added by your theme.  

There already is a filter you can use to set the field as required `submit_job_form_fields`

The core plugin also does not have frontend field required/validation, this would require your own custom template overrides to handle this or using a 3rd party plugin:

https://wpjobmanager.com/document/editing-job-submission-fields/
