### ISSUE TITLE
How to create a page for Regions?

### ISSUE THREAD

**Issue by deezywonder** [Automattic/WP-Job-Manager#2104]
I'm trying to create statics result pages to help me with SEO, but it's not working.
I use the Job Region and I use this shortcode [jobs selected_region=IDOFREGION] but nothing happens, it just creates a page with the all jobs...

Can you help me?
Thanks.

**Comment by cena** [comment]
Hi, this is intended for bug reports and enhancement requests for the WP Job Manager plugin.  It is not a support forum.

In any case, we do not make the Regions plugin for WPJM, so your best bet is to contact the developer: https://astoundify.com/support/

Best,
Cena
