### ISSUE TITLE
Improve file uploading experience for logged out guests

### ISSUE THREAD

**Issue by Joe-Bloggs** [Automattic/WP-Job-Manager#2106]
This issue was initially opened in the WJPM Support forums on WP here: 
https://wordpress.org/support/topic/logo-image-upload-loader-not-working-when-user-logged-out/

There is an issue with the Logo/File upload field. The field works as expected when user is logged in, showing the little upload process bar, thumbnail as well as the remove option.

When user is logged out, this doesn't work.

**To Reproduce:**
This issue can be easily reproduced on WPJM Demo site.
1. Go to https://demo.wpjobmanager.com/post-a-job/
2. Sign in as a user
3. Click the 'Choose file' button to upload a file, file should upload as expected, giving process bar, thumb & remove option
4. Log out of the account
5. Repeat the process as logged out

**Screenshots/Screen recording:**
Please see the following screen recording exactly showing the issue: https://youtu.be/F70VoQQZD8U

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [X ] This bug happens with a default WordPress theme active.
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.6
- WP Job Manager Version: 1.34.5
- PHP Version: 7.3
- Theme: Tested with Storefront, Twenty Twenty One

**Comment by Joe-Bloggs** [comment]
@tripflex do you think you'd be able to help out with this one? 

I'd love to use the multiple image upload with AJAX with your WPJM Field Editor, but unfortunately this bug makes it totally impossible for the logged out users :(

**Comment by creowings** [comment]
I have the same problem, did you find a solution? It seems to me that there was no such problem before. Please give me a hint?

**Comment by Joe-Bloggs** [comment]
> I have the same problem, did you find a solution? It seems to me that there was no such problem before. Please give me a hint?

@creowings no solution yet.

**Comment by tripflex** [comment]
So this actually isn't a bug, it's intended for security reasons.

In version 1.26.2 of the core WP Job Manager plugin, a security vulnerability was patched to prevent guest/anonymous users, from being able to upload files directly to your server, without having an account (and having them added to media gallery):
https://github.com/automattic/wp-job-manager#1262

Because of this, any guest user on your site that is not logged in, will not be able to upload via AJAX by default, for security reasons.

If you wish to bypass this, and allow AJAX uploads for guest users (which I do not condone or support), you can add this code to you child theme’s functions.php file, or using the Code Snippets plugin:
https://gist.github.com/tripflex/f9ae184b485ff8d2ee592ed576be3212

**Comment by tripflex** [comment]
In regards to non-logged in users, to select multiple photos you have to either use CTRL+select or SHIFT+select which is standard HTML file upload handling (this is based on browsers not WP Job Manager specifically).

https://www.computerhope.com/issues/ch000771.htm

Although I do agree this is a bit cumbersome as a standard file upload method.  Wondering if maybe there's anything we could do to make this more intuitive without removing security handling @jom ?

**Comment by Joe-Bloggs** [comment]
Thanks @tripflex , that really helps, I appreciate that.

Not really sure what to do now though. I'd love to have the submissions opened to guests, but I know that I'll be getting support messages saying the multiple image upload doesn't work. 
I think I'll use the snippet to allow the guest uploading with AJAX and monitor the activity, but yes, I agree that it's a bit clumsy the way the upload currently works, so if guys could possibly come up with more intuitive and user-friendly alternative of uploading multiple images for guests, it would really be great. Thanks again.

**Comment by jom** [comment]
As @tripflex has mentioned, that is expected behavior based on the security fix. We still allow guest uploads, they just happen when submitting the form and not in the submission step (background).

**Comment by jom** [comment]
Actually, closing in favor of #1203. I think the propose solution is what we'd want to do.

**Comment by Joe-Bloggs** [comment]
@jom I know you probably have a lot on your plate and I really appreciate you taking time to answer this, but the #1203 ticket was opened in 2017. It's 2021 now. Do you think maybe this enhancement could be moved a little higher up in the queue? 
It's about user experience.

**Comment by jom** [comment]
@Joe-Bloggs We're currently focused more on bug reports and high-impact enhancement requests. There doesn't seem to be a lot of requests for this, but I'd be happy to look at any community PRs for this to get it in.

**Comment by Joe-Bloggs** [comment]
> @Joe-Bloggs We're currently focused more on bug reports and high-impact enhancement requests. There doesn't seem to be a lot of requests for this, but I'd be happy to look at any community PRs for this to get it in.

Sure, many thanks @jom , that would be great.
