### ISSUE TITLE
Missing field 'thumbnailUrl' 

### ISSUE THREAD

**Issue by amarsai1** [Automattic/WP-Job-Manager#2108]
Anybody, please help me how I can fix the Missing field 'validThrough' on https://www.techsingh123.com/

actually, I'm facing too much issue please help me

**Comment by tripflex** [comment]
Please make sure you fill out the correct form when opening an issue, your question does not make much sense at all, you say `thumbnailUrl` in title but `validThrough` in message.

`validThrough` for structured data will only be output if `job_expires` field has a value on the listing itself.

**Comment by tripflex** [comment]
You can ask for support at https://wordpress.org/support/plugin/wp-job-manager/ please only report bugs or feature requests here on GitHub

**Comment by tripflex** [comment]
Closing due to no response from author

**Comment by amarsai1** [comment]
thanks, everyone with help your valuable suggestion I have fixed now https://www.techsingh123.com/ bugs free.
