### ISSUE TITLE
Locations manager

### ISSUE THREAD

**Issue by ofry** [Automattic/WP-Job-Manager#2109]
### Is your feature request related to a problem? Please describe

I want location taxonomy manager containing all available locations.

### Describe the solution you'd like

For example, I can put all possible locations to this manager, then I can programmatically create drop-down list with locations in filter window. Or auto-complete location widget, or smth else.

### Additional context

Filter example: 
![screenshot-location-search](https://user-images.githubusercontent.com/11790863/105696603-95ac1700-5f14-11eb-939d-88135facd513.png)

If this will realized, then I can modify this form for drop-down list.

**Comment by tripflex** [comment]
This is already possible using the Regions addon:
https://wordpress.org/plugins/wp-job-manager-locations/

Majority if not all themes already support this

**Comment by ofry** [comment]
Thank you for this answer.

**Comment by ofry** [comment]
But how to use this plugin for such filtering? There are totally lacks any documentation.

And I saw in plugin info:

"**Note:** Listings are not filtered by regions. They are simply used as an organization tool."

**Comment by tripflex** [comment]
@officeutils i guess that is only theme specific then, as the core plugin does not have support for this addon plugin, so if the addon plugin is not adding it and your theme is not, your only option is to add it yourself with PHP or use my Search and Filtering addon which will do it for you:

https://plugins.smyl.es/wp-job-manager-search-and-filtering/
