### ISSUE TITLE
Adding AI Parsing and Matching to WP Job Manager

### ISSUE THREAD

**Issue by mouhidine** [Automattic/WP-Job-Manager#2116]
Hello the team,

We're considering to merge WP Job Manager with our open source project https://github.com/Riminder/open-jobboard as a plugin. 
Who would be the right person to talk to?

Thanks, Mouhidine

**Comment by thedigitalcircle** [comment]
That's a Great Idea. WPJM should consider this to modernize the plugin to next level. 
Shuvashish

**Comment by alexsanford** [comment]
Hi @mouhidine. This Github repository is reserved for bug reports, enhancement requests, etc. for the WP Job Manager plugin. If you require support, the best place to ask is on the [support forums](https://wordpress.org/support/plugin/wp-job-manager/), or through your wpjobmanager.com account if you have purchased any of our premium add-ons.

That said, it sounds like what you are looking to do is a custom project, and probably outside of the scope of our support. But if you have specific questions about some aspect of WP Job Manager, the support forums may still be a good place to ask.
