### ISSUE TITLE
Job detail pages do not display the primary menu

### ISSUE THREAD

**Issue by dkehne** [Automattic/WP-Job-Manager#2120]
On job listing page and job detail page there are two different menus shown on our page - and it does not seem to be adjustable. On the job listing page there is the correct (primary) menu but we don't know why and on what data the menu on the detailed job page is chosen from the plugin...

**To Reproduce**
1. Go to https://tuerantuer.de/jobs/ and look at the menu
2. Click on one of the jobs and see that there is another menu appearing.

**Expected behavior**
On job listing and job detail page the same menu should be shown. It should be the main menu of all pages which is set in WordPress. 

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.5.3
- WP Job Manager Version: 1.34.5
- PHP Version: 7.4.14
- Other important details:

**Comment by tripflex** [comment]
This wouldn't be anything related to WP Job Manager but related to the theme you're using and how it's configured the menus to output.  I suggest contacting your theme developer for support with this.  WP Job Manager doesn't have anything to do with menus.

The menu when viewing a job listing seems to all point to something within these subdirectories:
https://tuerantuer.de/europadorf/

My guess is your theme or menu is somehow being configured to output based on the post type or something similar -- either way as mentioned this wouldn't be anything related to WP Job Manager but related to your theme and the configuration of the theme and menu items

**Comment by dkehne** [comment]
We will have a look on that.

**Comment by dkehne** [comment]
The details pages from your plugin do not reference a post-id. We have built in a fallback in case of that in our code and solved the issue this way...
