### ISSUE TITLE
fpdate type datepicker issue

### ISSUE THREAD

**Issue by awais300** [Automattic/WP-Job-Manager#2123]
### Date picker won't work for repeated fields
it's not working when repeater fields are added programmatically, probably because the datepicker is initialized on page load.
It does work for the already saved repeated field.

Below is the code/filter where i'm adding experience fields, if you look at Date Job Begun and Date Job Ended custom fields where I have set the type to fpdate, the datepicker won't work for them, but it would work when these fields are saved and you try to re-edit.

```
add_action('submit_resume_form_fields', array($this, 'wpjms_frontend_resume_form_fields'));

public function wpjms_frontend_resume_form_fields($fields) {
	
	/*Experience Fields*/
	$fields['resume_fields']['candidate_experience']['fields']['supervisor_name'] = array(
	'label' => __('Supervisor Name', 'text-domain'),
	'type' => 'text',
	'required' => true,
	'placeholder' => '',
	'priority' => 2,
	);
	$fields['resume_fields']['candidate_experience']['fields']['supervisor_email'] = array(
	'label' => __('Supervisor Email', 'text-domain'),
	'type' => 'text',
	'required' => true,
	'placeholder' => '',
	'priority' => 3,
	);

	$fields['resume_fields']['candidate_experience']['fields']['date_start'] = array(
	'label' => __('Date Job Begun', 'text-domain'),
	'type' => 'fpdate',
	'required' => true,
	'placeholder' => '',
	'priority' => 4,
	);

	$fields['resume_fields']['candidate_experience']['fields']['date_end'] = array(
	'label' => __('Date Job Ended', 'text-domain'),
	'type' => 'fpdate',
	'required' => true,
	'placeholder' => '',
	'priority' => 5,
	);

	return $fields;
}
```

**Comment by tripflex** [comment]
This isn't related to WP Job Manager at all but related to the Field Editor plugin and the Resume Manager plugin.

You can use this example code to handle initializing those date picker fields.  If you have a valid license for field editor open a support ticket and ill help you with it.

https://gist.github.com/tripflex/ac4cdffdf0b0da92e55736452eabcd8d#file-functions-php-L110-L173
