### ISSUE TITLE
Improve integration with Sensei LMS

### ISSUE THREAD

**Issue by gikaragia** [Automattic/WP-Job-Manager#2133]
### Is your feature request related to a problem? Please describe
Currently there is no integration implemented between Sensei LMS and WP Job Manager. This proposal exists to track the popularity of such integration and any possible ideas of how it can be implemented. This integration can be implemented on a new separate plugin or included in one of the existing ones. Ideas that were mentioned until now include:

- Purchasing a WPJM related product would give access to a Sensei course.
- Users who submitted a resume, could be offered training or evaluation exams.

**Comment by bindlegirl** [comment]
3982288-zen
