### ISSUE TITLE
order_by is not working

### ISSUE THREAD

**Issue by sheeluagarwal123** [Automattic/WP-Job-Manager#2138]
Hi,
I am using Wordpress Job Manager plugin version 1.35.0 for my site on wordpress 5.7 running Workscout theme.
To display a list jobs I am using the shortcode [jobs show_filters="false" show_description="false" per_page="10"]
This should order the jobs in descending order based on Featured. but that is not happening, oldest jobs are listed first.

We try to use short code order_by=date and order=desc but no update in the order of display, oldest jobs are listed first.
We tried various combinations of ordering but the display is not updating at all.

Thanks!

**Comment by cyborgk9** [comment]
Are you using wp-job-manager-application-deadline? v1.2.4 seemed to introduce a bug where the "orderby" is set to "meta_value" for all queries. (See line 498 of wp-job-manager-application-deadline.php). I fixed it temporarily by adding "{ ... }" around the two $query->set(...); calls. Hopefully they'll fix their code for 1.2.5...

**Comment by mtgwebdesign** [comment]
Yes, one of my clients has the same issue but I don't understand enough about the code to be able fix it from the comment above.

**Comment by sheeluagarwal123** [comment]
I deactivated the wp-job-manager-application-deadline plugin and then after two days it automatically started working.. Maybe the cache issue. Definitely an issue with the plugin code, but I did not have permissions to edit it, so deactivated the plugin.
Thank you for the help!

**Comment by mtgwebdesign** [comment]
I found that just by deactivating the addon, making sure that the list shortcode was ordered by date ascending and then reactivating the Application Deadline addon plugin got the list to work again.

**Comment by alexsanford** [comment]
Thank you for the report! We have a fix in the works on the Application Deadline extension which should be released soon.

Caching is definitely a factor for this bug, which can make it hard to tell whether it is working properly. You should be able to open and save an active Job Listing to clear the cache and check if the ordering is working correctly.

**Comment by yscik** [comment]
Version 1.2.5 of the Application Deadline plugin is now released. If you are affected by this bug, after updating, you will need to clear the job listings cache to see the correct ordering. This can simply be done by editing any job listing and saving it again. (No need to change anything.)

**Comment by sheeluagarwal123** [comment]
Thank you for the update.
