### ISSUE TITLE
Job Alerts email sends expired jobs

### ISSUE THREAD

**Issue by wingm0n** [Automattic/WP-Job-Manager#2142]
**Describe the bug**
The job alerts is grabbing and sending jobs that are both expired and marked as filled.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 
- WP Job Manager Version:
- PHP Version: 
- Other important details:

**Comment by jom** [comment]
Please [contact support](https://wpjobmanager.com/support) for help and reporting issues on our premium plugins. This is just for the core plugin.
