### ISSUE TITLE
WYIWYG editor to style the notification and confirmation e-mails

### ISSUE THREAD

**Issue by LogoLogics2** [Automattic/WP-Job-Manager#2143]
The notification and confirmation e-mails are very basic and do not look very professional.
Adding a WYSWYG editor to style the notification and confirmation e-mails, would be a big +.

**Comment by Hastibe** [comment]
There is an excellent third-party plugin, [WP Job Manager Emails](https://plugins.smyl.es/wp-job-manager-emails/), which allows this (and a lot more), in case that is helpful to mention.
