### ISSUE TITLE
Not compliant with Google Structured Data Testing Tool

### ISSUE THREAD

**Issue by pantsman28** [Automattic/WP-Job-Manager#2148]
Google Testing structured data missing streetAddress and baseSalary
Scheme markup needs address to fix missing field jobLocation.address.streetAddress

Unable to fix this with custom fields geolocation_formatted_address
Would expect this to be part of the job data panel

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version:  5.3.7
- WP Job Manager Version: 1.35.0
- PHP Version: 7.3.24
- Other important details:

**Comment by Hastibe** [comment]
@pantsman28 -- not sure if this is helpful, but did you see their documentation about this?

https://wpjobmanager.com/document/fixing-structured-data-issues/

**Comment by alexsanford** [comment]
Closing this for now. If you go through the steps outlined in the [documentation](https://wpjobmanager.com/document/fixing-structured-data-issues/) and there is still an issue, feel free to reopen this.
