### ISSUE TITLE
single job listing does not use the same page attributes/template of parent page

### ISSUE THREAD

**Issue by Sidders2020** [Automattic/WP-Job-Manager#2152]
Hello, 
Using the Wordpress Vendd theme, I have set the [jobs] page attribute to be 'full width page'. However when a job is selected and I go to the 'single job listing' , it is not on the full width page, but instead the single job listing is on the Vendd 'default' page template, which unfortunately has a product search side bar. 
How do I make the 'single job listing' inherit the page attributes I have set for the [jobs] page?  I have looked in single.php but there seems to be no code relating to this. Better still, how can I see the single jobs page in my wordpress dashboard in order to set its page attributes.
Thanks
![WP Jobs single job listing](https://user-images.githubusercontent.com/38297000/118990116-8268ff80-b97a-11eb-99cf-24568d979d5e.JPG)
![WP Jobs Page](https://user-images.githubusercontent.com/38297000/118997317-7aac5980-b980-11eb-8f03-ca775276e83d.JPG)

**Comment by alexsanford** [comment]
I would suggest asking this question in the [support forums](https://wordpress.org/support/plugin/wp-job-manager/), or if you have purchased any WP Job Manager product, reach out to our support team from your wpjobmanager.com account.

Generally speaking, a job listing is not a WordPress "Page", and so the options may appear somewhere different in your theme. Jobs are a Custom Post Type (or "CPT") and it may be worth reaching out to your theme's support folks to ask how to customize these settings for CPT pages.

Closing as this does not appear to be a bug with WP Job Manager.
