### ISSUE TITLE
When job expires set Feature to 0

### ISSUE THREAD

**Issue by montegue85** [Automattic/WP-Job-Manager#2153]
So we use a carousal to display featured jobs on our web site. The problem is when the jobs expire the featured job stays on the carousal until it is manually removed. Would there a way to have it set the flags (meta_key='_featured' meta_value='0') when that happens? This enhancement would be great for anyone who uses a carousal to display job on the home page of their websites like we do.

**Comment by tripflex** [comment]
I think really the issue here is that you're showing expired jobs in your carousel ... you should probably restructure your query for the carousel to remove expired jobs

**Comment by montegue85** [comment]
Here is what the short_code for the carousal is 

<div class="featured_job_listing">
    <?php echo do_shortcode('[wcp-carousel id="2408" meta_key="_featured" meta_value="1" ]'); ?>
</div>

**Comment by montegue85** [comment]
> I think really the issue here is that you're showing expired jobs in your carousel ... you should probably restructure your query for the carousel to remove expired jobs

Here is what the short_code for the carousal is 

div class="featured_job_listing"
    ?php echo do_shortcode('[wcp-carousel id="2408" meta_key="_featured" meta_value="1" ]'); ?
/div
