### ISSUE TITLE
Anker-button for application-button in job-template

### ISSUE THREAD

**Issue by annekeengels** [Automattic/WP-Job-Manager#2164]
### Is your feature request related to a problem? Please describe
First of all, I don't have any php-skills... :-)
In the template job-application.php I added an id for the application button:

`<input id="bewerben" type="button" class="application_button button" value="<?php esc_attr_e( 'Apply for job', 'wp-job-manager' ); ?>" />`

That is, because I added another button at the top of the template content-single-job_listing-meta.php next type, date and location that is working as an anker to scroll down to the bottom of the job-page, where the application-button is located:

`<li class="button-bewerben"><a href="#bewerben" class="bewerben-button">Jetzt bewerben</a></li>`

### Describe the solution you'd like
What I would like to have is the following: When I click on my added anker-button at the top of the job-page, I would like to scroll down to the application button at the bottom AND I would like to automatically open the section that is actually opening, when I click on the application button.

Is there a possibility or a code snippet? Thank's everyon for your help! :-)

### Additional context
This is an example of one of my job-pages: https://addendum-pro.de/job/mitarbeiter-rechnungswesen-m-w-d/

**Comment by alexsanford** [comment]
Closing this as it isn't a feature request for WP Job Manager. The customization you described for your site should be possible for a developer to implement for you. Probably a JS code snippet that automatically pressed the button would do the trick 🙂
