### ISSUE TITLE
Impossible to use WPJM shortcodes inside of a WooCommerce endpoints

### ISSUE THREAD

**Issue by HlebP** [Automattic/WP-Job-Manager#2166]
### The problem 
I want to combine WooCommerce user account and WP Job Manager dashboard, WPJM Bookmarks, WPJM Alerts etc. This will improve the user experience  A LOT - everything will be in one dashboard interface. The idea is simple - add new endpoints in the WC user my account and put shortcodes there.

When I did that, the WPJM dashboard, alerts, and bookmarks displayed as they should. But then I found they are not functional! Literally, almost all action, form submissions (when create a job alert) fails.

The reason is in these checks. WP Job Manager:

`if ( is_page() && has_shortcode( $post->post_content, 'job_dashboard' ) ) {
	return true;
}`

The same check found also in the Alerts and Bookmarks addons. I assume in other addons they can also be found. 

### Possible solution
Can this area be improved so it will be possible to use shortcodes not only on usual pages? Like by adding a filter, or removing this check for shortcode presence?

**Comment by Braehler** [comment]
@HlebP 
waiting for this for so long. there are some other github threads about this see #2016 and #1311

**Comment by HlebP** [comment]
> @HlebP
> waiting for this for so long. there are some other github threads about this see #2016 and #1311

wow, did not found it, strange. I did a lot of search on this before starting it.

I am using a quite primitive workaround, maybe you can use it too until this area improved. This is how My Account page content looks right now:

`[woocommerce_my_account]<div style="display: none;">[job_dashboard][job_alerts][mas_company_dashboard][my_bookmarks]</div>` 

This makes them all work properly. Maybe there is a more elegant solution, with a content filter, but I have no time on that right now.

Looks like WPJM is not really supported anymore and have future :(

**Comment by HlebP** [comment]
There is now a plugin that can do that - Dashboard and User Account for WP Job Manager, Addons and WooCommerce.

**Comment by nvrn** [comment]
Hi there. It is possible that someone will need it.

In file \includes\class-wp-job-manager-shortcodes.php on line 61 has hook:
`add_action( 'wp', [ $this, 'shortcode_action_handler' ] );`

Function in this hook on line 84:

```
private function is_job_dashboard_page() {
  global $post;
  
  if ( is_page() && has_shortcode( $post->post_content, 'job_dashboard' ) ) {
	  return true;
  }
  
  return false;
}
```
In other words - before start actions check shortcode in post_content.

**For best quick solution you have four options:**

1. Disable this hook with the help Remove Class Action Without Access to Class Object Function (Search in Google).

2. Comment function in \includes\class-wp-job-manager-shortcodes.php (it's bad option).

3. If you use custom template for account page (example my-account.php) – not use `the_content()`; in this php code, but insert shortcode `[job_dashboard]` in account page (in the admin panel). Further: set Account Page for option Job Management Page in plugin settings (Jobs Settings – Pages).

4. Add Shortcode `[job_dashboard]` in template/page and hide this without CSS.

I chose the third option for myself.

**Comment by yscik** [comment]
Putting this in here too. There is a filter to control if the job dashboard action handler should run. This snippet should enable it for the WooCommerce My account page:

```php
add_filter( 'job_manager_should_run_shortcode_action_handler', function( $handle_actions ) {
	return $handle_actions || is_account_page();
} );
```
