### ISSUE TITLE
Job single page is not loading 

### ISSUE THREAD

**Issue by aatif604** [Automattic/WP-Job-Manager#2170]
**Describe the bug**
when I click on a job.  the job single page is not working please see the screenshot below 

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/71254187/127326307-393d9fa9-2b3e-446b-8239-75a563b6db33.png)

**WordPress Environment**
- WordPress Version: 5.8
- WP Job Manager Version:1.35
- PHP Version: 7.3
- Other important details:

**Comment by alexsanford** [comment]
Looks like there is an error occurring on your WordPress installation. The best place to ask about this is the [support forum](https://wordpress.org/support/plugin/wp-job-manager/), or if you have purchased any WP Job Manager product you can reach out to our support team from your wpjobmanager.com account.

I would start by trying a different theme, or disabling other plugins to see if that gets rid of the error message. If the site is live, you may want to create a staging site and do your testing there.
