### ISSUE TITLE
Application addon required file validation

### ISSUE THREAD

**Issue by digitalNightingale** [Automattic/WP-Job-Manager#2177]
When using the Applications add-on and on submission of an application, if there is a required file field, there is no error message stating that this is a required field. Clicking the submit button, the page refreshes and there is no indication if the application went through or failed. Note: the application does not go through.

**Steps to reproduce the behavior:**
1. Go to the admin center
2. Update the Application Form to include a required file type by adding new field type
3. Go to any job detail page
4. Scroll to Apply for job button
5. Click button
6. Click Send application button without entering a file
7. Notice the page refreshes without any type of notification.

**Screenshots**

Notice the required field tooltip for the text field. No such tooltip for the file field when trying to submit an application. 

<img width="940" alt="req-field-tooltip" src="https://user-images.githubusercontent.com/24949553/129761327-c0b0cb8e-8da6-40d0-8f47-1d27f76db966.png">

**Expected behavior**

When submitting an application with a required file field there should be an alert to the user that this is a required field. If it is selected as required in the admin center under the application form. Behavior should be similar to the text field type alert. See above screenshot.

In the job_manager/form-fields/file-field.php adding ```<?php if ( ! empty( $field['required'] ) ) echo 'required'; ?>``` to line 55, fixes the issue. All other fields have the required check in the input field code.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version:  5.8
- WP Job Manager Version: 1.35.1
- PHP Version: PHP 7.3
- Other important details: WP Job Manager - Applications Version 2.5.2

**Comment by damien-pilot-in** [comment]
Hi,
Any ETA on this? 
It's still an issue at the moment, seems like an easy fix but it's been 2 months...
