### ISSUE TITLE
WP-Job Manager 1.35.2 incompatible with Wordpress 5.8

### ISSUE THREAD

**Issue by tech-bfg** [Automattic/WP-Job-Manager#2178]
The WP-Job Manager broke when I updated to Wordpress 5.8 from 5.7.2. The top portion where the description goes disappeared and only the job data section was left. Already listed jobs still had text, but it was not possible to add text to a new job listing. The problem was solved when I reverted back to Wordpress 7.2 My site is running the following:

WordPress: 5.7.2
WP-Job Manager: 1.3.5
Theme Avada: 6.1.0
PHP:7.3

**Comment by alexsanford** [comment]
Hi! Thanks for the report 🙂 

I took a look, and I'm not seeing the same issue on my end using the latest version of Avada, WP Job Manager, and WordPress. The "Description" field is showing on the Post a Job page:

<img width="1303" alt="Screen Shot 2021-08-19 at 14 46 03" src="https://user-images.githubusercontent.com/842193/130118439-0cd5ecd1-97fe-4247-9851-a2c360bfb176.png">

I would suggest reaching out to our support team and they will help you in debugging this issue. If you have purchased any WP Job Manager product, you can do so from your account on wpjobmanager.com. If not, please feel free to post on the [WP Job Manager forums](https://wordpress.org/plugins/wp-job-manager/), which our support team also reviews regularly.

I'm going to close this issue as the Github repo is reserved for reproducible bugs. Feel free to reopen if needed.
