### ISSUE TITLE
Passwords are sent in emails instead of password reset link

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/WP-Job-Manager#2180]
**Describe the bug**
When _Email new users a link to set a password_ is enabled, plain text passwords are sent to a user email, instead of the link to set the password.

**To Reproduce**
1. Enable _Email new users a link to set a password_ in Job Listings > Settings > Job Submission
2. Submit a new job listing using a new email address to create the account
3. Check the received email.

**Expected behavior**
The email should contain the password reset link.

**WordPress Environment**
- WordPress Version: 5.8.1
- WP Job Manager Version: 1.35.2
- PHP Version: 7.4.23

Internal ref: 4296070-zen

**Comment by aaronfc** [comment]
Hi @dericleeyy I know this is an old issue but I was trying to reproduce it and I couldn't.
I have done what you described in the steps to reproduce in a 5.8.1 WP installation with WPJM 1.35.2 and PHP 7.4.

I always receive the email with a link to set the password.

Any idea if I might be missing anything?
