### ISSUE TITLE
WPJM shortcode [jobs] is crashing template & removing h1

### ISSUE THREAD

**Issue by wusatiuk** [Automattic/WP-Job-Manager#2184]
**issue**
- CSS class “page-listings” and “has-no-listing” is added to the `<body>` instead of just to the `<div>` where the shortcode is used.
- on line 1089 the h1 is removed. (very strange – never seen something like that before)

**examples:**
- page with shortcode (crashed): https://www.bungeespringen.net/base-flying/
- similar page without shortcode (looks fine): https://www.bungeespringen.net/tandemsprung/

shortcode used on site: [jobs job_types=”base-flying” show_map=”false” show_filters=”false”]

Tried to find differences in the HTML using the same page once with and once without shortcode: https://www.textcompare.org/html/?id=6151c3cf381d85001337b0a6

WPJob Manager: 1.35.2
Wordpress: 5.8.1
Theme: Listable Theme (https://themeforest.net/item/listable-a-friendly-directory-wordpress-theme/13398377)

**Comment by aaronfc** [comment]
Hi @wusatiuk thanks for your report!
I have been investigating this and it looks like the things you are seeing might be done by the theme you are using.
The reasons to belive that are:
- The `page-listings` and `has-no-listings` classes appear to be from the Listable theme. Just to be clear: those classes are defined by the Listable theme and we are not adding/removing them anywhere in the code.
- The h1 disappearing looks like something the theme could be doing by detecting that the `[jobs]` shortcode is being used.

Could you confirm with them? Another option you might want to try is to use another theme (maybe on staging) too see that those things are not happening there.

Hope that gets us closer to fixing your issue.

**Comment by mikeyarce** [comment]
Closing as it appears this is a problem with the Listable theme.  If you are still having this issue on a default theme with no other plugins active, please let us know, @wusatiuk !
