### ISSUE TITLE
How can I access the Job Fields details?

### ISSUE THREAD

**Issue by b2170090** [Automattic/WP-Job-Manager#2186]
I am writing a addon plugin. I need to create a job submit form without using template system. So I need the list of fields available in Job submit form. Is there any function to get the list of fields? Or any other way to access it?

**Comment by yscik** [comment]
👋  Sorry for the late reply on this. We have a `submit_job_form_fields` filter that contains the form fields. See this page for some examples on using it: https://wpjobmanager.com/document/wpjm-core-snippets/
