### ISSUE TITLE
Integration to Forminator / Contact Form 7 / Gravity Form instead of Applications add-on.

### ISSUE THREAD

**Issue by tnchuntic** [Automattic/WP-Job-Manager#2197]
### Is your feature request related to a problem? Please describe
Just wanted to have a complex and robust form for the application functionality. Currently, the Application add-on is to basic and doesn't have the functionality to handle a complex application form.

If it is possible to Integration to Forminator / Contact Form 7 / Gravity Form instead of Applications add-on.

### Describe the solution you'd like
Integration to Forminator / Contact Form 7 / Gravity Form instead of Applications add-on.

### Describe alternatives you've considered
Integration to Forminator / Contact Form 7 / Gravity Form instead of Applications add-on.

### Additional context
n/a

**Comment by tripflex** [comment]
It's certainly possible to do, there's already numerous plugins that handle this, one specifically that stands out is the Contact one:
https://wordpress.org/plugins/wp-job-manager-contact-listing/

**Comment by tnchuntic** [comment]
Thanks will have a look.
