### ISSUE TITLE
Reset Job Filter does not reset job types

### ISSUE THREAD

**Issue by jkchant** [Automattic/WP-Job-Manager#2198]
If I go to the Job Openings page and search or filter the "RSS" and "Reset" links appear with the search results.  If I click reset, all the fields are reset except the Job Type check-boxes.

**Comment by tripflex** [comment]
Based on the code this should already be happening:

https://github.com/Automattic/WP-Job-Manager/blob/master/assets/js/ajax-filters.js#L483-L485

Something to keep in mind, "resetting" of job types means they are all selected, not unselected.
