### ISSUE TITLE
Latest WP update broke plugin

### ISSUE THREAD

**Issue by AshcloudMac** [Automattic/WP-Job-Manager#2210]
**Describe the bug**
While creating job posts it seems random that the block to load the company logo appears. It also randomly does not load Job Categories or Job Types blocks on the right to edit them either.

The page I need help with: https://topjobseeker.com/

The bar on the right of the screen. Some load and some don’t and it seems random. This did not happen before the latest update.

See screenshots in the section below.

The dashboard page is too limited to edit posts and has too few options – for example it does not have a logo option to use a url which means I have to upload a logo every time. It is too time consuming when loading 30 to 50 job posts per day. So I edit the posts from within the plugin – Job Listings – All Jobs. Now that used to work great before the last WP update, all the side bars loaded with the job categories, types, url slug, Logo. Those sidebars now randomly load some of the features some of the time. Do you understand what I am referring too?

This seems defy the whole point of the job board. I have multiple people adding posts at different times of the day that I have to then go and edit and approve. The fact remains that before the last wordpress update it worked perfectly and after the update it didn’t.

Another great feature would be to be able to bulk edit posts to add a company logo to all of them.

**To Reproduce**
1. Go to Job Listings > All Jobs.
2. Edit a job post.
3. Refresh multiple times the screen and eventually "Job Categories", "Job Types" and "Company Logo" will not load.

**Screenshots**
![image](https://topjobseeker.com/temp/Clipboard01.png)
![image](https://topjobseeker.com/temp/Clipboard02.png)
![image](https://topjobseeker.com/temp/Clipboard03.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 
- WP Job Manager Version:
- PHP Version: 
- Other important details:

**Comment by aaronfc** [comment]
Hi @AshcloudMac,
I have been trying to reproduce the issue and I could only reproduce it when I installed YOAST SEO plugin (I saw in your screenshot that you had it installed and decided to try with it enabled).

Could you please confirm if having the Yoast SEO plugin disabled solves the issue?

Let us know so we can continue investigating from there to see if maybe we have something broken there.

**Comment by Jawn78** [comment]
I am having a weird problem after migrating. My default company logo wont load. I had it at www.sitename.com and moved it to sitename.com all the urls changed, but for some reason the company logo url from the media didn't change. take away www and it works.

@AshcloudMac I also agree that it takes away from this by making it so hard to update company logos with no support to do so through the API either... I messages the team and they said it wasnt something they support. But it takes away from the functionality a ton.

**Comment by mikeyarce** [comment]
It's been over a year and we still have not heard back about this problem, so I am going to close this issue out for now.

Thank you for the feedback about making it easier to upload company logos.  I think it fits in well with this existing issue:  https://github.com/Automattic/WP-Job-Manager/issues/1135
