### ISSUE TITLE
Some existing featured jobs not listed at the top

### ISSUE THREAD

**Issue by Lens40** [Automattic/WP-Job-Manager#2222]
**Describe the bug**
When featuring an existing job it is no longer displayed at the top position in some cases. Some are and some are not and in between there are some jobs which are not featured.

**To Reproduce**
Could not figure out a reason, and how to reproduce it. It seems to be random. And it is also not related to the date. 

**Screenshots**
<img width="383" alt="Bildschirmfoto 2022-03-12 um 19 07 11" src="https://user-images.githubusercontent.com/19168364/158017446-9227e945-bb13-414b-be96-6eea24bd7be3.png">

**Expected behavior**
I expect to see first all featured jobs and then the rest. At the moment it is an uncontrolled mix. When creating new jobs it seems to work. But existing featured jobs behave weiredly. All jobs have the custom field _featured set to 1 in the database. 

**Isolating the problem (mark completed items with an [x]):**

I only use the 2022 theme and Wp Job Manger. Everything else is deactivated.

**WordPress Environment**
- WordPress Version: 5.9.2 and tested also on 5.8.3
- WP Job Manager Version: 1.35.2
- PHP Version: 8.0 and 7.4 same problem
- Other important details: Only Wp Job Manager activated

**Comment by Lens40** [comment]
What I noticed, when creating a new job as featured it is sticky at the top, when un-featuring it stays in the exact same position. Also I noticed that some of the jobs get a menu order of "-1" instead of "0" when I select to feature the job offer.

**Comment by Lens40** [comment]
I figured out that a job to be featured and sticky needs to have the _featured field set to "1" and the menu order set to "-1". It seems that in my case it does not change the menu order when updating a job. I will try to investigate further if it is maybe related to Polylang-Sync I use in production.

**Comment by Lens40** [comment]
Ok it is a PolylangPro issue, the menu_order value is not synced between the different languages. Means when creating a featured job only the parent job gets the -1 and the other synced translations stay at 0. When unfeaturing a job the opposite happens, the job which is updated switches to menu_order 0 which is correct but the others switch to -1. So suddenly unfeatured jobs are sticky and you wonder why...lets see if Polylang can help with that.

**Comment by Brbirk** [comment]
I have exactly the same problem, but not using polylang. Can someone Help with that?
