### ISSUE TITLE
"Invalid file type" error not shown in ajax upload.

### ISSUE THREAD

**Issue by aaronfc** [Automattic/WP-Job-Manager#2233]
**Describe the bug**
When a file with an invalid type is selected in a file input while ajax upload is enabled the file is ignored but no feedback is shown to the user.

**To Reproduce**
1. Go to submit a job.
2. Select an incorrect file (anything which is not an image) when uploading the company logo.

**Screenshots**
![Kapture 2022-04-28 at 10 23 41](https://user-images.githubusercontent.com/799065/165710260-ade490ad-7097-4a2f-9324-8ef8673131f6.gif)

**Expected behavior**
Some feedback should be shown to the user. Other similar errors like when a file is too big are displayed with a simple `window.alert`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.9.1
- WP Job Manager Version: 048658456ec891b89b66374c6d80a1f19113b58b
- PHP Version: 7.4.1
- Other important details: We have a tutorial explaining how to limit the file types allowed during upload [here](https://wpjobmanager.com/document/customize-allowed-file-upload-types/).

**Comment by Hastibe** [comment]
Thanks for creating this bug report, @aaronfc -- we've noticed this, too, and have had users confused by it, so having an error thrown for the user when they attempt to add an invalid file type as the logo would be helpful.
