### ISSUE TITLE
Search_category in url not filtering

### ISSUE THREAD

**Issue by V-Staykov** [Automattic/WP-Job-Manager#2237]
**Describe the bug**
So I've seen this has been an issue many times before, but I couldn't find a fix for my particular case. The issue is that the URL param search_category is not taken into account when filtering for the [jobs] page. No matter what slug is there, the page returns all jobs, like there is no param at all.

**To Reproduce**
1. Go to[https://itlrecruitment.ie/]( https://itlrecruitment.ie/)
2. Click on the categories drop down and select any category.
4. See all jobs no matter what was selected or what was manually put in the search_category param in the url.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 5.9.3
- WP Job Manager Version: 1.35.3
- PHP Version: 7.4.26
- Other important details:

**Comment by mikeyarce** [comment]
Closing this as it seems like more of a problem with with the site and not with the plugin.  If you need support for this plugin you can go to https://wpjobmanager.com/support/
