### ISSUE TITLE
Conflict with Gravity Forms

### ISSUE THREAD

**Issue by houghchris** [Automattic/WP-Job-Manager#2259]
With the latest version of Gravity Forms activated and the latest version of WP Jobs Manager activated, the "merge tag helper" functionality in Gravity Forms stops working.

**To Reproduce**
1. Activate Gravity Forms
2. Activate WP Jobs Manager
3. Goto Forms
4. Select any form
5. Goto Notifications
6. Select any Notification
7. Attempt to access the Merge Tag Helper Menu - it wont work. https://share.getcloudapp.com/Z4uAw8rA
8. Disable WP Jobs Manager and repeat steps 3 - 7
It will now work: https://share.getcloudapp.com/8Lu0JB8J

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.0
- WP Job Manager Version: 1.35.3
- PHP Version: 7.2.34
- Gravity Forms Version: 2.6.3

**Comment by GerritEMulder** [comment]
I am also having this exact same issue on one of the websites I manage.

**Comment by StefMattana** [comment]
Also reported on 5434048-zen

**Comment by mikeyarce** [comment]
I tested this out today on Gravity Forms 2.7.2 and did not see the issue.   Merge tags seem ok now! 
![fGjFPh.png](https://user-images.githubusercontent.com/3220162/222877533-0074d3ef-2b26-4808-82b5-3dc6265e170a.png)

Going to close this out as it no longer seems like an issue.
