### ISSUE TITLE
Youtube video not displaying on job listings

### ISSUE THREAD

**Issue by StefMattana** [Automattic/WP-Job-Manager#2276]
**Describe the bug**
Upon adding a video link upon posting a job, the video doesn't display. 

**To Reproduce**
- Add a Youtube video link to the job posting field.
- Upon submitting the job post, the `Watch video` doesn't appear in Twenty Seventeen and OceanWP
 themes, but it appears on Jobify. Upon clicking on the button, nothing happens: 
<img width="1333" alt="Screenshot 2022-06-21 at 15 01 44" src="https://user-images.githubusercontent.com/11662998/174818666-14ff3e72-43ff-4dd2-a119-46912442d942.png">
- Adding the same Youtube URL from the WP Job Manager dashboard doesn't make any difference. 

I tried to embed the Youtube video (whose bug got fixed on https://github.com/Automattic/WP-Job-Manager/issues/1718):
- Video preview does show in the Editor.
- The video doesn't play reporting a permission issue - I asked the user about that. 
<img width="975" alt="Screenshot 2022-06-21 at 15 04 00" src="https://user-images.githubusercontent.com/11662998/174819181-9c5448b4-76c6-4e86-bb29-341c4014598f.png">

I could not replicate it with other themes as switching themes broke my site multiple times (Critical errors)

**WordPress Environment**
- WordPress Version: 6.0
- WP Job Manager Version: 1.35.3
- Jobify v. 3.11.1

**Comment by mikeyarce** [comment]
I'm going to close this as it seems like an issue with Jobify and not with WPJM itself.
