### ISSUE TITLE
Salary Field uses USD as the default currency

### ISSUE THREAD

**Issue by jinnypark** [Automattic/WP-Job-Manager#2278]
**Describe the bug**

With the latest WPJM update (v.1.36.1), when the salary field is enabled, "USD / YEAR" is applied automatically on the job display page. There isn't a way to change this text elsewhere.

**To Reproduce**
1. Go to Job Listings > Settings > Job listings
2. Scroll down to 'Salary' and enable Job Salary
3. Post a job with a salary, entering a numerical value
4. See the job posting with USD applied 

**Screenshots**
<img width="749" alt="image" src="https://user-images.githubusercontent.com/15963276/174887931-d0d62d8f-c069-4db8-821c-28b8333077c4.png">

**Expected behavior**
I expected to be able to either select desired currency, or no currency at all.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.0
- WP Job Manager Version: 1.36.1
- PHP Version: 7.4

**Comment by jinnypark** [comment]
Related: https://github.com/Automattic/WP-Job-Manager/pull/2263

This filter works as a workaround: 
```
add_filter( 'wpjm_job_salary_currency', function( $currency ) {
  return 'GBP';
} );
```
<img width="845" alt="image" src="https://user-images.githubusercontent.com/15963276/174889252-9ae0a0a7-d67f-4794-93da-44355adc7718.png">

Replace `GBP` with any other currency of choice.

**Comment by tripflex** [comment]
This also forces output of some type of "CURRENCY / FREQUENCY" without any way of disabling that

**Comment by StefMattana** [comment]
Semi related, there seems to be a conflict with a third-party plugin too (WPJM Extra Fields), as the core salary filed keeps being displayed despite the option being toggled off: https://wordpress.org/support/topic/conflict-with-alternate-plugin-for-showing-salary/#post-15764240

I reported this on [#2263](https://github.com/Automattic/WP-Job-Manager/pull/2263), and I asked the user to report this to the plugin author, but I thought it was worth flagging it here too.

**Comment by StefMattana** [comment]
Upon testing 1.36.2 I found out that nothing gets displayed in my test site's job listings upon enabling the salary options. 

I filled the salary field both from the backend and the rontend, and also by adding simple numbers (es 1000) and numbers with specifications (1000/hours; 1000/year). Still, nothing got published. 

I am running JobifyVersion: 3.11.1 if that helps.

**Comment by bobmatyas** [comment]
Reported on 5322900-zd-woothemes

**Comment by bobmatyas** [comment]
The initial report says version 1.36.1, but it also appears in 1.36.2. Using the snippet shared above: https://github.com/Automattic/WP-Job-Manager/issues/2278#issuecomment-1162291454 doesn't allow you to remove the ` / YEAR` portion of the string.

**Comment by Gnodesign** [comment]
@bobmatyas  You could use this function to remove the "YEAR" but you will still have the slash...

```
add_filter( 'wpjm_job_salary_unit', function( $unit ) {
  return;
} );
```

**Comment by Gnodesign** [comment]
@onubrooks it would be great to add a filter for the whole job salary output: https://github.com/Automattic/WP-Job-Manager/blob/28d4d1c5dc47ccc05e5ae3182088aae82a018d31/wp-job-manager-template.php#L1311-L1327

**Comment by bobmatyas** [comment]
Another report on 5315507-zd-woothemes

Request to remove time (` / YEAR`) and only display currency.

**Comment by bobmatyas** [comment]
Another report: 5329779-zd-woothemes

**Comment by onubrooks** [comment]
> @onubrooks it would be great to add a filter for the whole job salary output:
> 
> https://github.com/Automattic/WP-Job-Manager/blob/28d4d1c5dc47ccc05e5ae3182088aae82a018d31/wp-job-manager-template.php#L1311-L1327

Hey @Gnodesign, we are working on a fix for this issue. CC: @fjorgemota

**Comment by StefMattana** [comment]
A user [on this forum thread](https://wordpress.org/support/topic/all-salaries-are-now-showing-usd-year-after-salary-how-to-remove/#post-15774350) suggested an edit to remove the duplicate USD field via CSS: 

```
li.salary {
display: none;
}
```

But it doesn't seem like work. I tested it and it would remove the entire field, while ideally it would remove only the currency. Any suggestions to get a quick fix on this and remove this field?

**Comment by bobmatyas** [comment]
There isn't a way to do it via just CSS.

**Comment by fjorgemota** [comment]
I started working today on PR #2285, which should help fix most of the annoyances reported here.

The pain point, for me, is that it does that by adding a bunch of new options to the user interface, which means that we shouldn't need to use such a big amount of filters anymore, but they should still work. This is a pain point because it means increased logic and more options to maintain, so I'm still thinking about the changes there.

I'll try to look a little bit more into this issue next week. In the meantime, I accept help with testing this [plugin build](https://github.com/Automattic/WP-Job-Manager/suites/7186879151/artifacts/286866927) (but seriously, **DON'T USE THIS PLUGIN BUILD IN PRODUCTION**) and also with the wording of the messages there. (feel free to comment directly on the PR with your suggestions) :) 

Thanks!

**Comment by StefMattana** [comment]
Another request for changing currency [here](https://wordpress.org/support/topic/change-currency-from-salary/).
