### ISSUE TITLE
Multiple locations search causes incorrect results to be returned

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#2287]
https://github.com/Automattic/WP-Job-Manager/pull/2261

If a user searches "Atlanta, GA" this is going to return any result in "GA" which is not what the user is looking for specifically.  This merged PR basically splits the location query into multiple queries now split by comma or spaces.

What about when someone wants to do an exact search?

The only solution I can think of for now is to add a filter to disable this functionality and use the original search handling as before, or coming up with a way to determine when the user wants to search as an "OR" type query vs an exact query.  It's naive to assume everyone wants it as an "OR" query, especially when locations sometimes need to be very specific.

https://wordpress.org/support/topic/locations-dropdown-no-longer-specific/#post-15799430

**I feel like this PR was merged very quickly without any discussion around it (implementation wise) even though it was a major change on how location queries are actually made.**

Especially because since 2017 there's only been 3 upvotes on wanting the actual feature:
https://github.com/Automattic/WP-Job-Manager/issues/1217

**Comment by Hastibe** [comment]
Found this thread after [also reporting](https://wordpress.org/support/topic/search-broken-in-1-36-1/) this new search behavior as a bug, as this breaks search on my site (searching for "MyCity, ST" now turns up all cities in the state), and appears to users as a bug as it breaks the functionality of the search function for my site and any site that has listings with locations formatted this way.

**Comment by Gnodesign** [comment]
Handling the "remote" search via the location field is also not the best way, most of the users don't even know they can search "remote". I would suggest to separate it from the location search functionality, having it as a checkbox would be way more user friendly.

**Comment by bobmatyas** [comment]
I can confirm that this behavior exists:

<img width="1155" alt="Screenshot on 2022-07-07 at 09-38-02" src="https://user-images.githubusercontent.com/45246438/177787356-87d19ad8-c788-449f-96bf-bb377202a192.png">

**Comment by tripflex** [comment]
For those finding this as being a problem, until can finish up the PR, use the WP Rollback plugin to revert back to 1.35.x version of the plugin where this issue does not exist

**Comment by bizanimesh** [comment]
5445039-zen
