### ISSUE TITLE
Delete logo files when jobs are deleted

### ISSUE THREAD

**Issue by tcfboulder** [Automattic/WP-Job-Manager#2289]
### Is your feature request related to a problem? Please describe

When jobs expire, we delete them. After a year or more, the logo files which aren't deleted, take up a lot of disk space. The suggestion from the support forum (https://wordpress.org/support/topic/logo-files-not-deleted-when-jobs-are-deleted/#post-15806664) was to delete them manually, but content editors do not have access to the filesystem for easy bulk deletion.

### Describe the solution you'd like

Automatic deletion of logos when jobs are deleted.

### Describe alternatives you've considered
Manual file deletion.

**Comment by StefMattana** [comment]
Adding to this thread that the job board mentioned by this user is sort of isolated from the rest of the site, meaning that the user is unable to access the Media Gallery to manually delete the logo files.

**Comment by burtrw** [comment]
Unfortunately we may accidentally delete an image that is being used elsewhere, so I don't think we can move forward with this one.
