### ISSUE TITLE
Notice on edit post form if WP_DEBUG_DISPLAY is TRUE

### ISSUE THREAD

**Issue by mbouckaert** [Automattic/WP-Job-Manager#2293]
**Describe the bug**
After update the plugin, and if i have WP_DEBUG_DISPLAY defined to true, i have a lot of notice for the new field on job page like this
<br /><b>Notice</b>:  Undefined index: value in <b>/var/www/html/wordpress/ensa-normandie/wp-content/plugins/wp-job-manager/includes/admin/class-wp-job-manager-writepanels.php</b> on line <b>405</b><br /> 
Including on form value

**To Reproduce**
WP_DEBUG_DISPLAY = true
Update WP Job Manager  plugin 1.35.3 to 1.36.2

**Screenshots**
https://i.postimg.cc/8kBfT9G9/Screenshot-2022-07-11-at-11-10-17-Modifier-Offre-d-emploi-Charg-d-tudes-charg-de-mission-Ch.png

**Expected behavior**
It should not display this warning on this form i guess

**WordPress Environment**
- WordPress Version: 5.9.3
- WP Job Manager Version: 1.36.2
- PHP Version: 7.3.31

**Comment by mikeyarce** [comment]
Closing as I'm no longer able to reproduce this issue.
