### ISSUE TITLE
"No file selected" when selecting a valid image as Company Logo in Job Listing

### ISSUE THREAD

**Issue by muffinpeace** [Automattic/WP-Job-Manager#2294]
**Describe the bug**

The text that reads "No file selected" stays that way even when selecting a valid image for the company logo.

**To Reproduce**
1. Go to the Post a Job front-end page.
2. Scroll down and select an image file for the Company Logo
3. Notice it still says "No file selected"

**Screenshots**
<img width="1161" alt="Screen Shot 2022-07-11 at 17 25 58" src="https://user-images.githubusercontent.com/78239985/178312154-d5ceecfa-275c-4d31-8fa5-742fb332dc59.png">

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.0
- WP Job Manager Version: 1.36.2 
- PHP Version: 7.4
- Other important details: This came initially through a support request: 5359728-zen

**Comment by alexsanford** [comment]
Thanks for the report!

Noting here that the file selector still works as expected, but the "No file selected" text (which is added by default from the browser) is misleading.

Setting priority to "Low" as the feature is working, but with poor UX.
