### ISSUE TITLE
Possible bug in `class-wp-job-manager-ajax.php`

### ISSUE THREAD

**Issue by StefMattana** [Automattic/WP-Job-Manager#2302]
A user [on the WPJM forum](https://wordpress.org/support/topic/bug-fix-ob_end_flush/) suggested the following: 

>I think after the line “$result[‘html’] = ob_get_clean();” adding a “ob_end_flush();” in class-wp-job-manager-ajax.php is recommended. I was having an issue with my ajax returning blank and this seemed to fix it.

>The ajax request wouldn’t return anything, seemed like the variable [‘html’] would crash the page if it was too long. If I added that after the ob area it fixed the issue though.

**Comment by StefMattana** [comment]
Upon checking with @merkushin, it looks like there might be some limitations (perhaps a memory limit) on the user's site, since [In code](https://github.com/Automattic/WP-Job-Manager/blob/trunk/includes/class-wp-job-manager-ajax.php#L266), it looks like we don't want to flush immediately, since we want [to filter the output](https://github.com/Automattic/WP-Job-Manager/blob/trunk/includes/class-wp-job-manager-ajax.php#L274) a bit later.

I'm going to ask the user about the example html that they flush there (to estimate its size) and about their limits in configuration.

**Comment by muffinpeace** [comment]
The user came back saying that there isn't anything that they're using a basic spinup-wp install. 

`The issue only happens when there are like 30+ listings to be returned (I manually played w/ the array size). That being said I used query monitor and the memory limit wasn’t near being reached/tried increasing it. Just seems like it’s unable to keep context when the buffer is large or something so it returns nothing.`

**Comment by tripflex** [comment]
I think he needs to check `output_buffering` in his PHP.INI configuration see what it's set at.  I've had numerous sites with large number of listings returned without issues.

`ob_end_flush()` makes me wonder if xdebug or something else is polluting or filling up the output buffer causing his issues.  What this does is basically send all the buffer output and then turn buffer output OFF

It is possible to use `ob_get_contents` to get the value of the buffer and then call `ob_end_flush()` after the filter, but to be completely honest, in the past 9+ years i've been dealing with WPJM I have yet to see this issue once ... makes me think it's an issue with this person's setup, or something else that is starting a buffer maybe from the filter call or something?

**Comment by mikeyarce** [comment]
Closing this as it seems like an issue only on one users site.
