### ISSUE TITLE
Submit Button on Filters page does not do anything

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#2304]
While working on the remote position handling on the listings page, I noticed that the submit button does not actually do anything.  

Search gets triggered when a change is made in one of the default fields, and the form is wrapped in a `<form>` element, but clicking on the submit button does nothing.

This can be replicated on the demo site:
https://demo.wpjobmanager.com/jobs/

**Comment by mikeyarce** [comment]
I can confirm that the Submit button does not appear to be doing anything
![wpjm-search-submit](https://user-images.githubusercontent.com/3220162/212186797-c8dded15-7d58-47db-a9a8-99f7a72f12d9.gif)
