### ISSUE TITLE
WP Job manager attempting to load fonts (from assets/fonts) that don't exist when viewing WP Admin

### ISSUE THREAD

**Issue by bressler1995** [Automattic/WP-Job-Manager#2308]
**Describe the bug**
There appears to be some fonts that this plugin is trying to load when viewing wordpress admin, these resources are causing 404 errors likewise.  This doesn't seem to break any plugin functionality but it does seem to slow down wordpress admin due to it attempting to load these.  The two console errors I get are as follows:

Failed to load resource: the server responded with a status of 404 (Not Found)  [job-manager.woff:1]
Failed to load resource: the server responded with a status of 404 (Not Found) [job-manager.ttf:1]

**To Reproduce**
1. Go to wordpress admin
2. View Browser Console
3. You should see some console errors unless there is something else wrong that I don't know about

The odd thing is that I see the font files its looking for on the github but those same font files have been omitted in final release (should be/wp-content/plugins/wp-job-manager/assets/font/)

I was able to resolve this with a temporary solution by downloading the said font files off this git and doing a 301 redirect and that seems to correct the issue with the console errors no longer showing.

Screenshot of problem: https://sccds.org/wp-content/uploads/2022/08/Screenshot-2022-08-16-164046.png
Screenshot of redirections and errors no longer showing https://sccds.org/wp-content/uploads/2022/08/Screenshot-2022-08-16-165337.png

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

I did try deactivating all plugin and switching themes but the issue still persists.

**WordPress Environment**
- WordPress Version: 6.0.1
- WP Job Manager Version: Version 1.36.2
- PHP Version: 7.4.3

**Comment by dugwood** [comment]
Hit this bug too. I've copied missing fonts for the time being.

From the wordpress directory, with bash, you can type:

```
cd wp-content/plugins/wp-job-manager/assets
mkdir font
for i in dist/font/job-manager*; do cp $i "font/job-manager.${i/*./}"; done
```

**Comment by mikeyarce** [comment]
I'm no longer seeing this issue so I'm going to close this out.  @dugwood or @carlofabyss if you still see this please let us know!
