### ISSUE TITLE
Elementor Header not working on archive pages

### ISSUE THREAD

**Issue by uttamxtendify** [Automattic/WP-Job-Manager#2311]
**Describe the bug**
I have a question related to archive wp job manager pages, Actually issue is that when I create a header using the Elementor pro plugin then my header is not showing on the archive wp job manager pages.
So, please let me know what’s the problem.
I have checked already it’s working with default WordPress archive pages, only the WP Job Manager archive page does not show elementor header.

**Screenshots**
https://prnt.sc/vXLMY7-e78l-
https://prnt.sc/TwrKZTRdAOKB

**WordPress Environment**
- WordPress Version: 6.0.1
- WP Job Manager Version: 1.37.0
- PHP Version: 7.4.9

**Comment by mikeyarce** [comment]
Can you give us some specific steps to reproduce this issue?  Can we reproduce it with just the regular Elementor plugin or do we need Elementor Pro?
