### ISSUE TITLE
Syntax error in wp-job-manager/wp-job-manager-template.php file

### ISSUE THREAD

**Issue by ludo-4e71** [Automattic/WP-Job-Manager#2326]
I don't know how to reproduce this bug and when it occurs precisely but I'm receiving alerts from WP saying :
Une erreur de type E_PARSE a été causée dans la ligne 845 du fichier /homepages/3/d237706169/htdocs/preprod.intwee-emploi.com/wp-content/plugins/wp-job-manager/wp-job-manager-template.php. Message d’erreur : syntax error, unexpected ';'

I checked my php errors logs and here is what i found :
[12-Sep-2022 13:16:55 UTC] **PHP Parse error:  syntax error, unexpected '?'** in /homepages/3/d237706169/htdocs/wp-content/plugins/wp-job-manager/**wp-job-manager-template.php on line 845**

Here is the line 845 of wp-job-manager/**wp-job-manager-template.php :
$job_location_address = get_post_meta( $post->ID, 'geolocation_formatted_address', true ) **??** '';

It should be like this I think :
$job_location_address = get_post_meta( $post->ID, 'geolocation_formatted_address', true ) **?** '';

- WordPress Version: 6.0.2
- WP Job Manager Version: 1.38.0
- PHP Version: 7.4

**Comment by mikeyarce** [comment]
Hi @ludo-4e71 - that's a strange error - are you still seeing it?  `??` is valid syntax:  https://www.tutorialspoint.com/php7/php7_coalescing_operator.htm

If you still see this problem let, please let us know!
