### ISSUE TITLE
Request Featured Add Ons: Multi Location for WP Job Manager

### ISSUE THREAD

**Issue by CodeIgniterID** [Automattic/WP-Job-Manager#2329]
Add Ons Multi-location marker in create single job and shows in single listing page (Inlclude shema job array location)

**Comment by dsecareanu** [comment]
Yes, this is needed for jobs that can be performed in multiple locations.

**Comment by bobmatyas** [comment]
Closing in favor of https://github.com/Automattic/WP-Job-Manager/issues/890
