### ISSUE TITLE
Listing Limit Option Not Working As Expected

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/WP-Job-Manager#2333]
**Describe the bug**

The job listing limit doesn't work as expected. If you enter 0, you are allowed to enter an unlimited number of jobs. This should either not allow you to enter any jobs or the field description should state that 0 means unlimited jobs are allowed.

**To Reproduce**
1. Add more than 2 test jobs.
2. Go to 'Settings > Job Submission'
3. Add a "Listing Limit" of 0.
4. Try adding another job, you are allowed to add an additional job.
5. Set the listing limit to 1.
6. Try adding another job. You should be redirected to the Jobs dashboard.
7. Remove the "Listing Limit" entirely -- you can add jobs.

**Expected behavior**

- I would expect that if I enter "0", I wouldn't be able to add additional jobs.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version:  v6.0.3
- WP Job Manager Version: v1.3.8
- PHP Version:  v8.1
- Other important details:

**Comment by mikeyarce** [comment]
Thanks @bobmatyas !  I can confirm that this is happening.  My question is - why would you want to have the Listing Limit be 0?

**Comment by bobmatyas** [comment]
@mikeyarce I don't think there was a use case that the bug reporter had where they needed to do that, it was just reported as an inconsistency. It seems the check in the PR would fix the issue.
