### ISSUE TITLE
Salary Placeholder isn't Translatable

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/WP-Job-Manager#2337]
**Describe the bug**

In the job submission form, the placeholder string for salary (`e.g. 20000`) isn't translatable.

**Expected behavior**

- Like other placeholders, this one should be translatable.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: v6.1
- WP Job Manager Version: v1.38.1
- PHP Version: v8.1
- Other important details:

**Comment by StefMattana** [comment]
[The user in this forum thread](https://wordpress.org/support/topic/comment-remplacer-e-g-20000-par-par-exemple-20000) is asking if you can share a CSS or JavaScript code to use as a workaround while we address this issue. Thanks!

**Comment by bobmatyas** [comment]
@StefMattana Unfortunately it's way outside of scope. To modify w/JS they'd have to write a script that targets the element and then changes the default value. We could provide them with that general instruction, but they'd have to figure out how to load such a script on that specific page.

For the CSS, the solution is likely similarly convoluted. It's been a while since I've tried to target the `placeholder` attribute, but I think what they'd want to do is try to hide the placeholder and then add their custom value using `::after`.
