### ISSUE TITLE
Add a Business Hours extension

### ISSUE THREAD

**Issue by nikkoboy** [Automattic/WP-Job-Manager#2340]
WP Job Manager is a great solution to increase the functionalities of a theme. I noticed however that several listing/directory themes that work with WP Job Manager, do not have a business hours module per se (just a simple text box to enter manually business hours). This seriously limits the way "job" or entries can be researched. For instance, which jobs/businesses are currently "Open".

Would you consider adding a “Business Hours” module in the future, as a paying extension of WP Job Manager? This would make a great addition to environments already operating with WP Job Manager. Something that would look like this business hours plugin: https://directorist.com/product/directorist-business-hours/

It would make sense that a plugin like WP Job Manager which principally works with directories themes, would offer that kind of feature.

Thanks for your consideration

**Comment by gikaragia** [comment]
Thank you for the suggestion! We will add this to our internal tracking system to consider it for the future.
