### ISSUE TITLE
How to only allow logged users to see the email in the "apply for job" button in the description?

### ISSUE THREAD

**Issue by CarlitoDevDreamer** [Automattic/WP-Job-Manager#2343]
I am having issues when uploading XML files.

When bulk upload XML files:
I want to know if someone can help me with this issues:
1-The applying button should redirect to the company website or email(The email that appears at the button "Apply for job" at the end of the description), instead, the button is working as internal apply...

2-In the description, shows the company website, how to hide it for non logged users?

3-At the end of the description, there is a button written Apply for job--> is there a way to only allow logged users to know the content of this button, and only see the email, only after they are logged in?

PS:I used a books XML as an example, because I dont have jobs posts XML file yet...

Many thanks!

**Comment by bobmatyas** [comment]
This can be accomplished using template overrides as explained here:

- https://wpjobmanager.com/document/customising-job-application-process/
- https://wpjobmanager.com/document/template-overrides/

We aren't able to provide specific code to accomplish this.

**Comment by tripflex** [comment]
You can also use the visibility addon to do this as well

**Comment by CarlitoDevDreamer** [comment]
I was able to resolve all three issues, and as soon as I have the opportunity, I will post a more detailed solution. Additionally, if you have any questions related to these three issues (or others), please feel free to reach out to me. I'll be happy to assist!

1-The applying button should redirect to the company website or email (The email that appears at the button "Apply for job" at the end of the description), instead, the button is working as internal apply...  (this is related to the WP-Job-Manager the WordPress theme I am using and some included plugins)
Here is a solution: https://wpjobmanager.com/document/customising-job-application-process/ as @bobmatyas said! Thanks @bobmatyas !
![image](https://github.com/Automattic/WP-Job-Manager/assets/31795844/7aaa5e70-af35-4d4c-940a-3b5053221032)


2-In the description, shows the company website, how to hide it for non logged users?

3-At the end of the description, there is a button written Apply for job--> is there a way to only allow logged users to know the content of this button, and only see the email, only after they are logged in?

2 AND 3  Are also related to the WP-Job-Manager plugin, the WordPress Theme I am using and also some theme included plugins.

(2 and 3) Here is a solution:

```
<div class="application">
        <?php if (is_user_logged_in()) : ?>
            <a class="application_button button" style="background-color: DodgerBlue;" href="<?php echo $application_href; ?>" target="_blank"><?php _e('Apply for job', 'wp-job-manager'); ?></a>
        <?php else : ?>

           //USE HERE THE LOGIN/REGISTER BUTTON (use some text like LOGIN/REGISTER FIRST)

</a>
</div>

<?php endif; ?>
    </div>
<?php endif; ?>
```

Also it is a good idea to use Child Themes to make your changes, since the theme provider might make some updates, and if you make changes directly to the parent theme, they will be overwritten, (I think that the same applies to plugins)
(When I started I didn't know about the child-themes, and I made all my customizations to the parent theme (noob))

4- (BONUS) Also if you bulk upload job listings using XML (with a plugin like All-Import) or JSON:

When an employer user uses your frontend to post a job, it will appear an APPLY BUTTON, but when you bulk upload jobs using XML or JSON (…) it will probably appear two APPLY buttons and one work and the other doesn’t, so I found a way to prevent this to happen, here is a solution:

```
if (
    $apply_type === 'external' && !empty($apply_url) ||
    $apply_type === 'with_email' && !empty($apply_email) ||
    $apply_type === 'call' ||
    $apply_type === 'internal'
) {
    //PUT HERE YOUR THEME'S DEFAULT BUTTON (FOR FRONTEND JOB POSTS)
}
?>
```

This code checks if the job post was made mannualy on the frontend, since if the employer fills any of the external, email, call or internal, the corresponded field will be NOT empty, and this means the post was made “mannualy”!

If you have any suggestions, improvements, let me know, since I am still learning how to code! (Also thanks to @tripflex )
