### ISSUE TITLE
Allow Custom Post Types to be Companies

### ISSUE THREAD

**Issue by vaccinemedia** [Automattic/WP-Job-Manager#2352]
I'm currently working on a site built entirely using CPTUI and ACF Pro and have custom post types for Events, Features, Company Profiles and Jobs and when adding content, jobs can be related to companies. Unfortunately, using ACF Frontend Admin Pro, the end user can only pay to add a single job post at a time.

It would be great if WP Job Manager jobs could be associated / related to a CPT set by the admin of the website. There could be a tab in the settings area called "Company Post Settings".

In this tab it could ask you to select:

- The custom post type to be used for the related company
- The custom meta field to be used for the company logo

When a user is adding a job post, they would have the option to enter either the default company details as they normally do **OR** they could have the option to select a company from a list which is populated by companies for which they are the author.

I have created this already using ACF Frontend Admin Pro BUT I don't have all the other useful features which this plugin then provides such as Job Alerts or Woocommerce products which can be used to pre-pay jobs at a discounted price.

**Comment by tripflex** [comment]
This sounds like a completely custom setup specific to your use case scenario.  There's numerous "company" plugins out there that create companies as separate post types, and they use some kind of identifier on the job listing itself to identify the association to the company.

I doubt this is something that would be added to the core plugin, as it's not as easy as just "adding a tab" there's a good bit of code that will be required for handling association plus integration with all the addon plugins.  As such, this can be handled through all the filters already available in WPJM.

I suggest looking at the other company plugins out there, you can even get a copy of mine for free and go through the source code to see how it's handled:

https://plugins.smyl.es/wp-company-manager/

BUT with that said, if you want to spend the time to write the code Pull Requests are always welcome!

**Comment by vaccinemedia** [comment]
Your plugin looks promising - can ACF fields be added to the organisations post type?

**Comment by vaccinemedia** [comment]
@tripflex it looks like your beta plugin may do the trick. What I'm after isn't too complex. What I have made so far is all ACF based.

Here's the job post:
https://friendly-pasteur.77-68-35-227.plesk.page/jobs/dolorem-natus-deserunt-dolorum-ducimus-sit/

and here is the related company profile:
https://friendly-pasteur.77-68-35-227.plesk.page/prolific-profiles/zeus-360-virtual-tours/

Using ACF Frontend Admin Pro users are able to add jobs and relate them to company profiles which they are the author of and then pay for them. The only bits missing are redeemable multi-buy jobs and email alerts which are provided by WP Job Manager. So having WP Job Manager installed plus your plugin / add-on would negate the need for my existing job and company CPTs and give me multi-buy and job alerts.

I'm able to add the extra company fields to your company CPT using ACF. What I was describing in my original post was kind of like a cut down version of your add-on but where you select which post type you want to use as the company CPT whereas yours adds the CPT for you instead.

IF your add-on did not have any meta fields at all on the company CPT and allowed you to add just the ones you want / need using ACF that would be spot on :) It would just need a way of showing the related jobs on the company page and the company link on the job page. I'm using Elementor for the front end so maybe a shortcode could work for this?

**Comment by gikaragia** [comment]
Thank you for the suggestion. Introducing company profiles is one of the potential projects we are currently looking into.
