### ISSUE TITLE
Add new location parameters and submit to Google Structured data

### ISSUE THREAD

**Issue by iamtayyabrashid** [Automattic/WP-Job-Manager#2355]
Hello, i write to discuss a very native issue in WPJM.
I got the following errors in Google structured data, as i am not using geocoding. Google MAP API
Missing field 'postalCode' (optional)
Missing field 'streetAddress' (optional)
Missing field 'addressLocality' (optional)
Missing field 'addressCountry' (optional)
Missing field 'addressRegion' (optional)

My question is if create and add these fields by using WPJM-extra filed plugin. How can I add these fields in Google structured data?

**Comment by tripflex** [comment]
These values are automatically generated by geolocation handling, and if using a plugin to add them you must make sure they do NOT have a prepended underscore when saved to the listing

**Comment by tripflex** [comment]
I think I misunderstood your question with my first reply, you need to use a filter to add these:

https://github.com/Automattic/WP-Job-Manager/blob/95f3d6742d90b3a9c028bd53010e2d3760fc1d06/wp-job-manager-template.php#L441
