### ISSUE TITLE
Allow HTML tags in Main Responsibilities field

### ISSUE THREAD

**Issue by Delcasart** [Automattic/WP-Job-Manager#2366]
Main Resposibilities field is usually a list. It would be very helpful if bullets and other html formatting tags are available.

**Comment by mikeyarce** [comment]
Hi @Delcasart - can you tell us more about what you mean by "Main Responsabilities"?  I don't see that field on the "Post a Job" page by default.  I do see the "Description" field which does have HTML formatting and lists available.

Thanks for your help!
