### ISSUE TITLE
Job Listings Page not loading

### ISSUE THREAD

**Issue by digitalinfluence** [Automattic/WP-Job-Manager#2368]
Hello, the Job listings page is not loading any jobs.
**Screenshot attached.

**To Reproduce**
1. Go to digitalinfluence.app (create an account)
2. Click on 'Jobs
3. See error

**Expected behavior**
The job listings should appear (there are numerous listings)
<img width="1623" alt="Screenshot 2023-02-17 at 9 06 11 AM" src="https://user-images.githubusercontent.com/125671386/219677769-01c5a64d-fd64-46f8-b4b0-03381cec6918.png">

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active. - I am using BuddyBoss
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by mikeyarce** [comment]
Hi @digitalinfluence - this seems like a problem with your site in particular and not a bug with our code.  What I would suggest is going to the free support forums here:  https://wordpress.org/support/plugin/wp-job-manager/

If you have a paid license you can go get support here: https://wpjobmanager.com/support/
