### ISSUE TITLE
Validate job fields through wp-admin

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/WP-Job-Manager#2369]
If you use the front-end `[submit_job_form]` form to submit jobs, you get some form validation that makes sure:
- Required fields are filled in
- Email / URL is valid
- Category / Type are populated

When you fill out the job listing on the `wp-admin` side, the fields do not get validated.  
I think we at least need parity with both experiences.

People run into problems with using just the `wp-admin` experience, and we even recommend only using the frontend job submission in our documentation:
![Screenshot 2023-02-23 at 2 27 35 PM](https://user-images.githubusercontent.com/3220162/221044960-2bb211e7-c4fe-4adf-8602-4efe1b7c14c1.png)

**Comment by tripflex** [comment]
I think the idea here is that admin area is meant for management and editing where an admin may not want validation if they need to be able to remove a field from having a value

**Comment by mikeyarce** [comment]
Good point @tripflex - I think removing a field entirely would be fine, what I'd like to do is more validate to make sure if a field is filled in, that it's a valid Email/URL, etc.  Do you think that makes sense?

**Comment by tripflex** [comment]
Makes sense but just keep in mind that users may not always want that.  Especially if they are using the field in some kind of custom way.  Adding something like this could cause more issues than it solves. Just keep that in mind, like how validation is done for application field.

**Comment by gikaragia** [comment]
Hmm, I am also leaning towards not restricting users in admin in any way, especially considering that old sites might already use these fields in unpredicted ways that can possibly fail if we add any validation.

I agree that there is value in unifying the two job submission experiences somehow and this seems like a step towards that but maybe it would be better to handle it as part of a bigger project where we examine every use case.
