### ISSUE TITLE
Select2 overlap over fields in Job Submission form

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/WP-Job-Manager#2370]
**Describe the bug**
When you go submit a Job, the Select2 multi-select form overlaps the field when going below and has too much margin when going above.

Below:
![tJcXDP.png](https://user-images.githubusercontent.com/3220162/222562710-f8a50ced-f62f-4088-a417-bca558e32ec5.png)

Above:
![VFL3eN.png](https://user-images.githubusercontent.com/3220162/222563543-ef67eefd-0334-457e-8ce8-faa245127c26.png)

I tried with about 5 different themes and it always does this regardless of what theme it is.

**To Reproduce**
1. Go to the Job Submission page
2. Click on Job Type
3. See the dropdown overlap the input field

**Edit:  This only happens when logged in and you have the Admin bar present.**

**Comment by tripflex** [comment]
Are you logged in as admin with admin bar showing?

**Comment by mikeyarce** [comment]
@tripflex Yup!  Good catch, I'll edit the report to mention it only happens when the Admin bar is present.

**Comment by tripflex** [comment]
https://gist.github.com/tripflex/7f4a10fb27c7e8c95c86010f93ac250b

Yup been an issue for a while also seems to depend on the theme as well

**Comment by gikaragia** [comment]
This is now fixed
