### ISSUE TITLE
Improve licensing page experience for activation of multiple licenses.

### ISSUE THREAD

**Issue by aaronfc** [Automattic/WP-Job-Manager#2375]
As part of the Re-engaging Customers project we want to improve the experience for WPJM users who have purchased a bundle with multiple addons.

Currently the experience is quite cumbersome, by needing to activate each of the licenses individually.

Hopefully a simple "single save button" would be feasible and make it easier for the users.

We depend on 210-gh-Automattic/wpjobmanager.com for making a single request in bulk.

Design proposal: p6r3EZ-1lK-p2

Design i2: p6r3EZ-1mQ-p2

**Success Criteria**:
- [x] On the licensing page multiple licenses can be activated by a single "save" button.
- [x] On error the error message from server is shown (including link to renew or purchase licenses).
- [x] `invalid_product` errors are ignored (not shown) unless there wasn't any success
- [x] WP.com managed licenses management is still disabled. More context: here (p1680262423094569-slack-C04URKMQHA9) and [here](https://github.com/Automattic/WP-Job-Manager/pull/2332).

**Comment by aaronfc** [comment]
I am adding the Needs Design label in case we want to improve it more than just the single save button.

**Comment by aaronfc** [comment]
We will handle listing the "deactivated" addons in a separate ticket.

**Comment by aaronfc** [comment]
New design iteration here: https://wpjobmanagerp2.wordpress.com/2023/03/31/licensing-for-wpjm-add-ons-i2/

We might want to extract the "core bundled-view" as a separate task. Still discussing on it.

**Comment by aaronfc** [comment]
The API for bulk license activation is being implemented in 221-gh-Automattic/wpjobmanager.com

@fjorgemota these are error scenarios you will need to take into account:
- If non of the activations is successful we should show an error to inform that the "license is invalid".
- If it's not the above scenario we must show the error message for each unsuccessful plugin.

I am happy to discuss more about these.

**Comment by fjorgemota** [comment]
@aaronfc  

>  On error the error message from server is shown (including link to renew or purchase licenses).

Shouldn't the server return this instead?

> invalid_product errors are ignored (not shown) unless there wasn't any success

Is there a risk of this coming up from the server given the list of licensed plugins? I don't think so. :thinking:

**Comment by aaronfc** [comment]
> Shouldn't the server return this instead?

It does. The server is returning the error. The point was to "show" the error that is coming from the server.

> invalid_product errors are ignored (not shown) unless there wasn't any success

Yes, you could put an invalid license (one that is not supported by any of the products you sent in the api call). In that case we must show the errors. In case of at least **one** success, then the error shouldn't be shown. Since the license key could be valid only for one of all the available products.

I am happy to slack about this if something is not clear :)
