### ISSUE TITLE
Send email to admins when license is inactive.

### ISSUE THREAD

**Issue by aaronfc** [Automattic/WP-Job-Manager#2377]
As part of the Re-engaging Customers project we want to explore the idea of sending an email to the admin owner (using the same email mechanism is in place for "Forgot your password" and similar system emails) to let them know about their license expiring soon or being already expired.

First step would be investigating our possibilities here in terms of destination email and email delivery mechanism.
Next we need to land very well what email we want to send and when.

**Success criteria**:
- [ ] We have compiled our options in terms of email recipients and email mechanisms.
- [ ] We have discusses about the different triggers and texts we can use.
- [ ] We have implemented the emails we decided in the previous success criteria.
- [ ] We can test and receive the email replicating the expected scenario.

**Comment by interlineae** [comment]
See discussion at https://github.com/Automattic/sensei-pro/issues/2212

**Comment by interlineae** [comment]
Closing per the discussion above.
