### ISSUE TITLE
Revamp unlicensed notices design.

### ISSUE THREAD

**Issue by aaronfc** [Automattic/WP-Job-Manager#2378]
During the Re-engaging Customers project it was raised that the current notices when unlicensed are quite old-fashioned and messy.

The idea would be to revamp the UI as well as the UX (consolidating multiple of them in a single one, for example)

This is how it looks currently:
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/799065/231517510-11663e67-daef-492d-8b88-6bc0b0f7ceba.png">

After #2383 and #2382 we should be in a good place to do something better with these.

**Comment by Luchadores** [comment]
Hey @aaronfc, the idea of using the new notices it's perfect. This is from the link you have shared [here](https://github.com/Automattic/WP-Job-Manager/issues/2382).

**Comment by interlineae** [comment]
(Edit: The 'hide notice' button won't display alongside the dismissal 'x'.)

@aaronfc I have a change readyish that updates the notice styles to use the new `render_notice` method:

![updated-notice-styling](https://user-images.githubusercontent.com/2500940/233645418-f89eea6e-e0cb-4853-a7bd-9213abc538ed.png)

I'm wondering if I should submit the PR for this, or if we do want to go ahead with a grouped 'update all the things' notice, per:

![227242218-857a23c6-ef11-4ec3-8377-956484aa7cdd](https://user-images.githubusercontent.com/2500940/233645676-1d734acb-9d7e-4d08-bf41-9d758f6984b6.png)

I'm under the impression that this will potentially require a new `render_grouped_notices` method as we'll have no only different styling, but different information presented (if we stick to the design). Thoughts?

**Comment by aaronfc** [comment]
> @aaronfc I have a change readyish that updates the notice styles to use the new render_notice method:

I think we would replace the "hide notice" button with the "X" dismissal button.

> I'm wondering if I should submit the PR for this, or if we do want to go ahead with a grouped 'update all the things' notice.

I am ok with both approaches. Using the new style is already an improvement. But if we want to go ahead and merge them together it would be even nicer :)

> I'm under the impression that this will potentially require a new render_grouped_notices method as we'll have no only different styling, but different information presented (if we stick to the design). Thoughts?

Not sure about this one. We are already using it for the addon update notices. The thing is that we can just call the existing `render` method passing the `extra_details` attribute which accepts some HTML. We would just need to generate that HTML.

Anyway, since we are trying to close the feature branches if you work on this do not merge to the feature branch yet :)
