### ISSUE TITLE
Notices for out of date WPJM addons.

### ISSUE THREAD

**Issue by aaronfc** [Automattic/WP-Job-Manager#2379]
We want to add new notices when WPJM addons are out of date.

We would like those notices to be consolidated (if multiple) since there are users with many addons at the same time.

**Success Criteria**:
- [x] When a user has an out of date addon gets a notification.
- [x] When shown multiple notifications they consolidate in a good and friendly way.
- [x] We show an "Update" action pointing to plugins page ~(licensed addons) or licensing page (unlicensed addons)~

**Comment by aaronfc** [comment]
@Luchadores we might need help with designing this :)

**Comment by Luchadores** [comment]
Hello @aaronfc and friends 👋 I took a look at this and I was wondering if we could make them look similar to the Sensei ones, so we get some consistency going. 

Here's what I have for you:
![image](https://user-images.githubusercontent.com/10038976/227241821-4994c5e3-4445-417f-8a72-dc8880bc4986.png)

![image](https://user-images.githubusercontent.com/10038976/227242218-857a23c6-ef11-4ec3-8377-956484aa7cdd.png)

![image](https://user-images.githubusercontent.com/10038976/227242259-c21214b1-82c3-47d4-80de-853c06305344.png)

Not sure if I missed anything, so do let me know. Figma file is [here](https://www.figma.com/file/NfoFCYVLE46Wu8mEyLQhm4/WP-Job-Manager-%2F-Notices?node-id=20018242%3A334&t=3WXeJp4h2PPPBgUg-1). 

@burtrw

**Comment by aaronfc** [comment]
It's looking great! I really like the consolidated view :)

Not sure if we will be able to put the addons and links for each version in the notice, but I haven't looked into that yet.
This gives us a starting point to where we want to be – awesome! <3

**Comment by aaronfc** [comment]
I have created a [new ticket](https://github.com/Automattic/WP-Job-Manager/issues/2382) to adapt to the new style. In the current ticket I will limit myself to adding the new notices for the outdated WPJM addons in the best possible way with the existing design.
