### ISSUE TITLE
jm-ajax/get_listings/ loads extremely slow when more jobs are there

### ISSUE THREAD

**Issue by css1323** [Automattic/WP-Job-Manager#2386]
Hello,

The listings are extremely slow when there are more jobs, i have wp fastest cache premium everything works fine and loads within 2 seconds except the listings.

Can you please improve the coding or speed or add another hook so it works faster?  i have installed index mysql for speed also and have cleared all metavalues 

Here is the link: check the waterfall : https://gtmetrix.com/reports/turn-to.com/7STlz3vK/

https://turn-to.com/jm-ajax/get_listings/ this link takes almost 20 seconds to load ajax call. Kindly make it superfast or suggest a solution so i can speed up the post requests.

**Comment by gikaragia** [comment]
Is this still an issue @css1323? I can see now that your link is loading almost instantly now.

If you are still having issues, `get_listings` uses `WP_Query` so if you want to optimize it you should follow the same steps as in every other WP query. WPJM provides various filters that you can use, you can have a look in `get_job_listings` for more details.

If you seek support, you should use our support page which can be found [here](https://wpjobmanager.com/support/).

**Comment by css1323** [comment]
It is still an issue, the links are loading instantly because i have
formatted it to load only the starting 2000 jobs at the max with coding.
The issue is still ON. i wish there are breaks in the job listings so once
it loads 1000 jobs max it is given a break, than asked to load more? Than
another 1000 appear. That way it is optimized every time ajax is fired

**Comment by gikaragia** [comment]
Sounds to me @css1323 that you want to use the `per_page` argument in the `[jobs]` shortcode. If for example, you define your shortcode as 
```
[jobs per_page="100"]
```
only 100 jobs will get loaded and visitors will need to click 'Load more listings' to retrieve more jobs.

In any case, this is the repository of the free plugin and it is used to register bugs or enhancement requests only. If you need more help you should go through our support channels which can be found [here](https://wpjobmanager.com/support/).

**Comment by css1323** [comment]
No No No per page i understand, per page it is showing 25 jobs only on my
side but when i search for a keyword it goes inside all data and than
loads, sometimes it takes around 25 seconds to load. It searches all the
jobs and than load results. With ajax it is going to create problems on the
database load.

**Comment by gikaragia** [comment]
In that case, it seems to be an issue with a huge metadata table and WordPress and not with WP Job Manager specifically. Job Manager uses WP_Query for the AJAX calls.

**Comment by css1323** [comment]
I understand your point, but to make the wordpress platform faster, i am
here providing you an idea that might work wonders. First 2000 or 1000
results load if the results are more than 100K and then on click another
2000 or 1000 job slot loads, that way the wordpress load is less and the
results are perfectly accurate. I am just helping you on submitting my
logic, i may be wrong, but please consider this feature, it will be a
massive win-win situation with ajax firing for more jobs. It is wordpress i
know but we can do better logically to get the results we want, i am not
talking about myself particularly. if you guys can do it that would be
great, if you can atleast consider my idea than good, if it is something
out of control for wp job manager developers than i totally understand and
will not force you in doing so but i genuinely think this feature is
required,

Also, to geocode the addresses there is no other option other than google,
please consider some open source platforms so we can use this method.
Google is too costly when you go beyond their limits.





*-Best Regards,Shikhar ShahTech EntrepreneurMobile: +91-9727069323*
*Whatsapp: * *https://wa.me/919727069323* <https://wa.me/919727069323>



*www.findcss.com <https://www.findcss.com>Email: ***@***.***
***@***.***>*
