### ISSUE TITLE
Feature Request: Simple Paid Listings - Different pricing based off form field value

### ISSUE THREAD

**Issue by blainerobison** [Automattic/WP-Job-Manager#240]
I'd like the ability to change the listing cost depending on the value of a form field. 

For example, different pricing can be defined depending on which job category is selected.

My particular case is setting member/non-member pricing. If a user provides certain information within a custom field, I would like to charge a different price than what's defined as the default listing cost.

As of now, it doesn't appear there are any available filters to modify the charge amount. I'm using Stripe as the gateway and it looks like this is the method where the amount is being set for the charge.

class-wp-job-manager-spl-stripe.php

``` php
public function pay_for_listing( $job_id ) {
    ... array(
        'amount' => number_format( get_option( 'job_manager_spl_listing_cost' ), 2, '.', '' ) * 100,
    )
    ...
}
```

**Comment by Xavier1610** [comment]
Hi,
I'm looking for the exact same functionnality, but I didn't find how to do it. If it exists now how should I do to use it ? 
Thanks a lot for your help !

**Comment by askwpgirl** [comment]
Has this filter been added?

**Comment by alexsanford** [comment]
Yes, there is a filter `wp_job_manager_spl_get_job_listing_cost` in Simple Paid Listings:

```php
	/**
	 * Get cost of the job listing.
	 *
	 * @return float
	 */
	public static function get_job_listing_cost() {
		$job_listing_cost = 0;
		$job_listing_cost_str = get_option( 'job_manager_spl_listing_cost', 0 );
		if ( ! empty( $job_listing_cost_str ) ) {
			$job_listing_cost = (float) $job_listing_cost_str;
		}

		return apply_filters( 'wp_job_manager_spl_get_job_listing_cost', number_format( $job_listing_cost, 2, '.', '' ) );
	}
```
