### ISSUE TITLE
Icons broken in 1.40.0

### ISSUE THREAD

**Issue by Hastibe** [Automattic/WP-Job-Manager#2415]
**Describe the bug**
WP Job Manager icons used on the back-end and front-end are broken (appearing as question mark in browser) after updating to 1.40.0

**To Reproduce**
1. Update WP Job Manager to 1.40.0
2. Look at icons on back-end WP Job Manager pages or front-end jobs dashboard or job posts.

**Screenshots**
See in [this thread](https://wordpress.org/support/topic/icons-missing-after-update-to-1-40-0/) started on the wordpress.org support forum for the plugin.

**Comment by ptrkx747** [comment]
Same problem here
