### ISSUE TITLE
Public (non logged in) users do not have access to resumes, despite settings

### ISSUE THREAD

**Issue by apolloventures** [Automattic/WP-Job-Manager#2419]
**The issue:**

When I do a resume search as a non logged in user, I get an access denied error in search results.

In WP Admin > Resumes > Settings > Resume Visibility tab, for all text areas, I have “Anonymous (users not logged in)” and “All Users (any logged in user)” setup. I cleared Breeze cache as well.

My configuration is shown in the screenshot below:

![visibility](https://github.com/Automattic/WP-Job-Manager/assets/133379785/a848a8b4-9677-443f-8376-4ca107f14cb1)

Note: I discovered that if I delete the tags shown in the screenshot and have all blank, that it works for non logged in users. It is strange though — I believe it should work as I had it configured before as I included the non logged in user option.

Maybe the WPJM Visibility plugin is overriding the core WPJM functionality and causing an issue?

**Expected:**

In the scenario where in WP Admin > Resumes > Settings > Resume Visibility tab, for all text areas, I have “Anonymous (users not logged in)” and “All Users (any logged in user)” setup, I expect to allow users of these types to see the resume object(s) without an access denied error.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x ] This bug happens with a default WordPress theme active.
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.2
- WP Job Manager Version: 1.40.0
- PHP Version: PHP 8.2
- Other important details: WP Job Manager - Visibility, Version 1.6.0

**Comment by gikaragia** [comment]
Hello @apolloventures it seems like these roles (Anonymous and All users) are something that is added by another plugin (WPJM Visibility?) and it is an issue with the plugin itself. You will need to contact the plugin developer. I am going to close the issue as this is the repository for the WPJM free plugin.
