### ISSUE TITLE
Search in admin not working as expected. Results missing.

### ISSUE THREAD

**Issue by D0mcode** [Automattic/WP-Job-Manager#2423]
**Describe the bug**
The search feature from the admin is not giving the expected number of search results since version 1.40. Everything is good when rolling back to v1.39

**To Reproduce**
1. In the admin area, click on **Job listings** in the left menu
2. Enter a search string in the search field and click **Search Jobs**
3. Count the number of results
4. Clear the search and sort all jobs by alphabetical order of **Position**
5. Scroll down to your searched string and manually count the expected result

**Screen shots**
5 results when using the search:
<img width="978" alt="Capture d’écran, le 2023-05-17 à 09 47 51" src="https://github.com/Automattic/WP-Job-Manager/assets/33611149/f760716b-81ae-4ee1-96d0-d35a97627ed9">

More than 5 results when sorting and checking manually:
<img width="963" alt="Capture d’écran, le 2023-05-17 à 09 50 16" src="https://github.com/Automattic/WP-Job-Manager/assets/33611149/5fc46dcb-e3ed-4715-8a83-1ca097a1068c">

**Expected behavior**

Search results should include all instances of the string, as v1.39 did.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.2.1
- WP Job Manager Version: 1.40.1
- PHP Version: 8.1.18
- Other important details: currently 1037 jobs in database

**Comment by TwitchySloth** [comment]
I'm experiencing the identical problem. Users from three websites all complaining.

**Comment by ibiza69** [comment]
We have 4 websites experiencing same problem searching for a job position, and too searching for filled possitions or featured ones, it always doesn´t give any result after this last update. Thank you.

**Comment by todd-droid** [comment]
We too had this problem but it was only with expired jobs. We implemented a workaround by unchecking 'Hide Expired Positions in Job Archives/Search' under Settings > Job Listings. Before 1.40, this box was checked, but expired jobs could still be searched in the admin dashboard.

**Comment by StefMattana** [comment]
Reporting [a forum thread related](https://wordpress.org/support/topic/covered-positions-search-engine-does-not-work).

**Comment by gikaragia** [comment]
Hello @D0mcode, can you confirm that this issue happens only to expired or filled jobs for you too? If that is the case we have prepared a fix in #2431. As we currently don't have an ETA of when this is going to be released, in the meantime, you can use the following snippet to prevent the issue from happening:

```
function remove_filled_expired_filtering( $query ) {
	if ( is_admin() ) {
		remove_filter( 'parse_query', [ WP_Job_Manager_Post_Types::instance(), 'maybe_hide_filled_expired_job_listings_from_search' ] );
	}

	return $query;
}

add_filter( 'parse_query', 'remove_filled_expired_filtering', 9);
```

The fix will be included in the next release so we can remove the snippet after upgrading.

**Comment by ibiza69** [comment]
> Hello @D0mcode, can you confirm that this issue happens only to expired or filled jobs for you too? If that is the case we have prepared a fix in #2431. As we currently don't have an ETA of when this is going to be released, in the meantime, you can use the following snippet to prevent the issue from happening:
> 
> ```
> function remove_filled_expired_filtering( $query ) {
> 	if ( is_admin() ) {
> 		remove_filter( 'parse_query', [ WP_Job_Manager_Post_Types::instance(), 'maybe_hide_filled_expired_job_listings_from_search' ] );
> 	}
> 
> 	return $query;
> }
> 
> add_filter( 'parse_query', 'remove_filled_expired_filtering', 9);
> ```
> 
> The fix will be included in the next release so we can remove the snippet after upgrading.

Thanks, this fixed the situation!

**Comment by gikaragia** [comment]
It seems like this issue might be causing performance issues in some of the sites. If you are experiencing such issues you can use the following snippet which is similar to the previous one but disables the offending code entirely:

```
function remove_filled_expired_filtering( $query ) {
	remove_filter( 'parse_query', [ WP_Job_Manager_Post_Types::instance(), 'maybe_hide_filled_expired_job_listings_from_search' ] );
}

add_filter( 'parse_query', 'remove_filled_expired_filtering', 9);
```

We are working on a fix and we will release it once it's ready.

**Comment by ibiza69** [comment]
> It seems like this issue might be causing performance issues in some of the sites. If you are experiencing such issues you can use the following snippet which is similar to the previous one but disables the offending code entirely:
> 
> ```
> function remove_filled_expired_filtering( $query ) {
> 	remove_filter( 'parse_query', [ WP_Job_Manager_Post_Types::instance(), 'maybe_hide_filled_expired_job_listings_from_search' ] );
> }
> 
> add_filter( 'parse_query', 'remove_filled_expired_filtering', 9);
> ```
> 
> We are working on a fix and we will release it once it's ready.

Thank you once more!!

**Comment by gikaragia** [comment]
The fix for this issue is included in the latest release.
