### ISSUE TITLE
Adding an additional image upload

### ISSUE THREAD

**Issue by Lane689** [Automattic/WP-Job-Manager#2425]
Hi all, 
I want to add an additional image to `[submit_job_form]` shortcode. I followed a code on this page: https://wpjobmanager.com/document/editing-job-submission-fields/ to edit job submission fields and what I tried is edit a `wp-job-manager/includes/forms/class-wp-job-manager-form-submit-job.php` file. 

When I added this code: 
```
function custom_img_field( $fields ) {
	  $fields['job']['job_img'] = array(
		'label'       => __( 'Image', 'wp-job-manager' ),
		'type'        => 'image',  //or 'type'        => 'text',
		'required'    => false,
		//'placeholder' => 'e.g. 20000',
		'priority'    => 8
	  );
	  return $fields;
	}
add_filter( 'submit_job_form_fields', [$this, 'custom_img_field'] );
```

When I try that code I got this error: 
![image](https://github.com/Automattic/WP-Job-Manager/assets/88096949/aacb0e0a-ed36-4310-99e8-07b487137ff5)

What mistake do I made?

**Comment by gikaragia** [comment]
Hey @Lane689, the GitHub repository is used to submit enhancement requests or bugs. Please use our [support page](https://wpjobmanager.com/support/) if you need help.

With that said, I am not sure what `job_img` refers to. It isn't used in WPJM code.
