### ISSUE TITLE
Job Application URL to open in a new window

### ISSUE THREAD

**Issue by StefMattana** [Automattic/WP-Job-Manager#2435]
Per the suggestion of a user on a [forum thread](https://wordpress.org/support/topic/job-application-url-to-open-in-a-new-window/): 

> I have a client who would like to use this plugin and wants to send applicants to an application in their own system and I would love to have the link to open in a new window rather than leave the website and the job they are applying for.

Links don't open in a new tab by default [if the application method is URL](https://github.com/Automattic/WP-Job-Manager/blob/trunk/templates/job-application-url.php), it'd be nice to have the option to choose in the settings.

**Comment by gikaragia** [comment]
Although it makes sense and I think that it should be opening the links in a new tab by default, I am thinking that it isn't worth it to change it now as it will change the behavior of existing sites. And as long as users can always override the template, a setting isn't useful either.
