### ISSUE TITLE
Create promote and deactivate buttons on job listings opening modals

### ISSUE THREAD

**Issue by renatho** [Automattic/WP-Job-Manager#2438]
- Add promote and deactivate buttons to Job listing. Design: 6yDn5aNJyeJ4Xgp0lcDjDc-fi-20018640_4432
- Create the promote modal. Design: 6yDn5aNJyeJ4Xgp0lcDjDc-fi-20018663_2142
- Create the promotion deactivation modal. Design: 6yDn5aNJyeJ4Xgp0lcDjDc-fi-20018640_4216

This issue doesn't include the integration of the promote and deactivate buttons from the modals.

### Success Criteria

- [x] Clicking on promote button opens a modal with more details and a button to promote.
- [x] We have a way to set the link we'll have in the promote button of the modal for every job (currently, it can be a static link with the job ID in the query string as an example).
- [x] Clicking on deactivate button opens a confirmation modal that user can skip or proceed.
- [x] We have a way to set the link we'll have in the deactivate button of the modal for every job (currently, it can be a static link with the job ID in the query string as an example).

**Comment by mikeyarce** [comment]
PR: https://github.com/Automattic/WP-Job-Manager/pull/2459

**Comment by renatho** [comment]
https://github.com/Automattic/WP-Job-Manager/pull/2460
