### ISSUE TITLE
Integrate deactivate button on Job Listing

### ISSUE THREAD

**Issue by renatho** [Automattic/WP-Job-Manager#2440]
- When a job is promoted, we should display the deactivate button instead of Promote button.
- When clicking on the button, it should display a [modal](https://github.com/Automattic/WP-Job-Manager/issues/2438) asking for confirmation.
- After user confirmation in the modal, it should mark the job as not promoted (remove post meta that represents that it's promoted).
- Restrict this feature with a capability.

### Success Criteria

- [ ] Promote button doesn't show up in the Job Listing when a Job is promoted.
- [ ] Deactivate button shows up in the Job Listing when a Job is promoted.
- [ ] A modal with confirmation shows up when clicking on the deactivate button and we can interact with it.
- [ ] When users confirm the prompt, job is not promoted anymore.
- [x] #2494

**Comment by Hastibe** [comment]
Could you clarify what you mean by "promote" / "promoted"? WP Job Manager allows a job to featured, is that what you mean by promoted?

**Comment by renatho** [comment]
Hi @Hastibe!

Thank you for asking! We are working on a feature to allow promoting jobs from WP Job Manager on external job boards. We hope it's helpful for you and for many other users! 🙂

**Comment by Hastibe** [comment]
Ah, thanks for clarifying--I was really confused! Looking forward to learning more about this.
