### ISSUE TITLE
Notify wpjobmanager.com when a promoted job is changed

### ISSUE THREAD

**Issue by renatho** [Automattic/WP-Job-Manager#2441]
The sites should notify wpjobmanager.com when a job is changed (See [schema](https://github.com/Automattic/wpjobmanager.com/issues/345)).

- The trigger should be when a promoted job is removed, deactivated or updated (fields used in the feed only).
- It should call an endpoint in wpjobmanager.com notifying that a job was updated.
- In case of an error in this request, it should retry in some hours with a scheduled job (maximum 3 times).

### Success Criteria

- [ ] When a field used in job feed is updated in a promoted job, it should notify wpjobmanager.com.
- [ ] When a field used in job feed is updated in a **not** promoted job, it should **not** notify wpjobmanager.com.
- [ ] When a field **not** used in job feed is updated in a promoted job, it should **not** notify wpjobmanager.com.
- [ ] In case of an error, the request retries in some hours.

**Comment by mikeyarce** [comment]
Just adding a note that I've been using the post meta of `_promoted` to distinguish if a job listing has been promoted or not.
