### ISSUE TITLE
Update job status after job is promoted or expired in JobTarget

### ISSUE THREAD

**Issue by renatho** [Automattic/WP-Job-Manager#2442]
Create an endpoint in WP Job Manager plugin that will update a job to promoted or not promoted. Mikey raised some PRs with the `_promoted` post meta to represent it in the plugin.

Protect this endpoint will be part of a [separate issue](https://github.com/Automattic/wpjobmanager.com/issues/433).

### Success criteria

- [ ] It's possible to call an endpoint in WP Job Manager plugin in order to update the promoted status.
- [ ] Schema is documented in `/docs/api/internal.json`

**Comment by fjorgemota** [comment]
Just documented here the approach that I'm thinking for protecting this endpoint: https://github.com/Automattic/wpjobmanager.com/issues/433#issuecomment-1612222137
