### ISSUE TITLE
Write Promoted Jobs feature documentation

### ISSUE THREAD

**Issue by renatho** [Automattic/WP-Job-Manager#2443]
Draft feature documentation to be posted in a CFT.

### Success Criteria

- [x] We have a draft of documentation of the main features of Promoted Jobs project to be posted with a CFT.

**Comment by Hastibe** [comment]
Curious about what all these "Promoted Jobs" issues are about. Is this something you'd like to add / are requesting, or is this something actively being worked on by the WP Job Manager dev team?

**Comment by renatho** [comment]
Hi @Hastibe!

Copying the same [answer from the other issue](https://github.com/Automattic/WP-Job-Manager/issues/2440#issuecomment-1572829516) here:

> Thank you for asking! We are working on a feature to allow promoting jobs from WP Job Manager on external job boards. We hope it's helpful for you and for many other users! 🙂
