### ISSUE TITLE
Basic setup

### ISSUE THREAD

**Issue by renatho** [Automattic/WP-Job-Manager#2445]
- It's a basic setup containing folders and basic classes to initialize Promoted Jobs feature.

### Success Criteria

- [ ] We have a basic setup to allow starting other features from that.

**Comment by mikeyarce** [comment]
PR: https://github.com/Automattic/WP-Job-Manager/pull/2459

**Comment by renatho** [comment]
https://github.com/Automattic/WP-Job-Manager/pull/2460
