### ISSUE TITLE
Ajax fetch time is high for getting 10 jobs data on load 

### ISSUE THREAD

**Issue by bharathganji** [Automattic/WP-Job-Manager#2455]
### What I Expected
my side hirehuntindia.com
observe get_listing took 1.7 sec.

**can u observe and suggest what is problem here**

### Screenshot / Video
<img width="957" alt="image" src="https://github.com/Automattic/WP-Job-Manager/assets/59326887/deaec12c-a7f9-4f77-9c27-de7cff955b05">

**Comment by thedebian** [comment]
Please use the [WPJM support forum](https://wordpress.org/support/plugin/wp-job-manager/) for assistance, you can also read more about the different type of support you can get [here](https://wordpress.org/support/topic/asking-for-help-in-the-wpjm-forum/).
