### ISSUE TITLE
Add way to deactivate option to promoted job action

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/WP-Job-Manager#2461]
If a job is already promoted, we need to add the option to `Deactivate` the promotion

![Image](https://github.com/Automattic/WP-Job-Manager/assets/3220162/59339c97-adc3-429d-aa24-1179558b2724)

**Comment by mikeyarce** [comment]
Added to PR: https://github.com/Automattic/WP-Job-Manager/pull/2460

**Comment by renatho** [comment]
@mikeyarce, could you confirm if this issue is not duplicated from another one?

The deactivate button and modal are part of https://github.com/Automattic/WP-Job-Manager/issues/2438, while the deactivate integration is part of https://github.com/Automattic/WP-Job-Manager/issues/2440.

**Comment by mikeyarce** [comment]
Yeah we can close this
