### ISSUE TITLE
Add deactivate Modal

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/WP-Job-Manager#2462]
Add Deactivate Modal

![Image](https://github.com/Automattic/WP-Job-Manager/assets/3220162/0039f286-7609-4c29-a269-2cb48f5c758c)

**Comment by renatho** [comment]
Hey @mikeyarce! Isn't this issue duplicated of part of https://github.com/Automattic/WP-Job-Manager/issues/2438?

**Comment by mikeyarce** [comment]
Closing!
