### ISSUE TITLE
Deprecated Messages for PHP 8.2

### ISSUE THREAD

**Issue by masteradhoc** [Automattic/WP-Job-Manager#2463]
**Describe the bug**
While using PHP 8.2 i get various deprecation messages while visiting any wp-admin page

<html>
<body>

Veraltet | Creation of dynamic property WP_Job_Manager_Settings::$settings_group is deprecated | +wp-content/plugins/wp-job-manager/includes/admin/class-wp-job-manager-settings.php:52 | 1 | Plugin: wp-job-manager
-- | -- | -- | -- | --
Veraltet | Creation of dynamic property WP_Job_Manager_Admin::$settings_page is deprecated | +wp-content/plugins/wp-job-manager/includes/admin/class-wp-job-manager-admin.php:56 | 1 | Plugin: wp-job-manager
Veraltet | Creation of dynamic property WP_Job_Manager::$forms is deprecated | +wp-content/plugins/wp-job-manager/includes/class-wp-job-manager.php:73 | 1 | Plugin: wp-job-manager
Veraltet | Creation of dynamic property WP_Job_Manager::$post_types is deprecated | +wp-content/plugins/wp-job-manager/includes/class-wp-job-manager.php:74 | 1 | Plugin: wp-job-manager

</body>
</html>

**Expected behavior**
No deprecation message when using php 8.2

Thanks!

**Comment by yscik** [comment]
Thanks for the report, we have a fix in #2456 for the next release.
