### ISSUE TITLE
Duplicate a Job - Additional Status Options

### ISSUE THREAD

**Issue by workpei25** [Automattic/WP-Job-Manager#2470]
### Is your feature request related to a problem? Please describe
Currently, users have the ability to duplicate a post in their jobs dashboard. However, this option is only possible when the listing is active. This limits the capability of this feature when job listings are in a different status.

### Describe the solution you'd like
Ideally, the Duplicate option would appear to users when jobs are pending and expired in addition to when jobs are active. We have many users requesting this option. For example, when employers join our site we set their member status to pending while we validate their information. While a pending employer, we allow employers to post a job listing with the understanding that the job will not be published until their account is approved. In many cases, employers want to publish similar jobs, yet different, and it would be of great value to allow them to duplicate the first listing when trying to create a second. The same issue applies to many employers have expired listings who want to save time by duplicating an existing job description.

### Describe alternatives you've considered
Perhaps this could be an option under WPJM / Applications settings. This would allow the administrator to decide if they wanted to extend these settings or not.

We used to have access to the template that assigned these status' in the jobs dashboard but that does not seem to be the case anymore. We found this very helpful to customize the jobs dashboard.

**Comment by StefMattana** [comment]
+1 6679154-zen

**Comment by Hastibe** [comment]
This would be a great quality of life improvement and one that I know I've seen requested before.

**Comment by Hastibe** [comment]
@mikeyarce -- given that this enhancement hasn't been implemented in WP Job Manager, shouldn't this still be an open issue? I, for instance, would still like to see this enhancement added.

**Comment by mikeyarce** [comment]
Hi @Hastibe - the feature is there in version 2.3.0 - but I should mention it's from the Job Dashboard, not from `wp-admin`
