### ISSUE TITLE
Add an include argument to the get_terms function

### ISSUE THREAD

**Issue by vaccinemedia** [Automattic/WP-Job-Manager#2487]
**Describe the bug**
The function for pulling in and populating the dropdown for categories / terms has an argument for an exclude list but should really have one for an _include_ list. The logic for this is:

If you have some set categories and you want to only include some of them, an include list would take care of this. This list could be set and left indefinitely knowing it's future proof. Then if in the future a new term is added, it will not automatically be on the add a job form select field.

Having only an exclude list as you currently do means that if a term is added in future, someone with admin rights has to then add this term to the exclude list which adds an extra step where things may not be done for whatever reason and more steps = more places for things to go wrong.

A real life example:
I'm currently working on a site which has this plugin installed and shares the main categories with the posts and other CPTs who also share the same categories taxonomy.

The categories taxonomy has around 12 top level terms and tens of child terms. The client only wants 9 of the top level terms to be in the select on the add a job form. So tens on tens of term IDs need to be added to the exclude list to hide them from the customer. This is quite a task and would be more efficient if just the 9 wanted IDs could be added to an include list.

NOW also if they add any categories in future, these categories will end up in the add a job form even i they are not wanted there. So an admin then needs to add the new category IDs into the exclude list. IF an _include_ list was used instead, then nothing would change. The client would be able to add and remove as many categories as they want and it would not affect the add a job form. This is especially true where editors can add terms but only admins can manage the add a job form fields.

**Comment by gikaragia** [comment]
Hello @vaccinemedia your request seems reasonable however I am having difficulties tracking down which function/shortcode you actually refer to.

I have had a look in WPJM code and couldn't find an instance where this happens - in all cases that I have encountered WPJM uses the WordPress core functions (i.e. `get_terms`) which actually support an `include` argument. To make use of this argument you will probably need to use filters. You can have a look at `WP_Term_Query::_construct()` method for more details about the `include` argument.

I'll close this issue but please re-open it if you still think that this is an issue or you need more information.
