### ISSUE TITLE
Confusion Between "Listings" and "Positions" in Settings

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/WP-Job-Manager#2491]
### Is your feature request related to a problem? Please describe

The language of "Positions" and "Listings" is potentially confusing on the WP Job Manager settings:

![Annotation-Annotation on 2023-07-05 at 11-25-24 png](https://github.com/Automattic/WP-Job-Manager/assets/45246438/f3c5a46d-e9b1-41a1-bccd-9d52a58342da)

We use "Listings" throughout but have one place where we refer to "Positions".

### Describe the solution you'd like

It might be clearer if we changed the to make it more clear that "Filled Positions" are "Filled Listings".

Perhaps using the text: `Job listings marked as "filled" will not display in your archives.`

### Describe alternatives you've considered

Eliminate the "positions" reference entirely and replace with "listings"

### Additional context

This was raised on 6482026-zen

**Comment by masteradhoc** [comment]
@bobmatyas please check my PR if i got all appearances :) found also some in the remote jobs area.
