### ISSUE TITLE
Clarify "Archives" Language in Expired Listings / Filled Positions Settings

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/WP-Job-Manager#2492]
### Is your feature request related to a problem? Please describe

<img width="674" alt="Screenshot on 2023-07-05 at 11-52-52(1)" src="https://github.com/Automattic/WP-Job-Manager/assets/45246438/07c801d6-d8d1-44ca-a2ac-d922effa0b7f">

The language here is a bit unclear. "Archives" could potentially mean the backend of the site, or the frontend. What we are referring to here is the frontend. The settings don't change what displays in WP Admin.

### Describe the solution you'd like

It would be nice to clarify that:

- These settings affect the frontend only
- Jobs will always be visible via the backend
- Perhaps instead of "archives" we could use "job listings"?
- We could clarify that when "filled jobs" are hidden, their individual page remains visible. 
- The use of "search" is confusing. Both options, hide the the jobs from search. 

### Additional context

- Raised on 6482026-zen

**Comment by masteradhoc** [comment]
@yscik will take this as part of #2634

**Comment by masteradhoc** [comment]
@bobmatyas please check PR #2634 - should be clear now :) feel free to suggest other description!
