### ISSUE TITLE
I am trying to add some custom XML feeds but they are not loading

### ISSUE THREAD

**Issue by pbearne** [Automattic/WP-Job-Manager#2495]
**Describe the bug**

using the standard add_feed( $feed_name, $function ); call

I can't work out the url that will list the JOBs as in the callback we are not loading an archive

Looking at your feed you seem to doing a new Query for feeds rather than the normal 

I would expect the /job/FEEDNAME to render the jobs but get a 404

What am I doing wrong?  

**To Reproduce**
add a feed via code and try to render it 

**Screenshots**

**Expected behavior**
Be able to add cusom XML feeds

**Isolating the problem (mark completed items with an [x]):**
- [ y] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ y] This bug happens with a default WordPress theme active.
- [ y] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 
- WP Job Manager Version:
- PHP Version: 
- Other important details:

**Comment by gikaragia** [comment]
Hello @pbearne GitHub issues should be created to report bugs or enhancements. For questions, you should create a support ticket if you have a paid license or use our forums if you are a free user.

To answer your question, the WPJM RSS feed can be found in the following URL `<your site home url>/feed/job_feed`
