### ISSUE TITLE
When Prompting for Upgrade, Release Notes Should Point to Actual Release Notes

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/WP-Job-Manager#2496]
### Is your feature request related to a problem? Please describe

When you are prompted to upgrade WP Job Manager and its add-ons, each link points to the generic page rather than plugin specific release notes:

![Annotation-Annotation on 2023-07-06 at 08-52-25 png(1)](https://github.com/Automattic/WP-Job-Manager/assets/45246438/0a11c5d0-daeb-48a6-9f7b-34698acf992c)

### Describe the solution you'd like

Clicking on the links should go pre-select the plugin's release notes, ex:

`/release-notes/?job-manager-product=wp-job-manager-alerts&job-manager-release-year=`

**Comment by yscik** [comment]
Fixed in https://github.com/Automattic/WP-Job-Manager/pull/2620
