### ISSUE TITLE
Make it possible to disable pagination and show X jobs only

### ISSUE THREAD

**Issue by mikejolley** [Automattic/WP-Job-Manager#250]
http://wordpress.org/support/topic/only-the-three-most-recent-featured-jobs-to-show?replies=3

**Comment by NicoHood** [comment]
This is not yet documented: https://wpjobmanager.com/document/advanced-usage/shortcode-reference/

Edit for the people coming form google and still wondering:
```
[jobs per_page=1 show_filters=false show_more=false]
```
