### ISSUE TITLE
Don't allow editing promoted jobs if moderation is enabled

### ISSUE THREAD

**Issue by renatho** [Automattic/WP-Job-Manager#2505]
Issue extracted from: https://github.com/Automattic/WP-Job-Manager/issues/2477

When a job and the setting to moderate a job is activated, we shouldn't allow editing promoted jobs on the frontend. Otherwise, it would be moved to draft, automatically deactivating the promotion.

### Success Criteria

- [ ] Promoted jobs aren't removed from JobTarget when moderated jobs are edited.

**Comment by jom** [comment]
Blocking this until we decide on how to handle draft jobs. It might not be an issue depending on our approach.

**Comment by renatho** [comment]
Closing it based on our discussion to not deactivate promotion based on job status change.

**Comment by renatho** [comment]
Closing it based on our discussion to not deactivate promotion based on job status change.
