### ISSUE TITLE
AWS Cloudfront Issue in combination with WP Job Manager

### ISSUE THREAD

**Issue by janhuisman** [Automattic/WP-Job-Manager#2509]
**Describe the bug**
I activated AWS Cloudfront CDN on our testing site: https://staging8.kollabo.ch/

There is a problem when loading images though. On some pages, images arent served correctly. The wrong image URL, to a fallback image, is loaded: https://staging8.kollabo.ch/de-ch/jobs/elektroinstallateur-jobs/ (scroll down a bit and you'll see flags popping up everywhere).

![image](https://github.com/Automattic/WP-Job-Manager/assets/139330592/266998ad-f77b-43d9-9e03-8c1a939a8eb0)

On pages where there is no Job Manager map, there is also no problem: https://staging8.kollabo.ch/de-ch/jobs/dachdecker-jobs/

![image](https://github.com/Automattic/WP-Job-Manager/assets/139330592/a1f381b7-17d0-4fd1-bab7-e6d851974041)

I had this same issue with a different plugin, Business Review Bundle. They did an update and that fixed the issue. Therefore, I am quite sure that this problem is created by the Job Manager map.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [ ] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6,2.2
- WP Job Manager Version: 1.40.2
- PHP Version: 8.0.29
- Other important details:

**Comment by gikaragia** [comment]
Hey @janhuisman I am not sure which plugin you refer to but it is probably not one of the plugins that we develop. We only develop WP Job Manager and the plugins listed in this page: https://wpjobmanager.com/product-category/core-add-ons/
