### ISSUE TITLE
Taxonomy job_listing_type allow to be publicly queriable

### ISSUE THREAD

**Issue by masteradhoc** [Automattic/WP-Job-Manager#2510]
Give users a easy setting to make the taxonomy publicly queriable so archive pages will be possible

**Comment by gikaragia** [comment]
There are two ways currently to achieve this:
- The theme to have support for `job-manager-templates`
- To use the filter to `register_taxonomy_job_listing_type_args` and update the `public` or `publicly_queryable` argument.
