### ISSUE TITLE
Enhance the promoted job feature to also check the jobs REST API capability

### ISSUE THREAD

**Issue by aaronfc** [Automattic/WP-Job-Manager#2514]
_Originally reported by @renatho in https://github.com/Automattic/WP-Job-Manager/pull/2513#discussion_r1261601931_

Renatho raised some valid concerns during #2513, about the `promoted-job/<job_id>` endpoint being open.

I created this ticket to discuss about it.

**Comment by jom** [comment]
Looking at that PR again, we should definitely at least check to make sure it is published. Once that is done, I think the next question is: are we exposing anything here that isn't exposed by the WP REST API endpoint?

**Comment by renatho** [comment]
@jom gave the idea to add the capability check related to the REST endpoint being exposed to the promote feature. So if it's not exposed in the API, we don't allow users to use the promote job feature.
