### ISSUE TITLE
Search actions (like Reset) not shown under companies search form when there are no results

### ISSUE THREAD

**Issue by gitgreek-of** [Automattic/WP-Job-Manager#2539]
This is similar to that issue, which was fixed with 1.41:

https://github.com/Automattic/WP-Job-Manager/pull/2454

But with WPJM 1.41 this was not fixed in the companies area:

When a search for companies has no results, the search reset link is missing. And the user is somehow stuck in the search form.

<img width="1131" alt="Bildschirmfoto 2023-07-24 um 01 58 17" src="https://github.com/Automattic/WP-Job-Manager/assets/140485947/5af6a334-a85a-40be-a0c8-57eaf4d6532f">

**Comment by gitgreek-of** [comment]
As I learned from the theme developer, that is not a WPJM issue but was implemented in the theme.

Anyway, would be nice to have a consistent implementation in all main areas - not one elemental part (like search) coming from WPJM and another from a theme. For us users it is not clear, what comes from where.

**Comment by gikaragia** [comment]
Hello @gitgreek-of as I understand, this was an issue with your theme so no actions are needed from WPJM. Please re-open if something else is needed.

**Comment by gitgreek-of** [comment]
Hello @gkaragia, yes :-)

Does WPJM have a default search form for companies too (like for jobs)?

**Comment by mikeyarce** [comment]
Hi @gitgreek-of, WPJM only has the default job search.  However, it can search for companies if you just enter the company into the search :)

**Comment by Gnodesign** [comment]
My theme's (Cariera) custom company manager is what gave rise to this issue and has already been taken care of. This issue can be closed since it's outside of the WPJM scope.
