### ISSUE TITLE
Disable AJAX search result before enter "Find jobs" submit button

### ISSUE THREAD

**Issue by ghost** [Automattic/WP-Job-Manager#2555]
### Is your feature request related to a problem? Please describe
I tried to find an option to disable AJAX search result before enter "Find jobs" submit button.
When I enter "manager" in the keyword-field instantly the query is sent to the database and results in a higher load. 

### Describe the solution you'd like
I only want the query to be fired after clicking the "find jobs" button. This would reduce the number of db queries a lot.

### Additional context
<img width="883" alt="job_manager_ajax" src="https://github.com/Automattic/WP-Job-Manager/assets/10399188/6dfc1005-55ce-47ac-9c52-4d5f34fa16e7">

**Comment by gikaragia** [comment]
Hello @githubtobi this functionality is coming from a plugin that is not maintained by WP Job Manager. By default, the AJAX call happens when you finish typing. Maybe it comes from a plugin such as 'Auto Job Suggest'?
