### ISSUE TITLE
Listing renewals not compatible with Application Deadline add-on

### ISSUE THREAD

**Issue by Hastibe** [Automattic/WP-Job-Manager#2559]
**Describe the bug**
As of 1.41.0, the new "Listings renewal" feature is not compatible with your [Application Deadline](https://wpjobmanager.com/document/application-deadline/) add-on. 

If a user previously selected an early closing date (via the field added by the Application Deadline add-on) for their job listing, the user isn't provided an opportunity to choose a new closing date in the "Listing renewal" submission flow, nor is the closing date extended automatically when the user renews the job listing to extend the listing's expiration date.

**Expected behavior**
The user is taken to the editing form when choosing to renew their job listing, so that they have the opportunity to see and change any closing date previously selected, just like how the submission flow works if they were relisting an expired job listing.

**Comment by gikaragia** [comment]
As discussed [here](https://github.com/Automattic/WP-Job-Manager/issues/2560) we won't allow edits during renewals for now. We will update the application deadline however during renewals automatically.

**Comment by gikaragia** [comment]
Resolving as this is now fixed.

**Comment by Hastibe** [comment]
Great to see it fixed! For clarity, when a listing is renewed with the Application Deadline add-on now, is the expiration date of the listing extended by the maximum duration (as set in either Job Listings > Settings > Job Submission> Listing Duration, or, if using WP Paid Listings, in WooCommerce > Products > Job Post's "Job listing duration" that was used to renew listing), or does something else happen?

**Comment by Hastibe** [comment]
@gkaragia --just curious to hear what the fixed behavior is when you have a moment (see my previous comment above).

**Comment by gikaragia** [comment]
Hello @Hastibe. So during renewal both the application deadline date and the normal expiry would be increased by the duration of the package that was used to renew the listing.

**Comment by Hastibe** [comment]
@gkaragia -- just submitted a ticket via my account on www.wpjobmanager.com, but also thought I'd give a heads-up about this here, too, which I hope is helpful:

> We just renewed subscriptions to update Application Deadline and WC Paid Listings (which we are also using), and when an early closing date has been selected on a job and that job is renewed, the expiration date of the job post is extended from the date of the early application deadline instead of from the expiration date of the job post. 
> 
> This can be fixed from the front-end or back-end if the user goes to edit the renewed job post, clicks on the **blank** "Closing date" calendar field, selects "Clear", and then saves the changes, but this isn't an obvious solution / appears bugged, and -regardless- for uniformity and user preference, a renewed job post should have its expiration date extended by the maximum date allowed (i.e. from its original expiration date), whether there previously was an earlier closing date selected or not.
> 
> Here are steps to re-create the issue (I'm not sure if it's relevant to it, but we have "Automatic deadline expiration" selected in WP Job Manager > Settings > Job Listings):
> 
> 1. Set-up a published job post with an early closing date that is "expiring soon" and a job post without an early closing date that is "expiring soon".
> 2. Renew both job posts.
> 3. Note that the renewed expiration dates of the two job posts are different.
> 4. On the front-end (or back-end), edit the renewed job post that had the early closing date, click on the blank "Closing date" calendar field, select "Clear" and then save the job post.
> 5. Note that the expiration dates of the two renewed job posts are now the same.
> 
> We hope a fix for this bug can be implemented quickly, so that when a job with an early closing date is renewed, the expiration date of the job post is extended from the original expiration date of the job post (i.e. extended by the same amount as a job posted on the same day without an early closing date), and we look forward to hearing back!

**Comment by gikaragia** [comment]
Hey @Hastibe. I am assuming that the case that you describe has the 'Automatic deadline expiry' option enabled. 

So what you suggest is to remove the application deadline entirely during renewals. I am not sure this is intuitive. I'll explain what I mean with an example:
- A user posts a job and sets the application deadline to be the 1st of January.
- Let's assume that if he didn't set an application deadline the job would expire at 10th of January.

As a user, if did a renewal I would expect the expiry date to get extended by the amount of days of the package I paid for. So if the package extends the date for 30 days I would expect the expiry date to be 31st of January, not 9th of February.

 To achieve what you are looking for you should delete the application deadline entirely. This snippet achieves just that:

```
function delete_application_deadline( $new_expiry, $job ) {
	delete_post_meta( $job->ID, '_application_deadline' );

	return $new_expiry;
}

add_filter( 'job_manager_renewal_expiry_date', 'delete_application_deadline' , 11, 2 );
```

**Comment by Hastibe** [comment]
I just realized I never replied here to thank you for the snippet, @gikaragia -- it has been working well, and I really appreciate it!

Also, curiously, my reason for wanting this behavior is so that the renewal expiration date matches users' expectations / purchases, too--with this snippet clearing the early expiration date on renewal, if a user buys (for example) a 30 day job post and then renews it with another 30 day job post, they have the option of their job post being posted for 60 days total (regardless of whether they chose an early expiration date for their first 30 day job post), matching what they've purchased.

In your example above, the user purchased a 30 day job post (used to publish a job post on December 11th), and set it to expire 9 days early (on January 1st, instead of January 10th). Then the user decided they needed it posted for longer, and paid for a second 30 day job post by renewing it. If they didn't **first** edit and clear the early expiration date on their post before renewing, their job post will only be extended by 30 days from that early expiration date (so to January 31st). **This results in the user having purchased two 30 day job posts, but only having the option for their job to be posted for a maximum of 51 days.**
