### ISSUE TITLE
Improve usage tracking on installation

### ISSUE THREAD

**Issue by gikaragia** [Automattic/WP-Job-Manager#2580]
We should change the way that we currently as for users to enable usage tracking in the following ways:
- On the setup wizard, have the checkbox checked by default. This will enable usage tracking regardless if the user clicks ‘Start setup’ or ‘Skip setup’. It will not enable usage tracking only if the user unchecks the checkbox. We can look into updating the text on the buttons to make it more clear (e.g. Save and Skip)
- On activation do not show the ‘Enable usage tracking’ notice at all.
- For new users, we should display the 'Enable usage tracking' notice one week after installation, if they don't have tracking already enabled.
- For existing users, we should display the 'Enable usage tracking' notice one week after updating to the latest version.
- If the users click 'Disable Usage Tracking' we shouldn't ask them again.

![Image](https://github.com/Automattic/WP-Job-Manager/assets/53191348/5749cf9b-cb84-47f0-b0f1-87fa8797954e)

![Image](https://github.com/Automattic/WP-Job-Manager/assets/53191348/59b6be51-3cc9-4198-a5ef-d51510e17437)

**Comment by mikeyarce** [comment]
@gkaragia I've got everything working except this part which I'm not sure how it's supposed to work:

> For existing users, we should display the 'Enable usage tracking' notice one week after updating to the latest version.

If they install the plugin, they will see the `Enable usage tracking` notice and the only way to dismiss it would be to opt-out - either by going through the set-up and NOT checking the tracking box OR by clicking the `Disable Usage Tracking` button.   So if they have expressly opted-out, should we show the prompt again after a plugin update?
