### ISSUE TITLE
Update the designs of notices

### ISSUE THREAD

**Issue by gikaragia** [Automattic/WP-Job-Manager#2581]
We should update the designs of the tracking and setup wizard notices:

Before:

![Image](https://github.com/Automattic/WP-Job-Manager/assets/53191348/4bcb5e3a-262f-43d8-80f4-66f8180c2778)

After:

![Image](https://github.com/Automattic/WP-Job-Manager/assets/53191348/8d6315b2-5727-4957-8984-e2b0249d4ad5)

**Comment by mikeyarce** [comment]
I think we should also make sure the "Add-ons Bundle" notice is also styled properly:
![Screenshot 2023-09-19 at 11 20 42 AM](https://github.com/Automattic/WP-Job-Manager/assets/3220162/d62d8773-e7cb-4733-aaef-114c05fd554d)
