### ISSUE TITLE
Add new upsell banner to Job Listings and Settings page

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/WP-Job-Manager#2582]
EDIT:  We just need a new banner on the Job Listings page and WPJM Settings Page to let people know we have paid extensions.

Button will be:
- Job Listings
- Settings Page

**Did you know?**
You can upgrade your job listings with our job manager extensions and add applications, resumes, alerts, and more!

Button:  "View Extensions" takes to the Marketplace page

**Comment by yscik** [comment]
![Image](https://github.com/Automattic/WP-Job-Manager/assets/176949/91d664a7-ec56-4776-8e51-ac4a8f7b9ffd)
