### ISSUE TITLE
Re-design Menus

### ISSUE THREAD

**Issue by mikeyarce** [Automattic/WP-Job-Manager#2586]
- New Icon (should be base64 SVG icon so it's compatible with Calypso)
- Should have all the current same submenu items (Except Add New, remove those)
- Add "Applications pro" and "Resumes pro" items
- The Pro upsell items will link to pages that have more information on that add-on
- There will be a separate task for creating those pages.

I'm not sure if we will rename our "Add-ons" page to "Extensions" so I asked here: p6r3EZ-1Nu-p2#comment-3358
Decision:  Will be called "Extensions"

Related: https://github.com/Automattic/wpjm-addons/issues/118

Design:
![Image](https://github.com/Automattic/WP-Job-Manager/assets/3220162/b69b7f91-c1eb-4f42-b196-99aabcf92e36)

**Comment by fjorgemota** [comment]
For reference, Sensei did have changes similar to this one last year.

Here's the post of the related project thread: p6rkRX-2xl-p2

**Comment by yscik** [comment]
Also here is the section separator CSS added recently to the Applications plugin:

https://github.com/Automattic/wpjm-addons/blob/8476676fc27dbf1ba833f544ec6eec33771f671f/src/applications/assets/css/menu.scss#L26-L30
