### ISSUE TITLE
Single Job Listing: add back button to job list main page

### ISSUE THREAD

**Issue by StefMattana** [Automattic/WP-Job-Manager#2590]
This has been suggested by a user in [this forum thread](https://wordpress.org/support/topic/add-button-16/).

It'd be nice to have a "go back" button on single job listings to be able to return to the main job listings page. 
I don't think we have that per default, and the only way to get that is via template overrides AFAIK.

**Comment by gikaragia** [comment]
Hmmm this doesn't seem to be worth it. Some users might want the button but we will probably break any themes that rely on our templates.

As there is a way to implement this with template overriding, I will close this one.
