### ISSUE TITLE
Resume Manager → Skills are not cached/saved when user enters resume, clicks preview and goes back to re-edit (same if reCaptcha not checked)

### ISSUE THREAD

**Issue by promptpress** [Automattic/WP-Job-Manager#2591]
- When adding a new Resume …
- and entering Skills (must be activated in the backend)
- and clicking preview
- and then going back to re-edit
- the previously entered skills get lost.
- Same happens when you have activated reCaptcha in the backend and the user forgets to click the checkbox in the resume form: The user get s an error message, the form reloads to edit, but then the skills get lost.

→ This field is obviously not saved/cached in those cases. Happens only with that one Skills-field.

Bug was reproduced and confirmed by Cariera author.

To reproduce:

- see above steps

**Comment by gikaragia** [comment]
Hello @promptpress I have tried reproducing the issue but I couldn't. In my case, all the fields were populated regardless if I clicked the 'Edit resume' button or went back in my browser.

I think this is probably an issue with a plugin or theme that you have installed. I would suggest following the below steps:
- Deactivate all plugins except core WP Job Manager ones.
- Deactivate any themes.
- Alternatively, you can try reproducing it in a clan installation where only the WP Job Manager plugins are installed.

If you are still able to reproduce this, can you please send us more details on how to reproduce it? I will close the issue for internal tracking purposes but please re-open it if required.
