### ISSUE TITLE
Incorrectly duplicated string in settings

### ISSUE THREAD

**Issue by zedejose** [Automattic/WP-Job-Manager#2609]
**Describe the bug**
A string is incorrectly repeated in lines [256](https://github.com/Automattic/WP-Job-Manager/blob/534d65f977901c87e3da743b64f59d40d21fd0c5/includes/admin/class-wp-job-manager-settings.php#L256) and [275](https://github.com/Automattic/WP-Job-Manager/blob/534d65f977901c87e3da743b64f59d40d21fd0c5/includes/admin/class-wp-job-manager-settings.php#L275) in the settings class,

It says `'This lets users add a salary currency when submitting a job.'` for both but, 275 refers to the salary **unit**, not the currency .

**To Reproduce**
1. Go to `/wp-admin/edit.php?post_type=job_listing&page=job-manager-settings#settings-job_listings`
2. Scroll down to **Salary Currency**

**Screenshots**
<img width="684" alt="Screenshot 2023-10-08 at 14 23 00" src="https://github.com/Automattic/WP-Job-Manager/assets/1371600/a2419ee3-d9c4-40dc-8c48-ff20fec362ff">

<img width="864" alt="Screenshot 2023-10-08 at 14 28 41" src="https://github.com/Automattic/WP-Job-Manager/assets/1371600/e6abfc68-5452-4651-a183-44c8cf4f449c">

**Expected behavior**
A separate string on 275 saying `'This lets users add a salary unit when submitting a job.'`

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.3.1
- WP Job Manager Version: 1.42.0
- PHP Version: 8

**Comment by masteradhoc** [comment]
@zedejose please check my PR :)

**Comment by zedejose** [comment]
Thanks!
