### ISSUE TITLE
Php error on wp-admin / companies / settings page

### ISSUE THREAD

**Issue by cisnerosebastian** [Automattic/WP-Job-Manager#2610]
https://github.com/Automattic/WP-Job-Manager/blob/534d65f977901c87e3da743b64f59d40d21fd0c5/includes/admin/class-wp-job-manager-settings.php#L1092C25-L1092C25

I'm getting a 

"NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array"

that is breaking the page there.

changing this

```
foreach ( $option['options'] as $key => $name ) {
				echo '<option value="' . esc_attr( $key ) . '" ' . selected( in_array( $key, $value, true ) ? $key : null, $key, false ) . '>' . esc_html( $name ) . '</option>';
			}
```

to this

```
foreach ( $option['options'] as $key => $name ) {
    $isSelected = is_array($value) && in_array($key, $value, true);
    echo '<option value="' . esc_attr( $key ) . '" ' . selected( $isSelected ? $key : null, $key, false ) . '>' . esc_html( $name ) . '</option>';
}
```

fixes the issue.

**Comment by thedebian** [comment]
Should be fixed by #2631
