### ISSUE TITLE
Inform third-party devs about menu structure change

### ISSUE THREAD

**Issue by yscik** [Automattic/WP-Job-Manager#2613]
They might need to update their hooks adding menu items for their plugins.

**Comment by Gnodesign** [comment]
Will there be any documentation on this?

**Comment by yscik** [comment]
So far it looks like the parent page remains `edit.php?post_type=job_listing`, so existing `add_submenu_page` calls should keep working. 

Here is the PR and linked issue with the initial changes, we are renaming the menu to 'Job Manager', and trying to clean up a few items to reduce noise: https://github.com/Automattic/WP-Job-Manager/pull/2612
