### ISSUE TITLE
No option to create a resume package in WooCommerce Paid Listings

### ISSUE THREAD

**Issue by tawandakembo** [Automattic/WP-Job-Manager#263]
I notice that there is not option that allows me to create a resume package. I woud like applicants to make payments before they can apply for jobs and when I looked at the documentation before buying the 'WooCommerce Paid Listings' I noticed that it has a resume package when creating products. Now it's not available. Why?

**Comment by entrepreneur-sheikh** [comment]
i am facing the same problem please told me how it can be solved
