### ISSUE TITLE
Show only one type of job in submit form

### ISSUE THREAD

**Issue by vanesafg** [Automattic/WP-Job-Manager#2636]
I want to show only one type of job on the submit form and was trying to leverage this snippet:

add_filter( 'submit_job_form_fields', 'submit_job_form_fields_job_type_default' , 11);
  
function submit_job_form_fields_job_type_default( $fields ) 
{
    $fields['job']['job_type']['default'] = 'volunteer'; // Slug of the job type
  
    return $fields;
}

Can you please help me???

Thanks

**Comment by thedebian** [comment]
Please use the [WPJM support forum](https://wordpress.org/support/plugin/wp-job-manager/) for assistance, you can also read more about the different type of support you can get [here](https://wordpress.org/support/topic/asking-for-help-in-the-wpjm-forum/).
