### ISSUE TITLE
Select Category  filter does not filtering via ajax 

### ISSUE THREAD

**Issue by abirdhaka7** [Automattic/WP-Job-Manager#2649]
**Describe the bug**

On this page, http://s972810829.websitehome.co.uk/vacancies/ whatever you select from the Choose a Category dropdown, it shows the same jobs. The location field seems to work but not the category.

**To Reproduce**
1. Go to 'http://s972810829.websitehome.co.uk/vacancies/'
2. Click on 'chose a category.'
3. Chose any of them from the category dropdown and u will see same results

**Screenshots**
![image](https://github.com/Automattic/WP-Job-Manager/assets/47899197/4d357c58-36b3-426a-9355-62cdef4254f7)
![image](https://github.com/Automattic/WP-Job-Manager/assets/47899197/cfb7ddbf-fcea-4e3e-8e1b-b65b100527a7)
![image](https://github.com/Automattic/WP-Job-Manager/assets/47899197/0d334a81-c576-4c50-bd8b-345b09d01bb7)

**Expected behavior**
it supposed to show specific jobs from there regarding category when select any option from the select input field but its showing all job listings instead.

**Isolating the problem (mark completed items with an [x]):**
-[x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
-[x] This bug happens with a default WordPress theme active.
-[x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.4.1
- WP Job Manager Version: 1.38.1
- PHP Version: 8.1.25

- Other important details:

**Comment by mikeyarce** [comment]
Hi @abirdhaka7 - I can't reproduce this issue with the latest version of WP Job Manager and a default theme.  I would suggest updating WPJM to the latest version and if you still have this issue let us know.
