### ISSUE TITLE
While applying for job I am getting the issue

### ISSUE THREAD

**Issue by mohandtharsha** [Automattic/WP-Job-Manager#2694]
I am trying to apply for a job and I have purchased WP Job Manager pro plugin 
Try to help me with the solution.

Below is attachment,

![Screenshot 2024-01-05 165138](https://github.com/Automattic/WP-Job-Manager/assets/137255082/6c2271a7-3e43-4eba-abb5-9eb3ed593d64)

**Comment by thedebian** [comment]
Hi @mohandtharsha,
Please review the [support policy for WPJM](https://wpjobmanager.com/support-policy/) and use the right channel for your request, either [opening a support ticket](https://wpjobmanager.com/support/) if you have a license, or posting to [the community forum](https://wordpress.org/support/plugin/wp-job-manager/).
