### ISSUE TITLE
WPJM Date form-fields allow setting dates in the past.

### ISSUE THREAD

**Issue by pgk** [Automattic/WP-Job-Manager#2705]
**Describe the bug**

You can set a date in the past when entering expiry date or scheduled date.

**To Reproduce**
1. Go to your Add-A-Job page
2. On schedule date I am able to set the date to the past

**Screenshots**

**Expected behavior**
Do not allow selecting a past date in the first place.

**Comment by Hastibe** [comment]
Yes, this would be helpful to prevent--regularly have users choosing a closing date in the past by accident when posting a new job.

**Comment by flamuren** [comment]
This has just happened on my website. Can confirm users may pick wrong dates.
