### ISSUE TITLE
Featured first argument bug

### ISSUE THREAD

**Issue by Gnodesign** [Automattic/WP-Job-Manager#2721]
Issue: https://github.com/Automattic/WP-Job-Manager/pull/2675

**Describe the bug**
This feature performs as intended until the filters are deactivated. In such cases, the ordering reverts to its default behavior, disregarding the featured_first argument.

**To Reproduce**
1. Create a page with the shortcode `[jobs orderby="ID" featured_first="true" order="DESC" show_filters="true"]`
2. Visit the page and you can see that it works as expected.
3. Edit the jobs page and disable the filters: `[jobs orderby="ID" featured_first="true" order="DESC" show_filters="false"]`
4. Visit the page, and you can see the featured job listings are not shown on top as expected.

**Expected behavior**
The `featured_first` functionality should operate seamlessly in both scenarios, whether search filters are applied or not.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.4.2
- WP Job Manager Version: 2.2.0
- PHP Version: 8.0.30

**Comment by Gnodesign** [comment]
@mikeyarce You may want to take a look at this.

**Comment by mikeyarce** [comment]
Thanks for the report, @Gnodesign !
