### ISSUE TITLE
conditional logic for company fields does not work

### ISSUE THREAD

**Issue by jankes07** [Automattic/WP-Job-Manager#2758]
**Describe the bug**
I have created a form for adding a company and some of the fields have conditional logic so that they are not visible if the appropriate selection is not selected in another field. Unfortunately it doesn't work: all fields are visible all the time. How can I fix it?

**To Reproduce**
1. Go to https://stalwork.pl - register as "Pracodawca" . When you login click on "DODAJ OFERTĘ PRACY" button in top right corner scroll down and choose 'nowa firma'. scroll down to "Branże" checklist. all fields below that start with the header should be hidden and only show up if you check the appropriate box in the "Branżę" field

**Screenshots**
https://www.awesomescreenshot.com/video/24820965?key=ad1992b3eb74712c2e07ade543577c50

**Expected behavior**
fields should be hidden and only show up when clicked. This is how it works in a job offer, as you can see in the video

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- I didn't turn off other listings because, as you can see in the video, the logic works for Job Offers. Does not work for fields in the add new company form
- [ ] This bug happens with a default WordPress theme active.
yes
- [ ] I can reproduce this bug consistently using the steps above.
yes
**WordPress Environment**
- WordPress Version:  6.4.3
- WP Job Manager Version: newest
- PHP Version: 7.4
- Other important details:

**Comment by jankes07** [comment]
Hello? Is anybody there to help me with this issue???

**Comment by Gnodesign** [comment]
This matter doesn't relate to WPJM directly, it comes from the third-party extension [WPJM Field Editor](https://plugins.smyl.es/wp-job-manager-field-editor/). I recommend you to contact the author, @tripflex , by opening a support ticket if you have valid support for their plugin.

**Comment by tripflex** [comment]
Yeah this isn't related to WP Job Manager, please open a support ticket at https://plugins.smyl.es/my-account for support

@yscik @mikeyarce @fjorgemota you guys can close this i don't have access to anymore
