### ISSUE TITLE
the_company_logo ignores chosen size

### ISSUE THREAD

**Issue by jerwre** [Automattic/WP-Job-Manager#277]
the_company_logo seems to ignore chosen image size, returns full image/original image.

From functions:

``` php
add_image_size( 'job-thumb-600', 600 );
add_image_size( 'job-thumb-300', 300 );
add_image_size( 'job-thumb-150', 150 );
```

`var_dump( get_intermediate_image_sizes() );`
returns:

``` php
array(7) { 
[0]=> string(9) "thumbnail" 
[1]=> string(6) "medium" 
[2]=> string(5) "large" 
[3]=> string(18) "job-thumb-150" 
[4]=> string(18) "job-thumb-600" 
[5]=> string(18) "job-thumb-300" 
[6]=> string(14) "post-thumbnail" 
}
```

Images get saved as logo-150x37.jpg, logo-300x75.jpg etc. when uploaded. 

Postmeta for an uploaded image:

``` json
a: 5: {
  s: 5: "width";i: 1500;s: 6: "height";i: 375;s: 4: "file";s: 24: "2014/09/logo.png";s: 5: "sizes";a: 7: {
    s: 9: "thumbnail";a: 4: {
      s: 4: "file";s: 24: "logo-150x150.png";s: 5: "width";i: 150;s: 6: "height";i: 150;s: 9: "mime-type";s: 9: "image/png";
    }s: 6: "medium";a: 4: {
      s: 4: "file";s: 23: "logo-300x75.png";s: 5: "width";i: 300;s: 6: "height";i: 75;s: 9: "mime-type";s: 9: "image/png";
    }s: 5: "large";a: 4: {
      s: 4: "file";s: 25: "logo-1024x256.png";s: 5: "width";i: 1024;s: 6: "height";i: 256;s: 9: "mime-type";s: 9: "image/png";
    }s: 18: "job-thumb-600";a: 4: {
      s: 4: "file";s: 24: "logo-600x150.png";s: 5: "width";i: 600;s: 6: "height";i: 150;s: 9: "mime-type";s: 9: "image/png";
    }s: 18: "job-thumb-300";a: 4: {
      s: 4: "file";s: 23: "logo-300x75.png";s: 5: "width";i: 300;s: 6: "height";i: 75;s: 9: "mime-type";s: 9: "image/png";
    }s: 18: "job-thumb-150";a: 4: {
      s: 4: "file";s: 23: "logo-150x37.png";s: 5: "width";i: 150;s: 6: "height";i: 37;s: 9: "mime-type";s: 9: "image/png";
    }s: 14: "post-thumbnail";a: 4: {
      s: 4: "file";s: 24: "logo-150x150.png";s: 5: "width";i: 150;s: 6: "height";i: 150;s: 9: "mime-type";s: 9: "image/png";
    }
  }s: 10: "image_meta";a: 11: {
    s: 8: "aperture";i: 0;s: 6: "credit";s: 0: "";s: 6: "camera";s: 0: "";s: 7: "caption";s: 0: "";s: 17: "created_timestamp";i: 0;s: 9: "copyright";s: 0: "";s: 12: "focal_length";i: 0;s: 3: "iso";i: 0;s: 13: "shutter_speed";i: 0;s: 5: "title";s: 0: "";s: 11: "orientation";i: 0;
  }
}
```

Any ideas?

**Comment by catcologne** [comment]
I've got the problem, that my campany logo (also resume photo) always is cropped even though I set cropping false. e.g. I use this function in my custom template:
```
$foto_large = job_manager_get_resized_image( $foto, 'large');
```
"large" is defined in WordPress by 1024px X 1024px
I tried also with:
```
add_image_size('company-logo', 142, 100);
```

I even tried changing wp-job-manager-template from
```
if ( ! is_wp_error( $image->resize( $img_width, $img_height, $img_crop ) ) ) {
```
to: 
```
if ( ! is_wp_error( $image->resize( $img_width, $img_height, false ) ) ) {
```
No chance: the image is always cropped to a square image of 1024 x 1024.
Any ideas?

Thank you!

**Comment by mikejolley** [comment]
Depends what size its being output at, and what is outputting it. i.e. the theme may pass a different size in.

Also, once resized its cached and stored to the server fyi.

**Comment by catcologne** [comment]
ok, $foto in 
job_manager_get_resized_image( $foto, 'large'); 
is the original image with full size e.g. 1600 x 1200.
I remove the created images from the uploads-folder when I test this. Also I check the direct link to the image in the uploads folder and I can see the image in square.

**Comment by mikejolley** [comment]
When you define http://codex.wordpress.org/Function_Reference/add_image_size you need to also set cropping, and then when you call the image in the template files (https://github.com/mikejolley/WP-Job-Manager/blob/42698194e4e49f61cb5713b53e7008148196e47e/wp-job-manager-template.php#L299) you need to pass 'company-logo' instead of the default 'full'.

**Comment by catcologne** [comment]
What I did in functions.php (in my case I'm using the job_manager_get_resized_image function)
```
add_image_size('resume-large', 1024, 1024, false);
```
later:
```
job_manager_get_resized_image( $foto, 'resume-large');
```
Result is a square image:
http://jobwrk.com/wp-content/uploads/resumes/img_2011_09_13-20_56_37-resume-large.jpg

**Comment by mikejolley** [comment]
Where are you adding add_image_size? Give me your full code/snippet.

**Comment by catcologne** [comment]
in functions.php 
add_image_size('avatar', 50, 50, true);
add_image_size('slider-application', 160, 160, true);
add_image_size('slider-resume', 600, 600, true);
add_image_size('resume-large', 1024, 1024, false);

without anything around. A I said, I also tried:
```
job_manager_get_resized_image( $foto, 'large');
```
which is defined in WP Backend with 1024 x 1024px.
job_manager_get_resized_image( $foto, 'resume-large');

**Comment by mikejolley** [comment]
Plugins loaded hook I do this:

`
add_image_size('test-large', 1024, 1024, false);
`

Editing the content-job_listing.php I add this:
`
<?php the_company_logo( 'test-large' ); ?>
`

Result: https://dl.dropboxusercontent.com/s/2je1b0g5j2y1qec/2015-02-16%20at%2020.37%202x.png?dl=0

Uncropped, 1024 sized.

**Comment by catcologne** [comment]
I tried the same, in content-single-resume.php:
```
<?php the_candidate_photo('resume-large'); ?>
```
in functions.php
```
add_image_size('resume-large', 1024, 1024, false);
```
But nothing changed: image has the size of 1024 x 1024px.
The same happens with the company-logo.
 
Could there be another hook, filter, anything else interfering? Is it correct to enter the add_image_size at the end of the functions.php?

**Comment by mikejolley** [comment]
@catcologne tested that exact code and it worked: https://dl.dropboxusercontent.com/s/50fzlx9bf3trw74/2015-02-16%20at%2023.20%202x.png?dl=0

2 things to note:

a) you need to submit a new resume/image so its regenerated
b) regardless of these sizes, the CSS will change the display dimensions - if you want to to show at a different size you need to set:

`
width: 1024px;
height: auto;
`
for the image. I'm using inspector to see the 'real' size here.

**Comment by zenics** [comment]
I have the same problem with images.

I am using the function the_candidate_photo( 'custom-size' ); to pull the image from upload field.

The function does not pull the right size, actually, let me put it this way; file upload doesnt size the image to additional add_image_size . it puts the full size image in "wp-content/uploads/job-manager-uploads/candidate_photo/2017/08/image.jpg" . I dont see any other sizes at all. Also if I add the resume image from backend; it sizes the image and instead of that folder it goes to the media library (default upload folder).

the images uploaded from front-end are mostly large and can't control the user, so I need the right size image (in my case 320x320 this is my custom size) to pull.

It is really frustrating.

**Comment by zenics** [comment]
This is frustrating, the plugin dont resize images and keep the original size in the folder. I ve created an additional field for image and same thing no other size but full image. Can someone help us with this?
