### ISSUE TITLE
Post job: Categories always as a multi-select field

### ISSUE THREAD

**Issue by Gnodesign** [Automattic/WP-Job-Manager#2778]
**Describe the bug**
It appears that the "Job Category" field on the post job page consistently displays as multi-select, regardless of whether the "Multi-select Categories" option is disabled. This issue also extends to the Resume Manager. I received a report about this today, not sure when this bug started.

**To Reproduce**
1. Go to 'WP Dashboard -> Job Manager -> Settings -> Job Listings' and make sure **Multi-select Categories** is disabled
2. Go to "Post Job" page
3. Check the **Job Category** field

Same steps for **Resume Manager**

**Expected behavior**
The field should show as a multi-select only when the **Multi-select Categories** is enabled.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.4.3
- WP Job Manager Version: 2.2.2
- PHP Version: 8.0.30

**Comment by gikaragia** [comment]
The `Multi-select Categories` refers to the job filtering shortcode, not the job submission page. So if it is enabled, the user can choose many categories in the [jobs] shortcode and when disabled only one is allowed. On the other hand if you refer to 'Multi-select Listing Types', this is about the job type not category.

In the job submission page, only multiple categories is supported with the available settings. You can potentially allow it if you change the category to be single select though with a snippet:
```
'job_category'        => [
	'label'       => __( 'Job category', 'wp-job-manager' ),
	'type'        => 'term-select',
```
