### ISSUE TITLE
With each job alert, E-mails will NOT CONTAIN NEW JOBS ONLY but will contain all jobs matching the alert-settings.

### ISSUE THREAD

**Issue by WJoksch** [Automattic/WP-Job-Manager#2781]
Dear support,

I sent ticket to wpjobmanager.com support with Ticket Nr.#7724631 twice already, but no one responded. That's why I am posting the issue here now.

The problem is:
With each job alert, E-mails will NOT CONTAIN NEW JOBS ONLY but will contain all jobs matching the alert-settings. Up to max. 50 Jobs will be sent again and again daily.

Even if only 1 new job has been uploaded since the last job alert email, the last 50 jobs will be sent.

This problem exists since I did the previous update 3.0.0 and still exists even after the current update 3.1.0

My site is: https://bildungsserver.net

Greetings, Gunther

**WordPress Environment**
- WordPress Version: 6.4.3
- WP Job Manager Version: 2.2.2
- WP Job Manager - Job Alerts Version: 3.1.0
- PHP Version: 7.4.33

**Comment by joewa1980** [comment]
Our hack for avoiding this (we're experiencing the same issue) is to change the wording of the job alert to something like, "Your job alert <alert name> has been triggered. Click here to view the latest jobs."

...and don't include the list in the email. Just send the user to your jobs page via the link in the email.

**Comment by gikaragia** [comment]
This was fixed in 3.1.1. Let us know if you need anything else
