### ISSUE TITLE
Employers can create a Resume and apply for jobs

### ISSUE THREAD

**Issue by tobias992** [Automattic/WP-Job-Manager#2790]
**Describe the bug**
If I register as an employer and use the application function (Resume-Manager), employers can also create a resume and apply for jobs. I don't think that should be the case.

**To Reproduce**
1. Register as employer
2. Open your own job listing
3. Use application form (Resume-Manager)
4. You will be redirected to create resume form

**Expected behavior**
Employers shouldn't see the application forms in single job pages.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.4.3
- WP Job Manager Version: 2.2.2
- WP Job Manager - Applications: 3.1.0
- PHP Version: 8.0.30

**Comment by gikaragia** [comment]
Hey @tobias992 by default, Resume Manager does not hide the resume from anyone unless the setting to require an account is enabled and the user is not logged in.

With that said, you can achieve what you are asking with a code snippet that uses the `resume_manager_user_can_post_resume` filter. Something like this (haven't actually tested it):
```
function do_not_allow_employers( $can_post ) {
	$user = wp_get_current_user();
	if ( in_array( 'employer', (array) $user->roles ) ) {
    	return false;
	}
	return $can post;
}

add_filter('resume_manager_user_can_post_resume', 'do_not_allow_employers');
```
