### ISSUE TITLE
cache occurrence of inactive listings

### ISSUE THREAD

**Issue by aga2442** [Automattic/WP-Job-Manager#2795]
Hello,

I have mentioned this problem on the wordpress support page before, but since there is no improvement, I would like to explain it again.

I want to explain the problem in this way.

There are currently 26 active job listingss on my website.

But in the cache folder in the ftp area, there are 2089 cache files of job listingss.

this is not a new problem.

I am actively using the wp-rocket plugin.

you can see in the attached pictures.
![xxx1](https://github.com/Automattic/WP-Job-Manager/assets/66041736/381c7109-3ef5-4b08-8d5c-953c5e5eacc9)
![xxx2](https://github.com/Automattic/WP-Job-Manager/assets/66041736/13e78051-a415-4c02-a565-1126b0838676)

**Comment by gikaragia** [comment]
Hey @aga2442, I have tried locally WP Rocket with WP Job Manager and it seems like when a job is deleted, the cached files are deleted too.

I think this is maybe an issue with your environment and/or configuration. WP Job manager doesn't do any special handling so WP Rocket should work. I would suggest to contact WP Rocket support for further help.
