### ISSUE TITLE
PHP 8.3 deprecated notice for class-wp-job-manager-usage-tracking.php

### ISSUE THREAD

**Issue by Hastibe** [Automattic/WP-Job-Manager#2807]
Getting this "PHP Depreciated" notice in my debug.log on PHP 8.3. Just a FYI:

PHP Deprecated:  Calling get_class() without arguments is deprecated in /wp-content/plugins/wp-job-manager/includes/class-wp-job-manager-usage-tracking.php on line 163

**Comment by azollafox** [comment]
There's another report of this [on the forums](https://wordpress.org/support/topic/wp-job-manager-debug-error-on-both-backend-and-frontend/)

The user sees this error:
```
Deprecated: Calling get_class) without arguments is deprecated in ************/wp-contents/plugins/wp-jobmanager/includes/class-wp-jobmanager-usage-tracking.php on line 163
```

**Comment by Liztowoju** [comment]
We have another user with the same report [on the forums](https://wordpress.org/support/topic/wp-job-manager-debug-error-on-both-backend-and-frontend/#post-17826668)

They see this error:

> Deprecated: Calling get_class() without arguments is deprecated in /home/radicalt/opexrecruiting.com/wp-content/plugins/wp-job-manager/includes/class-wp-job-manager-usage-tracking.php on line 163

**Comment by masteradhoc** [comment]
Hi there
We have the same issue currently.

`Deprecated: Calling get_class() without arguments is deprecated in /var/www/vhosts/xxxxxxxx/httpdocs/wp-content/plugins/wp-job-manager/includes/class-wp-job-manager-usage-tracking.php on line 163`


Thanks for fixing this deprecated message.
