### ISSUE TITLE
ask code snippet to add company logo to the email send

### ISSUE THREAD

**Issue by IgalNeeman** [Automattic/WP-Job-Manager#2819]
### Additional context

Hello i need code snippet to define the logo company to the email sender
for exmaple
![image](https://github.com/Automattic/WP-Job-Manager/assets/44444912/bea264e8-20a5-4d65-ba34-878b82016658)

please help me i just need code snippet to change the pic  the my logo static i  try to serach in google and chgatpt and nothing not work for me
thanks

**Comment by mikeyarce** [comment]
Please visit the support forums for this type of request: https://wordpress.org/support/plugin/wp-job-manager/
