### ISSUE TITLE
Page Error: There has been a critical error on this website.

### ISSUE THREAD

**Issue by netuck-123** [Automattic/WP-Job-Manager#2833]
**Describe the bug**
I am encountering a critical error on our website whenever I attempt to generate a link for a newly posted job. Immediately after clicking the "Generate Link" button, the message "There has been a critical error on this website" appears, and the link is not created.

This issue is severely impacting our job posting process and preventing us from sharing job openings effectively.

**To Reproduce**
- Log into the website's admin dashboard.
- Go to Job Manager > Job Listing, look for [🛠️ Skilled Construction Workers Needed for Multiple Projects 🚧 (SKAGIT COUNTY AND SURROUNDING AREAS)](https://wa.construction/wp-admin/post.php?post=2623&action=edit)
- Click "Update" button
The error message appears

**Screenshots**
Screenshot Link: https://prnt.sc/Sz_FpzUD7mBY

**Expected behavior**
When the "Update" button is clicked after creating a new job posting:
Link Generation: The system should process the job posting details and generate a unique, functional link that directs users to the full job listing on the website.
No Error Message: No error message should appear on the screen. The interface should remain smooth and uninterrupted.
Link Display: The generated link should be clearly displayed within the job posting management interface, allowing the user to easily copy and share it.
Redirection: Clicking the generated link should successfully redirect the user to the corresponding job posting page on the website, displaying all relevant job details and application instructions.
System Stability: The website's overall functionality should remain stable and unaffected by the link generation process. No other errors or malfunctions should occur.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WP Job Manager plugin is active.
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- WordPress Version: 6.5.5
- WP Job Manager Version: 2.3.0
- PHP Version: 8.1.29
- Other important details: using CPanel for backend

**Comment by netuck-123** [comment]
Just wanted to follow-up on this.

**Comment by mikeyarce** [comment]
Hi @netuck-123 - I can't reproduce this issue with WP Job Manager itself, this sounds like an issue with your specific site or with your server.  I would suggest disabling plugins and switching themes to pinpoint where the issue is coming from.  If you need further help please see our Support page here https://wpjobmanager.com/support/

**Comment by netuck-123** [comment]
Hi Mikey,

It was our theme. Thanks for the heads up.

Kind Regards,

Jelly Anne Lumactud
WordPress Developer and Digital Marketing Specialist
WASHINGTON CONSTRUCTION
Office: 360-858-8580 Ext. 260 | Direct: 360-858-8512

*"Where your IMAGINATION meets our dedication to building PERFECTION"*
*A Subsidiary of Netuck Financial"*
