### ISSUE TITLE
Typescript error in console

### ISSUE THREAD

**Issue by lukesmallman1993** [Automattic/WP-Job-Manager#2834]
Hi,

I am getting the following error in the console:

Uncaught TypeError: Cannot read properties of undefined (reading 'mark')
    at Object.p (wpjm-stats.js?ver=07904eeaa2cdf65ab5ef:1:2600)
    at Object.impression (wpjm-stats.js?ver=07904eeaa2cdf65ab5ef:1:3762)
    at wpjm-stats.js?ver=07904eeaa2cdf65ab5ef:1:3171
    at Array.forEach (<anonymous>)
    at Object.init (wpjm-stats.js?ver=07904eeaa2cdf65ab5ef:1:3096)
    at wpjm-stats.js?ver=07904eeaa2cdf65ab5ef:1:4500

I'm not sure why I am getting this error, I've looked at the file and also the plugins but cant see anything wrong.

Thanks.

![PageSpeed Insights - Google Chrome 18_07_2024 16_50_33](https://github.com/user-attachments/assets/e9b6405e-ad3e-47fa-ab78-3d233db24b73)

**Comment by wgicio** [comment]
I have noticed this coming up very recently as well. I suspect it could be wordpress 6.6 however have not tested this. it was really the only thing that changed when the errors started coming up (maybe there was a woo update as well)

**Comment by Gnodesign** [comment]
The error appears on both the jobs page and the single job page. Additionally, this issue prevents the stats from being saved. Could we get a quick fix for this issue, as the stats are currently not functioning?
@yscik  @fjorgemota

**Comment by wgicio** [comment]
> The error appears on both the jobs page and the single job page. Additionally, this issue prevents the stats from being saved. Could we get a quick fix for this issue, as the stats are currently not functioning? @yscik @fjorgemota

my ajax is returning "success":true,"data" however have not looked at the actual data to see if did save

**Comment by andrewjae** [comment]
I have a similar issue on [](https://www.bestzambiajobs.com/)

I get this error below 


Uncaught TypeError: Cannot read properties of undefined (reading ‘mark’)
at Object.p (41d7e.js?x25378:1:2600)
at Object.impression (41d7e.js?x25378:1:3762)
at 41d7e.js?x25378:1:3171
at Array.forEach ()
at Object.init (41d7e.js?x25378:1:3096)
at 41d7e.js?x25378:1:4500

Kindly help

**Comment by joashrajin** [comment]
+1 at 8511234-zen
