### ISSUE TITLE
Employee Dashboard - Include Reference ID

### ISSUE THREAD

**Issue by SA-FL** [Automattic/WP-Job-Manager#2840]
The default template for the Employee dashboard includes Title, Date, Views, Applications, actions, but it doesn't include the reference number.

With the title likely to have different roles called the same thing, it means you can't differentiate and find the role you may want to review.  Having the reference number would help with this as it should be unique.  It would also help when re-listing roles.

As an example one of my users has hundreds of roles called "mortgage" broker, so it needs to review each to identify the one to relist, having the reference ID would massively simplify this.

**Comment by yscik** [comment]
Hey there! Would you like to include the numeric ID of the job, or do you mean a custom reference ID field? 

Either way, you can customize the dashboard columns with custom code, using filters or [template overrides](https://wpjobmanager.com/document/developer-reference/themes/template-overrides/). 

Here is an example to add the ID after the job title with a filter:

```php
add_action( 'job_manager_job_dashboard_column_job_title', function( $job ) {
	echo ' #' . esc_html( $job->ID );
}, 12 );
```

**Comment by SA-FL** [comment]
So, on the employee dashboard I'm looking for it to add the reference field, I believe the metakey for this is the job_reference.

What would the code be for that?

I would then just add this into the template "Job-Dashboard.php".  Would I need to amend the header too, or would this just pull it through?

Thanks


Spencer Ashby
Finlink, Director
Level 6 Adv DipFA
[Finlink]
01275 400689
Portishead, Bristol, South West

http://www.finlink.co.uk<https://cV-Q104.na1.hs-sales-engage.com/Ctc/I6+23284/cV-Q104/Jks2-6qcW69sMD-6lZ3mVW3W8QPz2NppMbW3GfBDr3H9c4cW7VhX6B6vXc2hW8Y9HCF2vNv1sN6yv2JTnn8NxW86RYCs6nxjdlN547s6T3JRD4N8fgCxj5748wW69HlVt8Y-XQqW7FZPmj14l7tgW4vDkKS1TNzX7W3wRcKq70FK-SW1tc4NG78x66wW1g3Cm178LsYLW7L29rC8Z89gbW3CNDgW8nf-XFW1Sm5zg89x3-3VgGhrX6L88hHV9zMS974pYwkVcMh0h3X3bfxf51cb0C04>

Click here to connect with me on LinkedIn!
***@***.***<https://cv-q104.na1.hs-sales-engage.com/Ctc/I6+23284/cV-Q104/JkM2-6qcW6N1vHY6lZ3mJW3cLn0H5B2g3LN2jkN38KSdrfW4WKftv7qcyYnW7rvl1B36ky-yW1Pwhb67HhPh1VwR5kS6F8BwhW7nqYq21SKvMgW4GRlSg7-N4bTW690v9g7-JL2DW7t9bhw7zy0xXW22dplQ8j6YsLW2QM9wG81WqxVW3lng9n2Qy7MKW7M6ZMZ2JyJfyW7ylb2y3_dcJfN2fj0wp69Z-2W7C6lGc7TypSlW36s6q710rjPZW3YckdH8klmGwW1xQNsZ3l-0P6N1KwNLSnlQYzW4XsPbr85TRf6f6-vl0804>

Finlink ltd is a limited company registered in England and Wales.
Registered number: 12504087
Registered address: A & W Building Newfoundland Way, Portishead, Bristol, England, BS20 7DF

**Comment by yscik** [comment]
If you want it to be its own column, you can add the column via the `job_manager_job_dashboard_columns` filter. 
It would be something like this below.

Note that this is an example you need to adjust to your case.

```php
add_action( 'job_manager_job_dashboard_columns', function( $columns ) {
	$columns[ 'job_reference' ] = 'Reference';
	return $columns;
}, 10 );

add_action( 'job_manager_job_dashboard_column_job_reference', function( $job ) {
	echo ' #' . esc_html( get_post_meta( $job, 'job_reference' ) );
}, 10 );
```
