### ISSUE TITLE
Application Dashboard does not use public link (with key) for candidate name

### ISSUE THREAD

**Issue by kjobs9** [Automattic/WP-Job-Manager#2842]
### Is your feature request related to a problem? Please describe
When a candidate applies for a job AND their resume status = "hidden", the employer canNOT click on the NAME of the candidate to view the resume from the application dashboard. (screenshot<img width="362" alt="screenshot codeable 1" src="https://github.com/user-attachments/assets/74709fb2-eba1-4ee1-aa54-c204a9672770">

### Describe the solution you'd like
Modify the application dashboard, replacing the default link that is used the applicant's name.The replacement would be the WPJM "Public" link that is appended with a key so that the employer can view the resume regardless of whether it's status = "hidden". The employer already receives this link via email, so it seems it only makes sense to also use in the dashboard.

### Describe alternatives you've considered
I've been told there's no way to manage this with settings at the moment. I'm looking at custom dev work.

**Comment by mikeyarce** [comment]
Hi @kjobs9, thanks for the report.  Looking into this I can see that when a resume is hidden, the post is set to `draft` - so there is no public link any more for that resume.  The only way to show the resume if hidden would be to publish it again, which I think would defeat the purpose of hiding it.  In this case I think it's working as expcted for now so I'm going to close this issue out.

**Comment by kjobs9** [comment]
Hi - Thanks for getting back to me. The email that goes to the employer
includes a link with a public key that works, even if it's hidden. I tested
it  and was able to open the resume link it an incognito browser for a
resume that was hidden.

Thanks,
Veronica
