### ISSUE TITLE
Filter Street Number Order

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#381]
Many places don't use the street number before the street name. Thoughts on a filter around the built street address so the number and name can be arranged depending on the country?

**Comment by mikejolley** [comment]
Would it be better to split the meta data rather than join them then? If not, feel free to do a pull req with how you need it handled.

**Comment by spencerfinnell** [comment]
Yeah splitting them would be the best. 

The default usage doesn't use any of the parts separately right so no need to worry about backward compatibility?

**Comment by mikejolley** [comment]
I think thats correct.

**Comment by cassim1** [comment]
As long as we get it like :
Street, Number 
Zipcode, City 

Im happy :)
