### ISSUE TITLE
New widgets

### ISSUE THREAD

**Issue by mikejolley** [Automattic/WP-Job-Manager#408]
- Recently viewed
- Popular

**Comment by solhuebner** [comment]
:+1:

**Comment by unirvrsl** [comment]
Where is the documentation for Applications plugin?

**Comment by mikejolley** [comment]
@unirvrsl same place as all of the docs https://wpjobmanager.com/documentation/add-ons/applications/

**Comment by unirvrsl** [comment]
TY... Trying to find out how to remove C/V or at least NOT make it mandatory upon applying for job

**Comment by mikejolley** [comment]
The doc on editing fields should help. v2 will have a form editor. Please use wpjobmanager.com/support/ for future questions - github is for bug reports only.

**Comment by mikejolley** [comment]
I'm going to scrap this idea for core because counting views will be affected by things such as static caching. 

I do know however that @spencerfinnell and Adam were working on a stats plugin - would be perfect for that guys? Since you'll be counting views so can calculate popular jobs easily.
