### ISSUE TITLE
Add helper functions to retrieve list of frontend/admin fields

### ISSUE THREAD

**Issue by mikejolley** [Automattic/WP-Job-Manager#492]
To allow plugins to get the field list from anywhere; not just admin/writepanels.

**Comment by wpmark** [comment]
Hi @mikejolley. I have done an implementation similar to this in my WP Broadbean (stand-alone) plugin. You can see I have a function here which includes a filter:

https://github.com/wpmark/wpbroadbean/blob/master/functions/wpbb-functions.php#L7-L16

Fields added here contain all of the different arguments needed in the different parts of the site. For example args for meta boxes and also front-end display etc. Default fields are added here:

https://github.com/wpmark/wpbroadbean/blob/master/functions/default-fields.php

When they are need I then just call the function, which contains all the filtered fields:

https://github.com/wpmark/wpbroadbean/blob/master/functions/admin/metaboxes.php#L16

Maybe something similar would work - fingers crossed and thanks.

**Comment by wpmark** [comment]
Is there a way to get the field list - added by any plugins as sites running the add ons will have additional fields, particularly add-ons that offer the field editor experience, even from within the admin?

I can't find a solution apart from what I have suggested above?

**Comment by mikejolley** [comment]
@wpmark best you could get would be the fields AFTER they have hooked themselves in so you get the final, modified list of fields.

**Comment by wpmark** [comment]
Thanks for getting back so quickly, have you got a code snippet that would do that. My brain is struggling to come up with something :-)

**Comment by mikejolley** [comment]
If you're running the fields through the same filter as core, shouldn't that just work?

**Comment by wpmark** [comment]
This is probably me being really silly but normally I would add stuff to a filter like this:

```
function add_stuff( $fields ) {
  $fields[ 'mystuff' ] = array(...)
}
add_filter( 'filter_name', 'add_stuff', 10, 1 );
```

All the other plugins will do the same. However how to do I get all of what has been added. I thought it this:

```
function get_fields( $fields ) {
  return $fields;
}
apply_filters( 'filter_name', 'get_fields', 999, 1 );
```

However when you call the function it expects you to pass it the fields which is what I want it to return. I am sure I am doing this wrong but if you could help that would be great.

**Comment by mikejolley** [comment]
Hmm yes what I was suggesting would need the 'initial' list of fields. You need the function helper this issue is for.

In the interim, can you not include the writepanel class and use the method in core? Will work until we add the functions. I don't think the filters will help, unless you duplicate the initial array of fields in your plugin which sucks.

**Comment by wpmark** [comment]
Even if I include the write panel class, actually when I think about it this will only return me the core fields from the core plugin won't it and not the fields other plugins have added?

**Comment by mikejolley** [comment]
@wpmark all plugins use the filter, so as long as those plugins are using and have their hook in place, it should adjust the fields.

**Comment by wpmark** [comment]
So therefore including the class and then something like this:

```
$fields = new WP_Job_Manager_Writepanels();
$fields = $fields->job_listing_fields;
```

`$fields` would then contain the array of fields added by all plugins and the core plugin?

**Comment by mikejolley** [comment]
Yes, if the plugins are hooked in by the time you call that method.. in theory.

**Comment by wpmark** [comment]
That seems to just give an error. I have this code:

```
require JOB_MANAGER_PLUGIN_DIR . '/includes/admin/class-wp-job-manager-writepanels.php';
$fields = new WP_Job_Manager_Writepanels();
$job_fields = $fields->job_listing_fields;
```

Which is now throwing this error:

'Undefined property: WP_Job_Manager_Writepanels::$job_listing_fields'

Any ideas? Thanks

**Comment by mikejolley** [comment]
Yeah, its a method not a variable. ->job_listing_fields()

**Comment by mikejolley** [comment]
Need to give this more thought since there are backend and frontend fields. Maybe a single function with an arg to get either or.

**Comment by tripflex** [comment]
:+1:

**Comment by jom** [comment]
Fields can be retrieved with `WP_Job_Manager_Writepanels::instance()->job_listing_fields()`
