### ISSUE TITLE
Shortcodes: Allow job_summary shortcode to output >1 job

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#495]
If you don't specify a job ID when using the `[job_summary]` shortcode, we just choose a single job at random:

https://github.com/Automattic/WP-Job-Manager/blob/1.23.4/includes/class-wp-job-manager-shortcodes.php#L433-434

... but it would be cool if we could up that limit and get multiple job summary cards in one go:

![screen shot 2015-07-08 at 10 33 01 am](https://cloud.githubusercontent.com/assets/5512652/8572848/b9f0c982-255c-11e5-88f2-509a4d6742e8.png)

Mentioned in Help Scout ticket 6287.

**Comment by nervewax** [comment]
Ideally, you could specify that the [job_summary] should output a specified number of job cards and also add the option to limit it to featured jobs, in the same way the [job] shortcode does.

**Comment by aheckler** [comment]
> also add the option to limit it to featured jobs, in the same way the [job] shortcode does.

This already exists I think:

https://github.com/Automattic/WP-Job-Manager/blob/1.23.4/includes/class-wp-job-manager-shortcodes.php#L422
