### ISSUE TITLE
mailing settings

### ISSUE THREAD

**Issue by shorif2000** [Automattic/WP-Job-Manager#497]
On contact form 7 there are 2 mail sections available to 2 separate emails can be sent out. however when using application form this gets overidden by the job plugin to pick up only the email address set in the job post. there is no multiple mail sections to address 2 different types of mail as contactform7. How can i implement this?

**Comment by mikejolley** [comment]
This is not a core issue.

Job Applications plugin sends out 2 emails; one to the job poster (email in job listing) and one to the applicant (email entered on form).

**Comment by shorif2000** [comment]
I have tested this plugin and never recieved an email as an applicant?

**Comment by mikejolley** [comment]
It needs to be setup in the 'application form' settings. Use the support area anyway; github is not the place for support. https://wpjobmanager.com/support/
