### ISSUE TITLE
Problem with WPML and the AJAX job listing

### ISSUE THREAD

**Issue by Gandhi11** [Automattic/WP-Job-Manager#498]
Hello there, I'm currently testing your plugin in order to buy the Unlimited core Add-ons and I have some problems. I'm currently using WPML on my site and I created jobs in English and French, but when I try to view the job listing in each language the results are allways in the default language(English).

You can view an exemple here : 
English : http://outils.bang-marketing.com/jobs/
French : http://outils.bang-marketing.com/fr/postes/

In french the job should be Dévellopeur Web.

The page language seems to be well pass to the ajax query but it look like the ICL_LANGUAGE_CODE at line 121 of the function 
get_job_listings in wp-job-manger-functions.php allways contains the default language.

Thank you

Wordpress : 4.2.2
WP Job Manager : 1.23.4
Theme : Divi : 2.4.5.1

**Comment by spencerfinnell** [comment]
@mikejolley  We're including this in the next release of Listify for compatibility https://gist.github.com/spencerfinnell/15b18c3a625e99779d0e -- but would be nice if it was done automatically.

It passes the lang parameter forward to the query (it's sent via AJAX but then never used again). Also adds the default language listings to the current language results if they aren't translated, as well as translating category dropdown (#493)

**Comment by Gandhi11** [comment]
Humm ok? So what can I do for now?

**Comment by mikejolley** [comment]
@Gandhi11 Please ask on the WPML forums - ICL_LANGUAGE_CODE should be the current language. If thats not right, it won't work with Job Manager which uses ICL_LANGUAGE_CODE to pass the 'lang' to the ajax request. If WPML need a change to https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager.php#L159 they can post here or email me.

**Comment by pierre-otgs** [comment]
Hello, I tried to send an email about this issue but it looks like you didn't received it.
Here's a suggested fix concerning this issue https://github.com/pierre-otgs/WP-Job-Manager/commit/46d40e8e8d4a778e590587def44924b7f1224789.
