### ISSUE TITLE
Conditional Fields for Submission Form & Advanced Search

### ISSUE THREAD

**Issue by jamesprismall** [Automattic/WP-Job-Manager#499]
Hello everyone!

I and many others I have chatted too have long wanted conditional fields for both the submission form and also to have an advanced search page. I currently have nearly 700 categories and child-categories - which has I think around three levels. What I would really like to have have is:

Step 1 > Top Level Categories > Pick Category
Step 2 > Reveal Second Level Categories > Pick Category or Multiple Categories
Step 3 > Reveal Third Level (If They Exist)
Step 4 > Reveal Forth Level and so on.. 

This would give our users a much better user experience when firstly submitting a new listing and also for visitor searching for listings.

Hopefully this is something that you could do for us!

James

**Comment by mikejolley** [comment]
Hi James,

This is something I will log as an idea on our roadmap, but tbh I have not seen much demand for this, so if you need it soon-ish you may want to get a developer to build it rather than wait :)

Thanks

**Comment by tnchuntic** [comment]
Just checking if this functionality is available on 2021 Applications add-on? Seems that the application add-on doesn't have it. Its been 6 years already :(
