### ISSUE TITLE
AJAX issue when applying with the Resume Plugin (shows  “>+ Add Experience )

### ISSUE THREAD

**Issue by csamp516** [Automattic/WP-Job-Manager#500]
When I click the "Preview" button when applying for a job, a bunch of new fields are loaded and at the bottom there are it shows “>+ Add Experience and another Preview button.  When that Preview button is clicked, another set of the new fields are loaded.  This affects the functionality of the whole application process.

I've updated both the WP-Job-Manager and Resume Manager plugins to their latest versions.  Nothing in the browser's error console.  Happens whether I am logged in or not.

Sample site:  http://radium.samperisi.com/apply-now

**Comment by tripflex** [comment]
Did you add any of your own custom code that affects the fields, either through a filter or something else?

Are you using any plugins like the field editor or custom fields?

**Comment by mikejolley** [comment]
I've seen this happen due to plugin conflicts so you should rule others out. Then use the correct support area since this github is for core only. Thanks.
