### ISSUE TITLE
Pre-Selection in job category multiselect.

### ISSUE THREAD

**Issue by jannnik** [Automattic/WP-Job-Manager#501]
It would be nice if I could set a preselection on the multiselect category filter:
If I show a list with all job listings and the filter on top, only the placeholder "choose a category" is shown while all categories are selected. The placeholder disappears first if I select a category.

Is a preselection on the multiselect already possible?

**Comment by tripflex** [comment]
Yes it actually already is, you can set the `default` argument in the field config array. If you're using a taxonomy you can set it to the actual value or set as an integer to set default by the term ID.

Check out the field template files in the templates directory

**Comment by jannnik** [comment]
taxonomy=job_listing_category&tag_ID=208&post_type=job_listing
If I use the ID 208 as value for the ´default´ or the ´selected´ argument, it does not work.
				<?php job_manager_dropdown_categories( array( 'taxonomy' => 'job_listing_category', 'hierarchical' => 1, 'default' => 1,'name' => 'search_categories', 'orderby' => 'name', 'hide_empty' => false) ); ?>

What am I doing wrong?

**Comment by mikejolley** [comment]
Depending on the values, 'selected' should be set to a term ID or slug. View the source to see if the values are slugs or IDs in your case.
