### ISSUE TITLE
Allow bulk license activation

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#502]
Would avoid this:

![screen shot 2015-07-20 at 3 30 23 pm](https://cloud.githubusercontent.com/assets/5512652/8785229/42e3fa5c-2ef4-11e5-8c88-e49b31196665.png)

... which can happen easily if you (for example) deactivate all plugins to test an issue on your site.

(Wasn't sure where to put this, but basically it affects every add-on as well.)

**Comment by mikejolley** [comment]
In latest version you can add your keys and submit all extensions in one post.
