### ISSUE TITLE
Location filter not working

### ISSUE THREAD

**Issue by taylorm370** [Automattic/WP-Job-Manager#503]
I can't seem to get the Location filter to filter out jobs that don't include the search term. I did have the "Predefined Regions" plugin activated, but deleted it when I ran into it overriding the Location information on the single jobs. If you search the location in the "Keywords" field however, it does filter out the other results. 

Can you help us fiture out the problem? Our web page with the jobs that is having those problems is listed below. Thanks.

http://imagingigloo.com/careers/available-jobs

**Comment by mikejolley** [comment]
The location field has been commented out by yourselves: https://dl.dropboxusercontent.com/s/dotnu9kgbfuyc3r/2015-07-25%20at%2014.29.png?dl=0
