### ISSUE TITLE
Allow re-approval after edits

### ISSUE THREAD

**Issue by mikejolley** [Automattic/WP-Job-Manager#509]

**Comment by designlab9898** [comment]
This is something to look into. Would be a great enhancement to allow Employers to able to edit their posted jobs but any edits will require admin to approve before it is published again. This will prevent Employers from make edits on one job that contains illegal entries which required admin review first.

**Comment by designlab9898** [comment]
Hi Mike, is there any progress on this feature. This would be really important for employers to manage dynamic content for their jobs, but any edits will set this job as Pending for Review.

**Comment by designlab9898** [comment]
Is this possible?

**Comment by mikejolley** [comment]
It's possible, just not planned short term.

**Comment by designlab9898** [comment]
How should it be done? Does it require core file modifications? I'm using
Fields Editor by myles

**Comment by mikejolley** [comment]
If I knew the exact steps to implement this I would have coded it already :p

**Comment by designlab9898** [comment]
Thanks Mike. Really appreciate if you could implement this feature.

**Comment by ekajuan** [comment]
I've found the answer, seems to work, please check it. 

```

add_action ('job_manager_update_job_data', 'update_job_post_status_publish_to_pending', 10,1);

function update_job_post_status_publish_to_pending($job_id) {
  $post_status = get_post_status( $job_id );
  
  if ($post_status == 'publish'  ) {

    $my_post = array(
        'ID'                => $job_id,
        'post_status' => 'pending',
    );
    
    wp_update_post(  $my_post ); 
    
    delete_post_meta( $job_id, '_job_expires' );
  }
}
```

**Comment by jstane** [comment]
Hi all   :)

It's in last update please  ?
It's an important issue, my customers correct their listing, they put in error the site and then it is the horror to find who modified what... to repair website...

Thanks !

**Comment by designlab9898** [comment]
I second to that. Because this is a public Listing website/plugin sometimes
we will never know the person who added the Listing looks ok and legit when
we approved, but after that the person edited the same listing and start
advertise illegal stuff, and the Admin doesn't even know that's been
approved in the website. Horrible story if that happens. My whole website
might get banned by my hosting provider for such carelessness

**Comment by jenhooks** [comment]
Requested here: 2664027-t

**Comment by designlab9898** [comment]
Don't put your hopes high. I posted this few months back, looks like it's
not gonna happen

**Comment by jstane** [comment]
I don't understand ? This function is integrated ?
I'm waiting this too...  :(

**Comment by adamhurlebaus** [comment]
I have an edit that worked for me.  Two files will need to be changed: 
[Adds setting to enable/disable feature](https://github.com/Automattic/WP-Job-Manager/commit/da86d39a0cb6209a024f8248d1b7e0bc6d254a9d)
[Adds code to job edit form](https://github.com/Automattic/WP-Job-Manager/commit/66178184ae50dd83d30a132bca186cb990c2af8b)

Unfortunately without a specific action or filter in the class-wp-job-manager-form-edit-job.php file, I haven't figured out an easy way other than a core plugin modification.  Maybe this is something worth committing to core, but the downside to me is that it would hide the job listing on the front end until it is re-approved.  The best case scenario would be to save the submitted edit as a draft revision until approved, as opposed to changing the status to pending as I have done with the code.

I don't recommend editing the core plugin file, but these revisions did work for me.

**Comment by jenhooks** [comment]
2675894-t

**Comment by nikhilgkurup** [comment]
hi , any good news ?. is this problem corrected ? any one has any solution for this problem ? my website is giving head ache to me due to this problem . users post unnecessory things after getting an approval by editing the pages

**Comment by aheckler** [comment]
2923529-t

**Comment by creowings** [comment]
What is it 2923529-t ? 

if you already have a solution to the editing of the employer's administrator had to accept

**Comment by aheckler** [comment]
> if you already have a solution to the editing of the employer's administrator had to accept ??

We don't have a solution for this yet.

**Comment by annezazuu** [comment]
Brought up in 3047148-t

**Comment by danjjohnson** [comment]
Requested in 3095666-t

**Comment by bikedorkjon** [comment]
3180785-t

**Comment by annezazu** [comment]
3264200-t

**Comment by davoraltman** [comment]
660664-zen

**Comment by MickyDncl** [comment]
This is a huge problem for me, I bought listable a directory theme and this issue is stopping my project in its tracks. It's crazy to allow people freedom to edit and link to whatever they want after I've approved the initial listing. Why has this not been rectified? Or am I missing something.

**Comment by jom** [comment]
I am working on this for 1.30.0. In the example above the expiration date gets reset once re-approved. Is this what is generally expected or should it maintain the original expiration date?
(React to this comment: ❤️ = reset expiration date, 🎉 = expiration date left as is) Either way, I'll put a filter in it to override. 

Without getting too complicated, the post will become unpublished while awaiting moderation.

Example copy for settings (feedback definitely welcome):
<img width="875" alt="screen shot 2017-12-20 at 4 11 06 pm" src="https://user-images.githubusercontent.com/68693/34234525-7c589e40-e5a0-11e7-8bd9-5d299100111f.png">

**Comment by designlab9898** [comment]
🎉

**Comment by MickyDncl** [comment]
Thanks Jom its great that this is scheduled in and those options in the screenshot look great. Do you have a planned release date?  I would be more than happy to test a beta version if you want to send it over.

**Comment by jom** [comment]
@MickyDncl No planned date, but it should ship with the next release (1.30.0).
