### ISSUE TITLE
Display bug for admin fields following recent upgrade to latest version (1.23.6)

### ISSUE THREAD

**Issue by hobailey** [Automattic/WP-Job-Manager#512]
Is this display normal (where the input labels are all overlaid on the actual input)?
![image](https://cloud.githubusercontent.com/assets/1564439/9219001/d98c7e9e-40d7-11e5-98fa-82dc201948d7.png)
I've reinitiated the cache etc, so I can't see what's wrong - but perhaps I'm missing something crucial?
Thanks

**Comment by mikejolley** [comment]
One of your JM plugins is also out of date. May be resumes or applications. Then clear all caches. This isn't a bug - its old CSS from something else.

**Comment by hobailey** [comment]
Ah yes, you're right (there was another bug saying a plugin was up to date when it wasnt) - thanks for your help and sorry for such a noobie issue
