### ISSUE TITLE
Need to know if candidate has active resume

### ISSUE THREAD

**Issue by nielszandsteeg** [Automattic/WP-Job-Manager#513]
Hi,

I need to know how I can check if a candiate has an active resume.

I've tried alot and checked around, but I can't find the right solution. 

Does somebody has that for me? 

Thanks,

Niels

**Comment by mikejolley** [comment]
Use a 'get_posts' function, for post_type 'resume' and pass in the author attribute as get_current_user_id(). That will get a users resumes. Closing this however, its not related to Job Manager core.

**Comment by nielszandsteeg** [comment]
Thanks anyway! Helped me out! :-)
