### ISSUE TITLE
Category fields don't prefill when modifying a job

### ISSUE THREAD

**Issue by brianheap** [Automattic/WP-Job-Manager#514]
Hi,
I have the latest version of Jobify and associated JPM installed etc, and after the latest list updates, when adding a job and on the "preview your job advert" page, if you click the "Edit" button to go back and edit various things, the 3 job categories fields aren't prefilled (the region, job type and job category). Is this a bug or have I broken something?
Thanks.

**Comment by mikejolley** [comment]
Tested; submitted a type and category, clicked 'edit', took me back and the fields were already set.

**Comment by brianheap** [comment]
Ah yes, I'm sorry for the false alarm. Was infact a bug just with the job_region select box (which is a different plugin) and was fixed with this (https://github.com/Astoundify/wp-job-manager-regions/commit/13e9fce2b40391b998270c8f0bd6bb2e036ab5fd) however not included in the release directly afterwards (which was somewhat confusing...).
Thanks for your response and time all the same.
