### ISSUE TITLE
Edit Job Listing but previous photos uploaded went missing

### ISSUE THREAD

**Issue by designlab9898** [Automattic/WP-Job-Manager#515]
Hi. I'm using Fields Editor, when I try to edit a job (Listing Page), I can see all the previous photos uploaded appears. But if i upload a new photo and save the Job, it looks like only the latest photo appeared. Previous photos disappeared.

**Comment by tripflex** [comment]
This is not the place for support with field editor, please submit a support ticket for any field editor support requests.

**Comment by designlab9898** [comment]
yes, maybe wrong place to post here. but you guys really didn't answer to my support tickets!

**Comment by mikejolley** [comment]
@designlab9898 This is the repo for core WPJM. I/this does not have a relation to @tripflex's field editor. I'm sure @tripflex will get back to you soon if you made a ticket :)
