### ISSUE TITLE
Limit number of Files Uploaded

### ISSUE THREAD

**Issue by designlab9898** [Automattic/WP-Job-Manager#516]
Is there any option to limit the number of files that are allowed to be uploaded depends on the Job Package?

**Comment by blue928** [comment]
I can't see it if it's available, but I believe this would be a great enhancement.

Currently I'm altering my $fields (Logo) array to contain 'ajax' => 'true', 'multiple' => 'true'.  It would be great if we could have one more  as 

'limit' => '4' (or some number)

**Comment by tripflex** [comment]
+1 I could also integrate this info field editor very easily if core handled it

**Comment by mikejolley** [comment]
Yeah this could be good to have.

**Comment by kochhase** [comment]
Hi Mike, 
is there a timeline to integrate it in core, so that myles can enhanced his plugin?

**Comment by kochhase** [comment]
Hi Mike and Myles,
Is there now a way to Limit number of uploaded Files?

**Comment by tripflex** [comment]
@mikejolley getting a lot of requests for this, any status update on if this will be added to core?  Thanks

**Comment by mikejolley** [comment]
@tripflex How would you think this needs handling? I think the multi-upload script has a setting for it, but we'd need to pass the max limit to it somehow.

**Comment by jonathandezoete** [comment]
Semi/temp solution for this:

jQuery(function() {
       jQuery('.wp-job-manager-file-upload[multiple]').on('click', function(e) {
          if(jQuery('.job-manager-remove-uploaded-file').length > 5) { alert('Max 6 images'); e.preventDefault() ;}
       });
    });

**Comment by ekajuan** [comment]
If the limit is set to 5, why not just create 5 boxes of image uploader? Each box can only be filled with 1 image. The upload method can by selecting an image or drag and drop

**Comment by designlab9898** [comment]
Is this feature possible?

**Comment by jammin138** [comment]
Does anyone know if this is coming anytime soon? Would be a fantastic feature!

**Comment by brasilh** [comment]
Guys,

Where i imput that code:

jQuery(function() {
       jQuery('.wp-job-manager-file-upload[multiple]').on('click', function(e) {
          if(jQuery('.job-manager-remove-uploaded-file').length > 5) { alert('Max 6 images'); e.preventDefault() ;}
       });
    });

Please, update the plugin with the limit option, that causing a lot of problems for me.

Thanks for all!

Rafael

**Comment by jammin138** [comment]
@mikejolley @tripflex , Hey guys, is this something you're still looking in to doing? Any ideas if how we can get this off the ground? Will this be supported in future updates if we can get this up and running. 

best wishes

**Comment by davoraltman** [comment]
+1 2672102-t

**Comment by bbostan** [comment]
Hey guys, 

this is a very importan point. What is the current status of that implementation? How can I use the code, which is commented above? 

Please help! Please!!! :D

**Comment by jammin138** [comment]
@bbostan I agree, this is an important feature. Unfortunately I've not been getting any feedback on it's status and I've resulted in manually limiting the amount of images that are uploaded. Far from perfect.

**Comment by bbostan** [comment]
@jammin138 can you maybe help me to limit the amount of images manually? (My E-Mail is berkant@gelinim.de ... )

**Comment by jammin138** [comment]
@bbostan I quite literally have to check new submitted listings as they're uploaded. Not ideal, but it works. It allows me to offer customers with free listings a restricted amount of images and paid user unlimited images.

**Comment by bbostan** [comment]
@jonathandezoete Hey Jonathan, where do we have to input the commented code for your solution? A lot of people are asking for that ... 👍

**Comment by jonathandezoete** [comment]
You can output it anywhere on the page where the upload fields are showing!
I have it in a child theme that overwrites the templates/job-submit.php file. So that would be a good place.

**Comment by bbostan** [comment]
@mikejolley Is it not time to implement this feature?

**Comment by jammin138** [comment]
I managed to get the code working that @jonathandezoete kindly supplied. I'm using "WP Job Manager Field Editor" with my website and put the following code: 

<script>
jQuery(function() {
       jQuery('.wp-job-manager-file-upload[multiple]').on('click', function(e) {
          if(jQuery('.job-manager-remove-uploaded-file').length >= 5) { alert('Max 5 images'); e.preventDefault() ;}
       });
    });
</script> 

into the job "description" field itself. The issue I'm having is if a user uploads one image at a time it works fine, but the user selects multiple images to upload the code doesn't work. I don't suppose anyone has a fix for this?

bw,

**Comment by bbostan** [comment]
@jammin138 Can you maybe expain how exactly you put the code in to the descripton field? Do you really mean it like the picture. I can't believe that this will work ...
![github](https://cloud.githubusercontent.com/assets/19611611/16547253/37857d08-4167-11e6-9f60-628b04a130b6.jpg)
..

**Comment by jammin138** [comment]
@bbostan you have to surround the code with script tags:

```<script>
(Code here)
</script>```

I'm on mobile so I can't copy and paste the entire code sorry

**Comment by designlab9898** [comment]
hi guys, if you got this feature working with WP Job Manager - Fields
Editor UI, please let me know. if it works, we can set different Job
Packages and set each File Uploaded Limit for each different Package. Free
Package (maybe accept only up to 5 images), Basic Package (up to 10-15
images), Pro Package (unlimited images can be uploaded), that would be
really cool, when this feature is added directly into Fields Editor plugin.
thanks for all the help

On Mon, Jul 4, 2016 at 4:12 AM, jammin138 <notifications@github.com> wrote:

> @bbostan <https://github.com/bbostan> you have to surround the code with
> script tags:
>
> (Code here)
> </script>```
>
> I'm on mobile so I can't copy and paste the entire code sorry
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Automattic/WP-Job-Manager/issues/516#issuecomment-230172801>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ANNiDOCR_lfL31vhscBYJC02py5OUfHrks5qSBfEgaJpZM4FtobJ>
> .
>



-- 
Sent by,
*DesignLab Solutions *
*JM0697683-V*


*Contact Number: +6017 788 6632 (MR. ALVIN GAN)*

*PREMIER COMPANY ADVERTISING, WEBSITE DESIGN, E-COMMERCE, PLATFORM
CUSTOMIZATIONS, SUPPORT & TRAINING*

**Comment by Goakgoak** [comment]
I tried the solution as in the picture above, surrounded by <script> tags, and all the same business as before, user can upload as many pictures they want.

**Comment by Goakgoak** [comment]
I tried the solution as in the picture above, surrounded by <script> tags, and all the same business as before, users can upload as many pictures they want.

**Comment by brasilh** [comment]
Guys,

this feature is very important for everbody. 

Is not just on Image Gallery, this option need to be able on all fields like category or tags.

We are waiting.

**Comment by Goakgoak** [comment]
Tags 
Listing -> settings -> submission.

**Comment by jammin138** [comment]
@brasilh 

This is a picture of it setup on my website. Like I've said the issue I have is if the user tries to upload more then one image at a time the code doesn't work. It only works when a use uploads each image individually. 

Ideally I think something should be set up so that users can upload a limited amount of images for free and if they pay for a more "premium" account they then get more images...

<img width="686" alt="screen shot 2016-07-04 at 18 37 24" src="https://cloud.githubusercontent.com/assets/17796043/16567488/22b37654-4217-11e6-90dc-d6b9d32aa567.png">

**Comment by Goakgoak** [comment]
Yes, I had first uploaded one by one very fast, now one by one until is fully uploaded, and no difference.

**Comment by infernal31** [comment]
Oh god one years i really want to cry

**Comment by tripflex** [comment]
It's on the way to be included with the next release of Field Editor plugin, hopefully getting it out this week (plan is for tomorrow)

**Comment by Goakgoak** [comment]
Sorry about the stupid question, do we need to call Jquery somewhere else?
Because I added that script in my description and didn't make the trick.
On the bright side, I was happy to hear the last email that we will have
that option out of the box. Thank you.

**Comment by jammin138** [comment]
@tripflex I'm going to give you a virtual high five when this comes out! Great work

**Comment by juniorterin** [comment]
You can use jQuery slice to remove the excess

var $limiteDeFotos = 5; // how much uploads 

var $auto_refresh = setInterval(function () {

  $('.main-class-of-your-field .job-manager-uploaded-files > .job-manager-uploaded-file').slice($limiteDeFotos).remove();

    $autoUpdate();

  }, 1000);

**Comment by juniorterin** [comment]
You can use jQuery slice to remove the excess

`var $limiteDeFotos = 5; // how much uploads

var $auto_refresh = setInterval(function () {

$('.main-class-of-your-field .job-manager-uploaded-files > .job-manager-uploaded-file').slice($limiteDeFotos).remove();

$autoUpdate();
}, 1000);`

**Comment by juniorterin** [comment]
jQuery slice may solve this problem with a client-side parse

```
var $limiteDeFotos = 5; // how much uploads

var $auto_refresh = setInterval(function () {

$('.main-class-of-your-field .job-manager-uploaded-files > .job-manager-uploaded-file').slice($limiteDeFotos).remove();

$autoUpdate();
}, 1000);
```

**Comment by tarrazon** [comment]
Hi, nobody find a solution ?

**Comment by jammin138** [comment]
@tripflex It's up running perfectly! Thanks for adding this feature, great work.

**Comment by tripflex** [comment]
Hey sorry guys forgot to post on here, the latest update 1.5.0 includes this new feature, plus enhancements I made to it.  

Initial check is done on frontend using JavaScript/jQuery for maximum images, both for ajax and non-ajax uploads.  Once the user submits the listing, it is also checked via PHP to make sure nobody works their way around the frontend JavaScript.

If the field doesn't have a custom description, it will also now show the max files allowed next to max filesize

Here's the changelog for latest:
http://plugins.smyl.es/wp-job-manager-field-editor/changelog

**Comment by DomMTL** [comment]
Hi, I would like to output the images as a modal image gallery (with lightbox). Is anyone here achieved such functionality with custom code or have heard of such plugin? Where should I start?

**Comment by tripflex** [comment]
@DomMTL just noticed your reply when reviewing this, the latest version of field editor now includes a new output as "WordPress Image Gallery" which will output thumbnails and then open then in a lightbox when clicked.
