### ISSUE TITLE
Listify Business Registration Page

### ISSUE THREAD

**Issue by mr110pure** [Automattic/WP-Job-Manager#519]
Hey Guys,

Is there anyway you can change the category selection on the registration form? It would be nice if owners can select a main category, and then a sub-category from that main one, instead of having to scroll through everything. Registering on a mobile device is a nightmare. lol Thanks!

**Comment by tripflex** [comment]
I think you're referring to conditional field types, i'll let @mikejolley weigh in on that one ...

**Comment by mikejolley** [comment]
It's not possible to split these up right now, but Ill note on roadmap. Could be made custom.

**Comment by mr110pure** [comment]
Is there someone you can recommend to do the custom work? The developers
I've reached out to on the recommend sites don't have a clue. Thanks

On Monday, October 5, 2015, Mike Jolley <notifications@github.com> wrote:

> It's not possible to split these up right now, but Ill note on roadmap.
> Could be made custom.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/WP-Job-Manager/issues/519#issuecomment-145570790>
> .
>


-- 
110% Pure
C.E.O
Point Blank Productions, Inc.
110 Percent Pure Publishing
Flawless Society
Grimey League
773.426.1477

**Comment by mr110pure** [comment]
<https://email.gofundme.com/ls/click?upn=S1RhcN80TQW1yVenQ-2BBoJhtxLH5Ht-2BSVVY3p2-2FkWMkx0TOkjQ05vtlP37mNK7UWe6qJ4QWfm6-2BhXUrrM-2BCroBbM9R4-2BQG-2BJgzXW-2FuL-2BLYTqW5X6zXSlvxuAoAbH852Wd5tQ96NCaiIZ2UJW0JHx0GSzzVaAzDwNYafLxt3jhtGA-3D9sJA_MQUFcoWv1-2FLxBDNNs3puwyPlqKQ6-2BrhKCO8LOwzUC2ldypvBh8g5JVLkhnOW5qgMniwT6uvsiTsn2fI44WbaDSplAROSjeEPE1Wc5sT78bhnKytJQVi28wjcUvLFy2VjW3GJP3vopkw2TLVFVzoM2KVsGqajzuvADz-2BcYxKwbYP7DN4rj-2BWplMyIUdn1B3Gb9FDlb7MFP-2BC80bT-2BLxSpEQDDQb65i7Xm2cksERtSQbiLyS52VGlvWwofNlr9fMVGNlCEKi7MxHSs-2B9XY4W6wHA-3D-3D>
<https://email.gofundme.com/ls/click?upn=McCelgEyxf19hZNOeSlreO6HA-2BSfGiGcMLzCiS-2ByOInE04FlC-2F5y-2FLNQ9z-2B1C2clxOTgjZaYC74J0fZvdvIBk3dOumZ-2Bf1sEvRA2Zd5lygzhtGCAgJWyflwI8AXsMf2w0los0az3G-2B3eG43-2Fcpw56FA-2FfpuY1s2QEUsFhGttI0os5LGutm1CtonTawymKf0S432jaqUtqG6-2FlacKi1pV44ivgUs5p5y7iIndscYwO1Gc1LqTqjc-2FcWRKhhYUrP3SkPDdwFqvQPiGYgwVmVtvJe2yJSbwAwLBs69nCwPyy3TP4jhY3-2B31SVX9PY2Hh2a7kQjiVIMo1o-2F4hqxr8GSr7A-3D-3DU4Fq_MQUFcoWv1-2FLxBDNNs3puwyPlqKQ6-2BrhKCO8LOwzUC2ldypvBh8g5JVLkhnOW5qgMniwT6uvsiTsn2fI44WbaDSplAROSjeEPE1Wc5sT78bhnKytJQVi28wjcUvLFy2VjHCD8jhMG6HfpO5Wcp9HkJqU6pciC55ZUOUdgF9sJWmsLdJmEHjF9WH3GKIl4gxM3ViQRNLEam5IQcYpMLqqN9h4liQLdRCsunEeqs-2B3hQGjllME7YGWu5xXlIPLcTjS-2Fu1bdMfyFtvSk-2FkM3xk3jQg-3D-3D>
Matthew "Pure" Bradley would like you to support Children's Indigenous
Health Education Program
<https://email.gofundme.com/ls/click?upn=McCelgEyxf19hZNOeSlreO6HA-2BSfGiGcMLzCiS-2ByOInE04FlC-2F5y-2FLNQ9z-2B1C2clxOTgjZaYC74J0fZvdvIBk3dOumZ-2Bf1sEvRA2Zd5lygzhtGCAgJWyflwI8AXsMf2w0los0az3G-2B3eG43-2Fcpw56FA-2FfpuY1s2QEUsFhGttI0os5LGutm1CtonTawymKf0S432jaqUtqG6-2FlacKi1pV44ivgUs5p5y7iIndscYwO1Gc1LqTqjc-2FcWRKhhYUrP3SkPDdwFqvQPiGYgwVmVtvJe2yJSbwAwLBs69nCwPyy3TP4jhY3-2B31SVX9PY2Hh2a7kQjiVIMo1o-2F4hqxr8GSr7A-3D-3D23F1_MQUFcoWv1-2FLxBDNNs3puwyPlqKQ6-2BrhKCO8LOwzUC2ldypvBh8g5JVLkhnOW5qgMniwT6uvsiTsn2fI44WbaDSplAROSjeEPE1Wc5sT78bhnKytJQVi28wjcUvLFy2VjsoA83Ex0D68Ajp2dvgyFSmVXfCRrObL7h2iqOIjvZFT7zOceuFfeAfjarfNdxrLU4F2We3CD-2FDQW9hT9OVc8i6-2FrMzk4492khr6tr3s-2BwFnM6agRW6xkAORrPB2dxdXlz7D-2Bzb6whqkUnr0GVn6RvA-3D-3D>
by making a donation and spreading the word.

Want to help the children in our community? I'm raising money for Jamii's
Children's Indigenous Health Education Program. As a father of a 4 year
old, I want my daughter and the children in my community to get the
culturally relevant education I never received. Any donation amount will
help. Thanks in advance.
View fundraiser
<https://email.gofundme.com/ls/click?upn=McCelgEyxf19hZNOeSlreO6HA-2BSfGiGcMLzCiS-2ByOInE04FlC-2F5y-2FLNQ9z-2B1C2clxOTgjZaYC74J0fZvdvIBk3dOumZ-2Bf1sEvRA2Zd5lygzhtGCAgJWyflwI8AXsMf2w0los0az3G-2B3eG43-2Fcpw56FA-2FfpuY1s2QEUsFhGttI0os5LGutm1CtonTawymKf0S432jaqUtqG6-2FlacKi1pV44ivgUs5p5y7iIndscYwO1Gc1LqTqjc-2FcWRKhhYUrP3SkPDdwFqvQPiGYgwVmVtvJe2yJSbwAwLBs69nCwPyy3TP4jhY3-2B31SVX9PY2Hh2a7kQjiVIMo1o-2F4hqxr8GSr7A-3D-3DQ4UM_MQUFcoWv1-2FLxBDNNs3puwyPlqKQ6-2BrhKCO8LOwzUC2ldypvBh8g5JVLkhnOW5qgMniwT6uvsiTsn2fI44WbaDSplAROSjeEPE1Wc5sT78bhnKytJQVi28wjcUvLFy2VjwVRdXgXNqz5jrsIgaELP1VPRwRwnbCjZsUJ4xsFM0VUXZN6MvcjVgd0TNqWxd9EEdBVEoUD1-2FfsKKWo5d1jpfJJxMKdv6Tp-2BvOr6ZtLtRnJykP4R7YnNSTu-2BCyn07-2FGKXoE9Vfu2-2BQKLaTfmNp2YZg-3D-3D>

------------------------------
What is GoFundMe?

GoFundMe is the world’s largest free social fundraising platform and has
helped millions raise over $5 billion for the people and causes they care
about.
------------------------------

This email was sent on behalf of Matthew Bradley via GoFundMe.

Don't want these emails? Unsubscribe
<https://email.gofundme.com/ls/click?upn=McCelgEyxf19hZNOeSlreDz60H4K4m7s7K90JBc3Wf3LvKvl7CzvwfwoRnA4x0w-2BvczDJyn7T2YZAtdYRD65Bvchz6u4J-2BrBrIwNYIcy2Pie-2FhdAonP0SWmWNcc8kKSTxTAl5ZCr14C2192euF24Ig3nsrhIoxv0eCJ5kA95VAg6C8ZzC6JI2mkzUtIGkTiQeOoQkHfqiai599kcPU-2Bht0-2FEjPm1uq-2FPq2pGeW-2Fb6lvVexJMzDkFpFY3XxCKQuqISuDv-2BSW0F7HFwx5Tub-2B3bojEGwn89ZHD0kDNT4IC-2FZiM-2FI5XpFuwwQ1eyFoY41Cpi6m4OAdwX6RJc4cnUAfSMf-2FAbrPgPFvZzIbl0TvX5tbua37okz0bvvjJ6eCYmwLqBAj2gTezmhr2WWBfSYw8tBtvRzp6krwW9LZBYIsDDimwbKMvA8NDwJdcGMyPN91uvp-2B0-2BwesP8mFKde68J6crZCC2tbz-2F3dQQPedf-2F1hE6ub61RNpJRCYXXQIvUGGeOzukEdgVXc7ppHLNXYHl-2B678Eijnygf6MkNSc2dOQLTiY-3D5QCD_MQUFcoWv1-2FLxBDNNs3puwyPlqKQ6-2BrhKCO8LOwzUC2ldypvBh8g5JVLkhnOW5qgMniwT6uvsiTsn2fI44WbaDSplAROSjeEPE1Wc5sT78bhnKytJQVi28wjcUvLFy2VjrSZW9kZUrwVHblSfJ3azX9foUQ3Dj5DRoqsNYAmSLIE9rBFJ-2BrB6jY6bM45jIox9qLb0q-2FF7qXqi1J7cFcuqavENfOieeef4BGXlBnUQszDLwXXbyBOh2uto20vkJL4dqaRQaKdG8jla-2B4nX8H4ocQ-3D-3D>
------------------------------

*GoFundMe®* 855 Jefferson Ave, PO Box 1329, Redwood City, CA 94063
