### ISSUE TITLE
Blank File Fields Create Broken Media Items

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#523]
If you have multiple file upload fields and one of them is blank a broken media attachment will be created.

**Comment by kraftbj** [comment]
At initial glance, this appears to happen when submitting a job with any blank media field.

You can duplicate by submitting a job with a blank logo field. The form is submitting via ajax: 

```Content-Disposition: form-data; name="company_logo"; filename=""
Content-Type: application/octet-stream
```

which is being "uploaded".

**Comment by spencerfinnell** [comment]
`$maybe_attach` will contain blank items for them, which can be filtered out. 

https://github.com/Automattic/WP-Job-Manager/blob/master/includes/forms/class-wp-job-manager-form-submit-job.php#L551

**Comment by andrewstewartcox** [comment]
Any updates on this?

**Comment by kraftbj** [comment]
@andrewstewartcox We'll post here with any updates/progress when we have them.
