### ISSUE TITLE
Drop down not working on "Post a vacancy"

### ISSUE THREAD

**Issue by maryke** [Automattic/WP-Job-Manager#525]
Hi there
I've installed your plugin WP Job Manager (the free plugin) Version 1.23.9, WordPress 4.3. You can see it in action here http://klerksdorponline.com/info/post-a-vacancy/ 
Unfortunately the drop down is not working. 
Please can you help me.
Thank you in advance.

**Comment by tripflex** [comment]
"The drop down" ... which drop down?  Please be more specific so we can help with any issues.

That URL also does not exist, the only one I found was this:
http://klerksdorponline.com/info/post-a-job/

Which works correctly.
