### ISSUE TITLE
Submit Resumes file uploader not working

### ISSUE THREAD

**Issue by Joystan** [Automattic/WP-Job-Manager#526]
Hi Support,

I have purchased the add-on package of WP Job Manager and installed the Resumes plugin which enables candidates to upload their resumes on Jobify theme. 

Unfortunately the Resume file upload and Photo upload is buggy. Sometimes it works, sometimes it doesn't.

URL: http://startupgoa.org/submit-resume/

I need to fix this ASAP!

Thanks in advance.

**Comment by Joystan** [comment]
![submit-resume-bug](https://cloud.githubusercontent.com/assets/10162730/9653145/f392460c-523e-11e5-9491-0dcbdd77491c.png)

**Comment by evertsemeijn** [comment]
Hi @Joystan premium plugins are not supported on this forum. You can use the form found at this link https://wpjobmanager.com/contact/

**Comment by Joystan** [comment]
Hi @evertsemeijn I have already done that under a subject of "other" as I could not enter my bug details on the website. It says it will take a few days to get back to me, but that's too much time for a user who owns a premium plugin.

I hope you understand my urgency.

**Comment by mikejolley** [comment]
@Joystan make that 5 requests for the same thing. Why are you spamming all of the support portals? We can see them all you know.
