### ISSUE TITLE
Description is a Required Field

### ISSUE THREAD

**Issue by GunnyRet** [Automattic/WP-Job-Manager#528]
I have tried to mimic an issue from a new customer.  She has added all the requested information except for the Description. Neither of us is able to access this field.  I can preview the new company, but cannot finish the account creation.  I am running 1.23.9. 
Neither of us is able to get beyond a preview screen. I see that this is a recent issue thought to have been corrected as recently as yesterday.

Any VERY specific guidance would be greatly appreciated.

Here is a view of the error:

![image](https://cloud.githubusercontent.com/assets/14221484/9795565/72f145f8-57bf-11e5-99fd-67153ce24622.png)

**Comment by GunnyRet** [comment]
I failed to mention that I have currently have jobs on this website and have also had another customer ad a job to the site with no issues.  So, I'm not sure if this issue is related to an update or something I may have inadvertently done.

**Comment by tripflex** [comment]
Yes this is correct, if the description field is not filled out you are going to have that error.  By default unless you're using the Field Editor or made changes through PHP, the description field should be a WP-Editor field, and from your screenshot that is not what it's showing up as.

My only assumption is that you have some type of error on your site, either JS or something else that is preventing the WP-Editor from loading correctly.

Please provide us with the URL to your submit listing page so we can look at it to make sure

**Comment by GunnyRet** [comment]
Here is the public link:

http://www.gunnyret.com/post-a-job/

Thank you so much for the speedy reply.

**Comment by tripflex** [comment]
Yup, just like I thought it's a problem with your site and a jQuery error, so not an issue with the core plugin:

![image](http://i.imgur.com/jlaKMeh.png)

**Comment by GunnyRet** [comment]
Thanks!  I will contact GoDaddy.  : )

**Comment by tripflex** [comment]
It's not GoDaddy it's the `polls-widget` plugin you're using.  You would need to contact them for support or just remove the plugin completely.

**Comment by GunnyRet** [comment]
That’s easy enough. I haven’t even started to use that plugin. I just found it and was possibly going to implement it later on.

 

Bryan A. McGown, “Gunny”

Owner

GunnyRet Consulting, LLC.

A Military Veteran Recruiting Company

“Work With Heroes”

“Serving the Global Needs of Veterans and Employers”

Mobile: 216.200.USMC(8762)

 <mailto:bryanamcgown@gunnyret.com> bryanamcgown@gunnyret.com 

Schedule a consultation or teleconference at www.gunnyret.com

 

LEGAL NOTICE:

This email and any files transmitted with it, may contain information that is PROPRIETARY, PRIVILEGED AND CONFIDENTIAL. It is the property of GunnyRet Consulting, LLC, and is intended only for the use of the intended recipient(s). If you have received this email in error, do not disseminate, distribute, forward, print or copy this email or any of its' attachments. Immediately destroy/purge the email and all attachments and notify the sender by reply of this email. Any misuse/abuse may result in disciplinary action and/or legal liability. Unauthorized interception of this email is a violation of federal law.
