### ISSUE TITLE
Jobs don't display until the page is refreshed

### ISSUE THREAD

**Issue by carlsonem** [Automattic/WP-Job-Manager#529]
The jobs posted on the job page don't display if I access the jobs pages from the home page menu link (under careers) at http://techtrendtest.com/.  That said, if I refresh the page or directly go to the page link http://techtrendtest.com/jobs/, the jobs are displayed. I'm assuming their is an issue with the feed. Any suggestions?

**Comment by mikejolley** [comment]
This is because your theme is using AJAX to load page content. AJAX does not run javascript within the loaded page.

Disable the ajax functionality to resolve.
