### ISSUE TITLE
Exclude admins from the "pending approval" workflow

### ISSUE THREAD

**Issue by humphreyswhite** [Automattic/WP-Job-Manager#531]
Hi - some of my clients are disabled and add jobs via the frontend on behalf of other users. Those who use screen readers can't use the dashboard, so they have to have their jobs approved by admins who can. Could you add a filter so we can exclude users with certain capabilities from having to have their jobs approved?

**Comment by mikejolley** [comment]
The option is named 'job_manager_submission_requires_approval' - this is filterable through WP API https://codex.wordpress.org/Plugin_API/Filter_Reference/pre_option_(option_name)
