### ISSUE TITLE
Allow image selection from media library when submitting a job

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#534]
Would be nice to be able to select an image from my media library here:

![screen shot 2015-09-24 at 4 20 53 pm](https://cloud.githubusercontent.com/assets/5512652/10085641/46125288-62d8-11e5-9d51-56bbfa7d483f.png)

Is this possible with the way we currently handle images? (e.g. storing image URLs as opposed to attachment IDs)

From this forum thread: https://wordpress.org/support/topic/stop-duplicate-client-logos?replies=11

**Comment by mikejolley** [comment]
No, and showing the media library to guests (!) is not advisable. If they want to reuse media, they can post from the backend. @aheckler

**Comment by spencerfinnell** [comment]
Yeah I've never really seen a good implementation of the media library on the frontend. Always way more problems than benefits.

**Comment by aheckler** [comment]
@mikejolley OK, feel free to close then. :) Thanks!
