### ISSUE TITLE
Unable to upload mp3s

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#536]
Despite mp3's being in the allowed type, they are being rejected by https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L658

First idea was that the piped listing was causing issues ( https://github.com/WordPress/WordPress/blob/f84c653fad232438c4bd78fce3b1feab75224a98/wp-includes/functions.php#L2227 ), but other types (ppt, for example) worked.

**Comment by kraftbj** [comment]
It seems like the core check is for audio/mpeg while the check is being done against audio/mp3

**Comment by jjdmk** [comment]
Hi, this is Joe that originally sent in the bug report. Thank you for starting the ball rolling so quickly!

I've been doing some more testing and it looks like m4a files also have the same problem, but m4b files upload just fine. 

They are all on the same line in wp-includes/functions.php
Line 2227: 'mp3|m4a|m4b' => 'audio/mpeg',

I tried changing line 2227 to: 'mp3|m4a|m4b' => 'audio/mp3', and was then able to upload an mp3 file. So it looks like you are correct, the problem is the check audio/mpeg vs audio/mp3.

Any thoughts on a solution?

**Comment by kraftbj** [comment]
`wp_check_filetype` checks the file name and returns the type per what Core expects. We're not doing that, it seems, so `audio/mp3` is checked against core's expected `audio/mpeg`.

Ideas: Eliminate our check completely. It would fallback to Core's. Downside: Instead of the list of available types, it is a generic security message: `Sorry, this file type is not permitted for security reasons.`

With the above, if we could get a filter in core to change that message, we could drop our check completely and add a filter to return the same message as now. Untested how that impacts things like WP Fields Manager.

@jjdmk -- in the immediate moment, if you're fine with Core's default message, removing this section from wp-job-manager-functions.php will get it operational in a hacky way until @mikejolley can weigh in. 

```
if ( ! in_array( $file['type'], $args['allowed_mime_types'] ) ) {
		if ( $args['file_label'] ) {
			return new WP_Error( 'upload', sprintf( __( '"%s" (filetype %s) needs to be one of the following file types: %s', 'wp-job-manager' ), $args['file_label'], $file['type'], implode( ', ', array_keys( $args['allowed_mime_types'] ) ) ) );
		} else {
			return new WP_Error( 'upload', sprintf( __( 'Uploaded files need to be one of the following file types: %s', 'wp-job-manager' ), implode( ', ', array_keys( $args['allowed_mime_types'] ) ) ) );
		}
	} else {
```

then be sure to remove the extra `}` after what was in the `else` block.

**Comment by kraftbj** [comment]
Just in case we go this route: https://core.trac.wordpress.org/ticket/34064

**Comment by jjdmk** [comment]
Excellent, thank you @kraftbj I really appreciate the very fast response time on all of this!

This works as a solution for now. Looking forward to seeing what @mikejolley cooks up!
