### ISSUE TITLE
Cache issue with submit job page

### ISSUE THREAD

**Issue by wmacmill** [Automattic/WP-Job-Manager#538]
Ran into an issue recently where using WP Job Manager and specifically WP Engine where the submit job page is cached. When the job is submitted it uses wp_update_post to update the post meta on submission and updates the post status. This should fire transition_post_status on the update however this doesn't end up getting fired. This means anything hooked to this post status update won't get fired. 

This could be an issue for other plugins that want to use the job submission status change to hook onto such as Post Status Notifier among others. Now you can exclude the job submit page from the cache and you will avoid the issue however not everyone is going to know this initially and (as was my case) when you switch from a development site with no cache to production with a cache they might not notice the change. 

I know it's a server specific issue in this case but I'm wondering if there's something in the plugin that we can use to help with this?

**Comment by mikejolley** [comment]
I don't think we can fix this plugin side. It's a server level rule - EDD for example has the same issue with their checkout http://docs.easydigitaldownloads.com/article/295-wp-engine-cache-exclusion-for-checkout-page

And for WC, they have in-built rules to exclude pages.

**Comment by wmacmill** [comment]
Thanks Mike - I actually just heard back from WP Engine this morning and it looks like it's the object caching actually and not varnish (WP Engine). If the object caching is disabled on the site the job submissions work fine, if it's enabled it doesn't. This occurs with any caching plugins that use object caching like W3 etc. 

For example if you spin up a site with just WP Job Manager and W3 Total Cache and turn on object cache you have the same issue where when you submit a job things like transition_post_status don't fire. 

I'm not exactly sure how the plugin is currently using object caching on the submit job form specifically but will potentially cause an issue for anyone using object caching with the plugin.
