### ISSUE TITLE
Indeed Apply Integration

### ISSUE THREAD

**Issue by brenthealy** [Automattic/WP-Job-Manager#539]
I would like to allow users to apply for a job via Indeed Apply.
Since LinkedIn has now closed their API, we need a more professional method to allow users to quickly apply using an online profile they may already have.

See existing plugin: https://wordpress.org/plugins/indeed-apply-shortcode/installation/
Indeed Apply: http://www.indeed.com/hire/indeed-apply
http://www.programmableweb.com/api/indeed
https://www.taylormccaslin.com/portfolio/indeed-apply-wordpress-plugin/

**Comment by mikejolley** [comment]
Logged on our feature board. thanks.
