### ISSUE TITLE
Add filter for multiselect chosen.js arguments?

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#540]
What are your thoughts about maybe adding a filter that could be used for setting the arguments in chosen's jQuery?

https://github.com/Automattic/WP-Job-Manager/blob/master/assets/js/term-multiselect.js
https://github.com/Automattic/WP-Job-Manager/blob/master/assets/js/multiselect.js

Specifically i've had numerous requests about things like max selections, allowing deselect, setting 'No Results' wording, etc.

We could just run the array of args through a filter, then use `wp_localize_script` to create the JS object/array

I can put together a PR if need be, just let me know

**Comment by mikejolley** [comment]
Sounds reasonable - will await your PR :)

**Comment by kochhase** [comment]
hi Myles and Mike,
is there are an ETA for this enhancement?
thanks Henryk

**Comment by tripflex** [comment]
@kochhase I just submitted it as a pull request, but it may take a bit before it gets included in the next release.  

If you need it now you can just use the copy from my `chosenargs` branch:
https://github.com/tripflex/wp-job-manager/tree/chosenargs

**Comment by kochhase** [comment]
Hello Myles,
thank you for this info. But how can I interact with this code? Is thers a way with you plugin 1.3.8? Or have I to extend the funktion.php. First of all I need the "max selections" funktion for images.

**Comment by tripflex** [comment]
https://harvesthq.github.io/chosen/options.html

Add a filter in your `functions.php` file

```php
add_filter( 'job_manager_chosen_multiselect_args', 'my_custom_chosen_multiselect_args' );

function my_custom_chosen_multiselect_args( $args ){
    $args['max_selected_options'] = 3;
    return $args;
}
```
