### ISSUE TITLE
Add ID to "Edit Listing" button for easy styling

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#541]
When submitting a listing, we have an ID on the submit button (`job_preview_submit_button `):

https://github.com/Automattic/WP-Job-Manager/blob/1.23.9/includes/forms/class-wp-job-manager-form-submit-job.php#L615

... but not on the Edit Listing button (line below). We should add an ID for easy styling.

From: https://wordpress.org/support/topic/modification-request-preview-button-styling

**Comment by spencerfinnell** [comment]
:+1: for classes instead of IDs.
