### ISSUE TITLE
Bug in job submission process 

### ISSUE THREAD

**Issue by jamesjonesphoenix** [Automattic/WP-Job-Manager#542]
While testing my site I realised that you can find yourself editing another user's preview job. To reproduce:
◾Allow account creation in settings.
◾Follow the submit form process not logged in as anyone.
◾Get to the preview step and then abort the process. Basically we get to the point job manager creates a user and preview job.
◾Log out
◾Start the process again either logged in as a different user or not logged in as anyone. By the time you get to the preview step you'll have made db changes to the first user's job and not created your own job.

It seems the WP_Job_Manager_Form_Submit_Job class is collecting information from the $_COOKIE variable and using it without taking into account the user_id owner of the preview job in any way.

**Comment by pimdoenders** [comment]
I've experienced this issue as well some weeks ago, but was not able to replicate it.

**Comment by mikejolley** [comment]
There is no issue with this - the cookie stores the JOB ID only. If you're for example submitting a job, leave, log in, and come back, your submission form will be populated with the previous un-submitted job's details saving you re-entry. If we based this on user ID, this would not work.

This would only be an issue if it allowed you to overwrite a fully submitted job. This does not.

Please note, 'preview' jobs are not considered submitted and are deleted unless posted. They are not visible.

**Comment by jamesjonesphoenix** [comment]
I can see how things don't matter so much in the preview step. However if you continue past the preview step as the second user, the profile status will change from 'preview' status to 'pending_approval' or 'pending_payment' and then be a published listing. At all steps the author of the post row is the first user. Ownership is never transferred to the second user. 

The second user will be wondering why their listing isn't available in the editing screen, the first user will have a new listing to manage that they didn't create.
