### ISSUE TITLE
Problem with VAT

### ISSUE THREAD

**Issue by Cabiriacomunicazione** [Automattic/WP-Job-Manager#545]
When I insert the VAT keeps giving me this error : 
VAT API Error: Operation timed out after 5000 milliseconds with 0 bytes received
and I do not proceed with the purchase plugins .

**Comment by wmacmill** [comment]
Are you sure you're not having an issue with Woocommerce maybe?

**Comment by Cabiriacomunicazione** [comment]
I resolved thank you

Best regards 
Andrea Marletta

--

 

Via Minozzi 10 - 43122 Parma 
Tel./Fax 0521.282278
www.cabiria.net <https://www.cabiria.net/> 

 <https://it-it.facebook.com/cabiria.net>    <https://twitter.com/GruppoCabiria>    <https://plus.google.com/113843045968324793565/posts>    <http://www.linkedin.com/company/cabiria-comunicazione>    <http://instagram.com/cabiriacomunicazione>


Ai sensi dell’art 13 del D.Lgs.n.196/2003 si informa che i dati personali saranno trattati nel rispetto della normativa ai soli fini della gestione dei rapporti commerciali e degli adempimenti civilistici e fiscali. Agli interessati sono riconosciuti i diritti di cui all’art.7 del D.Lgs n.196/2003. La versione completa dell’informativa sul trattamento è pubblicata sul sito web  http://www.cabiria.net/privacy <http://www.cabiria.net/privacy>

**Comment by AleksSiroki** [comment]
Hej Andrea,
Can you help please? How did you resolved this issue? I'm having the same problem! The only google search result was this. :)
