### ISSUE TITLE
Admin side filters problematic

### ISSUE THREAD

**Issue by ProfLebza** [Automattic/WP-Job-Manager#547]
We have been trying to sort out the admin side filters without any success. When choosing fields to filter on, the plugin just returns the job listings (reloads). I am not certain why this is happening since it doesn't report back any errors on the console. Can you please advice?

**Comment by mikejolley** [comment]
There are no admin side filters in WP job manager. It's the standard WordPress posts screen. https://dl.dropboxusercontent.com/s/jqxnhc7qy97vqlw/2015-11-03%20at%2011.05.png?dl=0
