### ISSUE TITLE
Wrong error message for maximum file size

### ISSUE THREAD

**Issue by Devact** [Automattic/WP-Job-Manager#553]
When submitting a logo of the company the error massage for maximum file size is wrong. Should be something like "Cannot upload files over %mb", now it's: "Uploaded files need to be one of the following file types".

![wp-job2](https://cloud.githubusercontent.com/assets/377895/10852804/5ed7a816-7f3b-11e5-98b5-0390b62cb564.jpg)

**Comment by mikejolley** [comment]
Seems fine in master https://dl.dropboxusercontent.com/s/ozmt5m35pe4zwjm/2015-11-03%20at%2012.28.png?dl=0
