### ISSUE TITLE
Clean Up Previews

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#555]
From a quick look, when a submission is previewed, it creates a hidden item in the database and uploads the media file. If the preview is never submitted, the database item and any uploads remain in the db/filesystem.

We should clean up after ourselves, either after a day or do something like a 15-minute countdown, etc.

**Comment by spencerfinnell** [comment]
Also leaves a user behind if that is their only submission.

**Comment by mikejolley** [comment]
We already have a preview cleanup function, but I need to look into whether or not its possible to remove attachments too.
