### ISSUE TITLE
The "edit_others_job_listings" cap is confusingly named

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#558]
Right now, the `edit_others_job_listings` capability only lets you change the author on new or existing job listings, like so:

![screen shot 2015-11-09 at 11 47 40 am](https://cloud.githubusercontent.com/assets/5512652/11039870/b1c28e30-86d7-11e5-8b77-b50df82847b9.png)

We should either rename it or alter it so that it actually does what it says it can do: allow you to edit other people's job listings.

For an example of that, see this gist by @kraftbj:

https://gist.github.com/kraftbj/34fa812a1ef54b08fd6d

**Comment by mikejolley** [comment]
This mirrors 'posts'.

In order to edit other users published posts you need:

edit_published_posts edit_others_posts

So for jobs you need the same:

edit_published_job_listings edit_others_job_listings

Without this, you can view but you cannot edit published listings.
