### ISSUE TITLE
Getting data base error 

### ISSUE THREAD

**Issue by Shreyanshharsora** [Automattic/WP-Job-Manager#559]
WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 500' at line 6 for query DELETE a, b FROM wp_options a, wp_options b
				WHERE a.option_name LIKE '\\_transient\\_jm\\_%'
				AND a.option_name NOT LIKE '\\_transient\\_timeout\\_jm\\_%'
				AND b.option_name = CONCAT( '_transient_timeout_', SUBSTRING( a.option_name, 12 ) )
				AND b.option_value < 1446880654
				LIMIT 500; made by do_action_ref_array, call_user_func_array, WP_Job_Manager_Cache_Helper::clear_expired_transients

please help me

**Comment by mikejolley** [comment]
Fixed in master. Will be in next update.
