### ISSUE TITLE
New User Notification Emails

### ISSUE THREAD

**Issue by edd677** [Automattic/WP-Job-Manager#562]
Am aware this issue was listed as fixed in 1.23.10, but unfortunately I am still not receiving new user notifications. The admin still receives an email - just not the employer/candidate.

I can see from various forums (wordpress.org, etc) that other users are still having this issue also. I don't mean to nag, but it is absolutely crucial this functionality works, given that users do not create their own passwords.

Thanks!

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 10 @ 23:54 (CET):



	Am aware this issue was listed as fixed in 1.23.10, but unfortunately
I am still not receiving new user notifications. The admin still
receives an email - just not the employer/candidate. 

	I can see from various forums (wordpress.org, etc) that other users
are still having this issue also. I don't mean to nag, but it is
absolutely crucial this functionality works, given that users do not
create their own passwords. 

	Thanks! 

	-
 Reply to this email directly or view it on GitHub [1].

Links:
------
[1] https://github.com/Automattic/WP-Job-Manager/issues/562


-----------------------------------------------------------

**Comment by kraftbj** [comment]
Can you provide specific steps to duplicate? I can't duplicate a failure of the notification e-mail.

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 11 @ 4:19 (CET):



	Can you provide specific steps to duplicate? I can't duplicate a
failure of the notification e-mail. 

	-
 Reply to this email directly or view it on GitHub [1].

Links:
------
[1]
https://github.com/Automattic/WP-Job-Manager/issues/562#issuecomment-155650017


-----------------------------------------------------------

**Comment by edd677** [comment]
Sure - I just visit visit my site, and:

1. Hit 'sign up' (top right)
2. Fill out the modal pop-up form (with gmail address), indicating I am a candidate.
3. Hit register.

And no email is received. Currently I am using GoDaddy's 'Managed WordPress' hosting package. Though it seems unlikely this would be the issue - since I receive every other email (e.g. admin notification of new user).

**Comment by kraftbj** [comment]
Can you include a link to your site? That doesn't sound like a way that WP Job Manager uses to create an user, but can't say for sure without seeing it :)

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 11 @ 22:18 (CET):



	Can you include a link to your site? That doesn't sound like a way
that WP Job Manager uses to create an user, but can't say for sure
without seeing it :) 

	-
 Reply to this email directly or view it on GitHub [1].

Links:
------
[1]
https://github.com/Automattic/WP-Job-Manager/issues/562#issuecomment-155913273


-----------------------------------------------------------

**Comment by edd677** [comment]
Sure! It's using the Jobify front-end.

www.londontechy.co.uk is the site.

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 11 @ 22:33 (CET):



	Sure! It's using the Jobify front-end. 

	www.londontechy.co.uk [1] is the site. 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1] http://www.londontechy.co.uk
[2]
https://github.com/Automattic/WP-Job-Manager/issues/562#issuecomment-155916690


-----------------------------------------------------------

**Comment by kraftbj** [comment]
That form is provided within Jobify ( specifically inc/integrations/wp-job-manager/wp-job-manager-form-register.php ), though nothing looks obvious amiss from their end from a quick glance. I'd suggest installing something like http://wordpress.org/plugins/email-log/ and check if the e-mail is being generated or not.

If so, then it is a server issue in most cases. If not, then I'd suggest contacting Jobify.

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 12 @ 0:05 (CET):



	That form is provided within Jobify ( specifically
inc/integrations/wp-job-manager/wp-job-manager-form-register.php ),
though nothing looks obvious amiss from their end from a quick glance.
I'd suggest installing something like
http://wordpress.org/plugins/email-log/ [1] and check if the e-mail is
being generated or not. 

	If so, then it is a server issue in most cases. If not, then I'd
suggest contacting Jobify. 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1] http://wordpress.org/plugins/email-log/
[2]
https://github.com/Automattic/WP-Job-Manager/issues/562#issuecomment-155937727


-----------------------------------------------------------

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 12 @ 0:06 (CET):



	Closed #562 [1]. 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1] https://github.com/Automattic/WP-Job-Manager/issues/562
[2]
https://github.com/Automattic/WP-Job-Manager/issues/562#event-461868340


-----------------------------------------------------------

**Comment by spencerfinnell** [comment]
Latest release of Jobify fixes this.

**Comment by edd677** [comment]
Thank you for your comments.

I'm beginning to think this issue might be related to my hosting setup. I'm using GoDaddy's "Managed WordPress" package (no cPanel, etc). Might this be causing issues? I'm also not receiving any job alerts...

I'll install the email log plugin and see if that provides any insight.
