### ISSUE TITLE
Links not URL encoded correctly

### ISSUE THREAD

**Issue by mikejolley** [Automattic/WP-Job-Manager#564]
https://wordpress.org/support/topic/application-url-isnt-properly-preserved-url-decoded?replies=1

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 12 @ 22:38 (CET):



	https://wordpress.org/support/topic/application-url-isnt-properly-preserved-url-decoded?replies=1
[1] 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1]
https://wordpress.org/support/topic/application-url-isnt-properly-preserved-url-decoded?replies=1
[2] https://github.com/Automattic/WP-Job-Manager/issues/564


-----------------------------------------------------------

**Comment by mikejolley** [comment]
Seems to be related to https://core.trac.wordpress.org/ticket/23605

**Comment by mikejolley** [comment]
^ which will be fixed in WP 4.4
