### ISSUE TITLE
search_location in the background working "class-wp-job-manager-ajax.php"

### ISSUE THREAD

**Issue by kochhase** [Automattic/WP-Job-Manager#566]
Hi Mike,
i have some strange problems if i searching with too languages (Polylang translating). I am using wpjm region addon. But if I am deactivating it I see the "search_location" field. Is it possible, that after activating the wpjm region addon the "search_location" field is working in the background? 

You can see that at http://meersjob.de

@ I have deactivated WPsearch, but without any reason@

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 15 @ 16:04 (CET):



	Hi Mike,
 i have some strange problems if i searching with too languages
(Polylang translating). I am using wpjm region addon. But if I am
deactivating it I see the "search_location" field. Is it possible,
that after activating the wpjm region addon the "search_location"
field is working in the background? 

	You can see that at http://meersjob.de [1] 

	@ I have deactivated WPsearch, but without any reason@ 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1] http://meersjob.de
[2] https://github.com/Automattic/WP-Job-Manager/issues/566


-----------------------------------------------------------

**Comment by mikejolley** [comment]
See #569
