### ISSUE TITLE
Job Packages 'Submit' Button not working.  

### ISSUE THREAD

**Issue by mikegunn** [Automattic/WP-Job-Manager#568]
Hello, 

I have tried both options under 'paid listings flow' and it still doesn't let me click the buttons to take the advert to the next stage.  i.e. to buy a package after viewing the preview or after choosing package then fill out job details.  See Example: http://yuejobs.co.uk/post-a-job-2/

-----

Also,

I only use the application form to allow candidates to send CVs in response to adverts i.e. not requiring them to create an account and upload CV.  Is there anyway I could send them to a 'Thank you for your job application page' after hitting the 'send application button'? See example: http://yuejobs.co.uk/job/delivery-driver/

I wish to create this in order to monitor my goal/conversion stats and/or pixels for Facebook advert campaigns.  

This is my first time using GitHub so apologies for any mistakes.  Your product has completely redesigned my project and I thank you for that. 

Mike

**Comment by mikejolley** [comment]
This isn't the place for support request for addons, but I can tell you that your problem is down to the styles in your theme. The heading is overlapping the button, so the button is not clickable.
