### ISSUE TITLE
Polylang compatibility

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#569]
Polylang is a plugin for multilingual sites that apparently some of the WPJM theme shops suggest.

Issue: The `[jobs]` shortcode returns the jobs of the language that had the most recent job update (e.g. if the last edited job was in Spanish, all languages would only return Spanish jobs).

Resolution: Add language to the WPJM query args:

```php
add_filter( 'get_job_listings_query_args', 'pll_wpjm_change_search' );
function pll_wpjm_change_search( $args ) {
  if ( function_exists( 'pll_current_language' ) ) {
    $args['lang'] = pll_current_language();
  }
  return $args;
}
```

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 17 @ 18:49 (CET):

Polylang is a plugin for multilingual sites that apparently some of
the WPJM theme shops suggest.
Issue: The [jobs] shortcode returns the jobs of the language that had
the most recent job update (e.g. if the last edited job was in
Spanish, all languages would only return Spanish jobs).
Resolution: Add language to the WPJM query args:

add_filter( 'get_job_listings_query_args', 'pll_wpjm_change_search' );
function pll_wpjm_change_search( $args ) {
  if ( function_exists( 'pll_current_language' ) ) {
    $args['lang'] = pll_current_language();
  }
  return $args;
}

-
Reply to this email directly or view it on GitHub.

-----------------------------------------------------------

**Comment by spencerfinnell** [comment]
:+1:

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 17 @ 19:01 (CET):



	-
 Reply to this email directly or view it on GitHub [1].

Links:
------
[1]
https://github.com/Automattic/WP-Job-Manager/issues/569#issuecomment-157454214


-----------------------------------------------------------

**Comment by spencerfinnell** [comment]
Also need to pick the right page for settings:

https://github.com/Astoundify/listify/blob/release/1.1.0/inc/integrations/polylang/class-polylang.php#L24-L31

**Comment by fourleafed** [comment]
-- Please reply above this line --

Hi Automattic/wp-Job-Manager We have received your email. We will
respond to you as soon as possible.Kind regards!

-----------------------------------------------------------
## Automattic/wp-Job-Manager sent a message, on Nov 17 @ 23:04 (CET):



	Also need to pick the right page for settings: 

	https://github.com/Astoundify/listify/blob/release/1.1.0/inc/integrations/polylang/class-polylang.php#L24-L31
[1] 

	-
 Reply to this email directly or view it on GitHub [2].

Links:
------
[1]
https://github.com/Astoundify/listify/blob/release/1.1.0/inc/integrations/polylang/class-polylang.php#L24-L31
[2]
https://github.com/Automattic/WP-Job-Manager/issues/569#issuecomment-157523704


-----------------------------------------------------------
