### ISSUE TITLE
Applications Add-on: Addon accepts applications for expired/removed jobs

### ISSUE THREAD

**Issue by Veraxus** [Automattic/WP-Job-Manager#572]
One of our client sites uses the Applications add on for WP Job Manager, and our client was complaining that applications were coming in for jobs LONG after they had expired and been removed from the site.

Upon investigation, we discovered that jobs were being submitted from external career websites to our client's job posting forms. We're okay with that, but the Applications addon does not check to see if the position is still available and saves any and every application posted to it, even if the specified job has expired or otherwise been removed.

The following check needs to be added to be added to the `WP_Job_Manager_Applications_Apply::application_form_handler()` function in `/wp-job-manager-applications/includes/class-wp-job-manager-applications-apply.php`…

    if ( 'publish' !== $job->post_status ) {
    	throw new Exception( __( 'That job is not available', 'wp-job-manager-applications' ) );
    }

This tweak will prevent the addon from erroneously accepting applications for jobs that have expired or otherwise been cancelled or removed.

**Comment by Veraxus** [comment]
As an aside, I wasn't sure where else to submit this. https://wpjobmanager.com won't allow me to access the support form since the license had expired, and there is no public repo for the addon being a premium plugin… and since I wasn't about to pay for the "privilege" of submitting a patch, this was the next best option.

**Comment by kraftbj** [comment]
I've made the PR on the private repo. Thanks for the report!
