### ISSUE TITLE
Error when uploading a photo

### ISSUE THREAD

**Issue by tarekkoura** [Automattic/WP-Job-Manager#573]
I'm using this plugin with Listify wordpress theme from themeforest

it has a button of upload photo to a listing

the photo should be directed to the listing gallery

this is the error message

Fatal error: Call to undefined function wp_generate_attachment_metadata() in D:\home\site\wwwroot\wp-content\themes\listify\inc\integrations\wp-job-manager\class-wp-job-manager-gallery.php on line 171

but what happens is that:
If I'm uploading photos to 
555-liberty-village-toronto-ontario-canada-astoundify-barbershop

uploaded photos should go to 

http://23.97.213.228/listing/555-liberty-village-toronto-ontario-canada-astoundify-barbershop/gallery/

but actually what happens is that the uploaded photo goes to:
http://23.97.213.228/listing/555-liberty-village-toronto-ontario-canada-astoundify-barbershop/astoundify-barbershop-5/ 

please advise

Thanks

**Comment by spencerfinnell** [comment]
Hey @tarekkoura Can you please open a ticket with Astoundify support at https://support.astoundify.com/ -- thanks!

**Comment by tarekkoura** [comment]
I've already opened a ticket, and didn't receive a real solution till now

so that is why I'm trying another source of support

**Comment by spencerfinnell** [comment]
Replied to the ticket. Lets keep the discussion there until further investigation. Thanks!
