### ISSUE TITLE
Applications Addon: Saving multiple times results in error

### ISSUE THREAD

**Issue by cvongrim** [Automattic/WP-Job-Manager#575]
Saving an application once works fine but when saving it again, it gives the following errors:

Notice: Undefined index: _attachment in /vagrant/html/wp-content/plugins/wp-job-manager-applications/includes/class-wp-job-manager-applications-writepanels.php on line 201

Notice: Undefined index: _attachment in /vagrant/html/wp-content/plugins/wp-job-manager-applications/includes/class-wp-job-manager-applications-writepanels.php on line 204

Warning: Cannot modify header information - headers already sent by (output started at /vagrant/html/wp-content/plugins/wp-job-manager-applications/includes/class-wp-job-manager-applications-writepanels.php:201) in /vagrant/html/wordpress/wp-admin/post.php on line 242

Warning: Cannot modify header information - headers already sent by (output started at /vagrant/html/wp-content/plugins/wp-job-manager-applications/includes/class-wp-job-manager-applications-writepanels.php:201) in /vagrant/html/wordpress/wp-includes/pluggable.php on line 1207

This only seems to happen if there is no a attachments.

**Comment by mikejolley** [comment]
Seems I'm unable to replicate this one with the latest release. Update on monday when its deployed, and if it still occurs, raise an issue in support so I can look in more detail.
