### ISSUE TITLE
modifiy the job_location on submit

### ISSUE THREAD

**Issue by firaskudsy** [Automattic/WP-Job-Manager#577]
i need to change the job_location filed before submit, i set its visiblilty to false and i want to give it the value of the job_region slug on submition, how to do this ?

**Comment by mgibbs189** [comment]
@firaskudsy See the `submit_job_form_fields_get_job_data` filter.

The hook can be found at line ~350 of `includes/class-wp-job-manager-form-submit-job.php`.

```php
function mysite_job_submit_fields( $fields, $job ) {
    // do your processing here
    return $fields;
}
add_filter( 'submit_job_form_fields_get_job_data', 'mysite_job_submit_fields', 10, 2 );
```

**Comment by firaskudsy** [comment]
I need to modify the value of the field. This hook not passing values or
return values

**Comment by firaskudsy** [comment]
when am using the hook above it set the value in the job location form filed, but what i want is to set this filed not by form, but by code before submiting the form, so what ever the user enter i will set some static value, how to do that ?

**Comment by aheckler** [comment]
@firaskudsy — Please use this forum to get support:

https://wordpress.org/support/plugin/wp-job-manager

GitHub should really only be used for bug reports and the like. Thanks!
