### ISSUE TITLE
Bookmark errors in Listify theme

### ISSUE THREAD

**Issue by Jillio** [Automattic/WP-Job-Manager#579]
There are at least 3 of us Listify users that are getting this error, and I'm getting it on 2 sites (in multiuser). When you click on the listing owner's listings, you get this:

In the hero section:

Warning: Division by zero in /home/mysite/public_html/wp-content/plugins/wp-job-manager-bookmarks/wp-job-manager-bookmarks.php on line 134

Warning: Division by zero in /home/mysite/public_html/wp-content/plugins/wp-job-manager-bookmarks/wp-job-manager-bookmarks.php on line 134
 1 Favorite 

And below the 3 listings per page

Warning: Division by zero in /home/mysite/public_html/wp-content/plugins/wp-job-manager-bookmarks/wp-job-manager-bookmarks.php on line 134

Warning: Illegal string offset 'post_id' in /home/mysite/public_html/wp-includes/functions.php on line 3211

Fatal error: Cannot use object of type stdClass as array in /home/mysite/public_html/wp-includes/functions.php on line 3211

**Comment by kraftbj** [comment]
I opened a report for this in the bookmarks repo. We'll get it fixed up.

**Comment by Xenero** [comment]
This still isn't fixed. Is there any ETA?
