### ISSUE TITLE
Show nothing with [submit_resume_form]

### ISSUE THREAD

**Issue by miclotfy** [Automattic/WP-Job-Manager#581]
when i added the shortcode  [submit_resume_form] i got blank page !!! 

I need to add page the candidates can submit their resume , how can i do that ?

**Comment by kraftbj** [comment]
Could you please contact support via http://wpjobmanager.com/support/ ? Additionally, please include your server's error logs and/or contact your hosting provider asking where to find them if you're not sure.

Thanks!
