### ISSUE TITLE
Integration with FacetWP

### ISSUE THREAD

**Issue by mgibbs189** [Automattic/WP-Job-Manager#582]
Hey @mikejolley,

Great work with WPJM. I'm looking to integrate `[jobs]` with FacetWP (for advanced filtering), and was wondering if you had any guidance or suggestions.

It's somewhat tricky since both plugins are AJAX-based. FacetWP first needs access to the query args, so the `job_manager_get_listings` filter looks to be the right one. I'll also likely need to inject FacetWP's response data along with WPJM's ajax response, in which case `job_manager_get_listings_result` could work.

Maybe you have a different idea (or have done something else for other AJAX-based integrations)?

I'd be happy to provide FacetWP, just let me know.

**Comment by kochhase** [comment]
Hi mgibbs189
what is jobify doing to let it work.
http://jobify.astoundify.com/category/314-facetwp
is there something to get in core to let us using FacetWP and searchWP like big jobplattforms?

**Comment by mikejolley** [comment]
This isn't something I've looked into, but we do have hooks in place and I know Jobify have managed to integrate with their theme at least. If you do succeed I'd be keen to see how it turns out or if you need more hooks.

**Comment by kishoresahoo** [comment]
Is FacetWP is compatible with WPJM?
