### ISSUE TITLE
Investigate whether unlinking images breaks other posts with the same image

### ISSUE THREAD

**Issue by mikejolley** [Automattic/WP-Job-Manager#583]
https://github.com/Automattic/WP-Job-Manager/blob/cb96686e5ddc35d5bb75136fabce189cf6f9fe0b/includes/class-wp-job-manager-post-types.php#L695

**Comment by tripflex** [comment]
This update to company_logo causes anybody with multiple set on company_logo to have issues.  Specifically this is a problem with Listable theme (as my plugin specifically removes the option to set as multiple), but Listable does use multiple.  I'm not sure if they've fixed it yet, just wanted to let you know

**Comment by tripflex** [comment]
Looks like latest release of Listable fixes compatibility
