### ISSUE TITLE
Add option to prevent editing of published listings

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#584]
We should consider adding an option similar to the "Allow Pending Edits" one, but for published job listings. By enabling it, you could prevent editing of published listings.

From Kayako 2450042.

**Comment by mikejolley** [comment]
@aheckler could disable the dashboard?

**Comment by aheckler** [comment]
Yeah, but I think you could still edit it if you knew the URL. ¯\\_(ツ)_/¯ Not sure if this is an edge case we care about though.

**Comment by mikejolley** [comment]
I don't think so, and I do think its better covered by https://github.com/Automattic/WP-Job-Manager/issues/509 if we ever implement revisions.
