### ISSUE TITLE
Job Not Visible

### ISSUE THREAD

**Issue by manattweb** [Automattic/WP-Job-Manager#586]
I installed the plugin and added a job two days ago and everything seemed to work fine, but I come back today and the job isn't showing up. Only after a page refresh does the job appear. Here's the page: http://www.centralarkansasurgentcare.com/careers/

Is this a known issue? Thoughts?

**Comment by tripflex** [comment]
You have JS errors on your site, which is probably the reason you are having problems, as this plugin uses ajax to load data and JS errors can cause JS to stop running due to the error .... 

![JS Error](https://smyl.es/img/Screenshot_2016-01-13_01-51-03_PM.png)

**Comment by aheckler** [comment]
@manattweb — I see the job on first load now:

![screen shot 2016-01-27 at 9 04 47 am](https://cloud.githubusercontent.com/assets/5512652/12615672/16019022-c4d5-11e5-9307-9ea946cacb82.png)

If this is still an issue for you, please reach out to us either in the forums:

https://wordpress.org/support/plugin/wp-job-manager

... or using our support form:

https://wpjobmanager.com/support/

GitHub issues should only be used for bug reports and the like, not support requests. Thanks!
