### ISSUE TITLE
Recaptcha not visible on Apply Job Page

### ISSUE THREAD

**Issue by piyush7g** [Automattic/WP-Job-Manager#587]
As per WP Job Manager document, 
https://wpjobmanager.com/document/tutorial-adding-recaptcha-job-submission-form/

i enabled recaptcha using code on Submit Job and Submit Resume.
i also want to add recaptcha on "Apply Job"  page. So, i added following code also but it is not visible on Apply Job page.

add_action( 'job_application_form_fields_end', 'recaptcha_field' );
add_filter( 'application_form_validate_fields', 'validate_recaptcha_field' );

Have i used the correct code or this code is for something else ?
Please guide me how i can put recaptcha on Apply job to prevent the robotic intervention.
![apply job](https://cloud.githubusercontent.com/assets/16690133/12303333/bfffc6ba-ba4f-11e5-82fa-4599015e99e3.png)

**Comment by aheckler** [comment]
Hi there!

Please use this form to get support for our paid add-ons:

https://wpjobmanager.com/support/

GitHub issues should only be used for bug reports and such. Thanks! :smile:
