### ISSUE TITLE
Expired Jobs do not Delete

### ISSUE THREAD

**Issue by tedmasterweb** [Automattic/WP-Job-Manager#589]
Expired jobs are not being automatically deleted when they expire. I'm pretty sure this was working up until about 6 months ago.

Steps to Reproduce
1. Create a new job and se the expiration date to be in two days.
2. Wait 3 days.
3. Check the list of jobs.

Expected Result
- Job is in the trash

Actual Result
- Job is still in the list of published jobs (but is expired)

I added the following code to functions.php in the child theme but it doesn't seem to be working:
```
// found here https://gist.github.com/mikejolley/27fe7edb343a078d97be
// This will make sure expired jobs are deleted after XX days
add_filter( 'job_manager_delete_expired_jobs', '__return_true' );

// The default is 30 days, but you can change this with the following
add_filter( 'job_manager_delete_expired_jobs_days', 'change_job_manager_delete_expired_jobs_days' );

function change_job_manager_delete_expired_jobs_days() {
   return 30; // change this to the number of days you desired
}
```

**Comment by aheckler** [comment]
Hi there!

Please use this form to get support for our paid add-ons:

https://wpjobmanager.com/support/

If we end up finding a bug in our job expiration code, we can open a GitHub issue then. It's more likely to be a simple misconfiguration though. 

Thanks! :smile:

**Comment by tedmasterweb** [comment]
Hi,

Thanks for the reply. I find the page you linked to to be utterly confusing. That page says: "For help with premium add-ons, please login to your account and post via the support section." but the "support section" link is to the same exact page (links to itself), even if I'm logged in.

Where, exactly, am I supposed to post my issue? I am a little poor-sighted but I do not see a form or a link where I can post my issue (even when wearing glasses).

Thanks and I hope to hear from you.

Sincerely,

Ted Stresen-Reuter

**Comment by aheckler** [comment]
You may need to sign in here first:

http://wpjobmanager.com/my-account/

If you don't have an account (because you haven't purchased any of our premium add-ons), you can also post in our WordPress.org forums here:

https://wordpress.org/support/plugin/wp-job-manager

Sorry for the unclear instructions!

**Comment by tedmasterweb** [comment]
(quoting you) "You may need to sign in here first"

(quoting myself) "even if I'm logged in"

It is a premium plug-in. We have a license, acquired it as part of the purchase of the Jobify theme. The license was in my account on wpjobmanager.com and active but now I don't see how I can tell the status of the license (there does not seem to be any place to list the licenses).

On the my-account page it says: "Hello Ted (not Ted? Sign out). From your account dashboard you can view your recent orders, manage your shipping and billing addresses and edit your password and account details." but I see none of that. All I see is what appears to be a footer ("Newsletter" and "Need help?").

What am I doing wrong?

TIA

Ted

**Comment by mikejolley** [comment]
>  We have a license, acquired it as part of the purchase of the Jobify theme

Our plugins are purchased separately to Jobify theme.

**Comment by tedmasterweb** [comment]
Hmmm… Ok… then maybe we don't have a license… Would that explain why I don't see anything on the my-account page http://grab.by/NFbk ? I'll look into the license issue too and get back to you. Should I reply here or somewhere else?

TIA

Ted

**Comment by aheckler** [comment]
> Would that explain why I don't see anything on the my-account page?

Yes.

> Should I reply here or somewhere else?

Once you have a license, you should be able to submit a support request. Without a license, you can still use the forums linked above.

**Comment by tedmasterweb** [comment]
I see my confusion… I have licenses for a number of WP Job Manager Add-ons (Applications, Job Alerts, Resume Manager, etc.) but apparently never bought a license for WP Job Manager. In fact, now I'm really confused because in the plugin description it says: "The core WP Job Manager plugin is free and always will be." What am I missing?

I hope you all can understand my confusion and provide a little more guidance.

Thanks again.

Ted

**Comment by aheckler** [comment]
> What am I missing?

WP Job Manager itself is free:

https://wordpress.org/plugins/wp-job-manager/

> I have licenses for a number of WP Job Manager Add-ons

Where do you see these, or where are you getting them?

**Comment by tedmasterweb** [comment]
We bought them as add-ons after we bought the Jobify theme (sorry for the earlier confusion). [Here is a screen shot](http://grab.by/NGwk) from the actual site showing the installed plugins.

Apply with LinkedIn is disabled because we decided we didn't wan't to use it.

Job Alerts has an expired license and we decided not to renew it because we aren't actually using it either.

The others, as you can see, have valid licenses.

So… I'm really sorry to be using this outlet for reporting my issues because it probably isn't related to the plugin but I find the support site to be unusable, probably because of something really obvious that at my advanced age escapes me.

Now, I should note that these jobs are being added by a plugin I wrote that takes jobs sent from Broadbean and inserts them as Job Manager jobs (complete with expiration date and all other metadata), and the expiration date displays properly, and you can see which ones have clearly expired, but it crosses my mind that perhaps you've changed the metadata for the post type in a recent update such that my plugin is failing to set a variable needed for the auto-delete function to work. Is that possible? While I wait for an answer I'll do some additional testing…

I'll gladly move this conversation elsewhere but perhaps someone reading this may find value in our eventual resolution?

Ted

**Comment by andrew40** [comment]
I would hazard a guess at it being your plugin and the importation of data from broadband being the main cause of the issue, as i don't have any of the issues you have with a nearly identical use of plugins.

**Comment by tedmasterweb** [comment]
Thanks for the feedback @andrew40. Still testing here. I have to guess I'm on the right track because it did work perfectly up to about April of 2015.

**Comment by mikejolley** [comment]
> Now, I should note that these jobs are being added by a plugin I wrote that takes jobs sent from Broadbean and inserts them as Job Manager jobs (complete with expiration date and all other metadata), and the expiration date displays properly

Install DEBUG BAR and DEBUG BAR CRON. Ensure the job_manager_check_for_expired_jobs job is actually running.

If the cron is running, this is the query we use to delete jobs https://github.com/Automattic/WP-Job-Manager/blob/master/includes/class-wp-job-manager-post-types.php#L417-L430 You could try running that query manually to see if your broadbean jobs match. They need to be expired and not modified for X days. If a plugin syncs or edits these jobs, the modified date will change.

**Comment by tedmasterweb** [comment]
Thanks Mike. Was testing exactly that query when your suggestion arrived :-)

I have to suspect the cron is not running because the query works, the expired job IDs are being returned. I'll confirm my suspicions and post my results here.

THANK YOU for your help!!!

PS: when I insert the cpt jobs coming from Broadbean, I'm setting the _job_expired value as 'YYYY-MM-DD HH:MM:SS' but I see that you are only setting the date. Looking at your code that shouldn't matter, but thought I'd mention it in case you see something I don't…

**Comment by tedmasterweb** [comment]
Ok, problem resolved, and I feel *really* stupid… Jobs are set to expire after 30 days. job_manager_delete_expired_jobs_days is also set to 30 days. 30 + 30 = 60… Need I say more? (banging head on desk and sheepishly existing the stage - thanks again for the support).

**Comment by tedmasterweb** [comment]
And one last thing… I'm trying to delete expired jobs immediately so I set job_manager_delete_expired_jobs_days to 0.

Given a job that expires on 27-Jan-2016. The cron for expiring jobs runs on 28-Jan. The post's modified date is then 28-Jan as well and the SQL used to delete jobs won't delete this expired job because it's date modified is not less than 28-Jan.

Would it make sense to modify the query to be <=?

Thanks again.

Ted

**Comment by abossola** [comment]
I had the same issue. Deactivating and reactivating of WP-Jobmanager did the job. For some reasons the wp-job-manager cron did not load correctly.
