### ISSUE TITLE
Add qtranslate-x support

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#590]
Their docs: https://qtranslatexteam.wordpress.com/integration/

I'm noting it here to gauge demand. 2 requests in the w.org forums today.

**Comment by mikejolley** [comment]
Perhaps @johnclause can weigh in how we'd do this like the Polylang/WPML integration. The docs don't cover our usage.

**Comment by Tbilisilocalguide** [comment]
if it's will happen, i will be so happy!
plz plz :)
thanks!

**Comment by gudh** [comment]
It's "qtranslate-x", instead of "x-translate", right?

Just want to write down my problem here: I translated my job listings with qtranslate-x, however the job listing title which used qtranslate-x shortcode to translate doesn't take effect

**Comment by iarouse** [comment]
May I ask if it's gonna be supported?

Thanks!

**Comment by mikejolley** [comment]
@iarouse If the qtranslate team want to chime in yeah...

**Comment by Tbilisilocalguide** [comment]
Any News guys? 
thanks
Best Levan

**Comment by queinidom** [comment]
I currently work on a multilingual WPJM project, I use QTranslate-X to manage the languages and its working.

**Comment by jrosseel** [comment]
Hi @queinidom. Did you write any integration code or did it work out of the box?

**Comment by richardmtl** [comment]
Requested in 1037762-zen

**Comment by jom** [comment]
QTranslate-X hasn't had an update since June 2016 so I'm going to mark it is as low priority. If anyone has code that improves compatibility, feel free to submit a PR or post the code here and I can add it.

**Comment by thedebian** [comment]
Closing this issue as the plugin is not available on wp.org since 2021.
