### ISSUE TITLE
Added Functionality: Private Messages in Job Posting

### ISSUE THREAD

**Issue by apsilva028** [Automattic/WP-Job-Manager#591]
I have a need for an improvement.  Right now, we allow employers to list jobs (project-based jobs) and for employees/contractors to search jobs (this is all in dev for a bigger project).  But we would like to have employees/contractors be able to "bid" on the jobs (we have two defined roles with separate forms) with a handful of custom fields from the employee/contractor submission side that would then appear/display under the job that the employer posted.  Is this possible?

**Comment by mikejolley** [comment]
We don't currently support PMs or the job bidding type use case. Take a look at https://www.appthemes.com/themes/hirebee/
