### ISSUE TITLE
Job Details Not Outputting to the Post

### ISSUE THREAD

**Issue by apsilva028** [Automattic/WP-Job-Manager#592]
After I create a job and post it, the only details that show up in the dashboard view (and when you click the job) are the description and title.  The job category and my other custom fields should output too so the applicant can see them, but they are not.  Please advise.

**Comment by aheckler** [comment]
Hi there!

Please use this form to get support:

https://wpjobmanager.com/support/

... or post in our WordPress.org forums:

https://wordpress.org/support/plugin/wp-job-manager

GitHub issues should only be used for bug reports and such. Thanks! :smile:
