### ISSUE TITLE
Indeed backfill limited to 25 

### ISSUE THREAD

**Issue by ChrisSparks** [Automattic/WP-Job-Manager#594]
On the Indeed integration, we've always been using more than 25 on our 'Backfill No Results' and 'Backfill After Jobs'. Now it says both are capped at 25. And, all of the sites we have already setup just churn on the search b/c the number is more than 25 I guess.

Is there a way to override this? 

Are we going to have to go into the settings for every site we have setup and change it to 25?

As of right now, the search is not working so the WPJobManager part of our sites is totally useless b/c it will not even show our jobs.

Thanks,

Chris

**Comment by mikejolley** [comment]
No bug here. The code contains:

`
if ( $limit > 25 ) {
			$limit = 25;
		}
`

So it never sends a request for more than 25 listings at a time.
