### ISSUE TITLE
Login won´t work when Woocommerce installed

### ISSUE THREAD

**Issue by norbertomoreau** [Automattic/WP-Job-Manager#597]
Have Woocommerce running without intention to match with WP-Job-Manager. 
Result: when login I end up in the Woocommerce user form.
Any workaround?

**Comment by mikejolley** [comment]
Job Manager doesn't have its own login form, so thats left to whatever else you're running. On most installs, to prevent admin access you'll go to my account to login when woocommerce is installed. This is correct.
