### ISSUE TITLE
Delete company logo if it's no longer in use

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#599]
If I have enough jobs posted to my site, eventually I'm going to accumulate quite a few company logo images. Those stick around even after the jobs they belong to have long since expired. We should delete them instead, maybe as a part of this process? 

https://github.com/Automattic/WP-Job-Manager/blob/1.24.0/includes/class-wp-job-manager-post-types.php#L418-L432

From: https://wordpress.org/support/topic/company-logo-not-deleting-in-media-library

**Comment by mikejolley** [comment]
This is not a great idea for 2 reasons;

1. Images in the media library can be added to content.
2. Company logo images may have one direct association with a post, but can be used by multiple.

There are plugins to delete unused media; use one of those.

**Comment by andreasvr6** [comment]
Hello,
can you recommend some plugins to delete unused media?
Regards,
Andreas

**Comment by aheckler** [comment]
@andreasvr6: It seems like this plugin is the most popular one for doing that:

https://wordpress.org/plugins/image-cleanup/

... but use with care, since it hasn't been updated in a long time.
