### ISSUE TITLE
Job alerts Bug 

### ISSUE THREAD

**Issue by JoelMbondi** [Automattic/WP-Job-Manager#600]
Hi,
I bought wp job alert plugin but it's not working. Indeed , I installed the plugin and I joined the shortcode in the page created for this purpose . However, when I arrive on my page and I click on add alert , I have a blank page that appears and I see even more change the wordpress bar.
 Need help thank you .

**Comment by aheckler** [comment]
Hi there!

Please use this form to get support for our paid add-ons:

https://wpjobmanager.com/support/

This repo is for WP Job Manager only, and should be used to submit bug reports only.

Thanks!
