### ISSUE TITLE
Modifying Column Headings in WP Job Manager Dashboard

### ISSUE THREAD

**Issue by airvid** [Automattic/WP-Job-Manager#602]
1. this is my first time on Git Hub.
2. I have posted requests on the plugin pages that I have paid for licences for and they referred me here.
3. I have searched key words "wp job manager dashboard column headings"  "wp job manager admin column headings"  to customize them.

I am trying to conceptualize the architecture and the relation to the various files associated with this plug-in.

Could someone point out the php file that the headings are contained.

My goal is to add / remove and modify the columns to reflect the fields I have added in the WP Job Manager Field Editor Plugin that I purchased.  the headings they have are irrelevant...  also, I need a more robust search. e.g.  Approved Listings= true AND Not Certified = false for example.. that's another story... but for the moment , just need to modify what columns are displayed and how they are displayed?

**Comment by airvid** [comment]
PS, I reviewed https://wpjobmanager.com/documentation/  as well, and did not get any results that helped with Dashboard , Admin or Column.

**Comment by aheckler** [comment]
@airvid: Please file support requests using this form:

http://wpjobmanager.com/support/

GitHub is generally used only for bugs in the actual code or specific feature requests. Thanks! :smile:
