### ISSUE TITLE
Editing job listing creates empty attachment file

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#603]
To repro:
1. Post a job listing.
2. Once it's published, use the Jobs Dashboard page to edit it (e.g. the job title or anything else).
3. Save the listing.
4. Notice a new (but empty) item in your media library:

![screen shot 2016-02-08 at 2 21 37 pm](https://cloud.githubusercontent.com/assets/5512652/12896311/482f1f26-ce6f-11e5-8d92-2b6dc8472ff1.png)

https://wordpress.org/support/topic/editing-a-job-from-front-end-bug

**Comment by spencerfinnell** [comment]
This could have snuck back in #523

**Comment by mikejolley** [comment]
https://github.com/Automattic/WP-Job-Manager/pull/616
