### ISSUE TITLE
Issue with WPJM Claim Plugin & WC Paid Listing

### ISSUE THREAD

**Issue by ethanferdosi** [Automattic/WP-Job-Manager#606]
Hi,

Using the latest release of both Claim & WC Paid Listing plugins, on submission form., all products are showing however it requires to filter those products with 'use for claim' flag ticked.

Thanks
Ethan

**Comment by aheckler** [comment]
@ethanferdosi: Can you please request support here?

http://wpjobmanager.com/support

GitHub should really only be used for specific bugs, but I have a hunch that this is simply being caused by a misconfiguration of your products.

Thanks! :smile:
