### ISSUE TITLE
Characters for Job Listing hidden in mobile css

### ISSUE THREAD

**Issue by jwdavidson** [Automattic/WP-Job-Manager#609]
The file assets/css/frontend.css has a media query for screens upto a max size of 767px. For screens less than 767px the rule is applied correctly but the padding for the left float is incorrect and a number of characters from the job listing are hidden. The rule that needs correction is:

{float:left;width:60%;padding:0}

and can be corrected by using

{float:left;width:60%;padding-left:3em}

**Comment by aheckler** [comment]
@jwdavidson: Can you link to a site where this is happening so we can take a look? Thanks! 

Relevant line in the LESS file: https://github.com/Automattic/WP-Job-Manager/blob/1.24.0/assets/css/frontend.less#L892

**Comment by mikejolley** [comment]
No padding is needed because no image is shown there. This is the default view:

https://dl.dropboxusercontent.com/s/bflgtds2e6ah1co/2016-02-26%20at%2012.00.png?dl=0

Perhaps you have a theme with custom output, in which case it will need its own responsive styles.
