### ISSUE TITLE
Company / job logo disappears when editing again after preview

### ISSUE THREAD

**Issue by jonasvogel** [Automattic/WP-Job-Manager#613]
To reproduce:
1. Create a new job, upload a logo for it
2. Go to job preview
3. Don't submit the job, but edit it again
4. Now the logo (which was uploaded before) is not there

**Comment by aheckler** [comment]
Also mentioned here: https://wordpress.org/support/topic/need-to-reupload-logo-after-clicking-edit-listing-with-submitting-a-job

**Comment by richardmtl** [comment]
Re-opening; the user in 1955503-zen claims that this is still happening.

**Comment by jom** [comment]
I think this is a duplicate of #613, but need to confirm that we didn't make it worse with this wee security tightening: https://github.com/Automattic/WP-Job-Manager/pull/1690/commits/6158253ffecc27069119f1e045df3f41aca99172

**Comment by jom** [comment]
Unable to reproduce. I'm guessing duplicate of #576
