### ISSUE TITLE
Upload file fields generate trash if empty on submit.

### ISSUE THREAD

**Issue by andreilupu** [Automattic/WP-Job-Manager#615]
Hi,

I just notice that if a user submits a job and he doesn't choose a logo, the plugin will create an empty attachment.

Tested on Twenty Sixteen once with the wordpress.org version and with the master branch and this happens if I submit one listing with logo and another without: 
![screen shot 2016-02-24 at 10 32 09 am](https://cloud.githubusercontent.com/assets/1893980/13279650/019aae34-dae2-11e5-9a36-c6d133896958.png)

After digging in code, I've noticed that on the **create_attachment** method there is no check on the [$attachment_url variable](https://github.com/Automattic/WP-Job-Manager/blob/e62dae9353989181a69696fcdfddcf8b527fe032/includes/forms/class-wp-job-manager-form-submit-job.php#L518) and this will be passed to **wp_insert_attachment** even if it's empty.

I'll be happy to do a pull request if needed.

Thanks,
Andrei

**Comment by spencerfinnell** [comment]
Related #603

**Comment by mikejolley** [comment]
https://github.com/Automattic/WP-Job-Manager/pull/616
