### ISSUE TITLE
[jobs] shortcode is not querying jobs on non default languages using WPML. 

### ISSUE THREAD

**Issue by vukvukovich** [Automattic/WP-Job-Manager#617]
On multilingual site using WPML plugin, [jobs] shortcode is only listing jobs on default language. On other languages "There are no listings matching your search." is shown.

**Comment by mikejolley** [comment]
This is a WPML issue - they said they would come by here and comment/suggest workarounds but nothing yet..

**Comment by vukvukovich** [comment]
It looks like your AJAX calls are not following WP codex standards, and it is related to that?

**Comment by mikejolley** [comment]
Custom ajax endpoints is not against standards. It's a more efficient way of doing ajax calls. The code for WPML still sets lang:

https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L754

**Comment by mikejolley** [comment]
And https://github.com/Automattic/WP-Job-Manager/blob/5d96bb4ebcaf3106cc5c90c01951e851b8700254/wp-job-manager.php#L158

**Comment by mikejolley** [comment]
Maybe you can check your jobs page to see if ICL_LANGUAGE_CODE is set. It's apparently one of their constants.

**Comment by vukvukovich** [comment]
I did breakpoint on it, and it looks that later is reverted to default language an not showing content. Do you have any clue where it can happen?

**Comment by mikejolley** [comment]
I'd only guess that WPML is not setting it to the posted LANG. Maybe it changed the way it picks up language codes.

**Comment by kochhase** [comment]
hi vukukovich, that was the reason why i have changed to polylang. since polylang 1.8 it is working fast an you could use https://de.wordpress.org/plugins/lingotek-translation/ for any kind of translation.
