### ISSUE TITLE
Resume Visibility Issue

### ISSUE THREAD

**Issue by dougherty6504** [Automattic/WP-Job-Manager#618]
Hi There

I tried using the snippet you suggested here https://gist.github.com/mikejolley/20d77105f88e54f0c01e#file-gistfile1-php but the problem is my packages are set I only offer 1 job posting per package therefore as soon as they use that one job I believe it stops access to the resume database.. is that correct?

I need them to be able to continue to have access through the duration of time the job listing is active. Is this achievable? 

Many thanks

Keith

**Comment by mikejolley** [comment]
Hi Keith,

This is not a support area. Please use github to log bugs only. What you're after is customisation which we do not provide.  

You want https://gist.github.com/mikejolley/f20343cbaa3a530cc8ee anyhow.
