### ISSUE TITLE
Bug when viewing application

### ISSUE THREAD

**Issue by ariabramson** [Automattic/WP-Job-Manager#620]
After editing a custom application field through the dashboard, this error shows up at the bottom of an application when viewed at /?action=show_applications&job_id=99

fpu-thumb-fld
a:2:{s:9:"_thumb_id";N;s:11:"_thumb_type";s:10:"attachment";}
tc-thumb-fld
a:2:{s:9:"_thumb_id";b:0;s:11:"_thumb_type";s:10:"attachment";}
post_slider_check_key
0

**Comment by mikejolley** [comment]
You have a plugin (slider?) saving meta data to the post without an underscore _. Underscore prefixed meta is hidden. Everything else is visible.

See job_application_meta() function if you need to customise this.
