### ISSUE TITLE
Paid Listings Plugin Stopped Working

### ISSUE THREAD

**Issue by moogster1** [Automattic/WP-Job-Manager#624]
Hi - I run the following site:

https://luxpages.co.uk/

I bought, downloaded and successfully activated the Paid Listings plugin and had it working fine.

I have just retested and the plugin, which is meant to kick in once an item is selected here:

https://luxpages.co.uk/choose-a-package/

has stopped working. 

I've gone through every setting in the back office and have deactivated / uninstalled all plugins that have been installed since the original installation but no cigar.

I'm pulling my hair out now!  Can you please take a look for me...

Thanks
moogster1

**Comment by mikejolley** [comment]
Can you use https://wpjobmanager.com/support/ please. This is an issue tracker for core, not extensions. Also note the choose a package page you're linking too is from the theme, not paid listings.
