### ISSUE TITLE
Apply with LinkedIn

### ISSUE THREAD

**Issue by stefek99** [Automattic/WP-Job-Manager#634]
Duplicates: #189 #473 

Related: #539

List of add-ons: https://wpjobmanager.com/add-ons/

Some articles about limiting API access: http://thenextweb.com/dd/2015/02/12/linkedin-takes-aim-developers-plans-lock-apis/

Apply with LinkedIn documentation: https://developer.linkedin.com/docs/apply-with-linkedin

That's my "micro research" - it should be possible to Apply with LinkedIn - I think it's much more relevant than apply with Facebook or Xing...

Thanks

**Comment by kraftbj** [comment]
Due to the overall difficulty of gaining suitable API credentials from LinkedIn, we discontinued our Apply with LinkedIn product.

**Comment by stefek99** [comment]
Understood.

No application with LinkedIn.

There is option to create resume with LinkedIn:

![image](https://cloud.githubusercontent.com/assets/249703/14225752/fc44c64a-f8cd-11e5-8148-5133dbd4e2d1.png)

Option requires single **API key**.

In LinkedIn I have **client ID** and **secret**:
![image](https://cloud.githubusercontent.com/assets/249703/14225754/3198bdd8-f8ce-11e5-8472-ff197d0aad33.png)

---

Is it straightforward to make it work or ```create resume with LinkedIn``` option should be removed?
