### ISSUE TITLE
Displaying Apply URL: Better default?

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#635]
In https://github.com/Automattic/WP-Job-Manager/blob/master/templates/job-application-url.php , we display the full URL as the link. If an employer is using URL-based tracking, these URLs can be gnarly. Is there a better default we could use (noting that site admins can override with a custom template).

2585036-t

**Comment by rtemery** [comment]
Agreed, this imperitive for external apply clicks.  The way links render now look spammy, and most employers are using ATS systems which generate very long-tail URLs.  It would be idea to just have a setting in admin to select (a) directly click through on 'Apply Now' target="blank" or (b) open job applications window and display a button.  Note: this solution would need to also be compatible with 'Applications Add-on'.

Is there a filter approach to this now with code I could use?

**Comment by jom** [comment]
I vote for just showing the host name. For example, for a URL like http://example.com/jobs/cool-job-zhjdujf838enjrhd?ref=wpjm-awesome-site-really-great&cool=true, just show:

> To apply for this job please visit [example.com](http://example.com/jobs/cool-job-zhjdujf838enjrhd?ref=wpjm-awesome-site-really-great&cool=true).

Or something similar.
