### ISSUE TITLE
Allow new user to set password

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#637]
When WPJM is set to create an user account automatically when submitting a job listing, we do not request a password from the new user. Since WordPress no longer e-mails out a pregenerated password, this would require all users to go through the Lost Password flow to determine their password.

The ability for the user to set a password initially would make the process more streamlined.

**Comment by edd677** [comment]
This would be a **massive** positive.

**Comment by tripflex** [comment]
Just to clarify for others, yes with WordPress >= 4.3.1 the user is required to go through the lost password flow ( RIP https://github.com/tripflex/wp-login-flow ), but they are still sent an email with the link to set their password (they don't have to request lost password email).  This provides "email verification" for the account, but I do understand some ppl may not want that  ...

**Comment by steveambielli** [comment]
Is there an option to do a template override to include a password field? I also noticed that WPJM and Resume Manager are not tied into the WooCommerce registration process like the Jobify theme is. It would be nice to have this option so that the registration process goes through one channel.

**Comment by TAugusitne** [comment]
This is definitely a much required option. It doesn't look great to send registered users to the back-end of Wordpress site to reset their password.

**Comment by vishalanurag** [comment]
I have edited /wp-job-resume-managerV1113/includes/forms/class-wp-resume-manager-form-submit-resume.php and /wp-job-manager/wp-job-manager-functions.php file to make the Password working in my Job Board. And Its working !

**Comment by ryantodd** [comment]
I have stumbled across the same issue.  Would be good to get a fix for this until WPJM resolves this issue in a new update.  I've also found some information which may help. http://slobodanmanic.com/249/wordpress-set-password-during-registration/

Ideally what I'd like to see is an option for a user to set a password at the job submit form if not already registered and logged in.

**Comment by celiageeks** [comment]
I am having the same issue. If they create their account at the same time that they are submitting their first form, they should have the ability to create their password too. We have a lot of complains from our client because of that. I wish the plugin would have a registration or login option before even posting. It makes it very confusing to fill the form and it creates an account. Only the text helped them understand what is happening, not ideal at all. Really hope something can be done to solve that.

**Comment by dixiyus** [comment]
Hello, i'm having the same issue too. Add a password field on job submission form would be a really good idea !
