### ISSUE TITLE
Add action before upload and after upload

### ISSUE THREAD

**Issue by mikejolley** [Automattic/WP-Job-Manager#639]
https://github.com/Automattic/WP-Job-Manager/blob/9d2cc849f4364976012065a0f43e57538cfc74bc/wp-job-manager-functions.php#L691

To allow modification of WP globals such as max filesize.

**Comment by tripflex** [comment]
:+1: was actually going to add comment on limiting # of uploads regarding limiting upload size, but this works :)

**Comment by kdstudio** [comment]
Hi,

I am sorry I am new at GitHub and I don't get it. Did you do any modification to wp-job-manager-functions.php??? I am not sure how to read your comment. Could you please clarify?

**Comment by danjjohnson** [comment]
@kdstudio no there hasn't been any code added yet.

I've added a workaround here, which people can add themselves:
https://wpjobmanager.com/document/limit-file-upload-size/

**Comment by jom** [comment]
Closing this in favor of work around. This seems like something best done using the filters in the work around.
