### ISSUE TITLE
AJAX Filters: Provide way to fire outside of jQuery.ready

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#640]
When using some AJAX-based page loaders, WPJM's AJAX call will never fire since we call it on [`jQuery.ready()`](https://github.com/Automattic/WP-Job-Manager/blob/master/assets/js/ajax-filters.js#L1)

Untested, but if we define our functionality in a function that is fired upon ready, but could be called otherwise, that would give other plugins/themes/site admins a way to trigger our event after their ajax load has finished.

**Comment by jom** [comment]
Closing, but will inform #1287
