### ISSUE TITLE
job_manager_dropdown_categories doesn't process selected category

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#642]
#### What I Expected To Happen

In an url, using `?search_category=foo` to preload the filter with the category.
#### What Happened Instead

No category is preselected.

It looks like everything functions right until job_manager_dropdown_categories is called. While there is a `selected` arg, I don't see it being used anywhere on the output.

**Comment by spencerfinnell** [comment]
You have to pass the term ID currently.

**Comment by chaselivingston** [comment]
@kraftbj Could you take another look at this in light of @spencerfinnell's comment?

**Comment by jom** [comment]
Confirmed that it is term ID. Closing.
