### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by wombizclub** [Automattic/WP-Job-Manager#645]
How do I get an email notification when a job is submitted - this doesn't seem possible at the moment and I am missing jobs that are being submitted?

**Comment by mikejolley** [comment]
You can use https://wordpress.org/plugins/post-status-notifier-lite/

**Comment by kochhase** [comment]
Hi wombizclub,
and this new plugin will be mutch better.
https://plugins.smyl.es/wp-job-manager-emails/

because in the near futur you can have notification by time. so you can send employer an email 5 days before his ad service will end.

**Comment by wombizclub** [comment]
Thank you

**Comment by tripflex** [comment]
Yeah i'll be adding a TON of new features to the emails plugin within the next couple weeks, including integration with every plugin I can that deals with WP Job Manager, new user notifications, password reset emails, etc.  

Right now initial release has a new "default" email setup for core WP Job Manager to send an email when a job is submitted, next release will allow you to create multiple emails for that same action, so if you want to send a different email to admin and the user, you will be able to.
