### ISSUE TITLE
Job Still Shows in job Listing When Deleted with `wp_delete_post`

### ISSUE THREAD

**Issue by wpmark** [Automattic/WP-Job-Manager#649]
I have a function that allows the deletion of jobs through functionality which uses the `wp_delete_post()` function. This seems to work fine in that the job is delete and removed from the admin post listing screen for jobs.

However when viewing the listings on the front-end (the page which shows all jobs with the filters above) the job remains in that list. When clicked to view, of course, it gives a 404.

I think the WP Job Manager plugin is caching this listing and was wondering how I would clear this cache when I delete the job using `wp_delete_post()`.

**Comment by chaselivingston** [comment]
@wpmark Could you contact us at https://wpjobmanager.com/support/ if you're still having problems?
