### ISSUE TITLE
schema.org markup

### ISSUE THREAD

**Issue by mikejolley** [Automattic/WP-Job-Manager#65]
http://schema.org/JobPosting

**Comment by brenthealy** [comment]
This is not done. please reopen. @mikejolley Look at the source of 
https://www.nigelfrank.com/us/vacancy/214153/nfiesdevacx
`<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "JobPosting",
    "datePosted": "2017-03-14",
  "description": "MS Dynamics AX Developer 
Malaga, Spain 


This is a very exciting opportunity to join an important IT company that is currently expanding their consulting team. We are looking for an experienced MS Dynamics AX Developer who will be based in their Malaga office. No Spanish required! 


Requirements: 

Previous MS Dynamics AX experience 
Advanced knowledge of X++, ASP.MET, C#, Visual Studio, SQL Server 
Sure Step methodology experience 
Strong analytical skills 
Excellent communication skills 
Motivation 
Fluent English 



In return the company will offer you among others: 

Very competitive salary 
Relocation package 
Career progression 
Excellent training 
Access to the leading technologies 
Great work environment 




Please contact Paulina at +34 518 880 803 or email resume to p.zajac@nigelfrank.com to ensure a spot for interviews IMMEDIATELY! 

Nigel Frank International is the global leader for Microsoft Dynamics recruitment, advertising more Dynamics jobs than any other agency. We deal with both Microsoft Partners &amp; End Users throughout Spain&amp;Portugal. By specializing solely in placing candidates in the Microsoft Dynamics market I have built relationships with most of the key employers in Spain&amp;Portugal and have an unrivaled understanding of where the best opportunities and Dynamics jobs are. 

I understand the need for discretion and would welcome the opportunity to speak to any Microsoft Dynamics candidates that are considering a new career or job either now or in the future. Confidentiality is of course guaranteed. For information on the Microsoft Dynamics market and some of the opportunities and Dynamics jobs that are available I can be contacted on +34 518 880 803. Please see www.nigelfrank.com for more fantastic Microsoft Dynamics opportunities! ",
  "employmentType": "full-time",
  "industry": "Dynamics AX",
  "jobLocation": {
    "@type": "Place",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "Romania"
    }
  },
   "skills": "MS DYNAMICS NAV, NAVISION, AX, AXAPTA, CRM, FUNCIONAL, CONSULTOR, CONSULTANT, FUNCTIONAL, TECHNICAL, PARTNER, MS GOLD, CONSULTORA, CLIENTE FINAL, INTERNACIONAL, PLAN DE CARRERA, MADRID, BARCELONA, CATALUNA, AX, JEFE DE PROYECTOS,ANALISTA ",
    "title": "MS Dynamics AX Developer  "
}
</script>`

**Comment by bikedorkjon** [comment]
Mentioned in 3110767-t

**Comment by jom** [comment]
Closed w/ #1115
