### ISSUE TITLE
Date resets when reactivating an expired listing

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#653]
#### What I Expected To Happen
- Edit an expired listing in wp-admin
- Change the expiry date to a future date, and click Publish
- I expected the job status to be active with the new expiry date I set. 

#### What Happened Instead
- When you click Publish, the job status is active, but the new expiry date disappears and you have to set it again.

#### Steps to Reproduce the Bug

- Edit an expired job
- Change the expiry date to a future date
- Publish the job

2623029-t

**Comment by MADagency** [comment]
Hello
Did you manage to solve this issue ?

**Comment by MADagency** [comment]
thanks for you reply ;-)

**Comment by donnchawp** [comment]
It looks like the problem is in set_expiry() in class-wp-job-manager-post-types.php - it checks for the stored value of the expiry date, but not the POST value, and then resets the POST value and returns.

**Comment by donnchawp** [comment]
#782 should fix it but I'd like to see some testing of it first.
