### ISSUE TITLE
Using [jobs show_filters=false] shortcode in a template/page with debug enabled returns a notice in response.

### ISSUE THREAD

**Issue by anishss** [Automattic/WP-Job-Manager#654]
#### What I Expected To Happen

- Added `echo do_shortcode('[jobs show_filters=false show_pagination=true]')` to a page/post.

- Expected a grid/list of listings without any filters to be displayed on the page/post.

#### What Happened Instead

- No listing was displayed. The listing in the grid had their visibility set to hidden.

- Only the loading image/gif was displayed.

- A notice was returned alongwith data in the json response of get_listings.

- Following notices were thrown in WP_DEBUG_LOG:

- PHP Notice:  Undefined index: form_data in /vagrant/wordpress/src/wp-content/themes/listify/inc/integrations/wp-job-manager/map/class-wp-job-manager-map-template.php on line 359

- PHP Notice:  Undefined index: form_data in /vagrant/wordpress/src/wp-content/themes/listify/inc/integrations/wp-job-manager/class-wp-job-manager-template.php on line 908

#### Steps to Reproduce the Bug

- Set WP_DEBUG to True

- Add `echo do_shortcode('[jobs show_filters=false show_pagination=true]')` to a page or post.

- Load the page/post.

**Comment by anishss** [comment]
Using `[jobs show_filters=false]` isn't working too.

**Comment by chaselivingston** [comment]
@anishss Seems like this is a problem with the Listify theme and not WPJM.
