### ISSUE TITLE
JOBS NOT SHOWING UP AFTER UPDATE!!!

### ISSUE THREAD

**Issue by carissam** [Automattic/WP-Job-Manager#659]
All of my jobs are there in the back-end, but they are not showing up on the front-end for people to see. I did not change anything. I did see that there was an update 4 days ago with the plugin --- could that be causing something???

http://yoursearchstaff.com/search-jobs/

Thanks

**Comment by mikejolley** [comment]
There was no update 4 days ago, just an update to readme content. it's your theme: https://dl.dropboxusercontent.com/s/2s7jdepvoe7o7xx/2016-04-25%20at%2017.40.png?dl=0

It is not compatible with WordPress 4.5.

**Comment by carissam** [comment]
Gotcha. Thank you!!!
