### ISSUE TITLE
Evaluate Support for the WordPress REST API

### ISSUE THREAD

**Issue by georgestephanis** [Automattic/WP-Job-Manager#661]
Let's evaluate whether it's worthwhile to add support for the WordPress REST API -- to make job listings more available to third-party apps and integrations and such.

Potential pitfalls would be sites whose job listings are behind some sort of authentication or paywall -- the methods used to lock those down may not also extend to the REST API -- for example, if they're just locking down the page that the job listing shortcode is embedded on.

If added in, should this be opt-in or opt-out?  Should it be opt in/out via a filter or a checkbox in the admin?  v1 should include job listings as a minimum, but should job creation via the REST API also be supported?  How should we handle extra options enabled by third-party addons?

Just looking to start the discussion here as to how to support it.

**Comment by pavankumarkatakam** [comment]
It would be nice to have an API for this, so that users are able to create APP also using the API's.

**Comment by judgej** [comment]
Is this still open for evaluation, or did it get developed?

**Comment by jom** [comment]
We are in the process of building this using WordPress core's REST API framework. 

https://github.com/Automattic/WP-Job-Manager/tree/features/rest-api

**Comment by judgej** [comment]
Thanks. I guess github makes it easy to see the [changes on a branch](https://github.com/Automattic/WP-Job-Manager/compare/features/rest-api) to follow what's happening.

[I raised it here too](https://wordpress.org/support/topic/what-api-facilities-are-available/), and posted a simple workaround to expose the limited job details a need right now, which are fine being public.

**Comment by jom** [comment]
Tracking issue here: https://github.com/Automattic/WP-Job-Manager/projects/6
