### ISSUE TITLE
Blank page on [submit_resume_form] 

### ISSUE THREAD

**Issue by KevinKamunyu** [Automattic/WP-Job-Manager#663]
#### What I Expected To Happen
Front end of resume submission
#### What Happened Instead
Blank page on [submit_resume_form] 
#### Steps to Reproduce the Bug
NIL/NA

**Comment by mikejolley** [comment]
Not enough details provided. Without links, details about your environment etc there is nothing we can do - it works out side and for other users.

**Comment by harishagrawala** [comment]
Pls check this link and assist http://www.insuranceinfo.co.in/submit-resume/ same problem facing after fixing conflict the other plugin now other part of plugin is working fine.. infact if i can remove the code, once we have put the code ... page gone daed.
