### ISSUE TITLE
Different list style to featured jobs

### ISSUE THREAD

**Issue by pailoro** [Automattic/WP-Job-Manager#666]
Hi!

There is some way how to display featured jobs in a grid list view and other as list view?

Thanks! =D

**Comment by mikejolley** [comment]
Not in core, BUT you could output these yourself with code in your template :) See https://codex.wordpress.org/Template_Tags/get_posts

The post type is "job_listing". Featured jobs have a meta key of _featured set to 1.

Good luck!
