### ISSUE TITLE
Allow Searching and Bulk Editing of Applicants

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#668]
Add a search field for applicant name and application keywords. Also allow bulk editing of applications, to set them to a specific status. 

2651679-t

**Comment by davoraltman** [comment]
@jenhooks I am not sure what you meant here exactly. Did you have in mind the /job-dashboard/?action=show_applications&job_id=xx page? If that's the case, we can move this issue to the Applications add-on repo.

**Comment by jenhooks** [comment]
I'm not sure what I meant, here. The user in the original ticket wrote:

> It would be great to have a search field for name/keywords and being able to bulk edit applications (e.g. set them to a certain status). Also it would be great to access the applicants management not only via the job manager link but to have the Application dashboard to show all applicants of all jobs and then having the filters to adjust which applicants are displayed.

From what he was describing, it sounds like all of the things he's requesting are already present in wp-admin. Job Applications can already be searched, though there aren't many bulk actions there -- only Edit and Move to Trash. 

I suppose this can be closed, unless a developer can determine if there's anything worthwhile here -- and yes, I do suppose it should be moved to the Applications repo. Happy to do that if warranted.

**Comment by jenhooks** [comment]
I think I figured it out -- currently, the only way to adjust an Application's [status](https://wpjobmanager.com/document/applications-customising-application-statuses/) is to change it on the Application itself:

![bulk_application_status](https://user-images.githubusercontent.com/7585054/37722623-dd810b0e-2d02-11e8-9c88-81c01eec532f.png)

It would be nice to have these options available on the bulk edit options here? 

![bulk_application_status2](https://user-images.githubusercontent.com/7585054/37722699-0df262e2-2d03-11e8-941f-1787c2f347b1.png)

If this is doable, I'll move it to the Applications repo as an enhancement request.

**Comment by alexsanford** [comment]
@jenhooks Yeah, I think this is definitely feasible! We do something like this for Job Listings already:

<img width="876" alt="screen shot on 2018-03-21 at 15 05 27" src="https://user-images.githubusercontent.com/842193/37728567-63c1b2a2-2d19-11e8-864e-1436a112c0b1.png">

I'd say go ahead with the enhancement request in the Applications repo 🙂

**Comment by jenhooks** [comment]
Thanks Alex -- closing in favor of https://github.com/Automattic/wp-job-manager-applications/issues/155
