### ISSUE TITLE
loading loop when submitting the form

### ISSUE THREAD

**Issue by joe0632** [Automattic/WP-Job-Manager#670]
#### Steps to Reproduce the Bug

Hello,

I download the plugin, it works rather well. However when I want to submit a bid not connected, the page loads without stopping. When I connected it works, but the goal is that anyone can bid and register at the same time.

How to fix this bug?

thank you in advance

**Comment by mikejolley** [comment]
You're registering via the job submission form?

Have you checked your server error logs for clues?

Disabled other plugins?

Tried another theme?

**Comment by chaselivingston** [comment]
Closing since there's been no reply.
