### ISSUE TITLE
Cannot Open Job Application Attachment Links - 404 Error

### ISSUE THREAD

**Issue by k6reed2** [Automattic/WP-Job-Manager#671]
There seems to be a conflict between the plugin and the way WordPress handles attachments or links. When trying to click directly on the attachment link in "Job Applications," I receive a 404 error.

I had a developer confirm that if you add **target="_blank"** to the anchor tag of the attachment links on the application list, it fixes it.

**Comment by mikejolley** [comment]
I don't see how. target="_blank" just opens a new window - the actual link you're sent to should be identical...

**Comment by tripflex** [comment]
Me either, as we have not received any response I can only assume this was a site specific issue that has been resolved.  @k6reed2 if you can provide us more information we will reopen this issue.
