### ISSUE TITLE
Email Notifications to Admin When New Jobs Are Submitted

### ISSUE THREAD

**Issue by jenhooks** [Automattic/WP-Job-Manager#672]
An email notification sent to the site administrator when a new job is posted is a popular request from users, and seems like an intuitive addition to WP Job Manager.

2651428-t

**Comment by spencerfinnell** [comment]
Related #645

**Comment by dkolski** [comment]
Have a look to "post status notifier" which is a great plugin to manage notifications whenever a status of  post type occurs. You can define rules and define for which post-type you want to apply the notification and for which status transition (status before and after).
It costs 20$.

**Comment by quantumleap33** [comment]
Here is a helpful [link](https://wpjobmanager.com/document/tutorial-send-email-employer-job-listing-approved/).
Also [Better Notification for Wordpress](https://wordpress.org/plugins/bnfw/) is really good for that and it's free. Developer is also responsive in the forums.

**Comment by tripflex** [comment]
This is possible in the emails addon as well BTW https://plugins.smyl.es/wp-job-manager-emails

**Comment by jom** [comment]
Bumping this to 1.31.0, which will have a more comprehensive email notification system.

**Comment by codestor4** [comment]
requested: 1052655-zen
