### ISSUE TITLE
WP_Widget convert to abstract class, widget() must  be defined

### ISSUE THREAD

**Issue by tripflex** [Automattic/WP-Job-Manager#673]
Found this fatal error issue when testing `4.6-alpha-37427` where `WP_Widget` class is converted to an abstract class.  Because `widget()` is not defined, fatal error shows up

See:
https://core.trac.wordpress.org/ticket/35981

Needs to be resolved before 4.6 is released

**Comment by kraftbj** [comment]
Reverted per https://core.trac.wordpress.org/ticket/35981 . I don't think there's any harm leaving it in though.
