### ISSUE TITLE
Deleting user does not delete associated listings

### ISSUE THREAD

**Issue by rali14** [Automattic/WP-Job-Manager#675]
#### What I Expected To Happen
All associated content, including listings should be deleted.

#### What Happened Instead
Job listings remain visible on front end and backend.

#### Steps to Reproduce the Bug
1. Create test user
2. Submit new listing
3. Approve listing
4. Delete user + content
5. Job listing remains

Tested on Twenty Fifteen with latest version of WP Job Manager. Report from 2 customers using Listify theme as well.

**Comment by jared77** [comment]
Did you get this sorted? I am having a similar issue in tests but this is when you refund or cancel an order of a package of listings. If the client wants his money back say 4 days later, you can cancel or refund and change status of the order BUT nothing happens to the listings in the member accounts who canceled...unless I am missing how to allow them from adding  new listings after they canceld?
