### ISSUE TITLE
is Mike working any longer on WPJM?

### ISSUE THREAD

**Issue by kochhase** [Automattic/WP-Job-Manager#676]
Sorry, but in the last year Mike was working on WPJM in a streamline. Now he seems to be only working on Woocommerce. What can we do to have some more progress in developing in this very good plugin and the addons? Myles is doing a very good job with his plugins, maybe he can do some core developement for WPJM
that´s my suggestion.
Henryk

**Comment by mikejolley** [comment]
A new squad is taking over core dev so I can focus on WooCommerce :)
