### ISSUE TITLE
Please add feature - bulk action for Filling multiple jobs

### ISSUE THREAD

**Issue by cmeurer** [Automattic/WP-Job-Manager#678]
Could you add a Bulk Action to mark several jobs at once as FILLED? You have this for Expired jobs but for Filled, I have to go into each listing and check the box then update. Let me know if this is something you could add. Thank you!

**Comment by cmeurer** [comment]
Is this something that can be done? Please let me know!

**Comment by cmeurer** [comment]
does this mean you added this feature?!

**Comment by jom** [comment]
@cmeurer It will be in the next release.

**Comment by cmeurer** [comment]
Wonderful! Any idea when that will be? Thank you!

**Comment by jom** [comment]
Not set yet. Hopefully within the next week or two.

**Comment by cmeurer** [comment]
Thanks again!

**Comment by cmeurer** [comment]
Hi Jake - Has it been added? Thanks!

**Comment by cmeurer** [comment]
Hi again - did you add "bulk action for Filling multiple jobs" ? Let me
know!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jom** [comment]
Yup! It has been since 1.27.0.

**Comment by cmeurer** [comment]
thanks!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
