### ISSUE TITLE
Problem using WP Jobs with WP Classifieds at the same time

### ISSUE THREAD

**Issue by godambrosio** [Automattic/WP-Job-Manager#680]
#### What I Expected To Happen
When I go to the Jobs Listing page I have a page with the list of the classifications of the other plugin, if I desactivate the other plugin it works fine and I have the list of the jobs.

**Comment by mikejolley** [comment]
I don't know where "WP Classifieds" came from (cannot find it on .org) but it sounds like it may be using the same post types as us. If thats the case, only one can display and this isn't something fixable.
