### ISSUE TITLE
Shortcode [my_bookmarks] doesn't keep page formating (page title does not show)

### ISSUE THREAD

**Issue by nikkoboy** [Automattic/WP-Job-Manager#682]
#### What I Expected To Happen

When [my_bookmarks] shortcode is inserted into a WP page, I expect the page to keep its original formating (display page title)
#### What Happened Instead

Page title does not appear on pages featuring [my_bookmarks] shortcode
#### Steps to Reproduce the Bug

Insert [my_bookmarks] shortcode in any standard WP page, save, and display. Title does not appears on top of the page. **Theme used:** Listable by Pixelgrade (said to be 100% compatible with WP Job Manager Bookmarks)

**Comment by davoraltman** [comment]
I am unable to reproduce this with the Twenty Sixteen theme and it seems like a theme layout issue/choice. Can you confirm?
