### ISSUE TITLE
Default to site language for geolocation

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#683]
Currently the language used for geolocation defaults to English.

We currently provide users with a snippet to change this:
https://wpjobmanager.com/document/specify-language-for-geolocation/

Seems like it would make sense to default to the current site language instead:
https://github.com/Automattic/WP-Job-Manager/blob/89d75fe34031fc234bb57079bf65e08d0f566be7/includes/class-wp-job-manager-geocode.php#L126

**Comment by jom** [comment]
Closed w/ #1007

@davoraltman @bikedorkjon The documentation page can not say it defaults to the site's locale. This snippet might still be helpful for people who want to specify a _different_ language than their site locale.

**Comment by spencerfinnell** [comment]
A couple will still need it that use a 4 character code. https://developers.google.com/maps/faq#languagesupport

**Comment by davoraltman** [comment]
Updated the page to reflect the current state.
