### ISSUE TITLE
Applications : user still able to apply even when resume is pending for approval with admin

### ISSUE THREAD

**Issue by piyush7g** [Automattic/WP-Job-Manager#686]
#### What I Expected To Happen
I am using both Resume Manager and Applications plugin
User should not be able to apply for job when his resume is in approval pending with admin

#### What Happened Instead
User is able to apply. But there is no drop down coming for selecting online resume

#### Steps to Reproduce the Bug
Create a new user. Submit resume using Resume Manager.
Now it is approval pending state.
But when you apply to some job, there is no validation alert that you can't apply as your resume not approved

**Comment by chaselivingston** [comment]
Closing in favor of Automattic/wp-job-manager-applications#63
