### ISSUE TITLE
Application form is not showing UP 

### ISSUE THREAD

**Issue by accioweb** [Automattic/WP-Job-Manager#696]
#### What I Expected To Happen
Using Job Application plugin but it is not showing up
#### Steps to Reproduce the Bug
I have enabled email and URL but still it is not showing up. I changed the theme to the default themes but still nothing. Also deactivated other plugins.

**Comment by chaselivingston** [comment]
@accioweb If you could submit a support request at https://wpjobmanager.com/support/ we'd be happy to help you there!

**Comment by melanie13** [comment]
hi , i have same probleme .
I inslaller the pluging but the application form does not appear on my website .
i submit email https://wpjobmanager.com/support/  , I have no answer for one week
