### ISSUE TITLE
Bug - Categories for Listing Disabled - Breaks Indeed XML

### ISSUE THREAD

**Issue by rtemery** [Automattic/WP-Job-Manager#698]
Through direct communication with Indeed - we discovered that IF the setting 'Categories for Listings' is disabled, the XML feed leaves that node blank.  The blank node breaks their schema. Indeed's recommendation is to omit the 'Category' tag from the XML in this scenario.

Reproduce:
Job Listings > Settings > Categories > Categories for Listings (unchecked).
Indeed Integration > Enable Indeed XML Feed (checked) > the XML node for 'Category' is empty.

Solution:
removeChild node when Job Categories are disabled (or) simply filter out the node.

**Comment by rtemery** [comment]
From Indeed:
The <category> tag shouldn't be empty. If you want to have the empty category tag in there, it should ONLY be:

</category>

OR, nothing at all.

**Comment by rtemery** [comment]
I fixed this on my instance by overriding the indeed-job-feed.php template file. However, the issue will persist for users IF listing categories are disabled.

**Comment by chaselivingston** [comment]
@rtemery I've moved this issue over to our repo for the Indeed integration, thanks for the report!
