### ISSUE TITLE
Upgrading WP Job Manager - Applications

### ISSUE THREAD

**Issue by RD900Ra** [Automattic/WP-Job-Manager#699]
Hi,
I have general question. Is there any way that plugin "WP Job Manager - Applications" can be adjusted, so that job seeker application will be sent to employer with attachment by e-mail. 

Why?The problem is that all with plugin "WP Job Manager - Applications" stores all data attachment  on my server, and with many daily applications there is a need for a large number of storage on the server.

Regards, Rok

**Comment by chaselivingston** [comment]
@RD900Ra We'd be happy to help you out if you could submit a support request at https://wpjobmanager.com/support/

Thanks!
