### ISSUE TITLE
Custom category search field not working on custom search form template

### ISSUE THREAD

**Issue by flamurbeqiri1** [Automattic/WP-Job-Manager#701]
#### add the custom template search form like in documentation, and search with only category field
here is the code:

`<form method="GET" action="http://localhost/theme-wp/jobs-opportunities/">`
`<select class="form-control adv_frm_style_s" id="search_category" name="search_category">
                      <option value=”” disabled selected>Select</option>
                        <?php foreach ( get_job_listing_categories() as $cat ) : ?>
                          <option value="<?php echo esc_attr( $cat->term_id ); ?>"><?php echo esc_html( $cat->name ); ?></option>
                        <?php endforeach; ?>
                    </select>`
`<button type="submit" class="btn btn-default btn_search_jobs_1">Search Jobs</button>`

**Comment by zahedkamal87** [comment]
@flamurbeqiri1  did you solve this? Please share any extra codes you had to apply to get it working, Thank you
