### ISSUE TITLE
Expired content is still hidden even if I unchecked the "Hide content within expired listings" setting

### ISSUE THREAD

**Issue by WernerLouw** [Automattic/WP-Job-Manager#703]
#### What I Expected To Happen

I unchecked the "Hide content within expired listings", so that everything will show even if it does have an expiry date.
#### What Happened Instead

It hides anyway. Can't get expired listings to show.
#### Steps to Reproduce the Bug

I unchecked the "Hide content within expired listings"...that is it.

**Comment by sissing** [comment]
I found the fix, I need to re-save the Permalink page. Maybe it's an idea to write this somewhere down, because for most people it's non-obvious to reserve the Permalink page.

**Comment by chaselivingston** [comment]
Confirmed.
