### ISSUE TITLE
Make reCAPTCHA a required field

### ISSUE THREAD

**Issue by glutenfreereviewsuk** [Automattic/WP-Job-Manager#704]
On the following URL it is possible to fill in the form but skip the reCAPTCHA and preview the page (you can then obviously submit the listing having not completed the reCAPTCHA): https://glutenfreereviews.co.uk/submit-a-review/

The reCAPTCHA should be a required field and users should not be allowed to preview the page before it has successfully been completed.

How do I fix this?

Thanks,
Phill

**Comment by chaselivingston** [comment]
@glutenfreereviewsuk This should help: https://wpjobmanager.com/document/tutorial-adding-recaptcha-job-submission-form/
