### ISSUE TITLE
job_manager_get_resized_image Loading Incorrect File

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#706]
#### What I Expected To Happen

Use `job_manager_get_resized_image( 'http://image.com/image.jpg', 'thumbnail' );` and get `http://image.com/image-150x150.jpg` returned.

#### What Happened Instead

`http://image.com/image-thumbnail.jpg` is generated and returned instead of the already existing `http://image.com/image-150x150.jpg`

#### Steps to Reproduce the Bug

Call `job_manager_get_resized_image( 'http://image.com/image.jpg', 'thumbnail' );`

#### Suggested Fix

`$resized_logo_path = str_replace( '.' . $path_parts['extension'], '-' . $size . '.' . $path_parts['extension'], $logo_path );`

Should not look for `$size` directly but instead the combined `$img_width` and `$img_height` that are declared above.

```
$dims = $img_width . 'x' . $img_height;
$resized_logo_path = str_replace( '.' . $path_parts['extension'], '-' . $dims . '.' . $path_parts['extension'], $logo_path );
```

**Comment by donnchawp** [comment]
It looks like job_manager_get_resized_image() is only used when the company logo is stored in postmeta, from pre-1.24.0 so those would be old entries but your fix works in my testing. I'll submit a PR shortly.

**Comment by spencerfinnell** [comment]
Cool thanks! Also happens for custom File fields which are are stored in meta still.
