### ISSUE TITLE
Localization error - single job page not found

### ISSUE THREAD

**Issue by sissing** [Automattic/WP-Job-Manager#709]
#### What I Expected To Happen
After choosing a job, to see the detail page of the job.

#### What Happened Instead
I get the page not found error

#### Steps to Reproduce the Bug
The url after choosing a job is: http://www.domainname.nl/vacature/job-name/
but this page isn't available, when I change vacature (dutch for job) to job: http://www.domainname.nl/job/job-name/ and now the page is now visible. But everywhere in the website he wants to use vacature in stead of job. Most likely this has to do with the localization of the plugin.

**Comment by sissing** [comment]
I found the fix, I need to re-save the Permalink page. Maybe it's an idea to write this somewhere down, because for most people it's non-obvious to reserve the Permalink page.

**Comment by chaselivingston** [comment]
Closing since this seems to be related to the translation plugin being used and not WPJM directly.
