### ISSUE TITLE
Product Data Not Appearing

### ISSUE THREAD

**Issue by egjeff4** [Automattic/WP-Job-Manager#710]
Hello,

I am not able to see product data with the WP Job Manager - WooCommerce Paid Listings plugin.  I can't add sale prices anymore, change the product type, etc. 

![edit product certified personal training wordpress](https://cloud.githubusercontent.com/assets/20212281/16464715/7be456e2-3e09-11e6-8000-1d34065e90f5.png)

**Comment by chaselivingston** [comment]
@egjeff4 This seems to be working for me, could be a conflict with your theme or another plugin. If you continue to have trouble, please submit a support request at https://wpjobmanager.com/support/
