### ISSUE TITLE
Creating new addon

### ISSUE THREAD

**Issue by Mopster** [Automattic/WP-Job-Manager#711]
Hello,

We're planning to write an add-on to synchronize jobs and applications with our database software. I couldn't find any instructions on requirements, expectations or any other information regarding developing a WP Job Manager add-on. Is there documentation I missed or is it just creating a standard WP plugin ?

- Mopster

**Comment by chaselivingston** [comment]
@Mopster Just a standard WordPress plugin that extends or enhances the functionality of the core plugin. There are a few others that are open source you could use for some ideas as well.
