### ISSUE TITLE
Google Map API Change Causing Broken Geocoding

### ISSUE THREAD

**Issue by annezazuu** [Automattic/WP-Job-Manager#712]
[See #4240 ](https://github.com/Automattic/jetpack/issues/4240). Google recently changed their map API requiring users to have an API to add. This is causing issues with certain themes in relation to geocoding:

https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update
https://developers.google.com/maps/documentation/javascript/get-api-key
https://developers.google.com/maps/documentation/javascript/error-messages#deverrorcodes

A user provided this filter as a workaround as a short term solution- http://cl.ly/gNwC

Long term, we need to add in an option to WPJM to set the API key.

**Comment by annezazuu** [comment]
brought up here - https://wordpress.org/support/topic/jobs-shortcode-error-no-google-maps-api?replies=1

**Comment by spencerfinnell** [comment]
It should be noted that for the plugin this key should be a Server key, not a Browser key. A theme that provides mapping functionality should have their own input for a Browser key.

But a UI for adding a Server key for geocoding would be welcome.

**Comment by Lens40** [comment]
A simple fix for those who can't wait:

wp-job-manager\includes\class-wp-job-manager-geocode.php LINE 126
`apply_filters( 'job_manager_geolocation_endpoint', "http://maps.googleapis.com/maps/api/geocode/json?address=" . $raw_address . "&sensor=false&region=" . apply_filters( 'job_manager_geolocation_region_cctld', '', $raw_address ), $raw_address ),
`
Change **http** into **https://**

`apply_filters( 'job_manager_geolocation_endpoint', "https://maps.googleapis.com/maps/api/geocode/json?address=" . $raw_address . "&sensor=false&region=" . apply_filters( 'job_manager_geolocation_region_cctld', '', $raw_address ), $raw_address ),`

ADD to theme functions.php as mentioned above (note only the server key works):

`/**
* Add Googlemaps-API Code for WP Job Manager Geolocation
*/

add_filter( 'job_manager_geolocation_endpoint', 'add_geolocation_key_to_endpoint' );

function add_geolocation_key_to_endpoint( $endpoint ) {
  $endpoint = add_query_arg( 'key', 'YOUR SERVER API KEY', $endpoint );
  return $endpoint;
}`

Hope it helps those who are waiting for a fix.

**Comment by campino2k** [comment]
```
add_filter( 'job_manager_geolocation_endpoint', 'make_google_maps_work_again' );
function make_google_maps_work_again( $endpoint ) {

    // add other params like api keys...

    // if http:// is prefixed, change to HTTPS due to google api changes
    $new_endpoint = str_ireplace('http:', 'https:', $new_endpoint);

	return $new_endpoint;
}
```

**Comment by Bertsi** [comment]
When I create the Maps API, does it has to be a Server-API? If yes, my Host is Strato and my Server-IP is flexible. The Google API Manager asks me logically to type in an IP. But if it is changing all the time, it makes no sense. Right? Are there any alternatives?

**Comment by spencerfinnell** [comment]
Create a key with no referrer restrictions and it will work.

**Comment by Bertsi** [comment]
Thanks a lot. It works now. It seems like, the problem was another one. I had installed but not activated a plugin called "GEO my WP", so I didnt took notice of it. But I guess it blocked the WP-Job-Manager-Geolocation-Function somehow. Because after I activated it correctly the geolocation works! So you either have to delete the GEO-my-WP-plugin or activate it.
