### ISSUE TITLE
Job Tags Filters lost when navigating away from page

### ISSUE THREAD

**Issue by nikkoboy** [Automattic/WP-Job-Manager#713]
#### What I Expected To Happen

When I use the Job Tags Filter on the listings page (http://www.fleamapket.com/listings/), and then click on a specific listing, when I go back to the listings page, I expect Job Tags Filters to be kept. When I'm doing a search by tags, I'm not only checking one result, but at least four or five.
#### What Happened Instead

When I click on a specific listing, and then go back to the listings page, all the Job Tags Filters I selected, are lost.
#### Steps to Reproduce the Bug

I tried and reproduce the bug by using the "Category" or "Region" filters, and when I return to the listings page, those filters were kept (which is not the case with "tags" filters). So this is definitely an issue affecting only the Job Tags Filter, and not the WP Theme I use, or other plugins.

Could you tell me how I can edit the plugin's code to keep the Tags filter active, during the same session? Thanks!

**Comment by chaselivingston** [comment]
@nikkoboy Just to confirm, are you using the Job Tags add-on to add these tags you're searching with?
