### ISSUE TITLE
Orderby Rand not working

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#714]
When you try using the shortcode [jobs orderby="rand"], it doesn't display job listings in a random order as it should.

Tried using different themes, the issue persists. Brought up in [this forum thread](https://wordpress.org/support/topic/orderbyrand-doenst-work?replies=1).

**Comment by donnchawp** [comment]
The problem was the caching being done on the WP_Query that fetched the jobs. I just shuffled the posts to make the order different.
