### ISSUE TITLE
Change Employer Notification email address?

### ISSUE THREAD

**Issue by JohnyVA** [Automattic/WP-Job-Manager#717]
Hi, 

When my client receives a notification that a candidate has applied for a job the email address comes from 'WordPress [mailto:wordpress@turbostaff.co.nz]'. 

How and where can I change this to 'Turbo Staff Website [mailto:website@turbostaff.co.nz]' please? 

The client's recruiters are missing these emails as it looks like spam.

Thanks

**Comment by rtemery** [comment]
This is WordPress Core behavior (not a WP Job Manger issue). You'll need a 'Send From' plugin for this.

**Comment by kraftbj** [comment]
Alternatively, you can use the `wp_mail_from` filter as described here: https://codex.wordpress.org/Plugin_API/Filter_Reference/wp_mail_from

As @rtemery stated though, WPJM does not set a custom from at this time.
