### ISSUE TITLE
Conflict with Jetpack's Photon: Featured Image removed when editing listing from frontend

### ISSUE THREAD

**Issue by Rappadappa77** [Automattic/WP-Job-Manager#719]
Hey Guys,

I haven't been following your post since last year, but I'm the individual who told @jeherve to look into the issue, hence why he created the post, JetPack has been updated for the last couple of months including today and I still have the same issue, I'm wondering if I'm the only person in the World who has this problem. So thank you to @mikejolley @spencerfinnell @aheckler for looking into this for me and trying to solve the problem.

Since the last thread was closed, not sure if you saw my message, so I opened another message thread, is a fix possible?

Howard

**Comment by jeherve** [comment]
Closing this in favour of #576
