### ISSUE TITLE
Listing Images Uploaded with wrong extension

### ISSUE THREAD

**Issue by TAugusitne** [Automattic/WP-Job-Manager#720]
#### What I Expected To Happen

When New listings are submitted Images should upload with correct extension (.jpeg, ,png, .jpg etc.), And these images should be visible on Media manager and also get linked to respective listings.

#### What Happened Instead
Images for new listings are getting uploaded to media with random incorrect extension name ie with a  mark '?' at the end.

**Some example of image with incorrect extension:**  image-25.jpg?68a322 , image-17.jpg?68a322 , image-17.jpg?68a322, image-23.jpg?68a322, image-24.jpg?68a322

Screenshot from media manager for above example:  http://imgur.com/wf0jVxL

When Images are having such extension they don't show up on the listing gallery and featured images. Refer screenshot: http://imgur.com/NFqmOPt

#### Steps to Reproduce the Bug

1) Try to add a new Listing
2) Enter the details of listing except the 'Description' or any other mandatory field of the listing ( Leave this field blank)
3) Upload pictures logo, image etc. as normal.
4) Click Preview listing - Now at this stage the page refreshes and says 'Description' missing in Red Colour !! (Due to a mandatory field.)
5) Now Try to add the listing 'description' or complete the mandatory fields again and then click on 'Preview'
6) You can then see on the preview page no images shows up !!! 
7) Click 'Submit' Listing
8) Login to site admin area and on 'Media' section you can see that the images have uploaded with wrong extension name and because of this listing will not show any images.

**Comment by chaselivingston** [comment]
@TAugusitne Is this only happening with the Listing Gallery feature of Listify?

**Comment by TAugusitne** [comment]
hi @chaselivingston 

Yes, It seems to be only happening with Listing Gallery Feature.

By the way it looks like W3 Cache with Amazon Cloud Front was creating this mess, I had disabled both and now there is no issues while the images are uploaded.

Thanks

**Comment by chaselivingston** [comment]
Thanks @TAugusitne. I'll close this for now, please get in touch if you need anything else!
