### ISSUE TITLE
Job Data fields have overlapping text 

### ISSUE THREAD

**Issue by no12design** [Automattic/WP-Job-Manager#722]
![screen shot 2016-07-13 at 21 32 31](https://cloud.githubusercontent.com/assets/4144735/16818807/859fc052-4941-11e6-9930-3cdfc369717c.png)

**Comment by chaselivingston** [comment]
@no12design Could you give us some more information on this? I'm not able to reproduce currently.

**Comment by tripflex** [comment]
This is probably due to out-dated addon plugin being installed on their site ... i've seen it numerous times, and the culprit was always some out-dated plugin CSS, not a CSS bug related to core.
