### ISSUE TITLE
Limit the number of featured jobs

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#723]
Add an option to limit the number of featured jobs as an argument for the [jobs] shortcode. Currently, you can only limit the number of featured jobs in a featured jobs widget.

**Comment by jom** [comment]
@davoraltman I don't see an easy way to treat, for example, the most recent 5 featured jobs as featured jobs and the rest as regular jobs. This would require us to run multiple queries for every page load and complicate the pagination for `[jobs]`. We would also need to figure out a way to display extra featured listings as non-featured when they did show up in the listing results.

Is this a frequently requested feature? I'll keep it open for a future release if we think it is necessary.

**Comment by davoraltman** [comment]
Thanks @jom ! I've encountered this request once or twice maybe. It would be a nice addition so I wouldn't discard it yet! :)

**Comment by jom** [comment]
Would the ones that got bumped from the top be shown as regular listings? We'd probably need to schedule this on a major release as it may involve updating templates for this.

**Comment by davoraltman** [comment]
Good point. I am not sure whether the bumped ones should be hidden or displayed as regular listings. We'll iterate on this.

**Comment by jom** [comment]
Closing, but will use to inform design of block (Replacing the shortcode) in #1287.
