### ISSUE TITLE
Datepicker error - date will be overridden with automatic (Frontend -/ Backend)

### ISSUE THREAD

**Issue by Cryptoom** [Automattic/WP-Job-Manager#724]
The Datpicker for Job-Submission has a small bug, when you create a Job and set the time for closing date via datepicker and go to Preview all looks good (show the date i choose), when i now go back to edit this job he set automatic the Date from today (override my choose automatic).

Same in the Backend, when you go to edit a Job, automatic at the Loading of the Job-Post to edit he show in the closing date the date from today. When i set this to a Date i wish and update the post he shows next time of loading in frontend the correct value but in backend everytime the today-date.

**Comment by chaselivingston** [comment]
@Cryptoom I'm not seeing the option to set an expiration date on the front-end, is your theme or other add-on adding that perhaps?

**Comment by Cryptoom** [comment]
Can be closed it is from the addon wp-jobmanager-application-deadline - im sorry!
