### ISSUE TITLE
Resume, I set only 1 as Limit Number of Post. But Not working.

### ISSUE THREAD

**Issue by noister** [Automattic/WP-Job-Manager#725]
#### What I Expected To Happen

Candidate suppose to upload or add only 1 resume per account.  
#### What Happened Instead

I can still create one or more resume after I set 1 under - Listing Limit – Limit the number of resumes users are allowed to post.

**Comment by chaselivingston** [comment]
@noister Could you provide steps to reproduce this?

**Comment by jom** [comment]
No author reply. Closing for now.
