### ISSUE TITLE
Admin Is Not Responsvie

### ISSUE THREAD

**Issue by turtlepod** [Automattic/WP-Job-Manager#726]
#### What I Expected To Happen

It should be responsive. WP admin is responsive since a long time ago. It is expected.
#### What Happened Instead

Admin is not responsive:
- Admin Column [screenshot](https://dl.dropboxusercontent.com/u/32880842/etc5/wp-job-man-admin-col.png)
- Meta Box [screenshot](https://dl.dropboxusercontent.com/u/32880842/etc5/wp-job-man-admin-meta-box.png)
#### Steps to Reproduce the Bug

Visit on mobile or resize your browser.

**Comment by davoraltman** [comment]
This was added in 1.26. Closing.
