### ISSUE TITLE
WP job manager addons conflict ( Broadbean and Geo Location )

### ISSUE THREAD

**Issue by Umeed** [Automattic/WP-Job-Manager#730]
Hi,
I am trying to solve an issue of WP job manager for my client. He is using Broadbean addon to import the jobs and geolocation to filter search by location.

The issue is when the jobs get imported from broadbean the search by location can't list them. Unless admin resave the job item from Wordpress dashboard. 

Is it possible to make the job available to search by location at the time Broadbean imports them?

I checked out the database table ( places_locator ) and it seems like the jobs which are importing by Broadbean don't put any data in (street number, street name, street and zip) fields.

I went through Boardbean core files and the file which this plugin is using to save the data is ( plugins/wp-job-manager/includes/admin/class-wp-job-manager-writepanels.php)

is it a wp job manage bug? or something else. Please advice where to check for the issue.

Thanks

**Comment by chaselivingston** [comment]
@Umeed Are you using http://wpbroadbean.com/wp-job-manager-broadbean-add-on/

Have you tried contacting them at all?

**Comment by jom** [comment]
No author reply. Closing for now.
