### ISSUE TITLE
Allow users to create a new category when they submit a job form

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#733]
Users can only choose from a list of already created categories when they are submitting a listing. We can add an option inside Job Listings -> Settings -> Job Listings which would allow users to create new categories on the [submit_job_form] page.
#2766020

**Comment by jom** [comment]
I'm going to close this for now, unless we get more requests for it. We would probably need to at least restrict this to logged in users only.

**Comment by jenhooks** [comment]
Requested here 1439851-zen.
