### ISSUE TITLE
Integrate with Jobs2Careers

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#734]
Add [Jobs2Careers](http://jobs2careers.com/) jobs in a form of an add-on or addition to the core. https://github.com/JobBrander/jobs-jobs2careers

Mentioned in #2769979

**Comment by jom** [comment]
Closing this for now as there hasn't been much interest, but if others request this we can consider it.

Future ref: https://github.com/jobapis/jobs-jobs2careers
