### ISSUE TITLE
Re-assigning active job listings - Listing count not updating

### ISSUE THREAD

**Issue by rtemery** [Automattic/WP-Job-Manager#737]
When re-assigning **active** job listings to a new user ID, the listing count is not updating.  For inactive jobs this wouldn't be a problem, but for active jobs this creates a business logic issue.

**Comment by chaselivingston** [comment]
@rtemery Thanks for the report! Could you provide more detailed steps to reproduce?

**Comment by rtemery** [comment]
Sure thing.
**To Reproduce:**
Job Listings > All Jobs > Edit > see 'Job Data' section > see 'Posted By' author> Change existing author to any new author (with a job package).

**What should happen:**
The NEW author's job count should reflect this as a NEW job listing, thus lower their listing package by (1) count.

**Comment by jom** [comment]
I can reproduce. @kraftbj @chaselivingston Thoughts on this? It feels a bit more like an enhancement to the wp-job-manager-wc-paid-listings plugin to add the ability to switch the package a job listing is associated with.

**Comment by davoraltman** [comment]
Yes, this should be a WCPL enhancement.

**Comment by jom** [comment]
Moved to WCPL
