### ISSUE TITLE
IS there any way to approve company first then employer can add company info 

### ISSUE THREAD

**Issue by Neetesh1** [Automattic/WP-Job-Manager#745]
#### What I Expected To Happen
I want to seprate the job and company form in to two diffrect form. right now it is comingin single from.
#### What Happened Instead
Is there any to separate out Job form from company form. 
If any Employer added any company then that company needs to verify firest then he can add the job information.

**Comment by aheckler** [comment]
@Neetesh1 In short, no. WP Job Manager doesn't create a post type for companies, so there's no way to do what you're referring to without some serious custom code.

Sorry I can't be of more help here! :(
