### ISSUE TITLE
Filter the job types filter args

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#746]
Would be good to filter the args here to allow people to change the sort order etc.
https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L247

**Comment by queinidom** [comment]
+1

**Comment by jom** [comment]
I'm not sure what that link was originally pointing to. For `get_job_listings()` we can filter the job types using the `job_types` argument.
