### ISSUE TITLE
links changed for job_listing_type taxonomy?

### ISSUE THREAD

**Issue by v3nt** [Automattic/WP-Job-Manager#749]
#### What I Expected To Happen

we had a link that used to select jobs by job_listing_type but now it does 't work.
#### What Happened Instead

forwards to root / 
#### Steps to Reproduce the Bug

this might be due to custom URLS which have worked for over 2 years and not been touched. Wondering if an update has changed something. 

How do we create a list of the job_listing_type with links to their default pages?

**Comment by diptisombanshi** [comment]
I have the same issue.

**Comment by spencerfinnell** [comment]
Your theme likely no longer declares proper support for taxonomy archive templates:

Related https://github.com/Automattic/WP-Job-Manager/issues/760
