### ISSUE TITLE
display sub_category

### ISSUE THREAD

**Issue by Poniyo** [Automattic/WP-Job-Manager#752]
Hello
How the display sub category each category in listify?
Or any other method
Thankful

**Comment by aheckler** [comment]
Hi there! For support questions, please see our forum here:

https://wordpress.org/support/plugin/wp-job-manager

Or, if you need help with a paid add-on, please log into our website and use this form:

https://wpjobmanager.com/support/

GitHub issues are intended for software bugs, enhancement ideas, and so on, not regular support requests.

Thanks! :)
