### ISSUE TITLE
Add body class on single job listings for filled positions

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#755]
When a position is filled, on the jobs page it has a body class of 'job-position-filled' so that it can be styled differently, but there is no such class on the single job listing.

As a temporary workaround, you can add the following to functions.php:

```
add_filter( 'body_class', 'dj_add_position_filled_class' );

function dj_add_position_filled_class( $classes ) {
    global $post;
    if ( $post->post_type !== 'job_listing' ) {
        return $classes;
    }
    if ( is_position_filled( $post ) ) {
        $classes[] = 'job_position_filled';
    }
    return $classes;
}
```

**Comment by davoraltman** [comment]
@danjjohnson Maybe add this to https://wpjobmanager.com/customization-snippets/ ?

**Comment by danjjohnson** [comment]
@davoraltman probably best to just get it in core. Should be an easy one for the next update.
