### ISSUE TITLE
Open Jobs not displaying when you go to the careers page

### ISSUE THREAD

**Issue by goodspire** [Automattic/WP-Job-Manager#758]
When you go to my jobs page - [](http://goodspire.com/careers/ )- then the open jobs do not display. This is occurring in all browsers. The only way to get the jobs to display is to actually refresh the page, but site visitors won't know to do that.

Please let me know how I can correct this issue.

**Comment by aheckler** [comment]
Hi there! For support questions, please see our forum here:

https://wordpress.org/support/plugin/wp-job-manager

Or, if you need help with a paid add-on, please log into our website and use this form:

https://wpjobmanager.com/support/

GitHub issues are intended for software bugs, enhancement ideas, and so on, not regular support requests.

Thanks! :)
