### ISSUE TITLE
Job listing is not visible in employee account

### ISSUE THREAD

**Issue by suyash87** [Automattic/WP-Job-Manager#761]
I used this plugin and added to http://icloudage.com/marketplace/

I can see the job listing in admin page, but when I login as normal employee account and post project, then i can not see option like my projects to see what projects I have posted, is there a way to show my specific job listing in personnel account?

**Comment by aheckler** [comment]
Use the `[job_dashboard]` shortcode as shown here:

https://wpjobmanager.com/document/shortcode-reference/#section-5

In the future, for support questions, please see our forum here:

https://wordpress.org/support/plugin/wp-job-manager

Or, if you need help with a paid add-on, please log into our website and use this form:

https://wpjobmanager.com/support/

GitHub issues are intended for software bugs, enhancement ideas, and so on, not regular support requests.

Thanks! :)
