### ISSUE TITLE
Cannot Open Job Application Attachment Links - 404 Error

### ISSUE THREAD

**Issue by sujisathish** [Automattic/WP-Job-Manager#763]
I have installed job application add-on for wp job manager. 
#### What I Expected To Happen

When i click the submitted application it should open in new window with the application loaded.

#### What Happened Instead

It gives 404 page not found

**Comment by aheckler** [comment]
Hi there! For support questions, please see our forum here:

https://wordpress.org/support/plugin/wp-job-manager

Or, if you need help with a paid add-on, please log into our website and use this form:

https://wpjobmanager.com/support/

GitHub issues are intended for software bugs, enhancement ideas, and so on, not regular support requests.

Thanks! :)
