### ISSUE TITLE
Hook to make listings get featured.

### ISSUE THREAD

**Issue by NitinPrakash** [Automattic/WP-Job-Manager#765]
Is there any hook to make Listings Featured on adding.

I want to add in my theme that few User Types when they add a JOB Listing it gets featured automatically.
Is it possible.

Moreover it will be great if Listings can be grouped by featured such that featured listings are grouped in random order.. All Featured first then other listings..

I hope it will be possible..

**Comment by aheckler** [comment]
Hi there! For support questions, please see our forum here:

https://wordpress.org/support/plugin/wp-job-manager

Or, if you need help with a paid add-on, please log into our website and use this form:

https://wpjobmanager.com/support/

GitHub issues are intended for software bugs, enhancement ideas, and so on, not regular support requests.

Thanks! :)
