### ISSUE TITLE
Date Format Options

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#767]
Allow more options for the date format instead of the default yy-mm-dd.

**Comment by aheckler** [comment]
@davoraltman Where are you seeing that date format? Not sure what you're referring to yet.

**Comment by davoraltman** [comment]
@aheckler We only allow one date format in https://github.com/Automattic/WP-Job-Manager/blob/bc9715e01da948ad755d40e4cd0ead41bd367301/includes/admin/class-wp-job-manager-admin.php#L49 and users are forced to use it. We can make a new setting which can allow users to choose their date format.

**Comment by eppul** [comment]
In Finland we use time format dd.mm.yyyy so it would be d.m.Y

**Comment by jom** [comment]
I propose we just use the WordPress date option. I'll work on a PR.
