### ISSUE TITLE
Malformed tag fouls job submission form

### ISSUE THREAD

**Issue by WhatcomMktg** [Automattic/WP-Job-Manager#772]
When a not logged-in user views a page containing the [submit_job_form] shortcode, the  "Your email" input field is prepopulated with

     <span id=

and outside and below that input field appears

     " value="" /> "

The element as seen in the page's source code is as follows

     <input name="create_account_email" class="input-text" id="account_email" type="email" placeholder="<span id=" eeb-365498"="">

Potentially relevant settings: 
1) Submitting jobs requires an account, 
2) account creation is enabled and 
3) usernames are automatically generated from the email address

See it in action at https://www.discoverferndale.com/jobs/submit-a-job-posting/

**SCREENCAP**
![job posting frontend malformed tag](https://cloud.githubusercontent.com/assets/3938156/19015475/d25b3e56-87b9-11e6-8a58-0c5dc1df5c83.jpg)

-------------------------------
**SOURCE**
![inspecting malformed segment job posting frontend](https://cloud.githubusercontent.com/assets/3938156/19015476/d25c54e4-87b9-11e6-9fac-4ab90bf8bb88.jpg)

**Comment by tripflex** [comment]
This isn't something due to core, but due to either another plugin that is filtering the `esc_attr_e` core function, or a change you (or a theme) have made to the `account-signin.php` file.  Did you create a template override for that file?

You can see in the default template there isn't anything that would cause this:
https://github.com/Automattic/WP-Job-Manager/blob/master/templates/account-signin.php#L49

**Comment by WhatcomMktg** [comment]
Thanks. I'm not smart enough to have created an overriding template. Ah, but I did install a plugin to prettify login/registration pages. I'll look there.

Thanks again.

**Comment by WhatcomMktg** [comment]
My fix was to remove the code that was prepopulating the field. Deemed it extraneous since it didn't really add to the user experience.

Thanks for the help.

**Comment by tripflex** [comment]
No problem, glad you got it figured out 👍
