### ISSUE TITLE
Job Application from header issue

### ISSUE THREAD

**Issue by sanjeewaweltz** [Automattic/WP-Job-Manager#773]
Hi,

i have issue with "Apply for job" using job application plugin , the plugin log file mentioned "**Fix - Use noreply address for 'from' to improve deliverability**." on version 2.2.3

the issue still there. please send code to fix this issue.

**Comment by aheckler** [comment]
Hi there! For support questions, please see our forum here:

https://wordpress.org/support/plugin/wp-job-manager

Or, if you need help with a paid add-on, please log into our website and use this form:

https://wpjobmanager.com/support/

GitHub issues are intended for software bugs, enhancement ideas, and so on, not regular support requests.

Thanks! :)
