### ISSUE TITLE
Bug in Resume Manager (incorrect action name)

### ISSUE THREAD

**Issue by shasha79** [Automattic/WP-Job-Manager#774]
#### What I Expected To Happen
do_action( 'before_get_resumes', $query_args, $args );

#### What Happened Instead
do_action( 'before_get_job_listings', $query_args, $args );

#### Steps to Reproduce the Bug
wp-job-manager-resumes/includes/wp-resume-manager-functions.php, line 106

**Comment by aheckler** [comment]
@shasha79 Thanks! I've filed this as an issue against our private repo for Resume Manager. We'll track it there. :)
