### ISSUE TITLE
Search Job Titles Only (Not Descriptions, etc)

### ISSUE THREAD

**Issue by edbeecroft** [Automattic/WP-Job-Manager#783]
It would be very useful to be able to **only** search job titles. I thought I'd seen something on this in the past, but can't find anything now we'd like to implement it.

We have a jobs board that focuses on Technical/Developer roles, now with over 335 jobs. The issue is that when an Java Developer wants to search for a role, because of the relaxed nature of the search function, they'll also see many irrelevant roles - for example Android Developer roles, and even an IT Support role that mentions "Java" as a "Bonus Point".

Having a relaxed search is fine when you only have a relatively small number of jobs, or perhaps covering very different industries without any meaningful overlap - but it's actually quite frustrating as a user (or so we've been told on multiple occasions!).

Changing some code would be fine, but an option in the settings would be even better!

Thanks!

**Comment by spencerfinnell** [comment]
You could remove the current keyword search filter via:

```php
remove_filter( 'posts_clauses', 'get_job_listings_keyword_search' );
```

And use similar approach to add your own that only searches titles.

https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L181

Can be added via https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L142
