### ISSUE TITLE
Submit Job Form issue - Not saving correctly

### ISSUE THREAD

**Issue by ColeAD** [Automattic/WP-Job-Manager#784]
#### What I Expected To Happen

When using the submit job form, the information saves correctly. Viewing the posted job as an applicant, I cannot apply for the job. There should be the button to allow me to apply but it's missing!
#### What Happened Instead

To resolve this issue, I have to go into the WP Dashboard, got to the job, and update the listing through the admin. I don't need to change anything on the job post, just click update. This then allows the Apply button to show up on the listing
#### Steps to Reproduce the Bug

If you are going to allow registered users to post jobs without the need for administrator approval, make sure the information is saved correctly to avoid this extra step. It's frustrating to have to ask an administrator to approve a post they have submitted through the form.

With the features you have, there should be no need for them to go back into the WP Dashboard. This needs to be fixed to ensure the process of saving a job post is complete from the from end, without the need to go make into the Dashboard.

**Comment by tripflex** [comment]
You haven't by chance disabled the `application` field from the frontend have you?

**Comment by tripflex** [comment]
Closing due to no response
