### ISSUE TITLE
addon "application" application form will not be displayed

### ISSUE THREAD

**Issue by melanie13** [Automattic/WP-Job-Manager#790]
I inslaller the pluging but the application form does not appear on my website

**Comment by tripflex** [comment]
Make sure you have enabled Email/URL application method in WP Job Manager settings.  Goto the Applications settings, enable Use form for email based applications, and Use form for URL based applications.

The `application` field on the listing MUST have a value in order for the Apply Now button to show up.  If your listing does not have a value in that field, nothing will show.

**Comment by melanie13** [comment]
yes, i check  : Use form for email based applications, and Use form for URL based applications.
how to add value? Is there a tutorial thank you

**Comment by tripflex** [comment]
The `application` value is set whenever the user submits a listing, or when you edit it in the admin, the default label is "Application Email or URL":

![](https://smyl.es/img/Screenshot_2016-11-02_08-23-20_PM.png)
