### ISSUE TITLE
Geocoding transform the address in two languages

### ISSUE THREAD

**Issue by raphael1982** [Automattic/WP-Job-Manager#796]
#### What I Expected To Happen

I expect to have only one language in the geolocalization into the single job post editor, as the site is based in italy I expect that addesses are generated in italian after the geocoding, all entries are bulk  imported, with only the name of the town, then the plugin generates the rest of the address by geocoding it. 

#### What Happened Instead

Some addresses are generated in english (the default lang of the plugin geocoding function) and some in italian. for example

EN: passirano, province of Brescia, Italy, Lombardy
IT: passirano BS, Italy, Lombardia 

If you take a look at the map, by specifing into the search field: Brescia (which is a province), the map shows only the english geocoded entries, the ones with: Province of Brescia intead of BS (which is the italian way to write the province in the address)

#### Steps to Reproduce the Bug

Go onto www.casaideale.green

run a seach query for Brescia, see the results

and compare to

running a search based on the region (second field of the search page) select Lombardy (which is the region containing the province of Brescia) and zoom on the province of Brescia (eastern side of Lombardy between lake Iseo and lake Garda) 

you will see that the first search query (Brescia) does not include all entries

and the second (Lombardy) contains other entries for the same area

the difference is that the ones appering in the search query Brescia have the address generated in english and the ones appering by selecting Lombardy (which is a WP listing category manually added to the job post) have noth the ones with the address generated in italian and in english.

![schermata 2016-11-02 alle 15 53 23](https://cloud.githubusercontent.com/assets/11426072/19935184/6ebee252-a119-11e6-927e-77bde0083cb5.jpg)
![schermata 2016-11-02 alle 16 01 03](https://cloud.githubusercontent.com/assets/11426072/19935183/6ebdf52c-a119-11e6-91fd-f05347634c46.jpg)

![schermata 2016-11-02 alle 15 56 08](https://cloud.githubusercontent.com/assets/11426072/19935192/75d9917c-a119-11e6-9fb4-11071ace085f.jpg)
![schermata 2016-11-02 alle 15 56 16](https://cloud.githubusercontent.com/assets/11426072/19935193/7603eb7a-a119-11e6-85da-ccb5e25f7c7f.jpg)
 
I've seen similar issue reported in the past

https://github.com/Automattic/WP-Job-Manager/issues/754
https://github.com/Automattic/WP-Job-Manager/issues/498#event-365226610

**Comment by spencerfinnell** [comment]
Sorting by Region does not interact with geolocation data that is generated, and is not related to the core WP Job Manager plugin. The "Regions" dropdown acts like categories would and does not consult the geographic information.

If your site's language is set to Italian and you use the Listify theme your results will be returned in Italian.

https://maps.googleapis.com/maps/api/geocode/json?address=passirano%20BS,%20Italy,%20Lombardia&language=it

See the `language` argument here: https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding

WP Job Manager will record what Google returns in the URL above; it can't gather any other information beyond that.
