### ISSUE TITLE
Define a Primary Column in CPT List Table

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#798]
#### What I Expected To Happen

Responsive list table in "Job Listings"

#### What Happened Instead

Jumbled mess! https://cloudup.com/cBNKItlLgQq

#### Steps to Reproduce the Bug

Visit "Job Listings" in the WordPress dashboard on a mobile device.

https://make.wordpress.org/core/2015/08/08/list-table-changes-in-4-3/

**Comment by jom** [comment]
Fixed in #906
