### ISSUE TITLE
WC Paid Listings "My Job Packages" not show in My Account page

### ISSUE THREAD

**Issue by skmohammadi** [Automattic/WP-Job-Manager#800]
Hi. I have installed version 2.71 of WC Paid Listings on Wordpress 4.6 and It seems "My Job Packages" template not show in My Account page. Additionally, "My Job Packages" endpoints not shown in WooCommerce Settings.

**Comment by aheckler** [comment]
Hi there! For support questions, please see our forum here:

https://wordpress.org/support/plugin/wp-job-manager

Or, if you need help with a paid add-on, please log into our website and use this form:

https://wpjobmanager.com/support/

GitHub issues are intended for software bugs, enhancement ideas, and so on, not regular support requests.

Thanks! :)
