### ISSUE TITLE
Feature Request: Add Classification and Sub-Classification to Post A Job form

### ISSUE THREAD

**Issue by Olivia101** [Automattic/WP-Job-Manager#801]
When adding a new job it would be useful to select a Classification and Sub-Classification which can then also allow for improved job results filters.

An example of job Classification and Sub-Classification would be:
**Accounting**
--- Accounts Officers/Clerks
--- Accounts Payable
**Engineering**
--- Chemical Engineering
--- Industrial Engineering

**Comment by edd677** [comment]
This would be amazing!

**Comment by aheckler** [comment]
This is exactly what job categories are for. :) Please make sure you have it enabled under Job Listings > Settings:

![screen shot 2016-11-16 at 10 58 01 am](https://cloud.githubusercontent.com/assets/5512652/20354275/9b838626-abeb-11e6-9ac9-3ca1a2cee5df.png)

Site admins can then create and manage categories under Job Listings > Job Categories, including making sub-categories as you explained.

Thanks!
