### ISSUE TITLE
Single resume not showing candidate picture, share resume, contact and bookmarks button

### ISSUE THREAD

**Issue by ajaygolu94** [Automattic/WP-Job-Manager#803]
Hello, 

We have purchased jobify theme and also core bundle of wp job manager. When we set up with demo content, it's not showing the  candidate picture, share resume, contact and bookmarks button in the single resumes. 
We have enabled the share post/job/resume option from jetpack and share job is working but in resume it's not displaying. Also I contacted to support but they are not responding to mail. I sent them two mail still no answer. 
Help me to solve this issue.

Website is http://jobportal.simtrader.ca/

Thanks

**Comment by spencerfinnell** [comment]
Astoundify will respond to your ticket as soon as possible. Ticket responses are Monday-Friday. 

Ensure you have enabled sharing output on the "Resume" post type in "Settings > Sharing".
