### ISSUE TITLE
Display Number of Outbound Clicks for Jobs Using URL Application Method

### ISSUE THREAD

**Issue by edd677** [Automattic/WP-Job-Manager#804]
**Feature Request:**

For jobs posted with the URL application method, the "Applications" column on the employer dashboard is obselete, and possibly even misleading. An awesome use of this column for URL listings would be to display the number of times candidates hit the "Apply" button on those listings. The column title can just be "Applications/Outbound Clicks".

The current setup means there is almost no way for an employer listing jobs with the URL method to understand the value of our job boards. Coupled with the fact employers also do not receive application emails for these listings, this can make keeping those clients extremely difficult. I understand there is a stats plugin, but 1) this doesn't change the fact the column is obselete and looks bad, and 2) from discussions with employers, page view data is insignificant in comparison.

Thanks team! 👌

**Comment by spencerfinnell** [comment]
I've added this feature request to the internal Applications repository. Thanks for the suggestion.
