### ISSUE TITLE
BUG: Listing Duration (Capturing incorrect date)

### ISSUE THREAD

**Issue by XomaL** [Automattic/WP-Job-Manager#805]
#### What I Expected To Happen
The Job Listing settings for Listing Duration allow to set the no. of days e.g. 45 days when the listings should expire after being published. The calculations on date are incorrect. An expiry date for each listing is being captured but it is not reflective of the no. of days input e.g. 45 days. 

Kindly assist how this can be resolved. Thank you.

**Comment by donnchawp** [comment]
The expiry on my test server is set to 30 days, and on the new job editor the expiry date is the 14th of December, 30 days from now, but if I use the front end form the expiry date isn't set.

**Comment by spencerfinnell** [comment]
Closing for https://github.com/Automattic/WP-Job-Manager/issues/869
