### ISSUE TITLE
Strings added in the last update not included in the POT file

### ISSUE THREAD

**Issue by raduconst** [Automattic/WP-Job-Manager#806]
After the last update of the plugin (1.25.2) I could see that a little change was made inside the listings page (see #647)

What I Expected To Happen
I expected to have this new strings added inside the POT file.

What Happened Instead
The two strings (the one for singular and the one for plural) cannot be found inside the POT file so I can translate them. 

Steps to Reproduce the Bug
Just open the existing POT file and look for _Search completed. Found %d matching record._ . This string cannot be found.

**Comment by donnchawp** [comment]
Good catch. Part of our release process failed and didn't regenerate the pot file, but we'll have it fixed for the next release.
