### ISSUE TITLE
Candidate should not be able to post a job listing

### ISSUE THREAD

**Issue by hellocourage** [Automattic/WP-Job-Manager#809]
#### What I Expected To Happen
A candidate can submit resume, but cannot post a job.
An employer can post a job listing, but cannot submit resume. 

#### What Happened Instead
Candidate can submit resume and post a job, and vice versa for employer. This shouldnt be the case. If a candidate is finding a job, he is obviously doesnt have a job position to post. Likewise, an business owner who is posting a job, is not finding a job to post his resume. 

#### Steps to Reproduce the Bug
Just login either as employer or candidate, try to do both submit resume and job listing.

**Comment by volodymyrpekh** [comment]
@hellocourage This is exactly what I was planing to report. Thanks! These are two different types of users with different purposes and different expectations.

**Comment by hellocourage** [comment]
@volodymyrpekh  It looks like we are being ignored here. No one reply. :(

**Comment by tripflex** [comment]
Just because someone doesn't respond within a couple days doesn't mean you're being ignored.

> Likewise, an business owner who is posting a job, is not finding a job to post his resume.

An employer could be posting listings as well as candidate resumes, especially if they are managing employees for things like temporary positions, and have their own positions to fill.  So no that's not always true ... especially for recruiters.

Unless you're specifically using the user role type for some custom feature on your site, I don't see why this would be an issue.

What problem or issue does this cause for you?

**Comment by hellocourage** [comment]
@tripflex  Glad that our queries are answered. :)  Well, the culture of recruitment differs in each country. I have talked to several ones especially in India, Singapore and Malaysia. They have the same workflow. That is, candidates will only post resume; Employers only post job listing. They won't be doing both. 

May I know if you can provide us an option to restrict the above, in the coming updates ? This will definitely help a lot especially, in the area of data privacy.

**Comment by hellocourage** [comment]
@tripflex  If a person needs to do both tasks (post job listing and submit resume), just sign up two accounts separately. That's the common practice that I have saw, and it is more clean cut. Eg. very popular job portals: www.jobstreet.com.sg , www.jobsdb.com.sg

**Comment by volodymyrpekh** [comment]
Hey @tripflex @hellocourage, 

I'm using listify wp theme (which also uses wpjm). I have healthcare  providers and patients which are totally different users and there's almost no chance that one will ever become both (provider and patient). 

I would like healthcare providers have slightly different registration form, profile verification and confirmation process. 

Currently, I can't even segment users who signed up but haven't filled their profiles completely.  With two different registration forms I would know who is a healthcare provider and who is a patient. That would also help me to segment those users for:
- Re-Engagement campaigns
- Post registration follow up
- Showcase/storytelling emails

I'm sure there's even more use cases for listify theme users.

P.S. I would appreciate any suggestions or advices. Maybe there are additional plugins for these cases. 

Thank you in advance!

**Comment by hellocourage** [comment]
@volodymyrpekh I totally agree with you. Though the developer has done a great job in developing a plugin for the community, and has certain belief on how an account should do both resume and job listing, the plugin should also provide an option within the plugin for the masses to allow an account to do only 1 thing. I guess its up to them if they want to move their plugin to another level of excellence.

**Comment by purethemes** [comment]
I agree with @tripflex - the roles are there and they have purely semantic meaning now. It gives more flexibility. If you need to restrict employers to job postings and candidates to resume posting, it's very easily achievable with combination of [Restrict Content ](https://wordpress.org/plugins/restrict-content/) and [Nav Menu Roles](https://wordpress.org/plugins/nav-menu-roles/)

**Comment by hellocourage** [comment]
@purethemes  Thanks for the feedback. Are you aware that restrict content cost is not cheap ?

**Comment by purethemes** [comment]
@hellocourage you should be fine with the free version, if not there are different plugins for that. https://wordpress.org/plugins/restrict-content-by-role/

**Comment by hellocourage** [comment]
@purethemes  Thanks Lukas. I try that first.

**Comment by kraftbj** [comment]
@hellocourage 
> This will definitely help a lot especially, in the area of data privacy.

What do you mean with regard to data privacy?

Right now, there are separate roles assigned depending on how the account is created, which adds flexibility when coupled with other plugins/code, etc. At this time, we're not exploring expanding role restriction within the WPJM core.

I'm going to close and mark this as wontfix for the time being. Though please do mention use cases and whatnot here. A "no" now does not mean forever.

**Comment by orchard800** [comment]
@kraftbj 

> Right now, there are separate roles assigned depending on how the account is created...

How are separate roles current assigned depending on how the account is created? I thought there was the choice of only one role to give anyone signing up.

I'm also using Listify and would love to know how to sign users up with different roles.

Thanks,
Dave
