### ISSUE TITLE
[Suggested Feature] - Share job advertisement between employers

### ISSUE THREAD

**Issue by mr3k** [Automattic/WP-Job-Manager#812]
Hi guys,

Thanks for a great plugin. We are using it and have several improvements and future features. 
To start with, we really see a potential use for sharing an job advertisement between several employers. When creating a job advertisement, the employer should be able to invite another user to help with the recruitment. There's pretty unique that there's only one person that is handling the recruitment process and sharing an account is not the best option. 

Is this of your interest?

**Comment by spencerfinnell** [comment]
It's a nice idea but I haven't seen any requests for this over the years. A custom solution would be possible but does not get requested enough to be added to the core plugin.
