### ISSUE TITLE
enhancing job applications form editor

### ISSUE THREAD

**Issue by khaledsawwaf** [Automattic/WP-Job-Manager#814]
Hello,
i've a pro addon installed "job applications", but i have 2 important options need to be there.

#### What I Expected To Happen
1- there's no field with date structure, so that if the user select that field, a date box will show instead of writing text.
2- if i have too many fields with different group title, how can i separate the fields of the form into groups?
for example: http://www.syriansoft.com/jobs/ApplicationForm.php

**Comment by spencerfinnell** [comment]
Thank you for your requests -- I have logged these in the Applications repository.
