### ISSUE TITLE
Application Details: Upon submission, leave details open and scroll down.

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#816]
When using third-party form solutions, submitting the form will refresh the page, but the applications detail area will be closed. If the third-party form may have an error that is hidden within the application detail.

We should return the user to the details area open to make the errors apparent.

2891325-t

**Comment by jom** [comment]
Read ticket... need to make the hiding here either be stateful or not happen after a POST request.

https://github.com/Automattic/WP-Job-Manager/tree/master/assets/js/job-application.js
