### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by steve19801980** [Automattic/WP-Job-Manager#820]
Is it possible to have a search box with a shortcode insert which only shows the keyword and location boxes and not the categories which when entered links through to the jobs page?

Similar to http://www.digitalgurus.co.uk/

**Comment by steve19801980** [comment]
No update??

**Comment by kraftbj** [comment]
https://wpjobmanager.com/document/shortcode-reference/ with the `show_categories` option is what I think you're asking about.

For other support requests, please use https://wpjobmanager.com/support/ . Thanks!
