### ISSUE TITLE
Page Error on User Deletion

### ISSUE THREAD

**Issue by stephenbair** [Automattic/WP-Job-Manager#821]
#### What I Expected To Happen
User to be deleted without error.

#### What Happened Instead
After clicking 'Confirm Deletion' I received an error to which I had to change the URL path back to the base domain. The user was deleted, but the error appeared. 

Warning: Missing argument 2 for job_manager_add_post_types() in /home/content/80/13050580/html/wp-content/plugins/wp-job-manager/wp-job-manager.php on line 174

Warning: Cannot modify header information - headers already sent by (output started at /home/content/80/13050580/html/wp-content/plugins/wp-job-manager/wp-job-manager.php:174) in /home/content/80/13050580/html/wp-includes/pluggable.php on line 1174

#### Steps to Reproduce the Bug
Go to Users, delete an existing user, confirm deletion, error appears, page does not load.

**Comment by jom** [comment]
Fixed in #875
