### ISSUE TITLE
Update arguments in calls to get_terms()

### ISSUE THREAD

**Issue by aheckler** [Automattic/WP-Job-Manager#825]
We have a handful of calls to `get_terms()` using the deprecated style:

```php
get_terms( 'some_taxonomy' , $args );
```

We should update them to the new way:

```php
$args = array (
    'taxonomy' => 'some_taxonomy',
    'more' => 'args',
    ...
);

get_terms( $args );
```

https://developer.wordpress.org/reference/functions/get_terms/

**Comment by jom** [comment]
Bumped this for now until it starts throwing actual deprecation warnings in WP core _or_ until we bump WPJM's minimum core requirement to 4.5. Right now core, although the naming shows deprecated, just treats it as an alternative calling for `wp_term()`. I imagine they will legitimately deprecate it one day and call `_deprecated_argument()`.

Right now it appears in two files. One is a template file (`templates/job-filters.php`) and the other is for the CPT filter (includes/admin/class-wp-job-manager-cpt.php). I started doing a `$wp_version` check in the CPT file, but doing it in the template file is a bit clunky. 

If we want to add support for this _before_ bumping minimum WP version to 4.5, I suggest creating another global wrapper function and do the WP version check in there.

**Comment by spencerfinnell** [comment]
Mentioned in the PR but I'll vote to bumping minimum version vs adding extra code. Being on WP.org I think the minimum requirements are stated clear enough and 4.5+ seems reasonable.

**Comment by jom** [comment]
Our bump to a minimum of WordPress 4.7 in the 1.31.0 release will allow us to incorporate this change now.
