### ISSUE TITLE
Delete wp-job-manager-submitting-job-id cookie

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#826]
Upon logging out of the WordPress user (and perhaps while logging in), we should clear the `wp-job-manager-submitting-job-id` cookie. If I'm reading things right, we could load a previous job if, on the same computer, someone logs in as another user and tries to submit a entry.

https://github.com/Automattic/WP-Job-Manager/blob/master/includes/forms/class-wp-job-manager-form-submit-job.php#L92

**Comment by spencerfinnell** [comment]
Related #835
