### ISSUE TITLE
Suggestion: User Search in Admin Job Posting form

### ISSUE THREAD

**Issue by arfoodie** [Automattic/WP-Job-Manager#827]
I post most of the job listings for my clients, and I am constantly opening a separate window to search for their user numbers so I can input them under "Posted by," so their jobs will appear in their job dashboard. Is there a way to create a search function here, like is done in WooCommerce and elsewhere? (See attached image) 
<img width="811" alt="user search" src="https://cloud.githubusercontent.com/assets/7267872/20956051/3898e736-bc0d-11e6-93af-fd2a5b313932.png">

If not, consider this an official request for the next update! Much love and thanks for all you've done for my business, BTW.

-Christie
arfoodjobs.com

**Comment by tripflex** [comment]
Looks like this is going to be something added in an upcoming release via #846

**Comment by spencerfinnell** [comment]
Closing for #846
