### ISSUE TITLE
Cannot override themes/content-job_listing.php properly

### ISSUE THREAD

**Issue by ThomsCass** [Automattic/WP-Job-Manager#830]
Hi guys,

If I modify this file in the plugin itself nothing happens even if I remove it !

If I put a copy in theme/job_manager then an override is possible but really weird stuff happen.

How can I get access to the real file that display the items job in the list ?

Thanks a lot

**Comment by volodymyrpekh** [comment]
@ThomsCass Hi, please use [https://wpjobmanager.com/support/](https://wpjobmanager.com/support/) and support will help you.
