### ISSUE TITLE
Featered listings not handled properly

### ISSUE THREAD

**Issue by sv1cec** [Automattic/WP-Job-Manager#831]
We are facing a serious issue in our site, for which we would appreciate your support.

First, we are using the latest versions of WP, Listify, Polylang, FacetWP and WP Job Manager. We are using three different languages in our site (Greek, English and French).

We have discovered a serious issue with the cooperation of WP Job Manager and FacetWP. The issue is related to how WPJM handles the "Featured" checkbox and is described below:

I have three job listings, which are translations of the same listing, Initially, they are all NOT featured. Their post_ids are 2472, 2473, 2474. In the database, I can verify that the menu_order field for all three listings is set to 0. Also, the _featured meta_key for all these posts is set to 0.  

I use wp-admin to change the first listing (English, post_id 2472) to Featured. I can see in the database that the menu_order field for the English listing is set to -1 and the meta_key _featured is set to 1. (so far so good)

I then select the Greek translation of the listing (post_id 2473) and I also check the Featured checkbox for the Greek listing. In the database, I can see that the meta_key _featured for both the English and the Greek versions are now set to 1. HOWEVER, the menu_order for the English listing (post_id 2472) is set to 0, while the menu_order for the Greek listing (post_id 2473) is set to -1. In other words, for some reason, while the Greek post gets the correct value for menu_order, at the same time, the English post menu_order is changed from its correct value of -1 to 0.

If I now select the French translation (post_id 2474) and check the Featured checkbox for it, then the menu_order in my listings change for the French transalation, from 0 to -1 (as it should), but also it changes from -1 to 0, for the Greek translation. 

In other words, initially:

post_id: 2472  menu_order: 0  meta_key _featured: 0
post_id: 2473  menu_order: 0  meta_key _featured: 0
post_id: 2474  menu_order: 0  meta_key _featured: 0

After checking the Featured checkbox for 2472, things change as:

post_id: 2472  menu_order: -1  meta_key _featured: 1
post_id: 2473  menu_order: 0  meta_key _featured: 0
post_id: 2474  menu_order: 0  meta_key _featured: 0

After checking the Featured checkbox for 2473, things change as:

post_id: 2472  menu_order: 0  meta_key _featured: 1
post_id: 2473  menu_order: -1  meta_key _featured: 1
post_id: 2474  menu_order: 0  meta_key _featured: 0

After checking the Featured checkbox for 2474, things change as:

post_id: 2472  menu_order: 0  meta_key _featured: 1
post_id: 2473  menu_order: 0  meta_key _featured: 1
post_id: 2474  menu_order: -1  meta_key _featured: 1

Right now, all posts show the Featured checkbox as checked, but please note that the menu_order field is set to -1 ONLY for the last post.

If I now uncheck the Featured checkbox from one of the listings (say I uncheck it for post_id 2474), another interesting thing happens. 

The contents of the database change to:

post_id: 2472  menu_order: -1  meta_key _featured: 1
post_id: 2473  menu_order: -1  meta_key _featured: 1
post_id: 2474  menu_order: 0  meta_key _featured: 0

Which seens to indicate that the program checks for the meta_key _featured and sets the menu_order to -1 for those posts which have _featured = 1 (which makes sense). 

In other words, if I change the Featured checkbox of a listing, from checked to unchecked, the program checks for the _featured meta_key and sets the menu_order field properly, for all three listings. If I change the Featured checkbox from unchecked to checked, the program does not check for the _featured meta_key and resets the menu_order field to 0, for the other two posts.

We would appreciate your help on these issues.

**Comment by kraftbj** [comment]
Until this is a verifiable bug, it'd be better to communicate via https://wpjobmanager.com/support/ . Since this is a particular unique setup and the issue is meta not syncing between multiple posts via Polylang, I'm not sure if this is something strictly on our end or Polylang's or both.

**Comment by sv1cec** [comment]
We can not communicate via that link you provide me, since we do not have an active license of WP Job Manager. We are using WP Job Manager because it was recommended by Listify, and it’s working fine, in general, but this is a very serious issue for us. And with the weekend ahead, I can’t talk to the bean counters until Monday morning to see if we can get a WP Job Manager license.

Please provide me with a communication method, so we can troubleshoot this issue.

Thanks

-------------------
John Caradimas
sv1cec@gmail.com

**Comment by kraftbj** [comment]
To be frank, multilingual plugins are especially problematic and mostly with issues outside of our code. There won't be a quick solution and possibly no solution without our scope of support.

**Comment by sv1cec** [comment]
I can understand that, but nowhere in your pages I didn’t see a warning saying “Don’t use our plugin with Polylang” or “Unexpected results can occur". So I think you should at least investigate where the bug lies and work with other plugin manufacturers to fix it.

-------------------
John Caradimas
sv1cec@gmail.com

**Comment by kraftbj** [comment]
I've added a notice at https://wpjobmanager.com/document/using-wp-job-manager-with-multilingual-plugins/ .

The bug, from my initial look, is WPJM is making a change to a singular post, which is the typical behavior. Polylang is trying to keep multiple posts (the original and translated versions) in sync and, in that process, misses some, I think.

At this time, this is not something on our radar to investigate further.

**Comment by kraftbj** [comment]
@sv1cec -- Remind me of the ticket number you submitted to our support system. I'm happy to refund your purchase if you're near the refund window if this prohibitively impacts your site.

**Comment by sv1cec** [comment]
As far as I am concerned, it is not a refund issue. It’s an issue of having our site based on some products (listify, WPJM, Polylang) which we thought would work together and it’s now evident that they don’t. 

It is also not a question of having polylang update more than one listing, I wouldn’t care for that. I would be happy if the code updates one listing at a time, but it updates it correctly without affecting the other listings. I would be happy to take up this issue with Polylang and stop bothering you, if it is sure that it’s a Polylang issue.

While I understand you have your own priorities about fixing bugs, for me it is imperative that this issue is resolved. So I would appreciate, if you could, at least, point me to the code where the menu_order field is set (or updated) to -1 (or to 0), when I check (or uncheck) the Featured checkbox in wp-admin.

Many thanks

-------------------
John Caradimas
sv1cec@gmail.com

**Comment by kraftbj** [comment]
The default is set https://github.com/Automattic/WP-Job-Manager/blob/569d92d2711f8d655f4667c69a07c29d74477b5b/includes/forms/class-wp-job-manager-form-submit-job.php#L595

Then, based on the form fields set, they are all looped and set via https://github.com/Automattic/WP-Job-Manager/blob/569d92d2711f8d655f4667c69a07c29d74477b5b/includes/forms/class-wp-job-manager-form-submit-job.php#L618

The featured field is added to wp-admin via https://github.com/Automattic/WP-Job-Manager/blob/569d92d2711f8d655f4667c69a07c29d74477b5b/includes/admin/class-wp-job-manager-writepanels.php#L77

For featured posts, we check the menu order here https://github.com/Automattic/WP-Job-Manager/blob/0bf2658abca036bcc1c0c4fded2193ff42f6aaf7/includes/class-wp-job-manager-post-types.php#L558

which fires off https://github.com/Automattic/WP-Job-Manager/blob/0bf2658abca036bcc1c0c4fded2193ff42f6aaf7/includes/class-wp-job-manager-post-types.php#L558

I don't know where the issue lies. Frankly, it's a complicated enough setup that I don't know when we would have a time to attempt to duplicate it to determine where it is originating from.

**Comment by sv1cec** [comment]
Hi Brandon,

I think I have figured out what the problem is.

First of all, it is not a WP Job Manager issue, so apologies are in order for bothering you people.

Second, the problem arises from Polylang. There are two things that affect the program, and which created the issue I reported to you.

First, there is the issue of declaring _featured as a custom field in Polylang wpml-config.xml file. If you do declare _featured as a custom field, then Polylang gives the value of 1 to _featured, in all associated translations. However, it does not set the value of menu_order to -1, as one would expect. The field menu_order is set to -1 only for the post (job listing) you are updating.

Second, if you first set Featured in the first translated post and then try to update another translated post then the program changes menu_order from all other posts from -1 to 0. The code that does that is located in file /wp-content/plugins/polylang/modules/sync/admin-sync.php, where you need to change line 238 from :

foreach ( array( 'comment_status', 'ping_status', 'menu_order', 'post_date' ) as $property ) {

to:

foreach ( array( 'comment_status', 'ping_status', 'post_date' ) as $property ) {


With this change and provided that you have ΝΟΤ defined _featured as a custom field, the program updates each translated post individually, setting menu_order to -1 and _featured to 1, as it should. A minor inconvenience being the fact that you have to check the Featured checkbox in every translated post, and update it. 

I can live with that!

Thanks for your patience and help on this issue.

-------------------
John Caradimas
sv1cec@gmail.com
