### ISSUE TITLE
Allow jobs and taxonomys to be not managed by Polylang (&WPML?)

### ISSUE THREAD

**Issue by Xilonz** [Automattic/WP-Job-Manager#832]
#### What I Expected To Happen
When post type is not translated through polylang I would expect all posts to show on the front-end.

#### What Happened Instead
The lang parameter is/was set and thus no posts are found.

#### Steps to Reproduce the Bug
- Disable the translation of jobs in the polylang settings.
- Add some jobs

Note: I first enabled the translation of jobs and added some translated Jobs

Solution:
Add `&& pll_is_translated_post_type('job_listing');` on wp-job-manager-functions.php on line 133

Edit: This is the same issue as #754

**Comment by kraftbj** [comment]
Which line 133? https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L133 is `}`.

If you're able, a PR is really helpful to make sure we're on the same page. Thanks!

**Comment by Xilonz** [comment]
I'm sorry, i'm not so familiar with git yet.

https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L131-L133
Should be:

``if ( function_exists( 'pll_current_language' )  ) {
  if (pll_is_translated_post_type('job_listing')) {
    $query_args['lang'] = pll_current_language();
  }
}``

**Comment by EngMs** [comment]
I’m having issues with wp job language plugin and polylang plugin
My job list only (but filter & category is translated) show on two pages using default language only

Default Language: Arabic
Second Language: English

Jobs In Default Language (Arabic) : http://athwaqest.com/%D8%A7%D9%84%D8%AA%D9%88%D8%B8%D9%8A%D9%81/
Jobs In Another Language (English) :http://athwaqest.com/en/employment/

I try this solution but noyhing

**Comment by Xilonz** [comment]
I've been investigating this problem, and I noticed a few more related problems:
- URL Slugs are translated, this is not supported by Polylang (free).
- WPLM must have the same problems. There are no checks if the post_type and taxonomy translations are actually enabled.

I am interested in fixing the Polylang related problems, but I don't own WPML, and have no experience with it.

**Comment by Xilonz** [comment]
After some investigation this ( https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L131-L133 ) code should be obsolete. 
Polylang does manage the Lang arg by itself. You only need it if you want to get another language.

Does that code still need to be there?

I only now need an solution for the changing slugs -- this seems also to be a problem for WPML, since the has_archive = 'plural' is [not translatable](https://wpml.org/documentation/getting-started-guide/translating-page-slugs/).

Should the slugs not just be an option from the settings panel and be removed from the translations all together? Both translation plugins don't use gettext for slugs.

**Comment by jom** [comment]
Fixed the original issue in #969. 

@Xilonz I'm not sure if your slugs problem is related to this issue. Feel free to open a new issue if it is a needed fix.
