### ISSUE TITLE
Filled and hidden positions displayed in WordPress native search

### ISSUE THREAD

**Issue by eppul** [Automattic/WP-Job-Manager#833]
Hi,

I found a bug in the plugin. When you setup "WP Job Manager" and set "Hide filled positions" and "Hide content within expired listings" the positions are still displayed in the WordPress native search.

#### What I Expected To Happen
I expected filled and expired position to be hidden from normal WordPress search. When the setup says so. 

#### What Happened Instead
When searching I found that all of the expired and filled positions are displayed int the native search of WordPress.

#### Steps to Reproduce the Bug
1. Install Wordpress
2. Install WP Job Manager
3. Setup WP Job Manager (enable: "Hide filled positions" and "Hide content within expired listings")
4. Create 2 Jobs
5. Expire that job first one and mark the second one as filled
6. Do search with WordPress own search function using the name of the expired job or the filled job
7. Now the expired/filled position should be displayed in the search results

**Comment by eppul** [comment]
When you thing of it. This could also be a security threat and it is at least a privacy issue.

**Comment by eppul** [comment]
And do they still index in google?

**Comment by tripflex** [comment]
It may be displayed in the search results, but if you click on it to go to the listing it's going to say "This listing has expired" ... although I do agree something should probably be added to prevent them from showing up in search results

**Comment by eppul** [comment]
This is problem when you have thousands of expired job listings on your blog page and people are trying to search for blog articled and no they only get expired job listings from the WordPress search function.

**Comment by jom** [comment]
Enhancement. 

Tasks for when "Hide filled positions" and "Hide content within expired listings" are enabled: 
- [] Filter out expired posts in core's search
- [] Possible: Filter out expired posts from sitemap creation in Jetpack?
