### ISSUE TITLE
application_form_validate_fields filter doesn't exist in applications add-on

### ISSUE THREAD

**Issue by tedmasterweb** [Automattic/WP-Job-Manager#834]
The filter for applications mentioned at the very end of this article: https://wpjobmanager.com/document/tutorial-adding-recaptcha-job-submission-form/ 
doesn't seem to exist. We realize this may be an issue with the Applications add-on but we were unable to figure out where else to submit this buglette.

#### Steps to Reproduce the Bug
1. Install version 1.4.5 of WP Job Manager - Applications
2. Add code shown for Applications at the very end of the article above
3. Go to a job and click the Apply button to display the form
4. Fill in the form
5. Do NOT click the checkbox stating that I am not a robot
6. Submit the form

#### What I Expected To Happen
The form would fail validation and be redisplayed (with an error message indicating the issue as that's how we programmed it)

#### What Happened Instead
Validation was never executed so the form was always valid and "robotic" submissions were accepted (instead of being rejected).

**Comment by kraftbj** [comment]
1.4.5 is a really old version of Applications. The current version is 2.2.3. The filter can be found on line 290 of includes/class-wp-job-manager-applications-apply.php.
