### ISSUE TITLE
The jobs shortcode does not persist job type

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#837]
When using a shortcode to set the job type, e.g. `[jobs per_page="2" job_types="full-time" show_tags=false show_filters="false"]`, this works for the initial load of jobs.

After clicking to load more, all jobs are loaded, not those matching the `job_types` attr.

**Comment by jom** [comment]
Able to reproduce. The JS that loads more looks for value of form fields. When `show_filters="false"`, nothing is passed.
