### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by sebcpfc** [Automattic/WP-Job-Manager#840]

**Comment by sebcpfc** [comment]
Hi, I can't remember if your plugin came bundled with my WP theme (Listable by Pixelgrade) or if I bought it separately. Anyhow, out of curiousity, how does the search functionality work? For example, I can search for "document sharing" with no results returned (and I have a listings such as Wrike/PandaDoc where file/document sharing is mentioned). Similarly, I can search for "security" and find GoodHire, which has "employee" in the description, yet if I search for "employee" GoodHire does not pop up. My site is: http://evercloud.co/

I wrote to Pixelgrade and this is what they replied:
"Thanks for reaching out. I should admit that your question is a good one. As you can see, we rely on WP Job Manager plugin for the listings, searching included. This might be the reason that the plugin's authors might be more advisable to give you a proper answer about how the searching is working. I'd be more than happy to help you but I'm afraid this question is exceeding my knowledge. 

Also, you can try activating another theme and see how the search is working there too. The results would be the same and this is why I just want to mention that plugin is responsible for the searching function."

You help will be greatly appreciated!

Cheers,
Sebastian

**Comment by kraftbj** [comment]
Howdy!

Support is available via https://wpjobmanager.com/support/ . Assuming another plugin/theme didn't override it, we hook into the `post_clauses` filter to search for keywords via https://github.com/Automattic/WP-Job-Manager/blob/0bf2658abca036bcc1c0c4fded2193ff42f6aaf7/wp-job-manager-functions.php#L177 .

This uses MySQL to search in the title, meta, content, etc.
