### ISSUE TITLE
Display all form validation errors at once

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#842]
```
On the edit listing page, if multiple fields are not ok with the validation rules and that the edit is submitted, error message are shown one by one. 
Instead, I believe it would be better to highlight all errors and once. That is better for the user than submitting, seeing one error, fixing it, submitting again, seeing another error, fixing it, etc. 
```

**Comment by tripflex** [comment]
A lot of them are handled now by HTML5 which does validation before the user even submits the page ... so the fields that would fail validation would be minimal, like categories, or file uploads, OR from the PHP validation backend on any filters.

**Comment by donnapep** [comment]
Closing this issue in favour of 949-gh-jpop-issues.

**Comment by spencerfinnell** [comment]
@donnapep Can we keep this one open/milestoned so the public can see this is on an active roadmap? Makes it easier for 3rd-party integrations to plan around and stay up to date.

**Comment by donnapep** [comment]
@spencerfinnell Good idea.

**Comment by donnapep** [comment]
Actually, I've moved the issue out of the private repo and added here as #1163.
