### ISSUE TITLE
BUG in 1.25.2 - Expired but featured job offers are still displayed

### ISSUE THREAD

**Issue by Lens40** [Automattic/WP-Job-Manager#843]
#### What I Expected To Happen
When a job is expired it should no longer be listed in the job listings.

#### What Happened Instead
With the latest release v1.25.2 all featured jobs that are expired are still listed and displayed. This was not the case with v1.25.1 so this is a new bug that came with the latest release.

#### Steps to Reproduce the Bug
Get WP Job Manager 1.25.2 create some featured jobs and expire them.

**Comment by Lens40** [comment]
Hi has anyone an idea what and which part of the code might be the reason? As not only the expired featured jobs are still displayed in the job page but unfortunately all expired jobs are listed on the job page....did some settings change?

**Comment by Lens40** [comment]
@donnchawp Hi I found that my issue is related to this commit : https://github.com/Automattic/WP-Job-Manager/commit/1d4fe7ecd0b160164924fc2414d2126a2eec5028

Can you tell me the intention of doing this? The option to hide or display the **content** of an expired job posting makes sense as it allows you to keep the content available for Google/SEO. I guess that is/was the intention of the function. 

Before your modification all expired jobs have not been displayed in the listings which makes a lot of sense, but where still available for Google if the option was disabled. With your modification I have to decide if the expired jobs are all displayed in the listing/search and available for Google or if I disable it I can't have the benefit of keeping the job content for Google Index available. 

I my case I believe you combined two features in one which shouldn't be combined. Especially because it is not a normal use case to display expired listings in the job listings.

My suggestion is to either revert this change or make two options:

1) Hide/Display expired jobs in the listing/search
2) Hide/Display job content of expired job listings -> In case the hidden feature is chosen you might consider adding a 410 or 404 header for google

Regards Lens

**Comment by Lens40** [comment]
If you want to keep it that way which probably wouldn't make sense please consider at least changing the description of the feature and set the "enabled" as default to avoid that new plugin users are wondering why expired listings are still displaying :

If enabled, the content within expired job offers will be hidden. Otherwise, expired job offers will be displayed as normal (without the application area).

into

If enabled, **expired jobs are no longer displayed in the job listings** and the content within expired job offers will be hidden. Otherwise, expired job offers will be displayed as normal (without the application area) **and displayed in the job listings**.

**Comment by Lens40** [comment]
@donnchawp what is your opinion on this?

**Comment by spencerfinnell** [comment]
Closing for https://github.com/Automattic/WP-Job-Manager/issues/869
