### ISSUE TITLE
My job list only  (but filter & category is translated) show on two pages using default language only

### ISSUE THREAD

**Issue by EngMs** [Automattic/WP-Job-Manager#844]
I’m having issues with wp job language plugin and polylang plugin
My job list only (but filter & category is translated) show on two pages using default language only

Default Language: Arabic
Second Language: English

Jobs In Default Language (Arabic) : http://athwaqest.com/%D8%A7%D9%84%D8%AA%D9%88%D8%B8%D9%8A%D9%81/
Jobs In Another Language (English) :http://athwaqest.com/en/employment/

I try this solution #832 but nothing change

**Comment by spencerfinnell** [comment]
http://athwaqest.com/en/employment/ no longer exists.
