### ISSUE TITLE
Replace listing author ID number meta with a dropdown

### ISSUE THREAD

**Issue by kraftbj** [Automattic/WP-Job-Manager#846]
WooCommerce has a nice selector to choose an user for an order. It would be nice to add this instead of requiring a site item to know the user ID of the intended author.

**Comment by spencerfinnell** [comment]
https://github.com/Automattic/WP-Job-Manager/blob/master/changelog.txt#L208

This was removed quite a while ago and would need to be replaced with an AJAX powered search.

**Comment by kraftbj** [comment]
@spencerfinnell Yup, IIRC, WC uses select2 and hits an admin-ajax endpoint. I meant dropdown more as a GUI to select an user vs numeric ID input.

**Comment by tripflex** [comment]
Yeah I agree, this is something that should be added back (but with AJAX feature), as it was originally removed to prevent memory or issues due to large user base, but having to locate the user ID is a hassle sometimes.

**Comment by canyasa** [comment]
Hello everyone, any updates about this feature? I tried to implement 3rd party plugins to achieve this but it messed up :/

**Comment by eppul** [comment]
Yeah I have almost 7k users so hopefully the new implementation will work with large numbers.
