### ISSUE TITLE
Adding Instagram and Pinterest to job submission form

### ISSUE THREAD

**Issue by eppul** [Automattic/WP-Job-Manager#849]
It would be nice to have Instagram and Pinterest in the job submission form.

So companies can add their Instagram and Pinterest account to the job listing.

Also they would be added to job listing same as Facebook, Twitter, Google+ etc

**Comment by kraftbj** [comment]
This can be done already via filters, but will keep in mind for future consideration.

**Comment by bikedorkjon** [comment]
Mentioned in 624161-zen

**Comment by jom** [comment]
Closing in lieu of filter option (for now)
```


add_filter( 'submit_job_form_fields', function( $fields ) {
	$fields['company']['company_instagram'] = array(
		'label'       => __( 'Instagram username', 'wp-job-manager' ),
		'type'        => 'text',
		'required'    => false,
		'placeholder' => __( '@yourcompany', 'wp-job-manager' ),
		'priority'    => 5
	);
	return $fields;
} );
```
