### ISSUE TITLE
Shortcode conflict with Unyson Framework ([job_dashboard] and also [candidate_dashboard], [job_alerts] just to note)

### ISSUE THREAD

**Issue by dthorns17** [Automattic/WP-Job-Manager#851]
#### What I Expected To Happen

Added the [job_dashboard], [job_alerts], and [candidate_dasboard] shortcodes to pages within drag and drop 'Text' element of the Unyson Page Builder and expected them to work the same as on the demo site.

#### What Happened Instead

While the information displayed correctly the only actions that would successfully complete from the listed jobs, resumes, or job alerts was the edit action. The add, delete - every other available action - would not successfully fire. The page would refresh or the job alert form would show, but no updates to the listings or alerts would happen, no messages would appear. 

As an added note - this would happen whether the shortcodes were on the same page or not. As an added note to that note, the [job_dashboard], [candidate_dashboard], and [job_alerts] shortcodes use the same actions as far as having them on the same page. 

#### Steps to Reproduce the Bug

Install a theme with or install the Unyson page builder and add any of the mentioned shortcodes to the page using the drag and drop 'Text' element of the page builder and clicking to the 'Text' tab of the WP WYSIWYG editor that appears.

#### Temporary Solution to the Bug

If the default/classic WP WYSIWYG editor is used for the page, the [job_dashboard], [candidate_dashboard], and [job_alerts] shortcodes work 100% as intended. 

Every action fires successfully. 

(Regarding the shared actions as the [candidate_dashboard] and [job_alerts] dashboard had to be on the same page for my purposes, the names of the [job_alerts] actions were changed in the associated class php file.)

**Comment by spencerfinnell** [comment]
The default https://developer.wordpress.org/reference/functions/wp_editor/ function is used on the job submission and editing page. Please contact the Unyson Framework author for further information as to why the plugin might conflict with an instance of the function on a frontent page.
