### ISSUE TITLE
Resume Manager Spam Emails

### ISSUE THREAD

**Issue by vipindhulia** [Automattic/WP-Job-Manager#852]
Hi, We are facing an issue with the Resume Manager. We are receiving everyday around 15-20 blank emails from Resume Submission. We have checked the code we didn't find from where these emails are coming. Either these are spam bots are trying to fill the form? 

So please suggest how to get rid of this issue. 

Below is the sample emails that we are getting everyday:
-------------------------------------------------------------------------------
Hello

A new resume has just been submitted by **. The details of their resume are as follows:
The content of their resume is as follows:

-----------
You can view this resume here:
You can view/edit this resume in the back-end by clicking here: http://cornhouseconsulting.com/wp-admin/post.php?post=1&action=edit

---------

**Comment by spencerfinnell** [comment]
The only way around this currently would be to require users to be logged in to apply to help prevent spam.

Ensure you don't have any other plugins adding malicious code that might make your site a target for spammers.
