### ISSUE TITLE
502 Bad Gateway When Someone Uploads a Resume

### ISSUE THREAD

**Issue by elenaips** [Automattic/WP-Job-Manager#853]
#### What I Expected To Happen
Clean submission of resume, no errors, etc.

#### What Happened Instead
502 Bad Gateway Error

#### Steps to Reproduce the Bug
Upload a .doc or .docx file - 100% | Upload a .pdf file - sometimes

**Comment by spencerfinnell** [comment]
Try enabling https://wordpress.org/plugins/disable-real-mime-check/ and uploading again.

**Comment by jom** [comment]
Closed. Should be fixed in WordPress 4.7.3.
