### ISSUE TITLE
Job type treated as string instead of array

### ISSUE THREAD

**Issue by deangelis** [Automattic/WP-Job-Manager#854]
There are many places where job type is treated as it would have only one value and it causes some problems. Here are some of my findings, but there are more i believe:

**/includes/forms/class-wp-job-manager-form-submit-job.php, row 519**
-> Returns array of job type id:s ( array(1) { [0]=> int(xxx) } ) and causes problem in row 523 where it sanitizes the title. I assume that something has changed and $values['job']['job_type']; in row 519 does not return string as it used to.

**/wp-job-manager-template.php, rows 232-269**
-> the_job_type & get_the_job_type functions only return one job type value and it's random one. You cannot get all the selected job types without creating your own function.

**Admin -view**
-> In "Job listings" view "Type" column only shows one random job type, instead of all the selected types

**Job url is generated badly**
-> Job url has "array" -text instead of job type. Example: /company-address-array-position-city/

I don't have any code fixes because this goes too deep and affects many places.

**Comment by spencerfinnell** [comment]
Related #781, #549

**Comment by tripflex** [comment]
from #884 

I get this error on job preview:
`Notice: Array to string conversion in /home/dariliya/public_html/najdi-zaposlitev/wp-content/plugins/wp-job-manager/includes/forms/class-wp-job-manager-form-submit-job.php on line 520`

**Comment by ryantodd** [comment]
This issue is annoying and is affecting is a really bad url for seo. Would be good to get this fixed

**Comment by spencerfinnell** [comment]
@jom Would like to see this bumped down to 1.26.1 -- it is very annoying and will cause SEO issues for users when they have to update URLs.

**Comment by rammyleeds** [comment]
Apologies in advance, I am very new to this website and am playing around with WP Job Manager. What I don't understand is this - the latest update allows the person submitting a job to select more than one job type (for example a person might say that the job is full-time or part-time - i.e. that they are flexible). Yet, the job listings page only outputs ONE of the assigned job catergories and not all of them. So, what's the point of enabling multiple selection when it outputs to nothing? Can this be fixed asap? Shouldn't be hard to do should it? The person who had this marvellous idea of allowing multiple selections - can you please allow it to be outputted? Display all selections in the job-listings.
