### ISSUE TITLE
WPML problem with the secondary language when showing a single job 

### ISSUE THREAD

**Issue by ologix** [Automattic/WP-Job-Manager#856]
My site is in english(main language) and french. The goal is to be able to show the same single job page in english and in french without having to translate the data.

What it does is, when you click to see a job when the listing is in french, the site goes back in english. 

To reproduce the bug, go to that url: http://cibleretour.com.66-129-145-130.megaqc.com/fr/emplois/ and click on any job. it'll switch back in english.

**Comment by Lens40** [comment]
Hi Ologix, this is not a bug but the normal behavior of Wordpress/WPML. So what you need to do is on creation of your jobs duplicate them into the other languages. You can do it manually on WPML in the backend or do it automatically. Last solution is a bit of custom work but feasible with WPML and their hooks.

**Comment by Lens40** [comment]
Also note that with the duplication you will also have the hreflang-Tags in each language version to avoid duplicate content within your website.

**Comment by ologix** [comment]
Thank you for the help but, I still seem to be needing some more.
1. It may be me just not looking at the right place but, how can you make the posts duplicate themselves automatically on creation?
2. Even with the page translated, it gets me a 404 error when I try to reach a job in french.

**Comment by ologix** [comment]
I'm still searching for an answer to how to automatically make the post duplicate and make my reaching of the job in french not make an error 404.

**Comment by ologix** [comment]
I have made it to a point where I know for certain it's about the rewriterules. When the site redirects from /job/job-slug to /poste/job-slug, it no longer detects it as a job. Is it a known problem?

**Comment by ologix** [comment]
The solution to the problem was to activate the "Custom posts slug translation options" and then translate the actual post-type so that the rewrite detects it as it is and not as some non-existant category of articles.
