### ISSUE TITLE
Expired jobs are being listed, expiry date field bugging out

### ISSUE THREAD

**Issue by jerwre** [Automattic/WP-Job-Manager#860]
Wordpress 4.7.1 (sv_SE - swedish if that matters)
WP Job Manager 1.25.2
Tested with default themes and all other plugins disabled.

#### What I Expected To Happen

Expired jobs should not be listed. 

Expiry date field should display saved expiry date, and allow you to enter a date earlier than today.

#### What Happened Instead

Expired jobs are being listed. 

In the database the post_status is set to expired, and the _job_expires in postmeta has the original expiry date set.

When I go to edit the post, the expiry date field shows the old date for a second before changing to the current date. If I try to set an earlier date than today and Update post, it'll be updated to todays date, and the post status will be changed to active. 

Saves normally if you set a future date.

_My current "work around" for not displaying expired jobs:_
Expired jobs are no longer being listed when the following option is checked:

> Hide content within expired listings
> If enabled, the content within expired listings will be hidden. Otherwise, expired listings will be displayed as normal (without the application area).

However I'd like the expired jobs to still be accessible via the URL, like before, without being listed.

#### Steps to Reproduce the Bug

Post/edit a job, set expiry date/status earlier than today to have it be expired.

**Comment by Lens40** [comment]
Check out: https://github.com/Automattic/WP-Job-Manager/issues/843. At least for the second half of your issue it is the same. In my opinion the development went itno a wrong direction.

**Comment by spencerfinnell** [comment]
Closing for https://github.com/Automattic/WP-Job-Manager/issues/869
