### ISSUE TITLE
Limiting job results of [indeed_jobs]

### ISSUE THREAD

**Issue by blaivas** [Automattic/WP-Job-Manager#861]
I wanted a simple thing - show 5 latest jobs with NO filters and below show 5 jobs from indeed.

So, first I tried this short code - [jobs per_page="5" show_filters="false"]. At Indeed Integration settings I have set "Backfill after jobs" to 5. But with this short code Indeed jobs do not show up. They only show up if Filters are set to true, but I really do not want filters.

So then I have tried this combination of 2 short codes in one line - [jobs per_page="5" show_filters="false"][indeed_jobs per_page="5"]. In this case jobs are showing up, 5 of my own jobs and for some reason 10 from Indeed, not 5. 

As far as I understand I should be able to use the same arguments (like per_page, orderby, order, show_pagination and others) with the [indeed_jobs] short code? So what is wrong? Or is this a bug somewhere?

Thank you

**Comment by spencerfinnell** [comment]
Thank you for the report -- this has been logged in the Indeed Integration repository.
