### ISSUE TITLE
“Apply For Job” Button Still Displayed Even Listing has Expired

### ISSUE THREAD

**Issue by lordzden** [Automattic/WP-Job-Manager#865]
#### What I Expected To Happen
Expired listings should disable or show any indicators that the listing is expired.
Apply for Job should be replaced with word “Expired”.
I dont want to hide expired jobs because it will hurt my SEO. I want to keep the expired listing but I dont want the applicants to apply using the button.

#### What Happened Instead
The Apply for Job is still displayed after listing has expired.

#### Steps to Reproduce the Bug
https://dumjobs.com/job/citymall-dumaguete-job-hiring/
![](https://content.screencast.com/users/BaloydiLloydi/folders/Jing/media/2b4893ee-6a20-4cd9-b714-1c0c822eef77/2017-02-04_1218.png)
`https://www.screencast.com/t/87XNf9oC

**More Information:**

- **Hide content within expired listings is disabled.**
- Notes: “If enabled, the content within expired listings will be hidden. Otherwise, expired listings will be displayed as normal (without the application area).”
- I have updated WordPress
- Updated Job Manager Plugin
- Theme is updated to latest version
**- Jobs are set to expired after 30 days.**
-

**Comment by spencerfinnell** [comment]
Closing for #869 -- will ensure this is hidden and listings are properly expired.

**Comment by lordzden** [comment]
thanks!
