### ISSUE TITLE
Problem WP JOB Manager 

### ISSUE THREAD

**Issue by matosso** [Automattic/WP-Job-Manager#866]
The problem is in the plugin WP Job Manager, I do not know what to do
![error](https://cloud.githubusercontent.com/assets/25559959/22623850/7a15d9ea-eb50-11e6-9603-5e626100631d.png)

**Comment by dbtlr** [comment]
@matosso: That error appears to be coming from a mapping plugin you're using. Could you please provide a list of plugins and versions you have installed? That would help me try to replicate and track it down.

**Comment by spencerfinnell** [comment]
Your theme might be calling additional libraries when the WP Job Manager plugin is activated, but there are no inclusions of the Leaflet javascript in the core plugin.
