### ISSUE TITLE
Company Logo not displayed on company profiles

### ISSUE THREAD

**Issue by HarshalPatil15** [Automattic/WP-Job-Manager#867]
For company profile page, Company logos are not visible as per company name.
Plugin name: WP Job Manager – Company Profiles
Plugin file – wp-job-manager-companies/wp-job-manager-companies.php

please note that – Company logos are visible on Home Page job listings for the companies.
Let me know if more information is required.

**Comment by spencerfinnell** [comment]
This is not related to the WP Job Manager core plugin -- company profiles are not created by default.
