### ISSUE TITLE
The file-field.php in /templates/form-fields is missing the required tag condition. 

### ISSUE THREAD

**Issue by wehaveaplan** [Automattic/WP-Job-Manager#868]

**Comment by wehaveaplan** [comment]
Row number 24 needs: <?php if ( ! empty( $field['required'] ) ) echo 'required'; ?>

**Comment by dbtlr** [comment]
@wehaveaplan: Please provide more information on what you're expecting vs what it is doing.

You can also provide a PR that adds this condition if that is easier to show.

**Comment by tripflex** [comment]
I think he's referring to the HTML5 required attribute.  If you really need this you can use a template override.  This is more of a feature request rather than an issue

**Comment by spencerfinnell** [comment]
I personally think the HTML5 validation should be removed in favor of only server side since not all fields currently support it. It makes for a bad UX.

**Comment by tripflex** [comment]
Yeah I agree, i've actually added an update to my field editor plugin to only add the HTML5 required attribute if configured in settings to do so.  I also looked at my templates and I didn't add required to the file field one, when I did to all the others, so there has to be a reason I didn't add it (compatibility wise), so I would lean on the side of saying don't add this, close the issue, if it's that important, the user can add it themselves using a template override.
