### ISSUE TITLE
Geocoding for new Jobs doesnt work

### ISSUE THREAD

**Issue by Bertsi** [Automattic/WP-Job-Manager#874]
So far I understood the functions of WP-Job-Manager correctly, the plugin automatically assign the correct geodata when I type in the name of a city to field location. 

In my case nothing happens. I can type in what city, adress, etc ever I want, the plugin doesnt search for any geodata. It seems like, that the function is just not activated. (Well, it worked one time for the city called "Münster" at the very beginning. But afterwards never again. I deinstalled the plugin and installed it again but it doesnt work anymore .)

Reproduction: Add new job - type in a location ... and nothing happens in my case.

Does anyone has an idea what the problem could be?

Thanks a lot!

**Comment by spencerfinnell** [comment]
See: https://github.com/Automattic/WP-Job-Manager/issues/712
