### ISSUE TITLE
Translate to Chinese issue

### ISSUE THREAD

**Issue by varydu** [Automattic/WP-Job-Manager#876]
I just translated this plugin to Chinese, according your document putted them into wp-content/language folder, but frontend is still in English. I named po and mo files to zh_CN-wp-job-manager.mo and zh_CN-wp-job-manager.po. Do I need to do anything else?

**Comment by spencerfinnell** [comment]
The file names should be `wp-job-manager-zh_CN`

If you have translated the plugin please contribute your translations back to https://translate.wordpress.org/projects/wp-plugins/wp-job-manager/dev/zh-tw/default
