### ISSUE TITLE
How to remove the Google Maps Link from the single job listing while keeping the location text?

### ISSUE THREAD

**Issue by RonaldF** [Automattic/WP-Job-Manager#877]
#### What I Expected To Happen

I am looking for a filter to removed the Google Maps Link from the single job listing. I followed the instructions found here when my client asked. https://wordpress.org/support/topic/disable-geolocation-in-job-listings/#post-8818583

Using the function code in the link above, the link did not disappear. I have added a screenshot to show the listing location link we are wanting to disable. We still want it to say "US West Coast"
<img width="417" alt="screen shot 2017-02-20 at 9 28 24 am" src="https://cloud.githubusercontent.com/assets/13787573/23131373/6033fb8c-f74f-11e6-97bb-e2d9f8e8ee1d.png">

**Comment by tripflex** [comment]
GitHub is for reporting issues and problems, not for support requests.  Please keep support requests on the appropriate Support Forum.

Specifically shown when creating new issue:
GitHub issues aren't for support! If you have questions, use this form: https://wpjobmanager.com/support/
