### ISSUE TITLE
ISSUE : Warning: number_format() expects parameter 1 to be double, string given in

### ISSUE THREAD

**Issue by benmmg** [Automattic/WP-Job-Manager#878]
I get this error message in my wp admin account and my website.

Warning: number_format() expects parameter 1 to be double, string given in (On Line 69)

PHP CODE 

	/**
	 * Get cost
	 * @return float
	 */
	public static function get_job_listing_cost() {
	return apply_filters( 'wp_job_manager_spl_get_job_listing_cost', number_format( get_option( 'job_manager_spl_listing_cost', 2 ), 4, '.', '' ) );
	}

Kindly Help.

Thanks

**Comment by tripflex** [comment]
This is not related to this core WP Job Manager plugin, this is related to a paid addon.  You should open a support request at wpjobmanager.com regarding this.

**Comment by benmmg** [comment]
Thanks
