### ISSUE TITLE
Dutch Translation Jquery ui dates wrong

### ISSUE THREAD

**Issue by valcosoftj** [Automattic/WP-Job-Manager#879]
#### What I Expected To Happen
dates to be correct
#### What Happened Instead
dates wrong
#### Steps to Reproduce the Bug
set blog language to duch and dates in the jquery ui datepicker are wrong

Its just badly translated in the pot file, please correct as below:
yyyy-mm-dd -> d-m-yy
yy-mm-dd -> d/m/yy

**Comment by spencerfinnell** [comment]
This can be updated here: https://translate.wordpress.org/projects/wp-plugins/wp-job-manager/dev/nl/default and will be included in the next release automatically.
