### ISSUE TITLE
Filtering by listings types

### ISSUE THREAD

**Issue by bugison** [Automattic/WP-Job-Manager#882]
Hi,
I use WP Job Manager with Listify theme and in search option on listings site there is “filter by type” and all checkboxes are marked by default.
How to do it if I want all my listings to be shown when checkboxes are not marked? Filtering should be done only after marking checkboxes. How to obtain this solution?
Thank you.

**Comment by volodymyrpekh** [comment]
@bugison For support, please visit [https://wpjobmanager.com/support/](https://wpjobmanager.com/support/)

**Comment by bugison** [comment]
@volodymyrpekh There is nothing about that. There is nothing about that.
I sent a request for help to wp job manager support and I got an answer:

> Unfortunately this isn't something that our plugin can do by itself. If you're using a suitably complex third-party theme, it *might* be able to do this, but I can't say for sure.
> 
> Sorry I can't be of more help here! :(

Will anybody help?

**Comment by volodymyrpekh** [comment]
@bugison Did you contact Astoundify team for support?

**Comment by bugison** [comment]
Of course, they answered:

> Thank you for getting in touch with us regarding your concern. Your question relates to the plugin WP Job Manager and the question would need to be answered by the WP Job Manager developers as they have in-depth knowledge of the plugin and it's features. The theme "Listify" provides the styling for your website and does not handle any of the features such as posting of listings, filtering by types, etc.
> 
> If you have questions regarding the plugin please direct them to the developers of that plugin so they can assist you. Support for that plugin is provided in the following places:
> 
>     WP Job Manager Add-on Plugins Support: https://wpjobmanager.com/support/
>     WP Job Manager WordPress.org Support: https://wordpress.org/support/plugin/wp-job-manager

**Comment by spencerfinnell** [comment]
Types are "exclusive" in the way they query results so starting with them all unchecked would mean the initial search would have no results. 

Whe tags addon works on inclusion like you're describing.

**Comment by bugison** [comment]
I have seen Job Tag WP Job Manager but I don't like it how it look like. I would rather filtering was done in the form checkboxes.

**Comment by spencerfinnell** [comment]
Listify styles tags the same way as types.

**Comment by bugison** [comment]
I'll check it.
