### ISSUE TITLE
Search with more than one keyword - zero results

### ISSUE THREAD

**Issue by Bertsi** [Automattic/WP-Job-Manager#894]
Im using jobify for my job listings. When I use the search bar and type in more then one keyword in the search-field, zero jobs get found, even when I use two exact keywords that appear in the headline of a certain job_posting. The only way it works, when I type the words in the exact order of the title of a job listing.

Example:
Title of Job LIsting: Manager for research-project
Search : Manager research - 0 Results
Search: research-project for Manager - 0 Results
Search: Manager for research - 1 Result

I changed the code like in #859 suggested but it didnt help.

Can anyone help me with that issue. Thanks a lot!

**Comment by rachelsquirrel** [comment]
I've got another report of this in #3103427-t and I can also reproduce it. 

It looks like the search does not support boolean operators like AND and OR. Eg: If I have two jobs - "brick layer" and "pianist" - when I search for "brick" the first job is returned. If I try searching for "brick pianist" or "brick and pianist" it returns no results.

**Comment by davoraltman** [comment]
@jom Can you look into this when you have time? Thanks!

**Comment by patrikx** [comment]
Hello, any updates on this? The search is almost unusable in the current state. Do not hesitate to contact me if you need more details or access to staging environment to troubleshoot this issue.

**Comment by davoraltman** [comment]
3205843-t
