### ISSUE TITLE
Expiration date issue

### ISSUE THREAD

**Issue by smuellerbrainfruit** [Automattic/WP-Job-Manager#895]

**Comment by smuellerbrainfruit** [comment]
Hello,

on my website: http://legalbc.brainfruit.net, the apply button doen't show up, since the Update

To reproduce the issue: 
You must login and then submit a Job under (mein pitchgate -> projekt einstellen)
In the Preview the button doesn't show up, too.
Then if the admin release the job, the button doesn't show up either.
 
I found the bug, it's because the Experiation date is automatically set to the current date. 
But I don't know how to fix this.

Thanks for your help.

**Comment by spencerfinnell** [comment]
https://github.com/Automattic/WP-Job-Manager/issues/869
