### ISSUE TITLE
Improvement: Up and Downgrade Paid Listing

### ISSUE THREAD

**Issue by CCarton** [Automattic/WP-Job-Manager#897]
Hello,

I'am working on a website that uses a couple of WJM plugins, including WC Paid Listing.
I've tried to set up subscription type packages (with paid listing and WC Subscription) and with levels so that a enduser can up and downgrade when they want. A bit is possible by switching, but that is not a decent method for listing packages. 
Simple explanation:
You can have multiple subscription packages like:
                                    
- Free (so without the checkout)
- Premium (paid monthly)
- Premium (paid yearly with discount)
- enz enz

If someone adds a listing (Listify theme) under free, and wants to update to premium it's an upgrade and they can add more info to the listing. If they downgrade to free, the 'premium' info isn't visible anymore but only the free info, but with the info somewhere saved..  Expiration of a paid subscription results in automatically go back to free.. (Free is forever)

So basicly a decent up and downgrade module.
I know more people are questioning this on Envato, is there a change this can be build in the near future?

**Comment by medienstuermer** [comment]
This would be an very important and good feature! 
Now all these things need to be done manually which causes a lot of administration work!

**Comment by Lens40** [comment]
Yes i support that too, it would be good to allow the customers to upgrade a normal listing to a featured listing by paying an upgrade fee. Most clients buy normal job packages with several jobs and decide only later to upgrade. Also it would help sales when a customer chooses a normal job and you give him the option to choose the upgrade option at the end of the publishing periode when he places the offer.

**Comment by Lens40** [comment]
Sorry I meant publishing process not period

**Comment by 11digitlabs** [comment]
@CCarton hey! Could you please let me know how you managed to switch between listing packages? No matter what I've tried it doesn't seem possible, I dont get a button in the order to upgrade or downgrade like it's shown here https://docs.woocommerce.com/document/subscriptions/switching-guide/#section-6

Thanks for your help in advance

**Comment by Kipperlenny** [comment]
why has this been closed?

**Comment by jom** [comment]
@Kipperlenny This is for WPJM core issues only. We're tracking this in the WC Paid Listings repository (no updates/ETA).
