### ISSUE TITLE
Searching for certain keywords return all results

### ISSUE THREAD

**Issue by chinmeh** [Automattic/WP-Job-Manager#900]
When searched for keywords **wp-content, tent, wp, content, uploads,etc** all listings are displayed instead of those listings which have the keyword in their post title, post content or valid post meta.

Steps to Reproduce the Bug:
- Visit the Jobs Page.Make sure you have listings containing attachments (image, doc)
- Search with keywords wp, wp-content,uploads, content,tent, etc. you would get all listings which have an attachment associated in the results.

Approach for solving the issue:
-Meta keys containing paths to attachments should be replaced by attachment ID or be excluded from the search query.

**Comment by turtlepod** [comment]
I just want to mention that this happen for regular WordPress search too.
Add image in a post and search for "uploads" or "wp" and it will return in search results.

So, this is WP behavior not really WP Job Manager.

**Comment by spencerfinnell** [comment]
There could be a blacklist of `meta_key`s that are not checked here: https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L182

Not sure what performance impact it would have though. 

There are no default fields that store a URL in meta anymore, however old data can potentially exist in the original `_company_logo` field, and themes/plugins can introduce their own fields (both of our themes do). It would be nice to have a way to easily exclude these from searching when registering fields for the submission form.

**Comment by jom** [comment]
Fixed in #910
