### ISSUE TITLE
'Apply Now' button invisible on iPhone and iPad

### ISSUE THREAD

**Issue by djdirtymac** [Automattic/WP-Job-Manager#909]
#### What I Expected To Happen
Affected website: http://maxwellbruce.com/jobs/ (all jobs have the same problem). The button should be visible on all devices, immediately below the job description.
#### What Happened Instead
On Apple handheld devices (and possibly others...?) the button is invisible, although still there. You can tap on the white space where the button is normally located, and it is still active.
#### Steps to Reproduce the Bug
I've updated the plugin to the most recent version, but the issue remains. I also submitted a support ticket several weeks ago, but have had no response.

**Comment by jom** [comment]
Hi @djdirtymac! I just tried it on your site and it looks like it is working. I remember checking it out right when you posted and I was able to reproduce it. Was it an issue with your theme? Are you still able to reproduce?
