### ISSUE TITLE
Show joblistings per Type

### ISSUE THREAD

**Issue by prochimps** [Automattic/WP-Job-Manager#913]
I want to show a list of jobs with a shortcode, but only certain types.
such a list of Full Time or Part time only.

**Comment by volodymyrpekh** [comment]
Hey @prochimps,

It's not a support forum. Please check documentation on this page: [https://wpjobmanager.com/document/shortcode-reference/](https://wpjobmanager.com/document/shortcode-reference/)

Thank you
