### ISSUE TITLE
Fatal error on theme customization page

### ISSUE THREAD

**Issue by sophia12345678** [Automattic/WP-Job-Manager#915]
I am working on a site for a client and can't even customize the homepage because when I load the Listify theme customizer, I get an error that says:

Fatal error: Call to undefined function get_job_manager_template() in /home3/lilwelchy/public_html/wp-content/plugins/wp-job-manager/wp-job-manager.php on line 145

I have tried reaching out to WP Job Manager and Astoundify to no avail. 

The website is: www.iknow-a-guy.ca

I have attached a screenshot as well.

Any help would be much appreciated as I can't begin work for my client until this is resolved!

Thanks in advance!
![wp job manager error](https://cloud.githubusercontent.com/assets/26797750/24513689/da3ccd42-153f-11e7-88ec-281815ab717a.png)

**Comment by spencerfinnell** [comment]
Your version of Listify is about a year out of date. Updating it should resolve your issues.

**Comment by sophia12345678** [comment]
Thank you for your reply! I did do the theme update, and the error went away for a while. 
I've just logged back in to do more updates and am getting the same error again. 

Is there anything else that could be effecting this? The theme and all plugins are up to date. 

Thanks in advance!

**Comment by spencerfinnell** [comment]
Do you see the error if you activate a different theme?

**Comment by sophia12345678** [comment]
I actually think I just figured it out! 
For some reason when I go to the customization page, I am not always signed in on the site, but only the backend of wordpress. Once I login through the site as well, the error goes away. 

Thank you kindly for your prompt responses!
