### ISSUE TITLE
Incorrect Files on WordPress.org

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#916]
https://cloudup.com/cV1ha-8L1xC

The current tagged release has a duplicate `trunk` directory. This causes activation right after installation to fail: `wp-admin/plugins.php?_wpnonce=d4458d675c&action=activate&plugin=wp-job-manager/trunk/wp-job-manager.php`

See `/trunk`

cc @dbtlr @kraftbj

**Comment by kraftbj** [comment]
Removed in 1626119-plugins. I didn't make a new tag, so folks with WordFence will probably get some type of alarm. @dbtlr - I don't think this is worth tagging a new release, but fine with doing it if you think so.

@dbtlr - The release script from the p2 is flawed. This is the first release I shipped using it (and I missed this, so on me) so let's stick to manual until we determine what happened.

**Comment by spencerfinnell** [comment]
Thanks for the quick action @kraftbj

**Comment by dbtlr** [comment]
Sounds good @kraftbj, I'll defer to your judgment here. :)
