### ISSUE TITLE
Add support for remote job listings

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/WP-Job-Manager#918]
Listings are currently tied to a single location. If no location is specified then the listings don't show up in a search.

Would be good to add support for 'location independent' job listings.

3135358-t

**Comment by spencerfinnell** [comment]
A workaround that can be used now is to use the Predefined Regions plugin and add a "Remote" region: https://wordpress.org/plugins/wp-job-manager-locations

**Comment by aheckler** [comment]
821075-zen

**Comment by aheckler** [comment]
When we do this, we should also add it to the Google Job Search schema. CTRL+F here for `TELECOMMUTE` to see how they want us to designate remote jobs:

https://developers.google.com/search/docs/data-types/job-posting

That will probably need to be a new checkbox in the default form fields.

**Comment by 0xDELS** [comment]
I'll give this a shot 👍

**Comment by danjjohnson** [comment]
This is very relevant now, given the COVID-19 situation:
https://developers.google.com/search/docs/data-types/job-posting#remote-jobs

3052806-zen

**Comment by thedigitalcircle** [comment]
Yes Indeed. But thread was started on 3 years back, still pending ☹️

**Comment by 0xDELS** [comment]
I think that the code is still up to date, probably just needs some testing to see if it still compatible with the current version of WordPress.

**Comment by starshunter88** [comment]
+1

**Comment by bindlegirl** [comment]
Requested in zen-3173499

**Comment by pranali333** [comment]
Pre-sale inquiry: 3219816-zen

**Comment by tripflex** [comment]
Also brought up here https://wordpress.org/support/topic/remote-job-location/

**Comment by tripflex** [comment]
Seems to be much more prevalent now with COVID may want to circle back to https://github.com/Automattic/WP-Job-Manager/pull/1621

**Comment by starshunter88** [comment]
any news about this very much needed feature?

**Comment by thedigitalcircle** [comment]
Yes.. I am waiting so long...

**Comment by tripflex** [comment]
@jom any thoughts on this?

**Comment by aicee** [comment]
Requested here: 3997043-zen

**Comment by cena** [comment]
4334490-zen

**Comment by davo20019** [comment]
Any updates on this?

**Comment by samikip** [comment]
Any news on this?? Going to 5 years now!

**Comment by MikeSEONuts** [comment]
Hi has there been an update on this - we have a website with remote jobs included so we need the option to add this schema too.
