### ISSUE TITLE
Use WordPress timezone for expiring jobs and sending emails

### ISSUE THREAD

**Issue by bgfrancey** [Automattic/WP-Job-Manager#919]
When a user submits a job and adds a closing date, the post disappears at the start of that day (ie. Jan 1, 00:00h) as opposed to the end of the day (ie. Jan 1, 23:59). 

This is something that is an issue for my client as they have listings that are closing before the actual deadline.

**Comment by jom** [comment]
I wonder if we should add a setting for this (End of Day vs Start of Day) and default it at the current behavior. I'm actually not sure what is the most intuitive for this. If we look at `calculate_job_expiry()`, it is just using `strtotime()`'s date math which, to me, would include all of the day it expires. 

@bikedorkjon @davoraltman @spencerfinnell et al.: How should we handle this?

**Comment by spencerfinnell** [comment]
Not sure a setting is needed but a filter might be nice. I personally haven't seen this requested anywhere else.

**Comment by davoraltman** [comment]
My $0.02 would be to set it to expire at the end of the day by default and add either a filter for it or a setting. Adding a setting would be a better user experience but this indeed isn't a very needed/used feature and adding a filter for it might a better idea.

+1 for the filter

**Comment by tripflex** [comment]
👍  for the filter as well

**Comment by tiberain** [comment]
Has this been fixed yet and in regards to #1037 has that been added into the master version yet

**Comment by aheckler** [comment]
937329-zen

**Comment by jom** [comment]
I just spent some time looking at the code for this. There are two instances where a job can expire. 
1) In WP admin when a job is saved (it checks the expiration date).
2) In `WP_Job_Manager_Post_Types::check_for_expired_jobs()`.

In both, it evaluates as true if current date > expiration date. So, if it expires on `2018-02-16` and today is `2018-02-16` it will _not_ be set to expired. This seems to have always been the behavior, granted there have been other bugs that could have affected this. If we wanted to change anything, it would actually be to have it expire on the morning of (`expired = current_date <= expired_date`).

For now, I'm going to return this to proposal status and remove the milestone.

One thing worth checking is your WordPress instance's timezone preference in Settings > General. If your timezone is set to UTC and you are in Seattle (UTC-8) at 6pm in the evening and set a job to expire today in Seattle, it will be "in the past" in UTC and will be set to expired.

@aheckler That ticket looks like it is a bug with the application deadline. There are a few issues with that plugin that could be the culprit. I'll take a look and tag the ticket if I see one that matches. In the code, application deadline does behave differently and defines `expired_or_no_more_apply = current_date_minus_1_day < expired_date` (effectively `current_date <= expired_date`).

**Comment by Irpe1337master** [comment]
Pump! 

As said in earlier messages "check_for_expired_jobs" method compares date and not time. For us this enchancement would be awesome so please add support for time when expiring listings! :)  

Also why is expiry cron job scheduled hourly if "check_for_expired_jobs" method doesn't check time?

**Comment by crazelab** [comment]
Hi all,

We are in 2020 and seems that the issue of the expired jobs is still unsolved (#983 #1037).

I personally have the same issue today.

May I know any updates which maybe I missed about this topic?

Thanks,

**Comment by jom** [comment]
Going to fold this into normal timezone standardization work. We should include a filter for start of day or end of day.
