### ISSUE TITLE
Disallow linking to other posts inside the WP editor

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#920]
#### What I Expected To Happen
When I try to add a link inside the [submit_job_form] page in the Description field, I shouldn't be able to see links to other posts.
#### What Happened Instead
I can see links to all post types made on the site. This happens on all Editor fields including the [submit_resume_form] page (ref in gh-137). This only happens when you are **logged in**.
#### Steps to Reproduce the Bug

<img width="538" alt="screen shot 2017-04-05 at 9 30 20 pm" src="https://cloud.githubusercontent.com/assets/10340370/24723277/3737c45a-1a47-11e7-9643-01e5db589bc4.png">

<img width="532" alt="screen shot 2017-04-05 at 9 30 43 pm" src="https://cloud.githubusercontent.com/assets/10340370/24723280/3a72d9f2-1a47-11e7-95f7-5252ce43f6d2.png">

cc @annezazuu @bikedorkjon @kraftbj

**Comment by davoraltman** [comment]
@dbtlr Can you take a look at this one when you have time? Thanks!

**Comment by jom** [comment]
We can filter the results (`wp_link_query_args` and `wp_link_query` filters) for this but the prompt text is [built into WordPress core's](https://github.com/WordPress/WordPress/blob/master/wp-includes/js/tinymce/plugins/wplink/plugin.js#L59) `wplink` TinyMCE plugin. Looks like they took out TinyMCE's default `link` plugin. Should we just filter out all page/post results from this link editor when editing/creating job listings from the shortcodes?

**Comment by spencerfinnell** [comment]
If the query is modified to return no results does it hide that section? I think that would be best.

**Comment by jom** [comment]
@spencerfinnell No. On the initial view (1st screenshot) nothing would show up but on the "Link Options" view it would just say "No results found" 

<img width="392" alt="screen shot 2017-04-06 at 4 19 49 pm" src="https://cloud.githubusercontent.com/assets/68693/24762006/f25222ba-1ae4-11e7-9a9d-980052967987.png">
<img width="497" alt="screen shot 2017-04-06 at 4 20 00 pm" src="https://cloud.githubusercontent.com/assets/68693/24762007/f27d7866-1ae4-11e7-8e2e-9c121ff92175.png">

**Comment by jom** [comment]
This might be a bit trickier than I originally thought. The query doesn't send much information about where it is coming from and I imagine we want this functionality to work elsewhere. We could use the referral, but that seems a bit hacky. I'll investigate it more. I don't think writing a custom TinyMCE plugin and packaging it with WPJM for link entry is something we want to do.

**Comment by spencerfinnell** [comment]
Maybe ensure the query can't return anything then hide the no results area with CSS?

**Comment by davoraltman** [comment]
@jom The same problem exists for [submit_resume_form] shortcode in the Resume Manager add-on. Can you add a fix for that one as well or will the fix you added resolve the problem in the Resume Manager? Thanks!

**Comment by jom** [comment]
This fix won't fix that plugin. If this hacky-ish approach is approved, I'll apply the same fix to that plugin.
