### ISSUE TITLE
Nothing happens after clicking "Preview"

### ISSUE THREAD

**Issue by sophia12345678** [Automattic/WP-Job-Manager#921]
I'm having an issue with the listing submission form. Once everything is filled out and you click "Preview", nothing happens. The exact same page is reloaded with a blank form. 

I tried deactivating all the plugins to see if any of them were causing this, but had no luck narrowing down the search. 

Any idea what could be causing this?

Website is: iknow-a-guy.ca

Thanks!

**Comment by spencerfinnell** [comment]
Do you have the same issue with a default WordPress theme?

**Comment by sophia12345678** [comment]
Yes, the issue is the same with the Twenty Fifteen theme.

**Comment by bikedorkjon** [comment]
Are you seeing anything in your php error logs when you submit the form?

**Comment by sophia12345678** [comment]
No - nothing is showing up their either. Is there any way of using a different plugin that will achieve the same thing? The form hasn't been working for about a week now.

**Comment by sophia12345678** [comment]
![errormessage2](https://cloud.githubusercontent.com/assets/26797750/25065515/5f803c2c-21df-11e7-8c95-e33d81511a9f.png)
![errormessage](https://cloud.githubusercontent.com/assets/26797750/25065514/5f802c1e-21df-11e7-8668-2cfb6874d961.png)

Still having issues but have found some other error messages. Any idea if this is related or how it can be fixed? We really need to get this form but up and working, and I would really appreciate WP Job Manager's assistance as it is the main component of the website.

I have attached screenshots. 

Willing to do a work-around if you have any suggestions either.

Thanks!

**Comment by sophia12345678** [comment]
Even deactivating contact form 7 doesn't change anything - the form is still on the page and behaves the same way.

Could this suggest there is something not set up properly between WP Job Manager and Contact Form 7?

Thanks

**Comment by jom** [comment]
It looks like assets related to Evergage were halting JavaScript execution on the site. I don't see these assets on there any longer. Is this still an issue?
