### ISSUE TITLE
Display Multiple Job Types

### ISSUE THREAD

**Issue by davoraltman** [Automattic/WP-Job-Manager#928]
@donnchawp Created a cool [feature](https://github.com/Automattic/WP-Job-Manager/commit/3f37d98d635995f06d5f6a38edaf011f5c57055a) to add multiple job types to a listing. However, it would also be cool to have the labels for the multiple types displayed on the frontend inside both the jobs and single job pages - http://cld.wthms.co/Vy6G

Came up in 3169876-t

**Comment by davoraltman** [comment]
3229034-t

**Comment by bikedorkjon** [comment]
https://wordpress.org/support/topic/only-one-job-type-showing-despite-enable-multiple-types-for-listings-checked/

**Comment by spencerfinnell** [comment]
Duplicate and solution suggested in https://github.com/Automattic/WP-Job-Manager/issues/854

**Comment by rammyleeds** [comment]
Apologies in advance, I am very new to this website and am playing around with WP Job Manager.   What I don't understand is this - the latest update allows the person submitting a job to select more than one job type (for example a person might say that the job is full-time or part-time - i.e. that they are flexible).    Yet, the job listings page only outputs ONE of the assigned job catergories and not all of them.    So, what's the point of enabling multiple selection when it outputs to nothing?   Can this be fixed asap?   Shouldn't be hard to do should it?   The person who had this marvellous idea of allowing multiple selections - can you please allow it to be outputted?   Display all selections in the job-listings.

**Comment by jom** [comment]
@rammyleeds #1014 will fix this in the next release (due soon).
