### ISSUE TITLE
Wp job tag manager added when modifying job in admin - problem with commas?

### ISSUE THREAD

**Issue by Suburblicious** [Automattic/WP-Job-Manager#929]
#### What I Expected To Happen
- I am using WP Job Manager with Job tags add-on.
- I have 3 tags from which users can choose (option used is MULTISELECT - list of pre-defined tags) 
- When submitting a job, the employer can choose in those 3 tags
- When admin reviews a job, he should be able to access only those 3 tags

#### What Happened Instead
All goes well in the public site. On the admin level, when admin reviews a job and try to add a tag, partial words are also added in the box.
For example, I add the following tag:
"Études de premier cycle - certificat, baccalauréat"
and when clicking submit, it adds:
"Études de premier cycle - certificat"
"baccalauréat"
All those accumulate in the database and have to be cleaned.

I suspect it is linked to commas being used in the tags. If so, it should be fixed...

#### Steps to Reproduce the Bug

- Define job tags with commas
- Add one of those job tags to a job listing
- You now have junk categories added to the database...

**Comment by jom** [comment]
Closing this as it is related to a plugin outside of WP Job Manager core. For support with the tags plugin or if you are still encountering this issue, please visit: https://wpjobmanager.com/support
