### ISSUE TITLE
Job Filtering by Type doesn't work

### ISSUE THREAD

**Issue by AndreaBacheva** [Automattic/WP-Job-Manager#936]
#### What I Expected To Happen

1) I create a new job type and save it. 
2) I add the job type to a job and save it.
3) When I go on the JOBS page and try to filter by the type I expect to see only results from the chosen type.

#### What Happened Instead

1) I create a new job type and save it. 
2) I add the job type to a job and save it - it also shows the type in the job listing in the admin panel.
3) When I go on the JOBS page and try to filter by the type, it shows seemengly random results.

#### Steps to Reproduce the Bug

1) Create a new job type and save it. 
2) Add the job type to a job and save it.
3) Go on the JOBS page and filter by the type - gives unexpected results.

**Comment by jom** [comment]
I wasn't able to produce with a standard WP theme. Please try clearing transients. Is this with the standard `[jobs]` filter?

![custom-job-type-filter](https://cloud.githubusercontent.com/assets/68693/26051349/d257367e-3959-11e7-8b01-955ed3c5024b.gif)
