### ISSUE TITLE
"Enable types for listings" setting breaks [jobs] shortcode

### ISSUE THREAD

**Issue by d4jeremy** [Automattic/WP-Job-Manager#937]
With regards to [**this issue**](https://wordpress.org/support/topic/two-errors-on-job-listing-page/#post-9069242) raised on the wordpress.org support forums...

I updated WP Job Manager to the latest version (from 1.25.0 to 1.25.3) and it broke the **[jobs]** shortcode.

These are the errors I was getting:

```
Warning: array_values() expects parameter 1 to be array, object given in /home/content/23/10695223/html/wp-content/plugins/wp-job-manager/includes/class-wp-job-manager-shortcodes.php on line 238
```
```
Warning: implode() [function.implode]: Invalid arguments passed in /home/content/23/10695223/html/wp-content/plugins/wp-job-manager/includes/class-wp-job-manager-shortcodes.php on line 238
```

I disabled the 'Enable types for listings' setting and it started to work again, so after a little more investigation, I managed to come up with a quick fix:

In `/wp-content/plugins/wp-job-manager/wp-job-manager-functions.php`, replace the `get_job_listing_types()` function (around line 257) with this:

https://pastebin.com/S5iq9zN6

I haven’t tested this solution extensively, but it seems to have at least restored the functionality of the [jobs] shortcode and is displaying all the jobs and types again, though some of the new settings will probably no longer have any effect.

Essentially, all I did was revert to an older version of the `get_job_listing_types()` function.

**Comment by jom** [comment]
Hi there! I'm unable to reproduce with a fresh install on the most recent version of WordPress. Which version of WordPress are you using? Do you have any caching plugins enabled?

**Comment by d4jeremy** [comment]
WordPress is on version 4.7.4... and here's a list of all the plugins we're using (no caching plugins):

```
Advanced Custom Fields PRO
Version 5.5.12 | By Elliot Condon | View details

Advanced Post Types Order
Version 3.9.7.1 | By Nsp Code | Visit plugin site

Akismet Anti-Spam
Version 3.3 | By Automattic | View details

All-in-One Event Calendar by Time.ly
Version 2.5.19 | By Time.ly Network Inc. | View details

Category Order and Taxonomy Terms Order
Version 1.4.9 | By Nsp-Code | View details

Contact Form 7
Version 4.7 | By Takayuki Miyoshi | View details

Duplicate Post
Version 3.2 | By Enrico Battocchi | View details | Documentation | Donate

Easy Theme and Plugin Upgrades
Version 2.0.0 | By Chris Jean | View details

Envato WordPress Toolkit
Version 1.7.3 | By Envato | Visit plugin site

Eventbrite API
Version 1.0.12 | By Automattic | View details

Keyring
Version 1.8 | By Beau Lebens | View details

LayerSlider WP
Version 5.4.0 | By Kreatura Media | Visit plugin site
	
List Custom Taxonomy Widget
Version 4.1 | By Nick Halsey | View details

Members
Version 1.1.3 | By Justin Tadlock | View details

Open Graph Protocol
Version 1.1.0 | By itthinx | View details

Private Content Login Redirect
Version 1.0.1 | By Kumar Abhisek | View details

Qode Instagram Widget
Version 1.1 | By Qode Themes
	
Qode Twitter Feed
Version 1.0 | By Qode Themes
	
Slider Revolution
Version 5.4.1 | By ThemePunch | Visit plugin site

Toolset Types
Version 2.2.9 | By OnTheGoSystems | View details | Types 2.2.9 release notes

Toolset Views
Version 2.4-b1 | By OnTheGoSystems | Visit plugin site

Widget Content Blocks
Version 2.3.6 | By Danny van Kooten | View details

WP All Export Pro
Version 1.4.6 | By Soflyy | Visit plugin site | Changelog

WP CSV
Version 1.8.0.0 | By CPK Web Solutions | View details

WP Job Manager
Version 1.25.3 | By Automattic | View details

WP User Avatar
Version 2.0.8 | By flippercode | View details | Support Forums

WPBakery Visual Composer
Version 5.1 | By Michael M - WPBakery.com | View details
```

**Comment by d4jeremy** [comment]
I just updated to version 1.26.0, which replaced my 'quick fix' code, and the [jobs] shortcode is working fine again now. 👍
