### ISSUE TITLE
Yoast Sitemap doesn't include the Expired Jobs

### ISSUE THREAD

**Issue by freshersplane** [Automattic/WP-Job-Manager#943]
Hi Team, 

I have been using the wp jobmanager for one of my website. I have small issue and i need to fix it on my site. The issue is ,  i have been using yoast seo plugin and sitemaps generated from it includes only jobs which are not expired. Expired jobs are excluded in the sitemap. Is this issue causing from Jobmanager Plugin? or do i need to do any settings for them to appear in the sitemap?

**Comment by jom** [comment]
Expired job listings are assigned to the `expired` post status. This is probably expected behavior for this plugin. I imagine these plugins are filtering out expired jobs. You would need to write a filter for the sitemap plugin that instructs it to include `expired` job listings.
