### ISSUE TITLE
grid display for jobs

### ISSUE THREAD

**Issue by florinnicola12** [Automattic/WP-Job-Manager#946]
Hi, 

I have a suggestion: please make it possible to display jobs in grid / cards, too. 

Thank you!

**Comment by volodymyrpekh** [comment]
@florinnicola12 This can be achieved with custom theme. No need to overload the plugin with this.

**Comment by florinnicola12** [comment]
How? Which theme?

Pe 2 mai 2017 18:47, "Vlad Pekh" <notifications@github.com> a scris:

**Comment by davoraltman** [comment]
@florinnicola12 You can check the Listify theme - https://listify-demos.astoundify.com/classic/listings/
