### ISSUE TITLE
There is no way to check if I am on WPJM page

### ISSUE THREAD

**Issue by hiendnguyen** [Automattic/WP-Job-Manager#947]
#### What I Expected To Happen
I need something like is_wpjm() (for WooCommerce, it is is_woocommerce()) so that I can dequeue js css for better performance

#### What Happened Instead
All WPJM css js files are loaded even not in "post a job" or "find a job" page

**Comment by jom** [comment]
Creating an enhancement label for the request to add `is_wpjm()`.

Better asset enqueuing is a higher priority enhancement tracked in #657
