### ISSUE TITLE
Check in the blog destination enabled by default

### ISSUE THREAD

**Issue by Tuttopia** [Automattic/WP-Job-Manager#949]
Use Broadcast to propagate WP-job Manage (CPT) and Woocommerce (other CPT) ads from a subsite (child) to the parent site.

The problem is that when I create a product or advertisement automatically (with a snnippet) in a subsite the option of Broadcast to parent is disabled and I have to check on it (on the site I want to broadcast) maually and then refresh the page For the broadcast to take place.

My question is:
Is there a way that the check to the site that I want to broadcast is activated by default so that when making a product or advertisement automatically (with a snippet) it is also automatically propagated without having to manually check on the destination website?

And the second question is: can I broadcast users?  (from one user to another subsite?)

**Comment by jom** [comment]
Hi there! GitHub Issues is for reporting bugs and feature requests. For support, please visit https://wpjobmanager.com/support.
