### ISSUE TITLE
Don't Return Empty String for Google Maps URL

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#951]
```
		// Google Maps API no longer accepts requests without an API key
		if ( '' === $api_key ) {
			return false;
		}
```

This is not true -- sites who have pinged the service before the requirement was put in place do not require a key. 

Also totally resetting the URL to nothing doesn't really make sense. The request should still be made and the API error should be shown to the user when saving the listing.

**Comment by jom** [comment]
Implementation note: Provide instructions for setting API key in error thrown.
