### ISSUE TITLE
Cannot Remove Company Logo

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#952]
#### What I Expected To Happen

Clicking [remove] on the company logo removes the company logo from displaying on a job listing.

#### What Happened Instead

The company logo continues to display.

#### Steps to Reproduce the Bug

1. Add a new job listing with a company logo.
2. Edit job listing via [job_dashboard]
3. Click [remove] below company logo.
4. Save changes.
5. View job listing.
6. Company logo (post thumbnail) still set when viewing in wp-admin.

https://cloudup.com/cu1_GhKZu58
https://cloudup.com/cy5Sm6wUypk
https://cloudup.com/c3iHpcCttyj

**Comment by davoraltman** [comment]
3200168-t
