### ISSUE TITLE
Segregate WPML compatibility code into its own file

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#962]
Move all WPML related code into one file and tie to `wpml_loaded` action (see [Jetpack's implementation as an example](https://github.com/Automattic/jetpack/blob/master/3rd-party/wpml.php)).

Found code:
- [/wp-job-manager.php:#153](https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager.php#L153)
- [/wp-job-manager-functions.php:#49](https://github.com/Automattic/WP-Job-Manager/blob/master/wp-job-manager-functions.php#L49)

**Comment by danjjohnson** [comment]
3224790-t confirmed Polylang fix works :)
