### ISSUE TITLE
Filtering jobs WP Query result

### ISSUE THREAD

**Issue by tomslominski** [Automattic/WP-Job-Manager#965]
Hi,

I'm just wondering whether it would be possible for you to make the WP Query used in get_job_listings() filterable? I see that this is not possible at the moment, even though the $query_args and $args are. Alternatively, is there any way to access that query globally? It would be very useful in themes that use WP Job Manager, where child themes don't have direct access to the results of the query.

**Comment by jom** [comment]
There should be filters (such as `get_job_listings_query_args`) throughout the chain of creating a `WP_Query` in `get_job_listings()` and normal filtering within `WP_Query` itself. The function that creates the query can be called from anyone once the plugin is activated. What would you like to filter that you're unable to using the already existing filters? 

Closing for now, but we can reopen for a specific bug or enhancement request.

**Comment by tomslominski** [comment]
Thanks for your reply. I've got access to actual WP Query results using the `the_posts` filter. However, I don't know which query comes from WP Job Manager, which is the only problem. A filter in the WP JM code would solve that.

I might be looking at this completely the wrong way - all I need is a list of post ID's found in the current query.

Fair enough if it's too niche of a request, I just thought it might be useful!
