### ISSUE TITLE
Sorting options break the featured listings

### ISSUE THREAD

**Issue by sashaza** [Automattic/WP-Job-Manager#971]
#### What I Expected To Happen
I expect that adding basic sorting options to jobs shortcode would keep featured listings at the top of the listings page.

#### What Happened Instead
If I add any sorting option to the jobs shortcode (besides default date added), the featured listings are not sticky anymore. e.g. if I sort listings randomly, the featured listings get mixed up in the list.  

#### Steps to Reproduce the Bug
Use [jobs orderby=rand] with some listings featured. The featured listings will not be sticky anymore.

**Comment by Abulhallaj** [comment]
I have the same problem with WP Job Manager 1.25.3 and Listable theme

**Comment by jom** [comment]
Confirmed. Broke in this commit:
https://github.com/Automattic/wp-job-manager/commit/32fc67f5628eb54da0739ed8ed8a65e9d5981860

For the fix, we'll need to create a custom sorting function.

**Comment by jom** [comment]
See PR #1238, but I'm switching this to an enhancement request as this is currently intended behavior.
