### ISSUE TITLE
AJAX get_listings/ Returns Location and Date in Wrong Language

### ISSUE THREAD

**Issue by chrislp** [Automattic/WP-Job-Manager#973]
I am searching for a Job in English. Primary language is German.
The job is returned in English, but the location is "Überall" (no location is set), it should be "Anywhere".
The date is "Veröffentlich vor 4 Wochen" instead of "Released 4 Weeks ago".

So apparently WP-Job-Manager gets the correct language (Otherwise the Job title and Type wouldn't be in English) but outputs date and location in default language.

I'm using WPML 3.7.0 and WP-Job-Manager 1.25.3 

I guess it's a bug.

![image](https://cloud.githubusercontent.com/assets/186817/26164385/c8b187e4-3b2c-11e7-8c43-2a66aa9d0080.png)

**Comment by spencerfinnell** [comment]
Please test again with version 1.26.0

**Comment by chrislp** [comment]
Thanks for your reply. An upgrade from 1.25.3 -> 1.26.0 doesn't seem to change the AJAX response's language.
