### ISSUE TITLE
Adjust Listing Expiration When Changing Status

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#974]
#### What I Expected To Happen

Changing listing status to "Active" from "Expired"  should actually set the listing as active by adjusting the existing listing expiration based on the original duration set. 

#### What Happened Instead

The listing remains expired because its current expiration date has already passed.

#### Steps to Reproduce the Bug

1. Create a listing with an expiration date in the past.
2. Publish listing. 
3. Set listing to active.

**Comment by jom** [comment]
I agree it is a bit clunky. Is #975 what you were thinking for expected behavior?

**Comment by spencerfinnell** [comment]
Yeah your PR introduces the behavior I would expect.
