### ISSUE TITLE
Enable users to differentiate between different Resumes when applying for a job.

### ISSUE THREAD

**Issue by owbrennan** [Automattic/WP-Job-Manager#976]
Hi,

While testing my setup of WP Job Manager, I've created 3 different Online Resumes.

I currently have the option set to force users to apply using their Online Resumes. When you to go apply for a job, you can choose which Online Resume to apply with, however they all have the same name (i.e. my own name) - see attached.

Is there a way to enable the user to add their own 'Title' in effect to each of the Online Resumes that they create so that they can differentiate between them when applying? This obviously wouldn't display on the actual Online Resume itself.
![screen shot 2017-05-18 at 08 14 04](https://cloud.githubusercontent.com/assets/28688068/26190606/44928aaa-3ba2-11e7-8bd5-204c2cc07927.png)

Kind regards,

Oli

**Comment by owbrennan** [comment]
Is this something that you would consider doing and can you think of a workaround in the mean time?

Thanks.

**Comment by jom** [comment]
Hi there! This is something we've flagged for the applications plugin a higher priority enhancement. We don't have a workaround right now.

**Comment by Lens40** [comment]
Definitely a think to improve especially as it is a paid add-on. A work around might be a custom field for the CV name + adjustment of the templates to show that custom field name instead.

**Comment by owbrennan** [comment]
I agree. I have the knowledge to add the custom field, but which template would I need to update to display it?

Thanks!
