### ISSUE TITLE
Map on preview page doesn't work on multi language site

### ISSUE THREAD

**Issue by rmxs** [Automattic/WP-Job-Manager#981]
#### What I Expected To Happen When i go to submit new listing using listify in preview there is a map displayed with address and contact details, this map works for one language but doesn't work for my other languages.
I'm using polylang and I found that the problem is on settings page under Pages menu.
In that menu you select the new listing page the listing page claim page etc.
If i select German page the map work for German language in preview, if I select English then the map work in English but not for the other languages.

**Comment by jom** [comment]
Hi there! WP Job Manager core does not provide that mapping functionality. Please contact the maker of the theme. There may be some limitations as WPJM retrieves the location data for just the region set via the `job_manager_geolocation_region_cctld` filter.
