### ISSUE TITLE
Search function -No boolean- keyword not keywordS

### ISSUE THREAD

**Issue by TPaffett** [Automattic/WP-Job-Manager#989]
Trying to get your keyword search for jobs to work correctly; it only does single keywords, not multiple;

For example

Search: 
Linux, C++, Python 
will Returns nothing.  

However individual keyword searches will return jobs? What use is this?

**Comment by spencerfinnell** [comment]
Have you tried the latest `master` branch?

https://github.com/Automattic/WP-Job-Manager/issues/894

**Comment by TPaffett** [comment]
No I haven't Ill have a look into it, thanks :)

**Comment by TPaffett** [comment]
Spencerfinnell: Thanks, works perfectly!!! (so far;)) :D
