### ISSUE TITLE
Removing certain form fields

### ISSUE THREAD

**Issue by kb6673** [Automattic/WP-Job-Manager#99]
I'm using the `submit_job_form_fields` hook to successfully remove some fields from the front end job form.

I can remove `company_twitter` and `company_logo`

However I can't remove `company_google` and `company_facebook`
They aren't listed in https://github.com/mikejolley/WP-Job-Manager/blob/v1.2.0/includes/forms/class-wp-job-manager-form-submit-job.php#L101

Where are they added? Or where can I remove them?

**Comment by IgalNeeman** [comment]
Hi , how can i remove it ? 
i try to remove it and i cant !! please help me
WP job manager 
all of this fiels in job submition when i want to add job to my website (post job)
i want to remove this fields and i cant , i try use code snippet and not work for me,
please i need any help 
here is the screen shot i want to remove all of this inputs

![Image](https://github.com/user-attachments/assets/8e5d6516-b90c-4439-b257-850440315b3d)
