### ISSUE TITLE
Using the Relist link from an expired job does not relist the job. 

### ISSUE THREAD

**Issue by Rancheria** [Automattic/WP-Job-Manager#990]
#### What I Expected To Happen
Click on the relist button from the Job dashboard (end user side) I expect to be brought into the job posting to update the expiration date and status. 

#### What Happened Instead
Click on the relist button and it just redirects to the listing page without any changes.
#### Steps to Reproduce the Bug
Go to the job dashboard. In the listings click on the relist link.

**Comment by jom** [comment]
I'm not able to reproduce. If you're still able to reproduce this issue, please post more information (including your active theme and a list of your plugins).

**Comment by capsulebb** [comment]
I am also having the same issue, when clicked on the Relist button for an expired job, it redirects to the homepage without extending the expiry date. There is no paying option for my site, all Job Manager related plugins I have are Field Editor, Bookmarks, Tags with Listable theme. The problem persists even switched to Twenty Nineteen theme.

**Comment by johnRSD** [comment]
Did this ever get resolved? Currently having the same issues. This is the only thread I've found on the subject. Thanks.

**Comment by johnRSD** [comment]
My WPJM pages are set up to the proper pages. Currently the only page not set up is the Terms and Conditions page (which is disabled in the Job Submission settings). Each page used is set to the simplest WPJM shortcode available for the corresponding pages with the exception of the Jobs page that uses `[jobs orderby="modified"]`.

**Comment by johnRSD** [comment]
@dericleeyy That worked! Thank you for your help!

**Comment by lxmultimedia** [comment]
hello. here it is not working too. We have the "Post a Job" page correct set up in the settings. There is only this shortcode there "[submit_job_form]".

Today one client tried to relist an expired listing. He paid and a woocommerce order has been made, he has been charged.

But the listing was not relisted, it was still expired and not visible after payment.
