### ISSUE TITLE
Specified job location is set to "anywhere" when creating a new job listing

### ISSUE THREAD

**Issue by hafix86** [Automattic/WP-Job-Manager#991]
**What I Expected To Happen**
Usually, when creating a new job listing and adding a location, it will be listed showing up the appropriate city that has been typed (or was complemented by Auto Location). 

**What Happened Instead**
Now, when creating a new job, it is listed as "anywhere" after being published. So, for example I insert "Berlin" and the ouput is "everywhere" - no matter which location will be used. 
Furthermore, by comparing the new faulty job listings with the older ones, I found out that the following  custom fields are missing: geolocated, geolocation_city, geolocation_country_long, geolocation_country_short, geolocation_formatted_address, geolocation_lat, geolocation_long, geolocation_state_long,geolocation_state_short

The problem can be fixed by adding the missing fields and the input data manually. It seems that those are not generated when creating the job listing. The problem occured after updating to the latest version (1.26.0)

**Steps to Reproduce the Bug**
Add a new job listing containing a certain job location (city), save it and check the job location that has been published.

**Comment by hafix86** [comment]
I manually downgraded from 1.26.0 back to 1.25.3 - everything's fine again. 
Won't do that update again :-p

**Comment by spencerfinnell** [comment]
Add your Google Maps API key to Job Listings > Settings.

@jom https://github.com/Automattic/WP-Job-Manager/issues/951

**Comment by hafix86** [comment]
Oh, I didn't know that the API key gets lost by performing an update. Actually I am glad that the job board is running again without any problems. I'll check that out some day.

**Comment by spencerfinnell** [comment]
It's not lost, it's a new setting.

**Comment by RiaanKnoetze** [comment]
Even with a Google Maps API key, those meta fields are not populating for me :)

**Comment by RiaanKnoetze** [comment]
**Update**: Google made some changes; Had to enable the _Google Maps Geocoding API_ library before meta fields will be populated.

**Comment by moltra** [comment]
How did you reenable the Google Maps Geocoding API library?  are you doing this on the console.developers.google.com site?  Or someplace else.

**Comment by RiaanKnoetze** [comment]
> are you doing this on the console.developers.google.com site?

Yep, it's on Google's side :)

**Comment by spencerfinnell** [comment]
Set any Referrer restrictions to "None" on your API key. Enable "Google Maps Geocoding API". Add your key in Job Listings > Settings.

**Comment by johnwainer** [comment]
I'm having the same problem, I'm using Version 1.31.0 of the WP Job Manager, I inserted the Google Maps API and removed the restrictions, but I still get "Anywere" when I entered some Locations, like "Miami, FL"

**Comment by richardmtl** [comment]
@johnwainer Can you start a new thread in the WPJM support forum, please? If we determine that your issue is a new bug, we'll open up a new issue here. Thanks!

https://wordpress.org/support/plugin/wp-job-manager/

**Comment by steelhelmet** [comment]
same issue

**Comment by richardmtl** [comment]
@steelhelmet my advice is the same:

Can you start a new thread in the WPJM support forum, please? If we determine that your issue is a new bug, we'll open up a new issue here. Thanks!

https://wordpress.org/support/plugin/wp-job-manager/

However, if you have paid for some of our extensions, you can also get email support here:

https://wpjobmanager.com/support/
