### ISSUE TITLE
Apply button active if job submitted backend; but not if submitted frontend?

### ISSUE THREAD

**Issue by TPaffett** [Automattic/WP-Job-Manager#992]
I have just noticed, if I submit a job via the website, theres no apply button at the bottom, however if I manually add the job from the WP backend, it comes up with the apply button.... :/ 

![screen shot 2017-05-24 at 11 03 29](https://cloud.githubusercontent.com/assets/28857660/26398201/b14e00a2-4070-11e7-9e52-37fb8d1645ef.png)
Web page submitted job

![screen shot 2017-05-24 at 11 03 43](https://cloud.githubusercontent.com/assets/28857660/26398216/b9760018-4070-11e7-8e5b-208061571592.png)
Manually added job via the wordpress backend.

I have searched but can't find anything that could have caused the problems (although this morning I did have 403 issues with both my sites so I wonder if that could be a cause?)

**What I Expected To Happen**

Submit job via website; job appear on website with fields (description etc) and an apply button

**What Happened Instead**

Submitted via website; no apply button visible.

**Steps to Reproduce the Bug**

Submit job via website instead of back end, no apply button will appear.

Any help appreciated. :)

**Comment by spencerfinnell** [comment]
Is there a contact email or URL provided when submitting?

**Comment by TPaffett** [comment]
Not on the front end, only the back, it should display from a "contact 7" form.

**Comment by TPaffett** [comment]
Sorted!, I need to leave the front non-admin on the application URL. Thanks again Spencer, If you're ever in London, I owe you a beer (or two).

**Comment by harabidi** [comment]
Hello guys !!! I have the same problem , but i can't resolved , you edit the job-application.php ??

**Comment by tripflex** [comment]
@harabidi no you need to make sure that you have NOT disabled the `application` field from showing on the frontend.  That field MUST have a value saved to it for the Apply Now button to show on the frontend.

IF a listing does not show the Apply Now button, edit that listing as admin from the backend, and check if it has a value for the `application` meta key field

**Comment by harabidi** [comment]
thanks for answer, 
the code of the input looks like this 
`<input type="button" class="application_button button" value="<?php _e( 'Apply for job', 'wp-job-manager' ); ?>" />` ,i don't understand what logic it follows, help please !!
