### ISSUE TITLE
Deep Linkable Settings Tabs

### ISSUE THREAD

**Issue by spencerfinnell** [Automattic/WP-Job-Manager#993]
#### What I Expected To Happen

I should be able to link directly to a "Settings" tab.

#### What Happened Instead

I can only ever link to the first tab.

---

It would be nice to have some JS in place to detect a hash and switch tabs automatically when the page loads.

**Comment by tripflex** [comment]
I agree, I had to add my own javascript to handle it based on hash for settings, so just ported that over to core, just submitted a PR
