### ISSUE TITLE
Time zone issue in when setting client-side job listing expiration

### ISSUE THREAD

**Issue by jom** [Automattic/WP-Job-Manager#994]
See: https://github.com/Automattic/WP-Job-Manager/issues/869#issuecomment-303747326

#### What I Expected To Happen
When setting the expiration date for a job listing in WP Admin, the browser may convert the date should be timezone agnostic. 

#### What Happened Instead
When setting the expiration date for a job listing in WP Admin, the browser may convert the date to UTC. 

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

For some history, see: https://github.com/Automattic/WP-Job-Manager/issues/869#issuecomment-303747326

**Comment by spencerfinnell** [comment]
Looks like a quick fix is to set the minutes in the date format so the `datepicker` plugin does not try to calculate that itself. 

`'value'       => date( 'Y-m-d H:i:s', strtotime( get_post_meta( $post->ID, '_job_expires', true ) ) )`

**Comment by jom** [comment]
I can confirm that seems to fix it... PR on the way.
