### ISSUE TITLE
Support for my website

### ISSUE THREAD

**Issue by nikolacvetkoski** [Automattic/WP-Job-Manager#996]
Hello,
We have bought Jobify theme with the WP-Job-Manager plugin and installed it on this url http://mechatronian.com/
On the homepage where it says Career Mechatronians is Resume manager widget for featured resumes and I want to ask it is you that we need to talk about the drop shadows on the featured images on the homepage. On the demo theme there is shadow but on our there is not, is there a setting that we are missing?
Best regards,
Nikola

**Comment by volodymyrpekh** [comment]
Hey @nikolacvetkoski,

This is not the right place. Please go to theme support page - https://themeforest.net/item/jobify-wordpress-job-board-theme/5247604/support

Thanks
